### ISSUE TITLE
6.5.0 on Trestles at SDSC

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#100]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/100*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:23*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by xiangni** [comment]
*Original date: 2013-03-28 05:52:06*

---
/build AMPI mpi-linux-x86_64 smp --suffix=icc-debug -j8 -g
/build AMPI mpi-linux-x86_64 smp --suffix=icc-devel -j8  --disable-error-checking -optimize
/build AMPI mpi-linux-x86_64 smp --suffix=icc-production -j8 --with-production
/build AMPI mpi-linux-x86_64 --suffix=icc-debug-non-smp -j8 -g
/build AMPI mpi-linux-x86_64 --suffix=icc-devel-non-smp -j8 --disable-error-checking -optimize 
/build AMPI mpi-linux-x86_64 --suffix=icc-production-non-smp -j8 --with-production

**Comment by xiangni** [comment]
*Original date: 2013-03-28 06:32:43*

---
module purge
module load gnu openmpi

/build AMPI mpi-linux-x86_64 smp --suffix=gcc-debug -j8 -g
/build AMPI mpi-linux-x86_64 smp --suffix=gcc-devel --disable-error-checking -j8 -optimize 
/build AMPI mpi-linux-x86_64 smp --suffix=gcc-production -j8 --with-production
/build AMPI mpi-linux-x86_64 --suffix=gcc-debug-non-smp -j8 -g
/build AMPI mpi-linux-x86_64 --suffix=gcc-devel-non-smp --disable-error-checking -j8 -optimize 
/build AMPI mpi-linux-x86_64 --suffix=gcc-production-non-smp -j8 --with-production

**Comment by xiangni** [comment]
*Original date: 2013-03-28 07:09:24*

---
pgcc with mpi build is broken. pgcc with ibverbs build fails in nightly build.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 17:26:06*

---
Please open an issue with the details of the pgcc mpi breakage.

What's the path for the builds that did succeed?

**Comment by xiangni** [comment]
*Original date: 2013-03-28 18:55:02*

---
The successful build using icc and gcc is in /home/xiangni2/build/charm

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 20:54:15*

---
The pgcc issues should be resolved on the charm-6.5 branch. Could you do the remaining build against that?

**Comment by xiangni** [comment]
*Original date: 2013-04-01 16:52:48*

---
module purge
module load pgi mvapich2
/build AMPI mpi-linux-x86_64 smp --suffix=pgcc-debug -j8 -g
/build AMPI mpi-linux-x86_64 smp --suffix=pgcc-devel --disable-error-checking -j8 -optimize 
/build AMPI mpi-linux-x86_64 smp --suffix=pgcc-production -j8 --with-production
/build AMPI mpi-linux-x86_64 --suffix=pgcc-debug-non-smp -j8 -g
/build AMPI mpi-linux-x86_64 --suffix=pgcc-devel-non-smp --disable-error-checking -j8 -optimize 
/build AMPI mpi-linux-x86_64 --suffix=pgcc-production-non-smp -j8 --with-production

**Comment by PhilMiller** [comment]
*Original date: 2013-04-01 17:04:31*

---
Esteban, could you log in to Trestles and confirm that those paths are accessible to you? When that's done, please close this issue.

**Comment by pplimport** [comment]
*Original author: Esteban Meneses*
*Original date: 2013-04-08 21:50:05*

---
   They are accessible.
