### ISSUE TITLE
Changa's Final CkWaitQD() hangs after AtSync deletion-counting changes

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1002]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1002*

---
ChaNGa will hang at the final CkWaitQD() when run with 2 or 4 processors.  Repeat (with gcc 5.3.2)

build ChaNGa netlrs-linux-x86_64

In ChaNGa: ./configure; make
cd teststep
../charmrun +p 2 ../ChaNGa -n 0 test_pg.param

Note that this final CkWaitQD() at the end of Main::doSimulation() is there to help with memory leak detection.  It could be deleted (along with the treeProxy.ckDestroy() before it.

**Comment by trquinn** [comment]
*Original date: 2016-03-04 03:20:37*

---
Adding a load balancer gives an interesting result.
../charmrun +p 2 ++local ../ChaNGa -n 0 +balancer RefineLB +LBDebug 1 test_pg.param
will produce a large number of load balancing messages after the program is supposed to have finished:

....
Calculating gravity (theta = 0.700000) ... Calculating gravity and SPH took 2.3
47479 seconds.
Calculating total densities ... took 0.586102 seconds.
Reordering ... took 0.037478 seconds.
Outputting densities ... took 0.027045 seconds.
Outputting hsmooth ...Outputting accelerations  ...Done.

******************


CharmLB> RefineLB: PE [0] step 1 starting at 0.541986 Memory: 1.626465 MB
CharmLB> RefineLB: PE [0] strategy starting at 3.816033
dMinOverload: 1.050000 dMaxOverload: 2.010000
Testing curOverload 48 = 1.530000 [min,max]= 0, 96
Testing curOverload 72 = 1.770000 [min,max]= 48, 96
Testing curOverload 84 = 1.890000 [min,max]= 72, 96
Testing curOverload 90 = 1.950000 [min,max]= 84, 96
Testing curOverload 93 = 1.980000 [min,max]= 90, 96
Testing curOverload 94 = 1.990000 [min,max]= 93, 96
Testing curOverload 95 = 2.000000 [min,max]= 94, 96
CharmLB> RefineLB: PE [0] Memory: LBManager: 920 KB CentralLB: 1 KB
CharmLB> RefineLB: PE [0] #Objects migrating: 0, LBMigrateMsg size: 0.00 MB
CharmLB> RefineLB: PE [0] strategy finished at 3.816541 duration 0.000508 s
CharmLB> RefineLB: PE [0] step 1 finished at 3.817777 duration 3.275791 s


CharmLB> RefineLB: PE [0] step 2 starting at 3.818001 Memory: 1.626785 MB
CharmLB> RefineLB: PE [0] strategy starting at 3.818247
dMinOverload: 1.050000 dMaxOverload: 2.010000
Testing curOverload 48 = 1.530000 [min,max]= 0, 96
Testing curOverload 72 = 1.770000 [min,max]= 48, 96
Testing curOverload 84 = 1.890000 [min,max]= 72, 96
Testing curOverload 90 = 1.950000 [min,max]= 84, 96
Testing curOverload 93 = 1.980000 [min,max]= 90, 96
Testing curOverload 94 = 1.990000 [min,max]= 93, 96
Testing curOverload 95 = 2.000000 [min,max]= 94, 96
CharmLB> RefineLB: PE [0] Memory: LBManager: 920 KB CentralLB: 1 KB
CharmLB> RefineLB: PE [0] #Objects migrating: 0, LBMigrateMsg size: 0.00 MB
CharmLB> RefineLB: PE [0] strategy finished at 3.818773 duration 0.000526 s
CharmLB> RefineLB: PE [0] step 2 finished at 3.819922 duration 0.001921 s

And so on ad infinitum.

**Comment by trquinn** [comment]
*Original date: 2016-03-05 06:30:36*

---
I tried this with charm 6.7.0, and the problem went away.  "git bisect" tells me:

07e2a189b3b1560655bcfd689499f991b0122f7a is the first bad commit
commit 07e2a189b3b1560655bcfd689499f991b0122f7a
Author: Phil Miller <mille121`illinois.edu>
Date:   Mon Feb 15 12:02:19 2016 -0800

    LBDBManager: Check whether deleting an object lets the AtSync() barrier proceed
    
    Change-Id: Ib77c2fcdbbfb868380716e7cc34e3a47875eb03a

**Comment by PhilMiller** [comment]
*Original date: 2016-03-05 23:38:08*

---
Yeah, when Harshitha and I made that change, we apparently didn't consider what would happen if all objects were deleted everywhere, and QD were to be used.

Should there maybe be a guardrail in the AtSync code to somehow pause when there are no objects anywhere?

**Comment by PhilMiller** [comment]
*Original date: 2016-03-10 18:56:37*

---
Retitle to actually be informative.

**Comment by harshithamenon** [comment]
*Original date: 2016-03-16 05:13:00*

---
There are couple of reasons for this hang.

The main reason is that AtSync is triggered when all the elements are destroyed. This is because when elements are destroyed, we need to check whether this enables AtSync local barrier to become active. In this case for ChaNGa this is caused at the end of the run. But we don't know whether it is the end of the program or more elements are going to be created in future. 

Few changes required are 

-ChaNGa needs to destroy the whole array including the elements and the location manager. To do that CProxy_CkArray(treeProxy.ckGetArrayID()).ckDestroy(); needs to be called.
-This showed a bug in deletion of location manager.https://charm.cs.illinois.edu/redmine/issues/1011
-Even after all this, the qd still hangs for reasons unknown.
-Even if the qd doesn't hang, the batsyncer will cause local barrier AtSync to be activated. This may require another change in the AtSync logic.

**Comment by harshithamenon** [comment]
*Original date: 2016-03-16 19:54:20*

---
Changes that fixes these are 
~~https://charm.cs.illinois.edu/gerrit/#/c/1114/~~ https://github.com/UIUC-PPL/charm/commit/5a92b2880d91e5108d34782a77b151143c22aa54
~~https://charm.cs.illinois.edu/gerrit/#/c/1113/~~ https://github.com/UIUC-PPL/charm/commit/53819195252795af1c2722595c404d22bc1aa101
https://charm.cs.illinois.edu/gerrit/#/c/1115/

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 19:31:31*

---
Changes mentioned were all merged. Tom, is the reported issue resolved?

**Comment by PhilMiller** [comment]
*Original date: 2016-11-25 21:32:42*

---
Pinged change 1115 to ChaNGa, hopefully Tom can clear this up for us.

**Comment by trquinn** [comment]
*Original date: 2016-11-26 04:36:55*

---
The original (somewhat incorrect) changa code now runs without hanging with the latest charm branch.  However, there is now a changa changeset to comment this code alltogether since it is only used to debug memory leaks.

**Comment by stwhite91** [comment]
*Original date: 2017-04-04 20:50:48*

---
Closing unless there are any objections...
