### ISSUE TITLE
6.5.0 on Stampede and Lonestar at TACC

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#101]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/101*

---
No body.

**Comment by rbuch** [comment]
*Original date: 2013-03-26 23:52:47*

---
Still don't have working Stampede access, have been in contact with XSEDE and TACC to get it.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-27 00:01:13*

---
Please reassign to someone who does, then.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:24*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.
