### ISSUE TITLE
+setcpuaffinity +showcpuaffinity doesn't actually print the affinity settings

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1010]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1010*

---
+pemap 0-15 +setcpuaffinity prints affinity information but +setcpuaffinity +showcpuaffinity doesn't

**Comment by jcphill** [comment]
*Original date: 2016-03-11 02:57:21*

---
Make that "+pemap 0-15 +showcpuaffinity" prints affinity information...

**Comment by ericjbohm** [comment]
*Original date: 2018-03-14 19:16:59*

---
Was fixed by Evan's work.

**Comment by ericjbohm** [comment]
*Original date: 2018-03-14 19:18:00*

---
since resolved ins't closed, we choose closed
