### ISSUE TITLE
Replace deprecated auto_ptr with unique_ptr in generated SDAG code

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1012]
*Original author: Laura Silva Lopes*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1012*

---
I had a problem yesterday compiling charm++ 6.7.0 to use it for NAMD 2.11. This problem appears at the compilation as a warning, but the compilation ends normally.

CkIO_impl.decl.h:845:35: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]

When testing the compilation with pgm this error appears again. I'm reporting this because one NAMD user had the same problem:
https://lists.cs.illinois.edu/lists/arc/charm/2016-03/msg00000.html 

It turns out auto_ptr is deprecated in gcc latest versions and should be replaced by unique_ptr.
http://stackoverflow.com/questions/2404115/is-auto-ptr-deprecated

Doing a recursive grep in charm source code I found this function only in one file:
src/xlat-i/sdag/CParsedFile.C:109:  decls << "  std::auto_ptr<SDAG::Dependency> __dep;\n";

I just replaced auto_ptr by unique_ptr and compiled normally. After I managed to compile and run NAMD without any problem!

Hope this is going to be useful!

**Comment by stwhite91** [comment]
*Original date: 2016-03-17 13:59:41*

---
This is just a warning so NAMD and Charm++ run fine with it.

We continually re-evaluate C++ compiler support to decide which features of modern C++ we can use portably. It looks like unique_ptr was not implemented in GCC until v4.4, and as of last year we still had users stuck using v4.3. (See the discussion here: https://charm.cs.illinois.edu/redmine/issues/740). We will look into this again and fix this particular issue in a future release.

**Comment by stwhite91** [comment]
*Original date: 2016-11-20 22:26:35*

---
After 6.8.0 we are going to require full C++11 support from compilers, so this can be changed to unique_ptr after the release.

**Comment by stwhite91** [comment]
*Original date: 2016-11-28 22:56:20*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2002/~~ https://github.com/UIUC-PPL/charm/commit/a15b823b27eb84118ba8ca965138b850940acb10

**Comment by PhilMiller** [comment]
*Original date: 2016-11-28 23:08:33*

---
The fix linked above depends on libstdc++ corresponding to GCC 4.4+, but that should be fine now. We've merged some other changes that require it a couple months back (see #1228), and gotten no complaints.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 03:10:17*

---
Had to jump through some hoops to stick with auto_ptr on BG XLC, since it can't handle the bits of C++11 support in GCC 4.4's libstdc++. Everywhere else, we're using unique_ptr as desired.
