### ISSUE TITLE
6.5.0 on Taub

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#102]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/102*

---
No body.

**Comment by bilgeacun** [comment]
*Original date: 2013-03-26 01:14:04*

---
Charm++ is built with;
* net-linux-x86_64 arch 
* icc and gcc compilers 
* 3 different options; debug: "-g", trace: "--disable-error-checking -optimize" and production: "--with-production"
* 2 versions; smp and non-smp 

Charm++ is NOT BUILT, when building with trace: "--disable-error-checking -optimize" option, both in icc and gcc compilers, both smp and non-smp versions.
In all other versions Charm++ built successfully.

Other than some AMPI fails which is reported in another bug report, all of the autobuild tests passes on Taub.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-26 01:28:56*

---
"Charm++ is NOT BUILT, when building " - you mean there is a compilation error? If yes, please open a new bug with necessary information, and crash report.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-27 15:37:49*

---
Great - what's the path that I can announce to users?

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:24*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by bilgeacun** [comment]
*Original date: 2013-03-28 13:50:18*

---
The path is /home/acun2/charm on Taub, now it builds with --disable-error-checking option, however issue #133 is still there.
