### ISSUE TITLE
testrun script divides by zero

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1022]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1022*

---

```
../../../bin/testrun  ./hello +p8 +restart log  ++local
expr: division by zero
```

https://charm.cs.illinois.edu/autobuild/cur/netlrts-darwin-x86_64.txt
Tests don't seem to be failing because of this, but it's certainly ugly.

**Comment by bilgeacun** [comment]
*Original date: 2016-03-31 20:30:32*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1123/~~ https://github.com/UIUC-PPL/charm/commit/d7528dd6d5cd1179550fb69fe9c144572e224acf
