### ISSUE TITLE
win64 fails to find the testrun script in autobuild

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1028]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1028*

---
mpi-win64 and multicore-win64 are failing with this error on the first test they try:

../../../../bin/testrun  +p1 ./check  
Makefile:25: recipe for target 'test' failed
make[2]: Leaving directory '/home/nikhil/autobuild/multicore-win64/charm/multicore-win64/tests/util'
Makefile:13: recipe for target 'test' failed
make[1]: Leaving directory '/home/nikhil/autobuild/multicore-win64/charm/multicore-win64/tests'
Makefile:149: recipe for target 'test' failed
fatal> error code 2 during remote> make test
make[2]: ../../../../bin/testrun: Command not found

**Comment by stwhite91** [comment]
*Original date: 2016-04-08 18:28:01*

---
This fixed another issue for VC++: ~~https://charm.cs.illinois.edu/gerrit/#/c/1136/~~ https://github.com/UIUC-PPL/charm/commit/c4f6e3799ede07b59b426565afeaf0aedb0db557

But net-win64, mpi-win64, and multicore-win64 tests all still fail to find the testrun script.

**Comment by PhilMiller** [comment]
*Original date: 2016-06-03 18:17:57*

---
Got a fix built. ~~https://charm.cs.illinois.edu/gerrit/1236~~ https://github.com/UIUC-PPL/charm/commit/e82575a78ecca6708d704eff4f69629f535b6d1b
