### ISSUE TITLE
icc and iccstatic builds fail with icpc 16.0.2

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1032]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1032*

---
./build charm++ netlrts-linux-x86_64-icc --no-build-shared --with-production

...

../bin/charmc  -optimize -production   -I.   -c -o ckreduction.o ckreduction.C
In file included from charm++.h(978),
                 from ckreduction.C(50):
ckreduction.h(213): warning #3495: rvalue references are a C++11 feature
          tupleElement(CkReduction::tupleElement&& rhs_move);
                                                ^

ckreduction.C(1940): error #303: explicit type is missing ("int" assumed)
      const auto& reducerFp = CkReduction::reducerTable[reducerType].fn;
                ^

ckreduction.C(1940): error: a value of type "CkReduction::reducerFn" cannot be used to initialize an entity of type "const int &"
      const auto& reducerFp = CkReduction::reducerTable[reducerType].fn;
                              ^

ckreduction.C(1941): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
      CkReductionMsg* result = reducerFp(num_messages, simulated_messages);
                               ^

compilation aborted for ckreduction.C (code 2)
Fatal Error by charmc in directory /home/jphillip/charm/netlrts-linux-x86_64-icc/tmp
   Command icpc -fpic -I../bin/../include -D__CHARMC__=1 -I. -O3 -U_FORTIFY_SOURCE -fno-stack-protector -c ckreduction.C -o ckreduction.o returned error code 2
charmc exiting...
gmake: *** [ckreduction.o] Error 1

**Comment by jcphill** [comment]
*Original date: 2016-04-12 14:50:17*

---
[jphillip`br005 charm]$ icpc --version
icpc (ICC) 16.0.2 20160204
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

This is on PSC bridges.

**Comment by stwhite91** [comment]
*Original date: 2016-04-12 16:13:45*

---
The issue stems from this commit: ~~https://charm.cs.illinois.edu/gerrit/#/c/1116/~~ https://github.com/UIUC-PPL/charm/commit/b43c918a03e4808109805a18688f9e48754a1850

That patch will not be in the 6.7.1 release since it is a feature, but for 6.8.0 we need to at least make the build system detect and set the right C++11 flags, like '--std=c++11' for ICC.

See the discussion on this commit: ~~https://charm.cs.illinois.edu/gerrit/#/c/1132/~~ https://github.com/UIUC-PPL/charm/commit/83a0d8191fb00d9a394b87f5b070633d935e828e

**Comment by stwhite91** [comment]
*Original date: 2016-04-13 17:29:47*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1140/~~ https://github.com/UIUC-PPL/charm/commit/74d557865fe02b5d52a60891c40d48e8de733620

**Comment by stwhite91** [comment]
*Original date: 2016-04-13 22:16:23*

---
Steve Hoelle doesn't seem to have Redmine set up yet, so I can't assign this to him, but the above commit of his fixes the issue.
