### ISSUE TITLE
Bad free in LtrsExit()

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1033]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1033*

---
Starting with commit 4667d328c13e2eedcb03307e1d3074dc52bb41ea, using charm to compile ChaNGa and running the "teststep" test on an SMP machine will cause an abort() due to a bad free.  The traceback says:
```
#0  0x00002aaaabd21875 in raise () from /lib64/libc.so.6
#1  0x00002aaaabd22e51 in abort () from /lib64/libc.so.6
#2  0x00002aaaabd628bf in __libc_message () from /lib64/libc.so.6
#3  0x00002aaaabd680c8 in malloc_printerr () from /lib64/libc.so.6
#4  0x00002aaaabd69e4e in _int_free () from /lib64/libc.so.6
#5  0x00002aaaabd6d10c in free () from /lib64/libc.so.6
#6  0x00002aaaabd24681 in __run_exit_handlers () from /lib64/libc.so.6
#7  0x00002aaaabd246a5 in exit () from /lib64/libc.so.6
#8  0x000000000079c499 in LrtsExit ()
#9  0x000000000079c4d8 in CommunicationServer.isra.32 ()
#10 0x000000000079c7b1 in ConverseRunPE ()
#11 0x000000000079c846 in call_startfn ()
```

This is with the verbs-linux_x86 smp build on an Ivybridge (20 core) host compiled with gcc 4.9.3

**Comment by PhilMiller** [comment]
*Original date: 2016-04-13 21:51:17*

---
If this is the result of earlier heap corruption leading to other breakage at exit time, ~~https://charm.cs.illinois.edu/gerrit/#/c/1142/~~ https://github.com/UIUC-PPL/charm/commit/1e4157cd1b6641c1e7d6f98c96afb847c65c88831 may in fact fix it.

**Comment by stwhite91** [comment]
*Original date: 2016-04-14 16:15:42*

---
The above fix has been merged.

**Comment by PhilMiller** [comment]
*Original date: 2016-04-14 16:49:32*

---
Tom: Please confirm that with this fix, your reported crash is resolved. When we get that, we can close this issue.

**Comment by trquinn** [comment]
*Original date: 2016-04-14 17:18:53*

---
With Commit ID: v6.7.0-140-g046e8f9, I no longer get the crash.
