### ISSUE TITLE
Constant comparison warnings from xlC compiler

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1034]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1034*

---

ck.C:2692:22: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (e->getSrcPe()<0 || e->getSrcPe()>=CkNumPes()+CkNumNodes()) return 0;
        ~~~~~~~~~~~~~^~

ckarray.C:267:12: warning: address of array 'info.listenerData' will always evaluate to 'true'
      [-Wpointer-bool-conversion]
  if (info.listenerData) {
  ~~  ~~~~~^~~~~~~~~~~~

ckarrayreductionmgr.C:133:19: warning: comparison of constant \-1 with expression of type 'unsigned short' is
      always true [-Wtautological-constant-out-of-range-compare]
                        if (m->userFlag!=-1)
                            ~~~~~~~~~~~^ ~~

**Comment by sbak5** [comment]
*Original date: 2016-07-31 05:50:59*

---
Can you write down some details of the environment where you found this bug? I tried to build charm++ on ANL Mira(BG/Q) by using xlc but I didn't encounter this bug. 
The following is the build option I tried on Mira.

./build charm++ pamilrts-bluegeneq xlc --with-production.

**Comment by jcphill** [comment]
*Original date: 2016-09-12 21:47:00*

---
It would have been an SMP build.

**Comment by stwhite91** [comment]
*Original date: 2018-02-09 15:59:32*

---
A Charmworks intern is looking into this.

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 06:04:06*

---
He said these warnings have been taken care of or the code they were in was removed.
