### ISSUE TITLE
Add support for srun to charmrun script for gni layer

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#1038]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1038*

---
Charmrun for gni layer calls either *aprun* or *mpirun*. Edison switched using *srun* therefore charmrun needs to test for *srun* as well. 
Autobuild tests fail because of this problem.

**Comment by mprobson** [comment]
*Original date: 2016-05-05 19:21:58*

---
From Core: Attack problem by just failing over to srun if aprun and mpirun both fail to run

**Comment by mprobson** [comment]
*Original date: 2016-06-09 18:58:17*

---
Implemented and testing a fix

**Comment by mprobson** [comment]
*Original date: 2016-06-23 21:31:35*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1292/~~ https://github.com/UIUC-PPL/charm/commit/887ea48a0801dea30ee192cf66a8eda444ab3fb6

**Comment by PhilMiller** [comment]
*Original date: 2016-06-26 15:00:03*

---
Getting there, but still not quite:

```
make[3]: Leaving directory `/scratch1/scratchdirs/acun/autobuild/gni-crayxc/charm/gni-crayxc/examples/collide/collidethread'
make[2]: Leaving directory `/scratch1/scratchdirs/acun/autobuild/gni-crayxc/charm/gni-crayxc/examples/collide'
make[1]: Leaving directory `/scratch1/scratchdirs/acun/autobuild/gni-crayxc/charm/gni-crayxc/examples'
Submitting batch job for> make test OPTS=
 using the command> sbatch /scratch1/scratchdirs/acun/autobuild/gni-crayxc/charmrun_script.19109.sh
Job enqueued under job ID Submitted batch job 722369
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
squeue: error: Invalid job id: Submitted
autobuild> too many errors, abort!
fatal> error code 1 during remote> ./instead_test.sh charm/gni-crayxc/tmp make  test 
Returned from executing scripts/gni-crayxc/test on remote host
fatal> Test on remote host failed with fatal error (0)
```

Looks like it's mis-parsing the job ID out of the `sbatch` output.

**Comment by stwhite91** [comment]
*Original date: 2016-08-09 14:26:51*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1343/~~ https://github.com/UIUC-PPL/charm/commit/292b7d3c5964e505179eaa9ef61f034102b58259

**Comment by stwhite91** [comment]
*Original date: 2016-08-10 13:41:28*

---
Now the error is this:
```
Submitting batch job for> make test OPTS=
 using the command> sbatch /scratch1/scratchdirs/acun/autobuild/gni-crayxc/charmrun_script.17216.sh
Job enqueued under job ID Submitted batch job 1732462
squeue: error: Invalid job id: Submitted
cat: /scratch1/scratchdirs/acun/autobuild/gni-crayxc/charmrun_script.17216.stdout: No such file or directory

```

**Comment by stwhite91** [comment]
*Original date: 2016-08-25 13:42:05*

---
Issue is fixed for gni-crayxc but gni-crayxc-smp has a parsing issue in ./instead_test.sh:

```
Submitting batch job for> make test OPTS=
 using the command> sbatch /scratch1/scratchdirs/acun/autobuild/gni-crayxc-smp/charmrun_script.7180.sh
./instead_test.sh: command substitution: line 71: syntax error near unexpected token `|'
./instead_test.sh: command substitution: line 71: `cat .status.$$ | tail -1 | | awk '{print $4}''

```

**Comment by mprobson** [comment]
*Original date: 2016-08-29 00:05:10*

---
Should be all good now
