### ISSUE TITLE
ChaNGa crashes on verbs for dwf.6144 on 128 nodes

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#1043]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1043*

---
No body.

**Comment by harshithamenon** [comment]
*Original date: 2016-04-21 05:01:19*

---
Tom identified the reason for the crash and the following patch fixes it


diff --git a/src/arch/verbs/machine-ibverbs.c
b/src/arch/verbs/machine-ibverbs.c
index e1854b2..3bc92df 100644
--- a/src/arch/verbs/machine-ibverbs.c
+++ b/src/arch/verbs/machine-ibverbs.c
`` -558,7 +558,7 `` loop:
         /*      blockAllocRatio=16;
                 blockThreshold=8;*/

-       blockAllocRatio=64;
+       blockAllocRatio=128;
         blockThreshold=9;

**Comment by stwhite91** [comment]
*Original date: 2016-04-22 15:01:15*

---
Isn't this issue the same as 1042?
https://charm.cs.illinois.edu/redmine/issues/1042

**Comment by trquinn** [comment]
*Original date: 2016-04-22 15:03:28*

---
Yes.

**Comment by stwhite91** [comment]
*Original date: 2016-04-29 14:47:52*

---
Same issue as 1042.
