### ISSUE TITLE
AMPI collectives support for MPI_IN_PLACE

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1050]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1050*

---
AMPI currently implements MPI_IN_PLACE only for MPI_Reduce, MPI_Ireduce, MPI_Allreduce, MPI_Iallreduce, MPI_Reduce_scatter_block, and MPI_Reduce_scatter. 

We are missing MPI_IN_PLACE support for the following functions:
MPI_Scan
MPI_Exscan
MPI_Gather
MPI_Gatherv
MPI_Allgather
MPI_Allgatherv
MPI_Alltoall
MPI_Alltoallv
MPI_Alltoallw
MPI_Scatter
MPI_Scatterv

And all of the non-blocking variants of these.

**Comment by stwhite91** [comment]
*Original date: 2016-05-09 03:56:56*

---
ampif.C needs to test if buffers are NULL and set them to MPI_IN_PLACE if so.  Currently, this is only done for MPI_Reduce and MPI_Allreduce. Added support to other reduce routines in AMPIF here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1178/~~ https://github.com/UIUC-PPL/charm/commit/7f37b414b4fbb479e57b8ebf0d740eec6d3d1900

**Comment by stwhite91** [comment]
*Original date: 2016-07-14 19:31:29*

---
MPI_IN_PLACE for everything but MPI_Alltoall added here. Note that we just need a different algorithm for large message sizes with non-power-of-two communicator sizes: ~~https://charm.cs.illinois.edu/gerrit/#/c/1303/~~ https://github.com/UIUC-PPL/charm/commit/fc8a0095250a1cc9f32ef67185151f4a3aaaa2ec

**Comment by stwhite91** [comment]
*Original date: 2017-02-02 06:02:12*

---
As noted above, the only thing left to do on this is MPI_Alltoall.

**Comment by stwhite91** [comment]
*Original date: 2017-02-13 00:20:19*

---
What's the status of this? It would be good to have a fix merged before the 6.8.0 release

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-13 22:09:00*

---
I just pushed a patch that implements MPI_IN_PLACE for MPI_Alltoall:

~~https://charm.cs.illinois.edu/gerrit/#/c/2240/~~ https://github.com/UIUC-PPL/charm/commit/fc28a9698f582e2cb45b989c5d700c476123a605

Tested with a small custom MPI_Alltoall code.

**Comment by stwhite91** [comment]
*Original date: 2017-02-13 23:42:18*

---
Fix for large Alltoalls using MPI_IN_PLACE, the last part of this issue: ~~https://charm.cs.illinois.edu/gerrit/#/c/2240/~~ https://github.com/UIUC-PPL/charm/commit/fc28a9698f582e2cb45b989c5d700c476123a605
