### ISSUE TITLE
Make tracing warning about flushing logs more informative

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1058]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1058*

---
Currently, Projections warns users at the end of a run in which it had to flush its logs, but it's not clear how to solve that issue.
Make the warning message suggest increasing +logsize and print its current value. And update the Projections manual with info on +logsize, and +traceoff w/ traceBegin() and traceEnd().

**Comment by stwhite91** [comment]
*Original date: 2017-01-30 00:40:36*

---
This should be quick and would be valuable to have merged before the 6.8.0 release.

**Comment by rbuch** [comment]
*Original date: 2017-01-31 21:06:10*

---
Implemented at ~~https://charm.cs.illinois.edu/gerrit/#/c/2177/~~ https://github.com/UIUC-PPL/charm/commit/35e085ca1cea96c96809dc558a011a77b5f25223.  The documentation already contained the correct information as far as I can see.
