### ISSUE TITLE
Replace std::maps with a better implementation

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#1064]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1064*

---
During the 64bit merge, some one-off data structures (such as CkMigratableList) were deleted and replaced by std::map, however the use of std::map was only meant to be temporary (see https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commit;h=1791cb5e77c580b4f8c9b67ecbd76a144e4c2cbc for the original commit message).

A better implementation should be found, but one that also works on all of the platforms we care about (so std::unordered_map is out for now due to lack of support on xlc).

**Comment by stwhite91** [comment]
*Original date: 2016-05-11 21:14:59*

---
Related: https://charm.cs.illinois.edu/redmine/issues/185

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2016-05-12 01:44:21*

---

Performance comparisons of map, unordered_map and ckhashtable: https://charm.cs.illinois.edu/private/tms/listlog.php?param=449

**Comment by epmikida** [comment]
*Original date: 2016-05-12 18:50:01*

---
It looks like unordered_map is the clear winner in just about every case. Sam suggested using a typedef to use unordered map everywhere it is supported, and typedef to std::map everywhere else (mainly just XLC I think)

**Comment by stwhite91** [comment]
*Original date: 2016-10-03 22:56:45*

---
Even just doing the typedef for map vs unordered_map would be worth doing soon

**Comment by PhilMiller** [comment]
*Original date: 2016-10-05 19:49:29*

---
Yes, please add that typedef. Note that we'll still need to use old-style `typedef` syntax instead of modern `using` syntax, because the case that needs the alternative is IBM XL on Blue Gene, and that doesn't support the new syntax.

**Comment by PhilMiller** [comment]
*Original date: 2016-10-27 23:13:11*

---
Ping. The configure test and consequent typedef for this don't seem like a big deal. Is there some hidden complexity that I'm missing here?

**Comment by epmikida** [comment]
*Original date: 2016-11-02 22:39:39*

---
I just missed it being assigned to me. Working on it now. The only "complexity" is that without 'using' we will can't just typedef Map to either std::map or std::unordered_map based on platform. We will need to do a separate typedef for each map in the location manager because they all have different template arguments.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-23 19:15:20*

---
~~https://charm.cs.illinois.edu/gerrit/1978~~ https://github.com/UIUC-PPL/charm/commit/ac84e2be6f63d892bf3aa9a576a16bbc27624db2
I'll open a follow-up bug about resolving which XLC versions/platforms we should be constraining to the slower ordered structures.

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 16:35:56*

---
Use tr1/unordered_map instead of stl map on BG XLC: ~~https://charm.cs.illinois.edu/gerrit/#/c/2013/~~ https://github.com/UIUC-PPL/charm/commit/806b3277cac6c0e37864c8339e1220a0770a1b54
