### ISSUE TITLE
Migratable DMA regions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#107]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/107*

---
Regions of memory attached to a migratable entity like chare array elements that can be used as the target of RDMA operations.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 17:35:45*

---
Needs CmiOnesided to happen first.

**Comment by stwhite91** [comment]
Zero copy API covers this. Either low-level direct API put/get operations, or high-level entry method APIs
