### ISSUE TITLE
Migrate lagging 'net' builds to 'netlrts'

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1070]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1070*

---
Based on net-linux-x86_64 and net-darwin-x86_64 vs their netlrts equivalents, the conv-mach files can be copied straight over from net to netlrts to make a working build.

Subbugs should copy over for their designated platform, test, make adjustments as necessary, and commit.

**Comment by stwhite91** [comment]
*Original date: 2017-03-23 15:45:10*

---
net-linux-amd64 and net-linux-cell are the only net builds left without netlrts equivalents. Do we even want to have netlrts versions of those?

**Comment by jcphill** [comment]
*Original date: 2017-03-23 16:32:34*

---
Sam White wrote:
> net-linux-amd64 and net-linux-cell are the only net builds left without netlrts equivalents. Do we even want to have netlrts versions of those?

Isn't amd64 the same as x86_64?
