### ISSUE TITLE
Migrate net-linux-arm7 to netlrts

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1072]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1072*

---
See parent

**Comment by stwhite91** [comment]
*Original date: 2017-03-23 15:29:29*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2336/~~ https://github.com/UIUC-PPL/charm/commit/592408b82b300ddc74dc40489e17ac156b6bf413

Next we would like to start having autobuild test this...
