### ISSUE TITLE
Migrate net-linux-ppc to netlrts

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1074]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1074*

---
See parent

**Comment by stwhite91** [comment]
*Original date: 2017-03-23 15:34:59*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2336/~~ https://github.com/UIUC-PPL/charm/commit/592408b82b300ddc74dc40489e17ac156b6bf413

**Comment by PhilMiller** [comment]
*Original date: 2017-04-11 21:02:08*

---
The above linked patch is for arm, not ppc

**Comment by PhilMiller** [comment]
*Original date: 2017-04-11 21:02:39*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2337/~~ https://github.com/UIUC-PPL/charm/commit/f258d0f6918db929e4b258220b093e471f7298bd
