### ISSUE TITLE
Remove deprecated machine layers and retired machines from Autobuild

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1079]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1079*

---
Autobuild has the following tests that should be removed/migrated:

1. 32-bit Darwin builds
2. Builds on Finesse (retired lab machine): net-linux-x86_64-icc, uth-linux-x86_64
3. Builds on Hopper (retired Cray XE): mpi-crayxe, gemini_gni-crayxe, gemini_gni-crayxe-smp
4. Builds on Trestles (retired cluster with PGCC): net-linux-x86_64-smp-pgcc, net-linux-x86_64-pgcc
5. Net-layer builds for platforms that already have equivalent lrts builds: net-darwin, net-linux, net-linux-ibverbs

Other takeaways:
- No ICC tests are being run anymore (used to be on Finesse), should be done on Stampede or Edison.
- No PGCC tests are being run anymore (used to be on Trestles), but I'm not sure we care.

**Comment by stwhite91** [comment]
*Original date: 2016-06-12 15:14:15*

---
ICC tests are being done on Edison, so that is already covered.

**Comment by bilgeacun** [comment]
*Original date: 2016-07-06 19:39:14*

---
1- darwin 32 builds are removed.
2- net-linux-x86_64-icc on Finessse is removed, uth-linux-x86_64 is migrated to Beauty
3-Only place Cray-XE tests can be moved is Blue Waters I suppose, and that requires ssh with token. Is there any other place that we can test those?
4-PGCC tests are already skipped. Do they need to be removed from the list as a whole?
5-net layer builds are removed.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 18:37:04*

---
Not a change in the codebase, so not targeted to a code release.

**Comment by bilgeacun** [comment]
*Original date: 2016-10-13 17:56:07*

---
Removed unnecessary net-* and pgcc builds from autobuild. There are various other skipped tests, but keeping them for now since it may be needed to do extensive testing in future.

**Comment by stwhite91** [comment]
*Original date: 2017-03-08 22:36:59*

---
Here's some machine layers that are still around that I think we might be able to remove completely:
```
net-linux
net-linux-amd64
net-linux-cell
net-sol
net-sol-x86_64
mpi-sol
mpi-sol-x86_64
win32

```
