### ISSUE TITLE
Improve SMP mode documentation

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1082]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1082*

---
This was brought up during last week's group meeting: documentation of SMP mode, what it is, how to run jobs on different net-layers/machines for different configurations of logical Nodes/PEs to physical resources.

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 15:37:47*

---
This is sorely needed.

**Comment by mprobson** [comment]
*Original date: 2017-04-13 22:49:24*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2399/~~ https://github.com/UIUC-PPL/charm/commit/f5373f19f67c460e2be25c3a7c511b4be66a09b3

**Comment by stwhite91** [comment]
*Original date: 2017-07-28 12:32:56*

---
Bump, the release is expected to be out next week.
