### ISSUE TITLE
Insert "// Potentially missing FooClass_SDAG_CODE in your class definition?" in generated SDAG

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1108]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1108*

---
Help the user see why their compilation failed.

**Comment by stwhite91** [comment]
*Original date: 2017-02-04 20:45:43*

---
I took a quick crack at this after coming across it: ~~https://charm.cs.illinois.edu/gerrit/#/c/2190/~~ https://github.com/UIUC-PPL/charm/commit/f77c68fbb92b491858cf728fa9afbb11164a7a26

There are still plenty of things that come up in the errors that don't have the comment, but enough that are guaranteed to come up that it should always be visible.
