### ISSUE TITLE
AMPI thread migration fails on Edison gni-crayxc

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#1112]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1112*

---
When running the megampi test with more than one PE I get the following error:
```
mprobson`nid00047:~/charm/gni-crayxe-LIBS-master/tests/ampi/megampi> srun -n 2 ./pgm +vp1
Charm++> Running on Gemini (GNI) with 2 processes
Charm++> static SMSG
Charm++> SMSG memory: 9.9KB
Charm++> memory pool init block size: 8MB, total memory pool limit 0MB (0 means no limit)
Charm++> memory pool registered memory limit: 200000MB, send limit: 100000MB
Charm++> Cray TLB page size: 8192K
Charm++> Running in non-SMP mode: numPes 2
Converse/Charm++ Commit ID: v6.7.0-246-g5ae6849
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (48-way SMP).
[0] RandCentLB created
srun: error: nid00047: task 1: Segmentation fault
srun: Terminating job step 662862.2
slurmstepd: *** STEP 662862.2 ON nid00047 CANCELLED AT 2016-06-23T12:33:53 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: nid00047: task 0: Killed
```
charm build: ./build LIBS gni-crayxe --with-production --enable-error-checking -j16
Charm head is at commit ID: 5ae684996.
Machine: Edison
Modules: PrgEnv-intel/5.2.56 and craype-hugepages8M

Running with +p1 (aka srun -n1 runs fine). All other AMPI tests in `make test` have also failed at some point but I haven't transcribed their errors. I discovered this while working on #1038 but my commits to enable charmun to use srun automatically have the same problems as running srun by hand.

**Comment by stwhite91** [comment]
*Original date: 2016-06-24 03:59:09*

---
I can reproduce the issue on Edison (gni-crayxc). It does not happen on Blue Waters (gni-crayxe), pamilrts, or netlrts.

The error occurs during migration, TCharm::cjJustMigrated calls resume on the thread after migration and there is a segfault. I need to look into the threads package we're using on Edison...

**Comment by stwhite91** [comment]
*Original date: 2016-06-24 04:10:30*

---
Using context threads rather than qthreads seems to work. Context threads are already the default for gni-crayxc-smp.

**Comment by stwhite91** [comment]
*Original date: 2016-06-24 04:22:11*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1293/~~ https://github.com/UIUC-PPL/charm/commit/62ea1db6a84c3391028846134fdc7e9171819b06
