### ISSUE TITLE
smart-build.pl should detect supercomputers with specialized software environments (BG/Q, Cray) and act accordingly

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1113]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1113*

---
When running `./build` on Blue Gene Q, the smart-build.pl script doesn't show any awareness of its environment - it acts oblivious to the fact that the entire path and such include BG/Q specific stuff. This confuses users who don't know what options lead them to the build for their supercomputer, rather than the head nodes.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-26 18:57:39*

---
I think we should try to get this dealt with before 6.8.0 is released

**Comment by PhilMiller** [comment]
*Original date: 2017-01-26 18:58:59*

---
Eric B - NB

**Comment by ericjbohm** [comment]
*Original date: 2017-10-25 18:54:33*

---
Phil, do you think we should try to get this done in 6.9?  I think the overall effort isn't hard, but there are a lot of corner cases to fiddle with that require direct experimentation in different environments.

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-29 19:13:18*

---
I currently don't have access to any BG/Q machines.

**Comment by ericjbohm** [comment]
*Original date: 2017-11-29 19:25:19*

---
Given that BG/Q has no forward path, I'd be inclined to focus these efforts on other platforms.  We should also work to get you access to ALCF's BG/Q,  but the more interesting work would be for next generation machines based on OFI and PAMI.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-12 23:08:47*

---
Any opinions on the following one-liner as a Cray environment detection test?


```
if [ "`echo "$PATH" | grep /opt/cray/ -`" != "" ]; then echo "Cray environment found"; else echo "Cray environment not found"; fi
```

**Comment by nitbhat** [comment]
*Original date: 2018-01-17 21:57:48*

---
Default $PATH values on select supercomputers:

1. Vesta - BGQ
/usr/lib64/qt-3.3/bin:/soft/compilers/bgclang/wbin:/soft/compilers/bgclang/mpi/bgclang/bin:/soft/buildtools/cmake/2.8.11.1/bin:/home/nbhat/bin:/soft/environment/softenv-1.6.2/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/bgsys/drivers/V1R2M4/ppc64/gnu-linux/bin:/bgsys/drivers/V1R2M4/ppc64/hlcs/bin:/soft/debuggers/scripts/bin:/soft/accttools/bin:/soft/buildtools/trackdeps/bin:/soft/compilers/ibmcmp-may2016/vac/bg/12.1/bin:/soft/compilers/ibmcmp-may2016/vacpp/bg/12.1/bin:/soft/compilers/ibmcmp-may2016/xlf/bg/14.1/bin:/bgsys/drivers/ppcfloor/bin:/bgsys/drivers/ppcfloor/sbin:/dbhome/db2cat/sqllib/bin:/dbhome/db2cat/sqllib/adm:/dbhome/db2cat/sqllib/misc:/usr/lpp/mmfs/bin:/home/nbhat/bin

2. SummitDev - Power 8
/sw/sources/lsf-tools/bin:/sw/summitdev/xalt/0.7.5/bin:/sw/sources/hpss/bin:/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/jsm_pmix/bin:/autofs/nccs-svm1_sw/summitdev/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20170914-beta/spectrum-mpi-10.1.0.4-20170915-nmlgpsufnxxal2wv64hh7zfisabr56ry/bin:/sw/summitdev/xl/20170914-beta/xlC/13.1.6/bin:/sw/summitdev/xl/20170914-beta/xlf/15.1.6/bin:/opt/ibm/spectrumcomputing/lsf/10.1/linux3.10-glibc2.17-ppc64le-csm/etc:/opt/ibm/spectrumcomputing/lsf/10.1/linux3.10-glibc2.17-ppc64le-csm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibm/flightlog/bin:/opt/ibm/spectrum_mpi/jsm_pmix/bin:/opt/puppetlabs/bin:/usr/lpp/mmfs/bin

3. Bridges - OFI network with Intel CPUs
/usr/lib64/qt-3.3/bin:/opt/intel/advisor_2017.1.3.510716/bin64:/opt/intel/vtune_amplifier_xe_2017.3.0.510739/bin64:/opt/intel/inspector_2017.1.3.510645/bin64:/opt/intel/itac/2017.3.030/intel64/bin:/opt/intel//itac/2017.3.030/intel64/bin:/opt/intel//clck/2017.2.019/bin/intel64:/opt/intel/compilers_and_libraries_2017.4.196/linux/bin/intel64:/opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin:/opt/intel/debugger_2017/gdb/intel64_mic/bin:/opt/packages/slurm/17.02.5/bin:/opt/packages/allocations:/opt/packages/interact/bin:/usr/lib64/ccache:/usr/bin:/bin:/usr/sbin:/sbin:/opt/packages/hpnssh/7.5p1-hpn14v12/bin:/usr/local/sbin:/opt/puppetlabs/puppet/bin:/opt/packages/slash2/psc/sbin:/opt/intel/parallel_studio_xe_2017.4.056/bin:/opt/puppetlabs/bin:/home/nbhat4/.local/bin:/home/nbhat4/bin

4. Stampede 2 - OFI network with Intel KNLs
/opt/apps/xalt/1.7.7/bin:/opt/apps/papi/5.5.1/bin:/opt/apps/libfabric/1.4.2/bin:/home1/apps/idl/8.4/idl/bin:/opt/apps/intel17/python/2.7.13/bin:/opt/apps/autotools/1.1/bin:/opt/apps/git/2.9.0/bin:/tmprpm/intel17/impi/17.0.3/bin:/opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin:/opt/intel/compilers_and_libraries_2017.4.196/linux/bin/intel64:/opt/apps/gcc/5.4.0/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/dell/srvadmin/bin:.:/opt/apps/intel17/impi17_0/fftw3/3.3.6/bin

^ This could vary depending on the loaded modules.

**Comment by rbuch** [comment]
*Original date: 2018-01-26 20:51:01*

---
I think we don't care about BG/Q looking forward for a variety of reasons. First, the machines should be out of production in a short time, so they probably won't be useful for much longer. Second, people who are using BG/Q already are likely to already have explicit build commands and scripts and won't be using the ./build script (e.g. some of the NAMD collaborators).

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-22 21:57:17*

---
~~https://charm.cs.illinois.edu/gerrit/3765~~ https://github.com/UIUC-PPL/charm/commit/14bbf53d0d157c836d7e694b9bd2f658a3e40bc7
