### ISSUE TITLE
Build and link ROMIO on AMPI by default

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1114]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1114*

---
If building AMPI, build ROMIO on AMPI. Add an MPI-IO test to AMPI's tests too. MPI-IO is part of the standard, and we want to know if something we add breaks it.

**Comment by stwhite91** [comment]
*Original date: 2016-06-29 14:02:06*

---
Note: parallel make with ROMIO tries to run ROMIO's configure in parallel, resulting in failure.

**Comment by stwhite91** [comment]
*Original date: 2016-09-07 21:58:37*

---
ROMIO is now built by default when building AMPI. You can specify '--without-romio' to not build it. It is always linked by ampicc: ~~https://charm.cs.illinois.edu/gerrit/#/c/1833/~~ https://github.com/UIUC-PPL/charm/commit/ee84e087ae9e5396257758ac4dc9006e5163a421

Remaining issues related to ROMIO builds:
1. Parallel builds with ROMIO crash.
2. We have no tests for MPI-IO stuff. We should add one to tests/ampi/ so it is tested regularly.
3. We get a lot of compiler warnings for MPI_Info stuff (issue #1151) when building ROMIO.

**Comment by PhilMiller** [comment]
*Original date: 2016-10-22 16:49:36*

---
The non-idempotent nature of how your scripts clean and rebuild every time it runs is making tests take way longer to run than they ought to, especially on systems where compilation and linking are slow:
http://charm.cs.uiuc.edu/autobuild/cur/gni-crayxc-smp.txt

**Comment by stwhite91** [comment]
*Original date: 2016-11-05 19:25:20*

---
Patch to not rebuild AMPI-ROMIO when it has already been built: ~~https://charm.cs.illinois.edu/gerrit/#/c/1971/~~ https://github.com/UIUC-PPL/charm/commit/6fd10623f7fa6d49b231655d63830a4aac8c4473
