### ISSUE TITLE
Document ability of [sync] entry methods to return any type that supports PUP

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1136]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1136*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2016-07-11 21:49:50*

---
The manual still says that `[sync]` entry methods can only return messages

**Comment by stwhite91** [comment]
*Original date: 2016-09-02 20:23:31*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1822/~~ https://github.com/UIUC-PPL/charm/commit/57f414efb5f9d7ac5209c3e6ce242665b2781404
