### ISSUE TITLE
Define 'thisIndex' for Groups

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1148]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1148*

---
Chare arrays all have a member variable 'thisIndex', while Groups and NodeGroups have a semantically similar ID called 'onPE'. This is an unnecessary pain when porting code from, say, a Chare Array to a Group.

Suggested fix: add a static member variable to Groups called thisIndex, whose value is the same as onPE.

**Comment by stwhite91** [comment]
*Original date: 2017-01-31 00:47:56*

---
It would be good to have this soon, before the 6.8.0 release.

**Comment by karthiksenthil** [comment]
*Original date: 2017-03-10 02:12:05*

---
Why should `thisIndex` be defined as a static variable?

I have a current implementation which adds `thisIndex` as a regular protected member(int) of the `IrrGroup` class defined in charm++.h and ck.C

In the constructor `thisIndex` is set as follows:
```
thisIndex = ckGetChareID().onPE;
```

This seems to be working for both Groups and NodeGroups. I've tested with examples/charm++/hello/group and tests/charm++/pingpong

**Comment by stwhite91** [comment]
*Original date: 2017-03-10 17:25:18*

---
The idea behind making it static was that we could save on memory overhead by having one instance of it. We can discuss whether that is important or not in core meeting. Go ahead and submit the patch as is.

**Comment by karthiksenthil** [comment]
*Original date: 2017-03-11 01:15:14*

---
Patch on Gerrit: ~~https://charm.cs.illinois.edu/gerrit/#/c/2298/~~ https://github.com/UIUC-PPL/charm/commit/2fbd3b8249dc03738e453fb968d6392f5286b824
