### ISSUE TITLE
Partition according to topology, not linear node numbering

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#116]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/116*

---
When running with partitions, we should try to make them as topologically close as possible, to provide the best performance. Right now, we split the nodes into blocks by their sequential ID number, and run one partition on each block.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 20:31:37*

---
I'm looking at the replica branch now, and the commits are quite a mess. Please rebase interactively to form clear, discrete changes that will be easier to understand than "commit everything so I can merge" or "commit stuff before a machine goes offline".

**Comment by nikhil-jain** [comment]
*Original date: 2013-05-31 06:32:39*

---
Yeah, rebasing and rephrasing of the commits is a given at the time of merge.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 06:46:04*

---
I'm asking that it happen as the first step of review, so that I an actually make sense of what I'm reading.

**Comment by nikhil-jain** [comment]
*Original date: 2013-05-31 15:26:43*

---
replica-ready is the updated branch.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 19:02:15*

---
You're rebased to mainline and cleaned out some of the totally random commits, but it's still not in a really reviewable state. I would expect separate, individual, working commits for _at least_ each of the following:
* Variable partition size specified on the command line
* Topo aware automatic partition construction
* User-defined partition construction

Bug fix commits for each of these should be folded into the basic commit, so that we don't intentionally introduce broken commits whose fixes are already known. Where makefiles need to change to match code changes, those should also occur in the same commit.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 20:49:24*

---
I'm looking at the consolidated diff, so as not to be distracted by the transient states.

1st comment: `calculateTotalHops()` is defined solely in `init.C`, but never called. Is it for some unspecified later use, or is it detritus?

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 20:54:41*

---
The code to print topology to a file should not fall back to standard output. If the user asked for this information in a particular place, it's a fatal error if that place isn't writable. We should display the nature of the failure (e.g. `perror(errno)`) and abort the run.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:07:44*

---
The documentation of custom partitioning strategies could be clearer:
* The `-custom-part` flag needs to be passed when _linking_, not when compiling.
* Rather than "a user is required to implement a C function . . .", "a user must link an object exporting a C function . . ."

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:18:07*

---
Documentation:
* Not all of the described partitioning features appear in 6.5.0, so the docs can't say just that. All of the options besides `+partitions` and `+replicas` should be marked as available in 6.6 onwards.
* `+use_topology` needs to be either documented, or deleted as redundant with the more specific `+use_topology_scheme`.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:31:55*

---
For user convenience, the loop in `TopoManager_createPartitions()` to identity-initialize the `nodeMap[]` should be moved to `create_topoaware_partitions()` before the call to `createCustomPartitions()` and `TopoManager_createPartitions()`.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:38:59*

---
There's a missing `else` in the `PARTITION_MASTER` case in `node_lToGTranslate`, such that `n_l2g(0, 0)` will return junk instead of the node with rank 0.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:42:37*

---
With `+use_custom_part` and `CMK_ERROR_CHECKING` set, we should validate that the output nodemap makes sense - all entries are in `[0, CmiNumNodesGlobal()-1]` and that each appears exactly once.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 21:59:49*

---
`partitioning_strategies.h` needn't contain any sort of header comment - version control records the file name and authorship.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:00:39*

---
Clean up the crufty amalgamation of partitioning_strategies.h and hilbert.h.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:04:10*

---
Nearly all of the code in partitioning_strategies.h should be in a .C file, with most functions declared static. The only two functions used externally are `getPlanarList` and `getHilbertList`.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:12:55*

---
`TopoManager_getRanks()`:
* puts its input argument `coords` after its output arguments `rank_cnt` and `ranks`
* takes an array `ranks` as an output argument, but it's not documented how the user is supposed to determine how big to allocate this

`TM_getPeRank` and `TM_createPartitions` also have their arguments in a sub-optimal order.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:17:13*

---
Nikhil, did you delete an earlier comment? I got an email from Redmine with your comment
> I am not inclined to spend further time on it as far as changing the commits are concerned. If you are convenient with reviewing the code with these commits, please do so; else I will request for an alternate reviewer.
but it seems to have disappeared from this issue's record.

**Comment by nikhil-jain** [comment]
*Original date: 2013-05-31 22:24:45*

---
Yes, it was deleted since it may have been a conflict visible in public space.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:28:04*

---
The C-language `TopoManager_*` interfaces are not thread-safe as designed. One thread can be using `_tmgr` while another one goes into `TM_reset()`, deleting and re-constructing it.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 22:29:06*

---
Development communities have disagreements all the time. I didn't feel like anything in there warranted hiding. If it did, then we should probably not have been doing it.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-11 20:36:46*

---
This was preexisting dead code. Removed.

Phil Miller wrote:
> I'm looking at the consolidated diff, so as not to be distracted by the transient states.
> 
> 1st comment: `calculateTotalHops()` is defined solely in `init.C`, but never called. Is it for some unspecified later use, or is it detritus?

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-11 20:38:49*

---
As a user of other libraries, I have found resorting to stdout as a better option, instead of causing the program crash. But the point is worth discussing with others.

Phil Miller wrote:
> The code to print topology to a file should not fall back to standard output. If the user asked for this information in a particular place, it's a fatal error if that place isn't writable. We should display the nature of the failure (e.g. `perror(errno)`) and abort the run.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-11 21:54:23*

---
I switched the arguments for CreatePartitions. However, for getRanks, the ordering is something people are used to, and hence it is kept this way. The documentation will be added to doc. 

Phil Miller wrote:
> `TopoManager_getRanks()`:
> * puts its input argument `coords` after its output arguments `rank_cnt` and `ranks`
> * takes an array `ranks` as an output argument, but it's not documented how the user is supposed to determine how big to allocate this
> 
> `TM_getPeRank` and `TM_createPartitions` also have their arguments in a sub-optimal order.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-08 19:14:40*

---
Basic strategies are in place and users can also specify their own strategies.
