### ISSUE TITLE
charm-6.7.1.tar.gz untars to charm

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1161]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1161*

---
The file distrib/charm-6.7.1.tar.gz file untars to the directory charm, which is not what the user would expect.

**Comment by stwhite91** [comment]
*Original date: 2016-08-17 21:56:36*

---
I changed it to untar to a directory named 'charm-6.7.1'

**Comment by stwhite91** [comment]
*Original date: 2016-08-29 16:00:19*

---
Marking 'closed' so that it doesn't show up under 'open' issues.
