### ISSUE TITLE
tracing runs segfault while writing logs

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1162]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1162*

---
No body.

**Comment by jcphill** [comment]
*Original date: 2016-08-14 22:35:40*

---
I'm consistently seeing segfaults or, most informatively, free(): invalid pointer, at the end of smp tracing runs on thousands of pes.  This is for 6.7.1 and current head.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 18:10:51*

---
Has there been any investigation or follow-up on this? This could be pretty crippling for large-scale performance work.

**Comment by rbuch** [comment]
*Original date: 2017-04-04 18:35:23*

---
I thought I had added a log here before, but I guess not.  I had tried to replicate this when the bug was originally assigned and didn't have any luck in reproduction.  I'll give it a go again to see if I can get an example case.

**Comment by stwhite91** [comment]
*Original date: 2017-09-01 19:07:16*

---
Still an issue?

**Comment by stwhite91** [comment]
*Original date: 2017-10-03 16:50:01*

---
Bump. Need to reproduce the failures and address them, or retarget to 6.9.0

**Comment by rbuch** [comment]
*Original date: 2017-10-04 18:35:42*

---
I was never able to reproduce this. Has this been an issue for you at all as of late, Jim (or anyone else)?

**Comment by PhilMiller** [comment]
*Original date: 2017-10-11 19:38:50*

---
No longer seems to be reproducible. Re-open or open a new issue if it is observed again or can be reproduced.
