### ISSUE TITLE
pathHistoryManager doesn't PUP

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1166]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1166*

---
Commit b240e238385ba2d0aa08748880b3b34ce59d03a2
Author: Yanhua Sun <sun51`illinois.edu>
Date:   Mon Nov 2 11:21:03 2015 -0600

put a non-functional pup() in the pathHistoryManager class.  This breaks checkpointing.

**Comment by stwhite91** [comment]
*Original date: 2016-08-17 18:33:52*

---
Do you still see problems on current master, since the following commit was merged? ~~https://charm.cs.illinois.edu/gerrit/#/c/1331/~~ https://github.com/UIUC-PPL/charm/commit/fd80c5efe1460f532da531b86bf1d89ababa0ec1

**Comment by trquinn** [comment]
*Original date: 2016-08-17 19:00:19*

---
Things work with the latest version.  Sorry for not checking this first.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 18:34:03*

---
Not fixed in code, so not relevant to a release of the code.
