### ISSUE TITLE
Command line argument +balancer for multiple balancers does not work

### ISSUE THREAD

**Issue by kavithachandrasekar** [UIUC-PPL/charm#1169]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1169*

---
Specifying the command line argument +balancer multiple times, to allow different balancers to be called in subsequent steps, does not work any more. This was likely introduced with the feature to reject duplicate command line arguments [https://charm.cs.illinois.edu/redmine/issues/831].

**Comment by stwhite91** [comment]
*Original date: 2016-08-22 21:20:37*

---
The TCharm/AMPI option '+vp' is also supposed to be accepted multiple times (in the case of running multiple modules).
