### ISSUE TITLE
Use hwloc data from compute host, rather than assuming they're identical to the host running charmrun

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1174]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1174*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 05:40:29*

---
Please post which gerrit patch this was implemented in and then mark 'merged'

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:18:33*

---
Merged: ~~https://charm.cs.illinois.edu/gerrit/3446~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d
