### ISSUE TITLE
Detect unsupported non-uniformity of processes/threads in charmrun, and error

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1176]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1176*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 05:44:55*

---
Please post which gerrit patch this was implemented in, and then marked 'merged'.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:17:40*

---
Merged: ~~https://charm.cs.illinois.edu/gerrit/3446~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d
