### ISSUE TITLE
Support automated launch/spawn/bind when using charmrun ++mpiexec

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1178]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1178*

---
This may already even work. I haven't tested it yet.

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-22 22:41:10*

---
Are there any more details available about what this entails?

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-17 20:47:40*

---
Bump. I'm having difficulty understanding exactly to what this issue refers. Is this related to the hwloc patches?

**Comment by stwhite91** [comment]
*Original date: 2018-01-17 21:09:48*

---
I think this means the new hwloc arguments like ++oneWthPer{PU,Core,Socket,Host} should all work with ++mpiexec just like without ++mpiexec.

mpiexec is just a mechanism to launch some number of processes, but it doesn't do anything on its own about thread binding inside our processes.

It might already work, but the abort in this patch suggests it doesn't: ~~https://charm.cs.illinois.edu/gerrit/#/c/3446/~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-18 22:40:59*

---
++oneWthPer{PU,Core,Socket,Host} with ++mpiexec implemented in ~~https://charm.cs.illinois.edu/gerrit/3446~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d revision 7.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:17:56*

---
~~https://charm.cs.illinois.edu/gerrit/3446~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d
