### ISSUE TITLE
Support automated thread spawn/bind for standalone runs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1180]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1180*

---
When running on a single host without using charmrun (in a build of netlrts/verbs/multicore), it should still be possible to use this code to get thread count/placement right. Maybe it already works.

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 05:45:35*

---
Please post which gerrit patch this was implemented in, and marked 'merged'.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:17:20*

---
Merged: ~~https://charm.cs.illinois.edu/gerrit/3558~~ https://github.com/UIUC-PPL/charm/commit/ca83f39f190c4f833a836ef794db7011f4183798
