### ISSUE TITLE
Support automated process launch on a single host for standalone runs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1181]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1181*

---
If the user is running on one host but wants to be lazy about using charmrun, it should still be possible for them to request (for example) a process per socket, and have those launch and wire up correct.

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-19 18:06:53*

---
`++processPerSocket 1` should work with the hwloc patchsets both with charmrun and with standalone SMP executables.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:19:25*

---
~~https://charm.cs.illinois.edu/gerrit/3558~~ https://github.com/UIUC-PPL/charm/commit/ca83f39f190c4f833a836ef794db7011f4183798
~~https://charm.cs.illinois.edu/gerrit/3446~~ https://github.com/UIUC-PPL/charm/commit/b17ebda92afc56a9d5ae66d174cd04564abbfd8d
