### ISSUE TITLE
SMP-safe CmiReference and CmiFree

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1184]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1184*

---
Two related issues that could be broken out into separate issues once this work is begun:

1. Currently CmiReference and CmiFree are not protected by a lock at all. Consequently CMK_BROADCAST_USE_CMIREFERENCE is set to 0 in conv-config.h for SMP mode builds, meaning that broadcasts have to be delivered to all PEs in SMP mode rather than just once to each logical Node. To fix this add locking to CmiReference/CmiFree.

2. We should avoid the overhead of locking if there are no actual shared references to an object, and we could set a threshold size for broadcast messages where if a message is large we will use CmiReference/Free within the logical Node and if it's smaller than the threshold we could potential just deliver it to every PE to avoid lock contention.

**Comment by stwhite91** [comment]
*Original date: 2016-11-29 20:50:23*

---
Reassigning to Vipul since this is mostly targeted at broadcasts.

See the note in conv-config.sh about CMK_BROADCAST_USE_CMIREFERENCE in SMP mode:
```
/**
    CmiReference broadcast/multicast optimization does not work for SMP
    due to race condition on memory reference counter, needs lock to protect
 */
#if CMK_SMP && CMK_BROADCAST_USE_CMIREFERENCE
#undef CMK_BROADCAST_USE_CMIREFERENCE
#define CMK_BROADCAST_USE_CMIREFERENCE                      0
#endif

```

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 20:33:52*

---
This is more of a feature than a bug, meant to increase performance of large-message [nokeep] broadcasts.

Also, you may want to use these for thread-safe increment/decrement: ~~https://charm.cs.illinois.edu/gerrit/#/c/1954/~~ https://github.com/UIUC-PPL/charm/commit/3501af14a1750bf49878a9544997ddd9198640d2

**Comment by ericjbohm** [comment]
*Original date: 2018-04-26 22:22:35*

---
Should be possible to fix this with a use of std::atomic that is similar to the approach used in the pcqueue.h fix.  As the issue here is that in SMP we want the decrement on CmiReference to be safe and the old implementation does not enforce consistency.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-02 23:48:18*

---
~~https://charm.cs.illinois.edu/gerrit/4108~~ https://github.com/UIUC-PPL/charm/commit/716024c94421c7e4dfdb018bc89ae1ec4a053086

Implementing this appears to have been trivial. It required renaming a large set of files to C++ though.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-07 21:38:03*

---
Cross-referencing from Gerrit change:

Sam White wrote:
> Turning CmiReference and CmiFree into atomics does solve this issue, but it will add overhead in the case of regular entry method invocations (not broadcasts). We'll want to measure that overhead. At the least I think we would want to only make them atomic in SMP mode.
