### ISSUE TITLE
Cray's rca_get_max_dimension on Titan returns incorrect values

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#119]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/119*

---
A call to rca_get_max_dimension on Titan returns 12 16 24. The value of X dimension being 12 is erroneous, and is preventing topomanager from working correctly. And thanks to hack done by other people, incorrect topomanager means no one can run Charm++ on Titan without doing additional hacks!

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-23 16:38:32*

---
Hard code the value for Titan is the decision taken in Core meeting.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-27 04:46:32*

---
Do not use the dims to identify maxNID - explicitly cycle over pe to nid conversion for this purpose.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 02:07:30*

---
Fixed on mainline in commit 9bda4c8a272d9badc7f0c7dec718e8095b53776a - cherry-picked to stable as 54192a7.
