### ISSUE TITLE
AMPI fails to rename C++ main with signature 'int main()'

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1190]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1190*

---
The problem is main routines without (int argc, char **argv) arguments. This commonly appears in build system tests for compilers. We already support this for C programs, but not C++.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 19:18:55*

---
Let's talk about this directly - I can probably figure out a way around it.

**Comment by stwhite91** [comment]
*Original date: 2016-09-07 20:18:54*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1831/~~ https://github.com/UIUC-PPL/charm/commit/6e41e5e4ff4d0dd4ce50a750963f84d9dc8a5296
