### ISSUE TITLE
Document and exemplify chare class inheritance

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1196]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1196*

---
There's nothing in the manual or examples about chare classes having parent class relationships from which the child can inherit. The only thing we have is `tests/charm++/megatest/inherit*`, which is really nasty to read and understand.

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2017-04-13 18:45:39*

---
I see that it exists but is commented out. Phil, do you have any idea about this?

**Comment by stwhite91** [comment]
*Original date: 2017-04-14 15:57:39*

---
Is that documentation sufficient?

~~https://charm.cs.illinois.edu/gerrit/#/c/2391/~~ https://github.com/UIUC-PPL/charm/commit/2381050a2c575f4bb7a4fe66dd400b4f6ceacb65
