### ISSUE TITLE
Charmrun fails to connect to nodes on Taub in netlrts build. 

### ISSUE THREAD

**Issue by sbak5** [UIUC-PPL/charm#1197]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1197*

---
The netlrts version of Charm++ is built and executed well on taub but when it is built with gcc/4.9 (or later), it doesn't work well with the following message. 

Charmrun> error attaching to node 'taub487':
Timeout waiting for node-program to connect

This issue doesn't occur when it is built with the older version of gcc(4.4.7, default in taub)

This is the list of loaded modules. 
  1) torque/6.0.1h3   3) env/inv-cse      5) git/1.7          7) gcc/4.9.2
  2) moab/9.0.1       4) env/taub         6) vim/7.3

**Comment by PhilMiller** [comment]
*Original date: 2016-09-02 14:44:53*

---
Please try running a standalone version of some small program, and see if that crashes. If it doesn't crash, run it under `valgrind` and see if it reports any interesting errors. This is exactly how I tracked down that changes in GCC6 were screwing up a lot of Charm++ code.

**Comment by sbak5** [comment]
*Original date: 2016-09-02 14:52:51*

---
I've found this issue when I run a simple exercise in CS 598. It doesn't crash but just be terminated with the message above.

**Comment by bilgeacun** [comment]
*Original date: 2016-09-02 15:02:52*

---
Please try  ++mpiexec

**Comment by stwhite91** [comment]
*Original date: 2016-09-02 16:19:38*

---
netlrts-linux-x86_64 runs on Golub using ++mpiexec with the gcc/4.9.2 and mvapich2/1.6-gcc modules loaded. It also runs fine in standalone mode.

**Comment by stwhite91** [comment]
*Original date: 2016-09-02 16:32:43*

---
Nevermind, I was getting an allocation on Golub before, and it works there. On Taub, ++mpiexec does not work with gcc/4.9.2. I ran valgrind on the pingpong test in standalone mode, giving several instances of this:
```
==13005== 32 bytes in 1 blocks are possibly lost in loss record 60 of 215
==13005==    at 0x4C27AAA: malloc (vg_replace_malloc.c:291)
==13005==    by 0x53FC64: CmiAlloc (convcore.c:3035)
==13005==    by 0x545102: CldModuleGeneralInit (cldb.c:360)
==13005==    by 0x5413A0: ConverseCommonInit (convcore.c:3791)
==13005==    by 0x53D822: ConverseInit (machine-common-core.c:1261)
==13005==    by 0x4914C6: main (main.C:18)
==13005== 
==13005== 32 bytes in 1 blocks are possibly lost in loss record 61 of 215
==13005==    at 0x4C28222: operator new[](unsigned long) (vg_replace_malloc.c:384)
==13005==    by 0x54FB7F: cpuTopoRecvHandler(void*) (cputopology.C:183)
==13005==    by 0x53F3BC: CsdSchedulePoll (convcore.c:1783)
==13005==    by 0x54E3E4: LrtsInitCpuTopo (cputopology.C:582)
==13005==    by 0x4945E2: _initCharm(int, char**) (init.C:1393)
==13005==    by 0x53D92D: ConverseInit (machine-common-core.c:1294)
==13005==    by 0x4914C6: main (main.C:18)

```

**Comment by PhilMiller** [comment]
*Original date: 2016-09-02 16:42:25*

---
Those are just memory leaks. They should be cleaned up, but they are not a cause of launch failures.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 19:02:17*

---
Is this still a problem?

**Comment by kavithachandrasekar** [comment]
*Original date: 2016-09-23 19:22:57*

---
Eric Bohm wrote:
> Is this still a problem?

If charm is built with gcc 4.9.2, doing the following fixes the issue for running on Taub:

module load gcc/4.9.2
module load mpi/mpich/3.1.3-gcc-4.7.1

To the runscript, following edits need to be made:

#PBS -V (to export environment variables to the batch job)
++mpiexec (as Bilge suggested)

Attached is a sample script.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-04 20:58:58*

---
Since this issue occurs specifically on loading gcc/4.9 module, it needs for environment variables to be passed to the batch job as suggested in the solution. I checked with Seonmyeong and we think it's okay to reject the bug as it's specific to a configuration.
