### ISSUE TITLE
Fix hash function "hash" in "ckarrayindex.h" to include the first element in the loop

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1199]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1199*

---
This was suggested by Alexander Frolov. For 1d arrays, this makes for a continuous sequencing. Needs performance testing before merging

**Comment by PhilMiller** [comment]
*Original date: 2016-10-05 22:36:34*

---
~~https://charm.cs.illinois.edu/gerrit/1827~~ https://github.com/UIUC-PPL/charm/commit/85d452b86cb48338fdd7373041dfaefe19b7c8d9
Performance results showed benefits for tested cases.
