### ISSUE TITLE
Openatom mixes CkMulticast managers and uses different instances to contribute and broadcast

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1200]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1200*

---
The working of CkMulticast Managers is such that it doesn't get exposed now, but it does get affected in the 64-bit branch.

CkMulticastMgr uses remote pointers for mCastEntry objects which essentially are entries for book-keeping for sections. The section cookies have this pointer. As long as the remote pointer is right (i.e. the section cookie) is right,  using any instance of CkMulticastMgr will suffice (since all the book-keeping is through pointers which is specified in the cookie itself). 
Essentially the pointers created for book-keeping in one CkMulticastMgr are being used in other.

We are planning to get rid of remote pointers and use section-ids and a map inside CkMulticastMgr. This will expose this bug.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 19:15:49*

---
This needs way more explanation of why the described behavior does/will illustrate a bug in Charm++.

**Comment by PhilMiller** [comment]
*Original date: 2016-10-13 20:56:31*

---
Just as a check - this means that we have the following compatibility matrix:

```
             Charm++
Openatom     Old       New
     Old     Works     Broken
     New     Works     Works
```
And this is acceptable in the present circumstances? Either we're not worried about the broken case of old Openatom on new Charm++, or the single fix is easy to backport relative to other bugs that might be under examination?
