### ISSUE TITLE
SMP builds segfault on NULL lock in tests/charm++/chkpt

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1201]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1201*

---
http://ppl-jenkins.cs.illinois.edu:8080/job/Nightly-Build/940/label=precise,platform=netlrts-linux-x86_64-smp-clang/console
http://ppl-jenkins.c.sillinois.edu:8080/job/Nightly-Build/934/label=linux,platform=mpi-linux-x86_64-smp/console

Assigning this to Michael provisionally as one of the custodians of SMP.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-13 21:42:57*

---
In case it's not clear, this is ongoing:
http://ppl-jenkins:8080/job/Nightly-Build/label=linux,platform=mpi-linux-x86_64-smp/1101/console

**Comment by stwhite91** [comment]
*Original date: 2017-03-23 15:41:11*

---
That failure was happening inside CkNodeReductionMgr, that code has been removed entirely now right?

**Comment by PhilMiller** [comment]
*Original date: 2017-07-14 15:59:18*

---
I just checked - this failure wasn't seen in Jenkins Nightly-Build for mpi-linux-x86_64-smp or its successors since the linked build 1101. I'll check some of the net/lrts builds as well.

**Comment by PhilMiller** [comment]
*Original date: 2017-07-14 16:05:36*

---
As for Sam's note, Ck*Array*ReductionMgr got removed - CkNodeReductionMgr is still very much there, to support NodeGroup reductions

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 20:35:35*

---
This doesn't seem to have appeared in any of the Jenkins Nightly-Build runs for any configuration since at least June. Hypothesis is that the fix for #1616 covered this, but saying so conclusively would take some more analysis.
