### ISSUE TITLE
Building on OpenMPI fails due to mistaken need for C++ bindings library.

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1206]
*Original author: Erik Schnetter*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1206*

---
I tried building Charm++ with MPI support, using OpenMPI. This did not work, as the Charm++ configure stage could not determine how to link OpenMPI's libraries. I was able to resolve the problem with the attached patch "mpi.patch".

This was using OS X, gcc as compiler, the latest release of Charm++, and OpenMPI 2.0.

[mpi.patch](https://github.com/UIUC-PPL/charm/files/3536601/mpi.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2016-09-14 04:31:50*

---
Will post for review and merge shortly. Thank you for the contribution!

**Comment by jcphill** [comment]
*Original date: 2016-09-14 14:38:17*

---
Erik, what do "mpicc --showme:compile" and "mpicc --showme:link" return on your system?
It seems strange that Charm++ would require the C++ library to link files. It is more likely that the test is compiled with C++ even though MPI calls are only made from C.

**Comment by pplimport** [comment]
*Original author: Erik Schnetter*
*Original date: 2016-09-14 16:09:05*

---
These commands indeed don't mention the "mpi_cxx" library. Here is the pkgconfig file:

$ cat ../lib/pkgconfig/ompi.pc
1. Copyright (c) 2010 Cisco Systems, Inc.  All rights reserved.
#
Name: Open MPI
Description: Portable high-performance MPI implementation
Version: 2.0.0
URL: http://www.open-mpi.org/
#
prefix=/Users/eschnett/src/spack-charm/opt/spack/darwin-elcapitan-x86_64/gcc-6.1.0-spack/openmpi-2.0.0-7lkljiznpi5ylqws7mwogkfqqtsbdvun
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
#
1. Note that -lopen-pal and all the EXTRA_LIBS are only necessary when
1. static linking (they're pulled in by libopen-rte.so's implicit
1. dependencies), so only list these in Libs.private.
#
Libs: -L${libdir} -L/Users/eschnett/src/spack-charm/opt/spack/darwin-elcapitan-x86_64/gcc-6.1.0-spack/hwloc-1.11.3-qpc4ubmu6e5jeok2ry7x2rqvwtlrtzws/lib   -lmpi
Libs.private: -lhwloc
#
Cflags: -I${includedir}

I also see that Charm++ uses the C++ bindings of MPI, which do require the "mpi_cxx" library of OpenMPI.

**Comment by jcphill** [comment]
*Original date: 2016-09-14 19:07:19*

---
The C++ bindings of MPI are deprecated/removed, so if they are in Charm++ they need to go.
See http://blogs.cisco.com/performance/the-mpi-c-bindings-what-happened-and-why

**Comment by stwhite91** [comment]
*Original date: 2016-09-14 19:11:20*

---
We do not use the MPI C++ bindings proper, we only use MPI's C language bindings. We obviously need a C++ compiler to build Charm, so we use the mpicxx compiler wrapper.

**Comment by pplimport** [comment]
*Original author: Erik Schnetter*
*Original date: 2016-09-14 19:37:54*

---
I see symbols like these:

$ nm -A *.a | grep MPI | grep __ | grep Init
libck.a:mpi-interoperate.o: 0000000000000970 S __ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb
libmpi-mainmodule.a:mpi-mainmodule.o: 0000000000000f80 S __ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb

These are C++-mangled functions from the C++ MPI bindings. Do they point to an error in my configuration options?

**Comment by pplimport** [comment]
*Original author: Erik Schnetter*
*Original date: 2016-09-14 19:39:41*

---
Note: There are also references to external symbols ("U"), as in

libck.a:mpi-interoperate.o:                  U __ZN3MPI3Win4FreeEv

**Comment by pplimport** [comment]
*Original author: Erik Schnetter*
*Original date: 2016-09-15 14:15:20*

---
I encountered the same issue in another project as well. It seems that OpenMPI's "mpi.h" pulls in the C++ MPI bindings when the file is included from a C++ compiler. While "mpicc --showme" doesn't list "mpi_cxx", "mpicxx --showme" does:

$ mpicxx --showme:libs
mpi_cxx mpi

**Comment by stwhite91** [comment]
*Original date: 2016-09-15 16:16:59*

---
It looks like you can pass the '--disable-mpi-cxx' option to OpenMPI's configure script to avoid that if you are building it yourself. That flag is actually passed by default.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-15 16:19:38*

---
There's a simple solution to all this. We change our configure script to use `test_cc` instead of `test_cxx`, since we don't want/need the C++ bindings, and we're only calling MPI from C code in the machine layer.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-15 16:34:01*

---
My above hypothesized fix is here:
~~https://charm.cs.illinois.edu/gerrit/1852~~ https://github.com/UIUC-PPL/charm/commit/6010203118ce9fbf85aeb0d8db3e3640e07a8fb3

I have not even tested that this works yet. Busy today, but if someone else wants to grab it and say good/bad before I get back to it, go for it.

**Comment by PhilMiller** [comment]
*Original date: 2016-10-02 17:24:16*

---
Follow-on fix that's actually been tested here:
~~https://charm.cs.illinois.edu/gerrit/#/c/1895/~~ https://github.com/UIUC-PPL/charm/commit/ddf91af85ebf687a75bcee377c2cebecbfbf42d8
