### ISSUE TITLE
Abort on message sends to out-of-bounds chare array elements

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1216]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1216*

---
If a message is sent to a chare array element that is out-of-bounds for a statically sized chare array, we should abort instead of sending a message.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-09 18:05:27*

---
~~https://charm.cs.illinois.edu/gerrit/2041~~ https://github.com/UIUC-PPL/charm/commit/7ab0fbabb766d911c68bb39242cfe9fd0dba4b57
