### ISSUE TITLE
Update SDAG forall documentation

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1219]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1219*

---
SDAG's forall statement is barely explained in the manual. It should be clear that forall(..) { serial{ ... } } does not execute the loop body in parallel, as SDAG forall is basically an unordered SDAG for.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 17:13:26*

---
~~https://charm.cs.illinois.edu/gerrit/2526~~ https://github.com/UIUC-PPL/charm/commit/fa8b1552f7731a0aaedad3634382a8617cbba368
