### ISSUE TITLE
Win build failures

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1221]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1221*

---
Since merging 64bit IDs the *-win autobuild tests are failing with a n assertion from ckobjid.h:

```
testrun  ./pgm +p1  ++local
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.031 seconds.
Converse/Charm++ Commit ID: 0d953aa
[0] isomalloc.c> Disabling isomalloc because mmap() does not work
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Megatest is running on 1 nodes 1 processors. 
test 0: initiated [groupring (milind)]
test 0: completed (0.00 sec)
test 1: initiated [nodering (milind)]
test 1: completed (0.00 sec)
test 2: initiated [varsizetest (mjlang)]
test 2: completed (0.00 sec)
test 3: initiated [varsizetest2 (phil)]
test 3: completed (0.00 sec)
test 4: initiated [varraystest (milind)]
test 4: completed (0.00 sec)
test 5: initiated [groupcast (mjlang)]
test 5: completed (0.00 sec)
test 6: initiated [groupmulti (gengbin)]
test 6: completed (0.00 sec)
test 7: initiated [groupsectiontest (ebohm)]
test 7: completed (0.00 sec)
test 8: initiated [multisectiontest (ebohm)]
test 8: completed (0.00 sec)
test 9: initiated [nodecast (milind)]
test 9: completed (0.00 sec)
test 10: initiated [synctest (mjlang)]
varsize: requires at least 2 processors
varraystest: requires at least 2 processors
groupsectiontest: requires at least 2 processors
multisectiontest: requires at least 2 processors
[0] Assertion "(CmiUInt8)gid.idx <= (COLLECTION_MASK >> ELEMENT_BITS)" failed in file C:\cygwin\home\nikhil\autobuild\net-win64\charm\net-win64\include\objid.h line 22.
------------- Processor 0 Exiting: Called CmiAbort ------------

```

**Comment by stwhite91** [comment]
*Original date: 2016-09-29 13:28:06*

---
mpi-win jobs are not being launched correctly, we're getting 4 1-PE jobs instead of 1 4-PE job:
```
Reason: PE count 1 doesn't match expectation 4

```

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 16:42:17*

---
Include lrtslock.h for all Windows builds: ~~https://charm.cs.illinois.edu/gerrit/#/c/2018/~~ https://github.com/UIUC-PPL/charm/commit/4d3f69c8db603bfed43defa5bec4579a62d1a511

Add custom charmrun for mpi-win64 that calls mpiexec instead of mpirun: ~~https://charm.cs.illinois.edu/gerrit/#/c/2019/~~ https://github.com/UIUC-PPL/charm/commit/ce38522ef6aa821c7c6466d72c772430768d0681

PICS: Avoid dynamic stack arrays to stay strictly conformant (for MS VC++): ~~https://charm.cs.illinois.edu/gerrit/#/c/2021/~~ https://github.com/UIUC-PPL/charm/commit/c42386617734e28f146a1250ceb23e2f42ed7aa8

Current status:
net-win64 fails when linking first example/test program, with LrtsLocks undefined.
mpi-win64 now fails in first AMPI test because it picks up system MPI instead of AMPI's header.
multicore-win64 fails for AMPI programs with vp < p.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 18:38:29*

---
We're not seeing this failure at all anymore. There are others, but they seem less fundamental.
