### ISSUE TITLE
Document MetaLB

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1223]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1223*

---
There's no mention in the manual of MetaLB. I'm finding that several of us frequently suggest users take advantage of it, rather than manually tweaking LB intervals, and then have to describe what and how it should be used directly.

The manual should describe what MetaLB is, how to activate it, and how its use changes ideal program design.

**Comment by stwhite91** [comment]
*Original date: 2016-12-28 17:38:10*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2079/~~ https://github.com/UIUC-PPL/charm/commit/aef053d526e31a55258c78d2890accfbcab09e3a
