### ISSUE TITLE
Document TRAM [aggregate] entry method attribute

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1225]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1225*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:12*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by epmikida** [comment]
*Original date: 2017-04-10 16:59:51*

---
This is already documented in the libraries manual, where all of TRAM is documented. Is that sufficient, or do we want to transfer some/all of that documentation over to the main manual?

**Comment by PhilMiller** [comment]
*Original date: 2017-04-10 17:04:17*

---
That bit of documention can be reduced, since the header and module linkage is now automatic. The [aggregate] entry method API should be documented in the main Charm++ manual.

**Comment by epmikida** [comment]
*Original date: 2017-04-12 00:38:23*

---
Implemented in ~~https://charm.cs.illinois.edu/gerrit/#/c/2388/~~ https://github.com/UIUC-PPL/charm/commit/61bd4f95b5aa8110b71f3847a94b5aa65ad2f82b
