### ISSUE TITLE
Field width/mask definitions present undefined behavior due to too-wide shifts

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1228]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1228*

---
MS Visual C++ complains quite noisily that the shifts used to implement the various bit-fields of the overall 64-bit ID are wider than the field definition types themselves, resulting in undefined behavior.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 20:17:27*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1887/~~ https://github.com/UIUC-PPL/charm/commit/f22b89a9b6f33a738f555a73ff618a7c7cc3c33a1

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 20:35:38*

---
That patch is now merged, but there's some other issue on at least my tests of net-win64. We'll see what autobuild says tomorrow.

**Comment by stwhite91** [comment]
*Original date: 2016-09-29 13:26:59*

---
Same failure as yesterday on net-win64:
```
[0] Assertion "(CmiUInt8)gid.idx <= (COLLECTION_MASK >> ELEMENT_BITS)" failed in file C:\cygwin\home\nikhil\autobuild\net-win64\charm\net-win64\include\objid.h line 22.

```

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 18:38:29*

---
We're not seeing this failure at all anymore. There are others, but they seem less fundamental.
