### ISSUE TITLE
Avoid sender-side copy for large contiguous messages. API for charm and converse layers

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1234]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1234*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 18:36:12*

---
Still waiting on the SMP fix

**Comment by PhilMiller** [comment]
*Original date: 2017-02-09 19:44:11*

---
From minutes of the last core meeting:

> Callback fix to invoke on sending PE and not comm thread implemented. 
> 
> Another crash to fix.
>
> GNI implementation needs testing against revised infrastructure.
> 
> GNI still has alignment issue - RDMA GET needs 4 byte alignment, RDMA PUT does not. Nitin intends to see full solution implemented quickly.

Putting this here so status is clearly visible and easily located.

**Comment by jcphill** [comment]
*Original date: 2017-02-14 22:19:10*

---
The initial implementation of this doesn't need to be based on RDMA. The problem is not that the data is copied, but that additional memory equal to the full data size is used. Flow-controlled message streaming would allow the data to be transferred without blowing up memory usage.

**Comment by jcphill** [comment]
*Original date: 2017-02-18 19:26:31*

---
Assuming pup methods are available for the data, it should be possible to run the pup in a Cthread with the data going into a flow-controlled message stream.

**Comment by jcphill** [comment]
*Original date: 2017-02-23 13:47:37*

---
It would be good to have an MPI implementation as well.  Should be easy, since MPI 1.0 supported sending data in place.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-03 15:46:24*

---
API patch merged:
~~https://charm.cs.illinois.edu/gerrit/1273~~ https://github.com/UIUC-PPL/charm/commit/b01313ece18286048768cc3832dcd532423cfd66

As expected, no breakage in autobuild resulted.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-14 20:55:40*

---
API and some machine layer implementations merged. Other machine layers are still pending, but we want to check the box for the beta release.
