### ISSUE TITLE
Avoid receiver-side copy for large contiguous messages. API for charm and converse layers

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1236]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1236*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2017-04-22 15:25:08*

---
It would be good to know what is working and what isn't in this patch: https://charm.cs.illinois.edu/gerrit/#/c/1939/

**Comment by PhilMiller** [comment]
*Original date: 2017-06-20 13:56:48*

---
Since Vipul has left the group, and Nitin is picking up further RDMA work.

**Comment by nitbhat** [comment]
*Original date: 2018-01-12 15:48:43*

---
With the Direct API getting merged for 6.9.0, I think there is no pressing need to have this in 6.9.0. Since there is quite a bit of work to get this working for the generic layer, I'm pushing it for 6.9.1.

**Comment by nitbhat** [comment]
*Original date: 2019-01-16 16:47:24*

---
Gerrit: ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4820~~ https://github.com/UIUC-PPL/charm/commit/0d441637ac6c0dc27b4c08d919a4b9a453d2b98f
