### ISSUE TITLE
Onesided sender side implementation for GNI layer

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1237]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1237*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 18:34:59*

---
~~https://charm.cs.illinois.edu/gerrit/1908~~ https://github.com/UIUC-PPL/charm/commit/27595aa83f8bf95bf0a87ff92925707f32175f59
Works for sizes that aren't multiples of 4, but not for base addresses that are not aligned to multiples of 4.

There's a design for lifting that implementation (using GNI PUT, which isn't constrained like GNI GET) but it can come later.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-14 20:41:36*

---
Since there's still several things to fix up here, and we want to get the beta out the door, we're deferring this to the main release.

**Comment by stwhite91** [comment]
*Original date: 2017-04-22 15:18:32*

---
It looks like Nitin has been doing work on this too, so might need to coordinate.

**Comment by nitbhat** [comment]
*Original date: 2017-04-25 20:54:59*

---
Implementing PUT calls from Sender to Receiver for non-aligned memory addresses as RDMA GET expects 4-byte aligned addresses and length.

**Comment by nitbhat** [comment]
*Original date: 2017-05-22 14:52:51*

---
Feature: ~~https://charm.cs.illinois.edu/gerrit/#/c/1908/~~ https://github.com/UIUC-PPL/charm/commit/27595aa83f8bf95bf0a87ff92925707f32175f59
 - Used buffering of short messages for sending messages when they go out of "credits". The messages are buffered and get sent periodically 
 - Implemented PUT for unaligned cases (when source address, dest address and the length are not 4 byte aligned)
 - Deregistered memory on completion of RDMA requests
 

To do: 
 - Improve performance by optimizing registration (probably in some other patch as it is relevant for verbs as well)

**Comment by PhilMiller** [comment]
*Original date: 2017-06-19 03:14:52*

---
Looks like there's a hang in `tests/util` since merging this. Hopefully it's something simple to fix, since the higher-level code was tested to be working. Or, more hopefully, it was a spurious failure.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-19 15:02:21*

---
Hang issue did not reproduce in extended testing. Re-closing

**Comment by stwhite91** [comment]
*Original date: 2017-07-13 03:06:43*

---
Related patches merged:

Allocate machine specific info along with the charm message: ~~https://charm.cs.illinois.edu/gerrit/#/c/2758/~~ https://github.com/UIUC-PPL/charm/commit/8b554d03597f75d1f2e4ba547ad09ecf0170edb6

Store ack message data before releasing it: ~~https://charm.cs.illinois.edu/gerrit/#/c/2743/~~ https://github.com/UIUC-PPL/charm/commit/9823be9c42ef44bfd530ff39feb7f03665be88b7

Free smsgs used in RDMA for gni-crayxe builds: ~~https://charm.cs.illinois.edu/gerrit/#/c/2768/~~ https://github.com/UIUC-PPL/charm/commit/79d982b68dc06c79b8b3380ab08b5529e7a6b332
