### ISSUE TITLE
Onesided sender side implementation for Verbs layer

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1238]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1238*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2016-11-03 04:37:15*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1960/~~ https://github.com/UIUC-PPL/charm/commit/ae20298702767bd08cfe875b3f30a702ed84b010
