### ISSUE TITLE
Cleanup reduction uses in the runtime

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1239]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1239*

---
Here are some best practices for Charm++ reductions that are not always followed in the runtime:

1. You should use built-in reducer types whenever possible, as in nop and tuple reducers.
    - For reductions that have no contribution data and are only as synchronization points, prefer contribute(cb). Many places (see src/ck-ldb/ for examples) use contribute(0, NULL, CkReduction::sum_int, cb) instead. You can grep for "contribute(0" to find them.
    - Look for custom reducer types (in src/ck-cp/, src/ck-perf/, and src/ck-ldb/) that could be expressed more simply as built-in reductions (most likely as tuple reductions).

2. The callback should be a [reductiontarget] entry method unless the result message is saved by the recv'er to be used later or the contribution is non-POD.
    - This makes the code easier to read and takes away the responsibility of the recv'er to delete the message (plus [reductiontarget]'s are also [nokeep]).

3. Avoid having an extra copy on the sender side when possible. Reduction contributions are sometimes done via a temporary array. This incurs an extra dynamic memory allocation and copy on the sender, since the reduction framework needs to copy that array into a CkReductionMsg. Instead of allocating a temporary array, just allocate a CkReductionMsg and fill its data field with the contribution data directly and then contribute that. See src/ck-perf/trace-projections.C for a couple examples of extra copies.

**Comment by stwhite91** [comment]
*Original date: 2016-09-29 22:07:31*

---
4. Do not use ckSetReductionClient, instead pass the callback to the contribute method. This makes the control flow easier to follow for readers of the code.

**Comment by stwhite91** [comment]
*Original date: 2016-10-04 20:47:18*

---
ck-ldb cleanup (except for the custom reduction type 'lbDataCollectionType' in MetaBalancer.C): ~~https://charm.cs.illinois.edu/gerrit/#/c/1898/~~ https://github.com/UIUC-PPL/charm/commit/795a6c0e490a9f19c3ce58363887c4b2626e805f

**Comment by stwhite91** [comment]
*Original date: 2016-10-28 04:34:59*

---
ck-perf/ cleanup (except for 2 custom reductions): ~~https://charm.cs.illinois.edu/gerrit/#/c/1926/~~ https://github.com/UIUC-PPL/charm/commit/fe4b831d162726082f80a0ea65e20962aa22ccd8

**Comment by karthiksenthil** [comment]
*Original date: 2016-10-29 01:12:01*

---
ck-perf cleanup update :
The 2 custom reductions in ck-perf/trace-projections.C which can be changed into tuple reductions are _outlierReduction_ and _minMaxReduction_. These changes would also need some redesign in their corresponding reductiontarget functions i.e _globalMetricRefinement_ and _findNextMinMax_.

**Comment by stwhite91** [comment]
*Original date: 2016-11-30 17:35:46*

---
Only ck-ldb and ck-perf have been looked over and cleaned up. ck-cp, ck-pics, and ck-core remain.

**Comment by stwhite91** [comment]
*Original date: 2017-02-10 17:31:43*

---
Another note for optimizing reductions:

If a custom reduction uses a fixed size message (the messages size doesn't grow with each contribution like for CkReduction::set or concat), it should be made 'streamable'. To do that, change the 'addReducer(refucerFn)' call to 'addReducer(reducerFn, true)'.

Also, all custom reductions with fixed sized messages should avoid intermediate memory allocation/copies. So if a reducer function looks like this:
```
CkReductionMsg* reducerFn(int nMsgs, CkReductionMsg** msgs) {
  double data[MSG_LEN]; // allocate temporary data array
  for (int i=0; i<MSG_LEN; i++) {  // copy the first message's data into temp
     data[i] = (double *)msgs[0]->getData()[i];
  }
  for (int i=1; i<nMsgs; i++) { // processes remaining messages
     for (int j=0; j<MSG_LEN; j++) {
       data[j] += (double *)msgs[i]->getData()[j];
     }
  }
  CkReductionMsg *retMsg = CkReductionMsg::buildNew(MSG_LEN * sizeof(double), data);
  return retMsg;
}
```

It can be rewritten to operate on the first message in place:
```
CkReductionMsg* reducerFn(int nMsgs, CkReductionMsg** msgs) {
  double *data = (double *)msgs[0]->getData(); // use msgs[0] directly instead of a temporary array
  for (int i=1; i<nMsgs; i++) { // processes remaining messages
     for (int j=0; j<MSG_LEN; j++) {
       data[j] += (double *)msgs[i]->getData()[j];
     }
  }
  return msgs[0];
}
```

**Comment by pplimport** [comment]
*Original author: Justin Szaday*
*Original date: 2017-07-17 16:36:07*

---
I cleaned up all of the uses of `setReductionClient` in the tests except for those in `tests/charm++/megatest/reduction.C`, since they use unusual reductions that I was unsure how to port to a `CkCallback.` I also cleaned up all of the uses in the examples except for those in the `pencilFFT` and `msa` tests – as they were implied to be either deprecated or scheduled to be deprecated.

**Comment by stwhite91** [comment]
*Original date: 2017-08-03 20:26:06*

---
Can you add links to those gerrit patches here?

**Comment by stwhite91** [comment]
*Original date: 2018-03-15 19:49:05*

---
Remove uses in tests/ and examples/ directories:

~~https://charm.cs.illinois.edu/gerrit/#/c/2792/~~ https://github.com/UIUC-PPL/charm/commit/f952f4ed9b67606e71d0c1db9be8ca5891f4dd77
~~https://charm.cs.illinois.edu/gerrit/#/c/2800/~~ https://github.com/UIUC-PPL/charm/commit/92460f29f401990a3d448079b4cb89d7d1b43452
