### ISSUE TITLE
MPI_COMM_SELF handling issues in AMPI

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1240]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1240*

---
AMPI creates 1d chare arrays for each communicator, except for MPI_COMM_SELF, for which we avoid creating a chare (to save memory?) and instead handle as a corner case everywhere.
So far we have found issues in Intercomm_create and Comm_split, but all of the communicator and topology routines should be reviewed to make sure they handle it correctly.

This is blocking work on Intercomm_create and Comm_create_group.

**Comment by stwhite91** [comment]
*Original date: 2016-11-08 23:51:41*

---
The MPI_Comm_split failures have been observed in XPACC.

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-19 04:37:17*

---
MPI_Comm_dup with a MPI_COMM_SELF communicator to duplicate also is not handled correctly (ampi::splitReduce expected a split contribution from every rank!). This breaks some functionality in ROMIO.

**Comment by stwhite91** [comment]
*Original date: 2017-06-27 20:32:47*

---
This patch has some improvements, but is still broken for the ROMIO MPI_COMM_SELF MPI_Comm_dup case: https://charm.cs.illinois.edu/gerrit/#/c/2570/

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-27 20:38:00*

---
To fix this properly, we might have to implement full support for MPI_COMM_SELF in AMPI. For example, how would MPI_Comm_set_attr() work on MPI_COMM_SELF without this support?

**Comment by stwhite91** [comment]
*Original date: 2017-07-06 15:53:29*

---
Yes, I'm working on the full support now

**Comment by stwhite91** [comment]
*Original date: 2017-07-06 17:59:29*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2753/~~ https://github.com/UIUC-PPL/charm/commit/498a9f717ecfcadd6d2c001524944593609cd20c

**Comment by stwhite91** [comment]
*Original date: 2017-07-06 17:59:47*

---
It would probably be good to get this into 6.8.0

**Comment by stwhite91** [comment]
*Original date: 2017-07-06 23:32:22*

---
Related: make collectives optimizations for MPI_COMM_SELF apply to all comms with size of 1: ~~https://charm.cs.illinois.edu/gerrit/#/c/2755/~~ https://github.com/UIUC-PPL/charm/commit/0258b73eaf92fa40cac0a4c7e151671e6f98d613
