### ISSUE TITLE
Deprecate setReductionClient and CkSetReductionClient

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1249]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1249*

---
setReductionClient and CkSetReductionClient make Charm++ application control flow harder to read.
The alternative of passing the callback to the contribute() site is much nicer.

Add a note to the next release notes (6.8.0).

This is related to this issue: https://charm.cs.illinois.edu/redmine/issues/1239

**Comment by rbuch** [comment]
*Original date: 2016-11-02 22:52:07*

---
Implemented in ~~https://charm.cs.illinois.edu/gerrit/#/c/1962/~~ https://github.com/UIUC-PPL/charm/commit/953363e09465e3f7947d57f773771e5b46b238c7.
