### ISSUE TITLE
Document shrink/expand in the manual

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1251]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1251*

---
There is nothing in the Charm++ manual about using shrink/expand yet. Add that to an appropriate area of the manual

**Comment by ericjbohm** [comment]
*Original date: 2017-04-11 20:56:41*

---
Add this to the experimental features section.

**Comment by bilgeacun** [comment]
*Original date: 2017-05-03 19:43:38*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2492/~~ https://github.com/UIUC-PPL/charm/commit/9a7c51e7295689ec7ef2d750c4cea3812d0489ba
