### ISSUE TITLE
AMPI missing built-in MPI_INFO_ENV

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1259]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1259*

---
From the MPI standard:

After MPI is initialized, the application can access information about the execution environment by querying the predefined info object MPI_INFO_ENV. The following keys are predefined for this object, corresponding to the arguments of mpiexec:

```
command: name of program executed.
argv: space separated arguments to command.
maxprocs: maximum number of MPI processes to start.
soft: allowed values for number of processors.
host: hostname.
arch: architecture name.
wdir: working directory of the MPI process.
file: value is the name of a file in which additional information is specified.
thread_level: requested level of thread support, if requested before the program started execution.
```

Note that all values are strings. Thus, the maximum number of processes is represented by a string such as "1024" and the requested level is represented by a string such as "MPI_THREAD_SINGLE".
The info object MPI_INFO_ENV need not contain a (key,value) pair for each of these predefined keys; the set of (key,value) pairs provided is implementation-dependent. Implementations may provide additional, implementation specific, (key,value) pairs.

**Comment by stwhite91** [comment]
*Original date: 2016-10-15 17:16:21*

---
We might want to supply builtin MPI_Info objects for AMPI_Migrate, so users don't have to always create their own. This will simplify adding AMPI_Migrate calls to applications from 4 lines to 1 line:

Predefined MPI_Infos for AMPI_Migrate:
```
AMPI_INFO_LB_SYNC
AMPI_INFO_LB_ASYNC
AMPI_INFO_CHKPT_IN_MEMORY
```

Example new usage:
```
AMPI_Migrate(AMPI_INFO_LB_SYNC);
```

This is much simper than the old way:
```
MPI_Info info;
MPI_Info_create(&info);
MPI_Info_set(info, "ampi_load_balance", "sync");
AMPI_Migrate(info);
```

This would be done in a separate commit anways, just an idea...

**Comment by stwhite91** [comment]
*Original date: 2017-08-30 23:05:22*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2968/~~ https://github.com/UIUC-PPL/charm/commit/8aea54448d3d4d2a368ccc64b391e8c2d90d11e6

**Comment by karthiksenthil** [comment]
*Original date: 2017-08-30 23:21:36*

---
Should I submit another patch defining the MPI_Info objects to simplify AMPI_Migrate calls?

**Comment by stwhite91** [comment]
*Original date: 2017-08-30 23:41:06*

---
Yes
