### ISSUE TITLE
Document process launching arguments with aim of cross-machine rationalization

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#126]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/126*

---
The handling of +p, ++p, +n, +ppn, ++ppn options are inconsistent across various machine layers. We need to clearly understand where and how these options are handled on various machine layers (net, LRTS-based, others), with and without SMP. The goal is ultimately to rationalize the handling of these arguments across systems to provide a consistent interface for application users.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-04-05 19:44:31*

---

https://wiki.engr.illinois.edu/display/ppl/Process+Launch+Parameters

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:20:49*

---
This likely ends up being obviated by the shift to hwloc-driven launch

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 05:42:47*

---
hwloc launch parameters obviate the need for this
