### ISSUE TITLE
AVX512 Support

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#1263]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1263*

---
Add support for AVX512 instructions in Charm++'s SIMD instruction library.

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 06:09:22*

---
Are there users of this library? If not, we might want to remove it.

**Comment by ajithvallabai** [comment]
Hey is this support really added and tested ?

**Comment by rbuch** [comment]
> Hey is this support really added and tested ?

No, we never added support for AVX512 in our own SIMD library (`util/SSE-{Float/Double}.h`) since the desired support was added elsewhere. Note that this doesn't have anything to do with compiling with an AVX512 flag, just what functionality our SIMD library offers. 

In any case, I'm closing this issue for now since it's effectively deprecated.
