### ISSUE TITLE
Integrate METIS graph partitioning library patched for global variable privatization

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1267]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1267*

---
METIS mostly marks its statics and globals with `__thread`, but misses a few. Since it was previously removed from our repository, it has now been released under the liberal Apache 2.0 open source license. SO, we can bundle a patched version for use with MetisLB, AMPI, ParFUM, and ParMETIS-based parallel partitioning in ParFUM.

**Comment by kavithachandrasekar** [comment]
*Original date: 2016-11-09 19:27:46*

---
### Is it okay to add the library to src/libs/ck-libs with appropriate changes in the Makefile?

**Comment by PhilMiller** [comment]
*Original date: 2016-11-09 19:38:50*

---
Please go ahead with the re-integration there, with suitable Makefile changes. I'll add a couple follow-on tasks.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-09 19:53:41*

---
When you add METIS into the makefiles, please include it as a dependency of ParFUM.
