### ISSUE TITLE
multicore-win64, netlrts-win-x86_64: megampi fails when +vp < +p

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1269]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1269*

---
In working on #1221 / #1228, I've narrowed down to a particular phenomenon that seems distinctive. The megampi test runs fine if the number of AMPI ranks is greater than or equal to the number of PEs. If the number of ranks is less than the number of PEs, it aborts at startup with no useful output.

**Comment by stwhite91** [comment]
*Original date: 2016-11-06 17:27:07*

---
It seems to work for me with current master on dexterity, using './build AMPI multicore-win64 -j8 --with-production -g':
```
$ ./charmrun +p4 ./pgm.exe +vp1
Running command: ./pgm.exe +vp1 +p4

Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode:  4 threads
Charm++ warning> fences and atomic operations not available in native assembly
Converse/Charm++ Commit ID: v6.7.0-rc2-440-g6fd1062
[0] isomalloc.c> Disabling isomalloc because mmap() does not work
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.016 seconds.
[0] RandCentLB created
[0] Testing: Testing...
[0] Testing: Testing...
[0] Testing: Testing...
[0] Testing: Testing...
All tests passed

```

**Comment by stwhite91** [comment]
*Original date: 2016-11-06 18:47:26*

---
Fixing a race condition in trying to create array elements for not-yet-constructed managers seems to have solved this issue: ~~https://charm.cs.illinois.edu/gerrit/#/c/1964/~~ https://github.com/UIUC-PPL/charm/commit/441220e9864ea11ca62ed58d43edf37dd11d6c78

**Comment by PhilMiller** [comment]
*Original date: 2016-11-07 18:11:04*

---
Still failing on multicore-win64 in autobuild
https://charm.cs.illinois.edu/autobuild/old.2016_11_07__01_01/multicore-win64.txt
https://charm.cs.illinois.edu/autobuild/old.2016_11_06__01_01/multicore-win64.txt
https://charm.cs.illinois.edu/autobuild/old.2016_11_05__01_02/multicore-win64.txt

**Comment by PhilMiller** [comment]
*Original date: 2016-12-02 20:37:20*

---
Ronak and I got the code to run under Visual Studio's debugger, and could actually examine the stack, variables, etc.

We saw that the crash is during AMPI_Init, and there's a reduction going to an `ampi` chare array instance with an apparently negative group ID. That could come from mistaken construction of the array off PE0, perhaps, but I don't think that should be happening in this case.

At least we have a means to investigate it now.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-02 22:15:22*

---
Oh, and an important note about why Sam saw the code pass in comment 3 above: the crash results from an assertion failure, so without `--enable-error-checking`, it runs straight through. Which kinda makes me wonder why the code is constructing what looks like an invalid object ID, but still seems to run cleanly.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 04:14:42*

---
With new assertions added, that test now fails with the synchronous array creation off PE0 condition. Modifying the startup code to do that using the asynchronous interface. Some weird mapping thing that only lands rank 0 on PE1 when we're compiling with VC++ and running with fewer than P VPs.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 04:31:56*

---
Not directly tested on Windows, since I'm impatient and it's slow, but hypothetical fix here:
~~https://charm.cs.illinois.edu/gerrit/2076~~ https://github.com/UIUC-PPL/charm/commit/553c5bfaa29a934dd55ef0f9e8eaee06b55ebd34
