### ISSUE TITLE
Node GPU Manager hangs on exit

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1272]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1272*

---
Tests of the SMP GPU Manager changeset ~~https://charm.cs.illinois.edu/gerrit/#/c/1886/~~ https://github.com/UIUC-PPL/charm/commit/7b5173bc361d6d94ca342ae9e5beec3bc869fea84 are hanging on exit.
This is on blue waters.  The build is done with:
./build ChaNGa gni-crayxe cuda smp hugepages -j8 -O2
(note: no "--with-production")
and changa is configured with:
./configure --with-cuda=/opt/nvidia/cudatoolkit7.0/7.0.28-1.0502.10742.5.1

ChaNGa is run with: (see bluewaters:~trq/test/forces/gpu for test4 param and data files)
aprun -n 1 -N 1 -d 16 ./ChaNGa -theta $theta +ppn 15 +setcpuaffinity +commap 0 +pemap 1-15 test4_changa.param
About 30-50% of the time this will hang after printing:
EXIT HYBRID API
[Partition 0][Node 0] End of program

Debugging statements show that one thread never calls ConverseExit(), so the CmiNodeAllBarrier() blocks.  This implies (and debugging statements show) that one thread never gets the "StatDoneMsg" broadcast from _exitHandler().

**Comment by trquinn** [comment]
*Original date: 2016-10-29 19:50:56*

---
The same problem happens on a standard cluster (Plieades in this case), and a debugger revealed the issue:
threads are stuck in gpuProgressFn() waiting for gpuManager.progressLock, but this lock has been destroyed in exitHybridAPI().

**Comment by trquinn** [comment]
*Original date: 2016-11-08 17:40:51*

---
ping

**Comment by stwhite91** [comment]
*Original date: 2016-12-13 17:59:30*

---
Fixed in patch set #7 here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1886/~~ https://github.com/UIUC-PPL/charm/commit/7b5173bc361d6d94ca342ae9e5beec3bc869fea8
