### ISSUE TITLE
Tracemode utilization produces incorrect results for EP utilization metric

### ISSUE THREAD

**Issue by minitu** [UIUC-PPL/charm#1274]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1274*

---
Even if a Charm++ program is successfully connected to Projections via the Streaming CCS Tool,
two graphs showing the EP utilization metric (Streaming Utilization Plot, Detailed Utilization Plot) do not produce any data.
The only graph that seems to work is the Message Sizes graph. Tested with wave2d.

Graphs:
![livestreaming_ccs_error_1_1](https://user-images.githubusercontent.com/1772435/63629170-1a835a80-c5d6-11e9-9b69-c1c27f970df5.png)
![livestreaming_ccs_error_1_2](https://user-images.githubusercontent.com/1772435/63629171-1a835a80-c5d6-11e9-834f-7401a5809eaa.png)

Terminal outputs of Projections and wave2d:
![livestreaming_ccs_error_2_1](https://user-images.githubusercontent.com/1772435/63629174-1fe0a500-c5d6-11e9-8fba-1c2af894a97b.png)

**Comment by rbuch** [comment]
*Original date: 2017-02-14 18:34:06*

---
These were fixed as far as I remember, but I think Karthik had the relevant information (I sat down with him at his desk to fix this and he was supposed to make the logs afterward, I think).  I'll check back to see if these were really done.

**Comment by stwhite91** [comment]
*Original date: 2018-01-10 01:25:12*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3491/~~ https://github.com/UIUC-PPL/charm/commit/c4c6ac200d1b5f291ac3fbb92e06c478fe4d606c
