### ISSUE TITLE
DistributedLB: Objects not migrating after strategy runs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1275]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1275*

---
Will attach a demonstration case shortly

[simple-pic-charm.tgz](https://github.com/UIUC-PPL/charm/files/3536607/simple-pic-charm.tar.gz)

**Comment by stwhite91** [comment]
*Original date: 2016-11-02 18:46:08*

---
Eric M just submitted a patch for an issue with DistributedLB: ~~https://charm.cs.illinois.edu/gerrit/#/c/1951/~~ https://github.com/UIUC-PPL/charm/commit/4967eeebd89c4e120d07bd93fedfcfebd043e9c2

**Comment by PhilMiller** [comment]
*Original date: 2016-11-02 19:00:48*

---
Neither of the pending patches in Gerrit resolves this issue.

Demonstration code attached.

**Comment by kavithachandrasekar** [comment]
*Original date: 2016-11-02 22:24:38*

---
The migration phase after strategy phase seems to work okay for me. In the Makefile, the test uses 2 PEs. I believe we need atleast 3 PEs, since each underloaded PE sends info to 2 random neighbors. With +p2 it would hang in trying to find a second neighbor:

do {
    rand_nbor2 = rand() % CkNumPes();
  } while ((rand_nbor2 == CkMyPe()) || (rand_nbor2 == rand_nbor1));

**Comment by PhilMiller** [comment]
*Original date: 2016-11-02 22:34:49*

---
The potential to hang on 2 PEs seems like it should also be fixed.

I was running on 40 PEs when I observed the issue. I think I know what could be causing the lack of migration in that case. The overloaded PEs have objects that each would take an underloaded PE all the way past the average, past the overload threshold, to overloaded. Right now, the underloaded PEs will reject the load in that case, and the overloaded PE will keep trying to find a recipient. In this circumstance, it will _never_ find a willing recipient. Does that make sense?

If my hypothesis is right, I think what the strategy should do instead is accept load transfers if the resulting arrangement is sufficiently less overloaded than it was without making the transfer. Maybe the previously underloaded PE can then also try to shed some of its load. Or, if we're planning on using MetaLB anyway, we can just let it take some of the overload, improving the situation to some degree, and trust that the strategy will be run again soon.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-02-06 17:10:05*

---
As you suggest, this might make the receiver PE overloaded, thereby not migrating objects. Before sending to an underloaded PE, the donor PE checks that transferring object to receiver PE does not make it overloaded (i.e (p_load + obj->load) < avg_load). 

To check if it becomes sufficiently less overloaded overall, we could add a condition, ((p_load + obj->load) < avg_load) *|| (p_load + obj->load) < my_load* ) which could increase the migrations performed. When run on a single node, this logic seems to increase the initial migrations. Need to perform testing at scale.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-26 04:08:30*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2437/~~ https://github.com/UIUC-PPL/charm/commit/19f7f08245d8f44d5ebaba8cbcb15e54a437df51 to fix hang when there are only 2 PEs.

**Comment by rbuch** [comment]
*Original date: 2017-04-27 21:09:29*

---
Does your patch fix this in general or just for the 2 PE case, Kavitha?

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-27 21:15:03*

---
It fixes only for 2 PE case. The migration issue will likely be fixed with ~~https://charm.cs.illinois.edu/gerrit/#/c/1951/~~ https://github.com/UIUC-PPL/charm/commit/4967eeebd89c4e120d07bd93fedfcfebd043e9c2. With the fixes in that patch/branch, objects usually migrate as expected.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-05-11 15:04:45*

---
I have updated the gerrit patch ~~https://charm.cs.illinois.edu/gerrit/#/c/1951/~~ https://github.com/UIUC-PPL/charm/commit/4967eeebd89c4e120d07bd93fedfcfebd043e9c2 with Harshitha's fix from her branch. This version of DistributedLB performs load balancing in multiple phases, when the target threshold is not met, it attempts another phase of load balancing with an updated threshold. For a simple stencil load-balancing example, it performs migrations and balances load as expected.
