### ISSUE TITLE
net-cygwin: multiple testing failures

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1276]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1276*

---
Please open sub-issues for the currently observed individual failures

**Comment by PhilMiller** [comment]
*Original date: 2016-11-08 01:20:11*

---
In a non-production build, all seems to run successfully. That contradicts autobuild, but I haven't manually tested `--with-production` yet.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-08 02:14:22*

---
The list of substasks reporting individual failures using `--with-production --enable-error-checking` should be exhaustive.

**Comment by rbuch** [comment]
*Original date: 2017-02-14 21:48:28*

---
The net-cygwin target is no longer relevant.
