### ISSUE TITLE
Multiple shrink expand requests lead to segmentation fault

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1277]
*Original author: Justin Miron*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1277*

---
If a CCS client issues multiple shrink expand requests, the application segmentation faults.

The issue is with command line flag handling and appending new flags during the shrink expand requests.

**Comment by pplimport** [comment]
*Original author: Justin Miron*
*Original date: 2016-11-02 22:52:52*

---
The shrink expand restarts the application using a new command line string. This new string would copy the old command line args and append shrink expand specific args to the end. This led to duplicate arguments if there is more than one shrink expand request during the duration of a program.

Fixed by updating existing command line flags and only appending if the flags do not already exist in the new command line arguments.

**Comment by stwhite91** [comment]
*Original date: 2016-11-03 04:34:02*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1961/~~ https://github.com/UIUC-PPL/charm/commit/6353ee9323b3bd0b0e071ff64d95f9f4144059e0
