### ISSUE TITLE
ReductionStarting overhead in SMP mode

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1278]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1278*

---
On a benchmark where every PE has array elements, I'm still seeing a lot of `CkReductionMgr::ReductionStarting` messages, taking up a large fraction of runtime during that phase. Given the changes a while back to quiet them when they're not needed, I don't think they should appear at all.

[TimelineScreenshot.pdf](https://github.com/UIUC-PPL/charm/files/3536610/TimelineScreenshot.pdf)
[UsageProfile.pdf](https://github.com/UIUC-PPL/charm/files/3536611/UsageProfile.pdf)

**Comment by PhilMiller** [comment]
*Original date: 2016-11-05 18:39:38*

---
The fix in #29 should have covered this

**Comment by PhilMiller** [comment]
*Original date: 2016-11-05 19:14:32*

---
In projections traces, I noticed that each contribution was only triggering sends of ReductionStarting messages to other PEs in the same process. So, I tried a non-SMP build to see what would happen there. I saw no ReductionStarting messages at all, and performance was substantially improved.

There is some optimization missing in the node-level array reduction consolidation to match the non-SMP case.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-05 19:36:35*

---
Harshitha seems to have started on code to fix this in branch `harshitha/reductionstartingnode` but not finished it.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-05 20:13:37*

---
For note, the code on that branch at least mildly conflicts with the more recent streaming reduction changes, and I don't have the will to dig into how to resolve those conflicts properly. So I don't know if it would truly fix this case.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-10 22:07:14*

---
Unconditionally defining GROUP_LEVEL_REDUCTION to 1 in ckreduction.h quiets this down, at the cost of some efficiency in the reduction itself - the tree becomes the usual 4-ary tree over PEs, rather than taking nodes into account.

**Comment by stwhite91** [comment]
*Original date: 2017-01-19 23:40:26*

---
In Core we discussed the possibility of passing CkArrayOptions through to the reduction managers just like what is already done in CkArrayBroadcaster (called 'stableLocations' there).

**Comment by epmikida** [comment]
*Original date: 2017-02-07 21:56:37*

---
Implemented in ~~https://charm.cs.illinois.edu/gerrit/2216~~ https://github.com/UIUC-PPL/charm/commit/2c622f863c09793ab8410eb1138428d080fb8e63 by making CkReductionMgr node aware when in SMP mode.

**Comment by epmikida** [comment]
*Original date: 2017-02-07 21:57:21*

---
Implemented in [[~~https://charm.cs.illinois.edu/gerrit/2216~~ https://github.com/UIUC-PPL/charm/commit/2c622f863c09793ab8410eb1138428d080fb8e63]] by making CkReductionMgr node aware when in SMP mode.

**Comment by stwhite91** [comment]
*Original date: 2017-02-14 01:03:00*

---
The above commit leaves a TODO behind for the following:
```
  // TODO: This is currently gotten from the command-line...but it could
  // probably just be determined at runtime. I don't know if the CL option is
  // even documented anywhere.
  if(disableNotifyChildrenStart) return;
```

Documenting here so it is not forgotten

**Comment by PhilMiller** [comment]
*Original date: 2017-02-15 19:41:03*

---
And, merged. Finally.
