### ISSUE TITLE
Compilation with persistent on Cray fails

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#128]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/128*

---
If Charm++ is compiled with persistent on Cray, application compilation fails during linking if an extra library (-lz) is not linked.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 21:39:11*

---
It looks like fixing this was as simple as adding this line to `conv-mach-persistent.sh`:

```
CMK_LIBS="$CMK_LIBS -lz"
```

Fixed in fbaa981 on mainline, and cdfc40b3c on charm-6.5.
