### ISSUE TITLE
CkLoop gives bad results on > 64 pes per process

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1280]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1280*

---
If you run NAMD on apoa1 with --pmeProcessors 20 --useCkLoop 3 on multicore +p65 you get bad force errors.  +p64 works, and --useCkLoop 2 works.  The difference is that --useCkLoop 3 enables PME reciprocal space energy calculation, which requires a reduction.  The "--pmeProcessors 20" is necessary to show the bug because CkLoop is only used if numPes >= 2 * pmeTransPes.
If I change "FuncCkLoop::MAX_CHUNKS = 64" in src/libs/ck-libs/ckloop/CkLoop.C to 53 then the problem occurs at +p54, so the issue is with CkLoop.

**Comment by stwhite91** [comment]
*Original date: 2016-11-04 15:57:46*

---
Assigning to Seonmyeong based on module ownership

**Comment by jcphill** [comment]
*Original date: 2016-11-05 15:11:51*

---
Nevermind. This turned out to be bad CkLoop code in NAMD protected by a "CmiAssert(first==last)" that was preprocessed away.
