### ISSUE TITLE
win64 builds with tracing enabled are broken

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1282]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1282*

---
The autobuild tests are run with --with-production so tracing is not built.
PICS doesn't compile on MSVC. There seems to be multiple issues:
```
picsautoperfAPI.C(24): error C2131: expression did not evaluate to a constant
picsautoperfAPI.C(24): note: failure was caused by non-constant arguments or reference to a non-constant symbol
picsautoperfAPI.C(24): note: see usage of 'num'

```

```
picsdecisiontree.C(78): error C3861: 'getline': identifier not found
```

Not sure if critical for the 6.8.0-beta or not...

**Comment by PhilMiller** [comment]
*Original date: 2016-11-06 22:00:15*

---
Not release critical - we're treating Windows as a deployment platform for NAMD, not a development platform. In that respect, `--with-production` is pretty much all that matters at the moment.

That said, this should get fixed, so that it doesn't get in the way of debugging other issues that may crop up there.

**Comment by stwhite91** [comment]
*Original date: 2016-12-13 03:29:49*

---
The picsautoperfAPI.C issue was fixed here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2021/~~ https://github.com/UIUC-PPL/charm/commit/c42386617734e28f146a1250ceb23e2f42ed7aa8

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 19:48:17*

---
The other part got addressed here:
~~https://charm.cs.illinois.edu/gerrit/#/c/2049/~~ https://github.com/UIUC-PPL/charm/commit/9f5fc2715663979106bad225ec7f250ac8faeee8

Testing now (slowly), and will close if this builds cleanly now.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 20:09:28*

---
Taken together, the above commits fix the build there.
