### ISSUE TITLE
net-cygwin crashes in megatest/{queens,tempotest,synctest} under --with-production

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1287]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1287*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-08 01:41:43*

---
Changing the thread package to qt or back to uJcontext doesn't seem to help these. There's something else wrong, perhaps.

**Comment by stwhite91** [comment]
*Original date: 2017-03-03 17:38:06*

---
net-cygwin is deprecated
