### ISSUE TITLE
Reduce overheads of message creation in the OpenMP integration by adjusting the number of OpenMP tasks 

### ISSUE THREAD

**Issue by sbak5** [UIUC-PPL/charm#1295]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1295*

---
OpenMP integration into Charm++ split each Chare's work into fine-grained OpenMP tasks. 
Because most Charm++ applications overdecompose problem space into chares, it may be too costly to create more fine-grained OpenMP tasks all the time on each chare. 
To reduce overhead incurred by creating huge number of tiny OpenMP tasks and accessing the local task queue unnecessarily(Pushing and Popping OpenMP tasks even though they will be locally executed) , some simple optimization is applied.

Each PE keeps a vector to keep record of the ratio between locally executed tasks and stolen tasks. 
When each PE finishes the execution of OpenMP codes, it records the ratio to an element in the vector. 
When each PE starts, it uses the average of the elements in the vector and the number of idle threads within a node to decide how many messages to be created for the OpenMP execution. 

And, it separates the OpenMP tasks into two groups depending on the average of the previous ratios in the vector. 
OpenMP tasks in the first group is maintained in a local list only accessible to the thread which created the message. 
All the messages in the 2nd group are pushed into the work-stealing queue. 

To prevent the OpenMP tasks from being stuck in the local list while other threads are idle, the creator moves the tasks from the local list to the work stealing queue depending on the idle threads and the number of left tasks in the work-stealing queue while executing the tasks in the list.

This feature was already implemented on GOMP. and has been proven to reduce overheads significantly on many experiments.

**Comment by stwhite91** [comment]
*Original date: 2016-11-29 19:35:39*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1982/~~ https://github.com/UIUC-PPL/charm/commit/04df95ef985ac051f5e8e14ef451116839814dba
