### ISSUE TITLE
Patch METIS to privatize global variables

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1297]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1297*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-11 21:08:27*

---
Kavitha, did you have a patch for this? Do you recall if I said I did?

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-11 21:14:25*

---
I don't have a patch yet. I don't recall you mentioning that you did, I think you mentioned you might work on it. I can give it a try.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-13 19:02:40*

---
I looked at the object dump of the object files in the .bss section for global variables. It seems like all the global variables there already have __thread specifier. Could you please point me to an example in the code where the specifier has been missed?

**Comment by PhilMiller** [comment]
*Original date: 2017-04-14 16:03:58*

---

```

$ ../../src/libs/ck-libs/ampi/nm_globals.sh libckmetis.a 
0000000000006cd8 b buf.6961
0000000000000000 D gk_cur_jbufs
0000000000000000 d gk_exit_on_error
0000000000006400 B gk_jbuf
0000000000000000 B gk_jbufs
00000000000064d0 b old_SIGERR_handler
00000000000068d8 b old_SIGERR_handlers
00000000000064c8 b old_SIGMEM_handler
00000000000064d8 b old_SIGMEM_handlers
0000000000000014 b first_nonopt
0000000000000004 C gk_getopt_initialized
0000000000000008 C gk_optarg
0000000000000004 D gk_opterr
0000000000000000 D gk_optind
0000000000000008 D gk_optopt
0000000000000018 b last_nonopt
0000000000000000 b nextchar
0000000000000010 b ordering
0000000000000008 b posixly_correct
0000000000000004 b first.6993
0000000000000000 b last.6994
0000000000000000 b gkmcore
0000000000000000 d AAORDER.6949
0000000000000000 d PSSMWIDTH.6950
0000000000000000 b datestr.7039


charm/src/libs/ck-libs/metis $ git grep -l first_nonopt
GKlib/getopt.c

charm/src/libs/ck-libs/metis $ git grep -l old_SIGERR_handler
GKlib/error.c

charm/src/libs/ck-libs/metis $ git grep -l old_SIGMEM_handler
GKlib/error.c
```
It looks like the few remaining variables are all within GKlib.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-14 19:08:04*

---
Thanks for the nm script. Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2402/~~ https://github.com/UIUC-PPL/charm/commit/e52c8eddb98d0409de927a1067006e9908db7625
