### ISSUE TITLE
Build MetisLB by default

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1298]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1298*

---
Since we can now ship METIS in-tree, we can build MetisLB unconditionally.

**Comment by stwhite91** [comment]
*Original date: 2017-01-04 06:21:28*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1984/~~ https://github.com/UIUC-PPL/charm/commit/eed6d3aad90650cf04dde9b4cefa454e94b83fbf

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-11 19:03:52*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2319/~~ https://github.com/UIUC-PPL/charm/commit/4f784daa32b090218ef6bb8848cf277773abb35e
