### ISSUE TITLE
SDAG_RTS is missing object attribution in Projections traces

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1299]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1299*

---
We recently merged a change to attribute user-defined blocks of work in SDAG to the objects running them. However, the 'SDAG overhead' placeholder entry method doesn't attribute to a particular object. It always shows 0:0:0. Please fill in the tracing calls to fix this.

<img width="231" alt="Screen Shot 2016-11-10 at 11 33 15 AM" src="https://user-images.githubusercontent.com/1772435/63629286-ea888700-c5d6-11e9-9a2c-6bcbbe815db0.png">

**Comment by stwhite91** [comment]
*Original date: 2016-11-20 22:24:38*

---
Related: https://charm.cs.illinois.edu/redmine/issues/805

**Comment by stwhite91** [comment]
*Original date: 2016-11-23 18:59:41*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1995/~~ https://github.com/UIUC-PPL/charm/commit/34390dace4e88fa11cfc874c00844a6bb2bfa381
