### ISSUE TITLE
pass arbitrary arguments to mpiexec via charmrun

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1302]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1302*

---
It would potentially be useful to be able to pass arguments to mpiexec via the charmrun command line when necessary options aren't automatically determined from environment variables set by the queueing system.

**Comment by evan-charmworks** [comment]
*Original date: 2018-06-21 21:08:27*

---
Does `./charmrun ++mpiexec ++remote-shell "mpiexec --YourOptionsHere"` work?

**Comment by jcphill** [comment]
*Original date: 2018-12-19 19:17:31*

---
Yes, that does work.
Please add to the docs at http://charm.cs.illinois.edu/manuals/html/charm++/C.html#mpiexec

**Comment by evan-charmworks** [comment]
*Original date: 2018-12-19 20:16:32*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4872~~ https://github.com/UIUC-PPL/charm/commit/b3629a4217341476de16a2956992a29954c513d0
