### ISSUE TITLE
Deleting an array disables reclamation for all arrays bound to that location manager

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1312]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1312*

---
~~https://charm.cs.illinois.edu/gerrit/1114~~ https://github.com/UIUC-PPL/charm/commit/5a92b2880d91e5108d34782a77b151143c22aa54
The above change disabled sending `reclaimRemote()` messages to location manager instances that were going to be destroyed as a result of all associated arrays being destroyed. This change helps fix bug #1002.

In the case of bound arrays, one array being deleted permanently disables the `reclaimRemote()` calls in the associated location manager. I'm not sure of a present use case where this arises, but more dynamic future applications could stumble on this.

I thought AMPI might exhibit this in MPI_Comm_free, depending on how rank to index mapping works. If a given AMPI process is the same index in all arrays, and the ranks are mapped to indices by rank in MPI_COMM_WORLD, then there shouldn't be any cause to call `reclaimRemote`. I think that must be the case, because otherwise objects could become separated from their parent.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-27 19:53:03*

---
Actually, it looks like element deletion may destroy its corresponding CkLocRec and trigger this path regardless of whether there are any bound arrays. That means deleting one bound array would make all associated arrays fail in weird ways. That may require further investigation, and potentially bumps up the priority of fixing this.

**Comment by stwhite91** [comment]
*Original date: 2016-11-27 20:08:19*

---
I recently opened bug #1307 for AMPI_Comm_free (currently a no-op). I made a quick effort at implementing it, just calling ckDestroy on the local ampi chare array element for the given comm, and it failed weirdly. Haven't looked into it any more.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-27 20:09:48*

---
Interesting that we independently stumbled on this potential problem from opposite directions almost simultaneously.

**Comment by stwhite91** [comment]
*Original date: 2016-12-20 05:12:30*

---
Bumping priority to 'normal' since it effects AMPI and bound array deletion

**Comment by stwhite91** [comment]
*Original date: 2017-02-26 17:37:39*

---
I think this should be prioritized for merge before the release.

**Comment by epmikida** [comment]
*Original date: 2017-04-11 06:09:44*

---
A potential fix for this is implemented in ~~https://charm.cs.illinois.edu/gerrit/#/c/2380/~~ https://github.com/UIUC-PPL/charm/commit/9278e1df90297e10e2df09a9a0a794f59878a480, however it would appear that the reclaimRemote method no long does what it is supposed to. It just attempts to delete the local CkLocRec, however a while back it was changed so that CkLocRecs get deleted at emigration, so there will never be a local rec to delete. Instead it should clean out location caches for the given idx/id.

**Comment by epmikida** [comment]
*Original date: 2017-04-11 20:35:00*

---
A fix to the actual functionality of reclaimRemote has been posted here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2385/~~ https://github.com/UIUC-PPL/charm/commit/2c90af974313f23dd244365b4f2a4d633ae4896c

**Comment by PhilMiller** [comment]
*Original date: 2017-04-12 18:44:22*

---
Both patches have now been merged, so I think we're done here. Please re-open if that's not the case.
