### ISSUE TITLE
Replace widespread dynamic allocated arrays with std::vector and std::string

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1314]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1314*

---
There are loads of places in the runtime system and our examples where the code manually allocates an array member using `malloc` or `new`. This results in the potential for leaked memory, and really ugly cumbersome code in PUP methods that have to use the `if (p.isUnpacking()) foo = new T[n]` idiom. All of this goes away if those members are just defined as `std::vector<T>`

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 17:18:48*

---
Most places that deal with strings (esp. where we deal with files: checkpoint/restart, tracing, etc.) currently use char* or char[arbitrary_max_len], which can be cleaned up by using std::string too.

**Comment by stwhite91** [comment]
*Original date: 2017-11-04 22:08:40*

---
Cleanup ckreduction.C: ~~https://charm.cs.illinois.edu/gerrit/#/c/3234/~~ https://github.com/UIUC-PPL/charm/commit/e795cee5df1a68137c68bd62b26a0017c0c35ed4
Cleanup the rest of ck-core (except CkSectionID, which looks more involved): ~~https://charm.cs.illinois.edu/gerrit/#/c/3239/~~ https://github.com/UIUC-PPL/charm/commit/eef85fd39ef44b4105d295b2f663d16dc81aac5a

The biggest offenders for this bug are ck-perf and ck-ldb.

**Comment by stwhite91** [comment]
*Original date: 2017-11-08 21:43:33*

---
We should also replace all uses of CkVec with std::vector.

Edit: we've made some progress on this, but ck-ldb, ck-perf, and all the examples & tests remain to be done:

replace CkVec usage in xlat-i: with std::vector ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3273/~~ https://github.com/UIUC-PPL/charm/commit/58f1527c4fa31b99a71f1a0f3e329e934225433e
replace CkVec usage in conv-* with std::vector: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3274/~~ https://github.com/UIUC-PPL/charm/commit/359f4f328a002f38d687762a3a5096352a8daa88
ck-cp: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3275/~~ https://github.com/UIUC-PPL/charm/commit/dc185690c4ff36c02b3ecf958cca30bbaa9c9e4d
ck-core: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3337/~~ https://github.com/UIUC-PPL/charm/commit/8ee5a69685eda32b9a5e7a05064dadeaf61600b6

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-04 19:20:28*

---
https://charm.cs.illinois.edu/gerrit/c/charm/+/4922
