### ISSUE TITLE
Pingpong hangs in smp version on Taub

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#132]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/132*

---
I am running pingpong test on taub with the following script and it hangs after some point.

```
#!/bin/sh
#PBS -q cse
#PBS -l nodes=2:ppn=2
#PBS -N numt
#PBS -j oe
#PBS -l walltime=00:10:00

cd /home/acun2/charm/net-linux-x86_64-smp-gcc-test-production/tests/charm++/pingpong
~/gennodelist.sh > nodelist

time ./charmrun ++nodelist nodelist ./pgm +p2 +ppn1 > output

```
                                                               

This is the output from the execution;

```
Converse/Charm++ Commit ID:
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 2 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.033 seconds.
Pingpong with payload: 0 iterations: 1000
Roundtrip time for 1D Arrays is 103.624105 us
Roundtrip time for 1D threaded Arrays is 105.753183 us
Roundtrip time for 2D Arrays is 101.967096 us
Roundtrip time for 3D Arrays is 99.115849 us
Roundtrip time for Fancy Arrays is 95.360041 us
Roundtrip time for Chares (reuse msgs) is 98.726988 us
Roundtrip time for Chares (new/del msgs) is 115.087986 us
Roundtrip time for threaded Chares (reuse) is 96.486092 us
Roundtrip time for Groups is 98.433018 us
```

after this point it hangs but it supposed to continue and print these;

```
....
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 32.799006 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 31.252861 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 31.351089 us
Roundtrip time for NodeGroups is 31.659842 us

```

**Comment by bilgeacun** [comment]
*Original date: 2013-03-26 16:33:59*

---
Same condition occurs with +ppn2 too. Without specifying +ppn it works fine.

**Comment by bilgeacun** [comment]
*Original date: 2013-03-26 21:05:27*

---
The problem was using "+ppn1" or "+ppn2" instead of "++ppn 1" or "++ppn 2". 
They are working fine with those options but I suppose we should also be able to use "+ppn1" or "+ppn2".

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-04-05 19:56:23*

---

Did you try with space between +ppn 1 instead of +ppn1 (space after +ppn).

**Comment by ericjbohm** [comment]
*Original date: 2013-04-05 20:35:06*

---
Work on rationalizing the +p ++ppn argument lists and validating them.

**Comment by ericjbohm** [comment]
*Original date: 2013-05-03 19:47:18*

---
Documentation issue, see #126.
