### ISSUE TITLE
sync() undefined on bgclang build

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1320]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1320*

---
There is a macro used to protect against calling sync() where it is not defined, CMK_DISABLE_SYNC, that should just need to be set in the bgclang conv-mach header.

```
../bin/charmc  -optimize -production   -I.   -c -o ckcheckpoint.o ckcheckpoint.C
ckcheckpoint.C:270:9: error: use of undeclared identifier 'sync'
        sync();
        ^
1 error generated.
Fatal Error by charmc in directory /projects/CharmRTS/nbhat/autobuild/pamilrts-clang-nosmp/charm/pamilrts-bluegeneq-clang/tmp
   Command bgclang++ -I../bin/../include -I/bgsys/drivers/ppcfloor/comm/include -I/bgsys/drivers/ppcfloor/spi/include -I/bgsys/drivers/ppcfloor -I/bgsys/drivers/ppcfloor/spi/include/kernel/cnk -I/soft/libraries/alcf/current/xl/ZLIB//include -D__CHARMC__=1 -I. -O3 -ffast-math -fno-stack-protector -std=c++0x -c ckcheckpoint.C -o ckcheckpoint.o returned error code 1
charmc exiting...
make: *** [ckcheckpoint.o] Error 1

```

**Comment by PhilMiller** [comment]
*Original date: 2016-12-05 22:22:51*

---
That `sync()` call is quite semantically important. Are you sure this isn't just a missing `#include <unistd.h>` or some related `#define`?

Absent the `sync()` call, we need to have `fsync()` calls on the checkpoint files before closing them. Without that, we may continue from a checkpoint, thinking the data is safely on disk, only to find that it isn't after a failure.

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 17:29:40*

---
Yeah, ckcheckpoint was just missing inclusion of unistd.h: ~~https://charm.cs.illinois.edu/gerrit/#/c/2027/~~ https://github.com/UIUC-PPL/charm/commit/150bc9bc4dd97860dedb689e247d494bbbf46942

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 17:59:15*

---
Now we get a different failure:
```
Performing '/usr/bin/gmake charm++ OPTS= -g QUIET=' in pamilrts-bluegeneq-clang/tmp
../bin/charmc  -g  -I.   -c -o DummyLB.o DummyLB.C
../bin/charmc  -g  -o ../lib/libmoduleDummyLB.a DummyLB.o 
bgclang-ar: creating ../lib/libmoduleDummyLB.a
bgclang-ar: libc++.so.1: cannot open shared object file: No such file or directory

bgclang-ar: libc++.so.1: cannot open shared object file: No such file or directory

../bin/charmc: line 192: 14278 Segmentation fault      (core dumped) bgclang-ar q ../lib/libmoduleDummyLB.a DummyLB.o
Fatal Error by charmc in directory /home/white/charm/pamilrts-bluegeneq-clang/tmp
   Command bgclang-ar q ../lib/libmoduleDummyLB.a DummyLB.o returned error code 139
charmc exiting...
```

Using powerpc64-bgq-linux-ar instead of bgclang-ar seems to work: ~~https://charm.cs.illinois.edu/gerrit/#/c/2028/~~ https://github.com/UIUC-PPL/charm/commit/c20acb7e1880d79470e10a6c918dad6dc81adeaf

Then there are missing headers, fixed here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2029/~~ https://github.com/UIUC-PPL/charm/commit/9a4838c7da4c20ff7082b486d55624d1dcbcf949

Now a LIBS build of pamilrts-bluegeneq-clang compiles on Mira, after doing 'soft add +mpiwrapper-bgclang'.

**Comment by stwhite91** [comment]
*Original date: 2016-12-13 17:48:09*

---
bgclang builds are now passing autobuild
