### ISSUE TITLE
PSM2 network layer

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1322]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1322*

---
For Omni-Path the OFI layer is currently slower than MPI, which is based on PSM2. The only way to beat MPI is likely to do a direct PSM2 layer in Charm++.

**Comment by jcphill** [comment]
*Original date: 2017-01-26 19:07:11*

---
Look for the first occurrence of psm2_am in the following:

https://github.com/01org/opa-psm2/blob/master/psm2.h

 * PSM2 exposes a single endpoint initialization model, but enables various
 * levels of communication functionality and semantics through `e components.
 * The first major component available in PSM2 is PSM2 Matched Queues
 * (`ref psm2_mq), and the second is PSM2 Active Message (`ref psm2_am).
 *
 * Matched Queues (MQ) present a queue-based communication model with the
 * distinction that queue consumers use a 3-tuple of metadata to match incoming
 * messages against a list of preposted receive buffers.  The MQ semantics are
 * sufficiently akin to MPI to cover the entire MPI-1.2 standard.
 *
 * The Active Message (AM) component presents a request/reply model where
 * the arrival of a message triggers the execution of consumer-provided
 * handler code. This can be used to implement many one-sided and two-sided
 * communications paradigms.
 *
 * With future releases of the PSM2 interface, more components will
 * be exposed to accommodate users that implement parallel communication
 * models that deviate from the Matched Queue semantics.  For example, PSM
 * plans to expose a connection management component to make it easier to
 * handle endpoint management for clients without their own connection
 * managers.

**Comment by jcphill** [comment]
*Original date: 2017-01-26 19:15:13*

---
Presentation on OFI in MPICH:

https://www.openfabrics.org/images/eventpresos/workshops2015/DevWorkshop/Monday/monday_03.pdf

**Comment by jcphill** [comment]
*Original date: 2017-01-26 19:25:23*

---
More on active messages:

https://github.com/01org/opa-psm2/blob/master/psm2_am.h

**Comment by stwhite91** [comment]
*Original date: 2017-10-31 04:23:40*

---
OFI outperforms MPI on PSM2 and has been merged
