### ISSUE TITLE
assumes remote shell is OpenSSH

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1332]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1332*

---
In response to issues #709 and #710 hard-wired OpenSSH options are passed to ssh.
Since we let the user change the ssh command with ++remote-shell it would be nice to allow the user to disable these somehow, as they are annoying someone who is using rsh.
There is a work-around by pointing ++remote-shell at a wrapper script.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-21 19:51:40*

---
The way through this may be by shifting setting of those options so that they are bound directly to our default usage of ssh, rather than bolted on independently.

**Comment by jcphill** [comment]
*Original date: 2016-12-21 20:33:53*

---
The most common ++remote-shell setting may be a specific ssh client, so maybe don't completely disable them just because ++remote-shell is non-default.  Perhaps ++remote-shell-not-openssh as an additional flag?

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-23 21:57:42*

---
"++remote-shell-not-openssh" sounds cumbersome. Would it be sufficient to test the string passed to ++remote-shell against "rsh" and "*/rsh" and skip "KbdInteractiveAuthentication=no,PasswordAuthentication=no,NoHostAuthenticationForLocalhost=yes" if it matches?

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-26 20:42:20*

---
Ping.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-07 20:55:40*

---
Removing version tag because of the minor nature of this issue. Waiting on feedback before proceeding with implementation.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-10 22:58:45*

---
Bump.

**Comment by evan-charmworks** [comment]
*Original date: 2018-07-06 18:43:28*

---
Awaiting feedback.

**Comment by jcphill** [comment]
*Original date: 2018-12-19 19:23:49*

---
I don't think this is worth trying to fix as it's easy enough to do a wrapper script or use ++mpiexec if the user insists on being weird.

**Comment by evan-charmworks** [comment]
*Original date: 2018-12-19 19:51:08*

---
That works for me.
