### ISSUE TITLE
smp build broken on Cray compiler due to lack of __sync_synchronize

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#134]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/134*

---
__sync_synchronize is not supported by Cray compilers. Our config tests for __sync_fetch_and_add and assumes that __sync_synchronize is available. Split the definitions in converse.h.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 21:41:09*

---
More descriptive heading

**Comment by ericjbohm** [comment]
*Original date: 2013-05-17 23:01:45*

---

I cleared up several craycc issues:
    1. split tests for sync_synchronize and fetch_add
    2. split implementation selection for CmiMemory*Fence from CmiMemoryAtomic* to use whichever underlying intrinsic support is available based
    on the newly split configure test
    3. Add test and support for use of __builtin_ia32_lfence() so that craycc builds can leverage native intrinsics for CmiMemory*Fence
    4. fixed typo in configure.in
    5. fixed loud pointless compiler complaint about the return from getArrayMgr(void)
    
    With these changes in place, AMPI builds and passes make test when using craycc on gemini_gni-crayxe-hugepages-smp builds.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 19:28:47*

---
Cherry-picked to `charm-6.5` as commit:93e6cf839d262984949900873964c4a642f1d3b2

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 19:46:20*

---
Builds cleanly now.
