### ISSUE TITLE
AMPI fails to link on mpi-win64

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1341]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1341*

---
mpi-win64 autobuild fails in the first AMPI test because it picks up the system MPI instead of AMPI's header:
```
Entering directory '/home/nikhil/autobuild/mpi-win64/charm/mpi-win64/tests/ampi/megampi'
../../../bin/ampicxx -optimize -production  -optimize -production  -c test.C
Ignored Unrecognized argument -fno-lifetime-dse
test.C
test.C(96): error C2039: 'MPI_COMM': is not a member of 'MPI_Status'
c:\program files\microsoft compute cluster pack\include\mpi.h(316): note: see declaration of 'MPI_Status'
test.C(232): error C2039: 'MPI_COMM': is not a member of 'MPI_Status'
c:\program files\microsoft compute cluster pack\include\mpi.h(316): note: see declaration of 'MPI_Status'
test.C(234): error C2039: 'MPI_COMM': is not a member of 'MPI_Status'
c:\program files\microsoft compute cluster pack\include\mpi.h(316): note: see declaration of 'MPI_Status'
test.C(234): error C2660: 'MPI_Recv': function does not take 6 arguments
test.C(257): error C3861: 'AMPI_Migrate': identifier not found

```

**Comment by stwhite91** [comment]
*Original date: 2017-03-01 00:20:00*

---
Can you look at this this week, and if you can't fix it easily it then implement a workaround so that we don't test AMPI tests and examples on mpi-win-*? We can't keep making autobuild fail and possibly mask other failures. If you don't have access to a windows machine, ask Ronak to create an account on dexterity for you.

**Comment by stwhite91** [comment]
*Original date: 2017-03-15 17:12:17*

---
Bump. With the following merged, these builds should be the only ones that are persistently failing on AMPI now: https://charm.cs.illinois.edu/redmine/issues/1457

**Comment by stwhite91** [comment]
*Original date: 2017-03-21 15:24:17*

---
It looks like ampicc is not properly linking in AMPI's libraries/headers, and from a quick look at src/libs/ck-lib/ampi/ampiCC.in I can see at least one problem: the unix 'dirname' command is not supported on windows, so ampicc will not get the right path.

**Comment by matthiasdiener** [comment]
*Original date: 2017-03-25 01:21:36*

---
Committed a fix: ~~https://charm.cs.illinois.edu/gerrit/2339~~ https://github.com/UIUC-PPL/charm/commit/26ee55611a477d3c09636dea7cd9bcd49f608eb6
