### ISSUE TITLE
Workstealing task queue causes a race condition.

### ISSUE THREAD

**Issue by sbak5** [UIUC-PPL/charm#1345]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1345*

---
Workstealing task queue incurs a race condition due to the following faults in the implementation.

inline static void* TaskQueueSteal(TaskQueue Q) {
  int h, t;
  void *task;
  while (1) {
    h = Q->head;
    t = Q->tail;
    if (h >= t) 
      return NULL;
    (4) *task = Q->data[h % TaskQueueSize];* -> This line may incur a race condition because the worker can push a task in this slot before the thief returns this task.
    (5) if(!__sync_bool_compare_and_swap(&(Q->head), h, h+1)) 
           continue;
    (6) return task;
  }
}

inline static void TaskQueuePush(TaskQueue Q, void *data) {
  (1)int t = Q->tail;
  (2) Q->data[t % TaskQueueSize] = data; 
  (3) Q->tail = t+1;
}
(1) (2) (3) can be reordered as (1) (3) (2) so race condition happens in a scenario as the following
     head tail
(1)  0     0
(3)  0     1
(4)  0     1  task = Q->data[0] // task == NULL
(2)  0     1 Q->data[0] = data
(5)  1      1
(6)  1      1   return task; (return NULL)

This can be fixed in two ways. 

1. Added explicit barrier between (2) (3)  CmiMemoryWriteFence();
2. Modified (6) to Q->data[h % TaskQueueSize);  // This might be simpler and better.

**Comment by stwhite91** [comment]
*Original date: 2017-01-04 04:52:07*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2101/~~ https://github.com/UIUC-PPL/charm/commit/fce7e5d5963ffae55ffc8cc7993c9d4e9a84aa8f

**Comment by sbak5** [comment]
*Original date: 2017-01-04 07:15:45*

---
Seonmyeong Bak wrote:
> Workstealing task queue incurs a race condition due to the following faults in the implementation.
> 
> inline static void* TaskQueueSteal(TaskQueue Q) {
>   int h, t;
>   void *task;
>   while (1) {
>     h = Q->head;
>     t = Q->tail;
>     if (h >= t) 
>       return NULL;
>     (4) *task = Q->data[h % TaskQueueSize];* -> This line may incur a race condition because the worker can push a task in this slot before the thief returns this task.
>     (5) if(!__sync_bool_compare_and_swap(&(Q->head), h, h+1)) 
>            continue;
>     (6) return task;
>   }
> }
> 
> inline static void TaskQueuePush(TaskQueue Q, void *data) {
>   (1)int t = Q->tail;
>   (2) Q->data[t % TaskQueueSize] = data; 
>   (3) Q->tail = t+1;
> }
> (1) (2) (3) can be reordered as (1) (3) (2) so race condition happens in a scenario as the following
>      head tail
> (1)  0     0
> (3)  0     1
> (4)  0     1  task = Q->data[0] // task == NULL
> (2)  0     1 Q->data[0] = data
> (5)  1      1
> (6)  1      1   return task; (return NULL)
> 
> This can be fixed in two ways. 
> 
> 1. Added explicit barrier between (2) (3)  CmiMemoryWriteFence();
> -2. Modified (6) to Q->data[h % TaskQueueSize);  // This might be simpler and better--. (1)(3)(4)(5)(6)(2) can happen and this lead to race condition, and hangs.
