### ISSUE TITLE
Remove AMPI's MSGLOG support for sequential re-run of parallel execution

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1346]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1346*

---
Background on what this code is supposed to do: http://charm.cs.illinois.edu/manuals/html/ampi/manual.html#SECTION00038000000000000000

Reasons to remove it:
1. The current support for AMPIMSGLOG is already clearly broken, missing support in many routines that should have it.
2. The code is a pain to maintain when refactoring AMPI.
3. There are no known users of this feature (at least that Nikhil and I know of), and no tests for its correctness.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-05 20:19:04*

---
Looks like that would have been very useful for things related to Bigsim performance predictions. Record execution of a job on an existent system, and then re-run single ranks through a simulator that can give you the behavior of a future system.

**Comment by stwhite91** [comment]
*Original date: 2017-01-06 17:49:42*

---
Yeah, but BigSim + CODES are capable of doing that. That's exactly what Nikhil's and my paper at SC this year did, but BigSim's support is complete and this is broken.

**Comment by stwhite91** [comment]
*Original date: 2017-01-07 20:07:20*

---
https://charm.cs.illinois.edu/gerrit/#/c/1907/
