### ISSUE TITLE
Eliminate tests against archaic macro CMK_OPTIMIZE

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#135]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/135*

---
The macro `CMK_OPTIMIZE` was broken up into various more-specific macros `CMK_ERROR_CHECKING, CMK_CHARMDEBUG, CMK_TRACE_ENABLED, CMK_REPLAYSYSTEM`, and various other feature-specific flags. Each occurrence of `CMK_OPTIMIZE` should be changed to whichever of the above, or something else, is most suitable to its purpose.

When working on this, note that the modern macros are tested by value (`#if CMK_ERROR_CHECKING`), not by definition (`#ifdef CMK_OPTIMIZE`), as they are always defined.

As I write this, I count 261 instances of `CMK_OPTIMIZE` in the source tree.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-12 19:18:15*

---
Everyone should address instances of CMK_OPTIMIZE in the portions of the codebase they are responsible for, according to https://wiki.engr.illinois.edu/display/ppl/Software+Module+Ownership

**Comment by PhilMiller** [comment]
*Original date: 2013-04-12 20:17:48*

---

```

$ git grep CMK_OPTIMIZE | cut -d: -f1 | awk -F/ '{ for (i = 1; i < NF; i++) printf "/%s", $i; printf "\n"}' | sort | uniq -c | sort -rn # re-sorted partially by hand
     22 /src/ck-core
      4 /src/conv-core
      4 /src/conv-com
      4 /

      8 /src/arch/elan
      4 /src/arch/bluegenel
      2 /src/arch/portals-crayxt3
      2 /src/arch/pamilrts
      2 /src/arch/pami
      2 /src/arch/net
      1 /src/arch/sim-linux
      1 /src/arch/lapi

      3 /src/libs/ck-libs/collide
      2 /src/libs/ck-libs/mblock
      1 /src/libs/ck-libs/TMRC2D
      1 /src/libs/ck-libs/pmaf
      1 /src/libs/ck-libs/multiphaseSharedArrays
      1 /src/libs/ck-libs/idxl

      6 /src/libs/ck-libs/ParFUM
      6 /src/libs/ck-libs/fem
      1 /examples/fem/adapt

    151 /src/libs/ck-libs/pose
      2 /examples/pose/HiSim/Main
      2 /examples/pose/Ring
      1 /examples/pose/ASIM
      1 /examples/pose/ChunkSim
      1 /examples/pose/HiSim/BlueGene
      1 /examples/pose/HiSim/HypCubeArch
      1 /examples/pose/HiSim/HypCubeArchOB
      1 /examples/pose/HiSim/IB
      1 /examples/pose/HiSim/InputVcSelection
      1 /examples/pose/HiSim/OB
      1 /examples/pose/HiSim/OutputVcSelection
      1 /examples/pose/HiSim/RedStorm
      1 /examples/pose/HiSim/Routing
      1 /examples/pose/HiSim/Topology
      1 /examples/pose/LBSim
      1 /examples/pose/MiniNet
      1 /examples/pose/PHOLD
      1 /examples/pose/SimBenchmark

```

**Comment by ericjbohm** [comment]
*Original date: 2013-10-09 23:14:00*

---
To clarify we are taking the behaviours formerly defined by CMK_OPTIMIZE and using a set of more specific choices.
In a --with-optimize build, we currently set CMK_OPTIMIZE, plus the more specific flags.
These are all individually controllable from the build line as: --disable-controlpoint --disable-tracing --disable-tracing-commthread --disable-charmdebug --disable-replay --disable-error-checking 

Within the code they are controlled by the preprocessor as:

!CMK_ERROR_CHECKING is for assertions and paranoia, not correctness
!CMK_CHARMDEBUG is for code necessary for introspection and the other charmdebug features
CMK_TRACE_DISABLED should exclude the tracing code for everything in the tracing framework
!CMK_REPLAYSYSTEM is for the record replay infrastructure
!CMK_WITH_CONTROLPOINT is for the adaptive control point framework
!CMK_SMP_TRACE_COMMTHREAD is for the special user event tracing (see ugni) within the comm thread in SMP builds
!CMK_WITH_STATS is for statistics (network, events, etc) collection

You should use the most specific and relevant set of preprocessor vars for each code section.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 00:17:22*

---
I've cleaned out everything that was not in actual source code.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 00:27:40*

---
Reference affirmative macro, not inverted partner

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 04:37:47*

---
All gone!
