### ISSUE TITLE
CkArrayOptions callback for completion of chare array initialization

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1352]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1352*

---
Add a callback to CkArrayOptions to be triggered when all of the initial objects are constructed in a chare array.
Right now we don't have a good way to do this short of QD, which is global.

AMPI's intercommunicator creation is an example where this is needed, and where QD is not possible (since intercommunicators are created dynamically and other messages may be in flight on other communicators during creation of an intercommunicator).

**Comment by PhilMiller** [comment]
*Original date: 2017-01-10 18:00:06*

---
Could you get this implemented? Hand off to Ed, Karthik or such with your guidance if you think they can do it.

**Comment by stwhite91** [comment]
*Original date: 2017-01-12 21:53:24*

---
One thing I am not sure of that you or someone might just know: Is there a single point of exit in the initialization sequence for all types of chare array creation from which to invoke the callback?

**Comment by PhilMiller** [comment]
*Original date: 2017-01-13 01:36:34*

---
I'm not sure of what you mean by 'all types of chare array creation' - I think we only need to be concerned with bulk construction, which is done when the code returns from the populateInitial call on each PE. The array manager can contribute to a reduction targeting the callback.

**Comment by stwhite91** [comment]
*Original date: 2017-01-19 17:49:05*

---
AMPI's use case for this (intercomm creation) is one-at-a-time/element-by-element initial insertion. Perhaps we should refactor AMPI's array creation to use bulk insertion though...

One issue I ran into when initially trying to implement this was that the contribute() methods are not defined in CkArray.

**Comment by stwhite91** [comment]
*Original date: 2017-01-19 22:51:38*

---
Reassign if urgent. Isomalloc hangs and other AMPI things are more important to me at the moment. This is only really seen during intercommunicator creation in AMPI, which is itself rare.

**Comment by stwhite91** [comment]
*Original date: 2017-02-06 23:39:46*

---
Hacky implementation using pt2pt sends, rather than a reduction, here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2209/~~ https://github.com/UIUC-PPL/charm/commit/2e1010df374b65021f1c4948329a645554b1e939

I tried adding contribute() definitions/declarations to CkReductionMgr, which CkArray inherits from. But then when running with more chare array elements than PEs, we get a hang. The reduction mgr for some reason is expecting more contributions than it should...

**Comment by stwhite91** [comment]
*Original date: 2017-05-09 21:09:06*

---
We decided that since getting a proper reduction done inside CkArray will be ugly and doing all-to-one pt2pt sends will blow up at large core counts, using pt2pt sends in a tree-like manner is acceptable (clean up can come later).

**Comment by PhilMiller** [comment]
*Original date: 2017-05-11 19:38:00*

---
It looks like there's another use case for this outside AMPI - CkIO.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-11 21:21:11*

---
Hackishly re-using the reduction manager's spanning tree now.
