### ISSUE TITLE
CmiMemoryAtomics fail to build on bgclang

### ISSUE THREAD

**Issue by sbak5** [UIUC-PPL/charm#1354]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1354*

---
CmiMemoryAtomics fail to build on bgclang because they use __atomic_fetch_and_add(sub) instead of __atomic_fetch_add(sub). 
(I'm not sure why this works on GCC and ICC but these is no information about these builtins)

__atomic_<operations> is GCC C extension. So, this is actually not C11 standard operations.
But it provides the same feature of atomic operations in C11 atomics with this set of builtins.

For simplicity, GCC provides this set of atomic builtins so that users can do atomic operations with non-atomic variables. 

So, it's enough to replace '__atomic_fetch_and_add' with __atomic_fetch_add and add compiler flag, '__GNUC__' so that compilers compatible with GCC only can use these __atomic builtins while others use __sync builtins.

**Comment by sbak5** [comment]
*Original date: 2017-01-10 07:22:12*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2111/~~ https://github.com/UIUC-PPL/charm/commit/7754209f474fa34856e61d9cb472c8b155bc8c163

**Comment by stwhite91** [comment]
*Original date: 2017-01-11 01:49:10*

---
Follow up with making the workstealing queue use C11 atomics after the lockless queue patch is merged.
