### ISSUE TITLE
ODR violations among helper classes in LB strategies

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1359]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1359*

---

```
$ grep -n 'class ' *LB.C | awk -F: '{print $3 "\t" $1 ":" $1}' | sort

1. formatted, de-crufted output of the above:

class ObjLoadGreater {	GreedyLB.C:47
class ObjLoadGreater {	CommAwareRefineLB.C:79
class ObjLoadGreater {	RefineSwapLB.C:8
class ObjLoadGreater {	TempAwareCommLB.C:189
class ObjLoadGreater {	TempAwareGreedyLB.C:42
class ObjLoadGreater {	TempAwareRefineLB.C:251
class ObjLoadGreater {	TreeMatchLB.C:60

class ObjPeCommInfo {	CommAwareRefineLB.C:101
class ObjPeCommInfo {	TempAwareCommLB.C:211

class PeCommInfo {	CommAwareRefineLB.C:86
class PeCommInfo {	TempAwareCommLB.C:196

class ProcCommGreater {	CommAwareRefineLB.C:110
class ProcCommGreater {	TempAwareCommLB.C:220

class ProcLoadGreater {	CommAwareRefineLB.C:67
class ProcLoadGreater {	GreedyLB.C:40
class ProcLoadGreater {	TempAwareCommLB.C:177
class ProcLoadGreater {	TempAwareGreedyLB.C:35
class ProcLoadGreater {	TempAwareRefineLB.C:237
class ProcLoadGreater {	TreeMatchLB.C:53
```

The case between RefineSwapLB and GreedyLB caused actual, observable failures in RefineSwapLB, because its definition has a member variable, while Greedy's did not. When linked with GreedyLB, it picked up a definition of the copy constructor that did not have anything to copy. Thus, copied instances ended up containing garbage. This disappeared when optimization was enabled in compiling RefineSwapLB, because the desired definitions were all inlined, and the conflicting definition from Greedy never had a chance to cause trouble.

I originally observed this when trying to run SNL's PIC particle-pushing kernel mini-app, since RefineSwapLB showed the best performance results there.

The generic fix is to give the various class definitions all distinct names, so that there are no divergent definitions of the same symbols anywhere.

**Comment by juanjgalvez** [comment]
*Original date: 2017-01-13 16:32:21*

---
Another option is to just move the compare classes inside their load balancer class, which would probably be cleaner and avoid future name conflicts.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-13 19:01:48*

---
I like your suggestion much better than mine. It applies equally well to all of the helper classes mentioned.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-13 21:31:15*

---
Please link the the changes when setting status to _Implemented_, so that it's easy to cross-reference

**Comment by PhilMiller** [comment]
*Original date: 2017-01-13 21:31:34*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2124/~~ https://github.com/UIUC-PPL/charm/commit/bd72a9ce6008562c9f7c2615439985c6b5d1f340
