### ISSUE TITLE
mpi-linux-x86_64 build with pgcc backend fails

### ISSUE THREAD

**Issue by xiangni** [UIUC-PPL/charm#136]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/136*

---
build command ./build charm++ mpi-linux-x86_64 -g
../bin/charmc -host  xi-main.C
cc1plus: error: unrecognized command line option "-fno_using_std"
Fatal Error by charmc in directory /home/xiangni2/build/charm/mpi-linux-x86_64/tmp
   Command g++ -fPIC -DCMK_FIND_FIRST_OF_PREDICATE=1 --no_using_std -I../bin/../include -D__CHARMC__=1 -c xi-main.C -o xi-main.o returned error code 1

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 19:48:44*

---
The mistake was in conv-mach.sh passing the options for the detected backend compiler behind mpicc/mpicxx to the hardcoded gcc native compiler. Fixed in f0bc4a173563db34eae22c53fc688f8bf3b86b42, and will be cherry-picked to charm-6.5.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 20:58:04*

---
Fully tested the fix on Carver, so closing.
