### ISSUE TITLE
AMPI megampi test fails on mpi-crayxc and darwin builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1360]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1360*

---
AMPI's megampi test passes on +p1 +vp1 and +p +vp2 but fails on +p2 +vp2. The same test passes all runs on Blue Waters.

**Comment by stwhite91** [comment]
*Original date: 2017-01-15 18:00:51*

---
For some reason I can't get an interactive job on Edison now, and I get the same exact error message when I try to submit a job via sbatch:
```
$ salloc -N 1 -p debug -t 00:30:00 -L SCRATCH

salloc: error: Job submit/allocate failed: Unspecified error

```

**Comment by stwhite91** [comment]
*Original date: 2017-01-24 20:07:09*

---
Also seeing a failure on netlrts-darwin-x86_64 on Wit in megampi with +p1 +vp1.  Doesn't reproduce on my Mac, but is consistent in autobuild.

Edit: The darwin bug doesn't reproduce on Wit either, except in Autobuild....? Not sure what I'm doing different from autobuild...
http://charm.cs.uiuc.edu/autobuild/cur/

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-06 17:15:37*

---
megampi fails with OPTS="-optimize" (even on my macbook), compiling without optimization works fine.

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-06 18:13:49*

---
Seems to be a clang stack alignment issue. Adding explicit alignment 
```
int rank __attribute__ ((aligned (16)));
```
 to line 10 in test.C is a workaround.

**Comment by stwhite91** [comment]
*Original date: 2017-02-15 03:28:53*

---
The real issue was that we were returning the address of a variable on the stack when getting builtin keyvals like AMPI_MY_PE. The above patch was amended to fix the real issue.

**Comment by matthiasdiener** [comment]
*Original date: 2017-05-05 20:43:23*

---
Patch is here:
~~https://charm.cs.illinois.edu/gerrit/#/c/2201/~~ https://github.com/UIUC-PPL/charm/commit/535b4727f8c15d6eb633d3d5205b804452116e68
