### ISSUE TITLE
multicore-linux-x86_64 should alias to multicore-linux64

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1361]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1361*

---
If you try to build with linux-x86_64 instead of linux64 our build script aborts with the following error:
```
$ ./build AMPI multicore-linux-x86_64 -j16 --with-production -g
Error> option: linux is not supported in this version!
Supported compilers: clang craycc gcc icc icc8 iccstatic pgcc xlc xlc64
Supported options: bigemulator bigsim g95 gfortran ifort lcs omp ooc papi persistent pgf90 tsan
```

multicore-win64 and mpi-win64 should also have aliases, since we now have netlrts-win-x86_64.

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2017-02-06 19:04:35*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2203/~~ https://github.com/UIUC-PPL/charm/commit/15d86953243814e7ee708fbfd591d9677f891584
