### ISSUE TITLE
Remove/deprecate dead machine layers

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1363]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1363*

---
The `-sol, -cygwin, and net-` layers are no longer needed. Probably the `-win32 and -cell` layers too. We may want to make `netlrts-` versions of the `net-` layers that don't currently have a `netlrts-` equivalent.

**Comment by PhilMiller** [comment]
*Original date: 2017-01-18 20:30:22*

---
Format description to avoid ugly strike-through display

**Comment by PhilMiller** [comment]
*Original date: 2017-01-18 20:30:44*

---
Not really a bug - their presence doesn't much hurt anything.

**Comment by stwhite91** [comment]
*Original date: 2017-03-23 15:44:00*

---
Remaining builds we could potentially remove?
```
net-*
win32
*-cell
*-mips64
*-amd64

```

**Comment by ericjbohm** [comment]
*Original date: 2017-04-13 19:15:30*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2393/~~ https://github.com/UIUC-PPL/charm/commit/c321e82b64d026e52e0080ae4f24a8edd758067b  uses a #pragma and a launch time print to warn the user to use netlrts instead of lrts.
