### ISSUE TITLE
segmentation violation in tests/ampi/megampi with icc on Taub

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#137]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/137*

---
With icc 13.1, building Charm++ in smp version with the following options,  tests/ampi/megampi gives segmentation violation.

```
./build LIBS net-linux-x86_64 icc smp --suffix=test-trace --disable-error-checking -j32 -optimize
./build LIBS net-linux-x86_64 icc smp --suffix=test-production --with-production -j32
```

Output from  the execution;

```
./charmrun ./pgm +p2 +vp2 ++local
Charmrun> started all node programs in 0.008 seconds.
Converse/Charm++ Commit ID: 
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.003 seconds.
[0] RandCentLB created
[0] Testing: Testing...
------------- Processor 0 Exiting: Caught Signal ------------
Signal: segmentation violation
Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
Charmrun: error on request socket--
Socket closed before recv.

```

**Comment by PhilMiller** [comment]
*Original date: 2013-05-03 04:03:21*

---
I'm now unable to reproduce this issue. I loaded intel/13.1 and used the exact build commands listed in the description. The megampi test runs to completion, and does not crash. Is there some additional option or flag that I'm missing that would product this?

**Comment by bilgeacun** [comment]
*Original date: 2013-05-03 04:33:03*

---
With a fresh charm, it seems the problem is gone, it's working. However with Charm 6.5 it was not working, the 6.5 build I did is here /home/acun2/charm/net-linux-x86_64-smp-icc-charm-trace/tests/ampi/megampi on taub.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-03 17:40:17*

---
I can't reproduce this on `charm-6.5` either, following the exact build listed. I'm inclined to think this was a transient result of some bad system condition. Can you confirm that a build done now doesn't exhibit the crash anymore?
