### ISSUE TITLE
Crash in LrtsInitCpuTopo() on Quartz with verbs layer

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1381]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1381*

---
Quartz is a new cluster with an Intel Omni-Path 100 Gb/s interconnect. If I build on verbs layer and run on more than 1 process (non-SMP with +p > 1 and SMP with numNodes>1), it fails. The mpi layer works.

```
$ ./charmrun +p2 ./pgm ++mpiexec ++remote-shell ./mysrun
Charmrun> scalable start enabled. 
Charmrun> IBVERBS version of charmrun
Charmrun> started all node programs in 0.227 seconds.
Charm++> Running in non-SMP mode: numPes 2
Converse/Charm++ Commit ID: v6.7.0-585-g1255a4a
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: 
		Length mismatch!!

[0] Stack Traceback:
  [0:0] CmiAbortHelper+0x63  [0x5c8d23]
  [0:1]   [0x5cc189]
  [0:2] CmiGetNonLocal+0xa3  [0x5cd033]
  [0:3] CsdNextMessage+0x75  [0x5d2655]
  [0:4] CsdSchedulePoll+0x48  [0x5d2998]
  [0:5] LrtsInitCpuTopo+0x375  [0x5e1a05]
  [0:6] _Z10_initCharmiPPc+0xa6b  [0x5051db]
  [0:7] ConverseInit+0x2fe  [0x5d0f1e]
  [0:8] main+0x27  [0x490dd7]
  [0:9] __libc_start_main+0xf5  [0x2aaaab928b35]
  [0:10]   [0x4914af]
Fatal error on PE 0> 

		Length mismatch!!

```

**Comment by jcphill** [comment]
*Original date: 2017-01-26 18:35:13*

---
You can fix this by adding --with-qlogic to the command line, although it will probably still be slower than MPI.

**Comment by stwhite91** [comment]
*Original date: 2017-01-26 18:36:30*

---
I added Bilge as a watcher, since I thought we had automated that build option?

**Comment by jcphill** [comment]
*Original date: 2017-01-26 18:39:45*

---
I only see this:
https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=e3cfe89fffdd9349ababf5b13b01045c78fa0b26
which kept it from being on by default.

**Comment by stwhite91** [comment]
*Original date: 2017-01-26 18:50:19*

---
Building with --with-qlogic didn't help, I get the same error.

**Comment by stwhite91** [comment]
*Original date: 2017-01-26 18:54:39*

---
This is the commit that I thought automated Mellanox vs. QLogic choice in verbs: ~~https://charm.cs.illinois.edu/gerrit/#/c/702/~~ https://github.com/UIUC-PPL/charm/commit/ce5d773919690e622da14b1cc89f4410be834530

**Comment by bilgeacun** [comment]
*Original date: 2017-02-06 21:29:28*

---
I have reproduced this bug on 2 nodes, it works on +p>1 in one node. This is likely to be the same issue we saw on Bridges:
https://charm.cs.illinois.edu/redmine/issues/1048 As that issue disappeared there after they updated some libraries, leaving this for now to be tested again later after the machine becomes more mature.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-23 14:13:43*

---
This particular error occurs while doing low-level processing of messages sent during LrtsInitCpuTopo(), in the first phase which is something that happens before the code added in this patch (~~https://charm.cs.illinois.edu/gerrit/#/c/2723/~~ https://github.com/UIUC-PPL/charm/commit/e9191d90ba87d917ad9ed202d0be06ebc98ab553). It's likely to be either processing the CmiReduce (if error is in PE0 it may be the CmiReduce), or processing the broadcast message sent from PE0. I think it's a low-level issue and doesn't have to do with code in cputopology.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-23 14:19:40*

---
We could easily disable cputopology and see if the program progresses past that. If there are issues in machine-level implementation which I think is the case, it would crash somewhere else.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-11 21:24:04*

---
(Updating all of #1048 #1381 #1409 )

Since these machines are all ostensibly going to be using the ofi network layer from 6.8.1 onward, do we want to close these bugs as 'rejected'?

**Comment by stwhite91** [comment]
*Original date: 2017-09-13 19:55:36*

---
OFI should be used on Quartz.
