### ISSUE TITLE
charmrun doesn't compile on netlrts-win-x86_64

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1388]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1388*

---
This commit broke charmrun compilation on net-win64 and netlrts-win-x86_64: ~~https://charm.cs.illinois.edu/gerrit/#/c/2126/~~ https://github.com/UIUC-PPL/charm/commit/fa4e24fe3ca3b519d8984be7f4f13bfc31ca4ba4

```
../../bin/charmc -optimize -production   -Wno-error -lm -I.. -c -seq -DCMK_NOT_USE_CONVERSE=1 -DNOTIFY charmrun.C
Ignored Unrecognized argument -fno-lifetime-dse
charmrun.C
charmrun.C(69): fatal error C1083: Cannot open include file: 'rpc/rpc.h': No such file or directory

```

**Comment by PhilMiller** [comment]
*Original date: 2017-02-08 18:07:27*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/2224~~ https://github.com/UIUC-PPL/charm/commit/a8a0525464d9b71d251fd7261fb06c0451a74edf
