### ISSUE TITLE
MPI builds: Deduplicate handling of options necessary for different backend compilers

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#139]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/139*

---
Many of the `conv-mach.sh` and `cc-mpicxx.sh` files for various MPI builds contain logic to detect the actual backend compiler and add some compiler-specific options accordingly. This logic is often duplicative, as are the options involved when the same backend compiler is available on more than one MPI-based target.

We should pull the repeated logic into a common shell file that all of these can source, and put the standard per-compiler options in that. Extra compiler-and-platform-specific compiler options could be specified in an additional variable that the common script would reference, if needed.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 02:48:09*

---
Probably best not to schedule invasive changes like this for a patch release. Bug fixes relating to these bits can be done the individual, manual way with lower risk of regression.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 02:48:42*

---
Sam is probably a good candidate to do this, as the new owner of the MPI machine layer, and potential heavy user thereof.

**Comment by nitbhat** [comment]
*Original date: 2016-02-26 19:53:14*

---
The duplicative logic specifying MPI compilers is limited to mpi-linux-x86_64 and mpi-darwin-x86_64 builds. There's some duplicative logic relating to compilers for other specific builds eg for cray compilers, there's logic of adding flags if the compiler is pgcc. 
As the duplicative logic was specific to only a few builds, Phil and I had a discussion where we decided that there's no real benefit of having a common source file.
