### ISSUE TITLE
AMPI_Alltoall crashes for short messages

### ISSUE THREAD

**Issue by karthiksenthil** [UIUC-PPL/charm#1390]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1390*

---
Running the megampi test for more number of ranks(instead of 4) crashes with a memory corruption. More investigation points to MPI_Alltoall test.

**Comment by stwhite91** [comment]
*Original date: 2017-02-02 05:44:23*

---
We'll want to have MPI_Alltoall working for all message sizes in our 6.8.0 release. In the worst case, we could always fall back to the medium or long message algorithms for short messages as well.

**Comment by stwhite91** [comment]
*Original date: 2017-02-13 00:18:23*

---
What's the status of this?

**Comment by karthiksenthil** [comment]
*Original date: 2017-02-13 15:44:39*

---
I think there are multiple bugs associated with this issue.

1. When I run the test as `./pgm +vp 5`, the program crashes with

   `pgm: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed`

With GDB this points to a call within the MPI_COMM_SELF tests that are performed in megampi.

2. When I run the test as `./pgm +vp 7`, a mismatch of expected value for the Alltoall test is obtained. I am tracing the current recursive doubling algorithm to fix this.

As a temporary fix we can use the medium size messages algorithm for the short messages as well. Interestingly this solves both the above bugs.

**Comment by stwhite91** [comment]
*Original date: 2017-02-14 22:54:18*

---
I think we can safely abandon the short message protocol (and use the medium message protocol for those).

**Comment by karthiksenthil** [comment]
*Original date: 2017-02-16 21:40:27*

---
Patch link : ~~https://charm.cs.illinois.edu/gerrit/#/c/2254/~~ https://github.com/UIUC-PPL/charm/commit/fe23e210b69e7a532dc5923d7dc010e535284d21
