### ISSUE TITLE
Add an SMP/multicore build test to Jenkins

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1391]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1391*

---
Decided at Core last week: before any commit is merged, it should have to pass the test suite on an SMP or multicore build.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-24 13:50:46*

---
I think this is done?

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:06:58*

---
This has been working smoothly for a while.
