### ISSUE TITLE
Stampede test script fails during autobuild (verbs)

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1392]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1392*

---
Testrun script used in autobuild uses charmrun that isn't allowed to run on a login node. 

../../bin/testrun  +p4 ./check 4 ++timeout 180 +isomalloc_sync
To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.

Probable Fix: 
The fix would require modifying charmrun to support job submission (to a compute node) and then launching the executable with "./charmrun +p1 ++mpiexec ++remote-shell 'ibrun -o 0' ./executable".

**Comment by nitbhat** [comment]
*Original date: 2017-02-08 01:59:25*

---
Fixed the 'src/scripts/testrun' script used by verbs autobuild to run jobs on stampede. 
Fix included modifying the script to submit a job and waiting for it until it completes or until it hangs. The script is similar to the charmrun used by the gni layer (gni/charmrun)

Fix: https://charm.cs.illinois.edu/gerrit/#/c/2222/

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 18:17:15*

---
This would seem to have been dealt with, given that autobuild runs on Stampede pass. Please close if that's correct, and possibly link to any code change that was involved.

**Comment by nitbhat** [comment]
*Original date: 2017-04-11 17:48:29*

---
 It was decided to not modify testrun (or charmrun) and keep it platform agnostic. The fix involved making changes to the instead_test.sh script that is used for launching Charm++ tests in nightly build runs on Stampede. The change has been committed in the autobuild repository. (https://charm.cs.illinois.edu/gerrit/#/admin/projects/autobuild)
