### ISSUE TITLE
AMPI_Get_elements returns incorrect results for struct type

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1395]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1395*

---
test/ampi/mpich-tests/pt2pt/getelm fails with "Wrong number of elements for struct recv; got 1001 expected 24".

This routine may be broken for other derived datatypes as well. Or the test itself could be deficient (less likely).

**Comment by stwhite91** [comment]
*Original date: 2017-02-04 00:56:35*

---
Low priority until we have a concrete use case other than mpich-tests.

The basic issue is that the MPI standard allows recv'ing partial derived datatypes. Currently, AMPI assumes that the message is N consecutive copies of some datatype, where N >= 1 or N = 0. To fully support MPI_Get_elements, we need to have DDT support for deserializing a maximum of X bytes, where X is the length of the message. This way DDT will stop deserializing as soon as it hits the end of the message, regardless of whether it has reached the end what its type's size is.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-15 21:59:03*

---
Matt, heads up about this, since you're working in this space.

**Comment by stwhite91** [comment]
*Original date: 2018-08-01 15:59:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4341/~~ https://github.com/UIUC-PPL/charm/commit/be38f4c0718c90afec1ab487589cb65082940e0c
