### ISSUE TITLE
Document addReducer's new option 'streamable'

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1398]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1398*

---
Users can now ask that their custom reductions be processed in a streaming fashion when registering their reduction function via addReducer(). This feature is mentioned in the upcoming release notes but is not in the manual.

Also slightly related, section 16.1 says 'If different contribute calls pass different callbacks, some (unspecified, unreliable) callback will be chosen for use.' That is actually an error that we abort on, so that text should be updated.

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 15:36:15*

---
This should be quick/easy, so bumping priority.

**Comment by stwhite91** [comment]
*Original date: 2017-04-19 14:41:51*

---
Advanced tutorial attendees asked about this...

**Comment by stwhite91** [comment]
*Original date: 2017-04-26 22:06:08*

---
https://charm.cs.illinois.edu/gerrit/#/c/2446/

**Comment by rbuch** [comment]
*Original date: 2017-04-27 21:08:04*

---
The correct link for the patch is: ~~https://charm.cs.illinois.edu/gerrit/#/c/2447/~~ https://github.com/UIUC-PPL/charm/commit/275ccc225b0189d5162a87e9818607b52f6ee236, Sam's was abandoned due to duplication.
