### ISSUE TITLE
PAMI-SMP (both with and w/o ASYNC) Autobuild failure

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#14]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/14*

---
PAMI-SMP-ASYNC does not pass auto build.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 19:56:24*

---
The PAMI SMP builds all look good now. Should we close this?

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 20:06:55*

---
Autobuild lied - it passed even though the machine wasn't actually running anything.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-06 20:14:08*

---
PAMI-SMP passes autobuild - there was a memory explosion due to use of special memalloc on BGQ. It has been resolved. PAMI-SMP-ASYNC still remains buggy.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-06 20:29:34*

---
To provide more background on this - PAMI-SMP and PAMI-SMP-ASYNC were crashing for tests/converse/megacon. It was found that we were running out of memory for these tests. Megacon does around 130000 malloc of very small size and does not free them. This is typically a no-problem since the malloc size is just 40 MB. However, with BGQ's special malloc, all small malloc are converted to 4K, which results in Megacon requiring 500 MB or so space. The issue was fixed by limited the number of mallocs that happen via BGQ's special malloc.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 21:52:41*

---
Would fixing #63 have prevented or mitigated this?
