### ISSUE TITLE
Charm fails to compile on BGQ and Cray XE giving an error in TopoManager.C 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1405]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1405*

---
Machine: Vesta

Latest commit: 22035bcbda2e7987ee429d586243a90b35f4a8b7 (Bug #815: Add OPTS to hybrid API makefile)

Possible suspects: fa88d7f97cc947105af60fdb7e3dd60f1c65b705 (Bug 337) & 7f661eec7733721c6977c329f0976b715ee65c34 (TopoManager Cleanup)

Command and Error with xlc compiler: (./build charm++ pamilrts-bluegeneq --with-production -j16)
"TopoManager.C", line 193.8: 1540-0218 (S) The call does not match any parameter list for "rankToCoordinates".
"BGQTorus.h", line 75.17: 1540-1283 (I) "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &)" is not a viable candidate.
"TopoManager.C", line 193.3: 1540-1289 (I) The implicit object parameter of type "BGQTorusManager &" cannot be initialized with an implied argument of type "const BGQTorusManager".
"BGQTorus.h", line 89.17: 1540-1283 (I) "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &, int &, int &)" is not a viable candidate.
"TopoManager.C", line 193.8: 1540-0215 (I) The wrong number of arguments has been specified for "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &, int &, int &)".
"TopoManager.C", line 228.8: 1540-0218 (S) The call does not match any parameter list for "rankToCoordinates".
"BGQTorus.h", line 75.17: 1540-1283 (I) "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &)" is not a viable candidate.
"TopoManager.C", line 228.8: 1540-0215 (I) The wrong number of arguments has been specified for "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &)".
"BGQTorus.h", line 89.17: 1540-1283 (I) "BGQTorusManager::rankToCoordinates(int, int &, int &, int &, int &, int &, int &)" is not a viable candidate.
"TopoManager.C", line 228.3: 1540-1289 (I) The implicit object parameter of type "BGQTorusManager &" cannot be initialized with an implied argument of type "const BGQTorusManager".
"TopoManager.C", line 268.15: 1540-0218 (S) The call does not match any parameter list for "coordinatesToRank".
"BGQTorus.h", line 109.16: 1540-1283 (I) "BGQTorusManager::coordinatesToRank(int, int, int, int)" is not a viable candidate.
"TopoManager.C", line 268.10: 1540-1289 (I) The implicit object parameter of type "BGQTorusManager &" cannot be initialized with an implied argument of type "const BGQTorusManager".
"BGQTorus.h", line 138.16: 1540-1283 (I) "BGQTorusManager::coordinatesToRank(int, int, int, int, int, int)" is not a viable candidate.
"TopoManager.C", line 268.15: 1540-0215 (I) The wrong number of arguments has been specified for "BGQTorusManager::coordinatesToRank(int, int, int, int, int, int)".
"TopoManager.C", line 285.15: 1540-0218 (S) The call does not match any parameter list for "coordinatesToRank".
"BGQTorus.h", line 109.16: 1540-1283 (I) "BGQTorusManager::coordinatesToRank(int, int, int, int)" is not a viable candidate.
"TopoManager.C", line 285.15: 1540-0215 (I) The wrong number of arguments has been specified for "BGQTorusManager::coordinatesToRank(int, int, int, int)".
"BGQTorus.h", line 138.16: 1540-1283 (I) "BGQTorusManager::coordinatesToRank(int, int, int, int, int, int)" is not a viable candidate.
"TopoManager.C", line 285.10: 1540-1289 (I) The implicit object parameter of type "BGQTorusManager &" cannot be initialized with an implied argument of type "const BGQTorusManager".

Command and Error with gcc: (./build charm++ pamilrts-bluegeneq gcc --with-production -j16)
   Command /bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc64-bgq-linux-g++ -Wno-deprecated -I../bin/../include -I/bgsys/drivers/ppcfloor/comm/include -I/bgsys/drivers/ppcfloor/spi/include -I/bgsys/drivers/ppcfloor -I/bgsys/drivers/ppcfloor/spi/include/kernel/cnk -I/soft/libraries/alcf/current/gcc/ZLIB//include -D__CHARMC__=1 -O3 -U_FORTIFY_SOURCE -fno-stack-protector -std=c++0x -c global-elfgot.C -o global-elfgot.o returned error code 1
charmc exiting...
TopoManager.C: In member function 'void TopoManager::rankToCoordinates(int, int&, int&, int&, int&) const':
TopoManager.C:193: error: passing 'const BGQTorusManager' as 'this' argument of 'void BGQTorusManager::rankToCoordinates(int, int&, int&, int&, int&)' discards qualifiers
TopoManager.C: In member function 'void TopoManager::rankToCoordinates(int, int&, int&, int&, int&, int&, int&) const':
TopoManager.C:228: error: passing 'const BGQTorusManager' as 'this' argument of 'void BGQTorusManager::rankToCoordinates(int, int&, int&, int&, int&, int&, int&)' discards qualifiers
TopoManager.C: In member function 'int TopoManager::coordinatesToRank(int, int, int, int) const':
TopoManager.C:268: error: passing 'const BGQTorusManager' as 'this' argument of 'int BGQTorusManager::coordinatesToRank(int, int, int, int)' discards qualifiers
TopoManager.C: In member function 'int TopoManager::coordinatesToRank(int, int, int, int, int, int) const':
TopoManager.C:285: error: passing 'const BGQTorusManager' as 'this' argument of 'int BGQTorusManager::coordinatesToRank(int, int, int, int, int, int)' discards qualifiers
Fatal Error by charmc in directory /gpfs/vesta-home/nbhat/software/changa/changa_reg/charm/pamilrts-bluegeneq-gcc/tmp/topomanager

This happens with cray compilers on bluewaters as well.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-10 15:52:06*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2233/~~ https://github.com/UIUC-PPL/charm/commit/242927800ad0039cba771e84846a6cb2c777eae1

**Comment by stwhite91** [comment]
*Original date: 2017-02-10 17:39:39*

---
Related fix for Cray XE: ~~https://charm.cs.illinois.edu/gerrit/#/c/2234/~~ https://github.com/UIUC-PPL/charm/commit/5d9a7e7c9783df1188ca7a9420ea19191e533fc2

**Comment by PhilMiller** [comment]
*Original date: 2017-02-10 21:24:00*

---
Both fixes (BGQ, Cray XT/XE) merged
