### ISSUE TITLE
Improve visibility and usability of flushTraceLog()

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1408]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1408*

---
I just went looking in the manual for how to force Projections logs out to disk at a defined point in my application code, and couldn't find it. I dug around and eventually found `flushTraceLog()` in the header. This belongs in the manual, and should have a prototype in a standard header if it's not already. It should also have an empty definition for when there's no tracing bits linked in, so the user can call it without conditional compilation.

* Document it in the manual
* Add its prototype to a standard user-facing header, so it's always visible
* Implement a no-op version for when the real version isn't going to be linked

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:12*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by stwhite91** [comment]
*Original date: 2017-04-14 16:07:31*

---
bump

**Comment by rbuch** [comment]
*Original date: 2017-05-04 00:04:14*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2495/~~ https://github.com/UIUC-PPL/charm/commit/7d87a2f83032d1a155776395b343ef1ee0d38631
