### ISSUE TITLE
AMPI failure after Isomalloc migration on multicore/SMP darwin builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1429]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1429*

---

```

$ ./build AMPI netlrts-darwin-x86_64 smp --with-production --enable-error-checking -g
$ cd examples/ampi/Cjacobi3D/
$ make test OPTS="-O0 -g"

$ ./charmrun +p3 ./jacobi.iso 2 2 2 40 +vp8 +balancer RotateLB +LBDebug 1 ++local
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.007 seconds.
Charm++> Running in SMP mode: numNodes 3,  1 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: dad73e6
Warning> using Isomalloc in SMP mode, you may need to run with '+isomalloc_sync'.
Charm++> scheduler running in netpoll mode.
CharmLB> Verbose level 1, load balancing period: 0.5 seconds
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (16-way SMP).
Charm++> cpu topology info is gathered in 0.020 seconds.
[0] RotateLB created
iter 1 time: 0.100509 maxerr: 2020.200000
iter 2 time: 0.080193 maxerr: 1696.968000
iter 3 time: 0.093471 maxerr: 1477.170240
iter 4 time: 0.087024 maxerr: 1319.433024
iter 5 time: 0.096100 maxerr: 1200.918072

CharmLB> RotateLB: PE [0] step 0 starting at 0.558446 Memory: 17.867691 MB
CharmLB> RotateLB: PE [0] strategy starting at 0.558878
CharmLB> RotateLB: PE [0] Memory: LBManager: 920 KB CentralLB: 3 KB
CharmLB> RotateLB: PE [0] #Objects migrating: 8, LBMigrateMsg size: 0.00 MB
CharmLB> RotateLB: PE [0] strategy finished at 0.559023 duration 0.000145 s
CharmLB> RotateLB: PE [0] step 0 finished at 0.596226 duration 0.037780 s

------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: AMPI_Irecv failed with error code MPI_ERR_RANK: invalid rank
Fatal error on PE 0> AMPI_Irecv failed with error code MPI_ERR_RANK: invalid rank
make[3]: *** [test] Error 1

```

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-22 18:16:02*

---
It crashes with a segfault when running with +p2 instead of +p3.

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-22 22:31:10*

---
clang 's new operator seems to not use malloc(). Therefore, the malloc is not intercepted by isomalloc, resulting in the crash after migration.

**Comment by stwhite91** [comment]
*Original date: 2017-02-22 23:13:59*

---
The above is seemingly true only on darwin. The workaround fix for jacobi.C (use malloc instead of new) would be good to have merged soon, so that automated testing can be improved, but we'll need to figure out what memory allocation routine Clang is actually calling in new().

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-23 00:31:35*

---
After some more debugging, it seems libc++ of clang is calling malloc after all, but this call does not get redirected to isomalloc. 
The trace is:

libc++abi.dylib`operator new
libc++abi.dylib`malloc
libsystem_malloc.dylib`malloc
libsystem_malloc.dylib`malloc_zone_malloc

**Comment by matthiasdiener** [comment]
*Original date: 2017-02-23 21:36:52*

---
I took a first stab at the problem by explicitly providing new/delete functions on darwin.

~~https://charm.cs.illinois.edu/gerrit/2265~~ https://github.com/UIUC-PPL/charm/commit/baf59a6929142b322f3f65c2ca9f5708ced1b1ad
