### ISSUE TITLE
CthThread tracing broken - threads show up as black, dummy_thread_chare assigned to following entry

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1430]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1430*

---
Running NAMD with three patches per pe, each of which has a Cthread (created by CthCreate, managed by CthSuspend and CthAwaken). The three patch sequencer threads tend to run back-to-back. In Projections the first thread resume is black but you can see the message sends and trace back to them, the next two are dummy_thread_chare (correct), and then a later entry point is also labeled dummy_thread_chare but is clearly something else. If the threads do not run back-to-back the thread is black and the following entry is incorrectly labelled dummy_thread_chare.

**Comment by stwhite91** [comment]
*Original date: 2017-02-21 04:24:56*

---
This also renders AMPI Projections traces almost useless

**Comment by PhilMiller** [comment]
*Original date: 2017-02-27 21:08:03*

---
Jim, could you try things out with mainline charm (without that change reverted) with added calls to traceAddThreadListeners(thread, NULL) at the three places in NAMD's code it creates threads explicitly?

If that works, would you consider that as an acceptable permanent fix in NAMD's code? I would add an equivalent call in CthCreate itself, except that for threaded entry methods, we want to pass an envelope argument tracing back to whatever spurred the creation of the thread.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-27 21:11:59*

---
Actually, while potentially nice, I realize that solution won't be acceptable for AMPI, because apparently thread listeners don't follow migratable threads when they move.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-27 21:22:11*

---
https://charm.cs.illinois.edu/gerrit/2269 should clear things up for the non-[threaded] entry method case. I'll still need to investigate whether that produces messed-up traces for [threaded] entry methods, but at least it won't be a regression relative to previous releases.

**Comment by jcphill** [comment]
*Original date: 2017-03-01 16:29:00*

---
Tested 2269, threads trace back to where they were created rather than where they were awakened.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-13 16:48:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2302/~~ https://github.com/UIUC-PPL/charm/commit/6067d0763c21943ad3d00253dedbfb61c101f2b3
Full revert for now, since the affected functionality is more critical to current use than the cases improved by the change.

I'll revisit this a bit later, and hopefully get things working right. We need a good set of tests for thread tracing in various forms, and that will take some time to develop.

**Comment by stwhite91** [comment]
*Original date: 2017-12-06 15:20:19*

---
Patch here, needs to be tested on NAMD: ~~https://charm.cs.illinois.edu/gerrit/#/c/3359/~~ https://github.com/UIUC-PPL/charm/commit/5c4f5d6b29737c850da00d16707e426ff43fe9d3
