### ISSUE TITLE
Document CkLoop caller function

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1432]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1432*

---
This API change is not reflected in the manual:
~~https://charm.cs.illinois.edu/gerrit/#/c/947/~~ https://github.com/UIUC-PPL/charm/commit/294d0d8de422077099e72153d28856d944403f39

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 15:36:06*

---
This should be quick/easy, so bumping priority.
