### ISSUE TITLE
lambda syntax for CkLoop

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1433]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1433*

---
Support syntax similar to the following:

```
CkLoop_Parallelize( numChunks, lowerRange, upperRange,
  [=](int first, int last) {
    for ( int i=first; i<=last; ++i ) {
      ...
    }
  }, sync, redResult, type, [=]() {
    ... optional caller function body ...
  }
);
```

I altered the order of arguments to keep the loop bounds at the top.

[CkLambda.h](https://github.com/UIUC-PPL/charm/files/3536625/CkLambda.h.txt)

**Comment by jcphill** [comment]
*Original date: 2017-02-23 14:01:59*

---
Prototype implementation attached.

Missing reductions (more complex reductions should be supported anyway).

Does implement fall-through for numChunks = 1 (or numChunks = 0 with caller function).

Non-sync isn't implemented, since the lambda is being passed between threads as a std::function<void()>* and there would need to at least be a way to preserve and then destroy the std::function after the CkLoop_Parallelize call exits.  Capture by reference of local variables would of course never work.

**Comment by kavithachandrasekar** [comment]
*Original date: 2018-01-10 20:48:12*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3498/~~ https://github.com/UIUC-PPL/charm/commit/15894555a442ada63404167fcecad0997c966f15

This patch adds Jim's lambda syntax prototype to CkLoop. I will look to add reduction and non-sync support to this.
