### ISSUE TITLE
optimize degenerate CkLoop cases

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1434]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1434*

---
When calling CkLoop_Parallelize with numChunks == 1 and no caller function the calling PE should do the work itself.
If numChunks == 0 calling PE should do the work itself even if there is a caller function.
Basically, if ( numChunks + ! ! cfunc < 2 ) do work on calling PE.
This behavior will simplify turning CkLoop off without duplicating code.

**Comment by stwhite91** [comment]
*Original date: 2017-07-13 20:40:32*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2782/~~ https://github.com/UIUC-PPL/charm/commit/59b4dc3fc01989db1987ddf10a335654d7413aea
