### ISSUE TITLE
CkLoop worker traces to previous entry on pe rather than caller

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1437]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1437*

---
CkLoop work shows up as ckloop_converse_chare::CkLoop with "created by" and "executed on" both correct, but tracing falls back to to previous entry on execution pe rather than actual creator (CkLoop Parallelize caller).

**Comment by sbak5** [comment]
*Original date: 2017-09-27 06:01:06*

---
This is because CkLoop uses converse msgs by default. The msg doesn't contain info of the caller.

Figure out how to contain this info in the msg and use it for tracing.

**Comment by sbak5** [comment]
*Original date: 2017-09-28 22:04:11*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3084/~~ https://github.com/UIUC-PPL/charm/commit/1620b19d543848e3ee1e8ad4ff32c440491698de
