### ISSUE TITLE
off-node messages show created by receiving node comm thread

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1438]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1438*

---
Entries for messages sent by other nodes show that the are created by the communication thread of the receiving node rather than the pe that actually sent the message.

./build charm++ verbs-linux-x86_64-smp-iccstatic --no-build-shared --enable-tracing --enable-tracing-commthread -optimize

**Comment by PhilMiller** [comment]
*Original date: 2017-02-21 18:25:09*

---
I assume this is about what's seen in Projections Timeline, and not some other tool.

Does the point on the comm thread then trace back to the sender?

When you say "show that they are created by the communication thread of the receiving node", do you mean the trace-back line, the value in the info box displayed on mouse-over, or something else?

**Comment by jcphill** [comment]
*Original date: 2017-02-21 20:40:53*

---
Yes, Timeline.
Hovering shows "Created by: CommP (N0)".
Details window shows "CREAYED BY: Processor 220" (for a 220-PE run).
Single click goes back to local comm thead.
Single click with "Trace messages back" goes past comm thread to sender and beyond.
Single click with "Trace messages forward" only goes to receiving node comm thread.

**Comment by stwhite91** [comment]
*Original date: 2018-05-01 21:45:19*

---
This is one of two remaining bugs targeted at v6.9.0

**Comment by rbuch** [comment]
*Original date: 2018-05-02 23:32:15*

---
https://charm.cs.illinois.edu/gerrit/#/c/projections/+/4105/
