### ISSUE TITLE
Lies at startup about "The comm. thread both sends and receives messages"

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1441]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1441*

---
There is logic for setting and reporting Cmi_smp_mode_setting at startup, but this only reflects the behavior of the mpi-smp and gni-smp layers.

```
jim`sunnyvale$grep -r Cmi_smp_mode_setting .
./arch/util/machine-common-core.c:static enum MACHINE_SMP_MODE Cmi_smp_mode_setting = COMM_THREAD_SEND_RECV;
./arch/util/machine-common-core.c:      if (Cmi_smp_mode_setting == COMM_THREAD_SEND_RECV) {
./arch/util/machine-common-core.c:      } else if (Cmi_smp_mode_setting == COMM_THREAD_ONLY_RECV) {
./arch/util/machine-common-core.c:      } else if (Cmi_smp_mode_setting == COMM_WORK_THREADS_SEND_RECV) {
./arch/util/machine-common-core.c:      } else if (Cmi_smp_mode_setting == COMM_THREAD_NOT_EXIST) {
./arch/util/machine-common-core.c:	if(Cmi_smp_mode_setting == COMM_THREAD_ONLY_RECV
./arch/util/machine-common-core.c:	   || Cmi_smp_mode_setting == COMM_THREAD_NOT_EXIST)
./arch/mpi/machine.c:    if (Cmi_smp_mode_setting == COMM_THREAD_SEND_RECV) {
./arch/mpi/machine.c:  if (Cmi_smp_mode_setting == COMM_THREAD_ONLY_RECV) {
./arch/mpi/machine.c:    if(Cmi_smp_mode_setting == COMM_THREAD_SEND_RECV){
./arch/mpi/machine.c:    }else if(Cmi_smp_mode_setting == COMM_THREAD_ONLY_RECV) {
./arch/mpi/machine.c:      Cmi_smp_mode_setting = COMM_THREAD_ONLY_RECV;
./arch/mpi/machine.c:    if (Cmi_smp_mode_setting == COMM_THREAD_SEND_RECV)
./arch/mpi/machine.c:    if (Cmi_smp_mode_setting == COMM_THREAD_ONLY_RECV && _thread_provided != MPI_THREAD_MULTIPLE) {
./arch/mpi/machine.c:        Cmi_smp_mode_setting = COMM_THREAD_SEND_RECV; 
./arch/gni/machine.c:    Cmi_smp_mode_setting = COMM_WORK_THREADS_SEND_RECV;

```

**Comment by jcphill** [comment]
*Original date: 2017-02-21 22:03:31*

---
More specifically, verbs and net-ibverbs only use the comm thread for receives.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:13*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by minitu** [comment]
*Original date: 2017-04-06 00:13:30*

---
Patch pushed to gerrit [[~~https://charm.cs.illinois.edu/gerrit/#/c/2360/~~ https://github.com/UIUC-PPL/charm/commit/adb3fc3ee35e6ece9ff4258746d5c371493b27ce]]

**Comment by nitbhat** [comment]
*Original date: 2017-08-31 20:25:32*

---
A pamilrts-smp build, which doesn't use a comm thread, also displays this message "The comm. thread both sends and receives messages". Additionally, it'll be good to do a rundown of smp builds for all machine layers and test if the comm thread mode is displayed correctly.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-15 18:02:49*

---
Nitin, could you follow up with checks on the other layers and note whether/what needs to be done here?

**Comment by nitbhat** [comment]
*Original date: 2017-09-22 17:10:54*

---
Sure. I'll do that.

**Comment by nitbhat** [comment]
*Original date: 2017-09-27 22:30:34*

---
Did a rundown of the LRTS layers to confirm that the displayed message is correct. The default mode is COMM_THREAD_SEND_RECV. gni, netlrts, mpi, ofi and pamilrts async mode all use the default mode. verbs is set to COMM_THREAD_ONLY_RECV and pamilrts smp mode (not async) is set to COMM_THREAD_NOT_EXIST. 

Fix for verbs: ~~https://charm.cs.illinois.edu/gerrit/#/c/2360/~~ https://github.com/UIUC-PPL/charm/commit/adb3fc3ee35e6ece9ff4258746d5c371493b27ce
Fix for pamilrts:  ~~https://charm.cs.illinois.edu/gerrit/#/c/3081/~~ https://github.com/UIUC-PPL/charm/commit/b3350c8a77b9a1d2ebb770c057819e67fe969bb9
