### ISSUE TITLE
mpi-crayxc failure in megampi

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1445]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1445*

---
megampi fails on mpi-crayxc build on Edison on the first run with multiple PEs, with +p2 +vp2. Possibly due to migration?

**Comment by karthiksenthil** [comment]
*Original date: 2017-02-28 19:26:02*

---
The following is a trace of the crash on Edison:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_SINGLE (desired: MPI_THREAD_SINGLE)
Charm++> Running in non-SMP mode: numPes 2
Converse/Charm++ Commit ID: [New Thread 0x2aaaaacca700 (LWP 5994)]

Program received signal SIGSEGV, Segmentation fault.
__longjmp () at ../sysdeps/x86_64/__longjmp.S:56
56	../sysdeps/x86_64/__longjmp.S: No such file or directory.
```


I also verified that the program does not reach AMPI initialization functions like `ampiNodeInit` and `ampiProcInit`. It crashes even before these functions are executed.

**Comment by stwhite91** [comment]
*Original date: 2017-02-28 19:31:07*

---
The stack trace looks like a failure during a context switch but is pretty opaque. What is weird is that the other AMPI tests/examples pass manual testing...

**Comment by stwhite91** [comment]
*Original date: 2017-03-06 14:25:12*

---
Fixed by making context threads the default on mpi-crayxc: ~~https://charm.cs.illinois.edu/gerrit/#/c/2282/~~ https://github.com/UIUC-PPL/charm/commit/2ed0f878ab41eaf766ab0fed8f9546d601a278a5
