### ISSUE TITLE
AMPI_Reduce is broken for derived datatypes in user-defined reductions

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1447]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1447*

---
Users are allowed to use derived datatypes in custom reduction functions, but AMPI does not support that and might silently corrupt memory in such a case.

**Comment by PhilMiller** [comment]
*Original date: 2017-03-02 19:31:39*

---
As noted in meeting, there are two potential quick fixes to at least get codes hitting this case running or failing clearly:

* Abort if this case arises
* Implement the reduction as a gather to the root, and reduce locally. In allreduce, a root rank can then broadcast the result.

**Comment by stwhite91** [comment]
*Original date: 2017-03-02 19:40:02*

---
Abort: ~~https://charm.cs.illinois.edu/gerrit/#/c/2280/~~ https://github.com/UIUC-PPL/charm/commit/d5de7f68a8e0913f505fa560d9b26ad1b30c06f1

I can probably get to the 'gather' implementation tomorrow or this weekend.

**Comment by stwhite91** [comment]
*Original date: 2017-03-05 02:27:49*

---
Implemented user-defined reductions on non-contiguous derived datatypes using the non-commutative reduction code path: ~~https://charm.cs.illinois.edu/gerrit/#/c/2289/~~ https://github.com/UIUC-PPL/charm/commit/21d600fe7223a242a081ff9e844feb5f1edcb155

**Comment by stwhite91** [comment]
*Original date: 2017-03-05 16:07:28*

---
Oops, not yet
