### ISSUE TITLE
verbs-linux-ppc64le xlC

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1452]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1452*

---
Need to support verbs (vs net-ibverbs) with xlC on Summit-dev.
Hard to tell people to try verbs because net-ibverbs is deprecated without it.

**Comment by stwhite91** [comment]
*Original date: 2017-03-03 00:18:44*

---
Do any PPLers have access to summit-dev? If so assign to one of them.

**Comment by stwhite91** [comment]
*Original date: 2017-04-04 20:43:24*

---
This should be quick/easy

**Comment by bilgeacun** [comment]
*Original date: 2017-04-11 17:38:50*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2383~~ https://github.com/UIUC-PPL/charm/commit/d0101cb91a79379070878fe6a19b63bcb9feeb5d
