### ISSUE TITLE
Branching factor for group sections is not handled correctly.

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1453]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1453*

---
No body.

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2017-03-03 22:25:10*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2287~~ https://github.com/UIUC-PPL/charm/commit/b0ad86afc529b2bc3500b951b5cf8030b9124e8c

**Comment by PhilMiller** [comment]
*Original date: 2017-03-14 18:48:26*

---
Fix was merged over a week ago
