### ISSUE TITLE
Zero-copy send support for the MPI machine layer

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1458]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1458*

---
As Jim noted, it's straightforward for MPI to do in-place sends, and newer versions actually allow RMA, so we should support at least zero copy sends, and work up to true one-sided operation.

**Comment by nitbhat** [comment]
*Original date: 2017-03-13 06:39:23*

---
Gerrit Link: ~~https://charm.cs.illinois.edu/gerrit/#/c/2299/~~ https://github.com/UIUC-PPL/charm/commit/42f392ee31e50e6775fb7648880ad3dfa875d8433
