### ISSUE TITLE
Update list of available load balancing strategies in the manual

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1466]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1466*

---
The LB section of the Charm++ manual has a list of available load balancing strategies, which is missing some.
In particular, I think RotateLB should be added with a clear explanation that it is useful for debugging PUP routines and other migration-related failures in applications. Also, GreedyRefineLB and whatever other ones are missing from there that are used.

http://charm.cs.illinois.edu/manuals/html/charm++/7.html#SECTION01620000000000000000

**Comment by stwhite91** [comment]
*Original date: 2017-04-13 15:35:45*

---
This should be quick/easy, so bumping priority

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-13 18:12:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2390/~~ https://github.com/UIUC-PPL/charm/commit/a89a2ede6d2d9973c3ae819b7290f4d8f776a24a
