### ISSUE TITLE
mpi-win-x86_64 fails in collidethread example

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1474]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1474*

---
mpi-win-x86_64 has failed in this example the last 2 days (since AMPI was fixed on mpi-win):
```
make[3]: Entering directory '/home/nikhil/autobuild/mpi-win-x86_64/charm/mpi-win-x86_64/examples/collide/collidethread'
../../../bin/charmc -optimize -production   hello.ci
../../../bin/charmc -optimize -production  -c hello.C
Ignored Unrecognized argument -fno-lifetime-dse
hello.C
../../../bin/charmc -optimize -production  -language ampi -module collide -o hello hello.o
Ignored Unrecognized argument -fno-lifetime-dse
moduleinit4540.C
../../../bin/testrun  ./hello +p4 +vp10  

Running on 4 processors:  ./hello +vp10
charmrun> /cygdrive/c/Program Files/Microsoft MPI/Bin/mpiexec -n 4  ./hello +vp10


job aborted:
[ranks] message

[0-3] process exited without calling finalize

---- error analysis -----

[0-3] on CS-DEXTERITY
./hello ended prematurely and may have crashed. exit code 0xc0000005

---- error analysis -----
Makefile:21: recipe for target 'test' failed

```

**Comment by stwhite91** [comment]
*Original date: 2017-03-28 14:07:47*

---
mpi-win-x86_64-smp also fails in this the same test

**Comment by matthiasdiener** [comment]
*Original date: 2017-03-28 17:04:33*

---
Crashes with a segmentation fault even when run sequentially before starting main():

```
gdb ./hello.exe
Starting program: /home/mdiener/Work/charmtmp/mpi-win64/examples/collide/collidethread/hello.exe 
[New Thread 5096.0x159c]

Program received signal SIGSEGV, Segmentation fault.
0x000000007787f23c in ntdll!RtlAnsiStringToUnicodeString () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
```
Is there a better way to debug on win than using gdb?

**Comment by stwhite91** [comment]
*Original date: 2017-03-28 17:11:59*

---
The problem may be with the fact that this is using charmc's '-language ampi' option directly instead of using 'ampicc' (so the changes that you made to ampiCC.in are not being used here...)

**Comment by matthiasdiener** [comment]
*Original date: 2017-03-28 17:40:53*

---
Note that even when removing the fix for AMPI on mpi-win (Bug #1341), the crash is still the same.

**Comment by matthiasdiener** [comment]
*Original date: 2017-03-28 17:45:10*

---
So, in other words, we should compile/link/use *only* AMPI, not the system MPI, in the `charmc -language ampi` case?

**Comment by epmikida** [comment]
*Original date: 2017-04-13 20:09:50*

---
From what I understand, this bug came up after a change to demandCreation. One issue I have found so far is that AMPI sets _isStaticInsertion to true, but the collide library uses demand creation, and doesn't appropriately set the flag to false. However, this is not the only issue because the program crashes before even getting to main or initializing the collide library.

**Comment by epmikida** [comment]
*Original date: 2017-04-13 23:25:24*

---
My previous comment was not correct, it turns control gets to main(...) just fine, and is also able to initialize AMPI. For some reason, stuff printed to the console doesn't seem to show up until the end of execution, and don't show up at all if execution fails.

It appears that execution makes it into COLLIDE_Init and that's where the failure is occurring, seeming to have something to do with getting the local TCharm instance.

**Comment by matthiasdiener** [comment]
*Original date: 2017-04-18 16:50:00*

---
Implemented a simple fix ( ~~https://charm.cs.illinois.edu/gerrit/#/c/2416/~~ https://github.com/UIUC-PPL/charm/commit/b87764d664c72f31bc51bd21496f7516694c671b ). On mpi-win64, AMPI and TCharm were not initialized with `charmc -language ampi`, have to compile with `ampicxx`.
