### ISSUE TITLE
Define equality operators for proxies

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1475]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1475*

---
We can overload the equality operator for proxies. This stems from John Mitchell's email to the charm mailing list.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:13*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by epmikida** [comment]
*Original date: 2017-04-10 18:49:36*

---
For arrays/groups/nodegroups, this is trivial, but for singleton chares virtual IDs create an issue. A proxy that has a virtual ID is not the same as a proxy that has a non-virtual ID for the same chare.

**Comment by epmikida** [comment]
*Original date: 2017-04-11 23:19:44*

---
Implemented in ~~https://charm.cs.illinois.edu/gerrit/#/c/2387/~~ https://github.com/UIUC-PPL/charm/commit/b41a1f4acb972f1ee65b5fa669f4606a9b68df27
