### ISSUE TITLE
Charm++ Fails to Compile on Arch Linux

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1479]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1479*

---
The default configuration of charm++ (at least v6.7.1) fails to build on the Arch Linux distro Antergos (I haven't tried Arch Linux itself). The first issue is that charmc(?) tries to find `/lib/cpp` which does not exist on Arch, instead it should use `/usr/bin/cpp`. A temporary workaround is symbolically linking `/lib/cpp` to `/usr/bin/cpp` though this isn't a great long term solution.

The second issue is the error:

```
<code class="text">
Performing 'make -j 8 charm OPTS= -g -O0 QUIET=' in multicore-linux64/tmp
make: *** No rule to make target 'charm'.  Stop.
</code>
```

I was able to get past this by running `cd ./multicore-linux64/tmp && make -j8`. However, then there are issues with the documentation not building (I don't have all the LaTeX packages, nor do I think I should need them for compiling charm++). What I ultimately found worked was manually editing the Makefile in `multicore-linux64/tmp` to not have `charm++` as target but `charm` instead and removing the doc target.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 18:13:23*

---
Hi Nils,

Thanks for your report. Could you say what shell Antergos uses as /bin/sh by default, or what you have installed there?

I think we'll drop the explicit path to `/lib/cpp` and just rely on `$PATH` to find it appropriately.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 19:46:51*

---
~~https://charm.cs.illinois.edu/gerrit/2352~~ https://github.com/UIUC-PPL/charm/commit/1048e7ab8128f5ea7be0e683d22bcd73e3c16927
The `cpp` part of this issue is addressed in the patch linked.

**Comment by nilsdeppe** [comment]
*Original date: 2017-04-06 19:23:59*

---
Thanks for the fix! I can confirm that the cpp part of the issue is resolved.

Here is the output for your other question:


```
<code class="text">
$ /bin/sh --version
GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
</code>
```

**Comment by PhilMiller** [comment]
*Original date: 2017-04-06 19:34:27*

---
Could you post the `./build` command line you tried to run? I suspect it was something like

> ./build charm multicore-linux64 ...

Where the correct command, hopefully correctly documented, would be

> ./build charm++ multicore-linux64 ...

**Comment by nilsdeppe** [comment]
*Original date: 2017-04-06 19:39:11*

---
Ah yea... I am an idiot, good catch! Okay, so then this ticket is resolved with your patch. Thanks!
