### ISSUE TITLE
RDMA zero copy send implementation for multicore builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1481]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1481*

---
Currently, the RDMA send API uses the "generic" implementation in multicore builds. The generic implementation does the extra copy and sends the message like a normal parameter marshalled entry method invocation. This is a waste because in multicore we are guaranteed that the recv'er is in the same process as the sender, so we can do the direct memcpy from source buffer to receiver message that we already do on PAMI, GNI, Verbs, and MPI layers when the sender and receiver are co-located in the same logical node.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-05 20:29:36*

---
Isn't this already covered by the generic SMP support? And even if it isn't, any implementation work here would just change which thread is allocating and performing the copy, not how much data needs to be allocated or copied. I.e. Either the sender sizes and packs stuff into a marshalled message, and then passes a pointer to that message to the recipient, or the sender sizes and passes a metadata message to the recipient, which then allocates and copies the data into a message.

Am I missing something?

**Comment by stwhite91** [comment]
*Original date: 2017-04-05 22:02:12*

---
I assume what you mean by "generic SMP support" is the direct memcpy of the source buffer to a message on the recv'er, but that is only done when CMK_ONESIDED_IMPL is defined, which we don't currently do on netlrts (which multicore uses). There are no exceptions to that for multicore currently. But your point about the only difference being who does the copy is true, I didn't think about that. Should we mark this 'rejected'?

**Comment by PhilMiller** [comment]
*Original date: 2017-04-05 22:08:42*

---
It suggests that the fix for this issue is very easy - just add 

```
#if CMK_MULTICORE
#define CMK_ONESIDED_IMPL 1
#endif
```

At some appropriate spot, with a comment describing our discussion here.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-05 22:09:27*

---
Though it may make sense to separate the operability of the SMP implementation from the network-layer implementation, since this applies within-process even on layers like GNI where we don't have them working & integrated yet.

**Comment by stwhite91** [comment]
*Original date: 2017-04-05 22:20:25*

---
Just defining CMK_ONESIDED_IMPL to CMK_MULTICORE is not enough. When you link something that uses RDMA it fails with this:
```
../../../bin/charmc  -language charm++ -o pgm pingpong.o
../../../bin/../lib/libck.a(ckrdma.o): In function `CkUpdateRdmaPtrs(envelope*, int, char*, char*)':
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:223: undefined reference to `CmiSetRdmaRecvInfo'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:227: undefined reference to `CmiGetRdmaGenRecvInfoSize'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:233: undefined reference to `CmiSetRdmaRecvOpInfo'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:234: undefined reference to `CmiGetRdmaOpRecvInfoSize'
../../../bin/../lib/libck.a(ckrdma.o): In function `CkRdmaCreateMetadataMsg(envelope*, int)':
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:47: undefined reference to `CmiGetRdmaInfoSize'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:62: undefined reference to `CmiSetRdmaInfo'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:63: undefined reference to `CmiGetRdmaGenInfoSize'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:73: undefined reference to `CmiSetRdmaOpInfo'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:76: undefined reference to `CmiSetRdmaAck'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:87: undefined reference to `CmiGetRdmaOpInfoSize'
../../../bin/../lib/libck.a(ckrdma.o): In function `CkRdmaIssueRgets(envelope*)':
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:179: undefined reference to `CmiGetRdmaInfoSize'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:191: undefined reference to `CmiGetRdmaRecvInfoSize'
/dcsdata/home/swhite/charm/multicore-linux64/tmp/ckrdma.C:204: undefined reference to `CmiIssueRgets'
```
But we can provide no-op implementations of those, at least until netlrts has actual rdma support...

**Comment by stwhite91** [comment]
*Original date: 2017-04-05 23:04:15*

---
Implemented multicore RDMA support in netlrts here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2358/~~ https://github.com/UIUC-PPL/charm/commit/ae2c4f9d41c08dfc7e5a899ecb2cc1bf566f1212
