### ISSUE TITLE
Update Charm++ FAQ

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1482]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1482*

---
The “Charm++ FAQ” really needs to be updated. It is outdated in many ways: mentions of old/removed machine layers, no mention of relevant newer features, discourages use of some C++ features that are now standard/portable, and in its answer to the question “Does anybody actually use Charm++?” it only really mentions NAMD.

Go through the whole thing and update it, removing things that are no longer relevant:
http://charm.cs.illinois.edu/manuals/html/faq/manual-1p.html

**Comment by nitbhat** [comment]
*Original date: 2017-04-13 15:14:12*

---

**Comment by bilgeacun** [comment]
*Original date: 2017-04-18 19:46:45*

---
Charm++ tutorial webpage had this question that also can be added to Charm++ FAQ page:

"Is there syntax highlighting for Charm++ ci files?
Yes, there is for vim editor. 
$ cp charm/contrib/ci.vim ~/.vim/syntax/. 
$ vi ~/.vim/filetype.vim 
paste this in the file: 
au! BufRead,BufNewFile *.ci set filetype=ci 
"
