### ISSUE TITLE
Remove need for +LBCommOff

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1492]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1492*

---
The LB Database should not collect comm info unless a balancer that is running actually uses it. For PDES and fine-grained communication intensive applications the overhead of lb comm info collection is huge.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-13 20:44:32*

---
I have added the ability for LB's to specify the commStatsOn, and have removed it from command line options. There are over 10 LBs that need this option, so I am adding the option from the LB's currently.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-04-13 21:21:49*

---
https://charm.cs.illinois.edu/gerrit/#/c/2396/

**Comment by stwhite91** [comment]
*Original date: 2017-05-17 22:45:28*

---
Related: this patch allows '+LBCommOff' to avoid more of the overhead that comm stats collection entails: ~~https://charm.cs.illinois.edu/gerrit/#/c/2533/~~ https://github.com/UIUC-PPL/charm/commit/60c6d4bb5a4cbee57cf770fe141f327c309a13c9

**Comment by stwhite91** [comment]
Kavitha's patch has remaining unaddressed review comments that aren't likely to be fixed before 6.10's release. The new LB infrastructure should also not collect LB Comm stats when the LB strategy in use doesn't have any use for them.

**Comment by stwhite91** [comment]
Is this still relevant given the new LB framework?

**Comment by stwhite91** [comment]
^^^ Bump.  @rbuch @kavithachandrasekar
