### ISSUE TITLE
Broadcast trees are not topology-aware

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1494]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1494*

---
From Phil:
Looking at the implementation of our array->group->converse broadcasts, it seems that on systems with meaningful topology (e.g. GNI, PAMI), charm makes no attempt to take that into account. IIRC, this is something Jim had complained about several years ago, that I thought had been addressed.

**Comment by stwhite91** [comment]
*Original date: 2017-05-01 01:30:47*

---
This would still be great to have for 6.8.0 if you/Juan don't have any other 6.8.0 bugs.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-19 15:04:40*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2587/~~ https://github.com/UIUC-PPL/charm/commit/985bcfa12e905d5c09baf115d56cf32a57684744
