### ISSUE TITLE
Add -Werror=vla to Jenkins per-commit builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1496]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1496*

---
This will help us catch MSVC breaking commits before they make it to mainline

**Comment by stwhite91** [comment]
*Original date: 2017-04-14 16:05:52*

---
This should be quick and easy

**Comment by PhilMiller** [comment]
*Original date: 2017-04-16 13:43:08*

---
Done
