### ISSUE TITLE
charmxi fails to deal with rvalue references

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1501]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1501*

---
This is probably related to issue #1500, but having an entry method take an rvalue reference causes the `charmc` script to choke on the CI file. e.g. line 3 of:

```
<code class="cpp">
entry void observe_reduction_data(
        const Instance_t&,
        ReductionObservationData<Instance_t, ElementId<VolumeDim>, VolumeDim>&&);
</code>
```

Since rvalue references aren't implemented until C++11 this cannot be resolved until at least Charm++ v6.9.0

**Comment by stwhite91** [comment]
*Original date: 2017-11-29 21:21:20*

---
Is this fix in gerrit now somewhere? I thought it was, but I guess I was mistaken...

**Comment by PhilMiller** [comment]
*Original date: 2017-12-07 17:25:15*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3263/~~ https://github.com/UIUC-PPL/charm/commit/fc7869098f86ab81d1c8fa1f9e18bb9aa4cf08f8 addresses the performance concern here, in that (non-`inline`) entry method implementations will always be passed arguments as rvalue references. The interface declarations still won't parse rvalue reference syntax, but they can just be written as call-by-value arguments, and the generated code will take them as `const&` anyway.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:48:01*

---
Reassign to Evan based on discussion with Eric B.  Confer on how important this work is to schedule in the near future.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-08 23:09:05*

---
~~https://charm.cs.illinois.edu/gerrit/c/3490~~ https://github.com/UIUC-PPL/charm/commit/213a634bc6222463a79764064916099398f038f5

This patch adds rvalue references to charmxi's parsing grammar. I'm not sure if this is enough to fix the bug, but I would appreciate feedback and testing.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-17 17:32:51*

---
In testing this patch, a .ci file containing an rvalue reference function parameter was successfully parsed. Nils, if it would not be too much trouble, could you cherry-pick this patch and test it against the case reported in this issue description?
