### ISSUE TITLE
Fix gfortran paths on Darwin

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1502]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1502*

---
Anyone who wants to use gfortran on Darwin has to install their own compilers. Likely this is down with homebrew or macports.
So src/arch/common/conv-mach-gfortran.sh should search for gfortran of those first on Darwin, like we are now doing for gcc on Darwin since this: ~~https://charm.cs.illinois.edu/gerrit/#/c/2384/~~ https://github.com/UIUC-PPL/charm/commit/b39d8e771cfbbf731ba1a38044d38928c571544c

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-02 19:51:37*

---
* Homebrew's gfortran is called just "gfortran", and fortran programs work out of the box when specifying "gcc gfortran" as build options. (still needs ~~https://charm.cs.illinois.edu/gerrit/#/c/2579/~~ https://github.com/UIUC-PPL/charm/commit/d4bed4db01124bc879235139a86e34d9a7531fd7 )
* MacPorts' gfortran is called "gfortran-mp-6" and will need detection.

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-05 22:19:00*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/2590~~ https://github.com/UIUC-PPL/charm/commit/354017b76b64c0f377f30d25be343fa9a126456f
