### ISSUE TITLE
Improve multi-GPU support

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#1503]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1503*

---
Currently we round-robin PE's to devices which can be a problem if we only create GPU managers on even ranks with an even number of devices, etc. We should design a better scheme to assign GPU managers to devices, presumably one per device on a hardware node.

**Comment by minitu** [comment]
*Original date: 2018-10-16 16:27:39*

---
Moving issue to https://charm.cs.illinois.edu/redmine/issues/1994
