### ISSUE TITLE
Enable automated testing of tracemodes

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1504]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1504*

---
We don't currently test tracemode projections/summary/perfReport in Jenkins or autobuild.
To enable that, we need to either not run converse tests or define all the missing symbols.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-14 19:23:28*

---
Third option - ignore the tracemode when building a converse program, if that trace mode won't work with just Converse. Patch posted shortly.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-14 19:26:55*

---
~~https://charm.cs.illinois.edu/gerrit/2403~~ https://github.com/UIUC-PPL/charm/commit/cb55ffd03d14f9cb66b97137e412a7ad9438e2c5

**Comment by PhilMiller** [comment]
*Original date: 2017-04-16 13:24:10*

---
Need to make the corresponding fix for bigsim compilation/linkage as well.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-16 14:01:35*

---
~~https://charm.cs.illinois.edu/gerrit/2408~~ https://github.com/UIUC-PPL/charm/commit/122b5c45bff92898227e1ccd71c503d05445708a
Second round fix, tested working.
