### ISSUE TITLE
Deprecate hapi_pool* in favor of hapi_host*

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#1505]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1505*

---
This is pending Jaemin's patch "#2275":~~https://charm.cs.illinois.edu/gerrit/#/c/2275/~~ https://github.com/UIUC-PPL/charm/commit/1e117f16a5e82401a7c4940b5fb5cd195184cfca and that patch that introduces the malloc versions of these functions "#2407":~~https://charm.cs.illinois.edu/gerrit/#/c/2407/~~ https://github.com/UIUC-PPL/charm/commit/7401869eab4fd0d7192edc73d975011817bbc5dd.

This makes the API more extensible and allows the user to choose what memory mode they want to use when compiling. 

Places that need the change
- charm examples
- ChaNGa (already has equivalent change for the hapi_poolFree to hapi_hostFree)

**Comment by minitu** [comment]
The function signature of `hapiPoolMalloc` does not match `cudaMallocHost`, which means the current macro definitions in `hapi.h` for `hapiHostMalloc` will not work. Need to fix `hapiPoolMalloc` to have the same signature as `cudaMallocHost`, and then ChaNGa (and other apps) can use `hapiHostMalloc` and control its behavior through compile-time flags such as `HAPI_USE_CUDAMALLOCHOST` and `HAPI_MEMPOOL`.

**Comment by minitu** [comment]
Should be resolved by https://github.com/UIUC-PPL/charm/pull/3017 and https://github.com/N-BodyShop/changa/pull/79.

**Comment by minitu** [comment]
Resolved.
