### ISSUE TITLE
examples/hello/4darray breaks when doing sections

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#1506]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1506*

---
Here's the end of the output for a fresh build of netlrts-x86_64 charm. It breaks when it enters phase 2 which is the section test. 

Hi [33] from element 4 4 4 4
Phase 1 done
*** Error in `/scratch/mikida2/charm_builds/charm/examples/charm++/hello/4darray/./hello': malloc(): memory corruption (fast): 0x0000000000a96a70 ***
------------- Processor 0 Exiting: Caught Signal ------------
Reason: unknown signal

**Comment by epmikida** [comment]
*Original date: 2017-04-16 06:02:23*

---
Also, this test was not correctly being run by Autobuild, because the makefile has the wrong path to config.mk. That should probably be fixed as well.

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2017-04-27 17:39:45*

---
Patch: ~~https://charm.cs.illinois.edu/gerrit/#/c/2451/~~ https://github.com/UIUC-PPL/charm/commit/e90d1421571b0216dc42ba987285503b29fb32df
The example wasn't using messages inherited from CkMcastBaseMsg for multicast.
