### ISSUE TITLE
ckio test failure on gni-crayxc

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1507]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1507*

---
The ckio test has failed the past 2+ days on autobuild on gni-crayxc, seemingly due to a race condition between array construction and use: http://charm.cs.uiuc.edu/autobuild/cur/gni-crayxc.txt

```
make[3]: Entering directory `/scratch1/scratchdirs/acun/autobuild/gni-crayxc/charm/gni-crayxc/tests/charm++/io'
../../../bin/testrun  ./pgm +p4 4  

Running on 4 processors:  ./pgm 4
srun -n 4 -c 2 ./pgm 4
srun: Job step creation temporarily disabled, retrying
srun: Job step created
Charm++> Running on Gemini (GNI) with 4 processes
Charm++> static SMSG
Charm++> SMSG memory: 19.8KB
Charm++> memory pool init block size: 8MB, total memory pool limit 0MB (0 means no limit)
Charm++> memory pool registered memory limit: 200000MB, send limit: 100000MB
Charm++> Cray TLB page size: 8192K
Charm++> Running in non-SMP mode: numPes 4
Converse/Charm++ Commit ID: 7788005
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (48-way SMP).
Main ran
Main saw file ready
Main saw file ready
Main saw file ready
Main saw file ready
Main saw file ready
Main saw file ready
Main saw session ready
Main saw session ready
Main saw session ready
Main saw session ready
Main saw session ready
Main saw session ready
------------- Processor 1 Exiting: Called CmiAbort ------------
Reason: Cannot send a message from an array without a local branch

```

**Comment by PhilMiller** [comment]
*Original date: 2017-04-26 15:27:15*

---
I may have a simpler test case for this, or at least one that exhibits the same CmiAbort behavior.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-26 15:29:16*

---
The interesting note from the case I looked into is that a sane array ID is returned into the proxy object, but the manager and elements themselves all somehow see zero instead, and hence don't get back an object pointer when they go looking for it.

**Comment by trquinn** [comment]
*Original date: 2017-04-28 16:42:46*

---
I've been having a CkIO failure on a ChaNGa production run on Blue Waters that may be related to this.  The symptom in my case is that a CkReductionMgr associated with the CkIO WriteSession group is having its AddToInactiveList() method called, and the object members are garbage (in particular inactiveList is bad.)

**Comment by PhilMiller** [comment]
*Original date: 2017-05-11 19:36:55*

---
Looks like the issue is that a message referencing the newly-constructed write session is reaching PEs other than 0 before the constructor for the write session array. I can't rely on a group dependence for the ready message CkIO spits out, because that may only apply on one PE that has the array manager constructed, and then broadcast the array ID to PEs that don't yet have it constructed. So, #1352 would be really helpful here

**Comment by PhilMiller** [comment]
*Original date: 2017-05-11 21:40:42*

---
~~https://charm.cs.illinois.edu/gerrit/2519~~ https://github.com/UIUC-PPL/charm/commit/fff8f258e11aad1a0bd420e87d996659ee41a086

Tom, if you're still seeing this an issue here, could you try the above patch and let us know if that resolves it? Note that you'll have to pull in its predecessor as well, since it relies on a just-implemented bit of functionality that's not on mainline yet.

**Comment by trquinn** [comment]
*Original date: 2017-05-11 22:10:04*

---
It will take me a little while to reproduce my problem, since it usually happens after restarting from a checkpoint.

But I will give it a go.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-15 20:53:21*

---
I'm seeing issues with that patch on simple ChaNGa test runs. Working through them now.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-15 22:05:38*

---
Underlying issue with the patch provided, given that it was failing after restart from a checkpoint, was that an array map ID wasn't marked `readonly`, and so got lost between the initial and restarted run. Having fixed that (see patch series), ChaNGa's tests seem to run correctly for me.

**Comment by trquinn** [comment]
*Original date: 2017-05-25 13:57:02*

---
I'm not sure if it is the same bug, but after several checkpoints I get the following errors while in CkIO:
------------- Processor 2760 Exiting: Called CmiAbort ------------
Reason: Error! This group proxy has not been initialized!
------------- Processor 14927 Exiting: Called CmiAbort ------------
Reason: Requested adjustment to prior reduction!

This is with v6.8.0-beta1-156-gfff8f25 on both a Cray XE or a Cray XC.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-25 21:46:45*

---
Re-opening pending investigation

**Comment by trquinn** [comment]
*Original date: 2017-06-01 03:45:03*

---
I tried this with a later version of charm (cd4d6f8), and things seem to now be OK.
Perhaps this was related to Bug #1568: Fix chare array initCallback to deliver a CkReductionMsg?

**Comment by PhilMiller** [comment]
*Original date: 2017-06-01 19:14:09*

---
The subsequent fixed issue you found seems likely to have been the culprit. Reclosing for now.

**Comment by trquinn** [comment]
*Original date: 2017-07-14 03:33:18*

---
I'm getting this failure again on Blue Waters using charm version 5fd855b.  It seems to only be happening with large node count (1024) and after a restart.  I've got the latest crash in ~trq/scratch/h201824mr if that helps.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-08 21:45:38*

---
Tom, with the other fix that you recently pushed, could you test that this still reproduces, and potentially open a new bug with the full details of the current observed failure?

**Comment by trquinn** [comment]
*Original date: 2017-08-08 22:09:44*

---
The fix I pushed is a direct result of digging in to the crash here.  I'm almost certain that this is fixed, but I am rerunning to be sure.

**Comment by trquinn** [comment]
*Original date: 2017-08-14 16:37:34*

---
With the recent fix, I can no longer reproduce this bug.  I recommend this issue be closed.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-14 16:43:25*

---
Thank you, done. Sorry for the trouble, and thank you for the fixes.
