### ISSUE TITLE
Align -optimize flags with current release of GNU compilers

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#151]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/151*

---
We provide a generic wrapper for various backend compilers in charmc, and a flag `-optimize` that's meant to provide good optimization settings for any given backend without breaking things. Every new compiler release brings new optimization settings along with it. We haven't necessarily kept up with these releases and the options they bring to the table.

We should make sure that the flags we pass GNU compilers under `-optimize` are appropriate for the most recent few releases (probably 4.4-4.8, given how long they stay in service), in terms of performance, reliability, and compatibility.

**Comment by stwhite91** [comment]
*Original date: 2018-04-25 05:47:01*

---
The GCC documentation doesn't specify very many optimization options that aren't enabled by default at -O3 and which don't relax semantics. I did find a couple:

-fipa-pta

Perform interprocedural pointer analysis and interprocedural modification and reference analysis. This option can cause excessive memory and compile-time usage on large compilation units. It is not enabled by default at any optimization level.

-flto

Enable link-time optimization. Already have an open issue for that here: https://charm.cs.illinois.edu/redmine/issues/1817
