### ISSUE TITLE
Throw a runtime error for registrations that occur after startup

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#1514]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1514*

---
This specifically comes up for templated entry methods that aren't explicitly instantiated in the ci file. If you forgot to instantiate a version of the templated entry method, the code still compiles and links fine but at runtime, the behavior is undefined and no errors are ever thrown. One quick fix for this behavior would be to at least throw an error if a new registration occurs after startup.

**Comment by sbak5** [comment]
*Original date: 2017-05-01 22:17:35*

---
This issue doesn't happen on multicore version. Even without instantiation of template on ci files, the application is compelled, linked and executed on multicore version. 

Investigating this issue.

**Comment by epmikida** [comment]
*Original date: 2017-05-01 22:57:18*

---
I think that's just a symptom of the example program I gave you. The call to the entry method that wasn't instantiated was done in the main chare constructor, so it was still during startup. If you move that call to somewhere after startup completes then I suspect multicore will have the same problem.

**Comment by sbak5** [comment]
*Original date: 2017-05-10 07:40:21*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2510/~~ https://github.com/UIUC-PPL/charm/commit/5b0dd6364ea32405c1a48ad5bafe5b2837a99714

**Comment by sbak5** [comment]
*Original date: 2017-05-10 20:55:31*

---
After the initialization is done, the calling the templated entry method in an uninstantiated form leads to CkAbort. Probably this patch helps the issue resolved.
