### ISSUE TITLE
Document [inline] entry method optimization for const& args

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1515]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1515*

---
This came up in the advanced tutorial session following the workshop. The new optimization is not in the manual, and we should probably include an explanation of when you'd want to use inline.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-13 20:55:10*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2679/~~ https://github.com/UIUC-PPL/charm/commit/a60828e8ae62eff6394b34948c9ed8754729283a
