### ISSUE TITLE
Document PAPI Projections integration

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1517]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1517*

---
This came up in the advanced tutorial session and there's nothing in the manual about how to use it or what exactly it shows.

**Comment by rbuch** [comment]
*Original date: 2017-06-13 20:17:25*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2695/~~ https://github.com/UIUC-PPL/charm/commit/d57e56870958dda69db7cd4dc5d2bec4291ebeda
