### ISSUE TITLE
net-linux-x86_64-ibverbs-smp-iccstatic build failure in machine-ibverbs.c

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1518]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1518*

---

```

../bin/charmc  -optimize -production   -I. -o machine.o  -DFOR_CPLUS=1 machine.c
In file included from machine-dgram.c(819),
                 from machine.c(1651):
machine-ibverbs.c(2677): warning #167: argument of type "char **" is incompatible with parameter of type "void **"
            posix_memalign(&res, ALIGN_BYTES, size + sizeof(void*));
                           ^

machine.c(2623): warning #556: a value of type "int **" cannot be assigned to an entity of type "unsigned int **"
    CpvInitialize(int , networkProgressCount);
    ^

machine.c(3031): error: identifier "Cmi_smp_mode_setting" is undefined
    Cmi_smp_mode_setting = COMM_THREAD_ONLY_RECV;
    ^

machine.c(3031): error: identifier "COMM_THREAD_ONLY_RECV" is undefined
    Cmi_smp_mode_setting = COMM_THREAD_ONLY_RECV;
                           ^

compilation aborted for machine.c (code 2)
Fatal Error by charmc in directory /scratch/users/jcphill/charm-6.8.0-build-2017-Apr-19-89514-net-linux-x86_64-ibverbs-smp-iccstatic/charm-6.8.0-beta2/net-linux-x86_64-ibverbs-smp-iccstatic/tmp
   Command icc -D_REENTRANT -I../bin/../include -D__CHARMC__=1 -I. -DFOR_CPLUS=1 -O2 -U_FORTIFY_SOURCE -c machine.c -o machine.o returned error code 2


```

**Comment by jcphill** [comment]
*Original date: 2017-04-19 20:07:08*

---
Almost certainly caused by ~~https://charm.cs.illinois.edu/gerrit/#/c/2360/~~ https://github.com/UIUC-PPL/charm/commit/adb3fc3ee35e6ece9ff4258746d5c371493b27ce

**Comment by stwhite91** [comment]
*Original date: 2017-04-19 20:15:17*

---
What is the motivation for using net-ibverbs-smp rather than verbs-smp?

**Comment by jcphill** [comment]
*Original date: 2017-04-19 20:31:47*

---
I build both.  If nothing else I can check for performance regressions.

**Comment by minitu** [comment]
*Original date: 2017-04-20 16:34:58*

---
Non-lrts layers do not include `util/machine-common-core.c` and do not print information about the comm threads to the user.
So reverting the change to the net layer: [[~~https://charm.cs.illinois.edu/gerrit/#/c/2424/~~ https://github.com/UIUC-PPL/charm/commit/e741736313acb206c8879d25bb152a7667a20cb9]]
