### ISSUE TITLE
Entry methods with no parameters ignore priority from CkEntryOptions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1519]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1519*

---
We've fixed zero-argument entry methods to accept CkEntryOptions at the call site, and to respect group construction dependences, so their semantics are at least strictly correct. We're just missing priority/queueing stategy now, which is part of the performance semantics, but not the program correctness.

It's clear why it's implemented this way - the code on both send and receive sides would have to be duplicated to choose between working with a zero-payload system message and a dynamically allocated message with room for a priority or whatever else the options might dictate. Nevertheless, it's a somewhat glaring and surprising inconsistency that some entry methods can be passed options, and others can't.

**Comment by nitbhat** [comment]
*Original date: 2017-11-08 02:33:04*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3265/~~ https://github.com/UIUC-PPL/charm/commit/17457e23aa39cf663bc393715576a9e58d23f142

Along with setting priority, I also set the queuing type that the user can pass using CkEntryOptions.
