### ISSUE TITLE
Verbs RDMA send fails on 0-byte sized message

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1523]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1523*

---
Obviously users shouldn't use RDMA sends for 0-byte sized arrays, but we shouldn't fail on this.

When I run AMPI on this and set its RDMA message size threshold to 0, it fails in machine-onesided.h LrtsSetRdmaOpInfo() after the call to :
```
mr = ibv_reg_mr(context->pd, (void*)ptr, size, IBV_ACCESS_REMOTE_READ |
      IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_WRITE);

```

**Comment by stwhite91** [comment]
*Original date: 2017-04-23 15:22:14*

---
I only see this error on Cab at LLNL, which has a QLogic Infiniband interconnect. On iForge at NCSA, which has a Mellanox infiniband interconnect, I don't see it... we've run into issues with QLogic vs Mellanox before in our verbs layer, so maybe this is another difference?

**Comment by minitu** [comment]
*Original date: 2017-11-01 19:50:35*

---
I'll test this on golub, which is the only verbs machine I have access to.

**Comment by minitu** [comment]
*Original date: 2017-11-07 07:25:18*

---
Can't seem to reproduce this on golub; postponed to after 6.9.0.
