### ISSUE TITLE
Unused Variable impl_obj in _call_ArchiveChare_CkMigrateMessage

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1526]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1526*

---
I get an unused variable warning in Charm++ v6.8.0-beta2 that was not present in v6.7.1. It appears in the generated `def.h` files for classes in the `_call_ArchiveChare_CkMigrateMessage(void *impl_msg, void *impl_obj_void)` function. The warning is:

```
<code class="text">
/home/nils/SpECTRE/build_charm68_gcc/Evolution/ArchiveChare.def.h:187:29: warning: unused variable ‘impl_obj’ [-Wunused-variable]
   ArchiveChare < System > * impl_obj = static_cast<ArchiveChare < System >  *>(impl_obj_void);
</code>
```

and the relevant code in the header file is:

```
<code class="cpp">
void CkIndex_ArchiveChare<System>::_call_ArchiveChare_CkMigrateMessage(
    void *impl_msg, void *impl_obj_void) {
  ArchiveChare<System> *impl_obj =
      static_cast<ArchiveChare<System> *>(impl_obj_void);
  call_migration_constructor<ArchiveChare<System> > c = impl_obj_void;
  c((CkMigrateMessage *)impl_msg);
}
</code>
```

In charm v6.7.1 the function was:

```
<code class="cpp">
void CkIndex_ArchiveChare<System>::_call_ArchiveChare_CkMigrateMessage(
    void *impl_msg, void *impl_obj_void) {
  ArchiveChare<System> *impl_obj =
      static_cast<ArchiveChare<System> *>(impl_obj_void);
  new (impl_obj) ArchiveChare<System>((CkMigrateMessage *)impl_msg);
}
</code>
```

if this isn't a bug then it looks like the cast

```
<code class="cpp">
ArchiveChare<System> *impl_obj =
      static_cast<ArchiveChare<System> *>(impl_obj_void);
</code>
```

simply shouldn't be generated anymore.

Phil currently has access to our BitBucket repo and is welcome to test this on the main branch, `feature/spectre_2b` once I have the other charm++ v6.8.0-beta2 patches in the `Support/Charm` directory. I am also happy to test patches to see if they fix the issue. We are already ignoring a lot of warnings in Charm++ header files, but this one seems like an easy one to actually fix.

**Comment by stwhite91** [comment]
*Original date: 2017-04-23 15:18:50*

---
We recently made migration constructors unnecessary for chares that never actually migrate, so I think this is related to those changes. Phil may have more insight into this, so adding him as a watcher

**Comment by nilsdeppe** [comment]
*Original date: 2017-04-23 15:21:17*

---
Okay, that could be related then. Currently we have the migration constructors defined but are empty, e.g.


```
<code class="cpp">
explicit ArchiveChare(CkMigrateMessage* /*msg*/) {}
</code>
```


in case that's helpful.

**Comment by nitbhat** [comment]
*Original date: 2017-04-26 00:22:35*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2435/~~ https://github.com/UIUC-PPL/charm/commit/5d303c25e0dadab9ca602d22b181791bc2b77144
