### ISSUE TITLE
Unused Parameter Warning in Entry Methods with no Parameters

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1527]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1527*

---
In v6.8.0-beta2 entry methods that do not have any parameters emit an unused parameter warning for `impl_e_opts`. These functions used to not take any parameters in v6.7.1. Assuming this behavior is correct this could easily be silenced with a `static_cast<void>(impl_e_opts)` in the function body.

As a concrete example:

```
<code class="cpp">
void CProxy_EvolveSystem::exit(const CkEntryOptions *impl_e_opts)
{
  ckCheck();
  void *impl_msg = CkAllocSysMsg();
  if (ckIsDelegated()) {
    int destPE=CkChareMsgPrep(CkIndex_EvolveSystem::idx_exit_void(), impl_msg, &ckGetChareID());
    if (destPE!=-1) ckDelegatedTo()->ChareSend(ckDelegatedPtr(),CkIndex_EvolveSystem::idx_exit_void(), impl_msg, &ckGetChareID(),destPE);
  } else {
    CkSendMsg(CkIndex_EvolveSystem::idx_exit_void(), impl_msg, &ckGetChareID(),0);
  }
}
</code>
```

adding the static_cast on line 3 avoids the warning.

**Comment by stwhite91** [comment]
*Original date: 2017-04-23 15:16:12*

---
It used to be that we didn't actually support CkEntryOptions on entry methods taking no arguments, but we recently added support for that. Should be easy enough to add the cast to void.

**Comment by nilsdeppe** [comment]
*Original date: 2017-04-23 15:19:18*

---
Ah okay, that explains it. I haven't used entry options (yet) so I wasn't able to provide more info. Thanks for looking at this so quickly!

**Comment by nitbhat** [comment]
*Original date: 2017-04-26 03:31:28*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2436/~~ https://github.com/UIUC-PPL/charm/commit/465ccece7e1158e5a6b4fddd60befcbf7d2274eb1

This patch only targets removing warnings for entry methods that take no arguments. We could potentially have warnings removed for other generated code too. (Probably in a later patch, targeting a later release).
