### ISSUE TITLE
Align -optimize flags with current release of IBM XL compilers

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#153]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/153*

---
We provide a generic wrapper for various backend compilers in charmc, and a flag `-optimize` that's meant to provide good optimization settings for any given backend without breaking things. Every new compiler release brings new optimization settings along with it. We haven't necessarily kept up with these releases and the options they bring to the table.

We should make sure that the flags we pass IBM's XL compilers (xlc, xlc++, xlf) under `-optimize` are appropriate for the most recent few releases, in terms of performance, reliability, and compatibility.

The first step would be to see what versions are in service, and how their documented options differ.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-09 17:48:23*

---
xlc hasn't changed things much.  We are good here.
