### ISSUE TITLE
Isomalloc on SMP mode always prints warning about +isomalloc_sync, even when not in use

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1530]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1530*

---
When running on an smp build, all programs print the message "`Warning> using Isomalloc in SMP mode, you may need to run with '+isomalloc_sync'.`" at startup, regardless of whether they're actually using isomalloc or not. This is worrisome to users. Standard development practice in the broader community is to take warnings very seriously, and consider disregarding them anathema. We should only let this warning print when it's actually applicable.

**Comment by matthiasdiener** [comment]
*Original date: 2017-04-25 21:49:21*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2433/~~ https://github.com/UIUC-PPL/charm/commit/e2765409fa1018067edb88ad6d93706fbe4fa2bd

The patch moves the warning to memory-isomalloc initialization.
