### ISSUE TITLE
Example for using Google benchmark library with Charm++

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1532]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1532*

---
The attached code shows how to use Google's benchmark library with Charm++. It's nice because it automatically does enough iterations of the measured routine to provide a reasonably stable output. We should add some version of this to our contrib or examples directory.

[simplering.cc](https://github.com/UIUC-PPL/charm/files/3536634/simplering.cc.txt)
[simplering.ci](https://github.com/UIUC-PPL/charm/files/3536635/simplering.ci.txt)

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2018-01-19 20:39:45*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3540/~~ https://github.com/UIUC-PPL/charm/commit/2a557041d88d7e4dd2631d9f601b8a22992d6cf4
