### ISSUE TITLE
State Space Search Examples Broken

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#1533]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1533*

---
The examples in examples/charm++/state_space_searchengine/ currently don't compile, due to "error: ‘class Main’ has no member named ‘pup’".  This can be resolved by adding empty pup functions to the respective Main classes, but someone should also go back over the state space search examples and library code; it looks like it hasn't been touched in a while.

**Comment by stwhite91** [comment]
*Original date: 2017-04-24 14:42:25*

---
Reviving that code is probably far down our list of priorities right now, we might as well have the fix for broken compilation pushed now and then if/when someone revives it they can fix that.

**Comment by stwhite91** [comment]
*Original date: 2017-05-03 19:26:50*

---
The mainchare class was not inheriting from CBase_Main. Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2489/~~ https://github.com/UIUC-PPL/charm/commit/ad82ba7ca0a6cfcf0a07cad59728db5cae42ed37
