### ISSUE TITLE
Format/Indent all source code files that are a part of charmxi (xlat-i)

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1535]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1535*

---
The indentation for the source code files in src/xlat-i is quite messed up and non-uniform with different regions of tabs/spaces. Fix the indentation of all the source code files with standard indentation. (2 white spaces maybe). This can be quite easily done with a good editor.

**Comment by stwhite91** [comment]
*Original date: 2017-04-24 15:23:38*

---
This patch include a clang-format file that can be used to do this automatically: https://charm.cs.illinois.edu/gerrit/#/c/1255/

**Comment by nitbhat** [comment]
*Original date: 2017-04-25 01:34:23*

---
Used clang-format to format all .C and .h files in src/xlat-i/ 
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2429/~~ https://github.com/UIUC-PPL/charm/commit/4c92dc300c4f7110fa6943ed89f297d5b50d5de8

**Comment by nitbhat** [comment]
*Original date: 2018-01-19 15:55:27*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2429/~~ https://github.com/UIUC-PPL/charm/commit/4c92dc300c4f7110fa6943ed89f297d5b50d5de8
