### ISSUE TITLE
Fix ambiguous explanations of Ctv, Cpv, and Csv variables

### ISSUE THREAD

**Issue by minitu** [UIUC-PPL/charm#1541]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1541*

---
The explanation of Ctv variables is ambiguous in the comments of the source code and in the manual.

Thus 2 fixes required:
1. Comments in `src/conv-core/converse.h`
1. Manual section 2.13.1

**Comment by stwhite91** [comment]
*Original date: 2017-04-28 23:15:39*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2468/~~ https://github.com/UIUC-PPL/charm/commit/3ca2da98bb4b20516ff7a2b49717b3ae79017616
