### ISSUE TITLE
CMK_TIMER_USE_PPC64 inaccurate with variable clock speeds

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1544]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1544*

---
The pami-linux-ppc64le machine layer is defaulting to CMK_TIMER_USE_PPC64

src/arch/pami-linux-ppc64le/conv-mach.h:#define CMK_TIMER_USE_PPC64                                1

This timer assumes a constant clock speed, which hasn't been true for a long time so projections traces are pretty useless.

CMK_TIMER_USE_GETRUSAGE seems to work much better.

**Comment by jcphill** [comment]
*Original date: 2017-08-23 18:13:03*

---
Can you link to the change that fixes this?

**Comment by rbuch** [comment]
*Original date: 2017-08-30 19:52:09*

---
I was trying to test this before I push it to Gerrit, but I've been unable to build a pami-linux-ppc64le on the machine I have access to.  I've been in contact with the OLCF staff in trying to fix this.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-13 19:36:45*

---
Intel fixed their timer instruction (rdtsc/rdtscp) to fix this kind of issue years ago, by having the counter run on a fixed clock. Has IBM really just left it as a CPU cycle counter?

Regardless, we need to get this tested.

**Comment by jcphill** [comment]
*Original date: 2017-09-14 03:33:50*

---
What I was seeing in projections sure looked like it was just counting clock cycles.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-25 15:00:28*

---
Switch to just use getrusage for now posted here: ~~https://charm.cs.illinois.edu/gerrit/3075~~ https://github.com/UIUC-PPL/charm/commit/a27a153df52d90c1c6718b3ed1e504f7d2cc92f8
