### ISSUE TITLE
RDMA example with migration

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1546]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1546*

---
The failures in AMPI RDMA have raised concern that there is something bad going on when using RDMA + migration, even when ensuring that there are no outstanding sends during migration and running with +LBSyncResume. The only existing uses of rdma are 2 pingpong examples/tests, and AMPI, so more are needed. So add rdma entry method calls to jacobi or some other example that has load balancing...

**Comment by stwhite91** [comment]
*Original date: 2017-05-04 12:46:47*

---
This is really needed now to help debug current and future issues with RDMA before 6.8.0

**Comment by stwhite91** [comment]
*Original date: 2017-05-12 13:56:01*

---
I believe Nitin modified the stencil load balancing to use RDMA, and that is pending on a fix for RDMA entry methods in SDAG: https://charm.cs.illinois.edu/redmine/issues/1553

**Comment by PhilMiller** [comment]
*Original date: 2017-05-12 22:02:30*

---
The bug that spawned this request, #1539, has now been fixed. Is it still critical to have a new test/example that specifically exercises the interaction of RDMA sends and migration? If not, this can probably be de-prioritized, delayed, or just closed/rejected (as AMPI actually does exercise this case).

**Comment by stwhite91** [comment]
*Original date: 2017-05-13 03:41:11*

---
I think it's important to have an SDAG + Migration + RDMA example/test, but up to you whether that is this issue or not

**Comment by nitbhat** [comment]
*Original date: 2017-06-01 07:40:01*

---
Added the stencil3d example as a part of the SDAG support for rdma marked entry methods. This example tests both Migration and SDAG capabilities for an entry method with an 'rdma' parameter. 

Implementation: ~~https://charm.cs.illinois.edu/gerrit/#/c/2572/~~ https://github.com/UIUC-PPL/charm/commit/364594cab57ba5793d0571bf4f706140dc2cbdb8
