### ISSUE TITLE
Better support for AMPI/Projections with multiple virtual ranks

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#1551]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1551*

---
Since the tracing framework has no idea about virtual AMPI ranks (specified with +vp), bracketed user events seem to be overlapping in time, leading to an overly nested display in Projections, as well as making it hard to determine which event belongs to which VP. Will need substantial changes in the tracing framework as well as Projections. Followup from Feature #1088.

**Comment by matthiasdiener** [comment]
*Original date: 2017-05-08 23:14:33*

---
Two WIP patches:
- ~~https://charm.cs.illinois.edu/gerrit/2503~~ https://github.com/UIUC-PPL/charm/commit/6581ba7cb55d30d1f7e33ba98c852508c11a1047 (Projections)
- ~~https://charm.cs.illinois.edu/gerrit/2504~~ https://github.com/UIUC-PPL/charm/commit/f3b3d2e2016fa67282dea698f998a112ad232d4b (Charm)

**Comment by stwhite91** [comment]
*Original date: 2017-05-09 19:00:13*

---
Related issues:

https://charm.cs.illinois.edu/redmine/issues/1005
https://charm.cs.illinois.edu/redmine/issues/1524
