### ISSUE TITLE
Chare Array construction doesn't respect setGroupDepID in CkEntryOptions (or any other entry method options)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1563]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1563*

---
`CProxy_ArrayFoo::ckNew` accepts a `CkEntryOptions` argument, but doesn't put it to sensible use.

When the underlying element constructor takes no arguments, the CkEntryOptions argument is explicitly ignored.

When the element constructor does take arguments, the group dep is read from the CkEntryOptions and set on the message that will be handed to the elements' constructor. Because that's executed inline during `CkArray::CkArray()`, it gets ignored downstream.

If construction of an array's elements depends on the the availability of some specific group that the array itself doesn't depend on, there's thus no effective way to specify this.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:46:38*

---
Per discussion with Eric B, assigning to Nitin, based on recent work around CkEntryOptions handling

**Comment by nitbhat** [comment]
*Original date: 2018-01-17 23:32:40*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3528/~~ https://github.com/UIUC-PPL/charm/commit/d24d191d92a48c9cab38b84e7565e794f588949d
