### ISSUE TITLE
Non-group entry methods don't respect envelope group dependence

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1565]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1565*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:46:38*

---
Per discussion with Eric B, assigning to Nitin, based on recent work around CkEntryOptions handling

**Comment by nitbhat** [comment]
*Original date: 2018-01-17 23:33:09*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3528/~~ https://github.com/UIUC-PPL/charm/commit/d24d191d92a48c9cab38b84e7565e794f588949d
