### ISSUE TITLE
Parameter marshalled entry methods mostly don't set group dependence in message from CkEntryOptions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1566]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1566*

---
For parameter marshalled entry methods, charmxi only generated code to pull the group dependence from CkEntryOptions into the envelope of the resulting CkMarshallMsg for (node)group constructors, and not for other message or recipient types

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:46:39*

---
Per discussion with Eric B, assigning to Nitin, based on recent work around CkEntryOptions handling

**Comment by nitbhat** [comment]
*Original date: 2018-01-17 23:33:19*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3528/~~ https://github.com/UIUC-PPL/charm/commit/d24d191d92a48c9cab38b84e7565e794f588949d
