### ISSUE TITLE
[aggregate] entry methods should refuse to accept CkEntryOptions, since the contents are unusable

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1567]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1567*

---
Without C++11 support, we can stick in

```
if (impl_e_opts) CkAbort("[aggregate] entry methods can't handle any entry method options from CkEntryOptions");
```

Post C++11, we could instead do
```
template <int a = 0>
void CProxyElement_Foo::myMethodBar(int arg, CkEntryOptions *impl_e_opts) {
static_assert(false, "[aggregate] entry methods can't handle any entry method options from CkEntryOptions");
}
```

So that users get an explicit compile-time error rather than at runtime.

**Comment by epmikida** [comment]
*Original date: 2018-01-31 19:11:13*

---
From what I can tell, since we have C++11 support, using the delete keyword seems to be the more standard way of accomplishing this.
