### ISSUE TITLE
ckio failure on netlrts-linux

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1568]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1568*

---
Autobuild for netlrts-linux failed in the code added here: https://charm.cs.illinois.edu/autobuild/cur/netlrts-linux.txt

**Comment by PhilMiller** [comment]
*Original date: 2017-05-18 16:21:28*

---
~~https://charm.cs.illinois.edu/gerrit/2537~~ https://github.com/UIUC-PPL/charm/commit/71adad8c54098346cf750c10f022dc92d3f6d2e4
