### ISSUE TITLE
Support the Flang Fortran compiler

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1569]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1569*

---
Add Flang configurations to the build system: https://github.com/flang-compiler/flang

**Comment by matthiasdiener** [comment]
*Original date: 2017-10-27 04:06:52*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/3187~~ https://github.com/UIUC-PPL/charm/commit/74652a49271f694a7ec1c934cad1f1a3bb8df963
