### ISSUE TITLE
Align -(no-)optimize flags with current release of Cray compilers

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#157]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/157*

---
We provide a generic wrapper for various backend compilers in charmc, and a flag -optimize that's meant to provide good optimization settings for any given backend without breaking things. Every new compiler release brings new optimization settings along with it. We haven't necessarily kept up with these releases and the options they bring to the table.

We should make sure that the flags we pass the Cray compilers under -optimize are appropriate for the most recent few releases, in terms of performance, reliability, and compatibility.

The first step would be to see what versions are in service, and how their documented options differ.

**Comment by ericjbohm** [comment]
*Original date: 2013-05-20 21:03:21*

---
With craycc, less is more.  The default of using no options is approximately -O2.  conv-mach already does the right thing on Cray XE, so craycc files have been committed which allows it to be chosen as part of the platform name, but do not alter the settings at all from conv-mach.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-20 21:07:40*

---
This makes me realize that we actually have the opposite problem on CCE - `charmc -no-optimize` would be a lie. We don't proactively pass a non-optimization flag like `-O0`, but rather just use it to disable charmc's own `-optimize` that may have appeared earlier on the command line.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 18:57:29*

---
We want the non-optimizations case to work too, where the user asks for it and the compiler defaults to aggressive optimization.
