### ISSUE TITLE
Cpuaffinity ignores '++quiet'

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1570]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1570*

---
When specifying a commap, cpuaffinity ignores '++quiet' and prints anyways:
```
Charm++> set comm 0 on node 0 to core #2

```

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-05 20:11:16*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2589/~~ https://github.com/UIUC-PPL/charm/commit/0e69395d0cee929eb44ad94d95baf92f7aae3401
