### ISSUE TITLE
Documentation for ReadOnly is inaccurate regarding the number of copies per process

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1571]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1571*

---
"They are broadcast to every PE by the Charm++ runtime, and can be accessed in the same way as C++ ``global'' variables on any PE. "

Readonly data is broadcast to every Cmi Node (process), only one copy exists per process. Not per PE. This applies to simple types and complicated types.  We only pup it once. 

This inaccuracy could lead to at least two different kinds of trouble 
1. Assume that one needs a different mechanism to get one copy per process readonly data, thereby wasting effort reinventing the wheel.
2. Falsely assume your readonly data has an independent copy on each PE, then modifying it (in violation of the readonly label), thus leading to ugly race conditions and correctness failures when all the PEs of a single node are in fact modifying the same data.

**Comment by stwhite91** [comment]
*Original date: 2017-05-24 03:47:39*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2549/~~ https://github.com/UIUC-PPL/charm/commit/a9cab4678a88b9054475ade4cecc7e4c74119586
