### ISSUE TITLE
Improve pup_stl performance

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1572]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1572*

---
The serialization of `std::vector` (and other STL containers) is extremely slow. The reason for this is twofold. First, `push_back` is used to push into a zero-size (not just empty) container, which results in an insane amount of calls to malloc. My testing found that this can be solved by changing the `pup_stl_container` function in `pup_stl.h` to be:

```
<code class="cpp">
  template <class container,class dtype>
  inline void PUP_stl_container(er &p,container &c) {
    p.syncComment(sync_begin_array);
    int nElem=PUP_stl_container_size(p,c);
    if (p.isUnpacking()) {  // Unpacking: Extract each element and push_back:
      c.resize(nElem);
    }
    PUP_stl_container_items<container, dtype>(p, c);
    p.syncComment(sync_end_array);
  }
</code>
```

This provides a factor of 2-3 or so speedup in serializing std::vector<double>.

The second issue is that even for arithmetic types, such as int, double, and float, the same inefficient algorithm is used. By using `PUParray` for these cases I get a speedup of more than a factor of 4-5. Here is the changed function:

```
<code class="cpp">
  template <class T>
  inline void operator|(er &p, typename std::vector<T> &v) {
    if (std::is_arithmetic<T>::value) {
      int number_of_elements = PUP_stl_container_size(p, v);
      if (p.isUnpacking()) {
        if (v.size() != number_of_elements) {
          v.resize(static_cast<size_t>(number_of_elements));
          v.shrink_to_fit();
        }
      }
      PUParray(p, v.data(), number_of_elements);
    } else {
      PUP_stl_container<std::vector<T>, T>(p, v);
    }
  }
</code>
```

The code could be further optimized by removing the if statement in favor of `std::enable_if` in the function template parameters to "specialize" the function call for arithmetic and non-arithmetic functions. Unfortunately `std::is_arithmetic` is part of C++11. However, the code is easy to implement. See, for example, the libc++ implementation. At the very least this change should be made for v6.9.0.

**Comment by stwhite91** [comment]
*Original date: 2017-05-25 22:45:27*

---
I can't imagine why it was written this way, and the git history offers no explanation. I added Nils's first suggestion as a patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2554/~~ https://github.com/UIUC-PPL/charm/commit/a0bbd97ab011317faab00e5459684583082be7e6

**Comment by nilsdeppe** [comment]
*Original date: 2017-05-26 12:17:02*

---
Thank you! I think we should keep this ticket around setting the target to 6.9.0 for the second optimization. Thinking about it now, the second optimization could be added to `PUP_stl_container` by checking `container::value_type`, but that still requires C++11.

**Comment by stwhite91** [comment]
*Original date: 2017-05-26 18:19:03*

---
I added explicit specializations for the common arithmetic types so that we have that for the common cases in 6.8.0: ~~https://charm.cs.illinois.edu/gerrit/#/c/2559/~~ https://github.com/UIUC-PPL/charm/commit/d4f7eaa0e7d178d87f4b1e0b277d70db9462825b

We can leave this open targeted to 6.9.0 to complete it once we require C++11 support.

**Comment by stwhite91** [comment]
*Original date: 2017-05-30 14:34:42*

---
The two patches I posted above were merged, so the remaining issues are to specialize for all arithmetic types (or all types declared PUPbytes), and to use reserve() when possible instead of resize() to avoid calling the constructor repeatedly when unpacking.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-30 14:44:45*

---
Also to use `emplace_back` instead of `push_back` where possible to move instead of copy.

**Comment by nilsdeppe** [comment]
*Original date: 2017-05-30 14:53:52*

---
`push_back` has an r-value override in C++11, so as long as `std::move` is used that will work fine. I prefer using `emplace_back` only when wanting to call a constructor other than the copy and move, but this is merely a personal preference :)

**Comment by PhilMiller** [comment]
*Original date: 2017-05-30 15:19:08*

---
Ah, yeah, that makes sense. I'd agree with your preferred expression.

**Comment by stwhite91** [comment]
*Original date: 2017-10-27 02:46:04*

---
Implemented the second optimization here, now that we are clear of 6.8.2 and are requiring C++11 support for 6.9.0: ~~https://charm.cs.illinois.edu/gerrit/#/c/3177/~~ https://github.com/UIUC-PPL/charm/commit/78480a6186dfb157ccbe98595619b7c801827bf3
