### ISSUE TITLE
Make HDF5 library available for AMPI

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#1573]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1573*

---
Currently, the hdf5 library needs some changes to work correctly under AMPI:
* -exit vs. CkExit()-
* -charmrun output-
* -privatizing global variables-
* -Changes to build system-

We could fix these issues and integrate hdf5, similar to ROMIO.
hdf5 is licensed under a BSD-like license, so copyright should not be an issue.

**Comment by matthiasdiener** [comment]
*Original date: 2017-05-25 19:11:00*

---
With some modest changes, hdf5 compiles successfully (serial+parallel version).
The following serial tests (`make test` in `test/`) fail:
* dt_arith (does not terminate)
* swmr (does not terminate)

**Comment by stwhite91** [comment]
*Original date: 2017-05-25 19:14:29*

---
I would recompile AMPI with MSG_ORDER_DEBUG prints (top of ampi.C) enabled. That usually helps debug hangs.

**Comment by matthiasdiener** [comment]
*Original date: 2017-05-25 19:16:30*

---
Ok, I'll do that. Regarding the exit() vs. CkExit() calls, can't we just `#define exit(foo) CkExit(foo)` in ampi.h ?

**Comment by stwhite91** [comment]
*Original date: 2017-05-25 19:18:06*

---
We can now. It used to be that CkExit could only be called once by something on PE 0, I believe. That was changed recently.

**Comment by matthiasdiener** [comment]
*Original date: 2017-05-25 19:44:09*

---
CkExit has no return code parameter - how do charm++ applications signal failure?

**Comment by stwhite91** [comment]
*Original date: 2017-07-07 17:02:21*

---
Patch to merge hdf5 into the charm/ampi distribution was abandoned in favor of hosting a separate repo for our modified version of hdf5. We can potentially work with the hdf group to get the changes here merged upstream too:  https://charm.cs.illinois.edu/gerrit/#/admin/projects/hdf5-ampi

**Comment by matthiasdiener** [comment]
*Original date: 2017-07-15 21:20:01*

---
The current version of hdf5-ampi is usable and passes the PlasCom2 tests, which exercises a substantial part of the API.
Some things to followup on:

* Test if applications work with the shared library
* SMP mode to check privatization
* Virtualization
* Migration
* Some spurious crashes/segfaults at hdf5 library termination
* Test other architectures than linux/netlrts
