### ISSUE TITLE
OpenAtom crashes during launch at startup on BlueWaters using master charm

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1576]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1576*

---
Only happens when multinode runs are attempted.  Requires more experimentation to isolate issue.  

Does not happen at all when using charm from early april.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-08 19:04:53*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2644/~~ https://github.com/UIUC-PPL/charm/commit/be41d973931b1830e77889e10443607995024794

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-14 19:26:39*

---
Note that this bug can probably be considered critical as it could potentially affect any code that uses sections/ckmulticast.
