### ISSUE TITLE
Document and check restrictions on passing non-array callbacks to CkStartCheckpoint

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#158]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/158*

---
In a bit of exploration in the ChaNGa source code following from #147, I discovered the following comment:
> /// For checkpointing, the restart callback needs to be an array entry,
> /// so we have a short entry that simply calls the main entry.
This was originally written in 2007, but still appears to be true today, based on an examination of the source code in `ckcallback.h` and `charm.h`. The issue is that `CkChareID` contains a pe and an object pointer. After a restart, the address of any given chare object is quite likely to have changed.

To prevent users from tripping over this, we should update the documentation to describe what callback types are allowed for restart, and add a check to `CkStartCheckpoint` (and any similar functions for in-memory or other FT mechanisms) that the callback will be usable in a restart situation. I think that the check should be an actual `if(!valid(cb)) CkAbort()`, rather than `CkAssert`, since that path is not so performance sensitive to the cost of one if, and users may never run it with error checking enabled. Be sure to check for pointers in other types of `CkCallback` when writing the docs and safeguards.

I note that under some options, plain chares can be identified either by pointer (unconditionally so in `CkCallback`) or by `chareIdx` when the macro `CMK_CHARE_USE_PTR` is set to 0. If that index is persistent across restart (possible) and globally valid (not sure what happens to chares on a failed PE), then we could move to using that in `CkCallback` instead. It might imply a bit of a performance hit to code using many plain chares that interact heavily via callbacks, but I'm not sure how that weighs against an arbitrary restriction on fairly basic functionality like disk checkpointing. If we move plain chares to a global object ID scheme, then that ID would go in the callback instead of a pointer and this issue would be moot.

**Comment by heyram** [comment]
*Original date: 2013-04-17 21:06:22*

---
I am not completely knowledgeable about why CkChareID carries a ptr around. However,  our current perception of objid should be able to accommodate identifying and addressing free chares quite well. However, until we actually implement that, this task for additional checks / documentation is relevant and should proceed without waiting on objid_t.

**Comment by ericjbohm** [comment]
*Original date: 2013-05-03 19:28:20*

---
Please complete this before internship.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 02:00:56*

---
Xiang, can you do this in the next week, or should we reassign it to someone else?

**Comment by xiangni** [comment]
*Original date: 2013-06-04 05:50:25*

---
Sorry, I totally forgot about it. I will look at it tomorrow and estimate how much needs to be done. I will leave for travel this Saturday. If I cannot finish it in this week, please assign to someone else.

**Comment by xiangni** [comment]
*Original date: 2013-06-05 06:47:23*

---
The checkpoint and restart of plain chares are only handled properly for CkStartCheckpoint (not in double in-mem FT) when CMK_CHARE_USE_PT is set to 0 and the number of restart pes are same as before. That being said, the callback should always be valid if the checkpoint for plain chares are used properly. But I add the check of callback for safety.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-05 22:06:28*

---
How is `CMK_CHARE_USE_PTR` set on the various build configurations? When it's set to 1, we need to detect and error out on checkpoint callbacks that would aim at a plain chare.

**Comment by xiangni** [comment]
*Original date: 2013-06-05 22:17:23*

---
I just did a grep, CMK_CHARE_USE_PTR is set to 1 on various builds. CkStartCheckpoint does not checkpoint the data of plain chare when CMK_CHARE_USE_PTR is 1. If so, why would we use checkpoint with plain chare in such situation? Or are we expecting the user to reconstruct the plain chare?

**Comment by PhilMiller** [comment]
*Original date: 2013-06-05 22:23:01*

---
That's an additional degree of trouble that the application developer would have to face, but it's something they _can_ face. If they pass a plain chare callback containing a pointer to the checkpointing code, it's guaranteed to be broken, and we should detect _that_.

**Comment by xiangni** [comment]
*Original date: 2013-06-05 22:26:11*

---
OK, I will add the detection tonight.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-15 04:10:53*

---
It turns out other callback types than just those targeted at Chares contain pointers that may not be valid after recovery. I'm implementing the more comprehensive solution.

In the longer run, it'd be nice to move away from `CMK_CHARE_USE_PTR` entirely, so that something that one expects ought to work actually does.
