### ISSUE TITLE
Abort from AMPI RMA routines on derived datatypes

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1580]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1580*

---
We don't currently support these, and won't before the 6.8.0 release, so it would be good to add aborts to these routines to that effect before the 6.8.0 release.

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-13 18:00:14*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2600/~~ https://github.com/UIUC-PPL/charm/commit/45cb20a0421684cd5a1e3dea157c528187d0382c
