### ISSUE TITLE
AMPI_Get_accumulate is broken

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1581]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1581*

---
AMPI's implementation of MPI_Get_accumulate is completely wrong, and will always produce incorrect results at the target.

The control flow should look like:
1. Send the org buffer to the target (ie invoke a [sync] entry method, ampi::winRemoteGetAccumulate).
2. At the target, send back the contents of the targ buffer
3. At the target, accumulate the org buffer into the targ buffer
4. On the sender, recv back the original contents of the targ buffer, and copy them into the res buffer

**Comment by matthiasdiener** [comment]
*Original date: 2017-06-01 15:30:54*

---
Might be worth adding a test case in examples/ampi or tests/ampi .

**Comment by stwhite91** [comment]
*Original date: 2017-06-01 15:39:27*

---
That can be added to this: ~~https://charm.cs.illinois.edu/gerrit/#/c/2148/~~ https://github.com/UIUC-PPL/charm/commit/46d1e681239f3ee1f28ecad9217ea0224af4f1bc

**Comment by stwhite91** [comment]
*Original date: 2017-06-01 16:22:20*

---
Fix for Get_accumulate: ~~https://charm.cs.illinois.edu/gerrit/#/c/2574/~~ https://github.com/UIUC-PPL/charm/commit/a544a7dd72aebf3a23a2b5c5f6d64d33a9ce1bb8
