### ISSUE TITLE
Check commented old template documentation in doc/charm++/inhertmplt.tex against templates.tex

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1583]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1583*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2018-02-12 14:41:28*

---
This needs to be reassigned

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-22 18:26:32*

---
It appears that all the information contained in inhertmplt.tex but commented out was successfully migrated to templates.tex, where it has been maintained over time to e.g. not talk about AT&T Cfront and Borland C++.

Should I submit a patch to remove the commented out text from inhertmplt.tex?

**Comment by stwhite91** [comment]
*Original date: 2018-02-22 18:38:35*

---
Yes, that'd be good

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-22 18:39:46*

---
~~https://charm.cs.illinois.edu/gerrit/3763~~ https://github.com/UIUC-PPL/charm/commit/7c0547dd7ff1fb0c2d178f8fb36d5c11c06ccdf0
