### ISSUE TITLE
CmiCheckAffinity fails on large core counts with SMP

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1585]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1585*

---
Running ChaNGa on Blue Waters with 1024 nodes and affinity options of:

+ppn 15 +setcpuaffinity +pemap 1-15,17-31 +commap 0,16

I get:
ATP Stack walkback for Rank 649 starting:
  start_thread`pthread_create.c:301
  call_startfn`0x202c4bdd
  ConverseRunPE`0x202c4705
  _initCharm(int, char**)`0x201d3cc4
  CmiCheckAffinity`cpuaffinity.c:650
  LrtsNodeOf`cputopology.C:379
ATP Stack walkback for Rank 649 done
Process died with signal 11: 'Segmentation fault'

charm commit cd4d6f80b970ae702874a14404189f042e83478a

Going in with the debugger, I see:
#0  0x00000000202da1cc in LrtsNodeOf (pe=31369) at cputopology.C:379
#1  0x00000000202da27d in CmiPhysicalNodeID (pe=<optimized out>)
    at cputopology.C:629
#2  0x00000000202d9359 in CmiCheckAffinity () at cpuaffinity.c:650
#3  0x00000000201d3cc5 in _initCharm(int, char**) ()

Line 650 :      } else if ((CmiPhysicalNodeID(CmiMyPe()) == 0) && (CmiMyPe() < CmiNumPes())) {

CmiMyPe() is returning "31369".  This is larger than the total number of worker PEs (30*1024), but smaller than the total number of PEs (32*1024).  It appears that cpuTopo.nodeIDs[] in LrtsNodeOf() has only been initialized for the number of worker PEs.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-05 01:51:48*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2584/~~ https://github.com/UIUC-PPL/charm/commit/24b1ae017bbc44ee7ea4fdfb76c3091cfaf8ab53

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-05 01:56:47*

---
Yep, diagnosis is correct. CmiPhysicalNodeID can only be called for non-comm threads/pes. I had the order of conditionals wrong in the if statement. Fixed now.
