### ISSUE TITLE
FAQ : How do I use GPGPUs in Charm++?

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1588]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1588*

---
Add new question to FAQ

Provide capsule summary of options, refer to other documentation.

**Comment by stwhite91** [comment]
*Original date: 2017-07-28 12:32:45*

---
Bump, the release is expected to be out next week.

**Comment by mprobson** [comment]
*Original date: 2017-08-01 20:57:54*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2852/~~ https://github.com/UIUC-PPL/charm/commit/9a61cf234094f3879e7118eefdf008b0209fe50e
