### ISSUE TITLE
FAQ: how do I use Charm++ on Xeon Phi?

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1589]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1589*

---
Rephrase question if necessary to use whichever moniker for MIC is in vogue right now.

Add capsule summary, refer to other documentation.

**Comment by rbuch** [comment]
*Original date: 2017-06-20 20:43:41*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2712/~~ https://github.com/UIUC-PPL/charm/commit/aad82e21ac2094ba4409218922700104f83c4fbd
