### ISSUE TITLE
FAQ: 1 . 0 . 5 Does anybody actually use Charm++? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1590]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1590*

---
Freshen list.  Refer to Charm++ applications table in brochure.  Ref charmworks.

**Comment by stwhite91** [comment]
*Original date: 2017-07-06 22:43:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2718/~~ https://github.com/UIUC-PPL/charm/commit/af6e977a96e2c5f568db61297c7db56c32e44fa4
