### ISSUE TITLE
FAQ: 1 . 0 . 6 Who created Charm++? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1591]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1591*

---
update

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-23 03:35:59*

---
Patch: ~~https://charm.cs.illinois.edu/gerrit/#/c/2720/~~ https://github.com/UIUC-PPL/charm/commit/f361014bf02c88480c7383174be36f33e2f43e82
