### ISSUE TITLE
FAQ:  1 . 0 . 9 I have a suggestion/feature request/bug report. Who should I send it to? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1594]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1594*

---
update address to illinois

**Comment by rbuch** [comment]
*Original date: 2017-06-20 20:59:08*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2714/~~ https://github.com/UIUC-PPL/charm/commit/7c92bf21118bc1f56aff8174d18386a66beb7ce4
