### ISSUE TITLE
FAQ:  2 . 0 . 3 How do I compile Charm++? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1595]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1595*

---
update email address

**Comment by stwhite91** [comment]
*Original date: 2017-07-07 19:27:31*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2757/~~ https://github.com/UIUC-PPL/charm/commit/a7690842b6bd423ed8bfc3ea20de04ed2681d9f2
