### ISSUE TITLE
FAQ:  2 . 0 . 7 How do I specify the processors I want to use? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1596]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1596*

---
update for multcore and smp

**Comment by stwhite91** [comment]
*Original date: 2017-07-28 12:32:06*

---
Bump, the release is expected to be out next week.

**Comment by mprobson** [comment]
*Original date: 2017-08-01 20:20:55*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2850/~~ https://github.com/UIUC-PPL/charm/commit/7df7a010676883b798128f396ab384874d709c29
