### ISSUE TITLE
FAQ: 3 . 0 . 2 What is an ``entry method''? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1597]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1597*

---
Fix wonky quotes formatting in question.

**Comment by stwhite91** [comment]
*Original date: 2017-07-07 19:27:28*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2757/~~ https://github.com/UIUC-PPL/charm/commit/a7690842b6bd423ed8bfc3ea20de04ed2681d9f2
