### ISSUE TITLE
FAQ: 3 . 1 . 5 Can I do multiple reductions on an array? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1599]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1599*

---
Add reference to tuple reductions.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-19 20:04:41*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2709/~~ https://github.com/UIUC-PPL/charm/commit/8b8bb11eed0cc7c9ac396c7685191f6f15ee69c7
