### ISSUE TITLE
SDAG documentation of message API and CkSetRefNum

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#160]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/160*

---
CkSetRefNum and its utility in using SDAG with messages, instead of marshalled methods, is not documented in the manual.  Though it is used extensively in CharmLU.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-04 23:28:54*

---
Applied in changeset charm|commit:7fbaac1721584e0da3272534a9ba49ac829853b4.
