### ISSUE TITLE
FAQ: 3 . 1 . 6 Does Charm++ do automatic load balancing without the user asking for it? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1600]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1600*

---
Add reference to metalb and capsule summary of when why to use it.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-06-20 21:01:43*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2713/~~ https://github.com/UIUC-PPL/charm/commit/5790f24b6607dab66df8c62d9813c4562c716b28
Not adding Metabalancer strategy selection yet, since the corresponding patch will be merged after 6.8.0.
