### ISSUE TITLE
FAQ: 5 . 0 . 3 Can I use TotalView?  

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1602]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1602*

---
update

**Comment by stwhite91** [comment]
*Original date: 2017-07-28 12:33:27*

---
Bump, the release is expected to be out next week.

**Comment by stwhite91** [comment]
*Original date: 2017-08-07 13:44:04*

---
This and 1605 are the last open issues for 6.8.0

**Comment by PhilMiller** [comment]
*Original date: 2017-08-11 16:15:36*

---
~~https://charm.cs.illinois.edu/gerrit/2895~~ https://github.com/UIUC-PPL/charm/commit/d513ae95f62aa1f45441f4e934f9c8cbd152e7a3
