### ISSUE TITLE
FAQ:   5 . 0 . 4 How do I use gdb with Charm++ programs? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1603]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1603*

---
replace net with netlrts

**Comment by stwhite91** [comment]
*Original date: 2017-07-07 19:27:24*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2757/~~ https://github.com/UIUC-PPL/charm/commit/a7690842b6bd423ed8bfc3ea20de04ed2681d9f2
