### ISSUE TITLE
FAQ: 5 . 0 . 5 When I try to use the ++debug option I get: remote host not responding... connection closed 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1604]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1604*

---
Update to remove references to rsh and xhost.  Add newer options.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-06-20 21:25:32*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2715/~~ https://github.com/UIUC-PPL/charm/commit/04b4780c3a7fcd8c8eba2f81a4b1b7bd51fd26d5
