### ISSUE TITLE
FAQ:  6 . 0 . 8 Which C++ language features cause porting problems? 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1605]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1605*

---
update (e.g., note C++11 requirements for post 6.8)

**Comment by stwhite91** [comment]
*Original date: 2017-07-28 12:33:29*

---
Bump, the release is expected to be out next week.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-11 17:12:30*

---
~~https://charm.cs.illinois.edu/gerrit/2900~~ https://github.com/UIUC-PPL/charm/commit/441bd8d3759ec46098339e68521c1e807ed09754
