### ISSUE TITLE
SMP: Adapt to thread oversubscription, and provide flags to override

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#161]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/161*

---
The flag indicates the primary effect only in SMP builds. In multicore builds, for instance, when there are no com threads anyway, it is counter-intuitive to see this flag being recommended upon startup. The flag should be renamed to something that indicates its true purpose. The warning message at startup should also be updated to reflect this.

On Wed, Apr 3, 2013 at 6:45 PM, Gengbin Zheng wrote:
>
>
> The runtime option name and warning message  may need to be updated, but the
> same mechanism is still needed for multicore version, i.e. pthreads should
> do "sleep" wait instead of busy waiting.
>
> On Wed, Apr 3, 2013 at 5:11 PM, Venkataraman, Ramprasad wrote:
>>
>> Why am I getting this warning in multicore builds? I think it should
>> be disabled.
>>
>> Warning: the number of SMP threads is greater than the number of
>> physical cores, use +CmiNoProcForComThread runtime option
>>
>> I get this when I run in multicore mode with ++ppn greater than the
>> number of available cores.
>>

**Comment by PhilMiller** [comment]
*Original date: 2013-04-04 17:25:37*

---
If we're only going to warn on the thread to core oversubscription condition, then we should probably just automatically activate the appropriate adaptation. For instances where one wishes to control the sleep/spin choice explicitly, we can provide runtime flags to force one or the other behavior. In general, we know the right behavior to produce the best performance in the circumstance, so we should do it by default.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-12 19:10:32*

---
What produces a warning about `+CmiNoProcForComThread` now should automatically configure the runtime appropriately, and maybe print a warning about the oversubscription happening. There should be explicit override flags to force sleeping and spinning behaviors, and the existing flag should map to the sleep case.

**Comment by ericjbohm** [comment]
*Original date: 2013-05-03 19:27:05*

---
Please complete this before internship.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-05-04 03:46:42*

---
I checked in a fix. Ram, can you check whether that is what you want?

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 20:09:12*

---
commit:3723b6fd666544f810c1d2177773d558b547bd7c addressed part of this issue, but it's rather incomplete.
* There needs to be a flag to force the opposite behavior, of telling the runtime to act as if it's *not* over-subscribed. I suggest something like `+CmiSpinOnIdle`
* There needs to be a new flag with the same effect as `+CmiNoProcForComThread` with a complementary name as the above, such as `+CmiSleepOnIdle`

If neither of those is specified when threads oversubscribe cores, then we should still print a warning, even as we default to the sleeping behavior.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 20:09:48*

---
Yanhua: if this won't get done shortly due to your being on internship, please say so, and we will re-assign.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-05-31 04:27:25*

---
I am not quite sure what the problem is now and what is the bug.   If possible, can you assign to some one else after discussion?

**Comment by PhilMiller** [comment]
*Original date: 2013-05-31 04:45:37*

---
Here's the desired behavior:

A) By default, idle PEs should spin.

B) Two command line arguments, to let the user specify that PEs should either 
1. sleep when idle (as in current `_Cmi_noprocforcomthread = 1`), or 
1. spin when idle (i.e., `_Cmi_noprocforcomthread = 0`).

The name of these flags should not refer to comm threads, because the same settings apply to multicore builds as well.

C) If neither argument is provided, and Charm RTS threads oversubscribe available cores, 
1. print a warning that this is the case, and
1. set the appropriate flag for PEs to sleep when idle.

Prior to this bug, we had (A), (B)1, and (C)1. After commit:3723b6fd666544f810c1d2177773d558b547bd7c, we have (A), (B)1, and (C)2. Resolution would be to implement all  of A, B, and C.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 01:55:57*

---
Potential fix in branch `phil/oversubscription`, waiting for review comments.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-10 04:23:14*

---
I went through the changes, and they appear as required to me. But in general, I feel the need for a task to study the flags related to threads/SMP etc, have them documented, and possibly remove the ones that are superseded.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-10 21:46:57*

---
Mainline and stable branch change tested and pushed.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-18 22:46:48*

---
Initial fix made the argument checks only happen on `CmiMyRank() == 0`, which is problematic because every threads (worker or comm) gets it *own* copy of the argument list. Thus, all other threads had the relevant argument just left sitting around.
