### ISSUE TITLE
Document network dependent rdma thresholds, above which benefits of the zero copy API can be gained

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1611]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1611*

---
It's unclear to the user as to when the Zero Copy API should be used. So, it'll be good to document the buffer sizes for different networks to help the user choose between regular sending and zero copy sending appropriately.

**Comment by nitbhat** [comment]
*Original date: 2017-06-26 21:46:36*

---
Performance Evaluation before 6.8.0 release: https://docs.google.com/spreadsheets/d/1dL2AYO-kKZYGeM1PLDRX3k9z_uL95eDI7aU9qQjBZmo/edit?usp=sharing\

Current numbers for GNI and Verbs aren't great (around 2 MB mark). This will improve with upcoming rdma features like recv-side, registration api, dynamic decision to use regular send for small arrays etc. 

For now, documentation for 6.8.0 mentions that benefits from the zero copy api are mostly because of reduced memory footprint. 
Gerrit: ~~https://charm.cs.illinois.edu/gerrit/#/c/2734/~~ https://github.com/UIUC-PPL/charm/commit/a4b4d19fb9524fc3d960fc4b551a4d4a116738ff

**Comment by nitbhat** [comment]
*Original date: 2017-09-27 19:47:46*

---
Since the memory registration API and registration cache optimization hasn't been done for the Rdma Nocopy Entry method API and the performance numbers are still bad for gni and verbs, I think this ticket should be moved to a later version.

**Comment by nitbhat** [comment]
*Original date: 2017-10-06 23:11:08*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3100/~~ https://github.com/UIUC-PPL/charm/commit/daa9cad8082a0aeb155ee967e889aa6005748c26

This documentation exposed two bugs: https://charm.cs.illinois.edu/redmine/issues/1707 and  https://charm.cs.illinois.edu/redmine/issues/1708.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-11 19:40:01*

---
Not going to hold the 6.8.1 release for this.

**Comment by stwhite91** [comment]
*Original date: 2017-10-31 14:28:33*

---
I mistakenly thought this had been merged a while ago
