### ISSUE TITLE
Race condition during ckRestart causes hang after merging patch for bug #1576

### ISSUE THREAD

**Issue by juanjgalvez** [UIUC-PPL/charm#1616]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1616*

---
Bug is exposed by doing a CmiNodeAllBarrier after InitCPUTopology, which may be causing broadcast messages sent by PE0 in InitCPUTopology to overlap with restart messages.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-21 19:23:26*

---
This patch: ~~https://charm.cs.illinois.edu/gerrit/#/c/2723/~~ https://github.com/UIUC-PPL/charm/commit/e9191d90ba87d917ad9ed202d0be06ebc98ab553 may fix the issue.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-21 19:44:45*

---
Patch that might address the issue was already merged.

Prior to merging this patch, the issue so far had been observed to occur intermittently in netlrts SMP builds in test/charm++/chkpt.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-23 03:42:45*

---
I no longer see this bug in netlrts-linux-x86_64-smp after a sequence of many runs, while repeating the same sequence of runs without this patch the freeze eventually appears.

Still, we should pay attention to autobuild to make sure it doesn't appear in other cases.

autobuild on netlrts-win-x86_64-smp seems to still show this bug (after applying this patch). I haven't had success in trying to replicate it on Dexterity since I've been getting really weird behavior where even simple tests like `examples/charm++/hello/1darray` occasionally freeze.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-24 13:46:36*

---
Given that checkpoint-restart really doesn't get used on Windows (which is mostly for NAMD users at present), and there are apparently other sources of hangs there, I'm inclined to close this out.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-24 18:36:19*

---
Maybe it's been solved for Windows too but there are lingering issues from previous chkpt hangs? Maybe dexterity should be restarted.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-27 15:30:16*

---
On Jenkins Nightly-Build job, the hang in question still appears, and quite consistently.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-28 14:40:15*

---
Have been investigating and have much better understanding of what's going on.

In the original code (before implementing second reduction in cputopology), cputopology
does CmiReduce followed by broadcast from PE0 to all PEs. Adding CmiNodeAllBarrier right
after cputopology sometimes causes worker threads to reach CkRestartMain (and schedule bdcastR0)
before the commthread has sent the cputopology broadcast.
In this situation, initDone by worker threads in node 1 might be called before those
threads exit cputopology, causing a hang. initDone is called because they receive
bdcastRO from PE0 (which is processed before the broadcast from cputopology).

After this patch (~~https://charm.cs.illinois.edu/gerrit/#/c/2723/~~ https://github.com/UIUC-PPL/charm/commit/e9191d90ba87d917ad9ed202d0be06ebc98ab553), PE0 now waits for
other PEs to acknowledge reception of the cputopology broadcast before exiting cputopology.
This is implemented using a second CmiReduce. So, above issue should not occur anymore.

However, the new issue is that the second CmiReduce msg from node 1 is not sent to node 0.
This is because rank0 in node 1, when entering initDone via CkRestartMain, encounters a
CmiNodeBarrier. And CmiReduce doesn't progress if worker thread is stopped.


*Options I currently see to address this issue:*

- Instead of CmiReduce to notify PE0 that nodes have received cputopology broadcast,
do point-to-point CmiSend to PE0 (one send for each physical node).
Potential scalability concerns.
This is easy to implement and initial testing works and addresses issue.

- See if there is a way for CmiReduce to work even if worker thread is blocked, or
maybe implement CmiReduce with empty reducer that works this way. The second
CmiReduce in cputopology uses empty reducer.

- Don't call initDone from CkRestartMain and instead just wait for R0 broadcast from
PE0. I don't yet have a very thorough understanding of CkRestart to know if the
R0 broadcast will always be sent. And init.C mentions a potential race condition
that seems related to this case.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-28 14:53:06*

---
The all-to-PE0 p2p messages definitely won't be acceptable, because this is code that does run at large scale. It could potentially even crash machines like Blue Waters if we overload the network in the wrong way.

I would be inclined to try the option of dropping the initDone call from CkRestartMain, see if that clears things up here, and explicitly ask Tom to try that out with restart.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-28 14:58:36*

---
I agree that p2p sends is not the best option, although we are talking one message per physical node (not per PE or process). Also, that part of cputopology does not run on Blue Waters or BG/Q, so it wouldn't affect these machines.

I'll look at the other options.

**Comment by PhilMiller** [comment]
*Original date: 2017-06-28 15:02:19*

---
If that's the case about the p2p sends, it may be a perfectly acceptable option for the time being. I guess we just need to be sure that PE0 doesn't ever get blocked at a point where it won't process those messages. Non-BG/Cray systems don't generally reach the insane node counts where it would be a big deal, and per-node is much more acceptable than per-PE

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-28 20:24:25*

---
Actually, the option of doing p2p send for each physical node is probably not robust, and instead a message by each PE or process would be needed.

Instead, I have submitted a patch that allows the CmiReduce to work: ~~https://charm.cs.illinois.edu/gerrit/#/c/2735/~~ https://github.com/UIUC-PPL/charm/commit/6a393c85cd04e4f83bcc651d8253a853456efd3f
