### ISSUE TITLE
missing fences in CkLoop implementation

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1624]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1624*

---
Reported by Sameer Kumar, CkLoop reportFinished() needs a write fence to guarantee that results are visible to the thread that made a sync call to CkLoop (i.e., is waiting for results).  Also missing read fence in isFree().  waitLoopDone seems OK because of the locks.

**Comment by PhilMiller** [comment]
*Original date: 2017-07-03 21:02:52*

---
The group discussed this in core at some point. The code is apparently fine on x86 with its strict memory ordering semantics. Post 6.8, we'll switch to using native C++11 atomics to portably address these issues in full.

**Comment by jcphill** [comment]
*Original date: 2017-07-05 18:36:02*

---
Are CmiMemoryReadFence and CmiMemoryWriteFence somehow not portable and sufficient? Otherwise 6.8.0 CkLoop is broken on both Power and ARM.

**Comment by sbak5** [comment]
*Original date: 2017-11-30 22:21:36*

---
I think for PPC there are CmiMemoryWrite / CmiMemoryReadFences are inserted correctly. 
for x86, we're fine. 
So, not sure what the point of this issue is.

**Comment by jcphill** [comment]
*Original date: 2017-11-30 23:23:06*

---
The point is that Sameer sent a patch to fix this issue on POWER and I assume he knew what he was doing.

**Comment by sbak5** [comment]
*Original date: 2017-12-04 20:55:08*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3358/~~ https://github.com/UIUC-PPL/charm/commit/746d8478a9f7dc8ad5b3e26cce792d300863ef83

**Comment by sbak5** [comment]
*Original date: 2017-12-04 20:58:23*

---
For memory fences, we use CmiMemoryReadFence() which calls __sync_synchronize()
Maybe less costly fences for 'acquire' in relaxed consistency model are enough for CmiMemoryReadFence() to prevent reordering of loads/stores within the same thread. 

__atomic_thread_fence in gcc builtins with specific memory ordering can replace __sync_synchronize.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-06 17:26:28*

---
This is all C++ code, and we depend on C++11 now. We can use `std::atomic` fully.

**Comment by sbak5** [comment]
*Original date: 2017-12-06 17:38:48*

---
OK. I'll replace atomics with c++11 atomic codes.
