### ISSUE TITLE
Modify the keyword "rdma" to "nocopy"

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1626]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1626*

---
No body.

**Comment by nitbhat** [comment]
*Original date: 2017-07-06 16:49:57*

---
As the Zero Copy API supports within process transfers and non-RDMA layers, it was decided over a slack discussion on #lrts that it was more apt to have the charmxi keyword as "nocopy" instead of "rdma"

**Comment by nitbhat** [comment]
*Original date: 2017-07-06 20:48:17*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2754/~~ https://github.com/UIUC-PPL/charm/commit/cbf50e50b8c4f566c7763248c12a60df94ead1b2

**Comment by stwhite91** [comment]
*Original date: 2017-07-11 19:34:11*

---
Changed "rdma" .ci file keyword to "nocopy" and the "rdma()" send wrapper routine to "CkSendBuffer()".
