### ISSUE TITLE
Error while compiling LogAnalyzer tool in BigNetSim

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1628]
*Original author: Ashmita Raju*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1628*

---
Hello,

I am trying to convert the trace logs produced by the BigSim Emulator to be able to analyze them and find a computation communication graph for my program.
To do this I am trying to use the LogAnalyzer tool under BigNetSim. While running I get the following error.

ashmita`amd1:~/charm/charm-6.7.1/charm-6.7.1/BigNetSim/trunk/tools/LogAnalyzer$ make

test -d ../../tmp || mkdir ../../tmp
/storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/net-linux-x86_64/bin/charmc -I/storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/net-linux-x86_64/include/pose -g   -lz  -seq -o ../../tmp/LogAnalyzer LogAnalyzer.o -lconv-bigsim-logs -lconv-util -lblue-standalone -language c++
/storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/net-linux-x86_64/bin/../lib/libconv-util.a(pup_util.o): In function `CmiFwrite':
pup_util.C:(.text+0x906): undefined reference to `CmiWallTimer'
pup_util.C:(.text+0x973): undefined reference to `CmiWallTimer'
pup_util.C:(.text+0x991): undefined reference to `CmiWallTimer'
/storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/net-linux-x86_64/bin/../lib/libconv-bigsim-logs.a(bigsim_api.o): In function `BgWriteTimelines(int, BgTimeLineRec**, int, char*)':
bigsim_api.C:(.text+0x8be): undefined reference to `_Cmi_mype'
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/BigNetSim/trunk/tools/LogAnalyzer
   Command g++ -m64 -m64 -fPIC -g -o ../../tmp/LogAnalyzer LogAnalyzer.o -L/storage/others/ashmita/charm/charm-6.7.1/charm-6.7.1/net-linux-x86_64/bin/../lib -lz -lconv-bigsim-logs -lconv-util -lblue-standalone returned error code 1
charmc exiting...
make: *** [LogAnalyzer] Error 1

Can you please tell me what I am doing wrong?

Thank you

**Comment by stwhite91** [comment]
*Original date: 2017-12-13 18:30:40*

---
Does this same error happen on the current development branch (named 'charm'), rather than v6.7.1 which is a couple years old at this point?

**Comment by matthiasdiener** [comment]
Bigsim has been removed in #2703.
