### ISSUE TITLE
ST_RecursivePartition (spanning tree) crashes during init with large node counts on systems without topo info

### ISSUE THREAD

**Issue by juanjgalvez** [UIUC-PPL/charm#1632]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1632*

---
As documented by Eric B:
"Edison dies with a topology error at higher node counts. Unclear if this is actually a related bug, or a different issue. 32 nodes works, 45 nodes crashes thusly:
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: ST_RecursivePartition:: Increase bitset size to match size of largest topology dimension
------------- Processor 8 Exiting: Called CmiAbort ------------
Reason: ST_RecursivePartition:: Increase bitset size to match size of largest topology dimension
... etc"

**Comment by juanjgalvez** [comment]
*Original date: 2017-07-14 18:28:14*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2789/~~ https://github.com/UIUC-PPL/charm/commit/58f6f16077535e24f5c474cc1ee7ea8aaa059bb2

**Comment by ericjbohm** [comment]
*Original date: 2017-07-14 19:32:22*

---
patch tested and found to address the issue correctly for large (>32node) openatom runs on edison.
