### ISSUE TITLE
Zero-copy send support in the OFI layer

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1637]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1637*

---
Perhaps Intel can be talked into implementing the necessary support for the new OFI layer? Otherwise we'll need to do it.

**Comment by nitbhat** [comment]
*Original date: 2017-10-11 02:46:10*

---
Gerrit Link: ~~https://charm.cs.illinois.edu/gerrit/#/c/3122/~~ https://github.com/UIUC-PPL/charm/commit/70162088f8d492805c9f839c9999506a14bb2e4a
