### ISSUE TITLE
Repeated typo: Destory -> Destroy

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#164]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/164*

---
The word 'destroy' is misspelled as 'destory' in several places in the codebase. I'm fixing some of them, but leaving others for the moment to avoid conflict with other ongoing work.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-05 17:37:39*

---
Fixed the instances in persistent in commit:eed4862. Leaving `net/machine.c` and `arch/util/machine-smp.c` until #163 is fixed, and `ckmemcheckpoint.C` until other work on it (replica_ft, etc) gets merged.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 21:21:04*

---
The machine layer instances were fixed in code but not comments with the net-lrts work, so I've fixed the comments too and cut the blockage on other machine-layer changes. Still want the `ckmemcheckpoint.C` fixes, too.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:34:02*

---
Once the outstanding branches that heavily modify `ckmemcheckpoint.C` get integrated, these typos should be fixed.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:55:39*

---
A grep on src yield 0 such instances.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-29 03:03:44*

---

```
$ git grep -i -n destory
src/ck-core/ckmemcheckpoint.C:828:class ElementDestoryer : public CkLocIterator {
src/ck-core/ckmemcheckpoint.C:832:        ElementDestoryer(CkLocMgr* mgr_):locMgr(mgr_){};
src/ck-core/ckmemcheckpoint.C:868:// destory all array elements
src/ck-core/ckmemcheckpoint.C:921:  // including destorying all array elements
src/ck-core/ckmemcheckpoint.C:927://  CKLOCMGR_LOOP(ElementDestoryer chk(mgr); mgr->iterate(chk););
src/ck-core/ckmemcheckpoint.C:963:  // cannot be CkMemCheckPT::restart because destory will modify states
```

This hasn't been fixed.

**Comment by PhilMiller** [comment]
*Original date: 2016-04-14 19:41:47*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1107/~~ https://github.com/UIUC-PPL/charm/commit/8efeeb6fd8986ae8acc6999c580666992fc1c6b4
