### ISSUE TITLE
charmrun with nodelist option (++nodelist) fails on campus cluster

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1641]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1641*

---
[nbhat4`golub162 pingpong]$ ~/gennodelist.sh > ./nodelist && ./charmrun +p2 ++nodelist ./nodelist ./pgm
Charmrun> scalable start enabled.
Charmrun> IBVERBS version of charmrun
Charmrun> Error 255 returned from remote shell (golub162:0)
Charmrun> Reconnection attempt 1 of 3
Charmrun> Error 255 returned from remote shell (golub161:1)
Charmrun> Reconnection attempt 1 of 3
Charmrun> Error 255 returned from remote shell (golub162:0)
Charmrun> Reconnection attempt 2 of 3
Charmrun> Error 255 returned from remote shell (golub161:1)
Charmrun> Reconnection attempt 2 of 3
Charmrun> Error 255 returned from remote shell (golub162:0)
Charmrun> Reconnection attempt 3 of 3
Charmrun> Error 255 returned from remote shell (golub161:1)
Charmrun> Reconnection attempt 3 of 3
Charmrun> Error 255 returned from remote shell (golub162:0)
Charmrun> Too many reconnection attempts; bailing out

This is a recent issue, I remember it working fine a couple of months back. I think this is an issue with Golub/Taub, as ++nodelist works fine with lab machines. 

The alternative solution is to launch jobs with ++mpiexec. I think this bug resolution should at least document about ++mpiexec as an alternative way of launching the job (and probably document the connection failure on Golub/Taub as a known issue).

**Comment by evan-charmworks** [comment]
*Original date: 2017-10-11 20:45:45*

---
Would it be possible to grant me access to Golub/Taub so I can test this directly?

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-19 19:38:20*

---
All this error means is that the ssh connection cannot be established. I don't have access to these machines to specifically test but I don't believe this is Charmrun's problem beyond _maybe_ not being clear enough with the error message.
