### ISSUE TITLE
Review Standalone Build/Directives for  GPU Manager Documentation 

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#1645]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1645*

---
As fixed here: ~~https://charm.cs.illinois.edu/gerrit/#/c/2838/~~ https://github.com/UIUC-PPL/charm/commit/6a25c7b1d58213285c9617861dec274332158891, the stand alone checks for the GPU Manager were messing up the build of the library documentation (specifically the preceding section, TRAM).  These checks should be reviewed and reintroduced in the correct way if they're useful.

**Comment by mprobson** [comment]
*Original date: 2017-08-01 21:26:20*

---
I don't think they're useful, they were left over from when I was initially writing the manual and wanted to just look at that one section.
