### ISSUE TITLE
Support use of std::array in .ci files

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1646]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1646*

---
Use of std::array in .ci files conflicts with the .ci keyword 'array'.

**Comment by stwhite91** [comment]
*Original date: 2018-01-17 17:56:55*

---
I think Spectre wants this added? If so, it should be prioritized for 6.9.0

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-17 20:41:44*

---
~~https://charm.cs.illinois.edu/gerrit/3525~~ https://github.com/UIUC-PPL/charm/commit/13df1a1ade0303cfacc3fe5531506968a0763890
