### ISSUE TITLE
NullLB shouldn't wait for LB period

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1649]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1649*

---
Currently NullLB respects the LBPeriod. This means that if your application is calling AtSync more frequently than the LBPeriod, you get long delays in some of those calls even if you aren't running with a real load balancer.

**Comment by kavithachandrasekar** [comment]
*Original date: 2017-08-04 18:44:29*

---
Discussed this issue, Juan suggested one solution could be that we call ResumeFromSync from CkMigratable::AtSync when no LB is created.

**Comment by stwhite91** [comment]
*Original date: 2017-08-04 19:26:46*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2868/~~ https://github.com/UIUC-PPL/charm/commit/b969b03d5bcb36caa0194ce24c18a30e976d1297
