### ISSUE TITLE
CkArray::ckDestroy() does not delete CkMulticastMgr

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1652]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1652*

---
I think this is the fundamental cause of bug #1647 but I'm resubmitting to give it a more accurate name.

ckNew() creates groups for CkLocMgr, CkMulticastMgr, and CkReductionMgr, but ckDestroy() only deletes CkLocMgr and CkReductionMgr.  This is a memory leak of groups, but I think it is the origin of crashes when the groupTable gets written out for a checkpoint with those "dangling" CkMultcastMgr entries.

Demonstrate by: putting CkPrintf()s in CkCreateLocalGroup and IrrGroup::~IrrGroup() and note that you only get 2 deletions for every 3 group creations when doing a ckNew() followed by a ckDestroy().  Also if you put
  IrrGroup *oldObj = CkpvAccess(_groupTable)->find(groupID).getObj();
  CkAssert(oldObj == NULL);
at the top of CkCreateLocalGroup(), ChaNGa will crash after a few checkpoint/restarts and using CkIO (the restart target in changa/teststep).

**Comment by trquinn** [comment]
*Original date: 2017-08-05 14:57:53*

---
A proposed fix:
~~https://charm.cs.illinois.edu/gerrit/2871~~ https://github.com/UIUC-PPL/charm/commit/7d324fd101a01ad521aa6d4abc8b398e018906ab

**Comment by stwhite91** [comment]
*Original date: 2017-08-08 20:40:51*

---
We'll merge this into 6.8.0
