### ISSUE TITLE
Update manual entries on Load Balancing strategies

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1656]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1656*

---
The section describing the built-in strategies should be more descriptive of the trade-offs in strategies and should try to guide users to strategies we think are useful. When should you use a Comm-aware LB or a distributed LB or a hybrid LB? What are the differences between the Comm-aware LBs? When should you use RandCentLB or RotateLB?

**Comment by stwhite91** [comment]
*Original date: 2018-03-28 01:19:54*

---
This would be good to have for 6.9.0

**Comment by stwhite91** [comment]
*Original date: 2018-05-02 05:10:05*

---
Bump

**Comment by kavithachandrasekar** [comment]
*Original date: 2018-11-08 20:07:34*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4794/~~ https://github.com/UIUC-PPL/charm/commit/9d4699f5d295e027c023292592502c8ffd612d5f
