### ISSUE TITLE
Premature detection of Quiescence when TRAM is being used

### ISSUE THREAD

**Issue by lvkale** [UIUC-PPL/charm#1658]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1658*

---
This was identified in Charm++ version of Quicksilver by Karthik and Nikhil, in an LLNL internship project. There are multiple "aggregate" TRAM entry methods and non-aggregate regular entry methods executing during the time the problem arises.  It is non-deterministic. Justin and Sanjay wrote a test program (in late July) that also non-deterministically reproduce the problem.  Phil may have additional comments, since he was looking at it too.

**Comment by lvkale** [comment]
*Original date: 2017-08-12 19:45:53*

---
The bug is (I am reasonably sure) due to faulty quiescence detection algorithm in qd.C. It employees 2 phases. Once the counts of created and processed message (summed up via a converse custom reduction) are equal, it does one more round to confirm nothing has changed (which is a normal possibility.. since there may be 2 messages m1 and m2 such that only m1's creation and m2's processing have been counted. ). It uses a notion of "dirty" on each processor to track if something has changed is in 
qd.h L121	    int isDirty(void) { return ((mProcessed > oProcessed) || cDirty); }
oProcessed is the number of messages processed at the previous pass (o for old) of the algorithm. Note that it is not tracking oCreated in a similar manner. And that is the bug. If a message is created, remains stuck in TRAM (NDMeshStreamer) buffer awaiting timeout, the system won't detect any issue, under a narrow sliver of situations. 
One could fix this by tracking oCreated, but its much better to fix the algorithm to solely rely on counts (and idleness).

**Comment by lvkale** [comment]
*Original date: 2017-08-12 19:50:03*

---
A simple test program I wrote (after fixing the bug) demonstrates the problem consistently. Its a variation on hello, with 2 methods, one aggregated and one not. Each works like a chain. It fails most of the time with the current QD and succeeds with the fix. (Fix coming up in the next log).

**Comment by lvkale** [comment]
*Original date: 2017-08-12 19:56:14*

---
The patch that fixes it is attached. I suggest, after due scrutiny and testing, we merge this, so that users have a bug-fixed version. But after that, we should cleanup the code to remove the second "check dirty-ness only" phase, and any relevant code. 

The fix is basically to maintain the global count (created and processed.. same count) from the last time they were equal. Next time they are equal, they also need to be equal to this saved count, for us to declare quiescence. This is the original algorithm of our QD paper in 1993. I  don't know who changed it to make it track "dirty" and why.  For now, I have retained the dirty-tracking phase at the end, to get a bug-fix out expeditiously. 

Will someone volunteer to test the patch, and move it thru the gerrit review?

**Comment by PhilMiller** [comment]
*Original date: 2017-08-12 21:27:22*

---
Confirmed that the attached test code fails consistently on netlrts-darwin-x86_64, with 2 PEs running on a single host with pre-patch code.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-12 21:48:37*

---
~~https://charm.cs.illinois.edu/gerrit/2907~~ https://github.com/UIUC-PPL/charm/commit/54b77a75cdbb762b1d771ba095ad84b5f28f2f96

**Comment by PhilMiller** [comment]
*Original date: 2017-08-12 21:49:20*

---
Confirmed that the patch fixes the test, even when modified to run itself in multiple iterations in a single job.
