### ISSUE TITLE
AMPI tests /tests/migration and tests/megaampi fail on Stampede2 with MPI and OFI build

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1660]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1660*

---
The tests - tests/migration and tests/megampi fail when run on two processors on Stampede2 with the build mpi-linux-x86_64.

To reproduce: 
1. Build AMPI: ./build AMPI mpi-linux-x86_64 -j10 -O0 -g
2. Request a development job : idev -t 00:30:00 -N 1 -n 2
3. Inside tests/ampi/migration, run ibrun ./pgm +p2 +vp4

Similarly for tests/ampi/megampi. 

I couldn't get the stacktrace from the produced core dump as I'm getting warnings for missing debug-info (in spite of compiling with -g -O0). 

These errors can be reproduced on the ofi build too.

**Comment by stwhite91** [comment]
*Original date: 2017-11-08 18:54:33*

---
You just need to add '+isomalloc_sync' on Stampede2 and it works on OFI and MPI, non-SMP and SMP. A warning is printed out when you don't use '+isomalloc_sync' so I am just marking this 'rejected'.
