### ISSUE TITLE
Building charm with papi support is successful even when papi is not found (-lpapi)

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1661]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1661*

---
When I try to build charm with papi support like 
```
 ./build charm++ mpi-linux-x86_64 papi --with-production -j16 
```
 the compilation is successful, even when -lpapi is not found. (and papi is not found in the environment). I see the message - checking "whether PAPI exists"... "no" shown by configure, but configure goes through without complaining. 

We should have configure abort the process with an appropriate error message about not finding papi.

**Comment by stwhite91** [comment]
*Original date: 2017-08-22 16:00:42*

---
Also add an abort when building papi without --enable-tracing, and update the PAPI Projections documentation.

**Comment by stwhite91** [comment]
*Original date: 2017-09-01 19:01:33*

---
Assigning to Ronak b/c tracing...

**Comment by rbuch** [comment]
*Original date: 2017-09-18 21:42:36*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3033/~~ https://github.com/UIUC-PPL/charm/commit/f78d53bfec0468fcc4567dcfebfa9742adbe6e3c
