### ISSUE TITLE
Direct API for nocopy operations on sender-side and receiver-side

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1667]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1667*

---
Since the receiver side API (https://charm.cs.illinois.edu/redmine/issues/1236) has restrictions which demand the user to name a generated entry method in a specific manner in order to overload the generated method, it will be a worthwhile effort to have an alternative API which is more direct as compared to entry method overloading and gives user the control to perform GET/PUT calls directly.

**Comment by nitbhat** [comment]
*Original date: 2017-08-29 20:45:06*

---
Initial commit: ~~https://charm.cs.illinois.edu/gerrit/#/c/2967/~~ https://github.com/UIUC-PPL/charm/commit/504bc22b81afa75788cb0e38974f0268e52ecec0

**Comment by stwhite91** [comment]
*Original date: 2017-08-29 21:32:32*

---
We may want to avoid calling this "direct" since there is already something else called CmiDirect. I think in general the recv-side stuff is the completion of the Zero Copy API, but the fact that we will eventually have 2 APIs for the recv-side stuff will make it a bit confusing (I think of this API as the lower-level one, and the RdmaPost one as the higher-level abstraction).

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 21:48:34*

---
If the generic layer gets done, possibly even with a hacky implementation that only really provides one of GET or PUT and uses that for the other, then we can implement the other layers piecemeal after the basic thing is integrated.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 21:49:29*

---
And similarly, that one-of-GET-or-PUT design can get us up and running on the other layers quickly, though, with an extra round trip, and then be optimized later.

**Comment by nitbhat** [comment]
*Original date: 2018-04-04 19:26:04*

---
Except for documentation for the Direct API, which is targeted for 6.9, all the other tasks are for later releases.

**Comment by nitbhat** [comment]
*Original date: 2018-09-20 18:28:46*

---
Netlrts will not have a true "zero copy" implementation, it'll use the generic copy based implementation.

**Comment by stwhite91** [comment]
*Original date: 2018-09-20 18:33:02*

---
We could potentially use sendmsg and WSASend on netlrts-tcp as Juan did here, though I don't think it should be a priority right now:

~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4357/~~ https://github.com/UIUC-PPL/charm/commit/4af1d868a045935c5401856e47df919b0cd5ce95
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4535/~~ https://github.com/UIUC-PPL/charm/commit/6c657aa5121990a40f56d7cd963f6924ab487c18
