### ISSUE TITLE
Ensure that all libraries/modules will build as dynamic/shared objects (.so/.dylib vs .a)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1668]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1668*

---
>  `./build LIBS netlrts-darwin-x86_64 --build-shared --suffix=shared -j2 -g`

```
$ ls netlrts-darwin-x86_64-shared/lib{,_so} | grep -v '.dep$' | sort | cut -d. -f1 | uniq -c | sort -n | grep 1 | grep -v /
   1 libampiromio
   1 libirecv
   1 libmoduleCkSparseContiguousReducer
   1 libmodulesearchEngine
   1 libmodulesearchEngine_bound
   1 libqt
   1 libhwloc_embedded
```
Something is screwy in the build process of these library objects that leaves them without a .so/.dylib built, where every other library has one. The most concerning to me are libqt and libampiromio.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 17:19:50*

---
So, it turns out that libqt is wrong in the opposite direction - libqt.a gets built, but doesn't get copied to the lib directory, while libqt.dylib (on my mac) gets copied to `lib_so`

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 17:23:28*

---
A further amendment to that statement - libqt.a is missing because it's only copied as 
> `cp libqt.a ../lib/libckqt.a`

Note the change in name from libqt to libckqt. The dynamic version libqt.dylib is copied as both libqt and libckqt. This is a little weird.

**Comment by matthiasdiener** [comment]
*Original date: 2017-08-29 17:25:04*

---
ROMIO is currently not able to be built dynamically. Bug #952 tracks an update for ROMIO which should make it easier to enable creating a shared romio library.

**Comment by matthiasdiener** [comment]
*Original date: 2017-08-29 17:27:01*

---
Can we merge lib/ and lib_so/ ? I think this separation is not necessary, as shared and static libraries have different file extensions. Normal Linux systems have *.so and *.a in /usr/lib/, for example.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 17:29:11*

---
Merging the two directories would be a separate issue - this is just about whether both static and dynamic objects get built and installed at all.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 17:47:19*

---
remote:   ~~https://charm.cs.illinois.edu/gerrit/2962~~ https://github.com/UIUC-PPL/charm/commit/99be1b42af0c84c7dfa33e341a091934a7942c93 Bug #1668 irecv Makefile: enable charmc's automatic generation of dynamic ...
remote:   ~~https://charm.cs.illinois.edu/gerrit/2963~~ https://github.com/UIUC-PPL/charm/commit/e438e1bbbe8968ada289524220f8d31b902d8a8f Bug #1668 Makefile: Don't copy libqt.a under an unused name
remote:   ~~https://charm.cs.illinois.edu/gerrit/2964~~ https://github.com/UIUC-PPL/charm/commit/8e6cae158e5d72885f0782d60a9339e320570ba7 Bug #1668 state_space_searchengine: Ensure dynamic libraries get built when ...
remote:   ~~https://charm.cs.illinois.edu/gerrit/2965~~ https://github.com/UIUC-PPL/charm/commit/680439a4aeee0e2ae9cf66da99ac67afd91a249f Bug #1668 sparseContiguousReducer: Ensure dynamic libraries get built when ...

AMPI's ROMIO will have to happen with the version update mentioned. I'll add a note over there.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-29 18:56:52*

---
Ok, I see why we don't merge the two directories - when linking under control of `charmc`, it addresses user requests for static or dynamic linking of the finished binary by only passing one path or the other to the underlying linker. This means that even if the underlying tool is stupid about respecting the user's preference, we guarantee that it will only see the desired variant of the RTS objects.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-26 18:49:08*

---
Looks like our hwloc also needs to have shared object compilation enabled. It's missing, probably because it doesn't ultimately use charmc to assemble its .a, which would implicitly generate the .so/.dylib/.dll as well.

**Comment by stwhite91** [comment]
*Original date: 2017-10-26 19:00:59*

---
libampiromio is only built statically because the version of ROMIO we have doesn't support shared builds.
I believe this commit would get us that, but it isn't working yet. Matthias may have more details on it: https://charm.cs.illinois.edu/gerrit/#/c/2940/

Edit: the above comments confirm this.

**Comment by matthiasdiener** [comment]
*Original date: 2017-10-27 15:13:14*

---
Yeah, there is no update regarding romio yet.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-27 22:22:44*

---
charmc wants to reference hwloc when linking a shared object for QuickThreads. hwloc doesn't build a corresponding shared object by default, and adding `enable_shared='yes'` in configure.ac isn't enough to do it. More investigation to follow.

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-18 23:45:09*

---
hwloc will build a shared object with ~~https://charm.cs.illinois.edu/gerrit/3450~~ https://github.com/UIUC-PPL/charm/commit/563f43ac9e077ac2fd2682804e437e30db376739

**Comment by stwhite91** [comment]
*Original date: 2017-12-19 21:35:06*

---
All of the above changes have been merged, so the only remaining issue here should be ROMIO.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-26 17:48:37*

---
QuickThreads is also still kinda messed up, at least on Mac builds

**Comment by PhilMiller** [comment]
*Original date: 2017-12-26 18:08:18*

---
hwloc builds a dynamic library, but it's not presently usable on Mac. I needed to uncomment the `cp` command in `src/scripts/Makefile` to actually get it in `lib_so/`, copied over the `libhwloc_embedded.0.dylib` file that it referenced as well, and I still get the following:

```
$ pwd
/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/tests/charm++/simplearrayhello

$ otool -L hello
hello:
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libckmain.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libck.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libmemory-default.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libthreads-default.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libconv-machine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libconv-core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libtmgr.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libconv-util.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libconv-partition.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libhwloc_embedded.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libldb-rand.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libconv-ldb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/tmp/QuickThreads/libckqt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libmoduleNDMeshStreamer.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/lib_so/libmodulecompletion.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)

$ ./hello
dyld: Library not loaded: /usr/local/lib/libhwloc_embedded.0.dylib
  Referenced from: /Users/phil/PPL/charm/netlrts-darwin-x86_64-v6.8.2-208-gf71a444/tests/charm++/simplearrayhello/./hello
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-27 22:06:34*

---
With ~~https://charm.cs.illinois.edu/gerrit/3469~~ https://github.com/UIUC-PPL/charm/commit/31a0c1a9b35d9ee03e0aa46a0c0a5530d06399f4 I get:


```
$ pwd
/Users/evan/charm/netlrts-darwin-x86_64/tests/charm++/simplearrayhello

$ otool -L hello
hello:
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libckmain.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libck.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libmemory-default.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libthreads-default.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libconv-machine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libconv-core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libtmgr.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libconv-util.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libconv-partition.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libhwloc_embedded.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libldb-rand.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libconv-ldb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libckqt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libmoduleNDMeshStreamer.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/evan/charm/netlrts-darwin-x86_64/lib_so/libmodulecompletion.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)

$ ./hello
Charm++: standalone mode (not using charmrun)
Charm++> Running in non-SMP mode: numPes 1
Converse/Charm++ Commit ID: v6.8.2-211-gfa0e46341
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 1 processors for 5 elements
[0] Hello 0 created
[0] Hello 1 created
[0] Hello 2 created
[0] Hello 3 created
[0] Hello 4 created
[0] Hi[17] from element 0
[0] Hi[18] from element 1
[0] Hi[19] from element 2
[0] Hi[20] from element 3
[0] Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```

**Comment by matthiasdiener** [comment]
*Original date: 2017-12-28 02:47:28*

---
The ROMIO issue mentioned above is not solved yet, so AMPI applications still require at least the static ROMIO library. I'll address this in early January.

**Comment by stwhite91** [comment]
*Original date: 2018-01-12 18:38:15*

---
This enables shared builds of ROMIO: ~~https://charm.cs.illinois.edu/gerrit/#/c/3499/~~ https://github.com/UIUC-PPL/charm/commit/c116db4795f587233841287ff2817f600daa296d

I think this issue can be closed now?

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-12 22:46:53*

---
I tried the build and grep commands in the issue description and no items were listed. I agree that it is complete.
