### ISSUE TITLE
Add machine layer files as Makefile dependencies for building the machine layer library

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1669]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1669*

---
There are no existing Makefile dependencies for the pamilrts layer. Similarly, the gni layer doesn't have a few dependencies like machine-onesided.c and machine-onesided.h. Additionally, it should be ensured that all include files used in machine-common-core.c should be also added as dependencies. Atleast for all lrts layers, it'll be good to do a check that all makefile dependencies are added.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-28 17:26:13*

---
Could this be addressed by running something equivalent to the current `make depends` and putting the output directly in `Makefile.machine` or in a `Make.depends.machine` file that we can include?

**Comment by PhilMiller** [comment]
*Original date: 2017-12-11 22:43:01*

---
Teach make to automate this:
~~https://charm.cs.illinois.edu/gerrit/3400~~ https://github.com/UIUC-PPL/charm/commit/8374ad28287f7d7b4f14530be9653f60426a5b1c

**Comment by PhilMiller** [comment]
*Original date: 2017-12-17 16:20:27*

---
Follow-up fix for Windows builds here: ~~https://charm.cs.illinois.edu/gerrit/3442~~ https://github.com/UIUC-PPL/charm/commit/f386bba3e65b4ba8e0ef5a5ea0105a32a07ff226

Incidentally, this would (I think) let us move away from a pre-generated, committed `Make.depends`, and just have it all happen at build time automatically.
