### ISSUE TITLE
Migration of Taskqueue from Ck to Converse layer

### ISSUE THREAD

**Issue by sbak5** [UIUC-PPL/charm#1670]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1670*

---
The task queue is currently implemented in ck-core even though it doesn't use any constructs on ck-layer. 
Taskqueue is one of queues in converse and it should be able to be used independently by any programming framework based on Converse such as converse-based OpenMP and AMPI.

**Comment by stwhite91** [comment]
*Original date: 2018-01-05 00:21:36*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2988/~~ https://github.com/UIUC-PPL/charm/commit/bad107175ce3eee53f5b125259277f069bb6d449

**Comment by jcphill** [comment]
*Original date: 2018-01-16 18:08:43*

---
As noted in Gerrit, this broke Windows builds.
