### ISSUE TITLE
LLDB support for charmrun ++debug

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1672]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1672*

---
Since gdb support on the latest macOs is minimal and has issues related to codesigning, it'll be good to have lldb support for charmrun. Separately, it'll be a useful debugging feature and can benefit mac users who use lldb for debugging.

**Comment by stwhite91** [comment]
*Original date: 2018-06-25 19:18:21*

---
This seems to just work now if I replace 'arg_debugger = "gdb"' in charmrun.C with 'arg_debugger = "lldb"' and then run with both "++debug" and "++local". We should make lldb the default on Mac, and maybe make adding "++local" unnecessary when running with "++debug".

**Comment by evan-charmworks** [comment]
*Original date: 2018-06-27 20:48:58*

---
~~https://charm.cs.illinois.edu/gerrit/4317~~ https://github.com/UIUC-PPL/charm/commit/1f59ccd88a71075fcd426de443270d525a153965
