### ISSUE TITLE
Add 'ofi' target to autobuild

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1674]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1674*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2017-09-13 19:42:57*

---
ofi builds could be added on the same target machine (campus cluster) as verbs, so assigning to Jaemin.

**Comment by stwhite91** [comment]
*Original date: 2017-09-13 19:46:25*

---
Bridges at PSC would be an ideal candidate for autobuild, if we can set it up to run without 2-factor authentication.

**Comment by jcphill** [comment]
*Original date: 2017-09-14 03:31:28*

---
Bridges doesn't use 2-factor authentication.

**Comment by stwhite91** [comment]
*Original date: 2017-11-01 14:22:18*

---
Is there a problem with ofi on golub? This needs to get done

**Comment by stwhite91** [comment]
*Original date: 2017-11-06 14:57:59*

---
Bump. Any reason to not add this on golub?

**Comment by minitu** [comment]
*Original date: 2017-11-06 17:57:10*

---
I've been working on getting it running on golub, but there is an issue with using ++mpiexec, where if you set ppn in qsub larger than the total number of PEs used in a test program it uses only a single physical node. This is problematic with SMP buidls, and it affects the verbs autobuilds as well. I've found a workaround by setting ppn to 1 in qsub and create a nodelist out of PBS_NODEFILE and using that, so I'll go forward with it.

**Comment by stwhite91** [comment]
*Original date: 2017-11-08 20:48:10*

---
We want this to be on Bridges since that has an Omni-Path interconnect and we know OFI works there. We need to ensure we have enough allocation to run autobuild on it.

**Comment by stwhite91** [comment]
*Original date: 2017-12-11 23:21:29*

---
Bump, this needs to get done

**Comment by minitu** [comment]
*Original date: 2017-12-13 21:41:19*

---
I don't have allocation anymore on Bridges, but Karthik does.
We'll try using his account to set up autobuild there.

**Comment by stwhite91** [comment]
*Original date: 2018-01-10 20:46:39*

---
Autobuild for OFI is not passing yet. I don't even think it has actually gotten to building charm yet. Here's last night's run's failure:

```
./instead_test.sh: line 15: cd: charm/ofi-linux-x86_64/tmp: No such file or directory

```

**Comment by stwhite91** [comment]
*Original date: 2018-01-18 00:33:49*

---
Last night autobuild was able to log onto Bridges successfully but failed to unzip charm:

```
remote> gunzip -f charm.tar.gz
gzip: charm.tar.gz: No such file or directory

```

**Comment by stwhite91** [comment]
*Original date: 2018-01-30 18:29:06*

---
The build works, but then the jobs are pretty consistently timing out for whatever reason now:
```
In testdir charm/ofi-linux-x86_64/tmp
Submitting batch job for> make test OPTS=
 using the command> sbatch /home/skk3/autobuild/ofi/charmrun_script.31865.sh
Job enqueued under job ID 2272723
Job in state 
Job in state RUNNING
Job in state RUNNING
Job in state RUNNING
...
...
Job in state TIMEOUT
Job in state TIMEOUT
Job in state TIMEOUT
...
...

```

**Comment by stwhite91** [comment]
*Original date: 2018-01-31 15:19:52*

---
Once we get the non-SMP build running, we'll want to add a second target that is SMP

**Comment by minitu** [comment]
*Original date: 2018-01-31 20:25:43*

---
The issue of "There seems to be an issue with the OFI build that `+p1` passed to an application is regarded as `argv[1]`, and the pingpong benchmark (`tests/charm++/pingpong`) with `./pgm +p1` hangs as it tries to use `+p1` as the payload which is ultimately set to 0.", which I thought was resolved by ~~https://charm.cs.illinois.edu/gerrit/#/c/3452/~~ https://github.com/UIUC-PPL/charm/commit/6ec0f6de23ef5cf040221a8511ee90173cf634f9, seems to have resurfaced.

**Comment by minitu** [comment]
*Original date: 2018-01-31 21:16:18*

---
Actually the problem this time doesn't seem to be caused from `+p1`; the command that causes the hang is `../../../bin/testrun ./pgm +p1 ++timeout 180 +isomalloc_sync`, and the `++timeout 180` part is the culprit (so removing this works). But I think this problem happens whenever something not parsable is passed, because even `+timeout 180` causes the same hang. And the same thing if I use `charmrun` instead of `../../../bin/testrun`.

**Comment by stwhite91** [comment]
*Original date: 2018-02-02 14:11:47*

---
We still need +isomalloc_sync. The tests ran last night but failed in an AMPI test that needs that flag.

**Comment by stwhite91** [comment]
*Original date: 2018-02-03 16:58:33*

---
I added +isomalloc_sync and it passed last night. ALl that is need now is to add an SMP target.

**Comment by minitu** [comment]
*Original date: 2018-02-03 17:56:01*

---
Added SMP target to `system_list` and created `ofi-smp` folder along with `instead_test.sh` on Bridges.

**Comment by stwhite91** [comment]
*Original date: 2018-02-23 14:35:57*

---
ofi non-SMP and SMP passed yesterday. The SMP build seems to oftenhang, so that should still be monitored and addressed, but we can mark this resolved now.
