### ISSUE TITLE
make -use-new-std portable

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#168]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/168*

---
When the user passes -use-new-std to charmc, it is required to detect the type of the compilation unit (C or C++ source) and, depending on the underlying compiler, append the appropriate flag to the compilation command. The basic scaffolding to enable this exists in the configure and charmc scripts.

However, this effort to support C11 / C++11 flags is not yet portable.  For most underlying compilers, the flag resolves to a no-op as CMK_ENABLE_C11 and CMK_ENABLE_CPP11 are not defined to the appropriate values for that compiler. These shell variables need to be set for each compiler / build variant so that we can portably enable the new 2011 C / C++ standards while using charmc.

Note: This was marked as an incomplete feature, but has slipped into the 6.5 release as well as the release notes without mention of its current incomplete state. This task may be apt to be combined with recent tasks for updating the meaning of -optimize as it requires a per-compiler effort.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-16 22:01:43*

---
I've started on a new approach to this, in which charmc automatically enables C++11 support at build time, by testing the relevant options for different compilers and seeing which one works.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-17 20:08:14*

---
C++11 is now enabled automatically. C11 may never be widely enough available to matter (Microsoft doesn't like it)
