### ISSUE TITLE
ci file compilation fails with no details to debug when the module name has a hyphen

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1680]
*Original author: Samarth Kulshreshtha*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1680*

---
If you name a module with a hyphen and try to compile it then the compilation fails with -

Fatal Error by charmc in directory /home/smkuls/Documents/ra/training/hello-world
   Command /home/smkuls/Documents/charm/bin/charmxi -orig-file hello.ci returned error code 1
charmc exiting...

To reproduce, try compiling the attached file and then remove the hyphen from the module name and compile again.

Charm++ Version 60800

I did not find anything in the documentation which defines constraints on how to name a module.

[repro.ci](https://github.com/UIUC-PPL/charm/files/3536655/repro.ci.txt)

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 19:36:19*

---
Fix for charmxi was here: ~~https://charm.cs.illinois.edu/gerrit/3090~~ https://github.com/UIUC-PPL/charm/commit/6d5b9c791156df1c9db9418fe0db30e9886d6d69
