### ISSUE TITLE
Expose Arrays' Index Type as a Type Alias

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1682]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1682*

---
It would be really convenient if the template parameter to the base class of `CBase_` (specifically the `T` passed to `ArrayElementT<T>`) was exposed as a type alias (or typedef) inside the `CBase_` class, and maybe even the `CProxy_`.

**Comment by ericjbohm** [comment]
*Original date: 2017-09-20 19:34:14*

---
Retargeting new feature request to next major version

**Comment by PhilMiller** [comment]
*Original date: 2017-09-28 17:07:26*

---
Good suggestion. We'll try to get it into the next release.

**Comment by evan-charmworks** [comment]
*Original date: 2017-09-28 17:14:22*

---
Sounds simple enough. Any suggestions for the name of the typedef?

**Comment by nilsdeppe** [comment]
*Original date: 2017-10-05 15:54:00*

---
I'd go with the obvious: `array_element_t` :)

**Comment by evan-charmworks** [comment]
*Original date: 2017-10-05 17:54:39*

---
~~https://charm.cs.illinois.edu/gerrit/3109~~ https://github.com/UIUC-PPL/charm/commit/406e9d5957212e360be914fdb214dd9348a68299

I was able to add `array_index_t` to `CProxy_`*. Adding it to the base looked impossible (see `CBaseT1` in src/ck-core/charm++.h), but you can access the proxy from the base using `proxy_t`.
