### ISSUE TITLE
Charmc ends up deleting .C/.cpp file in case you forget to specify the output file while compiling

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1683]
*Original author: Samarth Kulshreshtha*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1683*

---
Repro:

1. touch test.cpp
2. charmc -o test.cpp

This will end up deleting test.cpp.

Note: g++ does not have this behavior.

**Comment by mprobson** [comment]
*Original date: 2017-09-20 19:52:37*

---
We should catch the lack of input file the way gcc (or similar) does

**Comment by PhilMiller** [comment]
*Original date: 2017-09-25 18:01:37*

---
~~https://charm.cs.illinois.edu/gerrit/3076~~ https://github.com/UIUC-PPL/charm/commit/45a157519234246fb3ea9cf5015d2bb9f49661c9
