### ISSUE TITLE
charmc Strips Empty Template Parameter Lists

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1687]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1687*

---
If I have `Klass<>` in a ci file the generated code is `Klass`, which has a completely different meaning and results in compilation failures.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-25 15:05:48*

---
Could you please post a complete .ci file that exhibits this?

**Comment by nilsdeppe** [comment]
*Original date: 2017-09-25 15:16:58*

---
Here is the simplest ci file I can think of that shows the problem:


```
<code class="cpp">
mainmodule MyMain {
  template <typename T>
  mainchare TemplateChare {
    entry TemplateChare();
  }

  mainchare TemplateChare<list<>>;
}
</code>
```


The issue is that `MyMain.def.h` has specializations like:


```
<code class="cpp">
void _registerMyMain(void)
{
  static int _done = 0; if(_done) return; _done = 1;

/* REG: mainchare TemplateChare<list >: Chare;
*/
  CkIndex_TemplateChare<list >::__register("TemplateChare<list >", sizeof(TemplateChare<list >));

}
</code>
```


and since `list` would be, say, a typelist defined as


```
<code class="cpp">
template <class...>
struct list {};
</code>
```


The result is a compiler error.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-25 19:41:43*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/3077~~ https://github.com/UIUC-PPL/charm/commit/76721f7ad99f46282383c82302cbc4964bd37615

**Comment by nilsdeppe** [comment]
*Original date: 2017-09-26 04:32:16*

---
I haven't tested yet, but thanks for getting to this so quickly!
