### ISSUE TITLE
CMK_TIMER_USE_PPC64 inaccurate with variable clock speeds

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1689]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1689*

---
The pami-linux-ppc64le machine layer is defaulting to CMK_TIMER_USE_PPC64

src/arch/pami-linux-ppc64le/conv-mach.h:#define CMK_TIMER_USE_PPC64                                1

This timer assumes a constant clock speed, which hasn't been true for a long time so projections traces are pretty useless.

Fix the code to do what's necessary to get accurate wall times from the fast intrinsic techniques.

**Comment by stwhite91** [comment]
*Original date: 2018-01-16 22:23:26*

---
Not sure why this was marked "implemented"...

**Comment by rbuch** [comment]
*Original date: 2018-01-26 23:37:17*

---
I tried reproducing this on a POWER8 machine and wasn't able to, the timing looked normal.

However, reading through some POWER9 docs makes it seem that there's no guarantee that the time base register update frequency is constant (https://ibm.ent.box.com/s/1hzcwkwf8rbju5h9iyf44wm94amnlcrv. page 898-899, section 6.1).

**Comment by jcphill** [comment]
*Original date: 2018-01-27 02:22:57*

---
It was marked implemented because of ~~https://charm.cs.illinois.edu/gerrit/#/c/3075/~~ https://github.com/UIUC-PPL/charm/commit/a27a153df52d90c1c6718b3ed1e504f7d2cc92f8

**Comment by stwhite91** [comment]
*Original date: 2018-02-11 04:55:47*

---
That patch was merged, so should this issue be marked 'merged'? If not, maybe retarget to 6.9.1

**Comment by rbuch** [comment]
*Original date: 2018-02-14 20:47:57*

---
I talked to Bilge to get more information about the timers on POWER and if there was any chance that the timer can be guaranteed to update at a fixed frequency. She didn't know and said that she would get back to me with more information.

For now, I'm pushing this to 6.9.1.

**Comment by evan-charmworks** [comment]
We should probably close this since POWER defaults to getrusage now.
