### ISSUE TITLE
Charmxi dies on Array Indices with Template Parameters

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1692]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1692*

---
If the index to a chare array has template parameters then charmc chokes. A workaround is defining a type alias to the type with the template parameters substituted in. However, it would be nice if this worked directly. Here is a simply CI file that demonstrates the issue:

```
<code class="cpp">
module Array {
  array [MyIndex<1>] MyArray {
    entry MyArray();
  }
}
</code>
```

The error is:

```
<code class="text">
STDIN:2:14-17: error: invalid construct
  array [MyIndex<1>] MyArray {
             ^^^^
Fatal Error by charmc in directory ./spectre
   Command ../charm/bin/charmxi -orig-file ./dummy.ci returned error code 1
charmc exiting...
</code>
```

**Comment by PhilMiller** [comment]
*Original date: 2017-09-28 17:13:52*

---
The long-range direction on this is to get away from .ci files entirely, so we don't need to run on the 'parsing C++' treadmill.

If it turns out to be straightforward, we may teach the .ci file parser to handle this in the meantime.

**Comment by stwhite91** [comment]
*Original date: 2018-04-10 14:35:04*

---
Nils pointed out that they have a templated array index type in Spectre that that allows users to define custom indices at compile-time, which we could absorb into Charm++: https://github.com/nilsdeppe/spectre/blob/develop/src/Parallel/ArrayIndex.hpp

**Comment by stwhite91** [comment]
*Original date: 2018-04-13 16:52:22*

---
Spectre currently has to work around .ci file parsing limitations for this.

Changes in here to support ci file changes: build/src/Parallel/ConstGlobalCache.def.h

Class for templated array indices here. Nils encouraged us to absorb this class into charm: spectre/src/Parallel/ArrayIndex.hpp

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-16 21:10:41*

---
The underlying deficiency in parsing is fixed in: ~~https://charm.cs.illinois.edu/gerrit/4006~~ https://github.com/UIUC-PPL/charm/commit/c50138d4b725299bb6d56c0de5ae052fcc520398

This does not integrate ArrayIndex.hpp from SpECTRE. A separate feature request/reminder issue can be created for that task.
