### ISSUE TITLE
Projections shows garbage for indices of 4d, 5d, 6d array elements

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1694]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1694*

---
Projections seems to come with an implicit assumption that chare arrays have (at most) 3 dimensions, and hence element indices have 3 components. For elements of higher dimension chare arrays, the values shown for object for the 'Id' field in the Timeline view seem to be garbage. E.g. look at traces from `examples/charm++/Molecular2D

Eric, have you ever seen this in traces from OpenAtom? That uses chare arrays of dimension greater than 3d, right?

**Comment by stwhite91** [comment]
*Original date: 2017-11-02 02:29:03*

---
I happened to be looking at CkArrayIndex for issue #1065, realized it was missing support in places for >3 dimensional arrays, and remembered this bug.
This adds the support for that and updates the tracing code accordingly. Projections itself will need to be updated to process the CmiObjId objects as either int or short arrays depending on the dimensionality.

https://charm.cs.illinois.edu/gerrit/#/c/3218/

**Comment by stwhite91** [comment]
*Original date: 2017-11-03 17:52:25*

---
Can you take over 3218? It's failing in LDSend() currently. I think there might be another object in the LB Database that stores array indices?

**Comment by stwhite91** [comment]
*Original date: 2018-02-11 19:06:23*

---
Projections needs the corresponding support to display >3 dimensional array indices.

**Comment by stwhite91** [comment]
*Original date: 2018-04-20 00:04:49*

---
https://charm.cs.illinois.edu/gerrit/#/c/projections/+/4034/
