### ISSUE TITLE
Allow default arguments in group entry methods

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1696]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1696*

---
I'm not sure this is a bug or a feature request since that depends on whether or not default arguments are supposed to work. What I've noticed is that default arguments for chare and chare array entry methods are supported (maybe not intentionally). However, when I have a group they break because of the "missing" default arguments to `int npes`, `int *pes`, etc. Here is the compiler error:

```
<code class="text">
AlgorithmGroup.decl.h:385:129: error: missing
      default argument on parameter 'npes'
  ...const ReceiveData_t &impl_noname_2, bool enable_if_disabled = false, int npes, int *pes, const C...
                                                                              ^
</code>
```

Being able to have default arguments for any entry method would be really useful.

**Comment by PhilMiller** [comment]
*Original date: 2017-09-28 17:20:19*

---
I'd call this a bug, indeed. Default arguments to entry methods are supported somewhat intentionally, and it's incorrect that they should be broken for group entry methods because of the support for 'list sends'.

**Comment by nilsdeppe** [comment]
*Original date: 2017-09-28 17:39:47*

---
Alright, thanks for the clarification!
