### ISSUE TITLE
[inline] template entry methods do not work

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1698]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1698*

---
I'm trying to call an `[inline]` template entry method, and it fails because the generated code calls:

```
<code class="cpp">
obj->receive_data(impl_noname_1, impl_noname_2, enable_if_disabled);
</code>
```

when it should generate:

```
<code class="cpp">
obj->template receive_data<ReceiveTag>(impl_noname_1, impl_noname_2, enable_if_disabled);
</code>
```

**Comment by epmikida** [comment]
*Original date: 2018-02-28 21:19:49*

---
Is this only in the case where template arguments can't be inferred automatically?

**Comment by epmikida** [comment]
*Original date: 2018-03-01 02:38:30*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3790/~~ https://github.com/UIUC-PPL/charm/commit/39cd0e61d4f7fdde09c063fc9c879b077d310d54
