### ISSUE TITLE
Native MPI Interoperability with PAMI machine layer

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#17]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/17*

---
Suport interoperation of Charm and MPI on PAMI.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 21:00:35*

---
The  bits described "here":https://wiki.alcf.anl.gov/parts/index.php/PAMI#Using_multiple_clients may be helpful, especially usage of the `PAMI_CLIENTS` environment variable.

**Comment by nikhil-jain** [comment]
*Original date: 2013-05-31 06:31:36*

---
Yeah, I am an aware of these methods and PAMI_CLIENTS. We have some sort of interop working using it in one of the branches.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-04 03:31:41*

---
Suport for time division based interoperation has been added. Other features will be dealt in a separate issue.

**Comment by PhilMiller** [comment]
*Original date: 2014-08-13 03:39:26*

---
Retitled for ease of comprehension in release-notes/roadmap usage of Redmine.
