### ISSUE TITLE
Cannot have non-copyable types in constructor arguments

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#1701]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1701*

---
If I try to pass a non-copyable type to a chare constructor my only option is to move an lvalue reference, which is not good. The solution is again supporting C++11, though there may be a C++03 method of implementing a workaround.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:32:21*

---
I take it you're trying to pass an rvalue reference to such an object? It doesn't really make semantic sense for any entry method argument (passed to a constructor or otherwise) to be truly non-copyable, in that they're going to get serialized and desrialized, creating a copy in some form.

I think the code is happy to take a `const &`, though. I'll check that shortly.

**Comment by nilsdeppe** [comment]
*Original date: 2017-10-06 15:44:18*

---
Looking now, this ticket could be made much more helpful on my part. The serialization is not the problem, it is the move into the `impl_obj_void`. Below is a modified def.h file where I have added the missing calls to `std::move`. The deserialized `impl_noname_0` is normally passed as an lvalue reference, which is fine for copyable types, but not for non-copyable. Having the constructor take a non-const lvalue reference and moving that is a workaround, but this breaks using the class outside of a Charm++ context. So far this has only bitten us in unit tests, but as C++11 support is required this should be a relatively straightforward change to Charm++.


```
<code class="cpp">
template <typename Metavariables>

void CkIndex_ConstGlobalCache<Metavariables>::_call_ConstGlobalCache_marshall1(
    void* impl_msg, void* impl_obj_void) {
  ConstGlobalCache<Metavariables>* impl_obj =
      static_cast<ConstGlobalCache<Metavariables>*>(impl_obj_void);
  CkMarshallMsg* impl_msg_typed = (CkMarshallMsg*)impl_msg;
  char* impl_buf = impl_msg_typed->msgBuf;
  /*Unmarshall pup'd fields: const tuples::TaggedTupleTypelist<typename
   * Metavariables::const_global_cache_tag_list > &impl_noname_0*/
  PUP::fromMem implP(impl_buf);
  tuples::TaggedTupleTypelist<
      typename Metavariables::const_global_cache_tag_list>
      impl_noname_0;
  implP | impl_noname_0;
  impl_buf += CK_ALIGN(implP.size(), 16);
  /*Unmarshall arrays:*/
  new (impl_obj_void) ConstGlobalCache<Metavariables>(std::move(impl_noname_0));
}
template <typename Metavariables>

int CkIndex_ConstGlobalCache<Metavariables>::
    _callmarshall_ConstGlobalCache_marshall1(char* impl_buf,
                                             void* impl_obj_void) {
  ConstGlobalCache<Metavariables>* impl_obj =
      static_cast<ConstGlobalCache<Metavariables>*>(impl_obj_void);
  /*Unmarshall pup'd fields: const tuples::TaggedTupleTypelist<typename
   * Metavariables::const_global_cache_tag_list > &impl_noname_0*/
  PUP::fromMem implP(impl_buf);
  tuples::TaggedTupleTypelist<
      typename Metavariables::const_global_cache_tag_list>
      impl_noname_0;
  implP | impl_noname_0;
  impl_buf += CK_ALIGN(implP.size(), 16);
  /*Unmarshall arrays:*/
  new (impl_obj_void) ConstGlobalCache<Metavariables>(std::move(impl_noname_0));
  return implP.size();
}

</code>
```

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:47:37*

---
Indeed, CProxy_Foo's generated code takes its arguments by const& even when declared in the .ci file as taking them by value. So, a temporary object passed as an argument will do the right thing, and an actual lvalue can be moved or not, and still be consumed as const lvalue reference. As far as I can tell, this means there isn't an issue of code semantics that should work but doesn't, but there might be syntactic representations that have to be avoided. Do I have that right, or is there a case I haven't considered properly? Do you have a concrete example I could look at?

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:49:10*

---
OK, our notes crossed paths as we were writing them. I'll look further in a bit.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-06 15:53:08*

---
OK, so I think what you're saying is that the generated code needs to move the temporary instances, so that the recipient can potentially take them by rvalue reference and consume them, rather than only being able to copy or hackishly moving from something that looks like an lvalue reference argument. Is that right? The difference between the current generated code and your example is the addition of std::move?

**Comment by nilsdeppe** [comment]
*Original date: 2017-10-06 16:00:18*

---
Yep, that's exactly correct. The only difference between my modified code and the generated is the addition of `std::move`. Specifically,


```
<code class="cpp">
new (impl_obj_void) ConstGlobalCache<Metavariables>(simpl_noname_0);
// was changed to
new (impl_obj_void) ConstGlobalCache<Metavariables>(std::move(impl_noname_0));
</code>
```


and the same for the second function.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-05 16:50:44*

---
I think this is addressed by ~~https://charm.cs.illinois.edu/gerrit/#/c/3263/~~ https://github.com/UIUC-PPL/charm/commit/fc7869098f86ab81d1c8fa1f9e18bb9aa4cf08f8 ?

**Comment by PhilMiller** [comment]
*Original date: 2017-12-11 21:34:07*

---
Based on the linked patch. If that doesn't resolve this issue, we can re-adjust the status, target, and assignment.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-15 18:50:35*

---
As illustrated [[here|~~https://charm.cs.illinois.edu/gerrit/#/c/3263/~~ https://github.com/UIUC-PPL/charm/commit/fc7869098f86ab81d1c8fa1f9e18bb9aa4cf08f87/src/ck-core/ckarray.h]] we now have chare classes that take rvalue references to their non-copyable constructor arguments.

**Comment by nilsdeppe** [comment]
*Original date: 2017-12-30 03:45:40*

---
It looks like with all the changes the generated code is `std::move(impl_noname_0).t` which has the type `T`, not `T&&`. The correct implementation would be `std::move(impl_noname_0.t)`. I've pushed a patch to ~~https://charm.cs.illinois.edu/gerrit/#/c/3472/~~ https://github.com/UIUC-PPL/charm/commit/f47e4ffc942fdf4d9d3c2e87e8aa2a6be50bfc251/src/xlat-i/xi-Parameter.C
