### ISSUE TITLE
Need a test that uses +partitions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#1709]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1709*

---
Bug #1675 should have been caught much earlier with a simple `make test` in the main repository.

One challenge is non-LRTS machine layers that don't implement partition support. We'll delete `src/arch/net`, so that's not an issue, but `srch/arch/pami` may still be. The relevant `conv-mach.sh` will have to set a flag indicating the lack of support, so the test's `Makefile` can check for it and skip the test accordingly.

**Comment by karthiksenthil** [comment]
*Original date: 2017-10-12 19:48:41*

---
Gerrit patch : ~~https://charm.cs.illinois.edu/gerrit/#/c/3125/~~ https://github.com/UIUC-PPL/charm/commit/116ae12258afd786c9fc9cb86cf5314571818d91
