### ISSUE TITLE
objid_t: Specify array size at construction time via CkArrayOptions despite non-bulk-construction

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#171]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/171*

---
Map onto bulk constructor metadata described in #170

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:05:50*

---
This won't be ready for 6.6, so push it back.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-21 01:52:36*

---
Commit e430341f4beef9cc83b3092635990e8f5bd5a6f8
