### ISSUE TITLE
examples/zerocopy/pingpong crashes intermittently on OFI layer SMP mode builds for production builds

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1714]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1714*

---
No body.

**Comment by nitbhat** [comment]
*Original date: 2017-10-16 19:24:12*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3133/~~ https://github.com/UIUC-PPL/charm/commit/b1b640302086d89784e8a0ed61436bdfc0cd6f93

The bug was due to a race condition where the message in the charm layer gets deleted before the deregistration in the machine layer. (as the deregistration code uses a pointer in the charm message). The fix was to store the memory region pointer in a stack object before calling the charm/converse message handler and use that for deregistration.

**Comment by stwhite91** [comment]
*Original date: 2017-10-20 15:18:04*

---
The 6.8.1 release was already tagged.

**Comment by stwhite91** [comment]
*Original date: 2017-10-21 14:09:37*

---
If there's a 6.8.2 this will be in it.
