### ISSUE TITLE
Sending variable sized messages with std::vectors

### ISSUE THREAD

**Issue by karthiksenthil** [UIUC-PPL/charm#1717]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1717*

---
This bug is based on the email sent by Joszef Bakosi to the mailing list : https://lists.cs.illinois.edu/lists/arc/charm/2017-10/msg00002.html

I was able to replicate the bug for a small test program attached with this bug report.

[hello.C](https://github.com/UIUC-PPL/charm/files/3536662/hello.C.txt)
[hello.ci](https://github.com/UIUC-PPL/charm/files/3536663/hello.ci.txt)

**Comment by stwhite91** [comment]
*Original date: 2017-10-20 23:47:27*

---
The issue is with the message object's constructor not copying all the elements of the vector into its array members. I replied to the mailing list.
