### ISSUE TITLE
pxshm for mpi layer

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1722]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1722*

---
consult with Nitin regarding implementation details.  Short term, figure out if this is plausible for 6.9 or not.

**Comment by stwhite91** [comment]
*Original date: 2017-10-31 04:05:19*

---
The current plan is to use CMA. It is supported by Linux kernels v3.2+. It's not clear if it will be ready for 6.9.0 or not yet.

**Comment by nitbhat** [comment]
*Original date: 2017-11-10 15:07:01*

---
Rejecting this issue as we'll be having a layer agnostic LRTS implementation: https://charm.cs.illinois.edu/redmine/issues/1657
