### ISSUE TITLE
Bigsim autobuild failures in checkpoint/restart test

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1726]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1726*

---
tests/charm++/chkpt/ is failing the past couple of days on the Bigsim autobuild target on Charity.

```
./build LIBS netlrts-linux-x86_64 bigsim
cd netlrts-linux-x86_64/tests/charm++/chkpt/
make

./charmrun  ./hello +p2 +x3 +y1 +z1  ++local ++no-va-randomization
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.007 seconds.
Charm++> Running in non-SMP mode: numPes 2
Converse/Charm++ Commit ID: 57cc10f
Charm++> scheduler running in netpoll mode.
BG info> Simulating 3x1x1 nodes with 1 comm + 1 work threads each.
BG info> Network type: bluegene.
alpha: 1.000000e-07	packetsize: 1024	CYCLE_TIME_FACTOR:1.000000e-03.
CYCLES_PER_HOP: 5	CYCLES_PER_CORNER: 75.
BG info> cpufactor is 1.000000.
BG info> floating point factor is 0.000000.
BG info> Using WallTimer for timing method. 
CharmLB> Load balancer ignores processor background load.
CharmLB> Load balancer assumes all CPUs are same.
Trace: traceroot: ./hello
Running Hello on 3 processors for 8 elements
Charmrun> error on request socket to node 0 '127.0.0.1'--
Socket closed before recv.
```

https://charm.cs.illinois.edu/autobuild/cur/netlrts-linux-x86_64-bigsim.txt

**Comment by stwhite91** [comment]
*Original date: 2017-11-02 14:55:50*

---
Buil system changes broke bigsim even worse for the past couple days but those have been fixed so this is again showing up.

**Comment by stwhite91** [comment]
*Original date: 2017-11-02 17:10:28*

---
Phil commented that git bisect shows this commit at fault: ~~https://charm.cs.illinois.edu/gerrit/#/c/381/~~ https://github.com/UIUC-PPL/charm/commit/be7ee10917004cb13a8fd0c27fd0f026bf774c43

**Comment by karthiksenthil** [comment]
*Original date: 2017-11-02 20:01:49*

---
This bug is not specific to the checkpoint/restart test. The hang happens when number of Charm PEs does not divide the number of bigsim PEs. For example the following run command also hangs for `tests/charm++/simplearrayhello`

`./charmrun +p2 ./hello 10 +x3 +y1 +z1 +wth1`

**Comment by PhilMiller** [comment]
*Original date: 2017-11-02 20:47:35*

---
It looks like the fix for #1735 also solves this. I'll run the tests a few more times to gain a bit of confidence.

**Comment by PhilMiller** [comment]
*Original date: 2017-11-02 20:50:07*

---
Looks like bgtest is happy with that patch, too.

**Comment by PhilMiller** [comment]
*Original date: 2017-11-02 20:51:07*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3220/~~ https://github.com/UIUC-PPL/charm/commit/51b07e3dfe956ae0ef1691727c1174b3db021f84
