### ISSUE TITLE
Make Boost uFcontext the default ULT implementation on supported platforms

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1727]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1727*

---
Boost uFcontext threads have lower context switching than any existing implementation we have, so should be made the default wherever they work. Separate issues should be opened for platforms where they don't work.

**Comment by stwhite91** [comment]
*Original date: 2017-11-29 18:34:07*

---
Bump

**Comment by stwhite91** [comment]
*Original date: 2017-12-11 18:54:28*

---
Bump, this would be valuable to have

**Comment by sbak5** [comment]
*Original date: 2017-12-13 20:51:32*

---
Thread_local variables are not guaranteed to work with boost-context. 

I think it works on linux but didn't work on OSX. So, if we want to make this as default ULT implementation then we should turn off thread local based `Cpv` implementation and use `Cpv` based on pthread_set/getspecific

**Comment by stwhite91** [comment]
*Original date: 2017-12-13 20:58:04*

---
Yes, so it should be the default on all platforms that it doesn't break other things on

**Comment by stwhite91** [comment]
*Original date: 2018-01-05 00:19:23*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3482/~~ https://github.com/UIUC-PPL/charm/commit/ed3214e889516bba1f400c49307702ff3e9273e0
