### ISSUE TITLE
The RTS should set std::set_terminate

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1730]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1730*

---
No body.

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-14 17:57:49*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/3720/~~ https://github.com/UIUC-PPL/charm/commit/becc7731feef74b4001fbe31a85658d054411fb6
