### ISSUE TITLE
Complete spack installation script

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1731]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1731*

---
Spack has a charm package, but it is out of date (v6.7.1) and only supports a few charm build options (net, netlrts, mpi, verbs).

Add pamilrts-{bluegeneq, linux-x86_64ppcle}, verbs-linux-ppc64le, ofi-, gni-crayx{e,c}. Remove deprecated 'net-' builds. Add different compiler options. Add AMPI and LIBS build targets. Add 6.7.0, 6.8.0, 6.8.1, 6.8.2 releases.

https://github.com/LLNL/spack/tree/develop/var/spack/repos/builtin/packages/charm

**Comment by stwhite91** [comment]
*Original date: 2017-11-08 19:32:05*

---
Note the mpi.patch file they have in the spack/charm package is no longer needed since 6.8.0

**Comment by stwhite91** [comment]
*Original date: 2018-01-25 23:55:27*

---
This wis now assigned to a Charmworks intern

**Comment by stwhite91** [comment]
*Original date: 2018-02-07 17:45:12*

---
https://charm.cs.illinois.edu/gerrit/#/c/3638/

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-12 19:19:53*

---
We should discuss if it makes sense to put the package in charm++'s repository, or if we just update the package on spack's GitHub.

**Comment by stwhite91** [comment]
*Original date: 2018-03-28 01:16:44*

---
Spack pull request here: https://github.com/spack/spack/pull/7291

I'm not sure if Edward Kim is still working for Charmworks on this, so we may need someone else to take it over and address the feedback from Spack developers.

**Comment by matthiasdiener** [comment]
*Original date: 2018-03-28 22:22:19*

---
`Sam, do you know what the status is? I'd be happy to take this over, but I don't have permissions to modify the pull request.

**Comment by stwhite91** [comment]
*Original date: 2018-03-28 22:41:57*

---
I just asked Edward and he just hadn't seen the comments on the pull request for whatever reason. So he'll keep working on it

**Comment by stwhite91** [comment]
*Original date: 2018-05-23 19:13:18*

---
Edward Kim got his pull request merged into the Spack repo: https://github.com/spack/spack/pull/7291

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-23 19:50:50*

---
It would be nice to be able to build the git version of charm++ via spack (which is something spack supports: https://spack.readthedocs.io/en/latest/packaging_guide.html#git ). In that case, we would need to depend on automake and autoconf as well.

**Comment by stwhite91** [comment]
*Original date: 2018-05-23 19:59:18*

---
Yeah that'd be useful, can you do that? Edward Kim is I think no longer at Charmworks.

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-23 20:02:02*

---
Ok, I'll do it.

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-23 21:01:18*

---
Pull request here: https://github.com/spack/spack/pull/8260

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-24 16:43:49*

---
The patch has been merged upstream.

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-24 17:40:42*

---
By the way, should this be mentioned somewhere in the manual (e.g., Appendix A. Installing Charm++)?

**Comment by stwhite91** [comment]
*Original date: 2018-05-24 17:42:18*

---
Yeah it could be

**Comment by matthiasdiener** [comment]
*Original date: 2018-05-24 21:18:15*

---
Patch for the manual is here: ~~https://charm.cs.illinois.edu/gerrit/4229~~ https://github.com/UIUC-PPL/charm/commit/6edb4d42d265654522decbf326a4a630a0c8eedd
