### ISSUE TITLE
Improve PUP performance of std::vector<T> where T is PUPbytes

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1739]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1739*

---
The following commit improved performance of std::vector<T> where std::is_arithmetic<T> is true. This should be extended to cover all PUPbytes types: ~~https://charm.cs.illinois.edu/gerrit/#/c/3177/~~ https://github.com/UIUC-PPL/charm/commit/78480a6186dfb157ccbe98595619b7c801827bf3

**Comment by jcphill** [comment]
*Original date: 2017-11-07 20:05:20*

---
Why std::is_arithmetic<> rather than the more general std::is_trivially_copyable<>?

**Comment by stwhite91** [comment]
*Original date: 2017-11-07 20:36:04*

---
That would work, but we'd need to add a configure-time test for support of it since not all C++11 compilers actually support it: https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std

**Comment by stwhite91** [comment]
*Original date: 2018-02-28 21:30:37*

---
Make PUP STL check if the type is PUPbytes rather than just arithmetic: ~~https://charm.cs.illinois.edu/gerrit/#/c/3785/~~ https://github.com/UIUC-PPL/charm/commit/c081ec4885871f68df175c220194cd8d0566ec4e

Improve documentation to recommend using PUPbytes for classes without pointer members: ~~https://charm.cs.illinois.edu/gerrit/#/c/3786/~~ https://github.com/UIUC-PPL/charm/commit/7062a0fcb3e1534453c9f052cfd55bdfa387eeb4
