### ISSUE TITLE
Send large readonly variables using the Nocopy API to reduce memory footprint and improve startup time

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1742]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1742*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2018-01-09 15:53:43*

---
I think it'd be good to get started on this sooner than later since it may serve as a motivating case for the different modes of registration/rdma

**Comment by nitbhat** [comment]
*Original date: 2018-04-06 00:51:02*

---
Moving this after 6.9

**Comment by stwhite91** [comment]
*Original date: 2018-09-07 15:22:41*

---
This would be a good first use case for the zero copy broadcast API

**Comment by nitbhat** [comment]
*Original date: 2018-10-10 15:57:14*

---
Gerrit: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4637/~~ https://github.com/UIUC-PPL/charm/commit/797b1f04a5fcc55d280a106714d380b11f5c18f6
