### ISSUE TITLE
Darwin (MacOS) build error with Xcode 9

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1743]
*Original author: Omri Mor (@omor1)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1743*

---
Compiling Charm++ with Xcode 9 results in a build failure, due to changes in header files.
Other projects (example from TensorFlow: https://github.com/tensorflow/tensorflow/issues/13220#issuecomment-331579775) have had the same issue.
The internal C++ <code>__threading_support</code> header (<code>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support</code>) defines the <code>__libcpp_thread_get_port()</code> function, which internally uses <code>pthread_mach_thread_np()</code>.
_That_ function is defined in <code>pthread.h</code> (<code>/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread.h</code>), but the function is hidden behind preprocessor conditions:

```
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE) || defined(__cplusplus)
```

<code>_XOPEN_SOURCE</code> is defined in <code>src/arch/*-darwin-x86_64/conv-mach.h</code> so that the <code>ucontext</code> functions can be used.
A workaround is to also define <code> _POSIX_C_SOURCE</code> or <code>_DARWIN_C_SOURCE</code>. I have no idea why <code>__cplusplus</code> isn't defined.

Another option is to use <code><sys/ucontext.h></code> instead of <code><ucontext.h></code>, which I don't think has the same requirement for <code>_XOPEN_SOURCE</code>

**Comment by stwhite91** [comment]
*Original date: 2017-11-22 18:37:34*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3322/~~ https://github.com/UIUC-PPL/charm/commit/1b4695ac0d34a57f56e3ba4911485c546f3dd735

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-27 17:56:59*

---
My patch uses the _DARWIN_C_SOURCE workaround, which is what I found used by two open source projects that came up in search results for the error message. It mitigates the issue entirely with no side effects I have observed, but it still feels like a hack.

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-04 23:07:26*

---
Other projects with the same problem and solution:

https://github.com/Habbie/pdns/commit/e201675a3aa63712f8d08c27f2cedc10873b8f4c
https://github.com/carlesfernandez/gnss-sdr/commit/bda1f15594d114216fa2f4c2817a3d10e9694646
https://github.com/envoyproxy/envoy/pull/1785/commits/9536842cfb50d245b309fc7dddb2404343bbe245
https://github.com/dotnet/coreclr/commit/aa26d41f9e1dc0e448318472d67aa432cf974e0e
https://github.com/khizmax/libcds/pull/96/commits/cd5a8dab3e1cb8587e2289a5496a33ca7f388df7
