### ISSUE TITLE
build --help needs information from src/scripts/configure

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1746]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1746*

---
Running build --help produces the following error:
```
Advanced options:
:./build: line 81: ./src/scripts/configure: No such file or directory
./build: line 82: ./src/scripts/configure: No such file or directory
  bigemulator     compile for BigSim simulator
  ooc             compile with out of core support
  syncft          compile with Charm++ fault tolerance support
  mlogft          compile with Charm++ message logging fault tolerance support
  papi            compile with PAPI performance counter support (if any)

```

**Comment by jcphill** [comment]
*Original date: 2017-11-16 18:09:16*

---
Error was showing up in the wrong place due the the paginator.  It's actually in the "Enable/disable features" section, which runs configure --help.
```
Enable/disable features:
./build: line 81: ./src/scripts/configure: No such file or directory
./build: line 82: ./src/scripts/configure: No such file or directory
  --with-production       build Charm++ with all optimizations for maximum performance, and disabling all above features

```

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-21 19:51:18*

---
This was caused by the removal of configure from the git repository, which is now regenerated from configure.ac during the build process. We run autoreconf before packaging a tarball, so `./build --help` should work fine there. I'm not sure how best to handle the problem when building directly from git.

**Comment by jcphill** [comment]
*Original date: 2017-11-29 20:51:44*

---
What is the command to run autoreconf without creating a build directory?

**Comment by PhilMiller** [comment]
*Original date: 2017-11-29 21:16:43*

---
`package-tarbahll.sh` should get you a readily-built tarball snapshot, with the configure script and other bits suitably generated.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-11 00:31:48*

---
Please test: ~~https://charm.cs.illinois.edu/gerrit/3503~~ https://github.com/UIUC-PPL/charm/commit/84becca3cd156a4cb68d0ac2410091ea4fee47a6
