### ISSUE TITLE
hwloc Breaking ROMIO Configure Script

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#1747]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1747*

---
The ROMIO configure script is broken on 32-bit platforms, complaining: 
```
checking if a simple MPI program compiles and links...  
*# Unable to compile a simple MPI program
*# Use the -mpi, -mpiincdir, and -mpilib options to configure to specify the
*# MPI implementation, the include path for mpi.h, and the MPI library to link
/scratch/autobuild/netlrts-linux/charm/netlrts-linux/bin/ampicc  -O -I/scratch/autobuild/netlrts-linux/charm/netlrts-linux/include -o conftest mpitest.c /scratch/autobuild/netlrts-linux/charm/netlrts-linux/lib/libmoduleampi.a > /dev/null 2>&1
buildcharm`esteem:/scratch/autobuild/netlrts-linux/charm/netlrts-linux-x86_64/tmp/libs/ck-libs/ampi/romio$ /scratch/autobuild/netlrts-linux/charm/netlrts-linux/bin/ampicc  -O -I/scratch/autobuild/netlrts-linux/charm/netlrts-linux/include -o conftest mpitest.c /scratch/autobuild/netlrts-linux/charm/netlrts-linux/lib/libmoduleampi.a
/usr/bin/ld: skipping incompatible /scratch/autobuild/netlrts-linux/charm/netlrts-linux/bin/../lib/libhwloc_embedded.a when searching for -lhwloc_embedded
/usr/bin/ld: cannot find -lhwloc_embedded
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /scratch/autobuild/netlrts-linux/charm/netlrts-linux-x86_64/tmp/libs/ck-libs/ampi/romio
   Command g++ -rdynamic -m32 -O -L/scratch/autobuild/netlrts-linux/charm/netlrts-linux/bin/../lib mpitest.o moduleinit15380.o -lmoduletcharm -lmoduleampi -lmoduletcharmmain /scratch/autobuild/netlrts-linux/charm/netlrts-linux/lib/libmoduleampi.a -lddt -lampi-compat -lckmain -lck -lmemory-default -lthreads-default -lconv-cplus-y -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lckqt -ldl -lmoduletcharmmain -lmoduleampi -lmoduletcharm -ltcharm-compat -lmoduleNDMeshStreamer -lmodulecompletion -lm -o conftest returned error code 1
charmc exiting...
```

This may be due to an earlier issue in the hwloc build:
```
make[1]: Leaving directory `/scratch/autobuild/netlrts-linux-smp/charm/netlrts-linux-smp/tmp/hwloc'
( test -e hwloc/src/.libs/libhwloc_embedded.lib && cp -f hwloc/src/.libs/libhwloc_embedded.lib hwloc/src/.libs/libhwloc_embedded.a )
make: [hwloc-target] Error 1 (ignored)

```

**Comment by rbuch** [comment]
*Original date: 2017-11-27 21:54:29*

---
This was observed on netlrts-linux-smp and netlrts-linux (with commit e1608dd483df978cf070b4b561c0f257e7ea2ef1).

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-27 21:56:56*

---
The `cp -f hwloc/src/.libs/libhwloc_embedded.lib hwloc/src/.libs/libhwloc_embedded.a` line is for Windows, and failure is normal on all other platforms. I should still take care of the error message.

**Comment by stwhite91** [comment]
*Original date: 2017-11-29 19:06:24*

---
Merged the following, but ROMIO still doesn't like it: ~~https://charm.cs.illinois.edu/gerrit/#/c/3335/~~ https://github.com/UIUC-PPL/charm/commit/b27683a8391a710574dc4124cd203f0df3e68ec4

**Comment by matthiasdiener** [comment]
*Original date: 2017-11-29 20:39:09*

---
The problem appears to be that libhwloc_embedded.a is a 64-bit file, while g++ tries to link to it with the `-m32` option.

```
$ ar x /scratch/autobuild/netlrts-linux/charm/netlrts-linux/bin/../lib/libhwloc_embedded.a
$ file topology.o
topology.o: ELF 64-bit LSB  relocatable, x86-64, version 1 (SYSV), not stripped
```

I.e., this particular issue is not ROMIO specific.

Running `make test` in `tests` fails with the same linker error for all of the tests (not only those that use AMPI or ROMIO).

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-29 23:43:57*

---
The problem originates from this test as part of hwloc's configuration step:

 checking size of void *... 8

By adding this line to configure.ac with the rest of the hwloc settings at the bottom, the test determines that sizeof(void *) == 4.

 export CFLAGS="-m32"

With this, hwloc compiles as 32-bit and the build command completes, due to this code in hwloc.m4:

 AC_MSG_CHECKING([which CPU support to include])
 case ${target} in
 i*86-*-*|x86_64-*-*|amd64-*-*)
 case ${ac_cv_sizeof_void_p} in
   4)
     AC_DEFINE(HWLOC_X86_32_ARCH, 1, [Define to 1 on x86_32])
     hwloc_x86_32=yes
     HWLOC_MS_LIB_ARCH=X86
     AC_MSG_RESULT([x86_32])
     ;;
   8)
     AC_DEFINE(HWLOC_X86_64_ARCH, 1, [Define to 1 on x86_64])
     hwloc_x86_64=yes
     HWLOC_MS_LIB_ARCH=X64
     AC_MSG_RESULT([x86_64])
     ;;
   *)
     AC_DEFINE(HWLOC_X86_64_ARCH, 1, [Define to 1 on x86_64])
     hwloc_x86_64=yes
     HWLOC_MS_LIB_ARCH=X64
     AC_MSG_RESULT([unknown -- assuming x86_64])
     ;;
 esac
 ;;
 *)
 AC_MSG_RESULT([unknown])
 ;;
 esac

The remaining question is how to add this flag properly in the correct circumstances.

**Comment by matthiasdiener** [comment]
*Original date: 2017-11-30 09:59:20*

---
Is the hwloc configure script honoring CMK_CC and so on? e.g., by running configure like this:

```
CC=$CMK_CC CFLAGS=$CMK_CFLAGS ./configure [...]

```

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-01 20:57:16*

---
~~https://charm.cs.illinois.edu/gerrit/3342~~ https://github.com/UIUC-PPL/charm/commit/446f84a6ff673bf328bee64438141ec2e298bea7

**Comment by PhilMiller** [comment]
*Original date: 2017-12-05 15:56:34*

---
There seems to still be a problem of the same sort in the Windows builds, based on autobuild this morning.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-05 15:57:33*

---
There's also something funny going on here:
https://charm.cs.illinois.edu/autobuild/cur/netlrts-linux-x86_64-omp-smp.txt
