### ISSUE TITLE
CharmPy support in Charm++

### ISSUE THREAD

**Issue by juanjgalvez** [UIUC-PPL/charm#1748]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1748*

---
Merge the changes in jjgalvez/charmpy into Charm++, and support a clean method of building libcharm.so on any system.

More complicated might be adding load balancers as an option, so maybe some specific load balancers should always be in libcharm.so by default?

**Comment by stwhite91** [comment]
*Original date: 2017-11-30 14:12:55*

---
For shared object build issues, see: https://charm.cs.illinois.edu/redmine/issues/1668

**Comment by juanjgalvez** [comment]
*Original date: 2018-01-23 17:09:12*

---
This patch (~~https://charm.cs.illinois.edu/gerrit/#/c/3550/~~ https://github.com/UIUC-PPL/charm/commit/8988c76ea26e7649f179035546948dba8c055983) merges all the changes in 'jjgalvez/charmpy' into master.
It also includes GreedyRefineLB by default when building with `--enable-charmpy`.

Note that the above patch doesn't yet include a good way to generate libcharm.so, but at least we have an "ugly" way to do it for regular Linux workstations and for macOS, as described in README.charmpy.

**Comment by juanjgalvez** [comment]
*Original date: 2018-01-23 17:16:00*

---
Moved the need for a good way to build libcharm.so to a separate issue: https://charm.cs.illinois.edu/redmine/issues/1778
