### ISSUE TITLE
CMA fails at Runtime when OS doesn't provide permissions

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1749]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1749*

---
Ronak saw this issue on his laptop with a netlrts-linux-x86_64 build. 

Although the issue is being identified and handled, there's nothing much the user can do to fix it. A check for permissions during configure can help disable CMA on machines that support it but do not provide permissions for it. 

```
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: Can't use CMA for SHM! Permissions Denied
```

**Comment by stwhite91** [comment]
*Original date: 2017-12-06 17:03:35*

---
Related: the print statement that says if CMA is enabled should only be printed once on PE 0, but currently it gets printed multiple times:


```
$ ./charmrun +p4 ./pgm +vp4 ++local
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.006 seconds.
Charm++> Running in non-SMP mode: numPes 4
Converse/Charm++ Commit ID: v6.8.2-138-g529f8574d
Charm++> cma enabled for within node transfers using the zerocopy API
Charm++> cma enabled for within node transfers using the zerocopy API
Charm++> cma enabled for within node transfers using the zerocopy API
Charm++> cma enabled for within node transfers using the zerocopy API
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.001 seconds.
[Partition 0][Node 0] End of program
```


Also we should capitalize "CMA"

**Comment by stwhite91** [comment]
*Original date: 2017-12-06 20:56:29*

---
From Core meeting: we'd like to add a runtime check for CMA support. This should be fixed with high priority, since it breaks all Charm++ programs on some machines.

**Comment by nitbhat** [comment]
*Original date: 2017-12-07 15:18:59*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3381/~~ https://github.com/UIUC-PPL/charm/commit/9f5778579c07774ceeed06773f81f27478305763
