### ISSUE TITLE
objid_t: location cache should be keyed by objid_t

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#175]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/175*

---
A LocMgr keyed by objid_t seems amenable to most situations when an inversion function is known / can be generated. When the user specifies the conversion function, we may require an additional inversion function too. However, we still haven't explored the implications of our distributed lookup model. The design discussions for that effort might veto this task.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:05:52*

---
This won't be ready for 6.6, so push it back.
