### ISSUE TITLE
Add an ampirun script as drop-in replacement for mpiexec

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1766]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1766*

---
configure scripts of libraries often taken a '--with-mpiexec' option that lets you pass a different job launcher, but the number of processes passed to that is often hardcoded as "-n" which charmrun doesn't take. Supply an ampirun wrapper around charmrun that takes -n, -np, and -p alike.

*Options that we could support:*
* -n|-np|-p: total number of ranks (recommended by MPI standard)
* --host: comma-separated list of hosts to run on (as in OpenMPI)
* --vr: Flag to toggle virtual ranks on (use only 1 process per host when this is on; do we need SMP mode for this?)
* --verbose: By default, pass ++quiet to charmrun. With this flag, do not pass ++quiet.
* Other flags recommended by the MPI standard (wdir etc.; maybe not necessary for the first version)

*Script name and location:*
* make this script available as: ampirun, ampiexec, mpirun, mpiexec?
* Ideally, we should copy this to the application directory when compiling (instead of charmrun?)

**Comment by stwhite91** [comment]
*Original date: 2017-12-14 14:55:26*

---
We previously removed an old ampirun script: ~~https://charm.cs.illinois.edu/gerrit/#/c/1176/~~ https://github.com/UIUC-PPL/charm/commit/0e2d6852c8c86147fc2f19f4d9fc24a2927009ec

**Comment by matthiasdiener** [comment]
*Original date: 2018-01-17 23:11:32*

---
WIP patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/3527~~ https://github.com/UIUC-PPL/charm/commit/af1d49185e72b681842517606210ccf31519a964

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-07 18:09:43*

---
This is implemented and needs some reviews.
