### ISSUE TITLE
Clean up incorrect quotation marks in the manuals

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1781]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1781*

---
For some reason, trying to make quotes in the documentation like ``this'' doesn't work. It shows up online exactly like that, but it's used throughout all the manuals.

**Comment by jcphill** [comment]
*Original date: 2018-01-30 19:53:30*

---
What software is generating the online manuals from LaTeX (and doesn't know how to handle quotes)?

**Comment by matthiasdiener** [comment]
*Original date: 2019-04-21 00:38:02*

---
Is this still an issue with the RST manual?
