### ISSUE TITLE
charmrun ++local dies without error message on non-existent program

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1782]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1782*

---
Calling charmrun with a non-existent program produces a useful error message:
```
jim`belfast$/Projects/namd2/charm-6.9.0/netlrts-linux-x86_64-smp-iccstatic/bin/charmrun /foo
Charmrun> scalable start enabled. 
Charmrun remote shell(abijan.0)> Cannot locate this node-program: /foo
Charmrun remote shell(abijan.0)> Exiting with error code 1
Charmrun> Error 1 returned from remote shell (abijan:0)
```
Except with the ++local option:
```
jim`belfast$/Projects/namd2/charm-6.9.0/netlrts-linux-x86_64-smp-iccstatic/bin/charmrun ++local /foo
Charmrun> scalable start enabled. 
Killed

```

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2018-01-26 09:54:02*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3575/~~ https://github.com/UIUC-PPL/charm/commit/d553faa0530a46602ac96036cc3ebbb305971570

The error comes from that after execve in line 5368 returns, indicating that exec was unsuccesful, the following line's fprintf isn't printed.
I tried fflush but does not seem to work.
Instead, before spawning processes in PE's, a quick check is done to see if the program path is valid.
Original error messages are in ssh_script function (line 4507), but this isn't called when ++local option is used.

**Comment by jcphill** [comment]
*Original date: 2018-01-26 15:10:04*

---
Passing a file that is not executable is also handled badly:
```
jim`sunnyvale$/Projects/namd2/charm-6.9.0/netlrts-linux-x86_64-smp-iccstatic/bin/charmrun ++local Make.config  
Charmrun> scalable start enabled. 
Killed
```

We need to figure out why an error message is not displayed.

**Comment by jcphill** [comment]
*Original date: 2018-01-26 17:16:31*

---
Dong Hun Lee wrote:
> ~~https://charm.cs.illinois.edu/gerrit/#/c/3575/~~ https://github.com/UIUC-PPL/charm/commit/d553faa0530a46602ac96036cc3ebbb305971570
> 
> The error comes from that after execve in line 5368 returns, indicating that exec was unsuccesful, the following line's fprintf isn't printed.
> I tried fflush but does not seem to work.
> Instead, before spawning processes in PE's, a quick check is done to see if the program path is valid.
> Original error messages are in ssh_script function (line 4507), but this isn't called when ++local option is used.

See my comments in code review.  The code dups stdout (1) instead of stderr (2).
