### ISSUE TITLE
The manual isn't building correctly / updating online

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1785]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1785*

---
The Charm++ manual and other manuals are not building correctly since 10 days ago according to Jenkins. This means that the online versions are not automatically updating.

http://localhost:8080/job/charm-documentation/

**Comment by matthiasdiener** [comment]
*Original date: 2018-01-30 20:36:47*

---
The build error is:

```
make[1]: Leaving directory '/scratch/jenkins/workspace/charm-documentation/doc/charj'
rm -rf /www/manuals/backup
mkdir -p /www/manuals/backup && \
mv /www/manuals/pdf /www/manuals/html /www/manuals/backup
mkdir: cannot create directory ‘/www’: File exists
Makefile:29: recipe for target 'web' failed
make: *** [web] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

On January 19th (=10 days ago), the filesystem on the build machine (panache) was somehow changed so that `/www` is now a symlink to `/web/www`, which results in the `mkdir` failure shown above:

```
mdiener`panache $ ls -l /www
lrwxrwxrwx 1 root root 8 Jan 19 16:21 /www -> /web/www
mdiener`panache $ mkdir -p /www
mkdir: cannot create directory ‘/www’: File exists

```

**Comment by matthiasdiener** [comment]
*Original date: 2018-01-30 21:15:22*

---
Untested patch here: https://charm.cs.illinois.edu/gerrit/#/c/3591/

**Comment by matthiasdiener** [comment]
*Original date: 2018-01-31 21:18:10*

---
The issue has been fixed on panache. The above patch was not necessary.

**Comment by rbuch** [comment]
*Original date: 2018-01-31 21:37:53*

---
This was caused by /web on panache not being mounted properly for some reason. Running sudo mount /web fixed it.

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 14:27:30*

---
Marking 'Closed' so redmine will remove it from the 'Open' category
