### ISSUE TITLE
ddt dependence missing in AMPI's makefile

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1791]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1791*

---
ddt was moved into AMPI, but there is no dependence on ddt or its header, so if you update DDT and re-make AMPI the build system ignores your changes: ~~https://charm.cs.illinois.edu/gerrit/#/c/3468/~~ https://github.com/UIUC-PPL/charm/commit/d89c19a946162092483b9830a92ab777ae57e638

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-01 20:50:41*

---
This seems to work for me:

```
$ cd charm/tmp/libs/ck-libs/ampi
$ make
AMPI built successfully
AMPIF built successfully
$ touch ddt.C
$ make
/Users/mdiener/Work/charm/bin/charmc  -c ampi.C
/Users/mdiener/Work/charm/bin/charmc  -c ampif.C
[...]
```

Same for ddt.h.

ddt.o and ddt.h should be dependencies through the HEADDEP and OBJS Makefile variables.

**Comment by matthiasdiener** [comment]
*Original date: 2018-02-01 20:58:23*

---
... except that ddt.o does not get rebuilt when ddt.h changes. 
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/3609/~~ https://github.com/UIUC-PPL/charm/commit/aac58f65d3e7cc85d7a2f05341bd08703860bbf9
