### ISSUE TITLE
ARM64 build and stability issues

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1797]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1797*

---
When building on ARM64, the multicore-arm build uses 32-bit version of boost-context library, causing build failure.  The problem this bit in the main build script:

    if test `echo "$BASEVERSION" | grep -c "arm"` -gt 0
    then
      UFCONTEXT_HEADER_NAME="arm_aapcs_${UFCONTEXT_HEADER_NAME}"
    elif test `echo "$BASEVERSION" | grep -c "mips"` -gt 0

After changing the build script to use arm64 it builds successfully, but megatest crashes part way through (it runs to completion with v6.8.2), with Valgrind showing some dodgy stack behaviour. This happens on an Arm Cortex-A57 as well, so it's not specific to ThunderX2.

**Comment by ericjbohm** [comment]
*Original date: 2018-02-21 20:01:04*

---
Someone in NAMD group should take on arm64 support.  Ronak, please reassign as appropriate.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-21 20:37:12*

---
If there is any need for help with testing, I personally own a Raspberry Pi 3 and have an ARM64 installation on an SD card. To my understanding, the uFcontext subtask is the majority of the problem, so when a fix for that is ready I could test it.

**Comment by stwhite91** [comment]
*Original date: 2018-03-15 20:28:05*

---
Patch for uFcontext threads support: ~~https://charm.cs.illinois.edu/gerrit/#/c/3847/~~ https://github.com/UIUC-PPL/charm/commit/43c51a4b11744bc3fea64f18439217ac2a92ee5d

That just needs testing validation

**Comment by stwhite91** [comment]
*Original date: 2018-03-29 20:42:08*

---
Evan confirmed that making context threads the default has fixed the ARM 64-bit builds.
