### ISSUE TITLE
uFcontext thread support for 64-bit ARM systems

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1798]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1798*

---
Jim Philips reported that current charm fails to build because uFcontext threads always picks the 32-bit ARM. There are apparently other issues with this build, but this one should be straightforward.

**Comment by sbak5** [comment]
*Original date: 2018-02-14 21:08:56*

---
Yeah, I didn't consider ARM64 for boost context libraries. So, I expect it can be fixed quickly.

**Comment by sbak5** [comment]
*Original date: 2018-03-14 06:40:30*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3847/~~ https://github.com/UIUC-PPL/charm/commit/43c51a4b11744bc3fea64f18439217ac2a92ee5d

Added configuration directories for ARMv8 processors. 
Except Cortex-A32, all ARMv8 processors supports 64 Bit ISA (AArch64). So, this issue work for most ARMv8 processors. 
For Cortex-A32, maybe arm7 build works.

**Comment by stwhite91** [comment]
*Original date: 2018-03-27 23:08:21*

---
As noted on the gerrit issue, this still isn't passing any tests that use ULTs. Maybe for now just make the default on ARM be not uFcontext

**Comment by stwhite91** [comment]
*Original date: 2018-03-29 20:41:00*

---
Marking this complete for now since we've worked around it by using context threads on ARM8.

There's another issue open for actually getting uFcontext threads to work on ARM8: https://charm.cs.illinois.edu/redmine/issues/1837
