### ISSUE TITLE
Charm++ program segfaults when an element from a nodegroup proxy is used for message passing

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1799]
*Original author: Dong Hun Lee*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1799*

---
In the attached example, when a callback of a reduction for a nodegroup is specified with an element of the nodegroup (instead of the whole nodegroup proxy), the program segfaults, and the variable set in the nodegroup's constructor appears to become corrupted.
Happened using ofi-linux-x86_64-smp and netlrts-linux-x86_64-smp; v6.8.2.

This does not happen when group chares are used or if the whole nodegroup proxy is provided for the callback.

[hello.C](https://github.com/UIUC-PPL/charm/files/3536666/hello.C.txt)
[hello.ci](https://github.com/UIUC-PPL/charm/files/3536667/hello.ci.txt)

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2018-02-14 21:25:31*

---
Originally saw this problem from another application using:

```
<code class="c">
thisProxy[0].someFunction()
</code>
```
where thisProxy is a nodegroup proxy.
But was not able to reproduce this error in an example.

**Comment by rbuch** [comment]
*Original date: 2018-02-15 20:02:33*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3726/~~ https://github.com/UIUC-PPL/charm/commit/fd56d0e06e7f8766393bd5bf208ef6c5c9b9d2a2
