### ISSUE TITLE
Native MPI Interoperability with UGNI

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#18]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/18*

---
Implement interoperability of Charm and MPI on UGNI.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-02 20:14:33*

---
How's the testing look on this? Waiting for reports from the Chombo crew?

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-04 03:30:42*

---
Support for time division has been added. Other support will be dealt in a separate issue.
