### ISSUE TITLE
Section reduction contribute() should accept std::vector

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1800]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1800*

---
We added a new overload for contribute() which accepts a std::vector instead of taking a length and a buffer address. I think the same overload for contributions to section reductions is missing, and should be added for 6.9.0 for completeness and consistency.

~~https://charm.cs.illinois.edu/gerrit/#/c/3277/~~ https://github.com/UIUC-PPL/charm/commit/77378acbfd0ec83e2952267289ff2be3efc29b48

**Comment by stwhite91** [comment]
*Original date: 2018-03-08 20:07:42*

---
Can you link the gerrit patch here? Whenever marking a redmine issue as 'Implemented', we like to have the gerrit fix linked here

**Comment by raghavendrak** [comment]
*Original date: 2018-03-08 20:47:36*

---
gerrit patch:
~~https://charm.cs.illinois.edu/gerrit/#/c/3827/~~ https://github.com/UIUC-PPL/charm/commit/32d325ad4cc35d6fe0af350b7a4d68b0bf24ba5c
