### ISSUE TITLE
performance problem in net-lrts smp build

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#181]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/181*

---
charm net-lrts branch smp build is too slow, which can be observed in /tests/charm++/pingpong. The time difference can be seen from the output, I'm allocating 1 node and 10 cores on Taub.
adding +cpuaffinity does not have a significant effect.

```
[acun2`taub427 pingpong]$* ./charmrun ./pgm +p2 ++ppn 2* 
Charmrun> started all node programs in 1.356 seconds.
Converse/Charm++ Commit ID: v6.5.0-beta1-181-g3998d4a
Trace: traceroot: /home/acun2/charm_lrts/net-linux-x86_64/tests/charm++/pingpong/./pgm
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.004 seconds.
*Pingpong with payload: 100 iterations: 1000
Roundtrip time for 1D Arrays is 169.810057 us
Roundtrip time for 1D threaded Arrays is 209.335089 us*
....
```

while in original charm smp; 

```
[acun2`taub233 pingpong]$ *./charmrun ./pgm +p2 ++ppn 2 * 
Charmrun> started all node programs in 1.363 seconds.
Converse/Charm++ Commit ID: 
Trace: traceroot: /home/acun2/charm/net-linux-x86_64-smp-charm-debug/tests/charm++/pingpong/./pgm
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.003 seconds.
Pingpong with payload: 100 iterations: 1000
*Roundtrip time for 1D Arrays is 5.687952 us
Roundtrip time for 1D threaded Arrays is 12.612820 us*
.....

```

**Comment by nikhil-jain** [comment]
*Original date: 2013-04-30 07:30:14*

---
I checked in a fix for this - the progress engine to initiate sending of message was not being called after the message send; also the server was being polled only for available messages; both these were contributing significantly to pert loss. Bilge - please confirm if the fix works on Taub, lab machines and other platforms.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-15 16:44:24*

---
Assuming the relevant performance checks were done 3 months ago, please say so and mark this issue 'closed'.

Thanks.

**Comment by bilgeacun** [comment]
*Original date: 2013-08-15 16:50:05*

---
Yes, this issue is solved.
