### ISSUE TITLE
charmc option "-ld" to specify linker conflicts with passing "-ld" to link libd.so

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#1812]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1812*

---
Any program that uses dlopen() will need to link with libd.so by passing `-ld` to the linker. However, charmc has options "-ld" and "-ld++" for overriding $CMK_LD and $CMK_LDXX respectively.

I can only recommend removing charmc's -ld and -ld++ options, or renaming them to something else. Maybe -override-ld and -override-ld++.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-22 16:31:54*

---
https://charm.cs.illinois.edu/gerrit/3761

**Comment by jcphill** [comment]
*Original date: 2018-02-22 22:16:28*

---
I think you can do this with "-ld++-option -ld".

**Comment by jcphill** [comment]
*Original date: 2018-02-22 22:22:19*

---
Also, don't you need to link with libdl, not libd?
