### ISSUE TITLE
New path to zlib on ALCF BG/Q machines

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#182]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/182*

---
From ALCF Support:
> ***Supported Version of ZLIB Available***
> ZLIB, a general purpose compression library, is part of the supported packages on Mira, Cetus, and Vesta. It can be found at `/soft/libraries/alcf/current/{xl,gcc}/ZLIB/`. The last version installed is 1.2.7. The directory on `/soft/libraries/unsupported/zlib-1.2.6` will be deleted during the next maintenance period to avoid confusion. Please update your links and paths to use the supported version of this package.

Please update the arch files for BGQ as necessary to reflect the new location of zlib and test that it's detected and working appropriately.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-12 13:38:12*

---
Bump urgency and due date, because the old path will be broken on Monday.

**Comment by nikhil-jain** [comment]
*Original date: 2013-04-14 01:14:32*

---
This may be a noop since we do not use ZLIB implicitly on BGQ in our paths due to correctness issues.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-14 01:16:41*

---
Are you referring to #71? I fixed that a month ago.

**Comment by nikhil-jain** [comment]
*Original date: 2013-04-14 01:20:03*

---
I am not sure if the cause of crash on BGQ was the same as #71. Irrespective of that, the current paths on BGQ don't include the path to ZLIB. So in essence this task is now to test if Charm works with current version of ZLIB on BGQ, and based on that fix the ZLIB path if needed.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-16 16:43:14*

---
Yanhua, please test that the new libraries and updated code properly generate compressed projections logs without crashes. We should not have such a large system defaulting to generating needlessly huge output.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-17 05:14:32*

---
I  modified conv-mach.sh to use current zlib path, this works.  Projections generates .gz files.
However the point is that zlib for gcc/xlc is in different directory.  I tried to add to cc-xlc.sh cc-gcc.sh
this does not work.

**Comment by nikhil-jain** [comment]
*Original date: 2013-04-17 15:59:30*

---
An additional cc-gcc is not needed. The entries from conv-mach.sh are used in default case. If they need to be overwritten (for example when using xlc), cc-xlc.sh should contains the new exports.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-18 20:28:50*

---
I added the correct path to cc-xlc.sh, also overwrite the _INC and _LIB variable to use new path.   It is checked in. I tested for xlc on NQueen program, it works.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-18 20:29:54*

---
Does the same change need to be made for the mpi-bluegeneq builds?

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-19 15:58:39*

---
Same changes are also applied to mpi-bgq too now.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-23 21:17:15*

---
Tested working and cherry-picked to the stable branch. Thanks!
