### ISSUE TITLE
Zerocopy examples don't compile on windows builds and fail autobuild

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1824]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1824*

---

```

make[5]: Entering directory '/home/nikhil/autobuild/multicore-win-x86_64/charm/multicore-win-x86_64/examples/charm++/zerocopy/direct_api/simple_rget'
../../../../../bin/charmc -optimize -production   simple_rget.ci
touch cifiles
../../../../../bin/charmc -optimize -production  -c simple_rget.C
simple_rget.C
simple_rget.C(62): error C2229: class 'Ping1' has an illegal zero-sized array
simple_rget.C(63): error C2229: class 'Ping1' has an illegal zero-sized array
simple_rget.C(175): error C2229: class 'Ping1' has an illegal zero-sized array
```

The error reporting by the compiler is incorrect. The zero-sized array is the 
```
char layerInfo[CMK_NOCOPY_DIRECT_BYTES]
```
 which defaults to 
```
char layerInfo[0]
```
 inside ckrdma.h causing the C2229 error (https://msdn.microsoft.com/en-us/library/0scy7z2d.aspx)

**Comment by nitbhat** [comment]
*Original date: 2018-03-07 22:47:20*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/3821/~~ https://github.com/UIUC-PPL/charm/commit/681b2ce4949fd277b2b279ea89cf7b65fae8dfa7

**Comment by stwhite91** [comment]
*Original date: 2018-03-08 02:45:05*

---
Separately we'll want to cut down the run time of the pingpong example byt skipping over some sizes and decreasing the number of iterations.
