### ISSUE TITLE
Additions to commbench cause segfaults on many platforms

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#183]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/183*

---
Mostly SMP builds, but some single-threaded builds as well. cf. autobuild.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-13 16:41:23*

---
It is caused by cpv variable not initialized. I checked in  a fix and tested on net smp. It worked.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-13 16:43:08*

---
Will close when autobuild passes these tomorrow.
