### ISSUE TITLE
ChaNGa deadlocks due to recent change to QD types

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#1830]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1830*

---
I'm getting a deadlock when running ChaNGa with recent versions of charm.  "git bisect" says that the problem commit is:
commit 3137ae773a8af5bd476beafaeee4dabd168062bd
Change-Id: I2aed14aac27ea12b7f5680a602671f95bc78910d
QD: Convert to use more suitable types

Hence I suspect a race condition after moving from ints to CmiUInt8 for the QD counters.

Charm is built with:
./build ChaNGa gni-crayxc hugepages smp -j8 --with-production
using gcc 7.1.0.

**Comment by stwhite91** [comment]
*Original date: 2018-03-13 03:02:52*

---
Does this patch fix the problem? ~~https://charm.cs.illinois.edu/gerrit/#/c/3844/~~ https://github.com/UIUC-PPL/charm/commit/42ce6c964d9b0bea889e5e18a48b61c383ee60c6

**Comment by trquinn** [comment]
*Original date: 2018-03-13 20:29:10*

---
I tried changeset 3844, and I still get the hang.

**Comment by stwhite91** [comment]
*Original date: 2018-03-13 23:49:19*

---
But reverting 2897 makes the problem go away?

~~https://charm.cs.illinois.edu/gerrit/#/c/2897/~~ https://github.com/UIUC-PPL/charm/commit/3137ae773a8af5bd476beafaeee4dabd168062bd

**Comment by trquinn** [comment]
*Original date: 2018-03-14 04:21:40*

---
The problem goes away if I run with commit 8de6719c613f34a3d6b1baccb9aa4aa8f78c12db, the commit before 2897.

**Comment by stwhite91** [comment]
*Original date: 2018-03-14 15:33:00*

---
K we can just revert that change for now then, since I'm not sure how that is causing a problem and it's an easy one to revert.

**Comment by stwhite91** [comment]
*Original date: 2018-03-14 15:35:04*

---
Revert commit: https://charm.cs.illinois.edu/gerrit/#/c/3848/

**Comment by stwhite91** [comment]
*Original date: 2018-03-14 15:48:08*

---
Could you provide the run command for ChaNGa that reproduces the deadlock? In case we want to pursue the datatype change in the future, we'll need to be able to run this case

**Comment by stwhite91** [comment]
*Original date: 2018-03-14 20:25:25*

---
Actually, we found another issue in the original patch, I updated this patch to fix that. Can you try ChaNGa on the updated version of this patch? ~~https://charm.cs.illinois.edu/gerrit/#/c/3844/~~ https://github.com/UIUC-PPL/charm/commit/42ce6c964d9b0bea889e5e18a48b61c383ee60c6

**Comment by trquinn** [comment]
*Original date: 2018-03-15 01:20:58*

---
Commit 6b1b6d708 fixes the problem.
