### ISSUE TITLE
Shrink/expand broken by charmrun refactoring

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1831]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1831*

---
Trying to build with '--enable-shrinkexpand' fails on compiling charmrun with the following on netlrts-darwin-x86_64:

```
../../bin/charmc -g -O0  -Wno-error -lm -I.. -L../libs -c -seq -DCMK_NOT_USE_CONVERSE=1 charmrun.C -o charmrun.o
charmrun.C:4300:23: error: use of undeclared identifier 'nodetab_size'
  for (int i = 0; i < nodetab_size; i++)
                      ^
charmrun.C:4301:38: error: use of undeclared identifier 'nodetab_table'; did you mean 'host_table'?
    sprintf(dest1, "%s %s", dest1, (*nodetab_table[i]).name);
                                     ^~~~~~~~~~~~~
                                     host_table
charmrun.C:1352:36: note: 'host_table' declared here
static std::vector<nodetab_host *> host_table;

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-15 18:50:47*

---
~~https://charm.cs.illinois.edu/gerrit/3860~~ https://github.com/UIUC-PPL/charm/commit/f4a930ca908299ce7a7108a51794e0639416fefb

Are there any tests for shrink/expand?

**Comment by stwhite91** [comment]
*Original date: 2018-03-15 18:53:04*

---
examples/charm++/shrink_expand. It doesn't look like it's part of automated testing

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-15 19:12:44*

---
The example crashes. I will have to debug this.

**Comment by stwhite91** [comment]
*Original date: 2018-03-15 19:50:57*

---
k, since it doesn't have automated testing it may have been broken for a while now. Though I believe we tested it for v6.8.0's release.

**Comment by evan-charmworks** [comment]
*Original date: 2018-03-26 19:55:07*

---
Fixed in: ~~https://charm.cs.illinois.edu/gerrit/3900~~ https://github.com/UIUC-PPL/charm/commit/8adeaba44208b5730883effc55bdd559fa7720d8

Tested with netlrts-darwin-x86_64 and netlrts-linux-x86_64.
