### ISSUE TITLE
PAMI LRTS performance using ppn 64 is worse than that with PAMI

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#184]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/184*

---
When I compared NAMD Apoa1 performance on 64 nodes,  i found that PAMI LRTS is about 30% slower than PAMI using ppn 64. 
If using ppn 16, performance is close.

This can be reproduced by running Apoa1 PME every 4 steps.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 18:52:30*

---
Any progress on this?

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-20 21:23:19*

---
This may be in part due to superior L2 Atomics based mutex used by pami, though 30% is a lot. Follow #443 to see why it is difficult to port that feature.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-16 21:38:52*

---
We should find more people to work on machine layers. Nowadays all uGNI and PAMI problem go to me.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-02-19 22:50:08*

---
Just tested today for PPN 64 with PAMI SMP , PAMI LRTS SMP. It turns out that the performance in two cases is almost same.
Timestep is 21ms. 
  Here is the command 

runjob -p 1 -n 64 --block $COBALT_PARTNAME --verbose=INFO --envs BG_SHAREDMEMSIZE=32MB --envs PAMID_VERBOSE=1  : /home/jessie/NAMD/namd2/BlueGeneQ-xlC.smp.pami/namd2   /home/jessie/NAMD/data/apoa1/apoa1.namd +ppn 64  > o.log.64node.ppn64.pami.smp

runjob -p 1 -n 64 --block $COBALT_PARTNAME --verbose=INFO --envs BG_SHAREDMEMSIZE=32MB --envs PAMID_VERBOSE=1  : /home/jessie/NAMD/namd2/BlueGeneQ-xlC.smp.lrts/namd2   /home/jessie/NAMD/data/apoa1/apoa1.namd +ppn 64  > o.log.64node.ppn64.lrts.smp

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 05:33:43*

---
This is really old and seems to not have been reproduced
