### ISSUE TITLE
Add -Werror=vla to Jenkins per-commit builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1841]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1841*

---
This was done a year ago, but has apparently been undone sometime since then: https://charm.cs.illinois.edu/redmine/issues/1496

**Comment by nitbhat** [comment]
*Original date: 2018-04-04 16:45:36*

---
Added it to non-smp build - charm-commit-triggered and smp build - test-charm-smp.
