### ISSUE TITLE
Make multicore charmrun parse all arguments

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1848]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1848*

---
Currently the multicore version of charmrun only parses arguments until it hits one that doesn't start with a '+'. That means if you do './charmrun +p8 ./pgm <program_args_here> ++local ++quiet' the '++local' and '++quiet' are ignored. This is inconsistent with other builds of Charm++, which parse all args.

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-06 22:31:08*

---
~~https://charm.cs.illinois.edu/gerrit/3961~~ https://github.com/UIUC-PPL/charm/commit/fbda322dc9d9058ccec470cb72b476f58a2c1bd6
