### ISSUE TITLE
provide backup implementations of std::unordered containers

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#185]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/185*

---
There are several locations in the charm runtime where hashtables are used, or are sorely needed. We do have a homegrown CkHashTable from the pre-stl era, but the future-friendly solution is to use one of the std::unordered_{map, set, multimap, multiset} containers. These should already be widely available on the current generation of machines / compilers.

However as support for c++11 is not yet universal or complete, we need to test for the availability of these stl containers, and provide backup implementations if they are not available. Our configure infrastructure is the correct place to test for this. Consider using the unordered container implementations from dependable sources like gcc or boost as the drop-in backup.

**Comment by heyram** [comment]
*Original date: 2013-04-20 05:17:52*

---
For eg: one use case is in CkMulticastMgr::setup(). We've replaced the original O(N) array with a std::map (where N = numPEs). However, if the section spans O(N) processors, then this map will have a total cost of O(N logN) instead of linear cost! Ideally, we need a hashtable here instead of a map. See 796696fc for the (hopefully) temporary fix that uses std::map.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-03 20:26:07*

---
Per core meeting discussion, we should test for vendor-provided implementations in the configure script. If there's no implementation of a particular container, use an integrated copy of Boost's implementation instead.

**Comment by ericjbohm** [comment]
*Original date: 2013-07-01 21:09:00*

---
Import into ck namespace based on availability.

**Comment by lifflander** [comment]
*Original date: 2013-07-03 00:42:28*

---
By some quick inspection, I have found a couple things:

1) The boost implementation is tied fairly heavily to other boost-specific features and functions, although it does implement the standard tr1 spec for unordered_{map,set,multiset}. Note that extracting it from boost will be a little involved.
2) Many of the performance comparisons online (some from a year or two ago), show that boost massively outperforms STL implementations (it seems one factor is the hash function implementation in boost is fair superior)

More suggestions on how to proceed with this?

**Comment by heyram** [comment]
*Original date: 2013-07-05 18:31:09*

---
Jonathan Lifflander wrote:
> By some quick inspection, I have found a couple things:
> 
> 1) The boost implementation is tied fairly heavily to other boost-specific features and functions, although it does implement 
> the standard tr1 spec for unordered_{map,set,multiset}. Note that extracting it from boost will be a little involved.

I guess I was not clear in the meeting, but this is what I meant when I said it might difficult to extract these containers from boost.

> 2) Many of the performance comparisons online (some from a year or two ago), show that boost massively outperforms STL implementations (it seems one factor is the hash function implementation in boost is fair superior)

boost container performance may be much better, but we will need it _only_ if the default cpp library does not provide one. Most recent hpc systems seem to have sensibly modern compilers. And all the compilers that I checked (intel, ibm, gnu, clang) seem to support unordered containers even if their support for the rest of c++11 is incomplete / sketchy. My opinion is we find the most easily reused implementation and absorb it. We can always switch under the covers later (if needed).

**Comment by lifflander** [comment]
*Original date: 2013-07-23 07:39:51*

---
boost dependencies for <boost/unordered_map>:

"/opt/local/include/boost/aligned_storage.hpp"
"/opt/local/include/boost/assert.hpp"
"/opt/local/include/boost/config.hpp"
"/opt/local/include/boost/config/compiler/gcc.hpp"
"/opt/local/include/boost/config/no_tr1/cmath.hpp"
"/opt/local/include/boost/config/platform/macos.hpp"
"/opt/local/include/boost/config/posix_features.hpp"
"/opt/local/include/boost/config/select_compiler_config.hpp"
"/opt/local/include/boost/config/select_platform_config.hpp"
"/opt/local/include/boost/config/suffix.hpp"
"/opt/local/include/boost/config/user.hpp"
"/opt/local/include/boost/cstdint.hpp"
"/opt/local/include/boost/current_function.hpp"
"/opt/local/include/boost/detail/container_fwd.hpp"
"/opt/local/include/boost/detail/iterator.hpp"
"/opt/local/include/boost/detail/select_type.hpp"
"/opt/local/include/boost/detail/workaround.hpp"
"/opt/local/include/boost/exception/detail/attribute_noreturn.hpp"
"/opt/local/include/boost/exception/exception.hpp"
"/opt/local/include/boost/functional/hash.hpp"
"/opt/local/include/boost/functional/hash/detail/container_fwd_0x.hpp"
"/opt/local/include/boost/functional/hash/detail/float_functions.hpp"
"/opt/local/include/boost/functional/hash/detail/hash_float.hpp"
"/opt/local/include/boost/functional/hash/detail/limits.hpp"
"/opt/local/include/boost/functional/hash/extensions.hpp"
"/opt/local/include/boost/functional/hash/hash.hpp"
"/opt/local/include/boost/functional/hash/hash_fwd.hpp"
"/opt/local/include/boost/functional/hash_fwd.hpp"
"/opt/local/include/boost/integer/static_log2.hpp"
"/opt/local/include/boost/integer_fwd.hpp"
"/opt/local/include/boost/iterator.hpp"
"/opt/local/include/boost/iterator/detail/config_def.hpp"
"/opt/local/include/boost/iterator/detail/config_undef.hpp"
"/opt/local/include/boost/iterator/iterator_categories.hpp"
"/opt/local/include/boost/limits.hpp"
"/opt/local/include/boost/move/move.hpp"
"/opt/local/include/boost/mpl/arg.hpp"
"/opt/local/include/boost/mpl/arg_fwd.hpp"
"/opt/local/include/boost/mpl/aux_/adl_barrier.hpp"
"/opt/local/include/boost/mpl/aux_/arg_typedef.hpp"
"/opt/local/include/boost/mpl/aux_/arity.hpp"
"/opt/local/include/boost/mpl/aux_/arity_spec.hpp"
"/opt/local/include/boost/mpl/aux_/config/adl.hpp"
"/opt/local/include/boost/mpl/aux_/config/compiler.hpp"
"/opt/local/include/boost/mpl/aux_/config/ctps.hpp"
"/opt/local/include/boost/mpl/aux_/config/dtp.hpp"
"/opt/local/include/boost/mpl/aux_/config/eti.hpp"
"/opt/local/include/boost/mpl/aux_/config/gcc.hpp"
"/opt/local/include/boost/mpl/aux_/config/integral.hpp"
"/opt/local/include/boost/mpl/aux_/config/intel.hpp"
"/opt/local/include/boost/mpl/aux_/config/lambda.hpp"
"/opt/local/include/boost/mpl/aux_/config/msvc.hpp"
"/opt/local/include/boost/mpl/aux_/config/nttp.hpp"
"/opt/local/include/boost/mpl/aux_/config/overload_resolution.hpp"
"/opt/local/include/boost/mpl/aux_/config/preprocessor.hpp"
"/opt/local/include/boost/mpl/aux_/config/static_constant.hpp"
"/opt/local/include/boost/mpl/aux_/config/ttp.hpp"
"/opt/local/include/boost/mpl/aux_/config/use_preprocessed.hpp"
"/opt/local/include/boost/mpl/aux_/config/workaround.hpp"
"/opt/local/include/boost/mpl/aux_/include_preprocessed.hpp"
"/opt/local/include/boost/mpl/aux_/integral_wrapper.hpp"
"/opt/local/include/boost/mpl/aux_/lambda_arity_param.hpp"
"/opt/local/include/boost/mpl/aux_/lambda_support.hpp"
"/opt/local/include/boost/mpl/aux_/na.hpp"
"/opt/local/include/boost/mpl/aux_/na_assert.hpp"
"/opt/local/include/boost/mpl/aux_/na_fwd.hpp"
"/opt/local/include/boost/mpl/aux_/na_spec.hpp"
"/opt/local/include/boost/mpl/aux_/nttp_decl.hpp"
"/opt/local/include/boost/mpl/aux_/preprocessor/def_params_tail.hpp"
"/opt/local/include/boost/mpl/aux_/preprocessor/enum.hpp"
"/opt/local/include/boost/mpl/aux_/preprocessor/params.hpp"
"/opt/local/include/boost/mpl/aux_/static_cast.hpp"
"/opt/local/include/boost/mpl/aux_/template_arity_fwd.hpp"
"/opt/local/include/boost/mpl/aux_/value_wknd.hpp"
"/opt/local/include/boost/mpl/bool.hpp"
"/opt/local/include/boost/mpl/bool_fwd.hpp"
"/opt/local/include/boost/mpl/eval_if.hpp"
"/opt/local/include/boost/mpl/identity.hpp"
"/opt/local/include/boost/mpl/if.hpp"
"/opt/local/include/boost/mpl/int.hpp"
"/opt/local/include/boost/mpl/int_fwd.hpp"
"/opt/local/include/boost/mpl/integral_c.hpp"
"/opt/local/include/boost/mpl/integral_c_fwd.hpp"
"/opt/local/include/boost/mpl/integral_c_tag.hpp"
"/opt/local/include/boost/mpl/lambda_fwd.hpp"
"/opt/local/include/boost/mpl/limits/arity.hpp"
"/opt/local/include/boost/mpl/placeholders.hpp"
"/opt/local/include/boost/mpl/size_t.hpp"
"/opt/local/include/boost/mpl/size_t_fwd.hpp"
"/opt/local/include/boost/mpl/void_fwd.hpp"
"/opt/local/include/boost/pointer_to_other.hpp"
"/opt/local/include/boost/preprocessor/arithmetic/add.hpp"
"/opt/local/include/boost/preprocessor/arithmetic/dec.hpp"
"/opt/local/include/boost/preprocessor/arithmetic/inc.hpp"
"/opt/local/include/boost/preprocessor/arithmetic/sub.hpp"
"/opt/local/include/boost/preprocessor/cat.hpp"
"/opt/local/include/boost/preprocessor/comma_if.hpp"
"/opt/local/include/boost/preprocessor/config/config.hpp"
"/opt/local/include/boost/preprocessor/control/detail/while.hpp"
"/opt/local/include/boost/preprocessor/control/expr_iif.hpp"
"/opt/local/include/boost/preprocessor/control/if.hpp"
"/opt/local/include/boost/preprocessor/control/iif.hpp"
"/opt/local/include/boost/preprocessor/control/while.hpp"
"/opt/local/include/boost/preprocessor/dec.hpp"
"/opt/local/include/boost/preprocessor/detail/auto_rec.hpp"
"/opt/local/include/boost/preprocessor/detail/check.hpp"
"/opt/local/include/boost/preprocessor/detail/is_binary.hpp"
"/opt/local/include/boost/preprocessor/empty.hpp"
"/opt/local/include/boost/preprocessor/facilities/empty.hpp"
"/opt/local/include/boost/preprocessor/facilities/identity.hpp"
"/opt/local/include/boost/preprocessor/facilities/overload.hpp"
"/opt/local/include/boost/preprocessor/identity.hpp"
"/opt/local/include/boost/preprocessor/inc.hpp"
"/opt/local/include/boost/preprocessor/list/adt.hpp"
"/opt/local/include/boost/preprocessor/list/append.hpp"
"/opt/local/include/boost/preprocessor/list/detail/fold_left.hpp"
"/opt/local/include/boost/preprocessor/list/detail/fold_right.hpp"
"/opt/local/include/boost/preprocessor/list/fold_left.hpp"
"/opt/local/include/boost/preprocessor/list/fold_right.hpp"
"/opt/local/include/boost/preprocessor/list/for_each_i.hpp"
"/opt/local/include/boost/preprocessor/list/reverse.hpp"
"/opt/local/include/boost/preprocessor/list/transform.hpp"
"/opt/local/include/boost/preprocessor/logical/and.hpp"
"/opt/local/include/boost/preprocessor/logical/bitand.hpp"
"/opt/local/include/boost/preprocessor/logical/bool.hpp"
"/opt/local/include/boost/preprocessor/logical/compl.hpp"
"/opt/local/include/boost/preprocessor/punctuation/comma.hpp"
"/opt/local/include/boost/preprocessor/punctuation/comma_if.hpp"
"/opt/local/include/boost/preprocessor/repeat.hpp"
"/opt/local/include/boost/preprocessor/repetition/detail/for.hpp"
"/opt/local/include/boost/preprocessor/repetition/enum.hpp"
"/opt/local/include/boost/preprocessor/repetition/enum_binary_params.hpp"
"/opt/local/include/boost/preprocessor/repetition/enum_params.hpp"
"/opt/local/include/boost/preprocessor/repetition/for.hpp"
"/opt/local/include/boost/preprocessor/repetition/repeat.hpp"
"/opt/local/include/boost/preprocessor/repetition/repeat_from_to.hpp"
"/opt/local/include/boost/preprocessor/seq/enum.hpp"
"/opt/local/include/boost/preprocessor/seq/size.hpp"
"/opt/local/include/boost/preprocessor/stringize.hpp"
"/opt/local/include/boost/preprocessor/tuple/eat.hpp"
"/opt/local/include/boost/preprocessor/tuple/elem.hpp"
"/opt/local/include/boost/preprocessor/tuple/rem.hpp"
"/opt/local/include/boost/preprocessor/tuple/to_list.hpp"
"/opt/local/include/boost/preprocessor/variadic/elem.hpp"
"/opt/local/include/boost/preprocessor/variadic/size.hpp"
"/opt/local/include/boost/ref.hpp"
"/opt/local/include/boost/static_assert.hpp"
"/opt/local/include/boost/swap.hpp"
"/opt/local/include/boost/throw_exception.hpp"
"/opt/local/include/boost/tuple/detail/tuple_basic.hpp"
"/opt/local/include/boost/tuple/tuple.hpp"
"/opt/local/include/boost/type_traits/add_const.hpp"
"/opt/local/include/boost/type_traits/add_cv.hpp"
"/opt/local/include/boost/type_traits/add_lvalue_reference.hpp"
"/opt/local/include/boost/type_traits/add_pointer.hpp"
"/opt/local/include/boost/type_traits/add_reference.hpp"
"/opt/local/include/boost/type_traits/add_rvalue_reference.hpp"
"/opt/local/include/boost/type_traits/add_volatile.hpp"
"/opt/local/include/boost/type_traits/aligned_storage.hpp"
"/opt/local/include/boost/type_traits/alignment_of.hpp"
"/opt/local/include/boost/type_traits/broken_compiler_spec.hpp"
"/opt/local/include/boost/type_traits/config.hpp"
"/opt/local/include/boost/type_traits/cv_traits.hpp"
"/opt/local/include/boost/type_traits/detail/bool_trait_def.hpp"
"/opt/local/include/boost/type_traits/detail/bool_trait_undef.hpp"
"/opt/local/include/boost/type_traits/detail/cv_traits_impl.hpp"
"/opt/local/include/boost/type_traits/detail/false_result.hpp"
"/opt/local/include/boost/type_traits/detail/ice_and.hpp"
"/opt/local/include/boost/type_traits/detail/ice_eq.hpp"
"/opt/local/include/boost/type_traits/detail/ice_not.hpp"
"/opt/local/include/boost/type_traits/detail/ice_or.hpp"
"/opt/local/include/boost/type_traits/detail/is_function_ptr_helper.hpp"
"/opt/local/include/boost/type_traits/detail/is_mem_fun_pointer_tester.hpp"
"/opt/local/include/boost/type_traits/detail/size_t_trait_def.hpp"
"/opt/local/include/boost/type_traits/detail/size_t_trait_undef.hpp"
"/opt/local/include/boost/type_traits/detail/template_arity_spec.hpp"
"/opt/local/include/boost/type_traits/detail/type_trait_def.hpp"
"/opt/local/include/boost/type_traits/detail/type_trait_undef.hpp"
"/opt/local/include/boost/type_traits/detail/yes_no_type.hpp"
"/opt/local/include/boost/type_traits/function_traits.hpp"
"/opt/local/include/boost/type_traits/ice.hpp"
"/opt/local/include/boost/type_traits/integral_constant.hpp"
"/opt/local/include/boost/type_traits/intrinsics.hpp"
"/opt/local/include/boost/type_traits/is_abstract.hpp"
"/opt/local/include/boost/type_traits/is_arithmetic.hpp"
"/opt/local/include/boost/type_traits/is_array.hpp"
"/opt/local/include/boost/type_traits/is_class.hpp"
"/opt/local/include/boost/type_traits/is_const.hpp"
"/opt/local/include/boost/type_traits/is_convertible.hpp"
"/opt/local/include/boost/type_traits/is_empty.hpp"
"/opt/local/include/boost/type_traits/is_enum.hpp"
"/opt/local/include/boost/type_traits/is_float.hpp"
"/opt/local/include/boost/type_traits/is_function.hpp"
"/opt/local/include/boost/type_traits/is_integral.hpp"
"/opt/local/include/boost/type_traits/is_lvalue_reference.hpp"
"/opt/local/include/boost/type_traits/is_member_pointer.hpp"
"/opt/local/include/boost/type_traits/is_pod.hpp"
"/opt/local/include/boost/type_traits/is_pointer.hpp"
"/opt/local/include/boost/type_traits/is_reference.hpp"
"/opt/local/include/boost/type_traits/is_rvalue_reference.hpp"
"/opt/local/include/boost/type_traits/is_same.hpp"
"/opt/local/include/boost/type_traits/is_scalar.hpp"
"/opt/local/include/boost/type_traits/is_union.hpp"
"/opt/local/include/boost/type_traits/is_void.hpp"
"/opt/local/include/boost/type_traits/is_volatile.hpp"
"/opt/local/include/boost/type_traits/remove_const.hpp"
"/opt/local/include/boost/type_traits/remove_cv.hpp"
"/opt/local/include/boost/type_traits/remove_reference.hpp"
"/opt/local/include/boost/type_traits/remove_volatile.hpp"
"/opt/local/include/boost/type_traits/type_with_alignment.hpp"
"/opt/local/include/boost/unordered/detail/allocate.hpp"
"/opt/local/include/boost/unordered/detail/buckets.hpp"
"/opt/local/include/boost/unordered/detail/equivalent.hpp"
"/opt/local/include/boost/unordered/detail/extract_key.hpp"
"/opt/local/include/boost/unordered/detail/fwd.hpp"
"/opt/local/include/boost/unordered/detail/table.hpp"
"/opt/local/include/boost/unordered/detail/unique.hpp"
"/opt/local/include/boost/unordered/detail/util.hpp"
"/opt/local/include/boost/unordered/unordered_map.hpp"
"/opt/local/include/boost/unordered/unordered_map_fwd.hpp"
"/opt/local/include/boost/unordered_map.hpp"
"/opt/local/include/boost/utility/addressof.hpp"
"/opt/local/include/boost/utility/enable_if.hpp"
"/opt/local/include/boost/utility/swap.hpp"

**Comment by PhilMiller** [comment]
*Original date: 2013-07-23 19:28:47*

---
Just after you pushed through figuring that out, I came across this: http://www.meetingcpp.com/index.php/br/items/boost-dependency-analyzer.html

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 19:23:44*

---
Instead of trying to incorporate boost, please add a configure test for the availability of boost, std, and tr1 implementations of these containers, and mechanisms to invoke the one selected.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-23 19:16:51*

---
We don't care about supporting platforms that are so far behind C++11 any more. The only one of concern was XL (possibly only on BGQ), and we're just consigning that to using `std::map` instead.
