### ISSUE TITLE
Keep track of entry method template arguments in traces for Projections

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1856]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1856*

---
We currently don't record the template arguments of entry methods in traces for Projections, so if you have two 'entry void foo<int>(int x)' and 'entry void foo<double>(double x)' then they show up as the same in Projections.

**Comment by stwhite91** [comment]
*Original date: 2018-04-13 16:01:50*

---
This would be great to have for 6.9.0, but I don't think we should block the release on it.

**Comment by rbuch** [comment]
*Original date: 2018-10-10 22:47:57*

---
I've implemented a version of this using RTTI to get the type information. It works, but the values it gets are somewhat mangled and I don't think there's any guarantee that they're meaningful, so I'm not sure if it's a fully satisfactory solution. The code is on the ronak/entryTemplateProjections branch and at ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4682/~~ https://github.com/UIUC-PPL/charm/commit/5ecb13e3c03ff514fd589879c63e77860f0199ed.
