### ISSUE TITLE
Chare constructors cannot take noncopyable types as arguments

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1861]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1861*

---
Currently chare constructors take their arguments by const l-value reference, which prohibits passing non-copyable types to them. Instead they should take their arguments by value and std::move internally, to allow users to std::move the arguments.

Spectre currently has to work around this by editing our generated headers. They do so here: 

spectre/cmake/SetupCharmModuleFunctions.cmake (line 33) does the modification.

build/src/Parallel/ConstGlobalCache.def.h is the generated and edited file.

This same file contains other uses of std::move on types after they are deserialized for efficiency, that we should also take into mainline charm.

This file also contains more uses of std::move similarly: build/src/Parallel/Algorithms/ArrayAlgorithm.def.h

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-13 18:17:03*

---
Wouldn't taking them by value defeat the purpose of std::move?

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-20 18:32:31*

---
~~https://charm.cs.illinois.edu/gerrit/3263~~ https://github.com/UIUC-PPL/charm/commit/fc7869098f86ab81d1c8fa1f9e18bb9aa4cf08f8
~~https://charm.cs.illinois.edu/gerrit/3472~~ https://github.com/UIUC-PPL/charm/commit/f47e4ffc942fdf4d9d3c2e87e8aa2a6be50bfc25
