### ISSUE TITLE
cygpath: not found on non-Windows builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1869]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1869*

---
Introduced here: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3928/~~ https://github.com/UIUC-PPL/charm/commit/9526f130a86695b26173153ada6fae1cd552533a
```
../bin/charmc -intrinsic -optimize -production   mpi-mainmodule.ci && touch mpi-mainmodule.ci.stamp
/bin/sh: 1: cygpath: not found
make[1]: Nothing to be done for 'charmxi'.
make[1]: Leaving directory '/scratch/autobuild/net-pedantic/charm/netlrts-linux-x86_64-pedantic/tmp'
make headerlinks
make[1]: Entering directory '/scratch/autobuild/net-pedantic/charm/netlrts-linux-x86_64-pedantic/tmp'
Soft-linking headers...

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-17 20:12:14*

---
~~https://charm.cs.illinois.edu/gerrit/4013~~ https://github.com/UIUC-PPL/charm/commit/ce4a26ade1ad992553a2ccf4969126f760e3ffdc
