### ISSUE TITLE
Move performance tests and benchmarks from "make test" to a new "make benchmark"

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#1872]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1872*

---
A non-trivial portion of "make test" jobs is spent on performance testing. These tests should be moved to a separate "make benchmark" so that automated unit and integration testing can complete more quickly.

**Comment by stwhite91** [comment]
*Original date: 2018-04-18 16:21:23*

---
And at least some of the results of "make benchmark" should be plotted online somewhere every night based on some of the autobuilds whose performance we care about tracking. It would be useful for diagnosing performance regressions. We already do this for netlrts charm++ pingpong on the PPL wiki page.

I would want example/ampi/pingpong and tests/charm++/pingpong at a minimum. Potentially some reduction/broadcast tests, Converse/LRTS tests, and maybe some example programs to all have that.

This could be a good Charmworks intern task.

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-10 19:05:40*

---
https://charm.cs.illinois.edu/gerrit/4218

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-02 18:49:16*

---
We should merge the 6.10-targeted Zero Copy patches, and as many other patches under review that add new tests/examples as possible, before I proceed with this reorganization.
