### ISSUE TITLE
No rule to make target `charmrun', needed by `charmrun-target'

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1877]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1877*

---
When building Charm with -j16 or above on my Macbook I sometimes get this build error:
```
( /Applications/Xcode.app/Contents/Developer/usr/bin/make -C hwloc )
make: *** No rule to make target `charmrun', needed by `charmrun-target'.  Stop.
make: *** Waiting for unfinished jobs....

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-19 18:16:26*

---
Sam, could you see if this helps? ~~https://charm.cs.illinois.edu/gerrit/4031~~ https://github.com/UIUC-PPL/charm/commit/c0af46355417bed9e794bcdc33d0184df6dfd28d

**Comment by stwhite91** [comment]
*Original date: 2018-04-19 18:34:43*

---
Yeah that seems to have fixed it
