### ISSUE TITLE
sed doesn't recognize "-E" on Cray platforms

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1879]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1879*

---
Errors seem to be due to this change, not sure why it only shows up on Cray since sed on other build platforms doesn't document "-E" as a synonym of "-e".

https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=ba80d8c4073514f7ddc7bfe5d1ffc0dad14eafca

Beagle.log:sed: invalid option -- 'E'
Beagle-smp.log:sed: invalid option -- 'E'
Beagle-smp.log:sed: invalid option -- 'E'
BW.log:sed: invalid option -- 'E'
BW-smp.log:sed: invalid option -- 'E'
BW-smp.log:sed: invalid option -- 'E'
Eos.log:sed: invalid option -- 'E'
Eos-smp.log:sed: invalid option -- 'E'
Eos-smp.log:sed: invalid option -- 'E'
JYC.log:sed: invalid option -- 'E'
JYC-smp.log:sed: invalid option -- 'E'
JYC-smp.log:sed: invalid option -- 'E'
Titan.log:sed: invalid option -- 'E'
Titan-smp.log:sed: invalid option -- 'E'
Titan-smp.log:sed: invalid option -- 'E'

**Comment by stwhite91** [comment]
*Original date: 2018-04-22 15:08:31*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4043/~~ https://github.com/UIUC-PPL/charm/commit/d4f882ed49923a3e36adc78d2488ce74f8fce370
