### ISSUE TITLE
Abolish CmiBool

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#188]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/188*

---
Replace it with standard C or C++ `bool` wherever safe/possible

**Comment by PhilMiller** [comment]
*Original date: 2013-04-24 15:21:14*

---
Started reviewing `ramv/nuke-cmibool`

* I'm hesitant to change CkCallback right away, since those constructors are public API. If you can check that the tests, examples, and major applications aren't passing those inline arguments, or they're logical expressions rather than literals, that would clear this concern.
* We're likely to end up with merge conflicts on Harshitha's reductionStarting and Xiang's replica_ft branches. They won't be too bad, since this side is a simple search/replace, but they should be aware of it as they prepare to integrate. I'll add them to the watch list.
* I'm happy to see PUP's internals change over, but we can't drop support for PUPing CmiBool until all CmiBools are actually gone, in both the runtime and applications.
* In CkBitVector::Test, the return expression doesn't need to be cast.
* CkBitVector's comparison operators are just broken, both before and after the change. I don't see that as blocking this cleanup, but it's now open as #189. Again, the bool casts are unnecessary, though.
* CkImage::isEmpty: pointless cast, again

Overall, things look pretty good. Outside the load balancers, it looks like we've only got a small handful of other instances to eliminate.

**Comment by heyram** [comment]
*Original date: 2013-04-24 18:53:42*

---
Autobuild indicates that c++ compilers recognize bool on all our test platforms. Hence CmiBool is simply typdefed to bool on all our test platforms. If there exists a compiler where keyword bool is not recognized, there's a very high likelihood that we will have other build / performance issues with that compiler, and that we simply don't want to support it.

Despite the fact that its just a typedef, we should perhaps announce the deprecation in the 6.5 series and then remove them in 6.6.

> * I'm hesitant to change CkCallback right away, since those constructors are public API.

Another addition to public API changes: CkMigratable::usesAtSync is a protected boolean flag exposed to child classes (ie chare array elements).

> If you can check that the tests, examples, and major applications aren't passing those inline arguments, or they're logical expressions rather than literals, that would clear this concern.
> * I'm happy to see PUP's internals change over, but we can't drop support for PUPing CmiBool until all CmiBools are actually gone, in both the runtime and applications.
I debated a little about this. 

Is there a platform where CmiBool and bool are different where the above will cause problems? It should be easy to provide overloads guarded by if !CMK_BOOL_DEFINED, although I strongly doubt its necessary.

> * In CkBitVector::Test, the return expression doesn't need to be cast.
> * CkBitVector's comparison operators. Again, the bool casts are unnecessary, though.
> * CkImage::isEmpty: pointless cast, again

fixed.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-24 19:01:20*

---
I just realize now, after your comment, that CmiBool is only defined for C++ code and not for C. That simplifies a lot of this, since the typedef form is indeed universal now. Let me go back over things, and we may be able to move much faster.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-24 19:06:46*

---
In review, the changes to CkCallback, usesAtSync, and PUP are fine to go ahead. Since CmiBool is already universally a typedef for standard C++ bool, we can transition everything in our code right away, and just leave the typedef and definitions of CmiTrue/CmiFalse in place through a deprecation period.

I'd say clean up commits as you please and you're clear to merge.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-24 19:46:17*

---
There's a bit more mop-up work to be done:
* AMPI, mblock, packlib, and the bigsim emulator need the same search/replace treatment
* a couple documentation instances
* `converse.h` should drop the test against `CMK_BOOL_DEFINED` and the alternative non-typedef form
* The test in `configure` for `CMK_BOOL_DEFINED` can be deleted
