### ISSUE TITLE
Print slightly more detailed CPU topology info at startup by default

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1882]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1882*

---
We always print the number of PUs on a node during startup. On Quartz (LLNL), each node has 2 sockets, each socket has 18 cores, and each core has 2 PUs. We only print that each node is "72-way SMP" during startup, as in the following:
```
Charm++> Running on 8 unique compute nodes (72-way SMP).
```

I think we should print the number of nodes, the number of sockets per node, the number of cores per socket, and the number of PUs per core. This way it's easier to verify that hwloc and Charm++ are getting the right thing.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-10 23:43:15*

---
~~https://charm.cs.illinois.edu/gerrit/4164~~ https://github.com/UIUC-PPL/charm/commit/799a9f1ec31eada349961a4c12f025ef7a5d4189
