### ISSUE TITLE
 PumpOneSidedRDMATransactions 'putOp' undeclared on Cray GNI

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1891]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1891*

---
On gemini_gni-crayxe-persistent-smp:

../bin/charmc  -optimize -production   -I. -o machine.o machine.c
In file included from machine.c:4663:0:
machine-onesided.c: In function 'PumpOneSidedRDMATransactions':
machine-onesided.c:302:18: error: 'putOp' undeclared (first use in this function)
             free(putOp);
                  ^

**Comment by nitbhat** [comment]
*Original date: 2018-05-01 18:55:15*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4092/~~ https://github.com/UIUC-PPL/charm/commit/dd38b668429c32b24141b7c2656c15ffe99b6f38
