### ISSUE TITLE
no rule to make target .../stdarg.h error on Windows

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1892]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1892*

---
../bin/charmc  -optimize -production    -o ../lib/libconv-core.a convcore.o conv-conds.o conv-taskQ.o queueing.o msgmgr.o cpm.o cpthreads.o futures.o cldb.o random.o debug-conv.o debug-conv++.o conv-ccs.o ccs-builtins.o middle-ccs.o traceCore.o traceCoreCommon.o converseProjections.o machineProjections.o quiescence.o isomalloc.o mem-arena.o conv-counter.o memory-darwin-clang.o global-nop.o cmipool.o cpuaffinity.o cputopology.o cmitls.o memoryaffinity.o commitid.o sdag.o conv-interoperate.o conv-rdma.o 
../lib/libconv-core.a
make: *** No rule to make target '/cygdrive/cProgram Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/stdarg.h', needed by 'machine.o'.  Stop.

The missing '/' in "/cygdrive/cProgram..." may or may not be significant.

**Comment by jcphill** [comment]
*Original date: 2018-04-30 22:00:47*

---
That error is everywhere in machine.d:

machine.o machine.d : machine.c \
        /cygdrive/cProgram\ Files\ (x86)/Microsoft\ Visual\ Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/stdarg.h \
        /cygdrive/cProgram\ Files\ (x86)/Microsoft\ Visual\ Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/vcruntime.h \
        /cygdrive/cProgram\ Files\ (x86)/Microsoft\ Visual\ Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/sal.h \
        /cygdrive/cProgram\ Files\ (x86)/Microsoft\ Visual\ Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/concurrencysal.h \
        /cygdrive/cProgram\ Files\ (x86)/Microsoft\ Visual\ Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/include/vadefs.h \
        /cygdrive/ccygwin64/tmp/charm-6.9.0-pre/multicore-win64/tmp/converse.h \
        /cygdrive/ccygwin64/tmp/charm-6.9.0-pre/multicore-win64/tmp/conv-config.h \
        /cygdrive/ccygwin64/tmp/charm-6.9.0-pre/multicore-win64/tmp/conv-autoconfig.h \
        /cygdrive/ccygwin64/tmp/charm-6.9.0-pre/multicore-win64/tmp/conv-common.h \

This seems to be the cause:

https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=9526f130a86695b26173153ada6fae1cd552533a

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-01 19:17:53*

---
Please test ~~https://charm.cs.illinois.edu/gerrit/4093~~ https://github.com/UIUC-PPL/charm/commit/3ef63e5be6d725ea62ac0fca170d5ec82b91ee91
