### ISSUE TITLE
Charm's hwloc can collide with OpenMPI's

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1895]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1895*

---
https://lists.cs.illinois.edu/lists/arc/charm/2018-05/msg00004.html

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-08 16:21:00*

---
~~https://charm.cs.illinois.edu/gerrit/4145~~ https://github.com/UIUC-PPL/charm/commit/4348423d70ba1078bf77f429410017e3da87ff52

I am also seeking to merge this fix upstream: https://github.com/open-mpi/hwloc/pull/311
