### ISSUE TITLE
Cleanup AMPI DDT

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1897]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1897*

---
Now that CkDDT confined to AMPI, we can remove the CkDDT constants and replace them directly with MPI_ constants.
That applies to the type names themselves "CkDDT_INT" -> "MPI_INT" and to return types "0" -> "MPI_SUCCESS".

Also DDT can be cleaned up with C++11 features '= default' such as ' = delete', and simple getter/setter routines could be moved into the header.

**Comment by stwhite91** [comment]
*Original date: 2018-05-09 16:58:30*

---
Move simple routines and serialize() for primitive types into the header: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4152/~~ https://github.com/UIUC-PPL/charm/commit/d56c4fe51651cdcc18575660d3ee500e314ace8e

**Comment by matthiasdiener** [comment]
*Original date: 2018-07-27 19:48:59*

---
Error codes and constants:
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4408/~~ https://github.com/UIUC-PPL/charm/commit/669db6db4ac2ac6dd4eaac653d8aad8c50bd04b3
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4409/~~ https://github.com/UIUC-PPL/charm/commit/a8cfcae7bf5dea5a2bb27161ad4748110509a604
