### ISSUE TITLE
ckreduction.h {} xlC error: expected class member or base class name

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1902]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1902*

---
Build failure on ORNL Summit pami-linux-ppc64le-smp

../bin/charmc  -optimize -production  -I.   -c -o DummyLB.o DummyLB.C
In file included from DummyLB.C:6:
In file included from ./DummyLB.h:9:
In file included from ./CentralLB.h:9:
In file included from ./BaseLB.h:9:
In file included from ./LBDatabase.h:106:
In file included from ./LBDatabase.decl.h:3:
In file included from ./charm++.h:1131:
./ckreduction.h:249:5: error: expected class member or base class name
    {}
    ^
1 error generated.
Error while processing DummyLB.C.
Fatal Error by charmc in directory /ccs/home/jimp/summit/build_may/charm/pami-linux-ppc64le-smp/tmp
   Command xlC_r -I./../include -I /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/spectrum-mpi-10.2.0.0-20180508-riohv7qa3m5koyk4u5s7lqz5drkyljr2/pami_devel/include -I /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/spectrum-mpi-10.2.0.0-20180508-riohv7qa3m5koyk4u5s7lqz5drkyljr2/pami_devel/include -D__CHARMC__=1 -O3 -g -U_FORTIFY_SOURCE -I../bin/../include -I /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/spectrum-mpi-10.2.0.0-20180508-riohv7qa3m5koyk4u5s7lqz5drkyljr2/pami_devel/include -I /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20171006/linux-rhel7-ppc64le/xl-20180502/spectrum-mpi-10.2.0.0-20180508-riohv7qa3m5koyk4u5s7lqz5drkyljr2/pami_devel/include -D__CHARMC__=1 -I. -O3 -g -U_FORTIFY_SOURCE -std=c++11 -c DummyLB.C -o DummyLB.o returned error code 1

Looks recent:

cdd9e80e (Sam White              2018-05-03 15:19:09 -0500 249)     {}

commit cdd9e80e042d9a75cc87b4709577c95b5330d047
Author: Sam White <white67`illinois.edu>
Date:   Thu May 3 15:19:09 2018 -0500

    Cleanup: print reducer & callback type names as strings rather than ints
    
    Provides a more informative error message to users when overlapping
    reductions collide. Only enabled with CMK_ERROR_CHECKING.
    
    Change-Id: I0d841840cdcf652026976c8f4b95f2913a602221

https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commit;h=cdd9e80e042d9a75cc87b4709577c95b5330d047

**Comment by jcphill** [comment]
*Original date: 2018-05-10 16:45:58*

---
It looks like this fails due to an extra comma whenever CMK_ERROR_CHECKING is disabled:

+    reducerStruct(reducerFn f=NULL, bool s=false, const char *n=NULL) : fn(f), streamable(s),
+#if CMK_ERROR_CHECKING
+                  name(n)
+#endif
+    {}

The comma needs to move from after streamable(s) to before name(n).

**Comment by stwhite91** [comment]
*Original date: 2018-05-10 16:51:49*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4158/~~ https://github.com/UIUC-PPL/charm/commit/27e3a642eaaf00b2850b8cdc46fd58c679f6b8ce
