### ISSUE TITLE
Reimplement CmiNumCores et al using hwloc

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#1907]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1907*

---
With hwloc in place, there is no need to maintain our custom querying of hardware PU counts.

**Comment by stwhite91** [comment]
*Original date: 2018-10-02 17:26:51*

---
The current API also doesn't expose information about sockets or anything much beyond NumCores, NumPhysicalNodes, and NumPesPerPhysicalNode

**Comment by ericjbohm** [comment]
*Original date: 2018-10-02 18:15:10*

---
The basic functionality of the current API needs to be maintained.  Being able to get basic topology information with a single function call is incredibly convenient.  HWLOC is much richer for the within node information, but requires the user to do a lot more work to obtain the same information.  

The top level of the HWLOC ontology is "machine".  We can make collections of those, but any questions about the collection would be answered by us, not HWLOC.

That said, the implementation of the within host aspects of the API using HWLOC would help clean up some redundant code and exposing more of the functionality of HWLOC would be welcome.

**Comment by evan-charmworks** [comment]
#2250 was the first step of this.
