### ISSUE TITLE
Document PUP::able and associated macros

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1908]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1908*

---
This and the related functionality needs to be documented in the manual: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3985/~~ https://github.com/UIUC-PPL/charm/commit/2329d1d0c3cc01da60b082f01045bc73856aabe5

**Comment by epmikida** [comment]
*Original date: 2019-03-21 19:12:36*

---
Documentation added in this patch: ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5034~~ https://github.com/UIUC-PPL/charm/commit/e09a4ebbbca5dc78357cda314908430a828de2bf
