### ISSUE TITLE
Proper support for callbacks to [immediate] entry methods of node groups

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1909]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1909*

---
Currently, we don't keep track of whether a node group method is [immediate] or not inside of our callback infrastructure. This is also needed inside the direct API for zero copy messaging.

**Comment by nitbhat** [comment]
*Original date: 2018-05-16 23:20:30*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4196/~~ https://github.com/UIUC-PPL/charm/commit/dc0317bf55a92d09cd7ae864599f5f81131d2b56
