### ISSUE TITLE
announce deprecation of CmiBool

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#191]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/191*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-03 22:47:58*

---
Mentioned directly to namd-ppl list.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-03 22:51:15*

---
And to the charm mailing list.
