### ISSUE TITLE
Better explanation of [immediate] entry methods

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1911]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1911*

---
The manual's entry on [immediate] entry methods doesn't say anything about why you'd use them or not use them and where they are allowed to run (the comm thread).

**Comment by stwhite91** [comment]
*Original date: 2018-05-17 14:59:02*

---
I think the manual should say that [immediate] entry methods can run on the comm thread in SMP mode, and because of that you generally don't want long running entry methods to be immediate since it could delay communication.

**Comment by nitbhat** [comment]
*Original date: 2018-05-17 15:46:09*

---
In addition to this change, I also see another related section that seems incomplete as well:

10 . 1 . 3 . 2 Immediate Messages
Immediate messages are special messages that skip the Charm scheduler, they can be executed in an ``immediate'' fashion even in the middle of a normal running entry method. They are supported only in nodegroup.

What are the user controls for Immediate Messages? (How to make a message immediate etc).  I think those should be mentioned here.

**Comment by nitbhat** [comment]
*Original date: 2018-05-17 16:27:27*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4199/~~ https://github.com/UIUC-PPL/charm/commit/d705898aa477d2f396e720860ac48bc79977cea9
