### ISSUE TITLE
Consistent definition of "PE" throughout the manual

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1912]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1912*

---
The term PE should be consistently defined as a thread/process with a scheduler that chares can live on. 

The last paragraph in section 1.4 in particular is misleading in that it implies that comm threads count as PEs.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-16 00:06:10*

---
~~https://charm.cs.illinois.edu/gerrit/4188~~ https://github.com/UIUC-PPL/charm/commit/d80304640a63db2d6cb5d7a147fa48eb3724adc6
