### ISSUE TITLE
Make AtSync load balancing the default rather than periodic

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1914]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1914*

---
Periodic LB is currently the default, even though no production applications use it.
The only other uses for it would be fault evacuation / proactive fault tolerance, shrink/expand. But we could require those to use AtSync as well, possibly with MetaLB.

**Comment by juanjgalvez** [comment]
This is how it works in the new LB framework (to be merged).

**Comment by rbuch** [comment]
The new LB framework does this.
