### ISSUE TITLE
Make the build script clean/remove old builds

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1915]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1915*

---
If a user has a netlrts-linux-x86_64/ and a netlrts-linux-x86_64-smp/, then they do a "./build charm++ netlrts-linux-x86_64", our build script should remove the existing netlrts-linux-x86_64 directory before doing anything else.

We could potentially also add a "./build clean" command to remove all builds, and a "./build rebuild charm++" to do "cd <build_dir>/tmp && make charm++"

**Comment by epmikida** [comment]
*Original date: 2018-05-16 20:31:12*

---
I'm not sure if removing old builds should necessarily be the default, but either way something sensible should be done. Right now it appears to be broken completely. I did two ./builds in a row and the second one broke (after recompiling a bunch of unchanged files):

make: *** No rule to make target `charmrun', needed by `charmrun-target'.  Stop.
-------------------------------------------------
Charm++ NOT BUILT. Either cd into netlrts-darwin-x86_64/tmp and try

I would think making it work like a typical make file would be the most natural. As in, doing a ./build just defaults to running make in the appropriate directory if it exists, which will obey all dependency rules, only compile what needs to be compiled, and not rerun all the configuration checks. And then ./build clean <arch> maybe to clean that dir, and ./build clean all or ./build clean would remove all old builds?

**Comment by stwhite91** [comment]
*Original date: 2018-05-16 21:08:54*

---
I agree with what you've said: our './build' should behave like 'make'.

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-22 19:42:20*

---
~~https://charm.cs.illinois.edu/gerrit/4215~~ https://github.com/UIUC-PPL/charm/commit/8d1ddb135c56a814bb6ea79c275e6de124b9444d
~~https://charm.cs.illinois.edu/gerrit/4216~~ https://github.com/UIUC-PPL/charm/commit/3466cb4d22a615d6116e5ec92652cd33b94ad252
~~https://charm.cs.illinois.edu/gerrit/4217~~ https://github.com/UIUC-PPL/charm/commit/93cfbf74ff3772cc5fd0d9046026400a62856cce

**Comment by stwhite91** [comment]
*Original date: 2018-05-25 19:00:36*

---
All 3 of those patches have been merged, so rebuilding an already built target should work smoothly now.. We could still add ./build clean <arch> and ./build clean all
