### ISSUE TITLE
Remove CmiBool typedefs

### ISSUE THREAD

**Issue by heyram** [UIUC-PPL/charm#192]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/192*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-30 16:20:35*

---
ChaNGa and OpenAtom have now been cleaned up. NAMD has a bunch of uses, and I bet other applications do as well.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-03 22:46:40*

---
For backwards compatibility with at least one or two past NAMD releases, I realize it may be valuable to push the actual deletion somewhat further down the road.

**Comment by PhilMiller** [comment]
*Original date: 2014-10-15 17:28:40*

---
Implemented in "change 404":http://charm.cs.illinois.edu/gerrit/404

**Comment by PhilMiller** [comment]
*Original date: 2014-10-15 17:51:52*

---
Please get NAMD patched up to not use the CmiBool typedef and the CmiTrue/CmiFalse constants. They've been anachronistic for years.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-16 22:45:07*

---
Jim reports that NAMD's last remaining use of CmiFalse has been removed. Until there's a new NAMD release, Jenkins will carry a simply patch that corrects this one instance, so we can carry on CI testing of NAMD with this change applied.
