### ISSUE TITLE
Mac builds fail with "No gfortran found, exiting"

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1925]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1925*

---
Fortran support was neither requested nor required.  Break is likely due to this change:

commit e82ae8242b3dde160c5a5cc4cfec6f4d86613859
Author: Evan Ramos <evan`hpccharm.com>
Date:   Fri May 18 16:48:04 2018 -0500

    Call conv-mach-gfortran.sh from conv-mach-darwin.sh
    
    Change-Id: Id6a48c630e30ea88f888d9628aa564bf59bbe767

**Comment by evan-charmworks** [comment]
*Original date: 2018-05-29 21:45:05*

---
~~https://charm.cs.illinois.edu/gerrit/4237~~ https://github.com/UIUC-PPL/charm/commit/61e5995ef530fca7cebdfc1c224d047476fb8b87
