### ISSUE TITLE
mpi-linux-x86_64 failures in autobuild on charm++/megatest

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1926]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1926*

---
mpi-linux-x86_64 autobuild hasn't passed since May 2. On May 2nd we merged the C -> C++ machine.c renaming patch...

```
...
test 52: initiated [all-at-once]
Starting test
Created detector, starting first detection
Started first test
Finished second test
Started third test
test 52: completed (0.02 sec)
All tests completed, exiting
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 2521 on node respect exited on signal 9 (Killed).
--------------------------------------------------------------------------

```

**Comment by nitbhat** [comment]
*Original date: 2018-05-31 16:37:51*

---
This bug is being introduced by ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/2785/~~ https://github.com/UIUC-PPL/charm/commit/f7fbaaaae1088ee65988c1345203da3ed55abcc4

**Comment by stwhite91** [comment]
*Original date: 2018-05-31 16:41:20*

---
Can you revert that commit? It has almost no impact on performance from what I can tell

**Comment by stwhite91** [comment]
*Original date: 2018-06-04 13:18:29*

---
Reverting that commit fixed the issue
