### ISSUE TITLE
Evaluate other documentation possibilities 

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#1927]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1927*

---
Currently, Charm++ uses a documentation system built on top of Latex to create pdf and html manuals. We should  evaluate whether we can use a more modern system (e.g. pandoc/Markdown based, readthedocs.io, GitHub pages, ...).

**Comment by stwhite91** [comment]
*Original date: 2018-07-18 19:14:32*

---
Note that Juan has been using readthedocs.io for CharmPy documentation: https://charmpy.readthedocs.io/en/latest/

**Comment by matthiasdiener** [comment]
*Original date: 2019-01-10 16:45:14*

---
Patch to convert Latex to RST here:
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/3624~~ https://github.com/UIUC-PPL/charm/commit/04bf65953b2d404a2002a1bec1a736883aed84b3
