### ISSUE TITLE
Charm++ version and commit information is not available in tarball downloads of repo

### ISSUE THREAD

**Issue by karthiksenthil** [UIUC-PPL/charm#1935]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1935*

---
If the repository is downloaded as a tarball from Gerrit, the version and last commit ID is not printed. Presumably the variable `CmiCommitID` is not populated.

Output of hello program in such a repo:
```
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 1.677 seconds.
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: 
Charm++> scheduler running in netpoll mode.

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-06-21 21:41:49*

---
The code in `src/scripts/Makefile` that generates the definition of `CmiCommitID` must have run for a Charm++ program to build without a linker error indicating its absence. However, if no `VERSION` file is present, the string will be blank.

```
commitid.c: VERSION
	echo "extern const char * const CmiCommitID;" > $`
	echo "const char * const CmiCommitID = \"`cat VERSION`\";" >> $`
```

Does Gerrit have any way of running a script during the tarball assembly process? If not, I don't know if there is any way to resolve this issue.

**Comment by rbuch** [comment]
I don't think we have a good way of doing this for tarballs/zips generated from an arbitrary point in the git history. In my eyes, as long as a git cloned version and the **release** tarballs have the right information, that should be sufficient.
