### ISSUE TITLE
pose.decl.h is not found when using pose.h in the BigNetSim emulator 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1936]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1936*

---
This issue was found by Vishwas Vasudeva and reported on the Charm mailing list. 

```
In file included from BgSim_sim.h:3:0,
                 from BgSim_sim.C:1:
/scratch/nitin/charm_2/net-linux-x86_64-bigemulator/include/pose/pose.h:9:23: fatal error: pose.decl.h: No such file or directory
compilation terminated.
Fatal Error by charmc in directory /scratch/nitin/BigNetSim/trunk/Main
   Command g++ -DCMK_GFORTRAN -I/scratch/nitin/charm_2/net-linux-x86_64-bigemulator/bin/../include -D__CHARMC__=1 -I/scratch/nitin/charm_2/net-linux-x86_64-bigemulator/include/pose -I/scratch/nitin/charm_2/net-linux-x86_64-bigemulator/include -I../BlueGene -g -fno-stack-protector -std=c++0x -fno-lifetime-dse -c BgSim_sim.C -o ../tmp/BgSim_sim.o returned error code 1
charmc exiting...
```

To reproduce:

1. Build AMPI with bigsim emulator (./build AMPI netlrts-linux-x86_64 bigemulator -j16 -O0)
2. Build pose - go into <arch>/tmp/libs/ck-libs/pose and run "make -j4"
3. Download BigNetSim from SVN: svn co https://charm.cs.illinois.edu/svn/repos/BigNetSim/
4. Update BigNetSim/trunk/Makefile.common to point to charm arch directory
5. cd BigNetSim/trunk/SimpleLatency and run make

**Comment by ericjbohm** [comment]
*Original date: 2018-09-06 20:13:37*

---
BigNetSim should be deprecated as its functionality has been subsumed in Charades and Tracer.

**Comment by matthiasdiener** [comment]
Bigsim has been removed in #2703.
