### ISSUE TITLE
Threads assigned incorrectly for charm++/openmpi3.1.0/torque

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1937]
*Original author: Geoffrey Lovelace*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1937*

---
I'm trying to build charm++ v6.8.0 with SMP enabled on a cluster. Each compute node has 12 cores, so I want, e.g., to run a job on 2 nodes, with 11 worker threads on each node and 1 communication thread on each node. The cluster is running Scientific Linux 6.3, gcc 7.3.0, openmpi-3.1.0, and torque/pbs.

I followed the online instructions to build using the ./build command in the charm root directory; the command written to smart-build.log is 
  "./build charm++ mpi-linux-x86_64   mpicxx smp  -j16  --with-production"

charm++ builds normally as far as I can tell. Inside $CHARM_ROOT/mpi-linux-x86-64-smp-mpicxx/examples/charm++/hello/fancyarray/, if I get an interactive job with two compute nodes (12 cores each node), then threads don't run where I expect. If I run 
  ./charmrun ./hello

the output is as expected. But if I instead try
  ./charmrun +p2 ./hello ++ppn=11,

then the code tries to run 24 SMP threads on one compute node, instead of 12 SMP threads on each of two compute nodes and then terminates (output below).

If I run an mpi hello-world program in the same interactive job, I get the correct output ("Hello world" from each core on each node). If I recompile without SMP threading, then
  ./charmrun +p24 ./hello

runs fine on 2 compute nodes, 12 processes per node, as expected.

Is there any way I can run 1 process per compute node, with 12 threads per node? Are the common situations or mistakes setting up charm++ or its dependencies that might prevent me from getting the output I expect?

I'd be grateful for any help anyone might be able to give me.

=====================
1. Result running in mpi-linux-x86-64-smp-mpicxx/examples/charm++/hello/fancyarray/

orca-0-43$ ./charmrun +p2 ./hello ++ppn=11

Running on 2 processors:  ./hello ++ppn=11
mpirun -np 2 -machinefile /var/spool/torque/aux//81362.orca.fullerton.edu ./hello ++ppn=11
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_FUNNELED (desired: MPI_THREAD_FUNNELED)
Charm++> Running in SMP mode: numNodes 2,  11 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.0-0-ga36028e
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.361 seconds.

Charm++> Warning: the number of SMP threads (24) is greater than the number of physical cores (12), so threads will sleep while idling. Use +CmiSpinOnIdle or +CmiSleepOnIdle to control this directly.

------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: Multiple PEs assigned to same core. Set affinity options to correct or lower the number of threads.

1. Contents of /var/spool/torque/aux//81362.orca.fullerton.edu

orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-43
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42
orca-0-42

**Comment by stwhite91** [comment]
*Original date: 2018-06-19 01:43:55*

---
charmrun's +p parameter should be the total number of PEs, while ppn specifies the number of PEs per node. Can you try this:
```
./charmrun +p 22 ./hello +ppn 11 +pemap 0-10 +commap 11
```

Also, is there a job launcher that is preferred on this cluster, such as srun, aprun, mpirun, mpiexec, etc? You could try launching with whatever that is, for example:
```
srun -n 2 --ntasks-per-node 1 ./hello +ppn 11 +pemap 0-10 +commap 11

```

**Comment by pplimport** [comment]
*Original author: Geoffrey Lovelace*
*Original date: 2018-06-19 17:22:45*

---
Thank you very much for the quick reply! My system uses mpirun to actually run the jobs.

I tried the command you suggested. Output below; it still runs 24 threads on 1 node instead of 12 threads on each of two nodes.

Charmrun generates the following mpirun command in this case:

`mpirun -np 2 -machinefile /var/spool/torque/aux//81384.orca.fullerton.edu ./hello +ppn 11 +pemap 0-10 +commap 11`

However, I noticed that if I add the flag 

`--map-by ppr:1:node` 

to this mpirun command, then it appears to to the right thing (12 threads on each of two nodes).

So for now, it looks like I can just run jobs by calling mpirun directly, adding this flag. Do this sound reasonable to you? Is there a way to tell charmrun to pass this `--map-by-ppr:1:node` flag to mpirun, so I can start jobs with charmrun instead of mpirun?

`orca-0-20$ ./charmrun +p 22 ./hello +ppn 11 +pemap 0-10 +commap 11

Running on 2 processors:  ./hello +ppn 11 +pemap 0-10 +commap 11
mpirun -np 2 -machinefile /var/spool/torque/aux//81384.orca.fullerton.edu ./hello +ppn 11 +pemap 0-10 +commap 11
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_FUNNELED (desired: MPI_THREAD_FUNNELED)
Charm++> Running in SMP mode: numNodes 2,  11 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.0-0-ga36028e
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 0-10
Charm++> set comm 0 on node 0 to core #11
Charm++> Running on 1 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.017 seconds.

Charm++> Warning: the number of SMP threads (24) is greater than the number of physical cores (12), so threads will sleep while idling. Use +CmiSpinOnIdle or +CmiSleepOnIdle to control this directly.

WARNING: Multiple PEs assigned to same core, recommend adjusting processor affinity or passing +CmiSleepOnIdle to reduce interference.
Running Hello on 22 processors for 5 elements
Hello (25,4) created on 2
Hello (24,2) created on 6
Hello (23,0) created on 10
Hi[17] from element 0
Hello (-23,1) created on 17
Hello (-22,3) created on 20
Hi[18] from element 1
Hi[19] from element 2
Hi[20] from element 3
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
`

`orca-0-20$ mpirun -np 2 --map-by ppr:1:node -machinefile /var/spool/torque/aux//81384.orca.fullerton.edu ./hello +ppn 11 +pemap 0-10 +commap 11
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_FUNNELED (desired: MPI_THREAD_FUNNELED)
Charm++> Running in SMP mode: numNodes 2,  11 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.0-0-ga36028e
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 0-10
Charm++> set comm 0 on node 0 to core #11
Charm++> Running on 2 unique compute nodes (12-way SMP).
Charm++> cpu topology info is gathered in 0.003 seconds.
Running Hello on 22 processors for 5 elements
Hello (24,2) created on 6
Hello (25,4) created on 2
Hello (23,0) created on 10
Hi[17] from element 0
Hi[19] from element 2
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
Hello (-23,1) created on 17
Hello (-22,3) created on 20
Hi[18] from element 1
Hi[20] from element 3
orca-0-20$ 
`

**Comment by evan-charmworks** [comment]
*Original date: 2018-06-19 20:54:11*

---
Hi Geoffrey,

Does it work to pass `--map-by ppr:1:node` as part of the charmrun invocation, before your executable name? For example:

```
$ ./charmrun --map-by ppr:1:node ./hello

Running on 1 processors:  --map-by ppr:1:node ./hello 
charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 1  --map-by ppr:1:node ./hello 
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_FUNNELED (desired: MPI_THREAD_FUNNELED)
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 0 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.2-753-gc34c02df0
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 2 PUs = 12-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 1 processors for 5 elements
[0] Hello 0 created
[0] Hello 1 created
[0] Hello 2 created
[0] Hello 3 created
[0] Hello 4 created
[0] Hi[17] from element 0
[0] Hi[18] from element 1
[0] Hi[19] from element 2
[0] Hi[20] from element 3
[0] Hi[21] from element 4
All done
[Partition 0][Node 0] End of program

```

**Comment by pplimport** [comment]
*Original author: Geoffrey Lovelace*
*Original date: 2018-06-19 23:11:19*

---
Yep, that works! I guess what confused me was that charmrun didn't just automatically do the right thing, telling mpi to run one process per node. But now that I know about this flag, I'm good to go. Thanks again for your help and your quick response!
