### ISSUE TITLE
'make AMPI' doesn't rebuild libmoduleampi.so

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1941]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1941*

---
One of the Charmworks interns reported this: doing 'make AMPI' in an existing build of AMPI only rebuilds the static library, not the shared one if it was built with --build-shared.

**Comment by matthiasdiener** [comment]
*Original date: 2018-11-12 00:53:30*

---
Not sure if something has changed since this was reported, but I could not reproduce this (on Linux or Darwin).

Test:
```
$ ./build AMPI multicore-linux-x86_64 -j5 --build-shared
$ touch src/libs/ck-libs/ampi/ampi.C
$ cd tmp && make AMPI
$ ls -l lib/libmoduleampi.a lib_so/libmoduleampi.so
-> both files have the same modification time.

```

**Comment by matthiasdiener** [comment]
*Original date: 2019-02-12 23:55:27*

---
Closing this for now as I can't reproduce it.
