### ISSUE TITLE
RUsage incorrectly used in configure and memory library

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1943]
*Original author: Joseph Hutter*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1943*

---
in src/scripts/configure.ac, getrusage is used incorrectly. The image attached shows the configure, and it's the same problem in src/conv-core/memory.c. To use RUSAGE_THREAD, you need to define _GNU_SOURCE instead of __USE_GNU, and you need to do it before you include any sys files. RUSAGE_THREAD is supported since Linux 2.2. Should be a quick fix. See the manual page here: http://man7.org/linux/man-pages/man2/getrusage.2.html 

![Screen Shot 2018-07-09 at 11 25 01 PM](https://user-images.githubusercontent.com/1772435/63629753-bb274980-c5d9-11e9-89d8-62d99b3cc347.png)

**Comment by evan-charmworks** [comment]
*Original date: 2018-07-10 23:41:41*

---
~~https://charm.cs.illinois.edu/gerrit/4343~~ https://github.com/UIUC-PPL/charm/commit/70cc917747de49705fb85f975f5ea1c3c28c5e59
