### ISSUE TITLE
OpenMP library doesn't build when 5.0 is available

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1944]
*Original author: Joseph Hutter*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1944*

---
When building OpenMP libary, if you have 5.0 available, you see this during configure:
-- LIBOMP: OpenMP Version       -- 50
And then you get this later on:
CMake Error: File /projects/cwi/buildcfs/charm/verbs-linux-x86_64-omp-smp/tmp/libs/conv-libs/openmp_llvm/runtime/src/include/50/omp.h.var does not exist.
So it fails! Fortunately, it's not difficult to work around, but it would be nice if there were support in runtime/src/include for 50. Current workaround:
cd tmp/libs/conv-libs/openmp_llvm/runtime/src/include; cp -r 45 50; make -C ../../..;

**Comment by sbak5** [comment]
*Original date: 2018-07-10 20:00:08*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4340/~~ https://github.com/UIUC-PPL/charm/commit/274f6c4686675d4ba21993c1e6e9cf6094bb4f79
