### ISSUE TITLE
Charmxi segfaults with aggregate keyword on explicit declarations of templated client

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#1946]
*Original author: Joseph Hutter*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1946*

---
Code excerpt:

template <typename Data>
group CacheManager {
template <typename Visitor>
entry [aggregate] void addCache(MultiMsg<Data>);
};
extern entry [aggregate] void CacheManager<CentroidData> addCache<GravityVisitor> (MultiMsg<CentroidData>);

Charmxi just can't parse the aggregate keyword on explicit declarations. Not sure if bug or suggested feature.

**Comment by stwhite91** [comment]
*Original date: 2018-07-16 14:35:57*

---
This patch added support for attributes on explicit instantiations, so it's a bug. You can see a working example with [sync] attributes in charm/tests/charm++/charmxi_parsing/ParameterPack.ci

~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3987/~~ https://github.com/UIUC-PPL/charm/commit/440a2fdbf32a00365f1b3c52a50b6b1745e6926c

**Comment by evan-charmworks** [comment]
*Original date: 2018-07-16 16:50:17*

---
It looks like this entry has overlap with https://charm.cs.illinois.edu/redmine/issues/1227

**Comment by evan-charmworks** [comment]
*Original date: 2018-07-16 18:58:19*

---
~~https://charm.cs.illinois.edu/gerrit/4360~~ https://github.com/UIUC-PPL/charm/commit/2aeb66929da69fbdf5b3cd34ebd4f2ec096e879b fixes the crash on my end
