### ISSUE TITLE
Rename Charm's graph.h to something less generic

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1948]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1948*

---
src/util/graph.h ends up in Charm's include/ directory, meaning that if an application tries to #include "graph.h" it might get Charm++'s graph.h instead of its own or something else. This happens when building the Zoltan library on top of AMPI.

Our graph.h is apparently part of the load balancing framework, according to comments in it, even though it's not in ck-ldb/. I'm not even sure if it's used.

**Comment by matthiasdiener** [comment]
*Original date: 2018-07-19 21:46:52*

---
Seems to be used only by RecBisectBfLB.

**Comment by stwhite91** [comment]
*Original date: 2018-07-20 12:40:31*

---
Quinoa discussion: https://github.com/quinoacomputing/quinoa/pull/255#discussion_r203850796

**Comment by matthiasdiener** [comment]
*Original date: 2018-07-30 17:20:35*

---
RecBisectBfLB does not seem to compile, and I think we should consider removing RecBisectBfLB and the graph.h stuff.

**Comment by evan-charmworks** [comment]
*Original date: 2018-07-31 16:23:11*

---
Matthias Diener wrote:
> RecBisectBfLB does not seem to compile, and I think we should consider removing RecBisectBfLB and the graph.h stuff.

If the load balancing subgroup is okay with this, sounds good to me.

**Comment by kavithachandrasekar** [comment]
*Original date: 2018-08-01 22:07:09*

---
RecBisectBfLB works okay after updating num_partitions to use CkNumPes(). It seems to balance load okay on a single node. Here's a sample run.


```
<code class="text">
$ ./stencil3d 128 64 +ppn 4 +balancer RecBisectBfLB +LBDebug 1
Charm++: standalone mode (not using charmrun)
Charm++> Running in SMP mode: 1 processes, 4 worker threads (PEs) + 1 comm threads per process, 4 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.8.2-758-g1d39b80c5
Charm++> scheduler running in netpoll mode.
CharmLB> Verbose level 1, load balancing period: 0.5 seconds
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (2 sockets x 4 cores x 1 PUs = 8-way SMP)
Charm++> cpu topology info is gathered in 0.001 seconds.
CharmLB> RecBisectBfLB created.

STENCIL COMPUTATION WITH BARRIERS
Running Stencil on 4 processors with (2, 2, 2) chares
Array Dimensions: 128 128 128
Block Dimensions: 64 64 64
[1] Time per iteration: 0.028574 0.059614
[2] Time per iteration: 0.144010 0.203675
[3] Time per iteration: 0.141648 0.345374
[4] Time per iteration: 0.143779 0.489203
[5] Time per iteration: 0.141399 0.630652

CharmLB> RecBisectBfLB: PE [0] step 0 starting at 0.713235 Memory: 40.465790 MB
CharmLB> RecBisectBfLB: PE [0] strategy starting at 0.757647
[0] RecBisectBfLB strategy
[0] RecBisectBfLB: graph converted
returning from partitioner strategy
CharmLB> RecBisectBfLB: PE [0] Memory: LBManager: 810 KB CentralLB: 3 KB
CharmLB> RecBisectBfLB: PE [0] #Objects migrating: 4, LBMigrateMsg size: 0.00 MB
CharmLB> RecBisectBfLB: PE [0] strategy finished at 0.757679 duration 0.000032 s
CharmLB> RecBisectBfLB: PE [0] step 0 finished at 0.769063 duration 0.055828 s

[6] Time per iteration: 0.267664 0.898375
[7] Time per iteration: 0.015388 0.913812
[8] Time per iteration: 0.120018 1.033888
[9] Time per iteration: 0.120761 1.154704
[10] Time per iteration: 0.119944 1.274706
</code>
```

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-21 19:29:05*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4500~~ https://github.com/UIUC-PPL/charm/commit/a4dd39891355475b378168ee9789f512c8b6afef
