### ISSUE TITLE
Modify old charm++/converse onesided/direct API and examples to new rdma API

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#195]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/195*

---
dust off branch, test and integrate

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 17:36:52*

---
CmiOnesided will replace CmiDirect.  It already has a generic converse implementation.

**Comment by nitbhat** [comment]
*Original date: 2017-04-13 20:15:44*

---
We have three different converse APIs that use or intend to use RDMA functionality. (CmiDirect, CmiOnesided, CmiRdma). Out of these, the first two are dated and not in use. The last one is a thin API that was built to support charm++ level  "rdma" tagged messages for zero-copy message send/receives. 

This feature should focus on the following items:

1) Remove the old converse/charm++ APIs.
2) Modify existing examples in charm/converse to use the new RDMA API.

**Comment by stwhite91** [comment]
*Original date: 2017-04-22 15:14:56*

---
Getting GNI and NetLRTS RDMA support working, plus getting real applications (NAMD, OpenAtom, ChaNGa) to use the API, should be higher priorities than cleaning up the old code/examples.

**Comment by nitbhat** [comment]
*Original date: 2017-12-13 21:19:10*

---
I think out of the tasks currently assigned to me, this task is lower in terms of priority. So, can we target it to a release beyond 6.9.0?

**Comment by nitbhat** [comment]
*Original date: 2018-09-20 19:33:42*

---
Examples to be removed/modified:

1. charm/examples/charm++/onesided
2. charm/tests/charm++/pingpong
3. charm/examples/charm++/ckdirect/stencil3d/
4. charm/examples/charm++/ckdirect/matmul3d

Let me know if there are other example/test codes that need to be modified.

**Comment by nitbhat** [comment]
*Original date: 2018-09-21 20:12:50*

---
Gerrit:
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4594/~~ https://github.com/UIUC-PPL/charm/commit/f6bc80e04dd5b7fd5a05e43e6e558d4da479807d
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4595/~~ https://github.com/UIUC-PPL/charm/commit/bdbb8e667c321ec7063074c9947e64a724111f23
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4596/~~ https://github.com/UIUC-PPL/charm/commit/7ffc6660b8cef6e31a7a50b50365ba72b50a62f2
