### ISSUE TITLE
cmake-based build system

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#1953]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1953*

---
Our current home-grown build system consists of:
* the ./build shell script
* the ./smart-build.pl Perl script
* an autoconfiscated configure script
* an assortment of hand-written Makefiles
* completely separate build systems (hwloc, ROMIO, ...)

It would be interesting to have a more standard approach to building Charm++:
* Users are more familiar with the build system.
* We can provide reasonable defaults, such that users do not have to specify the network layer, SMP mode, optimization options etc.
* Fix issues with the current build system (e.g., Makefiles that ignore errors, infinite recompilation of some files, ...)

CMake is probably the most interesting alternative for us:
* It is supported on all platforms we support.
* It is installed on most systems.
* It only requires a C++ compiler.
* It has integrated testing and packaging frameworks.

**Comment by stwhite91** [comment]
*Original date: 2018-08-03 21:38:43*

---
https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4418/

**Comment by matthiasdiener** [comment]
Has been merged as #2136 .
