### ISSUE TITLE
Verbs Init code hangs when it tries connecting an inactive device

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#1954]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1954*

---
This issue was encountered when Yong Qin from Mellanox, tried running a charm++ application on their cluster which had multiple hca cards. The verbs init code should use ibstatus and find the active devices and try to connect to only the active devices. Currently, it tries to connect to the first device returned by ibv_devices. If the first device returned by ibv_devices is inactive, the program hangs. 

The fix should be to connect to the only active devices. If all the devices are inactive, an appropriate error message should be displayed.

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-13 22:48:28*

---
~~https://charm.cs.illinois.edu/gerrit/4474~~ https://github.com/UIUC-PPL/charm/commit/254898aa13cf60bdf2f1709de355f505bcf2ff93
