### ISSUE TITLE
Unbounded memory usage in LBDB

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1961]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1961*

---
Ronak mentioned finding a vector in LBDB that stores location records, which we simply do 'push_back()' on always, even though some entries are invalidated in the middle of the vector over time.
Instead of using push_back we can scan the vector for a NULL entry, and maybe keep track of the first NULL element in the vector so we have a guess at where to start the scan from always.

**Comment by stwhite91** [comment]
*Original date: 2018-08-08 18:33:54*

---
I think it would be good to have this fixed for 6.9.0 since it should be simple and non-API-breaking

**Comment by rbuch** [comment]
*Original date: 2018-08-08 18:44:37*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4460/~~ https://github.com/UIUC-PPL/charm/commit/251603c67e7164cab6960a1347562f09968e047f
