### ISSUE TITLE
Enable +isomalloc_sync by default for AMPI

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1964]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1964*

---
If running an AMPI application, it's often necessary to pass the runtime option '+isomalloc_sync' to ensure correctness in the face of Address Space Layout Randomization (ASLR).
The current implementation of +isomalloc_sync requires support for a shared file system across nodes, which is common but not universal. It would be nicer if we enabled +isomalloc_sync runtime support by default (on certain builds/systems only?) and added an option to disable it.

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-08 17:42:46*

---
Which platforms should not enable +isomalloc_sync by default?

**Comment by stwhite91** [comment]
*Original date: 2019-04-08 17:58:58*

---
BGQ and Windows don't support Isomalloc so it's not needed there, but I think any other system with a shared file system should work

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-08 18:00:57*

---
A shared filesystem on something like netlrts depends on how the user sets up the run. The thing to do would probably be try it on platforms that support it and inform the user when it fails but otherwise attempt to continue.

**Comment by evan-charmworks** [comment]
Ideally the use of the filesystem could be replaced by Converse messaging.

**Comment by stwhite91** [comment]
Yeah, I just opened issue #2252 for that
