### ISSUE TITLE
LAMMPS on AMPI fails after migration due to AMPI not wrapping posix_memalign()

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1965]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1965*

---
The application's data stuructures appear to be corrupted after migrating when using -memory isomalloc, though the issue disappears when using -memory os-isomalloc.

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-21 17:56:50*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4495~~ https://github.com/UIUC-PPL/charm/commit/a26c48121588f11ad53270c47ca5a999635f9dbf

The problem was that we did not wrap `posix_memalign`, which LAMMPS uses for heap allocations.
