### ISSUE TITLE
Some libraries are built as shared libraries even without --build-shared

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#1968]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1968*

---
At least the following seem to be always built as shared libraries:
* hwloc
* QuickThreads

The following build standalone shared libraries in the style of MPI user code and should not be affected by any changes to the above:
* one of the AMPI privatization tests

**Comment by stwhite91** [comment]
*Original date: 2018-08-23 12:43:00*

---
The AMPI privatization test is meant to be built as a shared object always, to test that privatizing global variables in shared objects works.

**Comment by matthiasdiener** [comment]
*Original date: 2018-08-23 13:26:45*

---
Would it make sense to do this privatization test only when compiling with --build-shared?

**Comment by stwhite91** [comment]
*Original date: 2018-08-23 13:40:27*

---
That test is building a library as a shared object, it doesn't matter how AMPI is built. You should always be able to build an application with a shared object linked into it no matter how you built the (A)MPI library.

**Comment by evan-charmworks** [comment]
*Original date: 2019-01-11 22:25:58*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4893~~ https://github.com/UIUC-PPL/charm/commit/5924c7263e042b2c9a092fe6621dc6f7ba9feb33
