### ISSUE TITLE
Replace use of signal() with sigaction()

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#197]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/197*

---
http://glandium.org/blog/?p=2979

Most of our uses of `signal()` are simply unconditionally setting a signal handler, rather than saving/restoring them. Even then, they're setting handlers other than 'default' or 'ignore', which may be unsafe in multithreaded SMP builds.

Even worse are the few that actually do save and restore handlers. Some of those may even mix poorly with the few `sigaction()` calls we do have.

Thus, all uses of `signal()` should be converted to `sigaction()` as the manual recommends.

**Comment by stwhite91** [comment]
*Original date: 2016-08-04 18:34:20*

---
This has been sitting in review since December, please address the comments and get it merged: ~~https://charm.cs.illinois.edu/gerrit/#/c/887/~~ https://github.com/UIUC-PPL/charm/commit/5bfb1ba3d2a5af24008d31b17338ff603e70e2dd

**Comment by jcphill** [comment]
*Original date: 2017-02-08 17:33:59*

---
This broke MPI builds.  See bugs #1402 and #1403.

**Comment by jcphill** [comment]
*Original date: 2017-02-08 17:40:09*

---
Also broke all Windows builds. See bug #1403.
