### ISSUE TITLE
libmemory- broken without production on BGQ

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1970]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1970*

---
The recent changes to how we build the various libmemory objects seems to have broken it.

```
../bin/charmc   -I. -o libmemory-charmdebug.o -DCMK_MEMORY_BUILD_CHARMDEBUG -optimize -touch-on-failure memory.C
In file included from memory.C:677:
./memory-charmdebug.c:30:2: error: "charmdebug is not enabled (e.g. when building with-production)"
#error "charmdebug is not enabled (e.g. when building with-production)"
 ^
memory.C:740:3: error: use of undeclared identifier 'meta_init'
  meta_init(argv);
  ^
memory.C:776:20: error: use of undeclared identifier 'meta_free'; did you mean 'mm_free'?
  MEM_LOCK_AROUND( meta_free(mem); )
                   ^~~~~~~~~
                   mm_free
```

With production the build completes.

**Comment by evan-charmworks** [comment]
*Original date: 2018-08-27 20:38:36*

---
This must have been exposed by ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4505/~~ https://github.com/UIUC-PPL/charm/commit/7361af1434bf6f959b1e21d6225f58a1c889a18c3/src/scripts/Makefile but I don't understand why it's happening. Specifically, it means `conv-mach-opt.h` became out of sync with `conv-mach-opt.sh`, or that the Makefile is reading the latter incorrectly. I don't see how the former could ever happen:

```
AC_ARG_ENABLE([charmdebug],
            [AS_HELP_STRING([--enable-charmdebug],
              [enable charmDebug])], ,
            [enable_charmdebug=yes])

if test "$enable_charmdebug" = "no"
then
  Echo "CharmDebug is disabled" 
  AC_DEFINE_UNQUOTED(CMK_CHARMDEBUG, 0, [disable charmdebug])
  add_flag CMK_CHARMDEBUG=0
else
  Echo "CharmDebug is enabled" 
  AC_DEFINE_UNQUOTED(CMK_CHARMDEBUG, 1, [enable charmdebug])
  add_flag CMK_CHARMDEBUG=1
fi
```

For the latter hypothesis, I put together this cleanup: ~~https://charm.cs.illinois.edu/gerrit/4527~~ https://github.com/UIUC-PPL/charm/commit/caf5dc74aea13ef7c998139137f6ae14334c7353

**Comment by stwhite91** [comment]
*Original date: 2018-08-30 03:08:35*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4534/~~ https://github.com/UIUC-PPL/charm/commit/d2a8263dd62be667a3545f47b278d827ac0c1d98
