### ISSUE TITLE
Tests/examples for non-threaded Charm++ programs using Isomalloc

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#1972]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1972*

---
~~https://charm.cs.illinois.edu/gerrit/4472~~ https://github.com/UIUC-PPL/charm/commit/730f7c25a216c1d4cb69693dc9153cc9bda7db72 adds support for arbitrary Isomalloc contexts. We should have tests and examples for this feature.

**Comment by stwhite91** [comment]
*Original date: 2018-09-07 18:41:21*

---
We also need to document the interface in the manual somewhere too, once we have tests and examples.

**Comment by evan-charmworks** [comment]
The patch in question was merged because it included cleanup that seemed to resolve an issue, but the API was not fully sanitized for real use in practice. My refactoring will remove the entirely arbitrary contexts that the lack of testing applies to.
