### ISSUE TITLE
Direct GPU-GPU messages

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#1973]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1973*

---
Enable Charm++ to send RDMA-style messages to/from buffers on the GPU. Our initial plan is to use the RDMA syntax. The runtime should detect whether the source and/or target buffers are resident on a local or remote GPU and invoke the corresponding GPU Direct call. We will test this approach with benchmarks (e.g. stencil2d) against GPU-aware MPI versions on multi-GPU clusters (e.g. Bridges, Comet, etc) to ensure we have comparable performance.

**Comment by mprobson** [comment]
*Original date: 2019-02-21 20:38:32*

---
Potentially split this into two/three tasks:
1. GPU-GPU on node
2. GPU-GPU off node
3. CPU-GPU off node

**Comment by minitu** [comment]
PR for within-node: #2644

**Comment by minitu** [comment]
PR for inter-node: #2791

**Comment by minitu** [comment]
Resolved by #3359.
