### ISSUE TITLE
forced dynamic linking on Cray breaks build on Beagle

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#1975]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1975*

---
This change forces dynamic linking on Cray:

~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4368/~~ https://github.com/UIUC-PPL/charm/commit/8d9992b6d73bd81376658234552a4d0c170a2b22

On Beagle at U. Chicago the -dynamic flag breaks something in the PE so -lrca doesn't get included on the g++ command line.

Also, it forces dynamic linking even when os-isomalloc isn't being used, which I assume Cray has off by default for a reason.

**Comment by evan-charmworks** [comment]
*Original date: 2018-09-06 21:38:04*

---
Is adding `-lrca` to the end of that `CMK_LIBS` line sufficient to resolve the link failure?

**Comment by jcphill** [comment]
*Original date: 2018-09-06 21:38:22*

---
The dynamic linking failure on Beagle is an old fault with a known work-around from Blue Waters and Titan.
We still probably don't want to force dynamic linking unnecessarily.

**Comment by jcphill** [comment]
*Original date: 2018-09-06 21:39:13*

---
FYI, the workaround is "setenv PE_PKGCONFIG_LIBS cray-rca:$PE_PKGCONFIG_LIBS".

**Comment by evan-charmworks** [comment]
*Original date: 2018-09-06 23:08:33*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4548~~ https://github.com/UIUC-PPL/charm/commit/fa02cb27e4cba0c4c900a25e91e2257181935311
