### ISSUE TITLE
Use C++ STL data structures in conv-conds.C

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1982]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1982*

---
Once we switch Converse over to C++, we can rewrite the data structures in conv-conds.c with STL containers rather than the homegrown C lists and heap used there.

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-04 19:20:16*

---
https://charm.cs.illinois.edu/gerrit/c/charm/+/4932

**Comment by stwhite91** [comment]
Needs some benchmarking and possibly performance optimization. Low priority for now so pushing off of 6.11

**Comment by stwhite91** [comment]
PR #2103 implements this, but has a known failure
