### ISSUE TITLE
charmxi fails silently on SDAG constructors

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1985]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1985*

---
charmxi should give a clear error that putting SDAG code in a chare constructor is not supported.

**Comment by stwhite91** [comment]
*Original date: 2018-10-06 00:54:17*

---
The documentation should also be updated to mention this restriction

**Comment by evan-charmworks** [comment]
*Original date: 2018-10-08 18:33:44*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4663~~ https://github.com/UIUC-PPL/charm/commit/155a7da0284982c62dca3e0594e8c4330b1f8441
