### ISSUE TITLE
Take advantage of streamable reductions inside CkMulticast

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1987]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1987*

---
ckreduction optimizes for streamable reductions (those that can be combined on the fly as they are processed). The original commit for streaming reductions mentions that it didn't add this same optimization to CkMulticast: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/904/~~ https://github.com/UIUC-PPL/charm/commit/17578a4b4303bd2ca61ec44130f0f93a4b3ff3ac

**Comment by stwhite91** [comment]
*Original date: 2018-10-08 00:51:34*

---
Related: https://charm.cs.illinois.edu/redmine/issues/1987

**Comment by stwhite91** [comment]
*Original date: 2019-01-17 19:17:55*

---
Could be done in 6.9.1 but we won't block 6.9.1 on it being done

**Comment by lvkale** [comment]
*Original date: 2019-03-14 19:40:25*

---
raghavendra, pleased pay attention to this during this week.

**Comment by raghavendrak** [comment]
https://charm.cs.illinois.edu/gerrit/c/charm/+/5128
