### ISSUE TITLE
pami-bluegeneq fails in tests/charm++/sdag/migration

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#1993]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1993*

---
Autobuild has a failure in `pami-bluegeneq` (but not any of the other PAMI targets). http://charm.cs.illinois.edu/autobuild/old.2018_10_07__01_01/pami-bluegeneq.txt

The problem first appeared in http://charm.cs.illinois.edu/autobuild/old.2018_09_28__01_01/pami-bluegeneq.txt, and while the day prior did not complete successfully ( http://charm.cs.illinois.edu/autobuild/old.2018_09_27__01_00/pami-bluegeneq.txt ), it did complete the test that now fails, `tests/charm++/sdag/migration`.

I suspect the problem is related to: ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4628~~ https://github.com/UIUC-PPL/charm/commit/4dac6a20b22cbdc4f4339db5c9c49f985fffb20a

**Comment by stwhite91** [comment]
*Original date: 2018-10-12 17:20:37*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4685/~~ https://github.com/UIUC-PPL/charm/commit/cf51efb6d43506b4e876386643afd1a477cb9f70
