### ISSUE TITLE
Fortran linking test fails with iccstatic

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1995]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1995*

---
icpc fails to link Fortran code in our configure test, so when trying to link a Fortran AMPI program we get:
```
Error: Configure testing was unable to link a Fortran program.
```

From charmconfig.out:
```
### whether the C++ linker succeeds with a Fortran entry point
      PROGRAM empty
      END PROGRAM
ifort -auto -fpic -c conftest.f90 -o test.o
icpc -static-intel -o testlink test.o -L/opt/intel/impi/2017.0.098/intel64//lib /opt/intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/../../compiler/lib/intel64/libifcore.a /opt/intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/../../compiler/lib/intel64/libifport.a /opt/intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/../../compiler/lib/intel64/libifcore.a /opt/intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/../../compiler/lib/intel64/for_main.o
icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
/opt/intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/../../compiler/lib/intel64/for_main.o: In function `main':
for_main.c:(.text+0x0): multiple definition of `main'

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-10-17 22:01:25*

---
I am able to reproduce this with `./build LIBS verbs-linux-x86_64-smp iccstatic` after applying ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/4709~~ https://github.com/UIUC-PPL/charm/commit/2600827d56a6653334fb7bd4b080c3cd3a7e20eb.

**Comment by stwhite91** [comment]
*Original date: 2018-10-17 22:16:56*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4710/~~ https://github.com/UIUC-PPL/charm/commit/e62f3b8217bc9388f73d840a91437221ff2fc1d1
