### ISSUE TITLE
Bug record/replay may hang in SMP

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#1999]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1999*

---
pretty sure tests exist for record replay, but they are either not being run, or are not exercising a lot of code in ck.C

try some experiments with that in the context of coverage analysis to find out what needs to be done to improve measured coverage.

**Comment by ericjbohm** [comment]
Record replay can be shown to hang on current master on netlrts-linux-x86_64-smp using simplearrayhello.

./charmrun ./hello 20 +p8 ++ppn 8 +record
.
.
.


./charmrun ./hello 20 +p8 ++ppn 8 +replay
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 1.378 seconds.
Charm++> Running in SMP mode: 1 processes, 8 worker threads (PEs) + 1 comm threads per process, 8 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.9.0-383-g97572b27c
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> replay mode.
Charm++> Warning: disabling message integrity detection during replay (requires linking with -memory charmdebug)
Charm++> Running on 1 hosts (1 sockets x 6 cores x 2 PUs = 12-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 8 processors for 20 elements
[0] Hello 0 created
[0] Hello 1 created
[0] Hello 2 created
[3] Hello 9 created
[6] Hello 16 created
[2] Hello 6 created
[5] Hello 14 created
[1] Hello 3 created
[5] Hello 15 created
[1] Hello 4 created
[6] Hello 17 created
[1] Hello 5 created
[4] Hello 12 created
[2] Hello 7 created
[7] Hello 18 created
[4] Hello 13 created
[7] Hello 19 created
[2] Hello 8 created
[3] Hello 10 created
[3] Hello 11 created
[0] Hi[17] from element 0
[0] CkMessageReplay> Message EP changed during replay org: [0 112 58 136] got: [0 80 58 59]
[0] CkMessageReplay> Message EP changed during replay org: [0 112 58 136] got: [0 80 58 59]

**Comment by ericjbohm** [comment]
Unable to reproduce that bug on non-smp.  Appears to be a race condition of some sort as I have not found it on 4 PEs, but it is easily produced on 8.

**Comment by evan-charmworks** [comment]
I can reproduce this on the first try with this one-liner:

`./build charm++ netlrts-linux-x86_64-smp --enable-replay -j12 -g3 && pushd netlrts-linux-x86_64-smp/tests/charm++/simplearrayhello/ && make -j12 OPTS="-g3" && while true; do ( rm -f *.log* && ./hello 20 ++ppn 8 +record && ./hello 20 ++ppn 8 +replay || break ); done`

Unfortunately when I add TSan I can no longer reproduce it.

`./build charm++ netlrts-linux-x86_64-smp --suffix=tsan --enable-replay -j12 -g3 -fsanitize=thread && pushd netlrts-linux-x86_64-smp-tsan/tests/charm++/simplearrayhello/ && make -j12 OPTS="-g3 -fsanitize=thread" && export TSAN_OPTIONS='log_path=tsan.log' && while true; do ( rm -f *.log* && ./hello 20 ++ppn 8 +record && ./hello 20 ++ppn 8 +replay || break ); done`

**Comment by ericjbohm** [comment]
The bug appears to originate in the record phase.  That is, when it is reproducible, it is typically from a recording from which the replay always fails in roughly the same way.  When it is not reproducible, the replay never fails. This implies that the non-determinism is in the recording, where we must have some sort of cross wiring or corruption in the message trace.

 When extra debugging is enabled, you can see results like:

Hi[17] from element 0
[0] ProcessMessage message: 0 112 59 21 11 ep:136
[0] Queueing message: 0 112 59 136 because we wanted 0 112 58 136
[0] requeueing delayed message: 0 112 59 ep:136
[0] ProcessMessage message: 0 80 58 5 0 ep:59
CkMessageReplay> Message EP changed during replay org: [0 112 58 136] got: [0 80 58 59]

Where that sort of throwback Queueing and/or requeueing event always presages the hang and never occurs when there is no hang.  +recplay-xor or +recplay-crc don't seem to be useful at detecting corruption in this case.  But the Message EP emission is indicative of something going off the rails.

**Comment by evan-charmworks** [comment]
Reproducible in multicore too: `./build charm++ multicore-linux-x86_64 --enable-replay -j12 -g3 && pushd multicore-linux-x86_64/tests/charm++/simplearrayhello/ && make -j12 OPTS="-g3" && while true; do ( rm -f *.log* && ./hello 20 ++ppn 8 +record && ./hello 20 ++ppn 8 +replay || break ); done`

**Comment by ericjbohm** [comment]
The problem seems to be due to event ID ordering non-determinism.  That is, it isn't strictly a record bug, nor a replay bug, in the strictest sense.  It is a violation of the assumption that the original partial ordering of events will be reproduced globally if replayed in order.  What we see in practice is that is true for non-smp mode (so far), but is not reliable for SMP.

For example: in SMP mode we see this cascade of failure:
[0] Hi[17] from element 0
[0] ProcessMessage message: 0 112 59 21 11 ep:136
[0] Queueing message: 0 112 59 136 because we wanted 0 112 58 136
[0] requeueing delayed message: 0 112 59 ep:136
[0] ProcessMessage message: 0 80 58 5 0 ep:59
[0] CkMessageReplay> Message EP changed during replay org: [0 112 58 136] got: [0 80 58 59]

Where non-smp has:
[0] Hi[17] from element 0
[0] ProcessMessage message: 0 112 59 21 11 ep:136
[0] Executing message: 0 112 59
[0] getNext: 0 112 60
[0] Hi[18] from element 1
[0] ProcessMessage message: 0 112 60 21 11 ep:136
[0] Executing message: 0 112 60

Because in the recorded track the message was event ID 58, but in the replay the message we got was event ID 59.  The problem starts with an off by one error where event id enumeration disagrees between record and replay because the event ID assignment has some non-determinism.  Actual recorded message counts are identical across SMP vs non-SMP.  However there are large holes in the recorded event ID cardinality. That is, there are many incidents where the event id is incremented, but the incremented event does not appear in any recorded trajectory.  I expect that the non-determinism is in those events, such that one or more of them occur in an order that is independent of the message processing order.  That difference then impacts the event ID count and perturbs the replay by creating a mismatch.

**Comment by ericjbohm** [comment]
#2408 fixes this issue by not incrementing envelopeEventID inside of initDone->sendTriggers. As that is reached by a non-deterministically set PE, and the rest of the queue processing is inaccessible to record/replay, incrementing with the envelope there perturbs the count non-deterministically.

**Comment by evan-charmworks** [comment]
Fixed by #2408
