### ISSUE TITLE
Reduce memory usage of reductions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#2]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2*

---
The current system for reductions buffers input messages at each node of the tree until every input has been received. For many kinds of reductions, this is wasteful, because they can be processed continuously (e.g. logical, int, min/max), or they could be processed in some smaller increment, forming a tree over the messages with good accuracy (e.g. FP addition).

**Comment by PhilMiller** [comment]
*Original date: 2013-02-06 00:57:37*

---
This will be much easier when #12 is done, since it will only need to be done once.

**Comment by PhilMiller** [comment]
*Original date: 2013-09-17 20:32:00*

---
Still blocked on integration of reduction starting work, #29. Thus, deferring to next release.

**Comment by rbuch** [comment]
*Original date: 2015-11-10 02:01:42*

---
This is done for everything except section reductions.

Gerrit Link: ~~https://charm.cs.illinois.edu/gerrit/#/c/904/~~ https://github.com/UIUC-PPL/charm/commit/17578a4b4303bd2ca61ec44130f0f93a4b3ff3ac

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 02:58:53*

---
This seems large and risky enough that it should probably not hit a patch release, unless we can be very confident in it.
