### ISSUE TITLE
Warnings about ignored return values from scanf

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#20]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/20*

---
Quoth Nikhil:
> The following the warning I see very often while compiling codes (that I mentioned in the core meeting)-
> 
> ./../../bin/../include/ckstream.h: In member function ‘CkInStream& CkInStream::operator>>(int&)’:
> ../../../bin/../include/ckstream.h:189: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result
> ../../../bin/../include/ckstream.h: In member function ‘CkInStream& CkInStream::operator>>(unsigned int&)’:
> ../../../bin/../include/ckstream.h:190: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result

**Comment by nitbhat** [comment]
*Original date: 2015-10-27 02:44:20*

---
Tried running with -Wall using the GCC compiler. Used the ckin stream to accept an input variable. Could
