### ISSUE TITLE
Linking ChaNGa with -tracemode projections fails on gni crayxc

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2001]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2001*

---
Repeat by:
./build ChaNGa gni-crayxc hugepages smp --enable-tracing -j8 -O2
in changa directory:
./configure --enable-bigkeys
Edit Makefile to add "-tracemode projections"
make

The error is:
../charm/bin/../lib/libtrace-projections.a(trace-projections.o): In function `TraceProjectionsInit::TraceProjectionsInit(CkArgMsg*)':
trace-projections.C:(.text+0xe119): undefined reference to `CmiTimerAbsolute'
collect2: error: ld returned 1 exit status

**Comment by stwhite91** [comment]
*Original date: 2018-10-24 16:10:54*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4718/~~ https://github.com/UIUC-PPL/charm/commit/a72fe80e265fa6a6263204aeac61a1acbce73034
