### ISSUE TITLE
compiling charm++ applications on an omp build has many warnings.

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2005]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2005*

---
include/conv-mach-omp.h:1:0: warning: "CMK_TASKQUEUE" redefined
 #define CMK_TASKQUEUE 1
include/conv-autoconfig.h:365:0: note: this is the location of the previous definition
 #define CMK_TASKQUEUE 0

**Comment by stwhite91** [comment]
*Original date: 2018-10-23 16:46:47*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4722/~~ https://github.com/UIUC-PPL/charm/commit/5fe5043847c505b68a0f5616aeda6cb872ae80cb
