### ISSUE TITLE
netlrts: pipelining stdout is erroneous

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#201]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/201*

---
In netlrts, the code to close stdout, and pipe it to our buffer causes crash. The same code work in net layer.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 18:51:29*

---
Please follow up on this.  Feel free to ask others for help, but make sure it gets attention.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-24 22:09:22*

---
Was this eventually fixed in some fashion? Possibly with some connection to #237?

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-24 22:15:24*

---
Yes..I fixed it.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-28 00:43:30*

---
I'm guessing the fix for this was in commit:7e012acb936fed56e97af9280e20a35bb921a11b ?

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-28 00:46:32*

---
Yes.
