### ISSUE TITLE
Large scale openatom runs fail due to running out of element bits

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2014]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2014*

---
Reason: Failed to create a new ObjID due to running out of element bits!

**Comment by ericjbohm** [comment]
*Original date: 2018-10-25 15:44:32*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4729/~~ https://github.com/UIUC-PPL/charm/commit/619810d5b934690392a1f1cf99f32c5fe212961c

**Comment by ericjbohm** [comment]
*Original date: 2018-10-25 17:46:39*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4729/~~ https://github.com/UIUC-PPL/charm/commit/619810d5b934690392a1f1cf99f32c5fe212961c combined with building charm with -DCMK_OBJID_COLLECTION_BITS=13 addresses this issue.

**Comment by stwhite91** [comment]
*Original date: 2018-10-25 19:28:33*

---
I bumped the default back up to 40 element bits + 21 collection bits + 3 type tag bits in the 64-bit ObjID. I think the error messages are now clear enough that this is okay.
