### ISSUE TITLE
build issues associated with 6.9 RC

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2015]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2015*

---
See slack build discussion for details, attempts to replicate using clang7 have so far not been successful.  Root cause currently unknown.

**Comment by stwhite91** [comment]
*Original date: 2018-10-25 16:21:17*

---
Nils's build failures with clang7 seem to have been spurious.

The other failure was that he was building with CharmDebug support (non-production) and didn't have rpc/rpc.h: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4730/~~ https://github.com/UIUC-PPL/charm/commit/e8d6e0ccf486e6cb4a35c6b8bb0ccf844ee59120
