### ISSUE TITLE
Add "--enable-tracing --enable-tracing-commthread" to an autobuild target

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2019]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2019*

---
Turn tracing on in an SMP target and enable comm thread tracing for it as well, since we currently have no tests for it. Requested by Jim Philips since this was broken for months without anyone noticing.

**Comment by stwhite91** [comment]
Do we have this in CDash, @matthiasdiener ?

**Comment by matthiasdiener** [comment]
> Do we have this in CDash, @matthiasdiener ?

I just added a `netlrts-linux-x86_64 smp --enable-tracing --enable-tracing-commthread` build on ambition to CDash.
