### ISSUE TITLE
Alpine linux builds fail with "memory.C:310:3: error: '__malloc_hook' was not declared in this scope"

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2021]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2021*

---
Jozsef Bakosi found this and sent it to the mailing list. Also passing --disable-charmdebug fails weirdly.

**Comment by evan-charmworks** [comment]
*Original date: 2018-10-29 17:11:36*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4744~~ https://github.com/UIUC-PPL/charm/commit/ff0a5377b6c8f3cf844db399ed7e83d8d9c9bed1

**Comment by evan-charmworks** [comment]
For reference: https://lists.cs.illinois.edu/lists/arc/charm/2018-10/msg00008.html
