### ISSUE TITLE
Documentation is currently not being built

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2025]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2025*

---
The Charm++ manual has not been rebuilt in a few weeks, and is out of date. For example, this patch ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4578/~~ https://github.com/UIUC-PPL/charm/commit/efbcacd0062f33bb7bdd2473a5a741a52fa2fba0 is not reflected in the online manual. It seems that the machine building the manuals (panache) is down.

**Comment by stwhite91** [comment]
*Original date: 2018-11-02 21:33:15*

---
Moved doc build to the 'prowess' lab machine

**Comment by minitu** [comment]
*Original date: 2018-11-06 19:38:22*

---
Documentation built successfully on prowess.
