### ISSUE TITLE
Remove defunct causal and message logging fault tolerance code

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2034]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2034*

---
Disused and accumulating digital rust.

Mark for deprecations with compile time, runtime warnings.
Add remark to release notes.

Slated for removal in Charm 7.

**Comment by evan-charmworks** [comment]
*Original date: 2018-12-03 21:53:17*

---
Is causal mode included in this issue?

**Comment by ericjbohm** [comment]
mlogft and causalft are completely broken on master.  It would require a moderate amount of work to even get either to compile to the point where we could then verify whether deprecation warnings worked as expected.

might be better to just slice them out entirely (as we do in the Charmworks distribution) and put a note to that effect in the release notes.
