### ISSUE TITLE
xlC rejects initializer list in CpvInit_Alloc

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2035]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2035*

---
This change breaks xlC builds on Summit:

~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4623/~~ https://github.com/UIUC-PPL/charm/commit/1a8e95ee7c5ec0f88ec507b6091629e08b9895ff

It just added the {} here:
  #define CpvInit_Alloc(t,n) new t[n]{}

The error is "expression not supported".  Removing the braces allows it to build.

**Comment by jcphill** [comment]
*Original date: 2018-11-30 20:29:08*

---
Here is a simple example of the compiler limitation:
```
[jimp`login4.summit charm.new]$ cat mytest.C 
void foo() {
 int *i = new int[12]{};
}
[jimp`login4.summit charm.new]$ xlC -std=c++11 mytest.C 
mytest.C:2:22: error: 1540-2991 The expression is not supported.
 int *i = new int[12]{};
                     ^
1 error generated.
Error while processing mytest.C.

```

**Comment by jcphill** [comment]
*Original date: 2018-11-30 20:46:37*

---
I think that the following is equivalent and supported by xlC:

#define CpvInit_Alloc(t,n) new t[n]()

**Comment by jcphill** [comment]
*Original date: 2018-11-30 21:04:53*

---
Fix implemented as ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4842/~~ https://github.com/UIUC-PPL/charm/commit/bf40593b1d499140c5a16d29efa3c489d95ff3cd

**Comment by matthiasdiener** [comment]
This doesn't seem to be an issue anymore with newer XL compilers. V16.1.1 accepts the code mentioned by Jim above.
