### ISSUE TITLE
Memory gnu should be updated with newer ptmalloc

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#204]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/204*

---
ptmalloc has been updated and our memory gnu should follow.

1. try memory gnu targets with memory os to see if memory os is a sufficient default
(this has already been implemented by Nikhil, but the results need to be analyzed)
2. get rid of memory-old
3. add memory pt target
4. deprecate memory-gnu for future removal 

changes to malloc
a. high water mark counters
b. function name changes

Could change to using mallinfo hooks instead of counters, but the name changes require source alteration.  For long term compatability we should study the plausibility of re-architecting this scheme to rely entirely on API hooks and wrappers rather than renaming and hacking in counter tracking code.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-10 22:49:30*

---
This is all wrapped up, right? We can just close this, I think.
