### ISSUE TITLE
Add [whenidle] to simplify speculative execution

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2042]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2042*

---
There are various cases where some computation can be done in the absence of other work, but would be of a low priority, or speculative.  In such cases it might be desirable to have an entry method triggered by a CcdIdle event which could perform the speculative work if there is nothing better to do.  this can currently be manually implemented by setting a Ccd and having the callback queue itself again via CCD, but this involves some moderately ugly code that could be trivially generated automatically.  So the only new aspect to this is that it would reduce the burden on the developer to implement this and the activity would be more naturally traced and visible in the Charm++ parallelization instead of hidden in chain of callbacks that don't even have to be entry methods.

Several refinements could be applied here, possibly as a parameterized elements such as whether the ide callback should only be called once, or every time sustained idle is detected.  Furthermore, additional parameterization could set a threshold for how much idleness is necessary to trigger the event,

**Comment by stwhite91** [comment]
*Original date: 2019-01-03 18:21:17*

---
If you have an example of the ugly Ccd code to do this, could you post it here? I anticipate needing to implement this myself soon

**Comment by ericjbohm** [comment]
*Original date: 2019-01-03 18:38:46*

---
Basic pattern (without templates or dependencies on more than C based trickery) is:

```
static void idleProgress(void *myObj, double time){
  MyClass *m= static_cast<MyClass *>(myObj);
  if(m->speculativeWork()) m->registerIdleProgressFunction();
}

void MyClass::registerIdleProgressFunction()
{
  CcdCallOnCondition(CcdPROCESSOR_STILL_IDLE, &idleProgress, (void *) this);
}
```

In this scheme, the speculativeWork function returns a boolean to indicate that is worth checking for speculative work on future idle invocations.   That allows us to avoid future overhead of checking if we know for certain within the scope of the speculativeWork function that there will be nothing more to do.  The application can re-register if that changes.

**Comment by Wingpad** [comment]
Catching up to speed here, can you verify that my understanding of this is correct? The `[whenidle]` property will register a `PROCESSOR_STILL_IDLE` callback for the Chare that invokes any `[whenidle]` entry method(s) when it is triggered and then automatically requeue itself. Do we expect there to be conditions under which it wouldn't automatically requeue itself? Like, will the entry method be required to return a boolean to indicate it has speculative work remaining?

Assuming I am understanding this correctly, this seems like it should be straightforward for me to do 👍

**Comment by stwhite91** [comment]
Yes I'd expect for users to want to control whether or not they re-register the CcdCallback. One use case would be during one phase of an application they want to register a [whenidle] method to know when things on that PE are done running, and in another phase they want a different [whenidle] method. For each phase, whenidle might execute the callback multiple times, and the user can check if they are done or not and re-register the method. I think a return boolean would be a good API for that. @ericjbohm ?

**Comment by Wingpad** [comment]
Ah, I see. How shall we have the user indicate which phase the application is in, and which phase a [whenidle] method should be registered/called in? Does Charm already have some general-purpose notion of phases as such that we can adapt for these purposes?

**Comment by stwhite91** [comment]
I think it can be even simpler than that. This is what I am imagining:
```
// This entry method is invoked after it has been both registered via CkCallWhenIdle() and the PE has become idle
entry [whenidle] bool idleProgress(double time) {
  return speculativeWork(); // returns true if it wants to remain registered to be called whenever idle, false to de-register itself
}

{ // Inside some arbitrary entry method
  CkCallWhenIdle(CkIndex_MyClass::idleProgress());
}
```

So basically the `[whenidle]` attribute just gives some syntactic sugar around the C function with its void* arg and casting that to a class object, plus we cleanup the API call for registering the callback too.

Also `[whenidle]` should behave like a `[local]` entry method, only call-able locally/inline from the scheduler.

**Comment by ericjbohm** [comment]
I think that captures the expected use case.  The return value indicates the application level expectation regarding whether it is likely to be worth future calls to speculativeWork.  

We want to provide the option of putting a specific entry method with a [whenidle] back into the call Idle list at some later point.  Notionally this may be in some specific phase.  Charm doesn't have support for identifying phases at this time, but the application almost always does.  So the core part of the concept is that we provide a way for the user to easily put their _idleProgress_ back into the notional "idle queue", and have it dropped from said queue by returning false.

At some future point, probably within a control point framework, this sort of thing might be handled more automatically, or adjusted introspectively.  But to get to that point we need the basic functionality to be available.

**Comment by Wingpad** [comment]
Alright, thanks for the clarification @stwhite91, that makes a great deal of sense. I will get to working on this.

**Comment by Wingpad** [comment]
Started working on this recently, and a couple of questions have come up. Namely, it seems like this keyword will have to add methods to the user's implementation of the class a la SDAG. For example, consider the user's class `Test` that has a `[whenidle]` entry, it will need functions like:

    class Test : CBase_Test {
        static void __ckIdleCallback(void *self, double time) {
            // call all local entry methods tagged with whenidle
            // re-register those that return true
        }

        void CkRegisterIdleWork() {
            CcdCallOnCondition(CcdPROCESSOR_STILL_IDLE, &__ckIdleCallback, (void *)this);
        }

        // ...
    }

Question is how best to achieve this, shall I co-opt the existing `_SDAG_CODE` macro or make a new macro for this purpose? Make `CBase_` an abstract class that implements these functions rather than a simple `typedef`? Alternatively, is adding this member to the user's class even necessary?

**Comment by stwhite91** [comment]
Hmm, this is more messy than I thought...

I was imagining that `CkCallWhenIdle();` would be a free function defined by the runtime as something like the following:
```
void CkCallWhenIdle(int ep, void *objPtr) {
      void* ep_func = _entryTable[ep]->call;
      CcdCallOnCondition(CcdPROCESSOR_STILL_IDLE, ep_func, objPtr);
}
```
Charmxi would need to generate a static C function that wraps the type cast from void* to MyClass* and calls the local entry method directly. It would then conditionally re-register the CcdCallback based on the method's return value. We might need to store the C function pointer separately from the proper entry method... could be in the entryTable object or maybe somewhere else? I think this will work without needing the SDAG-like macro, but I may be missing something

**Comment by Wingpad** [comment]
Alright, I might be over-thinking this then.  As far as that goes, I'm not sure how to capture the return value of an entry method from a `CkCallback`. If there's an easy way to do that, we could probably do it that way without the macro.

**Comment by Wingpad** [comment]
Ah, I think I understand what you meant now. I was getting thrown off by the fact that call functions for `[local]` entry methods are uncallable, but you were suggesting adding a new type of "call function" that is callable in this way. I will think about how to add this new function to the entryTable (perhaps as a new field in `EntryInfo`) or storing it elsewhere.
