### ISSUE TITLE
Potential GCC 8 Hang

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#2047]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2047*

---
A NAMD user has emailed the NAMD mailing list with the following:

> So you can take pure NAMD/Charmm++, build it with GCC8 compilers and
> try to run - you'll receive the same hang behavior (at least on our
> computers which are employs the same environment it's true).
> 
> Plumed team is already maintains NAMD-2.12 and 2.13 version, but once
> again - seems like the problem is related to the newest GCC compilers,
> not Plumed

> One important note: when hang occurs all dedicated CPUs (i. e., via
> namd2 +pN) are fully busy.

Thus, it seems like there may be some issue with gcc 8 or other new versions of the compiler in NAMD or in Charm++.

**Comment by jcphill** [comment]
NAMD user has updated his report:
Just recompiled git version of NAMD with CUDA 9 and 10 (separately). New GCC is installed (8.3.0).
Now simulation doesn't stuck at the very beginning but after short time it naturally explodes for unknown reason. NAMD compiled with GCC-7.3.1 works fine (for both CUDA versions).

**Comment by stwhite91** [comment]
Every hear anything more about this from the NAMD user? Should we close the issue?

**Comment by jcphill** [comment]
I assume it is still a problem.
