### ISSUE TITLE
Build script does not support thread sanitizer

### ISSUE THREAD

**Issue by VenkatSNarayanan** [UIUC-PPL/charm#2052]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2052*

---
The build script does not support building Charm++ with the GCC thread sanitizer.

**Comment by stwhite91** [comment]
*Original date: 2019-02-07 18:59:05*

---
Can you update the issue with the failed output?

In general when reporting an issue you should provide how exactly to reproduce the issue (your full charm build command, what type of build/environment if applicable, how to run the test case if applicable) as well as the output from whatever failed.

**Comment by evan-charmworks** [comment]
*Original date: 2019-02-12 23:44:11*

---
I was able to run with TSan successfully using these lines:

```
./build all-test multicore-linux-x86_64 tsan -j12 -g3 -fsanitize=thread && cd multicore-linux-x86_64-tsan/tests/charm++/simplearrayhello && TSAN_OPTIONS="log_path=log.txt" ./hello +p2
```

```
./build all-test netlrts-linux-x86_64-smp tsan -j12 -g3 -fsanitize=thread && cd netlrts-linux-x86_64-smp-tsan/tests/charm++/simplearrayhello && TSAN_OPTIONS="log_path=log.txt" ./hello +p2
```

(The redundant `-fsanitize=thread` is so that the tests and examples see the flag and not just the RTS.)

**Comment by DictatorXBlade** [comment]
*Original date: 2019-03-21 17:08:20*

---
It turns out that the problem is with the GCC version used to build Charm++ - GCC 4.x does not properly support the thread sanitizer.
