### ISSUE TITLE
Improve error message for unregistered chares/entry methods for when a module isn't visible

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2054]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2054*

---
The current error message says something about templated entry methods not being registered, but it should also mention that the error can result from not registering a module.

The offending error message is in CkRegisterEpInternal() inside src/ck-core/register.C

**Comment by evan-charmworks** [comment]
*Original date: 2019-03-21 23:21:15*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5033~~ https://github.com/UIUC-PPL/charm/commit/b030a29768673d67c68107081df90fc01494bb25
