### ISSUE TITLE
AMPI ROMIO fails to build when MPI_LIB is set

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2056]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2056*

---
After an AMPI user updated from an older version of AMPI they are now getting this error:

```
./build AMPI mpi-linux-x86_64 --destination=/home/charm-prod gcc


-----------
Building ROMIO
cd romio && \
        CFLAGS="" \
        FFLAGS="" \
        F77=/home/charm-prod/bin/ampif90 \
        CC=/home/charm-prod/bin/ampicc \
        ./configure \
        --disable-aio \
        --enable-f77=`test -f /home/charm-prod/lib/libmoduleampif.a && echo yes || echo no` \
        --srcdir=`pwd`
Configuring with args --disable-aio --enable-f77=yes --srcdir=/home/charm-prod/tmp/libs/ck-libs/ampi/romio
checking whether clock skew breaks make... no
checking whether make supports include... no
checking whether make allows comments in actions... no
configure: WARNING: Your make does not allow comments in target code.
Using this make may cause problems when building programs.
You should consider using gnumake instead.
checking for virtual path format... VPATH
checking whether make sets CFLAGS... yes
checking for architecture... LINUX
configure: WARNING: Unknown architecture ... proceeding anyway
ROMIO home directory is /home/charm-prod/tmp/libs/ck-libs/ampi/romio
configure: error: MPI library /opt/tools/openmpi-3.1.2-gcc-7.2.0/lib not found
gmake[2]: *** [/home/charm-prod/lib/libampiromio.a] Error 1
gmake[2]: Leaving directory `/home/charm-prod/tmp/libs/ck-libs/ampi'
gmake[1]: *** [ampi] Error 2
gmake[1]: Leaving directory `/home/charm-prod/tmp/libs/ck-libs'
gmake: *** [AMPI] Error 2
```

The error that /opt/tools/openmpi-3.1.2-gcc-7.2.0/lib is weird because that does exist.

**Comment by matthiasdiener** [comment]
*Original date: 2019-03-05 16:40:57*

---
Does the user have an "MPI_LIB" environment variable set when building AMPI? This variable should be unset before building.

**Comment by evan-charmworks** [comment]
*Original date: 2019-03-05 19:34:34*

---
We've let the user know about `MPI_LIB` and are awaiting feedback.

**Comment by matthiasdiener** [comment]
*Original date: 2019-04-04 16:42:41*

---
Has there been any feedback from the user?

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-04 16:51:15*

---
The user decided to build with --without-romio so we don't know if MPI_LIB ended up being the problem. We should still document this.

**Comment by matthiasdiener** [comment]
*Original date: 2019-04-04 17:13:05*

---
~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5059~~ https://github.com/UIUC-PPL/charm/commit/143c31503241bd6fbfe504a60c864f381fcc22f9 implements a simple fix that unsets MPI_LIB before configuring ROMIO.
