### ISSUE TITLE
Revise agreement to cover github distribution and license to address all commercial use cases and GitHub Distribution

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2057]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2057*

---
Usage of Charm++ in a commercial context in a non-distributed, or purely internal, use case should be explicitly considered a commercial usage not covered by the free license.

Likewise, the current OTM agreement with Charmworks should be revised to permit GitHub distribution for the university non-commercial version.

Discussions are ongoing with OTM to agree on updated versions of these documents.

**Comment by matthiasdiener** [comment]
WIP patch here: https://charm.cs.illinois.edu/gerrit/c/charm/+/5061

**Comment by ericjbohm** [comment]
We have not been successful in getting a response from OTM this week.
