### ISSUE TITLE
Finish work on newLB branch and merge with master

### ISSUE THREAD

**Issue by juanjgalvez** [UIUC-PPL/charm#2058]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2058*

---
Currently tracking tasks here:
https://docs.google.com/document/d/1Amt4JvkfqMAerUk2w4HdvAbB4ySi2lq9mXvhaqQ4ChI/edit?usp=sharing

**Comment by evan-charmworks** [comment]
Was the consensus on this in Core to retarget for 6.11?

**Comment by ericjbohm** [comment]
Yes, too much left to do in this for 6.10, so re-milestone to 6.11.

**Comment by stwhite91** [comment]
Can this be closed?

**Comment by rbuch** [comment]
> Can this be closed?

Yeah, I think so, I'll do so.
