### ISSUE TITLE
Don't force -lcudart on non-CUDA programs when using CUDA build of Charm++

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2062]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2062*

---
If CUDA supposed is detected by configure it not only builds the CUDA features, but also modifies the link options for programs that do not use Charm++ CUDA support to include -lcudart, such that even CPU-only binaries cannot run without CUDA installed.

**Comment by minitu** [comment]
Gerrit patch: https://charm.cs.illinois.edu/gerrit/#/c/charm/+/5176/

**Comment by minitu** [comment]
Jim is only talking about the CUDA build of Charm++ here. At the time, non-CUDA programs were forced to link in the CUDA libraries because of the contents of `src/arch/common/conv-mach-cuda.sh`.

**Comment by matthiasdiener** [comment]
The patches to fix this cause more problems, reverting them for now (#2466). Reopening this issue.

**Comment by jcphill** [comment]
> Jim is only talking about the CUDA build of Charm++ here. At the time, non-CUDA programs were forced to link in the CUDA libraries because of the contents of `src/arch/common/conv-mach-cuda.sh`.

Actually, I was talking about non-CUDA builds of Charm++, and the fix I was expecting was to not do anything CUDA-dependent unless the user explicitly requested CUDA when building Charm++. The new issue title is incorrect.

**Comment by minitu** [comment]
@jcphill The file that forces programs to link in the CUDA library, `src/arch/common/conv-mach-cuda.sh`, isn't it only used in CUDA builds? Currently I don't think there's anything CUDA-related that is required unless Charm++ is built with `cuda`.

**Comment by jcphill** [comment]
The problem is/was that if nvcc etc. was detected by configure it would automatically enable the CUDA features in Charm++ even if they were not requested.

**Comment by jcphill** [comment]
In any case, I can't seem to reproduce this anymore.

**Comment by matthiasdiener** [comment]
Looking at the current code in `configure.ac`, `Makefile`, and `conv-mach-cuda.sh`, cuda support shouldn't be activated without the user explicitly specifying the `cuda` option . Closing this for now.
