### ISSUE TITLE
CkCallback::ckExit does not work with interop mode

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#2063]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2063*

---
Instead of calling CkExit, which is redefined by mpi-interoperate.h to only exit the library and stop the charm scheduler, it calls the full CkExit and exits the program.

**Comment by evan-charmworks** [comment]
*Original date: 2019-04-12 17:19:26*

---
This is probably a matter of undefining (and redefining?) the macro magic to allow an optional parameter in C.

**Comment by epmikida** [comment]
*Original date: 2019-04-19 03:54:32*

---
Messing with the macro wouldn't really work. It's the fact that the CkExit macro is redefined for interop mode. But that redef is only visible to files which include the interop header. CkCallback does not, so it calls regular CkExit instead of LibCkExit. I don't think this change is feasible to do at compile time, but considering its a one time callback, I don't think that matters.

Implementation here: ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5106~~ https://github.com/UIUC-PPL/charm/commit/35cdcdd045086dc13e3ce2e6054a77c4f97c788f
