### ISSUE TITLE
Change issue links from Redmine to GitHub

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2071]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2071*

---
* In Charm++ itself: ~~https://charm.cs.illinois.edu/gerrit/c/charm/+/5089~~ https://github.com/UIUC-PPL/charm/commit/115dc1b0f8a63dbd6864bfcd0fc5277ab44882a7
* Websites:

   * ~~https://charm.cs.illinois.edu/download/ (Charm++ bug tracking)~~
   * http://charmplusplus.org/ (Main Menu: Follow -> Issue Tracker)
* Others?

**Comment by minitu** [comment]
PPL website link fixed: http://charm.cs.illinois.edu/software

**Comment by rbuch** [comment]
Updated [charmplusplus.org](http://charmplusplus.org), too.
