### ISSUE TITLE
Excessive execution times in Converse's commbench on dual-core systems

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2076]
Converse's commbench test (which is run with 4 PEs) takes a long time (>20 minutes) to run on systems that have only two cores. This currently prevents integration with Travis CI as the tests simply time out. The worst offenders are `pingpong`, `pingpong-cachemiss`, and `reduction`.

Possible solutions:
- Run with only 3 PEs
- Run with `min(4, #cores)` PEs
- Generate more output during execution such that Travis does not think that the tests are hanging
- others?

**Comment by matthiasdiener** [comment]
Since #1872 is merged, this isn't a big problem anymore. All Travis CI tests finish in about 20 minutes.

**Comment by evan-charmworks** [comment]
Is there a way to reproduce this outside of the CI VMs? I tried passing variations of `+pemap 0`, `+pemap 0,1`, etc but could not cause the 20 minute runtime described here.

**Comment by evan-charmworks** [comment]
Running with `+p16` on an 8-SMT Mac was sufficient to reproduce the issue.

Using the command `( for i in timer flood ctxt memoryAccess overhead proc broadcast smputil reduction pingpong pingpong-cachemiss ; do time ./charmrun ./pgm +p16 ++local -only $i ; done ) >output.txt 2>&1` I was able to gather this data:

| Test | Duration |
| --- | --- |
| timer | 0m1.638s |
| **flood** | **7m4.769s** |
| ctxt | 0m8.548s |
| memoryAccess | 0m1.719s |
| overhead | 0m0.383s |
| proc | 0m0.497s |
| **broadcast** | **2m5.582s** |
| smputil | 0m0.494s |
| **reduction** | **4m48.578s** |
| **pingpong** | **5m27.217s** |
| **_pingpong-cachemiss_** | **_23m34.624s_** |

**Comment by evan-charmworks** [comment]
These long-running tests are skipped under oversubscription as part of #2990, so unless the performance degradation itself needs to be fixed, this issue is resolved.
