### ISSUE TITLE
Port miniFE to Charm++

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#222]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/222*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2017-08-14 14:59:31*

---
This is now done, after having sat idle for a long time.

charmgit:benchmarks/mantevo/miniFE-2.0

**Comment by pplimport** [comment]
*Original author: Justin Szaday*
*Original date: 2017-08-14 15:04:06*

---
Well, I think there was an unfixed issue with reproducibility with this. When running on multicore builds it seems to work perfectly but on netlrts/multinode builds it will occasionally fail (I don't remember how). I meant to look at this but ended up getting caught up with other things.
