### ISSUE TITLE
Replica on Titan is slow

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#223]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/223*

---
Jim reported that replica with cuda on Titan is extremely slow. Probable bug with redirecting stdout, or with cuda usage.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 21:52:39*

---
Retitle to be more descriptive

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-07 03:19:41*

---
This bug seemed to have been a side effect of #229. Jim has confirmed, and I will mark the bug resolved.
