### ISSUE TITLE
Bug: undefined CthScheduled

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2268]
Using OmpCharm as the thread implementation for OpenMP requires ABI support.  The recent conversion from c to C introduced a bug.  The conversion preserved the inline declaration for CthScheduled.  However, CthScheduled is part of the implementation of kmp_runtime and kmp_barrier in OmpCharm.   Therefore, it needs to be externally visible at link time.  However, in C++ inline in the C (or CPP) implementation does not support the creation of an externally accessible symbol for the function signature.  Its also probably pointless as the compiler is just going to ignore your non header based inline regardless.

It might be possible to arrive at a clean way to do this solely in the converse.h file, but that creates a certain amount of confusion.  The right answer is probably creating a threads.h file and moving all the Cth functions to it from converse.h.  However, that may be a fairly disruptive change.  The basic problem can be solved by removing the inline.

**Comment by evan-charmworks** [comment]
I can look at this if you would like.

**Comment by matthiasdiener** [comment]
Also pinging @sbak5 .

**Comment by evan-charmworks** [comment]
@ericjbohm mentioned he had a patch for this.

**Comment by ericjbohm** [comment]
I'll issue a pull request for it later today.
