### ISSUE TITLE
Is this project open to contribution by outside developers (non UIUC faculty/students)? 

### ISSUE THREAD

**Issue by utkarsh5k** [UIUC-PPL/charm#2271]

**Comment by matthiasdiener** [comment]
Yes, we are open to external contributors. Please note that contributions are
subject to our license agreement, as specified in the LICENSE file.

We are currently working on a formal Contributor License Agreement (CLA) and
will inform external contributors when this will be required.

Please let us know if you have any questions.

**Comment by matthiasdiener** [comment]
Closing this issue. Please feel free to reopen if there are additional questions.
