### ISSUE TITLE
After make install, ampicc & ampicxx still refer the the `tmp` directory

### ISSUE THREAD

**Issue by marmistrz** [UIUC-PPL/charm#2275]
I'm the maintainer of the AMPI package for Arch Linux. The package is built in the following way: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ampi-openmpi

The tree produced by `make install` should contain no references to the `tmp` build directory. Unfortunately, `ampicc` and `ampicxx` still contain such references, precisely
```
charmarch=$(cat $CHARMBIN/../tmp/.gdir)
```

You may consider using `set -e` in your shell scripts, which will make sure that the script will terminate upon first error.

**Comment by matthiasdiener** [comment]
Thank you for the bug report. In the current git version, `ampicc` and the other AMPI shell scripts do not refer to the `tmp/` directory anymore. 

For version 6.9.0, since you are using the MPI layer explicitly, you could patch the line 
```
charmarch=$(cat $CHARMBIN/../tmp/.gdir)
```

with 
```
charmarch="mpi"
```

**Comment by marmistrz** [comment]
Thanks for the quick reply. 
If the issue is fixed in master, then I'm fine with just working it around for the time being. Feel free to close this issue.

**Comment by matthiasdiener** [comment]
Thanks for the feedback, I'll close this issue.
