### ISSUE TITLE
net-win32 configuration runs in a semi-smp mode 

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#228]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/228*

---
conv-mach file for net-win32 produces configurations that is partially SMP - locks enabled, shared variables but no CMK_SMP. Investigate the cause.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-05 22:39:28*

---
Gengbin, do you know why is it so?

**Comment by PhilMiller** [comment]
*Original date: 2016-03-18 21:21:52*

---
Do we have any reason to ever again care about 32-bit windows builds? If not, I'd suggest deassigning this bug and setting it to status 'Rejected'

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 20:11:20*

---
`net-win32` got deleted some months back. This is now moot.
