### ISSUE TITLE
bug: VERBS crashes  or hangs during launch for CharmVSS on large problems

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2286]
Works fine in Charm 6.9.  Works fine when built on UCX layer.

Will try some bisecting tonight to pin down what change introduced this bug.  This also impacts attempts to replicate #1671, as we would need verbs to not implode to evaluate pinned memory leaks,  and may or may not be related to #1473

**Comment by ericjbohm** [comment]
Bisected it to 5cb7ba2302c080e57ff34a8180e5f5b0bc553f33 as the commit that created this bug.

**Comment by nitbhat** [comment]
The crash is fixed by https://github.com/UIUC-PPL/charm/pull/2290. 

I'm going to investigate the hang now.

**Comment by ericjbohm** [comment]
Tested with master on xyz_428, no problems.
