### ISSUE TITLE
resource sets on Summit break CPU affinity

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2307]
When running on Summit on 4 nodes with 6 resource sets per node, 7 cores per resource set, recent Charm++ builds give the following errors:

> Charm++> cpuaffinity PE-core map : 0-83:4,88-171:4
> Error> Invalid core number 24, only have 7 cores (0-6) on the node.
> ...

So something is looking at the size of the resource set and concluding that it represents the range of CPU IDs on the node.

When I try +pemap 0-6 I get the following complaints:

> Charm++> cpuaffinity PE-core map : 0-6
> HWLOC> Couldn't bind to cpuset 0x00000001: Invalid argument
> HWLOC> Couldn't bind to cpuset 0x00000002: Invalid argument
> HWLOC> Couldn't bind to cpuset 0x00000020: Invalid argument
> HWLOC> Couldn't bind to cpuset 0x00000004: Invalid argument
> HWLOC> Couldn't bind to cpuset 0x00000004: Invalid argument
> ...
> Charm++> Running on 4 hosts (1 sockets x 7 cores x 1 PUs = 7-way SMP)
> ...
> Charm++> Warning: the number of SMP threads (42) is greater than the number of physical cores (7), so threads will sleep while idling. Use +CmiSpinOnIdle or +CmiSleepOnIdle to control this directly.

So clearly the pemap should be expressed as the actual CPU ID, not relative to the resource set. Worse is the final lines, which confuses the resource set with the node size.

This used to work fine and is now a serious performance issue.

**Comment by evan-charmworks** [comment]
Does #2265 help with this?

**Comment by jcphill** [comment]
> Does #2265 help with this?

I'd have to test. Should it? I don't know what "in terms of hwloc PUs" means.

I'm also wondering what change broke it.

**Comment by evan-charmworks** [comment]
At the least I would expect it to resolve the `Invalid argument` errors shown in your log.

**Comment by jcphill** [comment]
Would I need to specify +pemap 0-6 or could I return to +pemap 0-83:4,88-171:4 that used to work.
If I have to use +pemap 0-6 that's a change from previous behavior.

**Comment by evan-charmworks** [comment]
I'm not sure. If `+pemap 0-83:4,88-171:4` still does not work then that is something I need to fix for 6.10.

hwloc was only introduced to Charm++ after the release of v6.8.2 in the Git history and debuted officially in v6.9.0. The first commit that replaces the original CPU binding code with an hwloc-based implementation is d551b71f3d27305c280d2179014252d810d10d93 and there are several more after that. I would expect any regressions in this area to date back to these changes.

**Comment by jcphill** [comment]
With https://github.com/UIUC-PPL/charm/pull/2265 I can set affinity with +pemap 0-6, but I still get
> Charm++> Running on 4 hosts (1 sockets x 7 cores x 1 PUs = 7-way SMP)

and
> Charm++> Warning: the number of SMP threads (42) is greater than the number of physical cores (7), so threads will sleep while idling. Use +CmiSpinOnIdle or +CmiSleepOnIdle to control this directly.

If I add +CmiSpinOnIdle the oversubscription warning goes away.

The change to +pemap 0-6 is actually helpful that it provides a way around https://github.com/UIUC-PPL/charm/issues/1000

**Comment by jcphill** [comment]
The initial breakage is due to 0e35414d which asserts for CmiNumCores() that "PU count is the intended output here rather than literal cores", in which case we need to either add a CmiNumPhysicalCores() or change CmiNumCores() to CmiNumHwlocPus().

**Comment by evan-charmworks** [comment]
Are you sure the problem is with the designation of PUs as the intended meaning of "Cores" alongside other anachronistic terms in the runtime such as "Processors", and not with the replacement of bespoke CPU information lookup with hwloc's values?

**Comment by jcphill** [comment]
It looks like hwloc is fine for describing the layout of the resources available to an isolated process, but it does not describe the layout of the entire host on which that process is running, and therefore does not allow reliable inference of resource conflicts with other processes on the same host.

**Comment by jcphill** [comment]
There is a good description at https://www.open-mpi.org/projects/hwloc/doc/v2.0.4/a00326.php#faq_indexes and https://www.open-mpi.org/projects/hwloc/doc/v2.0.4/a00313.php of physical/OS vs logical indices. Since +pemap and +commap have traditionally used physical indices, it would be extremely disruptive to change their meaning to logical indices.

**Comment by evan-charmworks** [comment]
I agree that `+pemap` and `+commap` should mean the same things they did in v6.8.2.

**Comment by evan-charmworks** [comment]
Fixed by #2265
