### ISSUE TITLE
Manual unclear or incorrect on setting LB period

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#2312]
In section 2.2.6.5 of the manual, it states that the `LBSetPeriod` function can be called from anywhere to set the LB period. However, in practice it doesn't seem to do anything. `+LBPeriod` on the command line seems to still work just fine.

Either the manual is incorrect, or unclear on where/how it needs to be called, or the `LBSetPeriod` function is buggy.

**Comment by stwhite91** [comment]
Is this irrelevant now with the new LB framework?

**Comment by stwhite91** [comment]
Bump ^^^

**Comment by rbuch** [comment]
Fixed in https://github.com/UIUC-PPL/charm/pull/3251/.
