### ISSUE TITLE
Allow autobuild infrastructure to perform multiple test runs per build 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2321]
The current autobuild infrastructure can perform only one test run (with a set of TESTOPTS) per build. We would want to conduct multiple test runs after a build with different set of TESTOPTS. This is especially useful for smp builds where we could have multiple runs with different ppn values. (e.g. TESTOPTS1 = " ++ppn 1", TESTOPTS2 = " ++ppn 2", TESTOPTS3 = "++ppn 4" etc). To support this, the input `system_list` file should contain a list of TESTOPTS separated with a delimiter and the relevant scripts (build_on_system, instead_test.sh etc) should conduct multiple test runs with each of the TESTOPTS options.

**Comment by matthiasdiener** [comment]
Would it make sense to maintain the autobuild script in git as well (either in charm or as a separate project)?

**Comment by nitbhat** [comment]
Yes, absolutely. 

The autobuild infrastructure (the local scripts, remote scripts and system_list) were earlier a part of Gerrit (charmgit:autobuild). I think that should be migrated to GitHub if it hasn't already been done.

**Comment by matthiasdiener** [comment]
Oh, I see. Let me migrate it then.

**Comment by matthiasdiener** [comment]
Autobuild is now here: https://github.com/UIUC-PPL/autobuild
