### ISSUE TITLE
CMI_MSG_NOKEEP macro broken on pami-linux-ppc64le-smp

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2341]
```
../bin/charmc  -optimize -production   -I.   -c -o ck.o ck.C
ck.C:1663:3: error: no member named 'nokeep' in 'CmiMsgHeaderBasic'
  CMI_MSG_NOKEEP(env) = _entryTable[eIdx]->noKeep;
  ^~~~~~~~~~~~~~~~~~~
../bin/../include/converse.h:72:74: note: expanded from macro 'CMI_MSG_NOKEEP'
#define CMI_MSG_NOKEEP(msg)                  ((CmiMsgHeaderBasic *)msg)->nokeep
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
Error while processing ck.C.
```
```
jim@belfast$git blame src/conv-core/converse.h | grep CMI_MSG_NOKEEP
342095b5 (Eric Mikida                2019-06-20 13:51:12 -0400   72) #define CMI_MSG_NOKEEP(msg)                  ((CmiMsgHeaderBasic *)msg)->nokeep
jim@belfast$git blame src/ck-core/ck.C | grep CMI_MSG_NOKEEP
342095b5 (Eric Mikida            2019-06-20 13:51:12 -0400 1663)   CMI_MSG_NOKEEP(env) = _entryTable[eIdx]->noKeep;

```

Somehow related to https://github.com/UIUC-PPL/charm/commit/342095b5ae2f7993576a55c02ad12665efb44652

**Comment by jcphill** [comment]
It looks like pamilrts was updated but not pami (which is the production layer on Summit).
It doesn't look like Sameer's e6754908a3a8587bc7bc1f6fe0e5269924127066 was ever ported to pamilrts.

**Comment by nitbhat** [comment]
Hi Jim, 

This PR(https://github.com/UIUC-PPL/charm/pull/2342 <https://github.com/UIUC-PPL/charm/pull/2342>) should fix the ’nokeep’ issue. It adds the ’nokeep’ field to the converse message headers that were missed during the initial commit.  

Nitin

**Comment by nitbhat** [comment]
Hi Jim, 

This commit (https://github.com/UIUC-PPL/charm/commit/333d3699234fd0c24ff93eb4e892e98411a0ae15 <https://github.com/UIUC-PPL/charm/commit/333d3699234fd0c24ff93eb4e892e98411a0ae15>) adds Sameer’s ppc64le changes to pamilrts. Were there any specific changes that were not ported? 

Thanks,
Nitin

**Comment by jcphill** [comment]
Sorry, I didn't see how signification those changes were.
I guess we should start testing it finally.

**Comment by nitbhat** [comment]
I'm guessing this issue is fixed by https://github.com/UIUC-PPL/charm/commit/5988a3a1825756d8858db8d7c3778d60c013d74e. Can this issue be closed?
