### ISSUE TITLE
Charm++ Shrink-Expand (malleable jobs, dynamically varying node count)

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#236]
*Original author: Abhishek Gupta*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/236*

---
Job Shrink/Expand capability is necessary to enable malleable and evolving parallel jobs. Evolving jobs are those which can dynamically adapt to the changing resource requirement by changing the number or processors on which they are executing, without any external command. Malleable jobs are those which can change the number of processors on which they are executing, at runtime in respond to an external command. To enable adaptive/malleable jobs, two components are critical - a smart job scheduler, which can make decisions on when and which jobs to expand or shrink and a parallel runtime system which provides dynamic expand/shrink capability. The first component has been extensively researched and its merits over traditional job scheduler have been demonstrated. It is the second component which we plan to address in this work. Job expand/shrink capability is also useful for proactive fault tolerance, and in the context of HPC in the cloud.

[ShrinkExpandIssuesApproach.pdf](https://github.com/UIUC-PPL/charm/files/3536252/ShrinkExpandIssuesApproach.pdf)

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-06-20 18:13:07*

---
Definitions
Shrink – A parallel application running on nodes in a set A (k1, k2, ...kn)  is shrinked to be run on nodes in set B  (b1, b2,... bm), where M<N, and B is a subset of A.

Expand - A parallel application running on nodes in a set  A (k1, k2, ...kn)  is expanded to be run on nodes in set B  (b1, b2,... bm), where M>N, and B is a superset of A. 

Note: An alternative definition could be the case where e.g. for expand, M>N but B is not a superset of A. E.g. a job running on 400 node is to be expanded to 800 nodes, but the new node set does not contain the old nodes. One of the motivations for doing that would be to provide contiguous allocations when a job is reallocated. I propose to first support the simple definitions and then think about these scenarios.

Implementation Issues(See attached file):
	Communication between the decision-maker (e.g. scheduler) and the parallel application 
	What information needed – number of processes, node-list. How to pass it (CCS) ? How to deal with wrap around issue in nodelist.
	Charmrun (process launcher and manager) needs to 
	Update its data structures.
	launch new processes, co-ordinate updated node-table (IP, port) information among new set of processes.
	Converse
	Node-clients need to update their node-tables information  (e.g. IP, dataport table), 
	Other variables such as numpes, nodes. 
	What happens to pe numbering – e.g. what is process number 3 after shrink/expand – It may be different from original number 3.  The change in numbering would have its consequences.
	Chare arrays
	Chares need to be moved away from killed processes.
	Home Pes of chares moved away from killed processes should update their location.
	Chares for which a killed processes was home pe, should now have some other pe as their home pe.
	The pe numbering would change, so the array location information would need to be modified accordingly, on all Pes. What are the data structures that would be affected by the change in pe numbering? 
	Spanning trees need to be modified
	System-level groups such as load balancer would need some modifications
	Application-level groups – application writers need to take care?

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-06-25 17:44:39*

---
Eric's notes from core-meeting:

  CkNumPes changes, or is there a new quantity CkNumActivePes? contiguous pe set vs non-contiguous?
  Issues in distributed hash tables with dynamic adaptive traits.
    literature should be reviewed
    code should be reviewed wrt to impact on code for different possible solutions
  Use cases should be identified to determine impact on implementation difficulty and performance
  Virtualize location manager groups?  Virtualize all groups?
    virtualizing groups and nodegroups would have a lot of weird side effects.
  Or add an API to update all numPE dependent structures during a CkNumPEsResize() event.

  Could be implemented using in memory checkpoint to the shrunk set, restart in shrunk set.
   In case of moving shrink, the process is  a little more intricate.
   Implementation using in memory node local checkpoint storage may be the most efficient path,
     it should be investigated more aggressively by Abhishek.
   Worst case, might need to checkpoint to disk and  restart.
   This implementation amplifies the need to add better support for group checkpoint restart.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 15:28:12*

---
Since Abhishek is gone and Bilge took over integration efforts. This may not be too urgent.

**Comment by bilgeacun** [comment]
*Original date: 2015-08-17 16:22:10*

---
Related gerit commit: ~~https://charm.cs.illinois.edu/gerrit/#/c/315~~ https://github.com/UIUC-PPL/charm/commit/abf3ac80f1146562350b155c283372abfa0601a8

**Comment by PhilMiller** [comment]
*Original date: 2016-05-17 04:01:15*

---
Set target version, since the implementation is finally ready to merge thanks to Ralf and Bilge tirelessly addressing endless review comments.

**Comment by PhilMiller** [comment]
*Original date: 2016-06-27 18:40:30*

---
Make the subject more explicit, so that readers who don't know the lingo can understand this at a glance.
