### ISSUE TITLE
Netlrts - verbslrts does not work when asyncrounous io is enabled in non smp builds

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#237]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/237*

---
When CMK_ASYNC_NOT_NEEDED flag is 0, which is the default case, non smp builds of both netlrts and verbs(lrts) give "socket closed before recv" errors in the beginning of the program.
Nikhil had a fix for this, however that fix disables all the print statements within the machine machine layer.

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-20 21:15:04*

---
This was fixed long ago by changing the way pipes were set up.
