### ISSUE TITLE
Charmrun wrapper around ibrun.symm for dual binary execution on host+mic with IMPI on stampede

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#239]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/239*

---
Charmrun wrapper around ibrun.symm for dual binary execution on host+mic with IMPI on stampede

should be able to make this messy business a little less unpleasant with a wrapper script.

**Comment by stwhite91** [comment]
*Original date: 2017-02-02 04:41:28*

---
Dual binary launching no longer relevant for KNL
