### ISSUE TITLE
Document charmrun options for large systems

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#240]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/240*

---
Quoth Jim:
> I just found http://charm.cs.illinois.edu/manuals/html/charm++/C.html and I notice that ++scalable-start and various other options for scaling on large systems aren't listed there.  Many of those that are documented could use examples or explanations, e.g. using ++runscript to set up LD_LIBRARY_PATH.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-31 20:16:49*

---
Can you resolve it ?

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-11-01 23:01:24*

---

Added options for scalable-start, batch.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-11-03 18:23:41*

---
Updated manual is up on web. Marking as resolved.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-03 18:25:17*

---
Typo "multu-core"

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-11-03 19:08:31*

---

Thanks. Fixed.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-03 19:10:42*

---
Looks good. Thanks.
