### ISSUE TITLE
Avoid per PE unpacking of readonly variable and readonly messages in SMP layer

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#242]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/242*

---
Readonly variable and messages are currently being unpacked for each PE in SMP mode. This may lead to a race condition. The bug was found to affect OpenAtom in SMP mode.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-25 03:44:50*

---
We need commit:4ee3b52e9d1 and commit:660b671259c8 together (the latter fixes a typo in the former)

**Comment by PhilMiller** [comment]
*Original date: 2013-06-26 20:10:00*

---
Eric - can we get a test that OpenAtom seems to behave on SMP builds after this fix?

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-26 21:14:30*

---
Branch nikhil_bugfixes will need to used for a working version.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-27 04:40:49*

---
That's branch nikhil_bugfixes of *OpenAtom*

**Comment by PhilMiller** [comment]
*Original date: 2013-07-01 21:24:39*

---
Eric reports that this is working, and that OpenAtom performance is indeed improved by running in SMP mode.

**Comment by nikhil-jain** [comment]
*Original date: 2013-07-01 22:11:05*

---
Eric, can you throw some number on performance you saw?
