### ISSUE TITLE
Remove reference to NMI from autobuild

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#2429]
The autobuild web page includes "Charm++ is also built and tested daily on the NMI system. Check Charm++ NMI build status."  Which seems unlikely since NMI doesn't exist anymore and the hyperlinks are 404.

Remove it from the script that generates the web page.

**Comment by nitbhat** [comment]
Fix: https://github.com/UIUC-PPL/autobuild/commit/6ce9fb76bf0736b439664e5bcb74206b6d82d9b5
