### ISSUE TITLE
Hapi Dependency on Charm++

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2467]
Currently, Hapi depends on the Charm++ runtime (for `QdCreate`, `QdProcess` and `CkCallback::send`), which means that non-Charm++ applications (such as those that only use Converse) now require the Charm++ runtime to build and run. Converse itself requires Hapi for `hapiPollEvents` and `exitHybridAPI`.

See also #2459.

This causes the current auto build failure with cuda:
```
../../bin/charmc -optimize -production   -o check check.o -language converse++
../../bin/../lib/libcudahybridapi.a(hybridapi.o): In function `hapiPollEvents':
hapi_impl.cpp:(.text+0x1590): undefined reference to `CkCallback::send(void*) const'
hapi_impl.cpp:(.text+0x169a): undefined reference to `QdProcess(int)'
../../bin/../lib/libcudahybridapi.a(hybridapi.o): In function `hapiAddCallback':
hapi_impl.cpp:(.text+0x1afb): undefined reference to `QdCreate(int)'
../../bin/../lib/libcudahybridapi.a(hybridapi.o): In function `hapiEnqueue':
hapi_impl.cpp:(.text+0x1c41): undefined reference to `QdCreate(int)'
hapi_impl.cpp:(.text+0x1d17): undefined reference to `QdCreate(int)'
hapi_impl.cpp:(.text+0x1e56): undefined reference to `QdCreate(int)'
```

**Comment by ericjbohm** [comment]
Does this impact normal use cases of HAPI?  I get that there is a circular dependency issue for non-charm HAPI usage, but does such a thing exist?  If not, then I would argue this should not be a blocker for 6.10.

**Comment by minitu** [comment]
Eliminating dependency of Converse on HAPI seems to be the easier solution; polling can be registered inside Converse to be called on every scheduler invocation. If there are Converse applications that want to use HAPI this could cause a problem, but it's unlikely.
