### ISSUE TITLE
BGQ: Don't expose platform-specific includes to application code

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#248]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/248*

---
`TopoManager.h` included some BGQ-specific headers. This meant that application code that included it needed to have paths to those headers available for its own compilation. By Jim's request, the relevant code and includes were moved to `TopoManager.C` so that application code could more easily ignore this platform-specific junk.

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-25 20:21:36*

---
As I stated in the email, moving machine-specific code to TopoManager.C may not be the right thing to do. May be we can add BGQTorus.C if need be.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-25 20:24:49*

---
There's a lot of machine-specific code in `TopoManager.C` for many different platforms. If we want that file to be portable, there's much more to clean up than just this bit of BGQ support. Should we open a separate cleanup issue for that?

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-25 20:33:31*

---
Over the period, I have been trying to reduce it, although admittedly at a slower pace than I would have liked to. Branch lrtsTopo has most of that clean up in place, but needs more attention from me. #19 is a task (though not well defined) for it.
