### ISSUE TITLE
Binary cannot find __executable_start

### ISSUE THREAD

**Issue by hellkite500** [UIUC-PPL/charm#2486]
Possibly related to #1893 but this instance isn't built with -charm-shared and the patch for #1893 is included in in version 6.9.0 that is causing this error.

### Error:
When launching the application binary, the following error occurs
**error relocating ./adhydro: __executable_start: symbol not found**

### Application Build
Shortened object list for clarity:
/opt/charm/bin/charmc  -lnetcdff -Wl,--start-group -lnetcdf -lhdf5_hl -lhdf5 -Wl,--end-group -lcurl -lz -module CommonLBs -balancer GreedyCommLB -balancer MetisLB -fdiagnostics-show-option -fpermissive -optimize -lgfortran -g -Wall -language charm++ -O3 \<objects\> -o adhydro
### Charm build:

**./build charm++ mpi-linux-x86_64 -optimize --with-production**

### Charm version:
$cat VERSION
60900

### Extra Information:
$gcc --version
gcc (Alpine 5.3.0) 5.3.0

$gcc -Wl,-v,--version:  
collect2 version 5.3.0
/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld -plugin /usr/libexec/gcc/x86_64-alpine-linux-musl/5.3.0/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-alpine-linux-musl/5.3.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccKblbFf.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib/ld-musl-x86_64.so.1 -pie -z now -z relro /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../lib/Scrt1.o /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../lib/crti.o /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtbeginS.o -L/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0 -L/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../.. -v --version -lssp_nonshared -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtendS.o /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../lib/crtn.o
GNU ld (GNU Binutils) 2.26.20160125
GNU ld (GNU Binutils) 2.26.20160125

**Comment by hellkite500** [comment]
Interestingly, I cannot reproduce with  `gcc --version
gcc (Alpine 8.3.0) 8.3.0`

**Comment by evan-charmworks** [comment]
What is strange to me is that this error should never occur because the presence of `__executable_start` is tested for during Charm's configure step.

**Comment by matthiasdiener** [comment]
Have we ever tested non-glibc Linux (Alpine seems to have musl libc)?

**Comment by evan-charmworks** [comment]
Yes: #2021

**Comment by evan-charmworks** [comment]
I have run the full test suite on Alpine Linux successfully since the last activity on this issue. Reopen if it persists.
