### ISSUE TITLE
charmxi crashes with unnamed param in SDAG when clause

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#249]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/249*

---
If I say
```

when foo(int /* no name, because I'm not using it */) atomic {
  // Do stuff based on the message having arrived
}

```
`charmxi` crashes, by dereferencing a `NULL` pointer to the non-existent name, in `SdagConstruct::generateWhen()`

It should instead generate an appropriate dummy symbol in which to unpack that value (if needed), and otherwise ignore it.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 19:15:28*

---
Consult with Jonathan as needed, please use this bug fix as a motive to familiarize yourself with Charmxi as infrastructure supporting various HLL efforts.

**Comment by bilgeacun** [comment]
*Original date: 2013-10-24 21:34:29*

---
The parameter is ignored, if it's unnamed.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-24 21:50:11*

---
The change to fix this is not quite right. Whatever sent the message that matched the when clause will still have PUPed that entry method argument, regardless of it not being referenced in the implementation. By ignoring some variables on the receiving side entirely, the corresponding values in the packed up message will end up assigned incorrectly.

Take a look at my modified test on branch '249'. It asserts that the value of `b` is as expected. As I describe above, that assertion fails.

Please amend the code to address this, and squash your subsequent commits with my test when you merge to mainline, so that we're not left with an explicit 'break the test' commit.

**Comment by bilgeacun** [comment]
*Original date: 2013-10-25 03:43:42*

---
I see your point. But ignoring the variable in the entry method does not make sense as there can be multiple when statements using the same entry method and some of them might have unnamed parameters while some of them have not.  

Then creating a dummy name seems less complicated than ignoring the variable. There could be more than one unnamed parameters in a when construct and the generated dummy name should be distinct, so it requires to keep a counter probably. 

Creating a dummy name does not really have a disadvantage over ignoring the variable, right?

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 03:52:59*

---
When I opened the bug, I assumed dummy variables were necessary. Seeing the alternate design, I believe they really are necessary.

There is a nominal disadvantage to using dummies over skipping unused arguments entirely. Namely, if we could ask the PUPer to 'advance' past the arguments that we don't care about, we would save a bit of memory used and code executed. However, the PUP buffer would have to carry extra information to tell us how far to advance in its buffer, since non-primitive types can take arbitrary variable amounts of space when PUPed.

The only hypothetical optimization to the dummies that I can see would be only having one for each type, rather than one for each formal parameter. This shouldn't make an actual difference, since the compiler should be able to see that the individual variables are never used and optimize them out. I would skip this optimization as overcomplicated.

**Comment by bilgeacun** [comment]
*Original date: 2013-10-25 17:09:54*

---
Ok, I've created dummy variables instead. Can you have a look at branch 249 before I merge my changes to the main branch. Thanks!

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 17:18:07*

---
Just to confirm, it passes the modified test now?

**Comment by bilgeacun** [comment]
*Original date: 2013-10-25 17:22:00*

---
yes, it does.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 17:37:27*

---
Since we're looking at this now, I may as well suggest being more selective about which list(s) of state variables the dummy variable gets added onto. Since we know it's never going to be referenced, it only needs to be on the list of variable unpacked from the incoming message - it doesn't need to be saved for the body of the when or any of its children.

The code is fine to integrate as is, but it would be good if you could figure out the above optimization (with Jonathan's help, as needed).

**Comment by bilgeacun** [comment]
*Original date: 2013-10-25 20:47:35*

---
My latest commit to the branch does this optimization now. I've tested it and it works. 
If I'm not missing anything, it should be fine.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 21:23:53*

---
Could you push your updated code?

**Comment by bilgeacun** [comment]
*Original date: 2013-10-25 21:26:43*

---
Oh sorry, I've pushed!

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 21:43:07*

---
The code looks good. Please integrate it to mainline with `git merge --squash`, and delete the branch afterward.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-27 21:20:52*

---
Confirmed test passes on mainline.
