### ISSUE TITLE
Trilinos' Teuchos package breaks with AMPI's atexit

### ISSUE THREAD

**Issue by jbakosi** [UIUC-PPL/charm#2499]
Using ampi's mpi.h, attempting to build the teuchos package in trilinos, I get
```
In file included from /home/quinoa/quinoa-tpl/src/trilinos/packages/tpetra/core/src/Tpetra_Details_extractMpiCommFromTeuchos.hpp:53,
                 from /home/quinoa/quinoa-tpl/src/trilinos/packages/tpetra/core/src/Tpetra_Details_extractMpiCommFromTeuchos.cpp:42:
/home/quinoa/quinoa-tpl/src/trilinos/packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp: In static member function 'static Teuchos::TableFormat& Teuchos::PerformanceMonitorBase<T>::format()':
/home/quinoa/quinoa-tpl/install/gnu-x86_64/charm/bin/../include/mpi.h:60:21: error: expected primary-expression before 'do'
 #define atexit(...) do {atexit(__VA_ARGS__); atexit(ampiMarkAtexit);} while(0)
                     ^~
/home/quinoa/quinoa-tpl/src/trilinos/packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp:225:16: note: in expansion of macro 'atexit'
         (void) atexit (freeTableFormat);
                ^~~~~~
```
Apparently, the way teuchos uses `cstdio`'s `atexit` is incompatible with AMPI's redefinition in its mpi.h.

If I comment out the offending macro definition in mpi.h:60
```
 // #define atexit(...) do {atexit(__VA_ARGS__); atexit(ampiMarkAtexit);} while(0)
```
the problem goes away, but I'm wondering if this is not the right solution for AMPI.

Any advice on this?

**Comment by stwhite91** [comment]
The problem here for AMPI is that some applications call MPI_Finalize() from inside functions registered with atexit(). When atexit() functions are called, that happens from the main thread (not an AMPI user-level thread), which means that AMPI cannot find its context properly to clean up and shutdown. Currently we have this atexit() renaming on by default, and provide users with the option to disable it by building with "-DAMPI_RENAME_ATEXIT=0", but we can discuss whether it should be opt-in / off by default.

**Comment by stwhite91** [comment]
Upon closer inspection we have already fixed this issue with our renaming. Can you try with the master branch of AMPI?

https://github.com/UIUC-PPL/charm/commit/9147ff5f7d24dfb5bb421a8c25c6c99e6952af73

**Comment by jbakosi** [comment]
Sure, which branch should I try? Or should I just try with 9147ff5?

**Comment by matthiasdiener** [comment]
> Sure, which branch should I try? Or should I just try with [9147ff5](https://github.com/UIUC-PPL/charm/commit/9147ff5f7d24dfb5bb421a8c25c6c99e6952af73)?

Can you try with the current `master` branch?

**Comment by jbakosi** [comment]
Yes, the master branch works fine. Thanks for tracking this down so quick!
