### ISSUE TITLE
Uniquely tag each chare array broadcast to enable true unique delivery

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#250]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/250*

---
It is trivially possible to make array broadcasts arrive in different orders at different PEs, at least on machine layers that don't guarantee in-order delivery. (test code to be attached). There are a plethora of ways that this can result in some array elements receiving a different set of broadcasts than others, mostly involving migration of some sort, but some involve dynamic insertion instead.

As we (Sanjay, Ram, Jonathan, Phil) decided, the immediate fix for this is to put a global sequence number on every broadcast message, and use that sequence number instead of the current locally-incremented `bcastNo` to buffer and deliver array broadcast messages.

The deeper fix for broadcasts and insertions involves keeping a Lamport clock for every such event, and only doing deliveries when there is a suitable happens-before relationship between the message and the potential recipient. That should be a separate issue (in addition to #49), since it requires further analysis and design, and is not required to address the non-insertion case.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-23 05:32:20*

---
I'm not thrilled with the resolution from a design perspective, since it means array broadcasts are now buffered in two different ways and places, depending on whether they're early (the runtime message queue) or not (`CkArrayBroadcast::oldBcasts`). There's also the attendant delocalization of `CkArrayBroadcaster::bcastNo`.

From an operational perspective, though, the only clear criticism I can offer is that this can prevent a PE from going idle. Given how rare out-of-order array broadcasts should be, that's pretty slim. That would pose issues for letting power usage drop, converse conditions (`CcdPROCESSOR_BEGIN_IDLE`), and potentially using QD to detect other bugs arising from unordered message delivery. I'm not sure those issues, even taken together, are worth redoing the solution.

**Comment by lifflander** [comment]
*Original date: 2013-07-23 05:34:24*

---
The explicit buffer is easy to implement, I started with this actually, but it seemed to be an overdesign considering this was a rare case.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-23 05:58:24*

---
The usual issue with overdesign is that it makes later work on affected components more difficult. I feel like the explicit buffer design is easier on maintainers than the re-enqueue design. Either design could be commented (and the current one definitely warrants one on the `if` in `CkArray::recvBroadcast`), but the explicit buffer also admits naming things to make their purpose clear; e.g. a buffer named `outOfOrderBcasts` has a very clear purpose.

**Comment by lifflander** [comment]
*Original date: 2013-07-23 07:00:22*

---
Done with explicit buffer.

**Comment by lifflander** [comment]
*Original date: 2013-07-23 07:01:06*

---
Still needs some testing when these are really unordered

`todo: test with Ram's randomized queue

**Comment by PhilMiller** [comment]
*Original date: 2013-07-23 07:39:50*

---
Prior to work on this issue, CkArray had no knowledge of broadcast numbering and per-element delivery-couting on the receive/delivery side at all - that was handled 100% within CkArrayBroadcaster. If you take a look back in the history, the decision to insulate CkArray from managing that state was intentional, and I think that was wise.

My take is that `CkArrayBroadcaster::bcastNo` should not have been made public, and `CkArrayBroadcaster::outOfOrderBcasts` should not be public either. As it stands, `CkArray::recvBroadcast` now implicitly depends on the increment of `bcastNo` from before the call to `CkArrayBroadcaster::incoming()` to after it.

Please make `CkArrayBroadcaster` do its job, rather than splitting it up between that and `CkArray`.

The condition in the top `if` and the body of the `else` could actually be folded into `incoming()`. The later check for the next message having already arrived can be a simple `if (msg = broadcaster->getNextMsg()) recvBroadcast(msg);`

If you don't mind, I'll have a go at refactoring this, and you can tell me what you think.

**Comment by lifflander** [comment]
*Original date: 2013-07-23 07:44:15*

---
Sure, if you want to go ahead. I am willing to do that refactoring also.  I realized the logical separation that was there, but I'm not sure if there is a good reason for less cohesion between the two. In fact, merging the "broadcaster" code into CkArray might be a sensible approach.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 18:52:29*

---
Lowering priority since this is not affecting applications currently, and the relevant races won't happen in normal usage.

% Done lowered due to recognition that the simple sequencing solution got reverted due to its fundamental conflict with with the message logging FT code.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-07 23:49:46*

---
The hang in `tests/charm++/sdag/migration` under randomized queuing (#259) results from this weakness of the array broadcast system. On a simple net-linux-x86_64 build, that test run on 2 PEs frequently hangs with the 2 broadcasts it performs being stamped in opposite orders on each PE.

**Comment by lifflander** [comment]
*Original date: 2015-02-19 18:32:12*

---
Working on this.

**Comment by lvkale** [comment]
*Original date: 2015-09-17 20:25:08*

---
After this bug is fixed, add a test to nightly build (megatest?) to check it continues to work.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-22 17:12:49*

---
Jonathan - this bug was discussed in the last core. Is there a reasonable solution you now of?

**Comment by PhilMiller** [comment]
*Original date: 2015-09-22 20:12:30*

---
Postponed because it's not affecting existing applications.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-28 18:47:21*

---
Reassess this issue.

**Comment by lvkale** [comment]
wow... we dropped the ball on this. need to pick up in core tomorrow. Ongoing discussion on slack. It could be a problem even without migration because codes may assume bcasts are in order (e.g. may not use (or cannot?) refnum in sdag codes for bcast. )

**Comment by stwhite91** [comment]
We will discuss this more in Core meeting tomorrow, but some points from the slack discussion:
1. In-order deliver does not need to be guaranteed. We don't do that for pt2pt messaging already, and applications shouldn't assume it specially for bcasts.
2. It would be nice to guarantee that each bcast message is delivered exactly once to each chare array element even in the face of anytime migration. But production applications do not use anytime migration, and it already forces inefficiency and broken abstractions on us (see sections, the reduction starting protocol, spring cleaning for bcasts). So, perhaps another reason to make anytime migration not the default in Charm v7.0.

Also bcast messages still have refnums just like normal messages, which users can use to order them themselves or using SDAG.

Here's the commit of Jonathan's mentioned above that was merged and then soon after reverted: https://github.com/UIUC-PPL/charm/commit/b4ac109cdce1c3c4dad02ab59ae7ccdb89853615

**Comment by rbuch** [comment]
Fixed by #3614.
