### ISSUE TITLE
No rule to make target 'conv-autoconfig.h', needed by 'xi-main.o'

### ISSUE THREAD

**Issue by jbakosi** [UIUC-PPL/charm#2503]
I'm attempting to build on alpine linux, using
```
build charm++ mpi-linux-x86_64 --build-shared --with-production --disable-charmdebug -j36 -O3 -DNDEBUG
```
I get
```
./configure: line 3806: syntax error: unexpected redirection
make[1]: *** No rule to make target 'conv-autoconfig.h', needed by 'xi-main.o'.  Stop.
make[1]: Leaving directory '/home/quinoa/quinoa-tpl/install/gnu-x86_64/charm/mpi-linux-x86_64/tmp'
```
Please let me know if you need more information.

**Comment by matthiasdiener** [comment]
Can you please post line 3806 of `tmp/configure`? What is the output of `/bin/sh --version`?

**Comment by jbakosi** [comment]
configure:3806:
```
        IFS=' ' read LDXX_WHOLE_ARCHIVE_PRE LDXX_WHOLE_ARCHIVE_POST <<< $i
```

There is no output from `/bin/sh --version`. I have also tested this with bash 5.0, and I get the same problem.

**Comment by matthiasdiener** [comment]
Can you try the following?

In line 823 of `src/scripts/configure.ac`, replace 

```bash
IFS=' ' read LDXX_WHOLE_ARCHIVE_PRE LDXX_WHOLE_ARCHIVE_POST <<< $i
``` 

with 
```bash
IFS=' ' echo $i | read LDXX_WHOLE_ARCHIVE_PRE LDXX_WHOLE_ARCHIVE_POST
```

, remove the `tmp` directory, and rebuild.

**Comment by jbakosi** [comment]
That's a fix! Thanks!

**Comment by matthiasdiener** [comment]
Thank you for testing this! I'll submit a patch.
