### ISSUE TITLE
Whole array destruction 

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#251]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/251*

---
I want to be able to create chare arrays, have them do some work, and then completely disappear, including the underlying CkArrayMgr and CkLocMgr groups, as appropriate. This requires being able to destroy the groups themselves.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-07 23:47:00*

---
Implemented `CkArray::ckDestroy()` to do at least the basics of what one would expect from it. I think the destructor probably leaks stuff, and we need to refcount CkLocMgr and delete that when it has no more arrays bound to it. Maps are a bit stickier, in that users create those explicitly, so they would need to be destroyed explicitly.

Note that I have _not_ addressed standard group destruction, only the particular group classes involved in chare arrays.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-08 18:38:41*

---
Getting rid of CkLocMgr instances will be a bit harder, as there is a connection to the load balancing machinery that needs to be cut.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-08 20:49:27*

---
OK, LB disconnection looks to be pretty much done - AtSync barriers are deactivated, and the object manager entry is deleted. There's still an empty table slot left behind, and might be other stuff as well, but memory usage is down substantially (per valgrind's memcheck still-reachable memory reporting). The `CkLocMgr` now deletes itself when the last bound array unregisters.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-08 21:38:12*

---
Pushed on branch `array-deletion`, ready for review.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-09 20:53:11*

---
Jonathan notes that there's potential for failure if an array element migration message is in flight when the array manager group gets destroyed. I will add a check for that case.

We concluded that it's mostly acceptable to discard those messages, rather than adding some heavy synchronization to check that all elements are properly destroyed before destroying the manager group. That means there's a slight weakness in that array classes written to do some special cleanup when each element is destroyed will have to explicitly synchronize element destruction being complete before triggering array manager destruction.

**Comment by lifflander** [comment]
*Original date: 2013-08-09 21:10:13*

---
We should note in the documentation that once 'ckDestroy' has been called on an chare array proxy, that proxy can not be used to send a message or call ckDestroy again. This will lead to undefined behavior.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-11 23:49:37*

---
In his review, Lukasz suggested:
> I don't know whether there are other places in the code that store
> array information. Two places where that may happen are array
> listeners and comlib. You may want to run a benchmark where you create
> and delete arrays in a loop and check that memory use does not
> increase.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-14 02:18:00*

---
The test Lukasz suggested turned up the node-level `CkArrayReductionMgr` instances created for *every single group*, despite them going unused in non-SMP builds. Addressed in #266.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-14 03:33:24*

---
After testing repeated construction and deletion of chare arrays, I've squashed a bunch of residual leaks. These included various locks that only actually got allocated on SMP builds, the node-level reduction manager, and data associated with individual arrays by their map objects.

I also discovered and fixed issues #266, #267, and #268 along the way.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-14 23:53:44*

---
Hunted down more pathological stuff in spring cleaning: canceled Ccd triggers are not reclaimed as readily in the 'keep' mode, so transient structures like the array management groups should reset a fresh trigger each time.

I think we're finally clean in this regard. Code to be merged when mainline is clean.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-19 20:02:42*

---
And a maybe-final cleanup for the LB barrier trigger on element-less PEs.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-20 23:23:15*

---
Cleaned up the branch and merged to mainline.
