### ISSUE TITLE
Create a ucx-linux-ppc64le build target

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#2518]
The UCX layer should be usable on Summit/Sierra-like systems. This could go into v6.10 if we have time to do it by then

**Comment by rbuch** [comment]
More critically, it should also be used (and probably selected by default by the build script) on TACC's Frontera system.

I'd expect that we'd generally want to stick to using PAMI on Summit and Sierra.

**Comment by stwhite91** [comment]
This was added here: https://github.com/UIUC-PPL/charm/commit/6b128592522d0dae6c81371223392c244270fb30
