### ISSUE TITLE
conv-autoconfig.h contains defines which collide with standard config.h from autoconf

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#252]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/252*

---
The header file conv-autoconfig.h contains the following defines

* #define PACKAGE_BUGREPORT ""
* #define PACKAGE_NAME ""
* #define PACKAGE_STRING ""
* #define PACKAGE_TARNAME ""
* #define PACKAGE_URL ""
* #define PACKAGE_VERSION ""

which collide with the defines in a user's config.h if that user uses autotools. They should be removed from conv-autoconfig.h.

[0001-Commented-out-colliding-defines-in-conv-autoconfig.h.patch](https://github.com/UIUC-PPL/charm/files/3536374/0001-Commented-out-colliding-defines-in-conv-autoconfig.h.patch.txt)

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-07-23 17:41:30*

---
I have attached a patch that comments out the PACKAGE_* defines. I don't think that any of those defines are actually used in the code, so commenting them out should be pretty safe. But please double check.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-30 17:24:48*

---
Patch applied.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-02 20:17:27*

---
No complaints that it was done wrong, so closing.

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-07 16:30:22*

---
Thanks for fixing.
