### ISSUE TITLE
Race condition in sync-ft test

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#254]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/254*

---
Add a blocking sleep test on the checkpoint file before you issue the kill signal.

**Comment by lifflander** [comment]
*Original date: 2013-09-17 20:08:56*

---
Progress on this?

**Comment by ericjbohm** [comment]
*Original date: 2013-09-17 20:35:06*

---
Found that the internal mechanism for fault injection uses periodic CCD. Will require more elaborate revision to fix than simply hacking a shell script. Probably best if reimplemented to track completion of checkpoint completion of kill target PE.  Still need to evaluate distributed visibility issues for checkpoint completion information.
