### ISSUE TITLE
Add test case for AMPI_Register_main

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#2564]
Currently there is no test case for the `AMPI_Register_main` and `MPI_Setup` functionality described in the AMPI manual. Such a test should verify that that the application lifecycle completes successfully, that migration works, and that Isomalloc heaps coexist correctly.

**Comment by matthiasdiener** [comment]
Are there any users for this functionality?

**Comment by evan-charmworks** [comment]
I don't know. I didn't find any uses of it in the charm or ampi-benchmarks repositories. @stwhite91 do you know?

**Comment by matthiasdiener** [comment]
Unless there is a compelling case for it, we should consider removing this functionality. It is not compatible with shared libraries (see https://github.com/UIUC-PPL/charm/blob/006619fb9a097262a6c0608b7c588c4299f927eb/src/libs/ck-libs/ampi/ampi.C#L1126) and removing it would simplify the startup code significantly.

**Comment by stwhite91** [comment]
There are no more users of it. There was a paper written about its use in the early 2000s PSAAP1 rocket center but that's it.

**Comment by matthiasdiener** [comment]
> There are no more users of it. There was a paper written about its use in the early 2000s PSAAP1 rocket center but that's it.

Out of curiosity, do you have a link to the paper?

**Comment by stwhite91** [comment]
It's described in section 4.4 of this paper, and gets short descriptions in other early AMPI papers I believe: http://charm.cs.illinois.edu/newPapers/03-07/paper.pdf

**Comment by evan-charmworks** [comment]
PR #2565 removes this functionality.
