### ISSUE TITLE
Double in-disk checkpoint/restart creating zero-byte size files

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#257]
*Original author: Esteban Meneses*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/257*

---
   The double in-disk checkpoint restart is creating empty checkpoint files.
   After the CMK_CHKP_ALL flag was introduced (now set by default), the in-disk version is no longer storing the checkpoint in the files. 
   In function:
void CkMemCheckPT::recvArrayCheckpoint(CkArrayCheckPTMessage *msg)
the checkpoint message msg is simply stored in a table, which is sufficient for double in-memory C/R. For the in-disk case, that checkpoint message should be stored in a file. The line:
chkpTable[idx] = msg;
has to be changed to store the message in-memory or in-disk accordingly.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-04 05:28:34*

---
Marking for 6.6. If the relevant change was made before 6.5, then this should be retargeted to 6.5.2.

**Comment by xiangni** [comment]
*Original date: 2013-08-28 22:17:33*

---
Fixed the bug. Now when CMK_CHKP_ALL is turned on, checkpoints will be written to files for double in-disk checkpointing.
