### ISSUE TITLE
Create a test target agnostic of +p and ++ppn

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2570]
The lesson learned from the untested `gni-smp` hang in megatest (https://github.com/UIUC-PPL/charm/issues/2508), was to run tests with larger `++ppn` values (and even larger `+p` values if required). Creating a test target agnostic of `+p` and `++ppn` will allow us to run different series of tests with a range of `+p` and `++ppn` values.

**Comment by evan-charmworks** [comment]
#2952, #2953, #2954, #2955, #2956, #2957, #2958, #2959, #2960, #2961, #2965, #2990
