### ISSUE TITLE
hwloc topology load extremely slow on wide nodes

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2580]
On a 128-core node, Charm++ startup for +p128 takes 0.14 s on multicore and 0.17 s on netlrts without any affinity, but adding +pemap, +setcpuaffinity, or even +showcpuaffinity slows startup to over 18 s for both multicore and netlrts. The startup time seems to grow linearly with the number of pes on the node, regardless of the number of processes, so the bottleneck may be at the OS level, but ideally the hardware discovery would only be needed once per host.

This is a significant regression from Charm++ 6.8, which launched quickly with cpu affinity.

Representative stack trace during startup:

#1  0x0000000000bffbc4 in hwloc.read_path_as_cpumask ()
#2  0x0000000000bff046 in look_sysfscpu ()
#3  0x0000000000bf96f3 in hwloc_look_linuxfs ()
#4  0x0000000000be0a6a in cmi_hwloc_topology_load ()
#5  0x0000000000bc48a9 in print_thread_affinity() ()
#6  0x0000000000bc5164 in CmiInitCPUAffinity ()
#7  0x0000000000ab7109 in _initCharm(int, char**) ()
#8  0x0000000000467f0b in slave_init(int, char**) ()
#9  0x0000000000ba7790 in ConverseRunPE(int) ()

**Comment by jcphill** [comment]
Running +auto-provision +showcpuaffinity on a KNL node takes 68 s for startup. Running only +auto-provision takes "only" 35 s, so there is a double-initialization taking place.

**Comment by jcphill** [comment]
There are some useful suggestions at https://www.open-mpi.org/projects/hwloc/doc/v2.1.0/a00342.php and https://www.open-mpi.org/projects/hwloc/doc/v2.1.0/a00339.php
In particular, once a topology instance is loaded multiple threads can access it, and it can also be dumped to XML and sent to other processes.

**Comment by evan-charmworks** [comment]
I see the problem. Each PE initializes and loads a new copy of the CPU topology every time affinity is set or printed. This is a big waste of time, when it could be done exactly once for the entire run of a process.

**Comment by evan-charmworks** [comment]
In #2590 I've eliminated the redundant topology querying.

**Comment by evan-charmworks** [comment]
Fixed in #2590 and cherry-picked into 6.10.
