### ISSUE TITLE
Pull request #2540 breaks CkLoop

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2591]
Compiling ChaNGa with the ffda2e37a7e8b548a339f53e95d4d6fcd15e54cf commit (from PR #2540) and running gives:

Running on 64 processors:  ./ChaNGa.ucx +useckloop +bench -wall 60 -maxbal 10.0 +ppn 27 +setcpuaffinity +commap 0,1 +pemap 2-54:2,3-55:2 h148.cosmo50PLK.6144g3HbwK1BH.param 
charmrun>  /bin/setarch x86_64 -R  mpirun -np 64  ./ChaNGa.ucx +useckloop +bench -wall 60 -maxbal 10.0 +ppn 27 +setcpuaffinity +commap 0,1 +pemap 2-54:2,3-55:2 h148.cosmo50PLK.6144g3HbwK1BH.param 
Charm++> Running in SMP mode: 64 processes, 27 worker threads (PEs) + 1 comm threads per process, 1728 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.0-rc2-8-gffda2e37a
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++: late entry method registration happened after init
Entry point: CkLoop, addr: 0x6edb60
------------- Processor 27 Exiting: Called CmiAbort ------------
Reason: Did you forget to import a module or instantiate a templated entry method in a .ci file?

As you can see this is a ucx-linux-x86_64 smp build using gcc 9.1.0 on TACC frontera.

**Comment by jcphill** [comment]
Seeing the same thing, happens on as few as 4 pes:
`jim@belfast$./namd2 +auto-provision
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode: 16 threads (PEs)
Charm++> Using recursive bisection (scheme 3) for topology aware partitions
Converse/Charm++ Commit ID: v6.10.0-rc2-31-g332b37c
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++: late entry method registration happened after init
Entry point: CkLoop, addr: 0xd2bca0
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: Did you forget to import a module or instantiate a templated entry method in a .ci file?

[0] Stack Traceback:
  [0:0] namd2 0xe16c16 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [0:1] namd2 0xe16d2d 
  [0:2] namd2 0xd40add 
  [0:3] namd2 0xd3b404 InitCallTable::enumerateInitCalls()
  [0:4] namd2 0xd3d3f3 _initCharm(int, char**)
  [0:5] namd2 0x6932e1 master_init(int, char**)
  [0:6] namd2 0x61669c main
  [0:7] libc.so.6 0x3e2aa1ed5d __libc_start_main
  [0:8] namd2 0x6192fd 
CHARM++ FATAL ERROR: Did you forget to import a module or instantiate a templated entry method in a .ci file?

Segmentation fault (core dumped)
`

**Comment by stwhite91** [comment]
It looks like the offending commit changed _registerDone() from a function called only on PE 0 to one called on every PE. That function sets the value of _registerDone from 0 to 1, and its value is checked before aborting with the error message "Did you forget to import a module or instantiate a templated entry method in a .ci file?". So it looks like we need to change the _registerDone variable to a std::atomic or else lock/unlock around accesses to it.

**Comment by ericjbohm** [comment]
Side note, we need to get ckloop testing integrated into one of the
autobuild targets.

**Comment by evan-charmworks** [comment]
I think #2594 should fix this.

**Comment by trquinn** [comment]
After pulling #2594 , I'm now getting:
Charm++> cpuaffinity PE-core map : 2-54:2,3-55:2
------------- Processor 1740 Exiting: Called CmiAbort ------------
Reason: Unhandled C++ exception in user code.

[1735] Stack Traceback:
   [1735:0] ChaNGa.ucx 0x80d26b CmiAbortHelper(char const*, char const*,
char con st*, int, int)
   [1735:1] ChaNGa.ucx 0x80d380 CmiAsyncBroadcastFn
   [1735:2] ChaNGa.ucx 0x722f30 _initDone()
   [1735:3] libstdc++.so.6 0x2b96255a9106
   [1735:4] libstdc++.so.6 0x2b96255a9151
   [1735:5] libstdc++.so.6 0x2b96255a9385
   [1735:6] libstdc++.so.6 0x2b962559d1c6
   [1735:7] ChaNGa.ucx 0x581ea3
   [1735:8] 0x2b96239da010

gdb tells me that
(gdb) x/i 0x581ea3
    0x581ea3 <CstatsInit(char**)>:
     callq  0x553f00 <__cxa_throw_bad_array_new_length@plt>

**Comment by trquinn** [comment]
The above error seems to be due to another pull request.  If I revert commit commit f0b7756f7d4604470c8e66b044a5321475224138, then ChaNGa starts up fine.

**Comment by nitbhat** [comment]
Do we have any ckloop test in our examples/test suite? @ericjbohm

**Comment by evan-charmworks** [comment]
> Do we have any ckloop test in our examples/test suite? @ericjbohm

There are some in `examples/charm++/ckloop` but they are not included in `make test`.

**Comment by evan-charmworks** [comment]
The original issue described in this issue is fixed. The second one found later is tracked by #2597.

**Comment by N-body-group-Reed** [comment]
This note is independent of the above discussion, but I thought that it might be helpful. I got the Ckloop "error" message [1] while trying to restart using a checkpoint.

[1]
ChaNGa version 3.4, commit v3.4-140-gdc5af03
Restarting at 250
Not Using CkLoop 0
Initial Domain decomposition ... total 0.198092 seconds.
Done.
