### ISSUE TITLE
Doesn't work on Mac OS

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#260]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/260*

---
No body.

![Screen Shot 2015-02-19 at 6 26 16 PM](https://user-images.githubusercontent.com/1772435/63624944-ba83b880-c5c3-11e9-83a3-a4b20d8153cf.png)

**Comment by PhilMiller** [comment]
*Original date: 2013-08-05 21:36:47*

---
Jonathan says.

**Comment by bilgeacun** [comment]
*Original date: 2015-02-18 00:19:37*

---
From what I learned from Filippo, CharmDebug was actually never supported on Mac OS X.
I'll still spend some effort to get it working.

**Comment by bilgeacun** [comment]
*Original date: 2015-02-25 20:03:54*

---
Converted Linux specific setup of CharmDebug to Mac format, mainly 'size' command was producing different output than Linux, so it needs to be parsed accordingly. 
A screenshot from fixing the setup issues is attached; Start, step, continue buttons are frozen. More investigation is needed to understand what is the next problem.

**Comment by bilgeacun** [comment]
*Original date: 2015-04-01 16:22:44*

---
http://charm.cs.uiuc.edu/gerrit/#/c/662/
