### ISSUE TITLE
Zerocopy QD hangs for ucx-linux-x86_64 on Golub (seen on autobuild)

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2616]
Zerocopy API QD Test seems to hang during ucx-linux-x86_64 autobuilds.  

```
Running on 6 processors:  ./zerocopy_with_qd 142 +isomalloc_sync 
Charm++> Running in non-SMP mode: 6 processes (PEs)
Converse/Charm++ Commit ID: 990d4728c
Charm++> Synchronizing isomalloc memory region...
Charm++> Consolidated Isomalloc memory region: 0x2b6f80000000 - 0x7ff8a0000000 (88642048 MB).
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 2 hosts (1 sockets x 3 cores x 1 PUs = 3-way SMP)
Charm++> cpu topology info is gathered in 0.004 seconds.
[0][0][0] Test 1: QD has been reached for RO Variable Bcast
```

On reverting the latest UCX patches (https://github.com/UIUC-PPL/charm/pull/2562 & https://github.com/UIUC-PPL/charm/pull/2600), the test passes. 

Clearly, since https://github.com/UIUC-PPL/charm/pull/2600 is a minor change, the bug is introduced by https://github.com/UIUC-PPL/charm/pull/2562. 

Since that patch, (https://github.com/UIUC-PPL/charm/pull/2562) also introduced other major bugs like https://github.com/UIUC-PPL/charm/issues/2597, maybe we can revert that patch? (and think of another fix for the bug that the patch was attempting to fix)
@brminich

**Comment by brminich** [comment]
did not manage to get a hang on my local cluster. 
Ok, let's revert it. I'm trying to get an access to frontera to debug the issue.

**Comment by nitbhat** [comment]
@brminich: Okay, that's interesting. It looks like different machines (Golub, Frontera, Thor) are behaving differently. 

This issue has been fixed by https://github.com/UIUC-PPL/charm/pull/2619, and confirmed by the clean autobuild on Golub (http://charm.cs.illinois.edu/autobuild/old.2019_11_26__01_01/ucx-linux-x86_64.txt)
