### ISSUE TITLE
MetaBalancer: add mechanism to inform user of AtSync call that resulted in actual load balancing

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#262]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/262*

---
Per discussion with Prof Kale and Jonathan, we need to add a mechanism to make user aware of whether load balancing was done by RTS in the recently invoked AtSync. One solution that seemed feasible was to overload ResumeAtSync with a function parameter for the same. This overloaded ResumeAtSync in turn can invoke ResumeFromSync (without parameter) so that the existing code base works.

**Comment by stwhite91** [comment]
*Original date: 2017-04-11 20:54:30*

---
The AMPI use case can be covered using ckJustMigrated: https://charm.cs.illinois.edu/gerrit/#/c/2200/
