### ISSUE TITLE
when building from git, the classes directory does not exist and breaks the build process

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#264]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/264*

---
I have attached a patch that adds a rule to the Makefile which creates the directory in case it's not already there.

[0001-Create-classes-directory-in-case-it-doesn-t-exist-al.patch](https://github.com/UIUC-PPL/charm/files/3536375/0001-Create-classes-directory-in-case-it-doesn-t-exist-al.patch.txt)

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-08-09 17:43:43*

---
Oops, I didn't realize that you guys use ant now. Ant builds everything just fine.

The Makefile doesn't work for me though. Is using make to build the code still a supported option?

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-12 17:21:00*

---
This should be short work.

**Comment by bilgeacun** [comment]
*Original date: 2015-02-12 20:18:21*

---
Yes, the right way to build is using 'ant' not 'make'. In fact, Makefile in the repository is not used and it just creates an unnecessary confusion. 
I think I'll just remove the Makefile from there.

**Comment by bilgeacun** [comment]
*Original date: 2015-02-20 00:42:34*

---
http://charm.cs.uiuc.edu/gerrit/#/c/521/
