### ISSUE TITLE
Inefficient +setcpuaffinity defaults

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#2647]
PR #2448 changed `cpuAffinityRecvHandler` to use logical indices when assigning CPU affinity instead of non-portable OS indices in response to Issue #2445, where the latter causes an abort with `+setcpuaffinity` on Bridges. This new numbering scheme may result in poor performance in some cases due to grouping threads as closely as possible on adjacent SMTs while leaving entire cores unused. The example reported is with `+p12` on a 2 sockets x 8 cores x 2 PUs = 32-way SMP machine.

**Comment by rbuch** [comment]
I have also reproduced this on a 1 socket x 4 cores x 2 PUs = 8-way SMP machine, so it doesn't just happen on multi-socket machines.

**Comment by evan-charmworks** [comment]
After working on this for some time I think it's better to just revert the change that introduced this problem. The code in question needs more substantial replacement. #2649
