### ISSUE TITLE
LBDBManager.h disappeared

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2654]
Harshitha wrote a Hierarchical load balancer for ChaNGa that includes LBDBManager.h.  Can someone take a look at HierarchicalLB.cpp in ChaNGa and suggest how to adapt to this change?

**Comment by rbuch** [comment]
After looking at it, I think the inclusion of `LBDBManager.h` can be removed completely. It doesn't look as though anything from that file is used there. I was able to compile and run after removing it.

**Comment by trquinn** [comment]
I committed a fix to ChaNGa.  Thanks.
