### ISSUE TITLE
charmc links libXNVCtrl with non-CUDA build

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2679]
This can be reproduced on SDSC comet: if charm is built on the login nodes, the resulting charmc will link in libXNVCrtl.so.  This library is not on the compute nodes, so the resulting executable will fail when submitted to the queue system.

**Comment by minitu** [comment]
@evan-charmworks I think this is caused somehow by hwloc, as `grep -ir "xnvc"` in the source code gives me `contrib/hwloc/config/hwloc.m4` and `contrib/hwloc/hwloc/topology-gl.c`. Any idea on how to fix this?
