### ISSUE TITLE
Arguments to an sdag method are not available for defining condition of a while statement

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#269]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/269*

---
Seems like arguments passed to an sdag entry methods are not available for use in condition of while statement. They are available for others.

Look at the attached files for an example. I get the following error:

In file included from caseTest.C:12:0:
caseTest.def.h: In member function ‘void Main::_while_0(Closure_Main::run_2_closure*)’:
caseTest.def.h:211:7: error: ‘i’ was not declared in this scope
caseTest.def.h: In member function ‘void Main::_while_0_end(Closure_Main::run_2_closure*)’:
caseTest.def.h:222:7: error: ‘i’ was not declared in this scope

[caseTest.C](https://github.com/UIUC-PPL/charm/files/3536376/caseTest.C.txt)
[caseTest.ci](https://github.com/UIUC-PPL/charm/files/3536269/caseTest.ci.txt)
[Makefile](https://github.com/UIUC-PPL/charm/files/3536270/Makefile.txt)

**Comment by lifflander** [comment]
*Original date: 2013-08-16 06:10:33*

---
Should be fixed. See commit f4ee6b0e301b6de4605b72cfe21bc451bc6044d6

**Comment by nikhil-jain** [comment]
*Original date: 2013-08-16 06:12:45*

---
Tested, works now.

**Comment by PhilMiller** [comment]
*Original date: 2015-07-16 19:23:00*

---
Noting when this was fixed.
