### ISSUE TITLE
Make CkIO safe to use in real application code with proper flush and close calls

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#27]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/27*

---
No body.

**Comment by ericjbohm** [comment]
*Original date: 2013-04-02 21:14:20*

---
Has work resumed on this now that the release is out?

**Comment by PhilMiller** [comment]
*Original date: 2013-05-21 23:59:54*

---
Jim's initial comments from January:


> 
> Looking at the current CkIO interface I don't see any way to close or flush a file or to write other than at the beginning of the file.
> 
> I think the following interface would be sufficient and general:
> 
> void openOutputFile(const char *name, CkCallback ready,
> Options opts = Options());
> 
> void prepareWrite(Token token, size_t bytes, size_t offset,
> CkCallback ready, CkCallback complete);
> 
> write() would only need to be modified to handle non-zero offsets
> passed to prepareWrite, and it would need to be specified if the
> offset passed to write was added to the prepareWrite offset.  It
> appears that write can be called multiple times to write at different
> offsets and still operate properly.
> 
> void closeFile(Token token, CkCallback complete);
> 
> For trajectory files usage would look like this:
> 
> pe 0 calls openOutputFile()
> ready callback calls prepareWrite() for header
> ready callback calls write() for header
> while ( more steps ) {
> complete callback calls prepareWrite() for next frame
> ready callback broadcasts to NAMD IO pes
> NAMD IO pes call write() for frame
> complete callback calls prepareWrite() for header
> ready callback calls write() for header
> }
> complete callback calls closeFile()
> 
> For restart files there would probably be two files opened permanently and renamed and over-written without being closed and re-opened.  For each file this would look like:
> 
> pe 0 calls openOutputFile("restartname.tmp")
> ready callback calls prepareWrite()
> ready callback calls write() for header and broadcasts to NAMD IO pes
> while ( more steps ) {
> NAMD IO pes call write() for frame
> complete callback calls {
> rename("restartname","restartname.old")
> rename("restartname.tmp","restartname")
> rename("restartname.old","restartname.tmp")
> swap file tokens or open "restartname.tmp" if needed
> prepareWrite()
> }
> ready callback calls write() for header and broadcasts to NAMD IO pes
> }
> 
> This seems to make every pe open the file, not just the active ones:
> 
> if (((CkMyPe() - opts.basePE) % opts.skipPEs == 0 &&
> CkMyPe() < lastActivePE(opts)) ||
> true) {
> files[token].fd = openFile(name);
> }
> 
> This error reporting is useless:
> 
> CkPrintf("Output failed on PE %d: %s", CkMyPe(), strerror(errno));
> CkAbort("Giving up");
> 
> The string passed to CkAbort needs to contain the name of the file and the error string.

And his subsequent comments:


> Thinking about the interface some more, there is no need for a barrier after prepareWrite().  The output pes can either buffer output until that message arrives or write any full stripes and wait for the offset and bytes message to write the partial stripes at the beginning and end of the block.  If writes are not buffered then only the size needs to be defined. That would make the interface more like this:
> 
> 
> void openOutputFile(const char *name, CkCallback ready,
> Options opts = Options());
> 
> void setWriteRange(Token token, size_t bytes, off_t offset,
> CkCallback complete);
> 
> // requires setWriteRange, must fill range exactly
> void bufferedWrite(Token token, const void *data,
> size_t bytes, off_t offset);
> 
> void setWriteSize(Token token, size_t bytes, CkCallback complete);
> 
> // can have gaps, should not be mixed with bufferedWrite calls
> void unbufferedWrite(Token token, const void *data,
> size_t bytes, off_t offset);
> 
> 
> void closeFile(Token token, CkCallback complete);
> 
> For trajectory files usage would look like this:
> 
> pe 0 calls openOutputFile()
> ready callback calls setWriteRange() and write() for header
> 
> while ( more steps ) {
> complete callback calls setWriteRange() for next frame
> and broadcasts token to NAMD IO pes
> 
> NAMD IO pes call write() for frame
> complete callback calls setWriteRange() and write() for header
> }
> complete callback calls closeFile()
> 
> For restart files there would probably be two files opened permanently and renamed and over-written without being closed and re-opened:
> 
> 
> pe 0 calls openOutputFile("restartname.tmp")
> ready callback calls setWriteRange() for entire file
> and write() for header
> and broadcasts token to NAMD IO pes
> 
> while ( more steps ) {
> NAMD IO pes call write() for frame
> complete callback calls {
> rename("restartname","restartname.old")
> rename("restartname.tmp","restartname")
> rename("restartname.old","restartname.tmp")
> swap file tokens or open "restartname.tmp" if needed
> setWriteRange() for entire file
> write() for header
> broadcasts token to NAMD IO pes
> }
> }

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 21:51:51*

---
Need to ensure that rewriting already open files works, to reduce metadata load.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-09 22:55:12*

---
Now have revamped design implemented on branch `phil/ckio-next`. The documented public API can be seen in "ckio.h":http://charm.cs.illinois.edu/cgi-bin/gitweb.cgi?p=charm.git;a=blob;f=src/libs/ck-libs/io/ckio.h;hb=refs/heads/phil/ckio-next . 

Still to do are
* Correctness
** -Testing-
** Avoid leaking resources: Deleting session -array elements and the array itself- (Issue #251) once each session is complete
* Performance improvements (basics)
** properly mapping the session array elements to PEs
** -limiting open calls to just PEs that (may ever) have elements-
** benchmarking
* Portability
** -implementing fallbacks from `fdatasync()` where that's not available, to (in general order of preference) `fsync()`, `sync()`, or nothing.- On Blue Waters `sync()` is known to pose trouble, so that may be left out of the line-up.
* Application Convenience
** -implementing a form of session with a specified 'commit' write to wrap it up after the synchronization but before signalling completion-

**Comment by PhilMiller** [comment]
*Original date: 2013-07-10 16:51:09*

---
Jim's comments:
> Looking at redmine, I have no idea what this means:  "implementing a form of session with a specified 'commit' write to wrap it up after the synchronization but before signalling completion"


```
void startSession(FileReadyMsg *file, size_t bytes, size_t offset, CkCallback ready,
                  char *commitData, size_t commitBytes, size_t commitOffset,
                  CkCallback complete);
```
The idea is to specify a small write to be performed after the rest of the data is committed to storage (sync calls done). This is exactly the use case of NAMD's trajectory file write - the session is a frame, and the commit write is the file header update to reflect the added frame.

> I think file offsets should be off_t rather than size_t.

In general, I would agree with you on that, and in fact tried it early in the initial CkIO development. The trouble is that off_t is defined by POSIX, not C or C++, and so doesn't exist on Windows. Its only difference from size_t is that it's signed rather than unsigned. This only matters when doing pointer-relative seeks. Since writes in CkIO's API are all at absolute positions, the lack of negative range doesn't matter.

> The existing error handling is competely unusable for production code. You need to at least print an error message with the name of the file (not done anywhere), what operation failed, and strerror(errno) (missing from open) so the user has some idea what has gone wrong.  The full error message needs to go to CkAbort and not be hidden in a CkPrintf somewhere, and it needs to start with something really loud like "FATAL ERROR:".
> 
> The return value of fsyncdata() is not checked, which is a problem since it can return errors from previous write calls.

All system calls are now checked, and their failures reported fully and explicitly.

> In the public interface, peStripe and writeStripe would be clearer if they were called stripeSize and writeSize. 
> For activePEs, basePE, and skipPEs I think the convention is to not capitalize the e in "Pe". 

I'll consider the names again, and figure out whether those or something else seems best.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-24 00:05:27*

---
Further revisions made to address Jim's comments and concerns - testing, interface being fully defined, serializability, and event matching.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-09 17:39:31*

---
Caught a bug in the implementation of #226 while implementing session commits. It works now. All that's left is mapping, benchmarking, and tuning.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-22 18:50:21*

---
#275 will be the continuation for performance testing, tuning, etc.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 22:48:28*

---
Windows builds now compile successfully.
