### ISSUE TITLE
CpdAborting likely segfault on CpvAccess(cmiArgDebugFlag)

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#2710]
CpdAborting() should check CpvInitialized(cmiArgDebugFlag) && CpvAccess(cmiArgDebugFlag) rather than just CpvAccess(cmiArgDebugFlag), as it is possible for CmiAbort() to be called during early startup (e.g., inside LrtsInit) before PEs are initialized. I'm looking at a stack trace from a user where this seems likely.

**Comment by nitbhat** [comment]
Fixed by https://github.com/UIUC-PPL/charm/pull/2711
