### ISSUE TITLE
Memory leaks in Charisma RTS code

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#272]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/272*

---
Detected by cppcheck 1.61:

```
[src/ck-core/charisma.h:274]: (error) Memory leak: nconnect
[src/ck-core/charisma.h:56]: (style) Class 'Component' is unsafe, 'Component::name' can leak by wrong usage.
```

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 19:09:29*

---
Pritish, please help recruit an understudy to work on Charisma.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-25 21:51:07*

---
These bits have been deleted from the codebase. Hence, this issue is no longer relevant.
