### ISSUE TITLE
Node aware broadcast implementations for groups and arrays

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#2724]
Broadcasting of large [nokeep] messages to groups and arrays results in one copy of the message per PE, due to the fact that neither of these broadcasts are node-aware. In SMP mode, it would be better to have just one copy per node to avoid extra copies. It may also lower comm overhead by only sending the message once to each node and then relying on CmiPushPE to pass the message to the rest of the PEs on node.

First step is to make group broadcasts node aware. This is done in #2440 
Second step is to add additional functionality to extend this to arrays. Arrays broadcasts are built on top of group broadcasts, so this does not involve much change. Done in #2696 

Additional issues have caused bugs in AMPI with node aware array broadcasts.

**Comment by epmikida** [comment]
#2717 is related to this. AMPI uses nokeep and expedited together for all of its broadcasts.

**Comment by stwhite91** [comment]
I think this is done, @epmikida ?
