### ISSUE TITLE
Small fix in documentation

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#274]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/274*

---
I have added missing curly braces in an example code. The patch is against 460b06dae77ccfe3752afb3768a5c45b9abe67b6.

[0001-Fixed-braces-in-documetation.patch](https://github.com/UIUC-PPL/charm/files/3536377/0001-Fixed-braces-in-documetation.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2013-11-11 07:07:02*

---
Applied. Thanks.
