### ISSUE TITLE
Remove build system aliases

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2752]
Several build systems have multiple aliases:

| Alias                       | Real name              |
| --------------------------- | ---------------------- |
| **netlrts-linux-ppc64le**   | ~~netlrts-linux-ppc~~      |
| **mpi-linux-ppc64le**       | ~~mpi-linux-ppc~~          |
| ~~mpi-linux-amd64~~             | **mpi-linux-x86_64**   |
| ~~multicore-linux~~             | ~~multicore-linux32~~ (renamed to **multicore-linux-i386**) |
| **multicore-linux-x86_64**  | ~~multicore-linux64~~      |
| **multicore-linux-ppc64le** | ~~multicore-linux-ppc~~    |
| ~~gemini_gni-crayxe~~       | **gni-crayxe**     |
| **multicore-win-x86_64**    | ~~multicore-win64~~        |
| ~~netlrts-win64~~               | **netlrts-win-x86_64** |
| **mpi-win-x86_64**         | ~~mpi-win64~~              |
|**ucx-linux-ppc64le**|~~ucx-linux-ppc~~|

Names that should remain are marked in **bold**. Names and aliases that have been removed in #2809  and #2812 are shown in ~~strikethrough~~.

We should consider deprecating these. Having multiple aliases results in confusion for people building Charm++, e.g. "What is the difference between `netlrts-win64` and `netlrts-win-x86_64`".

The following build systems should be renamed for consistency and clarity:

| Old name                       | New name              |
| ----| -----|
|~~mpi-linux~~ | mpi-linux-i386|
|~~netlrts-linux~~|netlrts-linux-i386|
|~~uth-linux~~|uth-linux-i386|
|~~multicore-linux~~|multicore-linux-i386 (already mentioned in above table)|
|~~sim-linux~~|sim-linux-i386|

**Comment by evan-charmworks** [comment]
I agree. When an alias is used, the build script should warn the user and say what the standard name is. Some of the aliases and true names should be swapped, such as the `-win64` targets which should all be made aliases to `-win-x86_64` targets. I would further propose renaming `multicore-linux`, `netlrts-linux`, etc to `*-linux-i386`. We may also want to deprecate "arm8" and use "aarch64" and/or "arm64" instead.

**Comment by minitu** [comment]
`ucx-linux-ppc64le` is the one that survives (as in #2812), not `ucx-linux-ppc`, right?

**Comment by matthiasdiener** [comment]
> `ucx-linux-ppc64le` is the one that survives (as in #2812), not `ucx-linux-ppc`, right?

That's right, I fixed the table.
