### ISSUE TITLE
Running with fewer PEs than GPUs fails with floating point exception

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2754]
This circumstance will likely only happen when debugging but:
Running ChaNGa on a node with multiple GPUs and requestion fewer PEs available GPUs will cause a floating point exception in initDeviceMapping() because "pes_per_gpu" rounds to 0 at line 823.

This bug was not in charm v6.9.0.

**Comment by minitu** [comment]
I fixed this issue in the PR that I have recently been working on, will extract the relevant parts and try to merge that in ASAP.
