### ISSUE TITLE
Added additional text to the manual explaining the use of a load balancer in manual mode.

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#276]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/276*

---
The manual neglected to mention that the method StartLB() is not publically accessible in this form. Instead the LBDatabase object has to be referenced. I added some prose to explain this and a code snippet illustrating this.

[0001-Added-explanation-for-how-to-use-a-load-balancer-in-.patch](https://github.com/UIUC-PPL/charm/files/3536380/0001-Added-explanation-for-how-to-use-a-load-balancer-in-.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 19:06:20*

---
Either apply this patch as is, or do a more involved fix to the API as in #277.
