### ISSUE TITLE
Make manual LB invocation more straightfoward, and document it

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#277]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/277*

---
Either explain in the documentation how to call StartLB() (see issue #276) or expose StartLB() such that it is unnecessary to reference the LBDatabase object.

**Comment by rbuch** [comment]
*Original date: 2013-10-09 16:49:50*

---
Traced the path of a StartLB() call, looks like it needs to use myLDHandle.  I'll look into streamlining the process.

Meanwhile, #276 has been resolved, and now more detailed instructions are in the documentation.

**Comment by rbuch** [comment]
*Original date: 2013-10-10 22:22:50*

---
Added new function CkStartLB() that starts load balancing without needing a reference to the LBDatabase object.
