### ISSUE TITLE
Information regarding Charm++/OpenMP hybrid programs is lacking some details

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#278]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/278*

---
I have added some text to Chapter 24 explaining a bit in more detail how hybrid Charm++/OpenMP programs need to be built and run.

[0001-Added-more-text-regarding-Charm-OpenMP-hybrid-coding.patch](https://github.com/UIUC-PPL/charm/files/3536382/0001-Added-more-text-regarding-Charm-OpenMP-hybrid-coding.patch.txt)

**Comment by harshithamenon** [comment]
*Original date: 2015-09-15 15:14:21*

---
I looked at the patch. The patch makes updates to the ckloop section of charm++ manual to say that openmp can be used with Charm++ only in smp mode, which is not true. We can launch 1 charm process on one node and use openmp on other idle cores. But if there are no idle cores, then openmp thread may contend with charm PE.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 21:48:33*

---
~~https://charm.cs.illinois.edu/gerrit/884~~ https://github.com/UIUC-PPL/charm/commit/03e15b521cb54510e4fbf7c1b7133b48c5cf2d6e
