### ISSUE TITLE
Building charm++ - Compiler....

### ISSUE THREAD

**Issue by ZhexueM** [UIUC-PPL/charm#2780]
Hello everybody,
I need a little help compiling charm ++.

Currently I tried on a LINUX server (Debian 10.3 with gcc 9.3.0) to compile and install the charm ++ compiler.
The command here was:
./build charm ++ multicore-linux-x86_64 -j8 --destination = <path>

But the compiler doesn't work because it has multiple links to the location from which I compiled the compiler. This is not a good thing, since this directory is only a temporary thing.

So, what "options" do I have to give to the BUILD command that it installs a complete package - in other words: stores everything there in the "destination" and no links to the temporary directory.

Thank you for your help.
Kind regards and stay healthy

**Comment by matthiasdiener** [comment]
You can install a standalone version with `make install` after  running `./build`. In this case, you do not need to specify any `--destination=` argument. Note that `make install` will not compile anything by itself.

As an example, for your build you can do:
```
$ ./build charm++ multicore-linux-x86_64 -j8
$ cd tmp
$ make DESTDIR=~/charm-dir install
```

Please let me know if that works for you.

**Comment by ZhexueM** [comment]
Dear Matthias,

 

thank you very much for your answer. I was very helpful & it seems, that it works.

 

One Question about the sample-program:

                It is the same between 6.9.0 and 6.10.1 and which

                Directory must I moved to a “public place” for all Cluster – User?

 

 

 

Best regards and take care….

 

 

 

Matthias Krawutschke, Dipl. Inf.

 

Universität Potsdam
ZIM - Zentrum für Informationstechnologie und Medienmanagement

Team Infrastruktur Server und Storage 
Spezialized: High-Performance-Computing and Kubernetes

 

 

Campus Am Neuen Palais: Am Neuen Palais 10 | 14469 Potsdam
Tel: +49 331 977-153065, Fax: +49 331 977-1750

 

Internet:  <https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html> https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html

 

 

Von: Matthias Diener <notifications@github.com> 
Gesendet: Samstag, 28. März 2020 23:25
An: UIUC-PPL/charm <charm@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [UIUC-PPL/charm] Building charm++ - Compiler.... (#2780)

 

You can install a standalone version with make install after running ./build. In this case, you do not need to specify any --destination= argument. Note that make install will not compile anything by itself.

As an example, for your build you can do:

$ ./build charm++ multicore-linux-x86_64 -j8
$ cd tmp
$ make DESTDIR=~/charm-dir install

Please let me know if that works for you.

**Comment by matthiasdiener** [comment]
> It is the same between 6.9.0 and 6.10.1 

Yes, this example should work for any recent version of Charm++, including 6.9.0 and 6.10.1:

```
$ ./build charm++ multicore-linux-x86_64 -j8
$ cd tmp
$ make DESTDIR=~/charm-dir install
```

> which Directory must I moved to a “public place” for all Cluster – User?

Not sure what you mean. The directory specified in `DESTDIR` (`~/charm-dir` in the example that I gave above) contains everything needed to compile and run a Charm++ application. You should not have to move anything. If multiple users want to compile Charm++ applications, you could set `DESTDIR` to a system-wide location, e.g. something like:

```
# ... same commands as above
$ sudo make DESTDIR=/opt/charm install
```

**Comment by matthiasdiener** [comment]
I'll close this issue. Please re-open in case you have followup questions.
