### ISSUE TITLE
Building charm++ on RADXA RockPI 4 - NODE with aarch64 - DEBIAN - Kernel...

### ISSUE THREAD

**Issue by ZhexueM** [UIUC-PPL/charm#2781]
Hello everybody,
I need a little help compiling charm ++.

Currently I tried on a LINUX server (Debian 10.3 with gcc 9.3.0) to compile and install the charm ++ compiler.
The command here was:
./build charm ++ multicore-arm8 -j8 --destination = <path>

But when compiling my NODE breaks off & I can only address / work with a REBOOT.
What is possibly wrong here or what can I look up where and why the NODE breaks off / dies here? Does anyone have an idea?

Thank you for your help.
Kind regards and stay healthy

**Comment by evan-charmworks** [comment]
Try building with a lower `-j` value for parallelism. I've worked with Charm on Raspberry Pis and if I use a value higher than -j2, even on a 4-core board, I eventually get kernel panics, possibly due to overheating.
