### ISSUE TITLE
LBDatabase module disappeared

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2792]
Compiling ChaNGa with the latest charm release (commit 0e4c85210d754c3b5ff0ad5e8fe65d95fbf5abbf) fails with:
Compiling TreePiece.cpp...
In file included from HierarchOrbLB.h:8,
                 from TreePiece.cpp:21:
HierarchOrbLB.decl.h:7:10: fatal error: LBDatabase.decl.h: No such file or directory
    7 | #include "LBDatabase.decl.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

It looks like the interface to LBDatabase has changed; how do I rewrite the ChaNGa code (see TreePiece::balanceBeforeInitialForces()) for the new interface?

**Comment by rbuch** [comment]
Basically, this has been renamed to `LBManager`. I'll take a look at the ChaNGa code and make a PR to fix this.
