### ISSUE TITLE
Has Bigsim already been obsoleted? 

### ISSUE THREAD

**Issue by Ricahrd-Li** [UIUC-PPL/charm#2798]
Hi guys, 
I follow the doc of BigSim parallel simulator [(link)](https://charm.readthedocs.io/en/v6.10.1/bigsim/manual.html) trying to build bgampi using the command ``./build bgampi netlrts-linux-x86_64 -O2``  and ``./build bgampi netlrts-linux-x86_64 bigemulator -O2``, and I get ``make: *** No rule to make target 'bgampi'.  Stop. `` and ``Error> option: bigemulator is not supported in this version!``

Also I notice that you have removed Bigsim from Charm++ in issue [#2703](https://github.com/UIUC-PPL/charm/pull/2703) , so I am wondering if Bigsim simulator has already been obsoleted?  and what version of Charm++ should I use if I need to use Bigsim? thanks a lot.

**Comment by ericjbohm** [comment]
Hello Li Zhehao,

Yes we have obsoleted BigSim and the BigSim simulator.  They have been superseded by the TraceR and Charades projects.   Is there some essential functionality that they had that you find lacking elsewhere?  We were not aware that anyone was actively using BigSim.

**Comment by Ricahrd-Li** [comment]
Thanks for your reply! 
These days I am using bigsim and traceR to do some simulations of mpi collective communication, and I notice that to install traceR I need to first install bigsim from Charm++ v6.10.0, and to run the simulation I need to use bigsim emulator first and then replay the trace in traceR.  
Anyway, I will check out the doc of traceR if I meet any problem, thank you again.

**Comment by matthiasdiener** [comment]
Closing this issue. Please feel from to reopen if you have further questions.
