### ISSUE TITLE
MPI_Get_version not implemented

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#284]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/284*

---
IMB_MPT1 makes a call to this function, then ignores the result.  I commented that out as a workaround, but we should support this function.

**Comment by mprobson** [comment]
*Original date: 2013-10-25 21:19:09*

---
Done! Tested with tiny C and f90 codes.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-29 16:22:26*

---

```
d:\cygwin\home\gengbin\autobuild\multicore\charm\multicore-win32\tmp\libs\ck-libs\ampi\ampi.c(5466) : error C4716: 'AMPI_Get_version' : must return a value
```

Return success, please, like the spec says.

**Comment by mprobson** [comment]
*Original date: 2013-10-29 20:27:52*

---
Fixed the return value. Why don't we utilize MPI_SUCCESS and just return 0 instead?
