### ISSUE TITLE
Build and test failures on Windows

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#286]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/286*

---
Since the SDAG overhaul was merged, we've seen very consistent test failures on Windows builds. On 64-bit, this exhibits as consistent crashes in `examples/charm++/leanmd`. On 32-bit, there seems to be a persistent crash in `tests/charm++/sdag/case`. The failure mode of the latter is such that subsequent autobuild runs can't succeed without sysadmin intervention, because the executable is locked and this can't be deleted the following day.

These ongoing test failures are the majority of autobuild's red lights right now, and are putting a damper on ongoing work.

**Comment by PhilMiller** [comment]
*Original date: 2013-09-04 16:54:54*

---
When this is fixed, please revert commit:212d1e3a4673443732a2856c266fb1e9ee860851

**Comment by lifflander** [comment]
*Original date: 2013-10-24 21:56:22*

---
Phil: Do you remember if this is with the cygwin build?

**Comment by PhilMiller** [comment]
*Original date: 2013-10-24 22:00:36*

---
It looks like it was explicitly the non-cygwin mpi/multicore builds:
http://charm.cs.uiuc.edu/autobuild/old.2013_09_01__03_32/

**Comment by lifflander** [comment]
*Original date: 2013-10-30 19:48:58*

---
Bug has been reproduced. Working on a solution.

**Comment by lifflander** [comment]
*Original date: 2013-11-02 00:39:32*

---
SDAG's cast to CkMessage (which may not be C++ legal), seemed to be causing the memory address the change arbitrarily; fix is to just cast to void*

patch commit: 3012d79c6b78e6c25ce0674a5fc3b66ab0cd4a72

reverted (disable test commit): 212d1e3a4673443732a2856c266fb1e9ee860851

**Comment by lifflander** [comment]
*Original date: 2013-11-02 00:49:57*

---
There still may be an issue in charmxi, which I am still investigating. The major crashing with leanmd is fixed, and the caseTest runs.

**Comment by lifflander** [comment]
*Original date: 2013-11-07 21:44:47*

---
Seems to be fixed based on manual windows testing, but autobuild for windows seems to be broken

**Comment by PhilMiller** [comment]
*Original date: 2014-01-13 23:39:41*

---
Verified that Windows builds are clean at present, so moving up to current release.
