### ISSUE TITLE
charm++/hwloc causes NAMD to link to libcudart.so

### ISSUE THREAD

**Issue by pwang234** [UIUC-PPL/charm#2860]
NAMD intends to only link to the static CUDA libraries. But it looks if CUDA path is in CPATH, then charm++/hwloc will automatically pick up CUDA and add "lcudart" to charm-v6.10.1/multicore-linux64-gcc/tmp/conv-mach-opt.sh:

CMK_HWLOC_LIBS="-lhwloc_embedded -lm   -lcudart"

This in turn causes NAMD to link to libcudart.so.

**Comment by matthiasdiener** [comment]
Thank you for the report. This issue might be related to #2062 and #2121.

**Comment by pwang234** [comment]
./build charm++ multicore-linux64 gcc --with-production --enable-tracing -j

**Comment by pwang234** [comment]
A bit more info: when CUDA is in my CPATH, I saw the following output with the above build command:

checking for cuda.h... yes
checking if CUDA_VERSION >= 3020... yes
checking for cuInit in -lcuda... yes
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking if CUDART_VERSION >= 3020... yes
checking for cudaGetDeviceProperties in -lcudart... yes

**Comment by evan-charmworks** [comment]
@pwang234 I believe this is fixed in our master branch. Would you be able to retest this for us?
