### ISSUE TITLE
cmake build system is not installing liveViz.h

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2863]
With the latest master, a "./build ChaNGa ...." doesn't copy liveViz.h into include, and so ChaNGa fails to build.
Reverting to commit 26216d4526783ab87cc2664be7e8c7ab062aa1ff fixes the problem.

**Comment by matthiasdiener** [comment]
Thanks for the report @trquinn. Could you please check if #2864 fixes this issue?
