### ISSUE TITLE
CkReductionMgr::reduceMessages() using CkReduction::set incorrectly wraps the leaf node reduction message

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#287]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/287*

---
The first contribution of a child node is a single message. In this case CkReductionMgr::reduceMessages() simply returns the message without calling the reducer. However, when using the CkReduction::set reducer this behavior is incorrect, and instead the reducer should be called even for one single message so that the message is wrapped into a setElement struct. In the current implementation, the reduction becomes corrupted because the CkReduction::set() method one tier up in the reduction sizes the remote contribution incorrectly assuming a setElement struct and not a simple message. I have attached a patch that seems to fix this issue.

Caveat: This is the first time I dove into the Charm++ sources so deeply. So my analysis might very well be totally off. Please check carefully. In my limited tests however, the current charm branch does not correctly reduce a set, and the patch fixes this problem.

[0001-Fixed-bug-in-CkReductionMgr-reduceMessages.patch](https://github.com/UIUC-PPL/charm/files/3536393/0001-Fixed-bug-in-CkReductionMgr-reduceMessages.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2013-10-22 01:19:40*

---
It looks like the offered patch was applied. Is there anything else to be done, or should this issue be closed?

**Comment by harshithamenon** [comment]
*Original date: 2013-10-22 01:26:12*

---
I looked at the patch and verified that it is indeed correct and tested it before checking in the patch.
