### ISSUE TITLE
Compiler warning outpouring for checkpoint code

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#289]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/289*

---
The ckmemcheckpoint.h:76 line comes out 282 times in a normal production build for LIBS, so fixing that one alone would go a long way to making compilation quieter.

The middle portion of those isomalloc lines happen in a normal build, but a syncft build adds a few more.

On a related note, there is a theme here of ignoring the return value from system and IO calls.  Not at all reassuring in the context of fault tolerant code.

-------sample of related warning output----------

../../../../bin/../include/ckmemcheckpoint.h: In member function ‘void CkCheckPTEntry::init(int, int)’:
../../../../bin/../include/ckmemcheckpoint.h:76: warning: ignoring return value of ‘int mkstemp(char*)’, declared with attribute warn_unused_result

ckmemcheckpoint.C: In constructor ‘CkDiskCheckPTInfo::CkDiskCheckPTInfo(CkArrayID, CkGroupID, CkArrayIndex, int, int)’:
ckmemcheckpoint.C:271: warning: ignoring return value of ‘int mkstemp(char*)’, declared with attribute warn_unused_result

ckmemcheckpoint.C:704: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result

isomalloc.c: In function ‘read_randomflag’:
isomalloc.c:80: warning: ignoring return value of ‘fscanf’, declared with attrib
ute warn_unused_result
../bin/charmc  -optimize -production   -c -I. cpuaffinity.c
isomalloc.c: In function ‘init_ranges’:
isomalloc.c:2099: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result
isomalloc.c:2100: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result
isomalloc.c:2128: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result
isomalloc.c:2139: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result
isomalloc.c:2140: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result
isomalloc.c:2144: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result
isomalloc.c:2167: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result
isomalloc.c:2168: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result
isomalloc.c:2182: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result
isomalloc.c:2205: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result
isomalloc.c:2206: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:28:38*

---
This sort of thing hugely bloats autobuild output, and gets in the way of other developers. Please get it fixed.

**Comment by xiangni** [comment]
*Original date: 2013-10-08 05:44:20*

---
Eric already fixed it.

**Comment by ericjbohm** [comment]
*Original date: 2013-10-08 21:28:21*

---
I only fixed the most verbose of these errors.  Isomalloc has an alarming number of warnings.  Several write operations in the checkpoint code do not check the return value for failure.  There are too many calls like that in the checkpoint code.  I haven't studied them to be sure that there is an actual flaw, but whether you successfully wrote the checkpoint, or not, is something the runtime system should be certain to handle.  At the very least by dying an appropriately loud death.

**Comment by xiangni** [comment]
*Original date: 2013-10-10 05:02:48*

---
Fix two placed in ckmemcheckpoint.C. Hand over to Nikhil for isomalloc fix

**Comment by PhilMiller** [comment]
*Original date: 2013-10-10 05:12:45*

---
Xiang: Is it really appropriate to abort execution on failure to create a checkpoint, when the program itself might still run perfectly well to completion? This turns some filesystem failures into hard job failures.

I'm not sure how to balance between catching user errors where they point the checkpoint mechanism someplace that it will never successfully write, and maximizing the chances of successful execution in the face of irrelevant external problems. Perhaps this design issue is something for the core group to discuss.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-09 18:56:35*

---
Those warnings are not showing up anymore.
