### ISSUE TITLE
Add application tests to GitHub CI

### ISSUE THREAD

**Issue by matthiasdiener** [UIUC-PPL/charm#2890]
Restore the test(s) we did in Jenkins.

**Comment by matthiasdiener** [comment]
Added Changa (#2892). Was planning to add NAMD as well, but getting compilation errors (LB related?):

```
g++ -m64 -std=c++0x -I/home/mdiener/Work/charm/netlrts-linux-x86_64/include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvars/src -DSTATIC_PLUGIN -I/Projects/namd2/tcl/tcl8.5.9-linux-x86_64-threaded/include -DNAMD_TCL  -I/Projects/namd2/fftw/linux-x86_64/include -DNAMD_FFTW     -DNAMD_VERSION=\"3.0alpha\" -DNAMD_PLATFORM=\"Linux-x86_64-netlrts\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTREE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -O3 -fexpensive-optimizations -ffast-math  -o obj/mainfunc.o -c src/mainfunc.C
In file included from src/BroadcastObject.h:18,
                 from src/Broadcasts.h:12,
                 from src/mainfunc.C:12:
src/LdbCoordinator.h:43:9: error: ‘LDObjid’ does not name a type; did you mean ‘LDOMid’?
   43 | typedef LDObjid LdbId;
      |         ^~~~~~~
      |         LDOMid
```

@minitu @rbuch Is this a known issue?

**Comment by rbuch** [comment]
> Added Changa (#2892). Was planning to add NAMD as well, but getting compilation errors (LB related?):
> 
> ```
> g++ -m64 -std=c++0x -I/home/mdiener/Work/charm/netlrts-linux-x86_64/include -DCMK_OPTIMIZE=1 -Isrc -Iinc    -Iplugins/include -Icolvars/src -DSTATIC_PLUGIN -I/Projects/namd2/tcl/tcl8.5.9-linux-x86_64-threaded/include -DNAMD_TCL  -I/Projects/namd2/fftw/linux-x86_64/include -DNAMD_FFTW     -DNAMD_VERSION=\"3.0alpha\" -DNAMD_PLATFORM=\"Linux-x86_64-netlrts\"  -DREMOVE_PROXYRESULTMSG_EXTRACOPY -DNODEAWARE_PROXY_SPANNINGTREE -DUSE_NODEPATCHMGR -DBONDED_CUDA -DUSE_HOMETUPLES    -DUSE_CKLOOP=1 -O3 -fexpensive-optimizations -ffast-math  -o obj/mainfunc.o -c src/mainfunc.C
> In file included from src/BroadcastObject.h:18,
>                  from src/Broadcasts.h:12,
>                  from src/mainfunc.C:12:
> src/LdbCoordinator.h:43:9: error: ‘LDObjid’ does not name a type; did you mean ‘LDOMid’?
>    43 | typedef LDObjid LdbId;
>       |         ^~~~~~~
>       |         LDOMid
> ```
> 
> @minitu @rbuch Is this a known issue?

Yeah, I ran into this last week, it's nothing to do with the new LB stuff, it's because the CMake build doesn't do the same configure checks as the old build. In the old build, the variable that controls this (`CMK_LBID_64BIT`) is set in `configure.ac` and the variable is then defined in `conv-autoconfig.h`. Is there a place in the CMake build where this should go instead?

**Comment by matthiasdiener** [comment]
> Yeah, I ran into this last week, it's nothing to do with the new LB stuff, it's because the CMake build doesn't do the same configure checks as the old build. In the old build, the variable that controls this (`CMK_LBID_64BIT`) is set in `configure.ac` and the variable is then defined in `conv-autoconfig.h`. Is there a place in the CMake build where this should go instead?

Right, #2893 should fix this.

**Comment by matthiasdiener** [comment]
NAMD and ChaNGa have been added to Github CI. Closing this bug, but feel free to reopen in case we want to add additional tests.
