### ISSUE TITLE
AMPI Privatization: Structure-building source-source transformation

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#291]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/291*

---
The idea is to use rose to parse program and find all global static, pack them into struct and then replace all with struct references. 
(1) With help of Pei-hung from Rose group, now global can be correctly found and packed. 
(2) static can be found , but not correctly packed

**Comment by PhilMiller** [comment]
*Original date: 2013-09-13 03:27:32*

---
Just ran across this mailing list message from 2 years back indicating that some Sandia folks also tried this:
https://mailman.nersc.gov/pipermail/rose-public/2011-May/000973.html

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-29 21:43:15*

---
I am not working on this approach any more. Phil's tool seems to work well. This is not something we do need.
