### ISSUE TITLE
charmc: Inconsistent handling of distinction between C and C++ linking

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#292]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/292*

---
Some places in `charmc` use the variable `OPTS_LD`, others use `OPTS_LDXX`, and some even use both! We need to either unify them, or systematically make sure both cases are covered everywhere that's appropriate.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-09 20:57:27*

---
Spelling fix

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-09 18:34:10*

---
Variables OPTS_LDXX, CMK_CXX_OPTIMIZE and CMK_CXX_PRODUCTION removed.

Need to update documentation for "-ld++" and "-ld++-option".

**Comment by mprobson** [comment]
*Original date: 2015-08-27 20:58:45*

---
Per Core discussion

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 05:40:37*

---
A partial fix, though probably quite rusty at this point: ~~https://charm.cs.illinois.edu/gerrit/#/c/515/~~ https://github.com/UIUC-PPL/charm/commit/a1b7f0d0c06633f3ecedc2643669f254ef19d690

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-20 23:22:36*

---
This issue description is solely about OPTS_LD(XX), while the linked patch also affects CMK_CXX_OPTIMIZE and CMK_CXX_PRODUCTION. Phil's comment on the patch suggests the latter two are out of scope of this issue.

If I updated the patch and also made it only about OPTS_LDXX, would that satisfy this issue?

**Comment by stwhite91** [comment]
*Original date: 2018-02-20 23:28:09*

---
Yeah I think so

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-20 23:40:28*

---
~~https://charm.cs.illinois.edu/gerrit/515~~ https://github.com/UIUC-PPL/charm/commit/a1b7f0d0c06633f3ecedc2643669f254ef19d690
