### ISSUE TITLE
Use of deprecated features in charmrun.C

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#293]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/293*

---
Fix the compiler warning: deprecated conversion from string constant to ‘char*’ in charmrun.C

[0001-Fixed-deprecated-conversion-from-const-char-to-char-.patch](https://github.com/UIUC-PPL/charm/files/3536394/0001-Fixed-deprecated-conversion-from-const-char-to-char-.patch.txt)
[0001-More-const-correctness-fixes-for-charmrun.patch](https://github.com/UIUC-PPL/charm/files/3536395/0001-More-const-correctness-fixes-for-charmrun.patch.txt)

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-10 08:54:37*

---

Will apply this after #285.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-14 00:24:46*

---
We're going with improving the const-correctness of that code, instead of covering up where we've not been const-correct previously.

As a point of history, charmrun used to be C code, rather than C++, up until quite recently. Thus, the compiler wasn't as insistent about warning of non-const pointers to string literals.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2013-10-17 19:56:36*

---

Changed some parameters in a function declaration to const since theie usage was of const. This gets rid of half the warnings. Rest others are more of the format:

arg_v[argc++] =  "++ssh"

Any suggestions on what to do with these?

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-17 21:08:47*

---
All you should have to do is change it to

-       arg_argv[arg_argc++]="++debug";
+       arg_argv[arg_argc++]= (char*) "++debug";

**Comment by PhilMiller** [comment]
*Original date: 2013-10-17 21:28:47*

---
Casting away constness would be papering over safety issues that the compiler can protect us against. It's much preferable to actually push the const declarations through the system to the fullest extent possible.

Have a look at how I fixed one of the remaining instances in commit:5420dae, and follow that approach. Essentially, find where it's complaining about a bad assignment, and mark the corresponding variable declaration const. If that causes errors elsewhere, chase them down and make their variable declarations const too. If you run into a place in the code where something's modifying the memory pointed to by one of those variables, then congratulations, const-correctness enforcement caught a bug for us. _That's_ the part that truly needs to be fixed.

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-18 16:34:55*

---
Thanks, good points. How about this patch?

**Comment by PhilMiller** [comment]
*Original date: 2013-10-18 21:04:46*

---
Fixes incorporated, with some additional changes to push the const-ness further through, and _only_ cast it away at calls to `exec*`.
