### ISSUE TITLE
Added parsing logic so that ++debug-commands can be used with several gdb commands separated by "\n"

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#294]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/294*

---
Since gdb lacks anything like ';' to separate several commands in one line, the commands need to be separated by a newline character. I have added some parsing logic so that the string "\n" will now be translated into the character '\n'.

[0002-charmrun.C-parsing-of-strings-now-parses-n-into-n.patch](https://github.com/UIUC-PPL/charm/files/3536396/0002-charmrun.C-parsing-of-strings-now-parses-n-into-n.patch.txt)

**Comment by ericjbohm** [comment]
*Original date: 2013-09-11 23:24:37*

---
Logic looks fine to me.  Passed testing.  Is checked in.  Thanks for the patch!

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:21:53*

---
Adding target version so it will show up in the Roadmap, and subsequent release notes.
