### ISSUE TITLE
Hang in varTRAM test on UCX builds with oversubscription

### ISSUE THREAD

**Issue by minitu** [UIUC-PPL/charm#2987]
varTRAM test sometimes hangs or exceeds the time limit on GitHub CI UCX builds.
This might have been fixed with the recent update to UCX 1.8.1, but should still look into it and decrease varTRAM test's execution time if it takes too long.

**Comment by evan-charmworks** [comment]
UCX 1.8.1 did not fix the issue. The hang still occurs in the UCX CI sometimes.

**Comment by minitu** [comment]
Error log:
```
make -C varTRAM test OPTS='-g -optimize -production' TESTOPTS=''
make[2]: Entering directory '/home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/tests/charm++/varTRAM'
../../../bin/charmc -g -optimize -production  vartest.ci
../../../bin/charmc -g -optimize -production  -c vartest.C
../../../bin/charmc -g -optimize -production  -language charm++ -o vartest vartest.o
../../../bin/testrun  ./vartest +p4 8 100 100 

Running on 4 processors:  ./vartest 8 100 100 
charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 4  ./vartest 8 100 100 
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: v6.11.0-devel-327-g3c68eb6fd
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
Charm++> cpu topology info is gathered in 0.034 seconds.
Time : 111575976 us
##[error]The operation was canceled.
```

**Comment by minitu** [comment]
I think the hang occurs when the 4 processes are forced to map to 2 cores (as in the GitHub CI virtual machine).
On LLNL Lassen:
```
choi18@lassen2:varTRAM$ jsrun -n4 -a1 -c1 ./vartest 8 1000 100 +pemap L0,1
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: v6.11.0-devel-326-gd49980552
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map (logical indices): 0,1
Charm++> Running on 1 hosts (2 sockets x 20 cores x 4 PUs = 160-way SMP)
Charm++> cpu topology info is gathered in 0.082 seconds.
Time : 579870845 us
(hangs)
```

**Comment by minitu** [comment]
Looks like the only necessary change is to change the test to use +p2 instead of +p4.
Will be AFK for a couple of hours, will submit a patch afterwards (if @evan-charmworks would like to do so you're more than welcome to).

**Comment by evan-charmworks** [comment]
That should be sufficient to resolve the CI hang, but doesn't this indicate a problem that still needs to be fixed? Oversubscription should cause slowdowns but not indefinite hangs.

**Comment by minitu** [comment]
True, will keep this issue open until the hang with oversubscription is resolved.

**Comment by minitu** [comment]
Closing as we are now transitioning from TRAM to Hypercomm (https://github.com/jszaday/hypercomm-aggregation).
