### ISSUE TITLE
Add cmake rules to machine layer folders

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2999]
I noticed that making changes to `src/arch/mpi/machine.C` and building my already built `mpi-linux-x86_64` build doesn't build the changed files. I am guessing this is because there aren't any cmake rules added to the machine layer folders. @matthiasdiener?

**Comment by matthiasdiener** [comment]
Into which library does src/arch/mpi/machine.C go? I can only see it included in libconv-machine, and this seems to work for me:

```bash
$ cd mpi-darwin-x86_64/

$ make conv-machine
Scanning dependencies of target conv-machine
Building CXX object src/conv-core/CMakeFiles/conv-machine.dir/__/arch/mpi/machine.C.o
Linking CXX static library ../../lib/libconv-machine.a
ar: creating archive ../../lib/libconv-machine.a
Built target conv-machine

$ touch ../src/arch/mpi/machine.C

$ make conv-machine
Scanning dependencies of target conv-machine
Building CXX object src/conv-core/CMakeFiles/conv-machine.dir/__/arch/mpi/machine.C.o
Linking CXX static library ../../lib/libconv-machine.a
ar: creating archive ../../lib/libconv-machine.a
Built target conv-machine
```

**Comment by matthiasdiener** [comment]
A potential issue that I could see here is `.C` files that are `#include`d inside `machine.C`:

```
src/arch/mpi/machine.C:
421:#include "machine-common-core.C"
424:#include "machine-ctrlmsg.C"
606:#include "machine-onesided.C"
```

**Comment by matthiasdiener** [comment]
@nitbhat Do you still see this issue?

**Comment by nitbhat** [comment]
Sorry for the delay in getting back, I'll check soon and let you know.

**Comment by matthiasdiener** [comment]
Can you check if this is still an issue?

**Comment by nitbhat** [comment]
I think I was missing something when I opened this issue. I verified that changes to `machine.C`, `machine-onesided.C and `machine-rdma.h` are being reflected correctly on building. I'll close this for now and reopen it if I happen to see any source code changes not being reflected in the build.
