### ISSUE TITLE
Provide full topology information in partititioned runs on BGQ

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#3]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/3*

---
On some platforms that have meaningful network topology, running a partitioned job results in getting linearized topology information. Where possible, such as when the partition count neatly divides the machine, the information returned should be fully accurate.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-01 19:28:41*

---
Nikhil, please document which platforms are affected by this and to what extent. It may make the most sense to open a separate issue per platform, since any fixes could be assigned and completed for each independently. Feel free to de-assign this once that much is clear.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-17 19:29:15*

---
I think this is done now, correct? Calls to TopoManager within a partition will return appropriate answers?

**Comment by PhilMiller** [comment]
*Original date: 2013-09-04 21:33:34*

---
As mentioned during today's NAMD meeting, PAMI builds still return linearized coordinates in partitioned runs, due to past storage volume concerns. Nikhil said he'll replace the existing topology code there with calls to recently-exposed PAMI/SPI library calls, thereby fixing this issue.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-22 01:30:20*

---
TopoManager with sane topology output while using partitions is in branch bgq_topology. I am currently testing it, following which it will be merged.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-23 04:28:07*

---
The branch was merged to master.
