### ISSUE TITLE
Can't build wave2D example

### ISSUE THREAD

**Issue by NK-Nikunj** [UIUC-PPL/charm#3004]
As the title suggests, I am unable to build wave2D example in charm++ directory.

```
nk@f3lix:~/install/Release/charm/examples/charm++/wave2d(master)$ make all
../../../bin/charmc -module liveViz  -g  wave2d.ci
../../../bin/charmc -module liveViz  -g -c wave2d.C
wave2d.C:1:10: fatal error: liveViz.h: No such file or directory
    1 | #include "liveViz.h"
      |          ^~~~~~~~~~~
compilation terminated.
Fatal Error by charmc in directory /home/nk/install/Release/charm/examples/charm++/wave2d
   Command g++ -I../../../bin/../include -D__CHARMC__=1 -g -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -std=c++11 -c wave2d.C -o wave2d.o returned error code 1
charmc exiting...
make: *** [Makefile:19: wave2d.o] Error 1
```

On a closer inspection of the include directory from my charm++ build, I see that there is no liveViz.h:

```
nk@f3lix:~/install/Release/charm/netlrts-linux-x86_64/include(master)$ ls liveViz*
liveViz3d.decl.h  liveViz3d.def.h  liveViz.decl.h  liveViz.def.h  liveVizPoll.decl.h  liveVizPoll.def.h
```

I'm using charm++ commit `05a360eb0` on Arch linux on kernel 5.7.11 with gcc 10.1 as my compiler.

**Comment by matthiasdiener** [comment]
Can you post your `./build` command?

**Comment by NK-Nikunj** [comment]
I use the following command to build charm++:

`./build charm++ netlrts-linux-x86_64 --enable-tracing -j6`

**Comment by matthiasdiener** [comment]
I think you have to build the LIBS target instead:

```
$ ./build LIBS netlrts-linux-x86_64 --enable-tracing -j6
```

**Comment by NK-Nikunj** [comment]
I confirm that building LIBS builds the example successfully.

**Comment by matthiasdiener** [comment]
Closing this issue as the error appears to have been fixed. Feel free to reopen in case there are additional build problems with liveViz.
