### ISSUE TITLE
Crash in TreeLB with p > 1 and ppn > 1 

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#3013]
When running an SMP build with `p` > 1 and `ppn` > 1 with a TreeLB based load balancer, programs crash. The issue is that `awaitingLB[0]` becomes false prematurely because somehow the LB decision message for some PEs reports that there are no incoming objects, but there are in reality, so that PE thinks that LB is done but then receives incoming objects.

To reproduce, run `examples/charm++/load_balancing/hello` with:
`./charmrun +p4 ++ppn 2 ./stencil3d 64 32 +balancer GreedyLB`

Found in the course of testing #2990.

**Comment by evan-charmworks** [comment]
Is the segfault in `examples/charm++/load_balancing/hello` related?

**Comment by rbuch** [comment]
> Is the segfault in `examples/charm++/load_balancing/hello` related?

Yes, I believe so. I think I've traced it to message corruption due to reuse, which leads to a race between packing and local use, if it packs first, then the pointers are all invalid, causing the segfault.
