### ISSUE TITLE
Slow startup using NAMD UCX

### ISSUE THREAD

**Issue by dkokron** [UIUC-PPL/charm#3035]
The NAMD application uses charm++ for process communication. charm++ has a native UCX implementation that greatly improves runtime scalability of NAMD, however, job startup scales inversely with process count. I have measured job startup at ~8 minutes when using ~2000 processes (48 nodes). Are you aware of any way to improve this situation?

My platform is x86_64 (skylake)
`./build charm++ ucx-linux-x86_64 icc ompipmix --suffix xpmem --with-production $base_charm_opts --basedir=$HPCX_UCX_DIR -j12`

```
ucx_info -v
# UCT version=1.9.0 revision fcd1255
# configured with: CC=icc CXX=icpc --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --without-knem --without-java --prefix=/xxxx/play/Mellanox/hpcx-v2.7.0-gcc-MLNX_OFED_LINUX-4.7-1.0.0.1-suse12.5-x86_64/ucx-icc-cuda-xpmem --with-cuda=/nasa/cuda/11.0 --with-mlx5-dv --with-rc --with-ud --with-dc --with-ib-hw-tm --with-dm --with-cm --enable-mt --with-gdrcopy --with-xpmem=/xxxx/XPMEM/hjelmn/xpmem/install
```

**Comment by ericjbohm** [comment]
2000 processes is a lot for 48 nodes.  Is there a reason for not using the SMP build?  One could then launch one process per socket and address the cores with worker threads,

**Comment by dkokron** [comment]
NAMD recommends against SMP due to poor multi-node scaling.  That is also my experience (poor SMP scaling compared with native UCX).

**Comment by ericjbohm** [comment]
That runs counter to our usual experiences.  The large scale runs we are familiar with are almost always ucx-...-smp based. Could you provide a specific reference to that non-smp recommendation?  Note that the launch command has to be revised slightly to leverage the SMP based executable, otherwise you may experience poor scaling due to thread oversubscription.

**Comment by dkokron** [comment]
Hmm, I was referring to MPI based SMP having poor scalability.  I haven't
tried UCX+SMP yet.  Still, this doesn't directly address that main concern
which is slow startup of the native UCX build.  For comparison, a pure MPI
build using MPT (HPE formerly SGI) starts in a few seconds on the same set
of nodes.

Dan

**Comment by ericjbohm** [comment]
Could you provide a sample of the launch command you are using that results in slow startup?

**Comment by dkokron** [comment]
My startup command for the native UCX build is 
mpiexec -np 1920 --bind-to core --map-by ppr:20:socket -x UCX_TLS="rc,xpmem,self" .........................

I'm following build instructions at
http://www.hpcadvisorycouncil.com/events/2020/APAC-AI-HPC/pdf/HPC-AI_Competition_NAMD_Benchmark_Guideline.pdf

Oddly, they don't have a section on UCX+SMP.

**Comment by dkokron** [comment]
Please let me know if you would like any more information.
Dan
