### ISSUE TITLE
some libraries are only built statically, preventing a Charm++ installation with only dynamic libraries

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#304]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/304*

---
I package Charm++ for Gentoo Linux, but the same should be true for other Linux distributions:

On a typical Linux system only shared libraries are installed, because of the usual security and bloat arguments. However, if I build charm with --build-shared, and then install only what is in lib_so, the charmc script breaks because some Converse libraries are built purely as .o and don't end up in lib_so. One example is seed based load balancing, e.g. libldb-rand.o. As far as I can tell, this is not too hard to fix. In the main makefile, the targets libldb-*.o are renamed to libldb-*.a, and the charmc script now tests both .a and .so when linking the seed based load balancing code.

I have attached a patch against charm/HEAD.

[0001-Some-libraries-are-only-built-statically.patch](https://github.com/UIUC-PPL/charm/files/3536399/0001-Some-libraries-are-only-built-statically.patch.txt)
[0001-Some-libraries-are-only-built-statically.patch.1](https://github.com/UIUC-PPL/charm/files/3536397/0001-Some-libraries-are-only-built-statically.patch.1.txt)
[0001-Some-libraries-are-only-built-statically.patch.2](https://github.com/UIUC-PPL/charm/files/3536398/0001-Some-libraries-are-only-built-statically.patch.2.txt)

**Comment by PhilMiller** [comment]
*Original date: 2013-10-12 18:18:22*

---
This mostly looks good. One question on the change to `charmc`. Should the first condition and associated then branch refer to `libldb-$BALANCE.a` as it's now being built, rather than the current `libldb-$BALANCE.o`?

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-14 21:11:56*

---
Yes, you are right, I missed that one. I have worked on the patch a bit more and attached the new version. I had to also change the linker order a bit because changing something like `libldb-*.o -> libldb-*.a` means that the library has to come after libck. Please have another critical look. Thanks.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-14 21:30:26*

---
That looks like it solves the issue I pointed out.

Could you abstract the repeated `$CHARMLIB/libfoo.a|$CHARMLIBSO/libfoo.so`  selection logic into a standalone function?

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-15 04:33:21*

---
What do you think of this?

As an aside, I noticed that the parallel build breaks now when using --build-shared at the point the makefile is trying to build the libmemory-*.{a,so} modules. I think it's because the modules all come from the same source file, memory.c, and the intermediate, memory.o, goes missing or is overwritten when several threads are building different modules.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-24 17:18:59*

---
There's a makefile trick to avoid the trouble that both multiple targets from a source and parallel builds encounter here, but it looks a bit hackish to the uninitiated - I half scared a professor in undergrad using it on an assignment. Essentially, for each target, the makefile needs to create a corresponding named symlink to the source file, so that any intermediate object files get the unique target's name and not the common source file's name. I'll look at implementing that here, though it may run into trouble on our Windows builds, where symlinks are faked.

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-10-24 17:21:51*

---
I don't quite understand why symlinking helps. Why not create a temporary name and then run the compiler with "-c -o TEMPNAME.o"? Wouldn't that solve this problem?

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 21:16:45*

---
Deferring to after the 6.6 release, because I'm not quite ready to deal with the changes necessary to preserve parallel compilation.

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-11-20 20:12:10*

---
What about copying the files instead of symlinking in the makefile to avoid problems on Windows (or simply stop supporting Windows ;-) )? If you think that's a good idea, I'll have a go at an updated patch...

**Comment by PhilMiller** [comment]
*Original date: 2015-01-19 22:37:04*

---
Changes to be pushed shortly.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 19:14:56*

---
Pushed here, waiting for Nikhil's assistance in dealing with `mpi-mainmodule.o`: http://charm.cs.uiuc.edu/gerrit/#/c/465/

**Comment by PhilMiller** [comment]
*Original date: 2015-07-09 20:00:45*

---
I was dumb, and didn't notice that Nikhil had answered my request within a few hours. This could have been merged months ago.
