### ISSUE TITLE
JSON header file preventing charmc to use Kokkos' nvcc_wrapper as underlying compiler

### ISSUE THREAD

**Issue by minitu** [UIUC-PPL/charm#3042]
To allow both Charm++ and Kokkos code to be in the same compilation unit, `charmc` should be able to use Kokkos' `nvcc_wrapper` as the underlying compiler. This is because the Kokkos headers contain code with `__device__` flags that need to be passed through `nvcc_wrapper` (or `nvcc -x cu`). While current Charm++ code can be compiled with just `nvcc` (which treats input files according to their file extension), it fails to compile with `nvcc -x cu` (which treats the input files as `.cu`) because the JSON header file in Charm++ (`src/util/json.hpp`) does not compile (see https://github.com/nlohmann/json/issues/1773 for more details). This issue has not been fixed as of JSON v.3.9.1. When the JSON header file is switched with an older version, compilation either fails due to some weird memory allocation issue or it does not have the APIs that Charm++ uses (e..g `contains()`).

**Comment by minitu** [comment]
I worked around this issue by commenting out all the JSON related code in Charm++, but this will either not make load balancing work properly or disallow LB configurations.

**Comment by rbuch** [comment]
Would something like mentioned [here](https://github.com/nlohmann/json/issues/1773#issuecomment-544694584) work (seemingly adding the `--host-only` flag to CMake when compiling JSON-relevant files)?

**Comment by minitu** [comment]
@rbuch I don't think that will work for GPU execution, since the Kokkos headers configured with CUDA contain device code that needs to be compiled with `nvcc -x cu`. So compiling a source code that has both Charm++ and Kokkos code should be done with `charmc` with `nvcc_wrapper` / `nvcc -x cu` as the underlying compiler (or `nvcc_wrapper` with the proper Charm++ includes, flags, and so on)

**Comment by matthiasdiener** [comment]
Would renaming `json.hpp` to `json.C` (and doing the appropriate build system changes) fix this issue?

**Comment by minitu** [comment]
@matthiasdiener It would work as long as the JSON header file is not included by default when compiling Charm++ programs.

**Comment by minitu** [comment]
Reproducing the issue:

First build Kokkos (the following is what I used on Summit)
```
$ git clone -b 3.2.00 git@github.com:kokkos/kokkos.git
$ cd kokkos
$ mkdir build && cd build
$ cmake ../ -DCMAKE_CXX_COMPILER=$HOME/kokkos/bin/nvcc_wrapper -DCMAKE_INSTALL_PREFIX=$HOME/kokkos/install -DKokkos_ENABLE_CUDA=On -DKokkos_ENABLE_SERIAL=On -DKokkos_ARCH_POWER9=On -DKokkos_ARCH_VOLTA70=On
$ make -j && make install
```
then compile a Charm++ program (e.g. `examples/charm++/hello/1darray`) with `charmc` using `nvcc_wrapper` underneath (`charmc -c hello.C -c++ $(HOME)/kokkos/install/bin/nvcc_wrapper`).
For PAMI builds you also need to remove the spaces after the `-I` and `-L` flags in `CMK_SYSINC` and `CMK_SYSLIBS` in `conv-mach.sh`.
