### ISSUE TITLE
VERSION file in include/ conflicts with other libraries

### ISSUE THREAD

**Issue by nilsleiffischer** [UIUC-PPL/charm#3044]
The `include/` directory of a Charm++ installation has a `VERSION` file that contains the Charm++ version string. This file leads to conflicts with other libraries that may try to `#include <version>`, most notably Boost@1.73+. Here's the specific code in Boost that tries to include the file and fails: https://www.boost.org/doc/libs/1_74_0/boost/config/detail/select_stdlib_config.hpp

Do you have suggestions how to deal with this issue on my end? And/or should the `VERSION` file perhaps move to a more charm-specific place, such as `include/charm/version.h`?

**Comment by matthiasdiener** [comment]
Thank you for the report @nilsleiffischer. This is probably related to an issue affecting some versions of clang (#2844). Could you please add information about which OS you are using, and whether the file system is case-sensitive?

**Comment by nilsleiffischer** [comment]
Hi @matthiasdiener, this issue occurred on macOS 10.15.6, where the file system is case-insensitive. Feel free to close this issue as a duplicate of #2844, we can discuss there instead.

**Comment by matthiasdiener** [comment]
Thanks @nilsleiffischer. I'll close this issue. Let's continue in #2844.
