### ISSUE TITLE
"file with unrecognized extension" on macOS

### ISSUE THREAD

**Issue by nilsleiffischer** [UIUC-PPL/charm#3045]
We're getting the following error when linking on the macOS machines used by GitHub Actions:

```
file with unrecognized extension /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd
```

This might be related to the issue https://github.com/UIUC-PPL/charm/issues/2495 that was fixed by implementing a workaround. @matthiasdiener can you perhaps provide some insight?

## Environment

GitHub Actions workflow running on a GitHub-hosted macOS machine. Here's the details:

```
Current runner version: '2.273.0'
##[group]Operating System
Mac OS X
10.15.6
19G2021
##[endgroup]
##[group]Virtual Environment
Environment: macos-10.15
Version: 20200825.1
Included Software: https://github.com/actions/virtual-environments/blob/macos-10.15/20200825.1/images/macos/macos-10.15-Readme.md
##[endgroup]
```

Here's the link to the included software again: https://github.com/actions/virtual-environments/blob/macos-10.15/20200825.1/images/macos/macos-10.15-Readme.md

We're running Charm++ v6.10.2.

**Comment by matthiasdiener** [comment]
Can you post the full command line of the compilation that fails? is this during the Charm++ build? If yes, what is your ./build command?

**Comment by nilsleiffischer** [comment]
@matthiasdiener This occurs when using `charmc` to link an executable. Here's an example GitHub workflow that fails: https://github.com/nilsleiffischer/spectre/runs/1056818593?check_suite_focus=true

`charmc` is invoked as: `charmc -pthread -module DistributedLB -no-charmrun`

We're configuring the build with CMake, so here's an excerpt from its configuration that could also be relevant:
```
-- CMAKE_CXX_FLAGS: -Werror
-- CMAKE_CXX_LINK_FLAGS: -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/Users/runner/spack/var/spack/environments/spectre/.spack-env/view/lib
-- CMAKE_CXX_FLAGS_DEBUG: -g0 -DSPECTRE_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
-- CMAKE_EXE_LINKER_FLAGS:  -mmacosx-version-min=10.11
```

I realize this is probably not quite enough information to go on, so if there's more information I can give that might help, please let me know.

**Comment by evan-charmworks** [comment]
Does this help?

```diff
diff --git a/src/scripts/charmc b/src/scripts/charmc
index 910ced9047..944b84fb6f 100755
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -475,12 +475,6 @@ do
 		SKIP_MODULEINIT="yes"
 		;;
 
-	"-isysroot")
-		# Ignore -isysroot and the following argument (macOS SDK path),
-		# which charmc can not parse (Bug #2495).
-		shift
-		;;
-
 	"-language")
 		# Parse out some fake languages (that are actually modules)
 		case "$1" in
@@ -775,7 +769,7 @@ do
 		ARG_OPTS_CPP="$ARG_OPTS_CPP -I$1"
 		shift
 		;;
-	--pre-include|-include|--system-include|-isystem|-iquote|-idirafter)
+	--pre-include|-include|--system-include|-isystem|-iquote|-idirafter|-isysroot)
 		ARG_OPTS_CPP="$ARG_OPTS_CPP $arg $1"
 		shift
 		;;
```

**Comment by nilsleiffischer** [comment]
@evan-charmworks thanks for suggesting, I tried compiling from `master` and applied your patch, but the issue remained the same.

**Comment by matthiasdiener** [comment]
> @matthiasdiener This occurs when using `charmc` to link an executable. Here's an example GitHub workflow that fails: https://github.com/nilsleiffischer/spectre/runs/1056818593?check_suite_focus=true
> 
> `charmc` is invoked as: `charmc -pthread -module DistributedLB -no-charmrun`

Can you provide the full charmc command? E.g., by building the tests with `make VERBOSE=1`?

**Comment by matthiasdiener** [comment]
@nilsleiffischer can you check if this patch fixes this for you?

```patch
diff --git a/src/scripts/charmc b/src/scripts/charmc
index 910ced904..a8e15b1c9 100755
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -784,7 +784,9 @@ do
                # See https://github.com/UIUC-PPL/charm/issues/2617 for details.
                OPTS="$OPTS $arg"
                ;;
-
+    *.tbd)
+        OPTS="$OPTS $arg"
+        ;;
        -D*|-I*)
                if echo "$arg" | grep ' '  > /dev/null 2>/dev/null
                then
```

**Comment by nilsleiffischer** [comment]
That did the trick @matthiasdiener! Thank you for investigating! Do you think #3046 might make it into a bugfix release?

**Comment by matthiasdiener** [comment]
> That did the trick @matthiasdiener! Thank you for investigating! Do you think #3046 might make it into a bugfix release?

Thanks for reporting back! The question regarding the bugfix release is unfortunately a bit above my pay grade. I think it is not likely that we will have another 6.10.x release, but if we do, I can see this PR getting added to it. In any case, this will be part of 6.11, which should be released soon.
