### ISSUE TITLE
Cannot launch on stampede with >4k processes

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#305]
*Original author: Akhil Langer*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/305*

---
ibverbs build on stampede is not able to launch a job for num pes greater than or equal to 4k. 
tried different options ++scalable-start, ++batch, ++timeout, ++mpiexec but none of them succeeded
getting the following error messages:
error attaching node xxx
socket closed on error recv

**Comment by rbuch** [comment]
*Original date: 2013-12-04 22:56:08*

---
I observed the same issue in running NAMD on Stampede.  It works fine up to 2048 processors, but 4096 fails with Charmrun: Bad initnode data length.

This uses Charm version net-linux-x86_64-ibverbs-iccstatic and NAMD version Linux-x86_64-memopt.

The program is executed with the following flags: +p4096 ++scalable-start ++mpiexec ++remote-shell mpiexec +pemap 0-15

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:36:31*

---
Any update on this Abhishek?

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-01-03 05:48:14*

---

I do not think this is a problem with the launch. 

This issue is likely due to the Ibverbs Q-pair scalability problem, since we form P*P total Queue pairs in our implementation. 
The permanent solution would be to do something similar to what MVAPICH does - create on-demand QPs. I think Bilge has worked on ibud implementaion. Once that implementation is in place, the next step would be to extend it along the lines of what MVAPICH does. We could add a warning when a user tried to run the current layer beyond 8 or 16K, that it has some issues. MVAPICH may also be doing some message-coalescing. 

I can try playing with some parameters (like maxTokens) in current implementation to see if that can help scaling beyond 4K.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-04 08:46:53*

---
Can you comment on how Q-pairs set up may be the bottleneck - those many Q pairs not allowed? Memory constraint? Either looks unreasonable for 4K PEs. Also, P*P pairs are distributed over P processes, hence Q-pairs per PE are only P. 

Also, do you have insight on if number of sockets connection may be the bottleneck? Some one else had suggested this to be the probable cause.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 07:14:23*

---
Pritish just reported the same concern for net-layer. I suspect limit on ssh connections.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-06 08:05:41*

---
It can't be SSH connections, since 
* the ssh bits of the process worked fine in Pritish's latest report ("Node program started")
* The bug manifests when using `++mpiexec`, which has no SSH dependence at all.

Number of open sockets (either per-process or per-node) is very likely the culprit. On a Stampede head node, the output of `ulimit -n` (open files) is 1024, and of `ulimit -H -n` (hard limit on open files from kernel/system configuration)  is 4096.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 08:46:32*

---
Those numbers seem to match the 4096 limit that has been reported by multiple sources. That could be the culprit for ibverbs too (though I am not 100% sure) - connections to charmrun as server? This should be easy to verify (Abhishek being assigned this task - can you test that?). Once verified, at least resolution for ibverbs can be done.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-01-06 15:34:52*

---

The issue Pritish reported and the Ibverbs issues are apparently different. It appears that the ibverbs issue is not related to limit on number of open socket connections.

1. When I run a job and check for ulimits from the job script, it shows as 16384 for both soft and hard limit.

2. I can run on 4K on net layer by the following command line:
./charmrun +p4096 ++nodelist nodelist  ./hello 10000 ++verbose ++scalable-start ++timeout 60 ++batch 64
Pritish's problem was  that it was timing out while waiting for processes to connect to charmrun. All 4K processes were tyring to connect causing a bottleneck. Batching avoids that. For details, you can read the paper on startup.

3. On ibverbs, with that parameter, I get the bad initnode data length error. Lot of times, the error happens when a process died during initialization, in which case, an error message is sent to charmrun instead of NodeInfo data charmrun is expecting.

The likely reason is that some node crashed when doing that connection startup. 
One workaround is to use the SMP version as it creates fewer pairs.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-01-06 16:09:50*

---
I changed a parameter maxTokens in machine-ibverbs.c from 8000 to 1000 (even that I think is very large) and now I was able to succesfully start and complete a hello array example on ibverbs layer on 4K. So, that shows it was a problem with queue pair connection issue. (See the summary below)

./charmrun +p4096 ++nodelist nodelist  ./hello 10000 ++verbose ++scalable-start ++batch 128

We should do more testing with a reduced value of maxTokens and see if that is working. Then the ibverbs layer should scale better. 
-------------------------

Here is the summary of ibverbs scalability bottlenecks:

1. The main scalability issue is that in our implementation, there is one Queue Pair (QP) per connection. So, for N processes, there are N QPs. Now when we create a QP, we specify the number of WQE (Work Queue Elements) for each QP. For send queue, this is the number of maximum outstanding send allowed. For receive, a shared receive queue is typically used, which alleviates the problem with receives.

So, the memory requirement for each process is

(numNodes-1) * number of  send WQE + fixed number * receive buffers + fixed number * send packet pre-allocated buffers

The first term grows with numNodes, and becomes memory bottleneck. A 2007 CCGRID paper shows that when using the static QP creation (at start of MPI job) for mvapich, for 8K processes, using the default allocation of 200 send WQEs requires around 1 GB of memory per process.

In our implementation, we currently have number of WQE = maxTokens (=8000), which means that our memory usage would be huge. I think this is too large a number for communication between 2 processes. For large messages, we will use RDMA anyway.

The solution would be to do something similar to what MVAPICH does - create on-demand QPs. I think Bilge is working on ibud implementaion. Once that implementation is in place, the next step would be to extend it along the lines of what MVAPICH does. We could add a warning when a user tried to run the current layer beyond 8 or 16K, that it has some issues. MVAPICH may also be doing some message-coalescing.

2. For both send and receive, there are completion queues (SendCq, RecvCq), so we think that polling is not of the order of numNodes.

3. When not using Shared receive queue (implementation for non-mellanox HW),  the memory requirement for receive buffers grows as
numNodes * Fixed buffers per node.
This is another scaling bottleneck but this is only true when not using shared receive queue. Hence, target audience for this may be very small.

4. There is a fixed limit (4000) for total number of outstanding send packets on any process (across all QPs). Similarly, there is a limit on total outstanding receives. These limits could be problematic when there are lot of small messages (e.g all-to-all communications)

**Comment by PhilMiller** [comment]
*Original date: 2014-02-04 23:07:21*

---
Has any of the testing of this modified parameter been done? If not, will you do it, or should that be assigned to someone else? An arbitrary inability to launch at larger node counts is brokenness that we shouldn't let linger.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-02-10 15:10:05*

---

I tested that for some example programs on Stampede and they work. I have not tested applications. I did some literature survey to find what values other implementations use, e.g. mvapich seem to use 200 according to a 2007 CCGrid paper. May be even 1000 is too high. We should also test with a value of 500. Not sure if there will be a performance impact, I do not think there should be any. It should either run or crash. I can test NAMD and ChaNGa, or if it can be assigned to someone, that should also work.

Do we have SUs on Stampede, it shows as negative.

TG-ASC050039N       -332  2014-06-30

**Comment by PhilMiller** [comment]
*Original date: 2014-02-17 05:32:43*

---
Since it seems we have an issue with getting this tested and hammered out quickly, I'll suggest the following resolution, involving two changes:
1. Change the default to 1000 as tested
2. Add a runtime command-line option that can override the default, so that further tweaking can be done without code changes (i.e. we can simply document "add the argument to set maxTokens to N") if we find that the shipped default was not what we want, prior to a subsequent release.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-02-17 19:58:01*

---

I like Phil's suggestion. Once the core group agrees on a resolution, I can put that in.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-17 20:13:22*

---
Just discussed it in core. Please go ahead with the suggested approach.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-19 20:53:07*

---
Bilge tested that the new default and the command line option work.
