### ISSUE TITLE
FEM & ParFUM libraries suffer from several poor coding practicies

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#306]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/306*

---
Malloc and new are intermingled here for various local tempories.  There is no apparent reason for malloc being used for some int arrays while new is used for others.  Using cppcheck I disentangled erroneous frees of new alloced memory and visa-versa.  However, if these libraries are renovated for some new production application use, they should be cleaned up to use memory sensibly, strip out dead code, and generally go through a comprehensive overhaul.

**Comment by stwhite91** [comment]
*Original date: 2018-04-29 22:55:34*

---
I think these libraries are currently more likely to be deprecated/removed than to receive time spent on code cleanup.
