### ISSUE TITLE
charmxi doesn't parse std::size_t (but parses size_t)  

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#3065]
I ran into this error while building ExaM2M with charm master. 

The error I see is:
```
[PARSE-ERROR] Unexpected/missing token at line 15. Current token being parsed: 'size_t'.
/scratch/nitin/ExaM2M_2/src/IO/meshwriter.ci:15:11-38: error: invalid entry method attribute list
  const std::vector< std::size_t >& inpoel,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fatal Error by charmc in directory /scratch/nitin/ExaM2M_2/build_debug/IO
```

A simpler example to reproduce the issue is an entry method like `entry void write(std::size_t abc);`. 
This throws the following error: 
```
../../../../bin/charmc   direct_api.ci
[PARSE-ERROR] Unexpected/missing token at line 7. Current token being parsed: 'size_t'.
direct_api.ci:7:9-32: error: invalid entry method attribute list
  entry void write(std::size_t abc);
      ^^^^^^^^^^^^^^^^^^^^^^^^
Fatal Error by charmc in directory /scratch/nitin/charm_2/tests/charm++/zerocopy/direct_api_test
   Command ../../../../bin/charmxi -orig-file direct_api.ci returned error code 1
charmc exiting...
```

Since this was working previously, by running git bisect, I found that this bug was introduced by 
https://github.com/UIUC-PPL/charm/commit/6498e1752bcb4b64fa5ac03c1fc416ab6dff05bc (PR https://github.com/UIUC-PPL/charm/pull/2775)

**Comment by jbakosi** [comment]
@nitbhat until this is fixed, what do you suggest as a workaround in client code? Use `size_t` instead of `std::size_t` and risk that eventually will have to revert to `std::size_t` or eventually both will work?

**Comment by nitbhat** [comment]
@jbakosi: I think it's best to keep it the way it is since @evan-charmworks already has a patch to revert that change. (https://github.com/UIUC-PPL/charm/pull/3293)

**Comment by jbakosi** [comment]
Thanks, @nitbhat. This came up while attempting to update Charm++ in quinoa to the latest master and I just decided to [update only to v6.10.2](https://github.com/quinoacomputing/quinoa/pull/473) instead for now, which did not exhibit this problem. We should perhaps update ExaM2M to the same.
