### ISSUE TITLE
Collision Detection library gives varied results for multiple executions (and sometimes hangs)

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#3067]
This bug can be reproduced by running the `examples/collide/collideSimpleTest` test on the https://github.com/UIUC-PPL/charm/tree/nitin/collideBug branch. 

(Link to test: https://github.com/UIUC-PPL/charm/tree/nitin/collideBug/examples/collide/collideSimpleTest) 

I saw that even with the same number of PEs, I saw different number of collisions with multiple execution instances. Additionally, with different number of PEs, different number of collisions were seen. 

Occasionally, I also saw that some runs just hung during execution:
```
charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 3  ./hello 4
Charm++> Running on MPI version: 3.0
Charm++> level of thread support used: -1 (desired: 0)
Charm++> Running in non-SMP mode: 3 processes (PEs)
Converse/Charm++ Commit ID: v6.11.0-devel-388-g75c93fcfd
Charm++ built without optimization.
Do not use for performance benchmarking (build with --with-production to do so).
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 4 cores x 2 PUs = 8-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 3 processors for 4 elements
Creating element 0 on PE 0 and registering chunk as 0
[0][0][0] registerContributor chunkNo:0, nContrib:1
Creating element 1 on PE 0 and registering chunk as 1
[0][0][0] registerContributor chunkNo:1, nContrib:2
[0][0][0] CollideBoxesPrio chunkNo:0
Creating element 2 on PE 1 and registering chunk as 2
[1][1][0] registerContributor chunkNo:2, nContrib:1
Creating element 3 on PE 2 and registering chunk as 3
[2][2][0] registerContributor chunkNo:3, nContrib:1
[1][1][0] CollideBoxesPrio chunkNo:2
[0][0][0] CollideBoxesPrio chunkNo:1
[2][2][0] CollideBoxesPrio chunkNo:3
```

While speaking to @epmikida about his, he suspected that this could be caused by issues related to demand creation (like  issue https://github.com/UIUC-PPL/charm/issues/1324)

**Comment by evan-charmworks** [comment]
Could this be caused by floating point nondeterminism?

**Comment by nitbhat** [comment]
There was a silly error in my example causing all of this. It is required to call `bbox.empty()` to initialize the `min`/`max` variables. I was missing that call and those uninitialized variables caused all the trouble in the while loop (inside CollisionAggregator::aggregate) causing it to run infinitely. Calling `empty` before bbox initialization gives me consistent outputs and the hangs disappear.
