### ISSUE TITLE
Test Miniapps with New LB

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#3073]
Please post the results of running the new LBs with miniapps and other notes here.

**Comment by ZwFink** [comment]
It appears that the Barnes-Hut MiniApp doesn't use any load balancing. The Makefile links Charm++'s LB framework, but major load imbalance is observed when specifying/not specifying a load balancer. I searched the files for ```AtSync```/```ResumeFromSync``` and different variations of ```load```, ```balance```, and ```LB``` in case there has been an API change but didn't get any hits. 

I also tried using periodical load balancing with no effect. 

I'll try to find another MiniApp that uses load balancing and, failing that, use my code from the "Particles" training exercise to test the new LB framework.

**Comment by Wingpad** [comment]
LeanMD has `usesAtSync=True` across a few of its key classes, and en/disabling load-balancing had an effect for some of the configurations. The application did not crash during my testing.

| Configurations | # PEs     | # Steps |           |           |
|-----------|-----------|----------------|-----------|-----------|
| SMP       | 3 PEs     | 250 iterations |           |           |
| None      | Greedy    | GreedyRefine   | Refine    | Rotate    |
| 0m16.864s | 0m17.316s | 0m17.408s      | 0m17.045s | 0m17.133s |
|           |           |                |           |           |
| SMP       | 7 PEs     | 40 iterations  |           |           |
| None      | Greedy    | GreedyRefine   | Refine    | Rotate    |
| 0m16.861s | 0m19.138s | 0m16.403s      | 0m16.656s | 0m18.954s |
|           |           |                |           |           |
| Non-SMP   | 7 PEs     | 40 iterations  |           |           |
| None      | Greedy    | GreedyRefine   | Refine    | Rotate    |
| 0m21.356s | 0m21.630s | 0m21.968s      | 0m21.788s | 0m22.258s |

**Comment by minitu** [comment]
AMR test with 21 PEs (single socket) on OLCF Summit: `jsrun -n1 -a1 -c21 ./advection 3 32 30 9 +balancer DistributedLB +ppn 21 +pemap L0-80:4 +LBDebug 1` (3 LB steps)
PAMILRTS machine layer and SMP were used.

Both legacy modes (e.g. `-module GreedyLB` and `+balancer GreedyLB`) and TreeLB modes (e.g. `-balancer TreeLB` and `+balancer GreedyLB`) perform identically. The following table depicts the times for 3 different runs with each balancer.

Balancer | Simulation times | LB times
-- | -- | --
DistributedLB | 3.012396 s / 3.079687 s / 3.014520 s | 815 us, 740 us, 631 us / 838 us, 709 us, 658 us / 723 us, 741 us, 666 us
RotateLB | 3.873125 s / 3.874235 s / 3.872757 s | 370 us, 153 us, 75 us / 356 us, 152 us, 111 us / 372 us, 152 us, 79 us
GreedyLB | 3.036625 s / 3.052978 s / 3.103677 s | 748 us, 678 us, 717 us / 902 us, 736 us, 635 us / 698 us, 690 us, 681 us
GreedyRefineLB | 3.046412 s / 3.042482 s / 3.071557 s | 511 us, 327 us, 127 us / 453 us, 240 us, 128 us / 459 us, 245 us, 130 us

Non-SMP versions (e.g. `jsrun -n21 -a1 -c1 ./advection 3 32 30 9 +balancer GreedyLB +pemap L0-80:4 +LBDebug 1`) also work fine.

**Comment by minitu** [comment]
Also `+balancer DistributedLB` doesn't work with `-balancer TreeLB`, although this might be intended.

**Comment by ZwFink** [comment]
All experiments were performed using the particles code on 2-4 PEs. There was no difference in performance between TreeLB and the legacy mode LBs. Correctness was unaffected in SMP and non-SMP modes.

**Comment by rbuch** [comment]
> Also `+balancer DistributedLB` doesn't work with `-balancer TreeLB`, although this might be intended.

Yeah, this is intended, it has a different underlying structure, so it's a fully separate LB.

**Comment by rbuch** [comment]
All the tests look good, so closing.
