### ISSUE TITLE
+setcpuaffinity may not work in presence of partitions

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#309]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/309*

---
The default affinity will not be optimal if same physical node is shared by multiple partitions.

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-20 21:26:39*

---
I believe this was fixed long ago. Id ee1725dfae72ae3d7dbd4adae2f1785a3284b71d

**Comment by PhilMiller** [comment]
*Original date: 2014-04-20 23:36:43*

---
Reset target version, sine it's actually fixed in this release.
