### ISSUE TITLE
hwloc build issues in packaged tarball

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#3113]
Two things:

1. The layout of `contrib/hwloc` seems to have been changed so that there is no longer a `src/` folder (in #2558 when it was updated to v2.1.0), so the `package-tarball.sh` script needs to be updated.
2. I tried updating the `package-tarball.sh` script to reflect the new file structure (changing `src/` -> `hwloc/`), but then trying to build Charm++ from the generated tarball seems to do some kind recursive make when building hwloc that errors out. Trying this while packaging only `include/Makefile.in` and packaging all of the root `Makefile.in`, `hwloc/Makefile.in`, and `include/Makefile.in` (along with the original attempt, which was `hwloc/Makefile.in` and `include/Makefile.in`) results in the same behavior.

**Comment by matthiasdiener** [comment]
Does this already affect the 6.11.0-beta1 tarball?

**Comment by evan-charmworks** [comment]
If I change the `git add -f` line to instead `git checkout -- contrib/hwloc/`, it fixes the CMake build but breaks buildold.

**Comment by rbuch** [comment]
> If I change the `git add -f` line to instead `git checkout -- contrib/hwloc/`, it fixes the CMake build but breaks buildold.
> 
> Maybe buildold should not subsume hwloc's configure into Charm's and should instead call it from Make like we do for ROMIO.

Yeah, that seems like a good fix. Keeping them decoupled should make things simpler here.

**Comment by rbuch** [comment]
> Does this already affect the 6.11.0-beta1 tarball? ie, the tarball isn't buildable?

Yes, although the tarball on GitHub isn't the same tarball as what the script would generate, it's an automatically generated snapshot of the tag.

**Comment by evan-charmworks** [comment]
Fixed
