### ISSUE TITLE
Error building load_balancing example with EveryLB on v6.11.0-beta1

### ISSUE THREAD

**Issue by fmahebert** [UIUC-PPL/charm#3123]
While investigating the 6.11 beta I've noticed the following build failure. I see this on two different machines, using clang and gcc as the C++ compiler.

1. `git checkout v6.11.0-beta1`
2. ` ./build LIBS multicore-linux-x86_64   -j8  --with-production`
3. `cd multicore-linux-x86_64/examples/charm++/load_balancing/hello/`
3. `make` <-- succeeds
4. `make clean`
5. edit `Makefile` to replace `CommonLBs` -> `EveryLB`
6. `make` <-- fails with this error:
```
../../../../bin/charmc  -language charm++ -module EveryLB -o hello hello.o
/usr/bin/ld: ../../../../bin/../lib/libmoduleEveryLB.a(EveryLB.C.o): in function `_registerEveryLB()':
EveryLB.C:(.text+0x39): undefined reference to `_registerMetisLB()'
collect2: error: ld returned 1 exit status
```

**Comment by matthiasdiener** [comment]
Thank you for the report @fmahebert! Could you please check if #3130 fixes this for you?

**Comment by fmahebert** [comment]
@matthiasdiener Yes — #3130 fixes the builds with EveryLB on both systems I've been testing on. Thanks!

**Comment by fmahebert** [comment]
However... after compiling with `-module EveryLB`, the output of `./hello +balancer help` suggests that the majority of the LBs that were available on v6.10.2 are not available on v6.11.0-beta1:
```
Available load balancers:
* TreeLB:	TreeLB
* DistributedLB:	The distributed load balancer
* CentralLB:	CentralLB base class
* MetisLB:	Use Metis(tm) to partition object graph
```

@matthiasdiener Do you know if this is expected behavior? If not, I can open another issue to track that.

**Comment by matthiasdiener** [comment]
> However... after compiling with `-module EveryLB`, the output of `./hello +balancer help` suggests that the majority of the LBs that were available on v6.10.2 are not available on v6.11.0-beta1:
> 
> ```
> Available load balancers:
> * TreeLB:	TreeLB
> * DistributedLB:	The distributed load balancer
> * CentralLB:	CentralLB base class
> * MetisLB:	Use Metis(tm) to partition object graph
> ```
> 
> @matthiasdiener Do you know if this is expected behavior? If not, I can open another issue to track that.

Might this be due to the new LB infrastructure @rbuch ?

**Comment by rbuch** [comment]
> > However... after compiling with `-module EveryLB`, the output of `./hello +balancer help` suggests that the majority of the LBs that were available on v6.10.2 are not available on v6.11.0-beta1:
> > ```
> > Available load balancers:
> > * TreeLB:	TreeLB
> > * DistributedLB:	The distributed load balancer
> > * CentralLB:	CentralLB base class
> > * MetisLB:	Use Metis(tm) to partition object graph
> > ```
> > 
> > 
> > @matthiasdiener Do you know if this is expected behavior? If not, I can open another issue to track that.
> 
> Might this be due to the new LB infrastructure @rbuch ?

Yes, we removed a lot of the unused LB based on asking the mailing list/discussion. The list that's displayed is a bit misleading in that a lot of the common load balancers are now included under the TreeLB umbrella (GreedyRefine, Greedy, Refine, Rotate, etc.). If there's a particular LB that users were relying is no longer included, we can potentially add it back in (note that I'm currently bringing back RecBipartLB for SpECTRE for this reason).

**Comment by fmahebert** [comment]
@rbuch Okay, thanks for clarifying and for bringing back RecBipartLB!

**Comment by rbuch** [comment]
> @rbuch Okay, thanks for clarifying and for bringing back RecBipartLB!

This is being done in #3133.
