### ISSUE TITLE
Target files for netlrts-darwin-x86(_64)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#313]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/313*

---
Per Jim:
> It would be nice to have a netlrts-darwin-x86_64 port so that people can test replica code on their laptops.

May as well make the corresponding 32-bit x86 as well.

**Comment by nikhil-jain** [comment]
*Original date: 2013-10-30 20:51:18*

---
Is 32-bit x86 on macs common? Should we care?
