### ISSUE TITLE
+balancer help doesn't show TreeLB sub-balancers

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#3131]
From @fmahebert via https://github.com/UIUC-PPL/charm/issues/3123#issuecomment-716086771

> However... after compiling with `-module EveryLB`, the output of `./hello +balancer help` suggests that the majority of the LBs that were available on v6.10.2 are not available on v6.11.0-beta1. Only these are displayed:
> 
> ```
> Available load balancers:
> * TreeLB:	TreeLB
> * DistributedLB:	The distributed load balancer
> * CentralLB:	CentralLB base class
> * MetisLB:	Use Metis(tm) to partition object graph
> ```

If this message can't list all the TreeLB subtypes, it should at least indicate they exist and maybe where a list can be found.

Maybe CentralLB should be hidden from this list as well.

**Comment by matthiasdiener** [comment]
Could also replace the CkAbort with CkExit.
