### ISSUE TITLE
Make error when building individual LB on v6.11.0-beta1

### ISSUE THREAD

**Issue by fmahebert** [UIUC-PPL/charm#3136]
Following the documentation for [building individual LBs](https://charm.readthedocs.io/en/latest/charm++/manual.html?highlight=CkStartLB#compiler-and-runtime-options-to-use-load-balancing-module), subsection 2, leads to the following error:
```
$ cd multicore-linux-x86_64/tmp
$ make MetisLB
make: *** No rule to make target 'MetisLB'.  Stop.
```

In the previous v6.10.2, this command would create a module.

Perhaps this change is intended with the new build system, in which case all that is needed is a documentation update.

**Comment by matthiasdiener** [comment]
Yeah, this is due to the new build system. We'll have to remove that part of the manual.

**Comment by fmahebert** [comment]
👍

I should, by later today, have gathered our list of suggested documentation clarifications — my plan was to submit that as a Github issue to facilitate checking things off, discussion, etc. Would it be helpful to close this issue and include this item as a documentation change in my upcoming issue? Let's do whatever is easiest for you!

**Comment by matthiasdiener** [comment]
> 👍
> 
> I should, by later today, have gathered our list of suggested documentation clarifications — my plan was to submit that as a Github issue to facilitate checking things off, discussion, etc. Would it be helpful to close this issue and include this item as a documentation change in my upcoming issue? Let's do whatever is easiest for you!

Great, thank you! I think it is easiest to just reference this issue in the upcoming issue, no need to duplicate this.
