### ISSUE TITLE
LB-related hangs using SpECTRE & charm v6.11.0-beta1

### ISSUE THREAD

**Issue by fmahebert** [UIUC-PPL/charm#3145]
Testing SpECTRE with charm tag v6.11.0-beta1, I find reproducible hangs when I turn on the LB.

I am running some evolution, and varying the number of chare array elements being balanced as well as the number of HPC system nodes I run the executable on. SpECTRE is using AtSync LB.

With `+balancer GreedyLB` and `+balancer RefineLB`, I consistently find the run hangs after a small number of LB calls (I've observed ~3-30). For the same setup, the hang will occur after the same number of LB calls, though this number depends on the number of chare elements and the number of processors. The hang occurs after returning from the LB, while attempting the next series of timesteps.

With `+balancer DummyLB` or without invoking any command-line LB, there is no hang and the evolution completes as expected. I am using the same SpECTRE version in which AtSync LB seemed to work on 6.10.2.

I haven't yet checked other LBs for this behavior.

It's not clear to me if I'm seeing a problem in the LBs themselves, or if the LB AtSync interface has changed and SpECTRE needs updating. If the latter, we haven't yet found an indication of such an interface change within the documentation.

I am happy to try any tests that may be helpful in diagnosing this issue.

**Comment by rbuch** [comment]
Thanks for reporting this, it looks like it might be the same as #3108, which also hangs upon returning from load balancing. It seems likely that this is caused by something inside LB since it's now observable in two different applications at roughly the same point and when an actual load balancer is being used.

**Comment by fmahebert** [comment]
I just tried with RotateLB and got a hang there too...

**Comment by rbuch** [comment]
Do you still get crashes if you run with the `+LBSyncResume` flag? I'm not 100% sure, but I think the issue with #3108 and likely the issue here, too, is that `ResumeFromSync()` is called before all migrations are globally finished, so there's a race and not every element gets resumed (I still haven't proven this to myself definitively, but it looks like it's the case, and adding that flag empirically makes Enzo-E stop hanging). The old LB system doesn't guarantee that migrations are globally finished before `ResumeFromSync()` is called either, but based on the design, I think it's more likely that they would be done before control moves on.

I would test this on SpECTRE myself, but grepping through the source, I couldn't find anywhere `usesAtSync` is used or where `AtSync()` is called. Is there a particular branch or something that I should be looking at?

**Comment by fmahebert** [comment]
Adding this flag (i.e., running with a command like `exec +balancer GreedyLB +LBSyncResume` does not resolve the hangs I am seeing. I haven't tested very thoroughly, but so far 4/4 runs using GreedyLB and RotateLB have hung.

SpECTRE's LB work is on a branch at the moment. We are setting up a more minimal test problem within SpECTRE that avoids coupling in the evolution code, to see if the same LB problems occur there as well - I'll get back to you shortly with the outcome and with a branch (hopefully the simpler branch, but if needed the bigger LB+evolution branch) to look at.

**Comment by rbuch** [comment]
> Adding this flag (i.e., running with a command like `exec +balancer GreedyLB +LBSyncResume` does not resolve the hangs I am seeing. I haven't tested very thoroughly, but so far 4/4 runs using GreedyLB and RotateLB have hung.
> 
> SpECTRE's LB work is on a branch at the moment. We are setting up a more minimal test problem within SpECTRE that avoids coupling in the evolution code, to see if the same LB problems occur there as well - I'll get back to you shortly with the outcome and with a branch (hopefully the simpler branch, but if needed the bigger LB+evolution branch) to look at.

Okay, thanks for the update, I still think it's likely to do with some object registration race (I haven't been able to find an application that doesn't do dynamic insertion that hangs yet). A minimal test problem would be very useful, thanks for putting that together.

**Comment by fmahebert** [comment]
@rbuch We've found a (somewhat more) minimal problem that consistently hangs. This problem mimics a SpECTRE evolution in how it interfaces with Charm++, but replaces the grid elements and physics with a simple chare array that does dummy computations and sends dummy data to neighboring elements. The dummy work is interrupted for a global sync and a call to AtSync, then the dummy work resumes from ResumeFromSync.

I find this problem hangs consistently when I use 8 elements in the chare array and 5+ processors. I've tested this on one node of an HPC system, and also on my 8-core desktop. I haven't seen reliable hangs with fewer than 5 processors, so a "large" machine may be needed to study this. (Note that other configurations hang too, e.g. 4 elements and 5+ processors, though not always as consistently.)

As with the main evolution code, the hang occurs after all elements call ResumeFromSync and the dummy "evolution" begins again. For this problem I see the hang after 4 LB steps. We've checked via printf that all elements are calling ResumeFromSync, and that all elements were migrated as we expect by RotateLB. We've never observed a hang when using DummyLB, or when (in a different executable) using periodic LB.

General instructions for building SpECTRE are [here](https://spectre-code.org/installation.html) — we provide a container with all the dependencies, though not the beta `v6.11.0-beta1` release yet. Please let me know if I can be of any help getting stuff configured for SpECTRE.

Once SpECTRE builds, do the following:
1) checkout from [my fork](https://github.com/fmahebert/spectre) the branch `load_balancing_test_array`; this contains the LB code and the test problem
2) compile the test executable with `make SimpleLoadBalancerTest1DWithSync`
3) run the test executable with `path/to/spectre/build/bin/SimpleLoadBalancerTest1DWithSync +p5 +balancer RotateLB --input-file path/to/spectre/tests/InputFiles/LoadBalancing/SimpleLoadBalancerTest1D.yaml`

The coding for the LB and test problem was largely done by @moxcodes, so I'm pinging him in case he wants to follow along. Also @nilsdeppe.

**Comment by rbuch** [comment]
> @rbuch We've found a (somewhat more) minimal problem that consistently hangs. This problem mimics a SpECTRE evolution in how it interfaces with Charm++, but replaces the grid elements and physics with a simple chare array that does dummy computations and sends dummy data to neighboring elements. The dummy work is interrupted for a global sync and a call to AtSync, then the dummy work resumes from ResumeFromSync.
> 
> I find this problem hangs consistently when I use 8 elements in the chare array and 5+ processors. I've tested this on one node of an HPC system, and also on my 8-core desktop. I haven't seen reliable hangs with fewer than 5 processors, so a "large" machine may be needed to study this. (Note that other configurations hang too, e.g. 4 elements and 5+ processors, though not always as consistently.)
> 
> As with the main evolution code, the hang occurs after all elements call ResumeFromSync and the dummy "evolution" begins again. For this problem I see the hang after 4 LB steps. We've checked via printf that all elements are calling ResumeFromSync, and that all elements were migrated as we expect by RotateLB. We've never observed a hang when using DummyLB, or when (in a different executable) using periodic LB.
> 
> General instructions for building SpECTRE are [here](https://spectre-code.org/installation.html) — we provide a container with all the dependencies, though not the beta `v6.11.0-beta1` release yet. Please let me know if I can be of any help getting stuff configured for SpECTRE.
> 
> Once SpECTRE builds, do the following:
> 1) checkout from [my fork](https://github.com/fmahebert/spectre) the branch `load_balancing_test_array`; this contains the LB code and the test problem
> 2) compile the test executable with `make SimpleLoadBalancerTest1DWithSync`
> 3) run the test executable with `path/to/spectre/build/bin/SimpleLoadBalancerTest1DWithSync +p5 +balancer RotateLB --input-file path/to/spectre/tests/InputFiles/LoadBalancing/SimpleLoadBalancerTest1D.yaml`
> 
> The coding for the LB and test problem was largely done by @moxcodes, so I'm pinging him in case he wants to follow along. Also @nilsdeppe.
> 
> 
> 

Okay, thanks for the update, I'll take a look at this tomorrow. One quick question: does this test case also hang with LBs other than RotateLB as the hang with SpECTRE you described above does?

**Comment by fmahebert** [comment]
I knew I'd forget something!

Changing _only_ the command-line LB argument...
- with `GreedyLB`, the runs often hang after 50ish (30-60) steps... but not always
- with `RefineLB`, I haven't seen a hang in ~10 runs

Changing the command line argument and going to `+p8`...
- with `RotateLB`, hangs after 4 LB steps, as with `+p5`
- with `GreedyLB`, the runs hang in 10ish steps
- with `RefineLB`, still no hangs

I wonder if, for the current configuration of the test array, RefineLB isn't triggering many migrations?

**Comment by rbuch** [comment]
I've pushed a quick fix to the `ronak/fix-migration-hang` branch of Charm++, but I think this has uncovered a more fundamental issue in the location management system regarding custom indices that I'm still investigating. Can you try running with that branch to see if it fixes things in your tests?

**Comment by fmahebert** [comment]
Yes, it looks like that branch does fix the hangs.

I've run the test case with these settings,
- `RotateLB` with `+p5`, no hangs in 4 attempts
- `GreedyLB` with `+p8`, no hangs in 4 attempts
