### ISSUE TITLE
net-verbs-smp Hangs for cloth simulation

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#316]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/316*

---
Xiang reported that net-verbs-smp hangs for her Cloth Simulation code, though mpi-linux and net-linux does not.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-06 19:56:57*

---
Retitle more descriptively.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 02:47:27*

---
Does the cloth simulation code hang for net-linux-x86_64-verbs? What about net-linux-x86_64-smp? And, as suggested in chat earlier today, does it ever hang with randomized queuing under net-linux-x86_64?

Those tests are things Xiang can run a bunch of times each, to see if there's a moderate-frequency occurrence in simpler machine layers, or if the application code is flawed.

**Comment by nikhil-jain** [comment]
*Original date: 2013-11-08 02:50:39*

---
Does the cloth simulation code hang for net-linux-x86_64-verbs? No 
What about net-linux-x86_64-smp? No
And, as suggested in chat earlier today, does it ever hang with randomized queuing under net-linux-x86_64? No

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 03:19:31*

---
This has come up in the past wrt to cloth simulation, and I think I know the answer, but what is the memory footprint of this code, relative to the nodes it's running on?

How many nodes, and what ppn? Known thresholds for either to reproduce?

**Comment by nikhil-jain** [comment]
*Original date: 2013-11-08 08:10:05*

---
Finally there is some progress :)

Seems like adding this fork protection call - ibv_fork_init in the beginning solves the problem. I have not checked it in since the connection is unclear - we don't fork as far as I know.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 17:03:13*

---
This is an SMP build. From the perspective of IB Verbs, spawning a separate thread (workers, comm) may be effectively 'forking'. So, I guess that's not too surprising. If we wanted to rearrange things so that all ibverbs calls happen on the comm thread, and ensure that the first thread at startup becomes the comm thread, this may not be necessary. If there's no performance detriment to `ibv_fork_init`, then we should just go with that.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 17:04:48*

---
Also note that this change may need to propagate to LRTS `verbs-*-smp` as well.

**Comment by nikhil-jain** [comment]
*Original date: 2013-11-09 20:45:51*

---
Added fork protection to the verbs code.
