### ISSUE TITLE
PAMI LRTS SMP with L2Atomic Queue crashed

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#32]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/32*

---
Extended LRTS to use L2AtomicQueue to replace PCQueue in SMP for PAMI. However, it crashed in megatest

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-02-08 17:10:21*

---
The bug is that LrtsQueueCreate() did not return the queue pointer.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-03 06:52:54*

---
Detailing the bug - The way queues were created using a common function (LrtsQueueCreate) resulted in a race condition. A common static variable controlled the position of queue in an array, which in presence of multiple threads results in buggy code.
