### ISSUE TITLE
Manual doesn't actually show parameter marshalling for non-primitive types

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#323]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/323*

---
One of the key conveniences of parameter marshalling is that *any* type for which pup is defined can be passed as an argument to an entry method, rather than just primitive types (e.g. int, double), system-defined types (e.g. CProxy_Foo) and arrays of the same. However, I notice that this isn't clear in the manual at all, as evidenced by Nicholas Bock's recent message. Please elaborate on this ability, with explicit text and some example code. This ability should be clear in both the sections on Entry Methods (currently 3.1) and on PUP (chapter 6).

Deadline set for November 15 so that anyone reading during SC will see the changes.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-15 21:53:39*

---
You've been working on improving tutorial and documentation material. This seems like a good target for that goal.

**Comment by rbuch** [comment]
*Original date: 2015-01-16 23:48:35*

---
3.1.0.1 Marshalling User-Defined Structures and Classes and 6.4 Marshalling User Defined Data Types via PUP already cover this explicitly.  I've cleaned up a bit of the manual and example code and added an explicit example to the manual (http://charm.cs.uiuc.edu/gerrit/#/c/459/).

**Comment by PhilMiller** [comment]
*Original date: 2015-01-17 22:07:15*

---
I've merged 459, but I still think this could be more straightforward. I think code from HeapPUP or something like it should be displayed and explained in the entry methods discussion in section I-3.
