### ISSUE TITLE
sdag case statement causing message misdelivery

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#325]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/325*

---
Akhil informed me of this bug, but did not add it to redmine.

**Comment by lifflander** [comment]
*Original date: 2013-11-07 23:43:19*

---
Bug is that the chain the calls following a when clause inside a case statement is called *before* the speculation index is cleared.

**Comment by lifflander** [comment]
*Original date: 2013-11-07 23:44:54*

---
see commit 26540f705da6ab2286d9d0af03a6989928ae4960

**Comment by lifflander** [comment]
*Original date: 2013-11-07 23:45:16*

---
confirmed fixed in the small reproducible case, waiting for confirmation in AMR

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2013-11-08 21:03:28*

---
this  bug fix solves the problem in AMR

**Comment by lifflander** [comment]
*Original date: 2013-11-08 21:15:44*

---
new extensive test case for the "case" construct will be added to tests
