### ISSUE TITLE
Charm++ documentation fails to build due to insufficient checks in navemenuGenerator.py

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#326]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/326*

---
The script does not properly check for the return value of soup.find(). This
leads to a build failure in the documentation. I suspect that the problem is
deeper (why does soup.find() return None?) but for now this patch fixes the
documentation build problem.

[0001-Fix-navemenuGenerator.py.patch](https://github.com/UIUC-PPL/charm/files/3536408/0001-Fix-navemenuGenerator.py.patch.txt)

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:32:51*

---
Ronak, please work in integrating these changes.

**Comment by rbuch** [comment]
*Original date: 2015-02-09 22:22:24*

---
Unable to reproduce failure, reasoning given at: http://charm.cs.uiuc.edu/gerrit/#/c/46/

(Essentially, if this script fails, then make probably should fail, too.)
