### ISSUE TITLE
Message queue randomization for message-order debugging

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#327]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/327*

---
Ram implemented support for a randomized message queue in branch `ramv/randomized-msgq`, and the associated issues that arose were addressed in #259. Integrate this code, and document it.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 17:29:13*

---
Merge is clean, retested on net-darwin-x86_64 both with and without the randomized queue enabled (`--enable-randomized-msgq`), and `make test` passes. Pushing to mainline.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 17:30:32*

---
Documentation on this feature still needs to be added to appropriate parts of the manual. Reassigning to Harshitha as one of the scheduler module owners.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 19:12:56*

---
Jim notes
> I see that you checked this in, but when I try it I get these messages:
> 
> Configuring support for message priorities of arbitrary size (bitvectors)
> Ignoring --enable-randomized-msg.
> A randomized message queue is only available when --with-prio-type != bitvec.
> Specify prio-type to be a data type long enough to hold the msg priorities in your application
> for eg: --with-prio-type=int (or short / long etc).
> 
> This should be a fatal error because if somebody uses the --enable-randomized-msg option they definitely want it.
I think he's right, that configure should fail if a non-bitvector priority type isn't specified.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-08 19:55:51*

---
Some follow-up on this pushed to branch feature-327-followup. I've tested that these additional changes work as intended on net-darwin-x86_64, in the various configurations of with/without randomization and with/without bitvec priorities. Jonathan, please review and merge.

**Comment by lifflander** [comment]
*Original date: 2013-11-09 00:29:19*

---
Review complete, looks good, merged into charm.

**Comment by lifflander** [comment]
*Original date: 2013-11-09 00:32:12*

---
Has the documentation been added? I do not see any evidence of it..

**Comment by PhilMiller** [comment]
*Original date: 2013-11-09 17:26:43*

---
Documentation has been added in a new 'Debugging' appendix to the manual. However, it doesn't render properly in the generated HTML: http://charm.cs.illinois.edu/manuals/html/charm++/F.html
The compile-time flags need to be set as monospace, so that double dashes don't get collapsed into em-dashes.

**Comment by harshithamenon** [comment]
*Original date: 2013-11-09 18:51:45*

---
Thanks Phil for noticing this. I have checkedin the fix. I will keep an eye for it when the page gets updated.
