### ISSUE TITLE
Make markupSanitizer.py support python 3.1 and 3.2

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#328]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/328*

---
The script only supports <python-3 because of how uni-code literals are treated in python-3.{1,2}. In python-2, a unicode string has to be prefixed with 'u', while this notation was dropped in python-3.{1,2}. I have added a check to the script so that it runs now with python-2.7 and python-3.{1,2,3}.

[0002-Make-markupSanitizer.py-support-python-3.1-and-3.2.patch](https://github.com/UIUC-PPL/charm/files/3536410/0002-Make-markupSanitizer.py-support-python-3.1-and-3.2.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2015-01-17 21:43:59*

---
A simplified version that doesn't adjust the overall code structure is implemented here: <http://charm.cs.uiuc.edu/gerrit/460>. If we find a need to import the sanitizer code in some other module, then we can do the `main()` conversion as well.

Sorry for the absurdly long delay on applying such a simple fix, and thanks for providing it.
