### ISSUE TITLE
Feature: Implement Queue to manage host local process to process short messages (CMA)

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#3284]
Short messages, even the metadata associated with zero copy operations, currently go via the network interface.

For non-smp mode, this results in relatively high overhead for small messages.  The existing CMA (or POSIX SHMEM) infrastructure could be used as the communication mode for all small within node messages as long as a each PE has queue to manage the multiple producer single consumer operations.

**Comment by Wingpad** [comment]
Do you anticipate this being an "opt-in" feature, or something that the runtime implicitly handles for the user? If it will be an "opt-in" feature, can TRAM/other aggregators utilize these queues? You mentioned non-SMP specifically, but would these benefits translate to multiple processes within a physical node in SMP scenarios as well?
