### ISSUE TITLE
Jenkins for Autobuild

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#33]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/33*

---
It would be very useful to have Jenkins integrated in with Autobuild.

1. Firing off automatic tests on a limited number of platforms per git push event would allow us to catch errors early.
1. The ability to schedule tests at a finer level of granularity would be helpful
    - Periodic (perhaps weekly) execution of SU consuming full tests on relevant platforms
    - Periodic execution of performance benchmarks
    - Periodic execution of flagship application tests
1. The definition of sets of tests to be run at various frequencies
    - Autobuild's current all or nothing approach discourages aggressive expansion of the test framework
    - Various parameter choices, such as varying PPN and the many command line options, all go untested

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:23:04*

---
I fail to understand delay in completion of this task; increasing the priority. Please finish asap.

**Comment by PhilMiller** [comment]
*Original date: 2014-02-17 17:02:34*

---
I just realized a challenge in our matrix build setup. We've lost the ability to specify per-configuration arguments and options. That covers the failure of several of the SMP builds and sort of ICC.

**Comment by mprobson** [comment]
*Original date: 2015-01-22 21:03:04*

---
We've had automatic testing on push for a while now but we don't have the matrix build of all of our configurations working. IIRC, a subtask for the matrix has been assigned to Sol.

**Comment by matthiasdiener** [comment]
Closing this, we'll probably go with GitHub actions.
