### ISSUE TITLE
Build failure with CMake 3.20.0

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#3317]
When using CMake 3.20.0, the build fails with the following (tested with 7f455786f and `./build charm++ netlrts-linux-x86_64 smp  --with-production -j4`, but it should fail in general):
```
Fatal Error by charmc in directory <...>/charm/netlrts-linux-x86_64-smp-clang-11
   CMakeFiles/ldb-rand.dir/src/conv-ldb/cldb.rand.C.o: file not recognized: File truncated
charmc exiting...
Fatal Error by charmc in directory <...>/charm/netlrts-linux-x86_64-smp-clang-11
   CMakeFiles/conv-static.dir/src/conv-core/conv-static.c.o: file not recognized: File truncated
charmc exiting...
CMakeFiles/ldb-rand.dir/build.make:75: recipe for target 'CMakeFiles/ldb-rand.dir/src/conv-ldb/cldb.rand.C.o' failed
make[2]: *** [CMakeFiles/ldb-rand.dir/src/conv-ldb/cldb.rand.C.o] Error 1
CMakeFiles/Makefile2:586: recipe for target 'CMakeFiles/ldb-rand.dir/all' failed
make[1]: *** [CMakeFiles/ldb-rand.dir/all] Error 2
```
The build works fine with CMake 3.19.7.

**Comment by matthiasdiener** [comment]
This is weird, cmake < 3.4.0 is not supported at all and should cause an error to appear (or automatically run ./buildold instead), see e.g. 

https://github.com/UIUC-PPL/charm/blob/7f455786f6a3b8e9aac4e360e43f2c61f34d5797/CMakeLists.txt#L13

and 

https://github.com/UIUC-PPL/charm/blob/7f455786f6a3b8e9aac4e360e43f2c61f34d5797/buildcmake#L27-L37


Can you paste the output of `cmake --version`

**Comment by rbuch** [comment]
> This is weird, cmake < 3.4.0 is not supported at all and should cause an error to appear (or automatically run ./buildold instead), see e.g.
> 
> https://github.com/UIUC-PPL/charm/blob/7f455786f6a3b8e9aac4e360e43f2c61f34d5797/CMakeLists.txt#L13
> 
> and
> 
> https://github.com/UIUC-PPL/charm/blob/7f455786f6a3b8e9aac4e360e43f2c61f34d5797/buildcmake#L27-L37
> 
> Can you paste the output of `cmake --version` ?

Ah, yes, my mistake, I mistyped the version number. I was testing with 3.20.0, not 3.2.0.

**Comment by rbuch** [comment]
This is affecting CI now that https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210330.1 has introduced CMake 3.20.0 to the build images.

**Comment by matthiasdiener** [comment]
3.20.0 uses `-MD` to generate dependency information, which `charmc` did not support correctly (#3318).

**Comment by BJWiley233** [comment]
I also get this charmc extension error with version 3.22.1 and -MD compiling with gcc11 on bigSur 11.6.
