### ISSUE TITLE
Intranode optimizations for TRAM

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#334]
*Original author: Lukasz Wesolowski*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/334*

---
A new routing scheme to improve intranode aggregation for TRAM. 

Preliminary implementation is done. Changes to broadcast and staged completion components are still required.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-01-16 22:15:19*

---
I made the necessary changes to the staged completion scheme. I am delaying changes to broadcast scheme until a later date, due to lack of active use cases. Trying to use TRAM broadcast with the new scheme will lead to a CkAbort getting called.

Submitted for review in gerrit. 

http://charm.cs.uiuc.edu/gerrit/#/c/42/

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-01-21 00:46:06*

---
Merged in.

**Comment by PhilMiller** [comment]
*Original date: 2014-06-19 21:20:29*

---
Re-targeting so that it will be more obvious in release notes.
