### ISSUE TITLE
Incompatible return type for C-linkage function LDAddLocalBarrierReceiver

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#335]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/335*

---
c:\cygwin\home\jcphill\charm-6.6\mpi-win64\include\lbdb.h(356) : warning
C4190: 'LDAddLocalBarrierClient' has C-linkage specified, but returns UDT
'LDBarrierClient' which is incompatible with C
         c:\cygwin\home\jcphill\charm-6.6\mpi-win64\include\lbdb.h(340) :
see declaration of 'LDBarrierClient'
c:\cygwin\home\jcphill\charm-6.6\mpi-win64\include\lbdb.h(359) : warning
C4190: 'LDAddLocalBarrierReceiver' has C-linkage specified, but returns
UDT 'LDBarrierReceiver' which is incompatible with C
         c:\cygwin\home\jcphill\charm-6.6\mpi-win64\include\lbdb.h(348) :
see declaration of 'LDBarrierReceiver'

**Comment by PhilMiller** [comment]
*Original date: 2014-01-24 17:53:23*

---
I just moved these out of 'extern "C"' since they can never be called in that setting, and won't be used by any C code anyway (they're internal API).
