### ISSUE TITLE
Make topology physical node-aware when detailed info is not available

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#337]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/337*

---
TopoManager should be physical code aware atleast for cases where detailed topology info is not available.

**Comment by juanjgalvez** [comment]
*Original date: 2017-02-09 16:26:36*

---
Fix here:
~~https://charm.cs.illinois.edu/gerrit/#/c/2227/~~ https://github.com/UIUC-PPL/charm/commit/fa88d7f97cc947105af60fdb7e3dd60f1c65b705
