### ISSUE TITLE
Charmc doesn't handle spaces in string macro values passed to -D correctly

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#3371]
If you pass a macro value via "-D" to charmc (or ampicc) it doesn't handle spaces in a string value correctly:

```
$ ampicxx -g -DMYMACRO="test macro" test.cpp
g++: error: macro: No such file or directory
Fatal Error by charmc:
   Command g++ -DCMK_GFORTRAN -DCMK_GFORTRAN -D__CHARMC__=1 -DMYMACRO=test -g macro -pthread -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -ftls-model=initial-exec -std=gnu++11 -c test.cpp -o test.o returned error code 1
charmc exiting...
```

**Comment by stwhite91** [comment]
This is actually two issues:
1. String values of macros passed to -D don't work.
2. String values of macros passed -D with spaces in them don't work.

**Comment by matthiasdiener** [comment]
This isn't really AMPI-related right? `charmc` seems to have the same bug.

**Comment by stwhite91** [comment]
Correct, it's not really AMPI-related
