### ISSUE TITLE
Double hyphen not rendered properly in the manual

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#339]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/339*

---
There are many instances in the manual where double hyphen (--) is not rendered correctly. Some examples are --with-production, --enable-tracing, --enable-randomized-msg etc.

**Comment by lifflander** [comment]
*Original date: 2013-11-14 21:52:47*

---
merged into charm
