### ISSUE TITLE
new test case for the "case" SDAG statement

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#340]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/340*

---
used to find bug #325

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:28:55*

---
Jonathan - I believe you are done with this task?

**Comment by lifflander** [comment]
*Original date: 2014-01-03 05:29:45*

---
Yes
