### ISSUE TITLE
Test Applications using 6.6.0

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#341]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/341*

---
Our applications should be tested using 6.6.0.  Testing should include both correctness testing and performance testing against 6.5.0.  The latter may be tricky in some cases due to compatibility issues, please document those cases as they arise.

This is the parent task placeholder for the application specific tests.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-20 23:31:56*

---
I've re-opened all of the individual application-test issues, so that we can get clear affirmation that all is well after the performance regression fixes have been integrated.
