### ISSUE TITLE
Tracking the Currently Executing Chare

### ISSUE THREAD

**Issue by jszaday** [UIUC-PPL/charm#3421]
One can imagine various situations in which (local) access to the chare whose entry method is currently executing may be desirable. For example, lightweight control objects (LCOs, e.g., mailboxes, futures, channels, etc.) may need access to features of their execution context (i.e., a chare) to interact with other LCOs, e.g., communicating data. 

It is cumbersome for users to maintain access to this information. Pseudo-global variables must be updated at the start of every entry method and after threads resume-from-suspend. Passing around chare proxies or pointers can incur a great deal of clunkiness and replication of information, especially when large swaths of objects are created in deeply-nested (function) calls. Additionally, pointers are not resilient against migrations.

The Charm++ RTS maintains this information (in some capacity) for load-balancing and tracing. That said, these mechanisms are disjoint and do not currently expose all necessary information (i.e., array IDs). These mechanisms may not be used with node/groups and singleton chares as well. This motivates a new solution -- e.g., `CkAccessChare()`.

Each of the code paths within `ck.C::_processHandler` may need to be updated to support this feature. While some of its code paths update `Ckpv` variables like `currentGroup` and `currentChareIdx`, they may not be enabled in all builds and their (general) nonuniformity renders them unusable.

Note, a general-purpose solution may be made more feasible by increasing the adoption of 64-bit IDs.

**Comment by jszaday** [comment]
Note, one can access the current `CkLocRec` using the following procedure:

    auto* db  = LBManager::Object()->getLBDB();
    auto* obj = db->LbObj(db->RunningObj());
    auto* chare = static_cast<CkLocRec*>(obj->getLocalUserData());

**Comment by epmikida** [comment]
Yup, that should be an effective work around for the time being. Couple thoughts:

The currently running object being stored by the LB is probably just cause that was the first and so far only thing that needed it. Should eventually be moved somewhere more general and then both your work AND the LB can reference it.

Some of this stuff will likely be invalidated by planned future CkLocMgr work, ie I'm not sure if CkLocRec will exist in the future. At least not in it's current form. It's current form is largely unnecessary and only exists for legacy reasons.

Eventually, a solution that gets current chare regardless of whether it is an array, singleton, group, etc would be nice. Possibly just storing the current chare 64bit ID. Would likely be useful for this, LB, and tracing.

**Comment by rbuch** [comment]
> Yup, that should be an effective work around for the time being. Couple thoughts:
> 
> The currently running object being stored by the LB is probably just cause that was the first and so far only thing that needed it. Should eventually be moved somewhere more general and then both your work AND the LB can reference it.
> 
> Some of this stuff will likely be invalidated by planned future CkLocMgr work, ie I'm not sure if CkLocRec will exist in the future. At least not in it's current form. It's current form is largely unnecessary and only exists for legacy reasons.
> 
> Eventually, a solution that gets current chare regardless of whether it is an array, singleton, group, etc would be nice. Possibly just storing the current chare 64bit ID. Would likely be useful for this, LB, and tracing.

To corroborate, I agree with everything here, I too suspect the only reason LB stores the current object is that it's really the only thing that needs it (tracing kinda has that information, but it doesn't really "know" what's currently executing, it really just stores a mostly opaque ledger of what the RTS says is going on). I concur that it's a thing that we should promote to a general RTS service.
