### ISSUE TITLE
Incorrect CMake warnings

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#3423]
With the 7.0.0 RC I get the following warnings when building on my local Ubuntu 20.10 machine:

```
configure: WARNING: Your make does not allow comments in target code.
Using this make may cause problems when building programs.
You should consider using gnumake instead.
configure: WARNING: File locks may not work with NFS.  See the Installation and
users manual for instructions on testing and if necessary fixing this
```

When I run `make --version` I get `GNU Make 4.3`, and I'm building on my local SSD. Something seems to be going wrong with some check.

**Comment by matthiasdiener** [comment]
I think this message is printed by romio's configure script, over which we don't have too much control. Are you building with AMPI support?

**Comment by nilsdeppe** [comment]
Ah okay. I did `./build LIBS multicore-linux-x86_64 -j4`, so I'm not sure if AMPI is built with that or not, sorry...

**Comment by matthiasdiener** [comment]
> Ah okay. I did `./build LIBS multicore-linux-x86_64 -j4`, so I'm not sure if AMPI is built with that or not, sorry...

Yes, LIBS includes AMPI.
