### ISSUE TITLE
buildold fails on machines without /lib/cpp

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#3441]
As reported by @trquinn:

> v7.0.0-rc1 doesn't compile on a machine without /lib/cpp.  hwloc seems to cause the problem.
> v6.11.0-beta1 does compile.
> The final error is:
> ```
> configure:13996: error: in `/home/trq/src/charm/mpi-linux-x86_64-smp-mpicxx/tmp/hwloc':
> configure:13998: error: C++ preprocessor "/lib/cpp" fails sanity check
> See `config.log' for more details
> ```
> Here is the bad commit according to git bisect: b55cc8ca7a3295b2c474c9a3e6213f5a42b95a09

It would be useful to know what `tmp/hwloc/config.log` says. If buildold fails, it should print the contents of this file to stdout. It would be useful to know the exact command and input is used for the test that fails, as well as for the test preceding it for the C preprocessor as opposed to C++. The environment variables `$CPP`, `$CPPFLAGS`, and `$CXXCPP` would also be good to know.

**Comment by trquinn** [comment]
[config.log](https://github.com/UIUC-PPL/charm/files/6997067/config.log)
The config.log from tmp/hwloc is attached.  The build command was `./build ChaNGa mpi-linux-x86_64 smp -j8 -O2 mpicxx --force`.  CPP, CPPFLAGS, CXXFLAGS are not set.
