### ISSUE TITLE
Test AMR using 6.6.0

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#345]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/345*

---
AMR should be tested using 6.6.0. Testing should include both correctness testing and performance testing against 6.5.0. The latter may be tricky in some cases due to compatibility issues, please document those cases as they arise.

**Comment by ericjbohm** [comment]
*Original date: 2013-11-18 16:46:57*

---
Any progress on this?

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 21:02:30*

---
With debug builds of `net-darwin-x86_64` on my Mac, I'm seeing a few percent slowdown from 6.5.1 to current mainline. Will try with a production build.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 21:10:22*

---
Production builds show times about 2-5% slower, too. This is branch `hpcc-2012` of `users/alanger/amr`. Runtime is built `--with-production` and no other options, AMR is build with `-O3`. I'm going to quiet some excessive prints in the code that may be adding more noise than we'd like, but the difference-of-means between runs on the older and newer builds is pretty stable.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 21:16:27*

---
With per-step prints turned off, the timings are more stable, and the difference is very clear. The newer code is at least 5% slower, and the distributions of run times between the new versions don't overlap at all.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 21:21:16*

---
I just checked that the compilation flags being passed to the backend compiler are identical from 6.5.1 to mainline, so it's not just an optimization fault.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-30 19:10:12*

---
OK, on my Mac with 10.9 and Clang 3.3, I'm seeing about a 0.3-0.5% slowdown from 6.5.1 to current HEAD on a single PE. This is probably more in the realm of 'acceptable', though it's still bothersome.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-30 19:47:42*

---
Core group consensus (Eric & Nikhil concurring) is that this difference is small enough to be sub-critical.
