### ISSUE TITLE
pup_stl compiler error with `std::map` and custom comparator

### ISSUE THREAD

**Issue by moxcodes** [UIUC-PPL/charm#3457]
I had trouble using the utilities in `pup_stl.h` to define a pup function for a class that contained a `std::map` with a custom comparator.
The compiler error seemed to indicate that the internals were attempting to `resize` the container, but the STL does not define a `reserve` function for `std::map`s.

**Comment by evan-charmworks** [comment]
Thanks for the report. Does #3458 resolve the issue?
