### ISSUE TITLE
Test NAMD using 6.6.0

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#346]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/346*

---
NAMD should be tested using 6.6.0. Testing should include both correctness testing and performance testing against 6.5.0. The latter may be tricky in some cases due to compatibility issues, please document those cases as they arise.

Jim is actually doing pretty exhaustive testing, keep in contact with him and do a little basic coverage on PAMI and/or GNI.

**Comment by ericjbohm** [comment]
*Original date: 2013-11-18 16:47:28*

---
Any progress on this?

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-11-18 22:36:00*

---
Working on it.  JYC scheduler is paused. Waiting for it to be up.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-11-19 01:52:52*

---
I test NAMD 6.5 non-smp, smp, 6.6 nonsmp, smp on JYC for Apoa1, from 256 cores, to 1024 cores. 

Performance for SMP is better than non-smp. Performance for 6.5 and 6.6 is almost same  (difference is within 4%).

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-11-19 02:30:36*

---
On Vesta,  I test charm nonsmp, smp, smp async for Charm 6.6.  
Performance scales well from 2K to 8K cores.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-19 21:10:00*

---
Performance is within 4% between 6.5 and 6.6, but is one consistently better than the other? If the newer release is always slower, as we see with AMR, then we may want to investigate that in more depth.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-11-20 23:27:15*

---
On JYC, on 1K  and 256 cores, 6.6 is generally faster than 6.5 by 5%. 
Only on 512 cores,  6.6 non-smp is slower than 6.5 nonsmp by almost 20%. 

The command is  

aprun -n 512 -N 32  /u/staff/yanhuas/git/NAMD/bin/namd2.6.5  ../../apoa1/apoa1.2X.namd +pemap 0-31 +nodesize 32 >& o.512pes.6.5

aprun -n 512 -N 32  /u/staff/yanhuas/git/NAMD/bin/namd2.6.6  ../../apoa1/apoa1.2X.namd +pemap 0-31 +nodesize 32 >& o.512pes.6.6 

On Vesta BGQ, the 512 nodes running for async, it is running very slow.  However, on 128 nodes, 64 nodes it is normal

runjob -p 4 -n 2048 --block $COBALT_PARTNAME --verbose=INFO --envs BG_SHAREDMEMSIZE=32MB --envs PAMID_VERBOSE=1  : /home/jessie/NAMD/nightly/namd2/BlueGeneQ-xlC/namd2.6.6.smp.async /home/jessie/NAMD/data/apoa1-opt/apoa1.namd +ppn 12 > 512Node/o.N512.p16.6.6.smp.async

**Comment by PhilMiller** [comment]
*Original date: 2014-02-12 22:35:10*

---
Eric & Yanhua report that all is well.
