### ISSUE TITLE
CmiMemoryUsage() reports incorrect value on Blue Gene/Q

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#347]
*Original author: Lukasz Wesolowski*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/347*

---
The current implementation of CmiMemoryUsage() on Blue Gene/Q reports incorrect value when more than 2 GB of memory is used. 

I added a working function, and verified that it works on Vesta. Someone may want to test it on Vulcan, and maybe Mira.

**Comment by lifflander** [comment]
*Original date: 2013-11-15 01:37:24*

---
see commit: b283a8032c200173f7f2631bf5b4a26038ba1288, merged to charm
