### ISSUE TITLE
Release notes for 6.5.0

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#35]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/35*

---
Edit the list of note-worthy changes from the wiki into a coherent set of release notes.
https://wiki.engr.illinois.edu/display/ppl/Charm+release

**Comment by PhilMiller** [comment]
*Original date: 2013-02-19 02:05:35*

---
Eric, please check that I haven't misrepresented anything, or left out some entry that should have been in the wiki but wasn't. If all is well, please close.

**Comment by ericjbohm** [comment]
*Original date: 2013-02-19 19:39:17*

---
Release notes look fine to me.
