### ISSUE TITLE
Link failure for -lpami for Charm 6.5

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#350]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/350*

---
The reshuffling/renaming of the libpami library in the distribution on BG/Q means that you cannot build old (6.5) charm there without tinkering with conv-mach.sh to switch to -L$BGQ_INSTALL/comm/lib -lpami-gcc. 

Its sort of an open question as to whether this matters at this point as this bug is easily solved by upgrading to 6.6.  Doing a bugfix release for 6.5 for this issue may not be a very good use of our time.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:27:37*

---
With 6.6 release being perennially delayed, I suggest back porting the conv-mach changes. Not much of a work. Any opinions? In absence, I will do the back porting.

**Comment by PhilMiller** [comment]
*Original date: 2014-09-03 03:22:32*

---
No longer relevant, since we've actually done the 6.6 release.
