### ISSUE TITLE
CkIO::CkGetFileStripeSize() returns 0 on NASA Pleiades

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#3559]
This is with Charm++ v7.0.0 and ChaNGa running on Red Hat Enterprise Linux Server release 7.9 on the NASA Pleiades machine.  I'm not sure how to get the lustre version.

When opening a new file, the llapi_file_get_stripe() call at fs_parameters.c, line 42 returns "0" but lump->llm_stripe_size is set to 0.  This causes floating point errors later since the stripe size is divided into the number of bytes to be written.

A reasonable workaround would be to test for this along with a bad return code at line 46 so that a default stripe size gets set.

Also: there is a memory leak since the "lump" pointer never gets free()d

**Comment by rbuch** [comment]
Should be fixed in #3560.
