### ISSUE TITLE
No tmp/libs directory in build folder

### ISSUE THREAD

**Issue by BJWiley233** [UIUC-PPL/charm#3566]
This seems trivial but all the [documentation](https://charm.readthedocs.io/en/latest/libraries/manual.html?highlight=install#multi-phase-shared-arrays-library) says after building, "cd to your <build>/tmp/libs ..." to make the libraries.  Every time I build with `./build LIBS mpi-darwin-x86_64` I ONLY see a `libs` directory in `<build>/src/libs` I don't have a libs directory in the tmp directory so I am confused.

The only folders I have under  <build>/tmp are ampi, cklibs and pose which barely have anything in them:

```
% ls -1 -d charm/mpi-darwin-x86_64-gcc-gfortran/tmp/*/
charm/mpi-darwin-x86_64-gcc-gfortran/tmp/ampi/
charm/mpi-darwin-x86_64-gcc-gfortran/tmp/cklibs/
charm/mpi-darwin-x86_64-gcc-gfortran/tmp/pose/
```

**Comment by jszaday** [comment]
Thank you for bringing this to our attention. These instructions have become out of date with the switchover to the `cmake`-based build system. I will update them.

**Comment by BJWiley233** [comment]
that's okay, i see they get build as static `libmodule<my_lib>.a` under `lib` in build folder. That may be the key point to make in doc.  I am assuming these go to the prefix directory `/usr/local/lib` when using `make install`.    Were all moving to cmake now before it gets too crazy :)
