### ISSUE TITLE
v6.6.0-rc1 fails to build with --with-numa option

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#357]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/357*

---
When building with

`./build charm++ net-linux-amd64 --build-shared --enable-charmdebug --enable-tracing --enable-tracing-commthread --with-numa -j1 -O0 -g -pipe`

The build fails at:
```
../bin/charmc  -O0 -g -pipe -build-shared -c -I. memoryaffinity.c
memoryaffinity.c: In function ‘CmiInitMemAffinity’:
memoryaffinity.c:205:9: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
cc1: some warnings being treated as errors
Fatal Error by charmc in directory /var/tmp/portage/sys-cluster/charm-6.6.0_rc1/work/charm-6.6.0_rc1/net-linux-amd64/tmp
   Command x86_64-pc-linux-gnu-gcc -Werror=declaration-after-statement -m64 -DCMK_GFORTRAN -I../bin/../include -D__CHARMC__=1 -I. -O0 -g -pipe -fno-stack-protector -fPIC -c memoryaffinity.c -o memoryaffinity.o returned error code 1
charmc exiting...
gmake: *** [memoryaffinity.o] Error 1
-------------------------------------------------
Charm++ NOT BUILT. Either cd into net-linux-amd64/tmp and try
to resolve the problems yourself, visit
http://charm.cs.illinois.edu/
for more information. Otherwise, email the developers at charm`cs.illinois.edu
```
Without the --with-numa option, it works.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-19 23:28:52*

---
Fix at http://charm.cs.uiuc.edu/gerrit/#/c/11/ awaiting review.

**Comment by lifflander** [comment]
*Original date: 2013-11-19 23:32:36*

---
Reviewed, looks good. Merged into charm.

**Comment by pplimport** [comment]
*Original author: Nicolas Bock (@nicolasbock)*
*Original date: 2013-11-20 04:45:34*

---
Thanks! That was fast! The patch works for me as well.
