### ISSUE TITLE
charmc does not make ASM object but call to plain Apple clang call does

### ISSUE THREAD

**Issue by BJWiley233** [UIUC-PPL/charm#3570]
Not sure what I am missing with the unix assembly boost module.  Only running without charmc will actually make the ASM object.

Meaning this doesn't output an `-o *.S.o` object at all: 
```
/Users/brian/tools/NAMD_Git-2022-01-26_Source/charm/build_charm/bin/charmc /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -DAMPI_ERRHANDLER_RETURN=0  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -g -o CMakeFiles/boost-context.dir/ontop_x86_64_sysv_macho_gas.S.o -c /Users/brian/tools/NAMD_Git-2022-01-26_Source/charm/src/util/boost-context/ontop_x86_64_sysv_macho_gas.S
```
but this does:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc -DAMPI_ERRHANDLER_RETURN=0  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -g -o CMakeFiles/boost-context.dir/ontop_x86_64_sysv_macho_gas.S.o -c /Users/brian/tools/NAMD_Git-2022-01-26_Source/charm/src/util/boost-context/ontop_x86_64_sysv_macho_gas.S
```

**Comment by BJWiley233** [comment]
This only occurred cloning the most recent master repo.  I downloaded v7.0.0 and it built the ASM objects fine no problem from the build command.

**Comment by jszaday** [comment]
I believe that PR #3475 changed the default assumptions of `charmc`, and future versions (after v7.0.0) will now require the explicit addition of the `-c` flag. Please let us know if that resolves this problem.

**Comment by BJWiley233** [comment]
Sure I will try it.  I am going to try a few namd tutorials probably before I get to it since I got it compiled.  Thanks!
