### ISSUE TITLE
While building charm with AVX512 flags facing error

### ISSUE THREAD

**Issue by ajithvallabai** [UIUC-PPL/charm#3576]
I am trying to build charm 6.10.2 with AVX512 flag` ./build charm++ multicore-linux-x86_64 iccstatic --with-production "-O3 -ip -xCORE-AVX512"` 
Facing below error 

![snap_namd_AVX512](https://user-images.githubusercontent.com/8075112/156302298-8c7974c6-efa7-496f-9e42-9286c08ab888.JPG)

below attachement is config.log file
[config.zip](https://github.com/UIUC-PPL/charm/files/8166901/config.zip)

kindly give us a solution.

Even though this [fix ](https://github.com/UIUC-PPL/charm/issues/2503) was done in 6.10.2 version it is still occurring.

**Comment by matthiasdiener** [comment]
It is misdetecting the Python version, which is why the build fails. It is the same issue as https://github.com/UIUC-PPL/charm/issues/3546.

Could you try building Charm++ 7.0.0 with the same options?

**Comment by ajithvallabai** [comment]
python - 3.9.7
bash - 5.0.17(1)-release
awk - GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)

Above is my version details.
1. But the same builds fine for  charm 6.10.2 with AVX512 flag `./build charm++ multicore-linux-x86_64 iccstatic --with-production "-O3 -ip "` . is it expected ?

2. Yes 7.0.0 builds after running "make pgm" , pgm file is not present after building successfully Is it expected ?

![snap_erors](https://user-images.githubusercontent.com/8075112/156813430-f95586df-d56d-4f6b-99e4-ac3f7946a90d.JPG)


4. icpc: warning #10237: -lcilkrts linked in dynamically, static library not available . i get this warning , do u know how to get rid of it.

(below question is not related but i am just asking incase if you know.)
5. I get below error if use charm-AVX512 for compiling namd. I followed [this](https://github.com/ubccr/akrr/blob/c1ed244aa2b6ad09695d55700911ed4aed45c809/docker/namd/README.md) post
![snap_tims](https://user-images.githubusercontent.com/8075112/156818957-c83026f6-e98f-4fc7-ba39-aee3fffb8889.JPG)

**Comment by ajithvallabai** [comment]
the point 5 is also thrown from charm lib only

**Comment by evan-charmworks** [comment]
One thing worth mentioning is that the parameters at the end of the build command should not be enclosed in quotes. For example, `./build charm++ multicore-linux-x86_64 iccstatic --with-production -O3 -ip -xCORE-AVX512`.

**Comment by evan-charmworks** [comment]
Please reopen if this is still an issue.
