### ISSUE TITLE
Faced error while compiling 7.0 version in AVX512

### ISSUE THREAD

**Issue by ajithvallabai** [UIUC-PPL/charm#3577]
Hey i faced below error while compiling in AVX512 mode

`./buildold charm++ multicore-linux-x86_64 iccstatic --with-production "-O3 -ip -xCORE-AVX512 "`

![Screenshot from 2022-03-02 13-44-57](https://user-images.githubusercontent.com/8075112/156322301-df83fb38-923b-4a0b-aed1-08e5f16d6b44.png)

[config.log](https://github.com/UIUC-PPL/charm/files/8167854/config.log)

kindly help me with a solution if possible

**Comment by evan-charmworks** [comment]
Don't enclose the options in quotes.

`./buildold charm++ multicore-linux-x86_64 iccstatic --with-production -O3 -ip -xCORE-AVX512`
