### ISSUE TITLE
PAMI SMP Memory fragmentation / leak

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#358]
*Original author: Lukasz Wesolowski*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/358*

---
I have noticed a memory leak in pami machine layers in smp mode. For an all-to-all benchmark, I print out the memory usage at the start and after 1000 iterations for each message size tested. The memory usage is higher after the benchmark finishes than at the start. It does not appear to be a problem with my benchmark, as running in non-smp mode does not lead to a leak. I am including the output. Notice that the memory seems to increase in regular units of 8 MB or so. I noticed the same in my random access runs on BG/Q, where the memory eventually runs out:

Charm++> Running on 64 unique compute nodes (64-way SMP).
Elapsed time for payload 32 with 1000 iterations: 0.000274 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 64 with 1000 iterations: 0.000288 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 128 with 1000 iterations: 0.000303 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 256 with 1000 iterations: 0.000309 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 512 with 1000 iterations: 0.000328 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 1024 with 1000 iterations: 0.000338 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 2048 with 1000 iterations: 0.000359 seconds
Memory usage: 44.160156 MB
Elapsed time for payload 4096 with 1000 iterations: 0.000335 seconds
Memory usage: 52.160156 MB
Elapsed time for payload 8192 with 1000 iterations: 0.000386 seconds
Memory usage: 52.160156 MB
Elapsed time for payload 16384 with 1000 iterations: 0.000541 seconds
Memory usage: 52.160156 MB
Elapsed time for payload 32768 with 1000 iterations: 0.000900 seconds
Memory usage: 52.160156 MB
Elapsed time for payload 65536 with 1000 iterations: 0.001583 seconds
Memory usage: 60.160156 MB
Elapsed time for payload 131072 with 1000 iterations: 0.003079 seconds
Memory usage: 68.160156 MB
Elapsed time for payload 262144 with 1000 iterations: 0.006228 seconds
Memory usage: 84.160156 MB
[Partition 0][Node 0] End of program

[139070.output](https://github.com/UIUC-PPL/charm/files/3536412/139070.output.txt)
[alltoallTest.C](https://github.com/UIUC-PPL/charm/files/3536413/alltoallTest.C.txt)
[alltoallTest.ci](https://github.com/UIUC-PPL/charm/files/3536414/alltoallTest.ci.txt)
[Makefile](https://github.com/UIUC-PPL/charm/files/3536415/Makefile.txt)
[mtmTest.C](https://github.com/UIUC-PPL/charm/files/3536416/mtmTest.C.txt)
[mtmTest.ci](https://github.com/UIUC-PPL/charm/files/3536417/mtmTest.ci.txt)
[valg.13596.txt](https://github.com/UIUC-PPL/charm/files/3536418/valg.13596.txt)

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-11-23 02:03:10*

---
I previously reported that the memory leak does not occur in non-smp mode. Actually, it does. Here are the non-smp results. I ran up to a larger message size to show that the problem becomes more significant at higher message sizes. Notice that the memory usage does not increase until an all-to-all with message sizes of 64KB. This makes it unlikely that there is a leak in my program, as I don't do anything different for larger message sizes. 

I am including the output and the program as attachments.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-11-23 02:40:47*

---
Actually I was measuring memory usage at a time when received messages were not deleted yet. Closing the issue.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-23 03:03:31*

---
Setting to 'Rejected' as it was not actually a bug.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-11-23 04:40:42*

---
After freeing received buffers, there is still an increase in memory use over time. I see similar behavior on a lab machine, so it may be a problem with charm in general, not anything related to pami machine layer. I will keep looking at this and try to come up with a simpler example showing this problem.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-11-24 05:01:41*

---
I simplified the alltoall code and ran it with valgrind on a local workstation to help in tracking down the memory leak. 

The leak is not as significant when running locally on 4 PEs (compared to 64 node run on BG/Q), but valgrind did identify some issues. 

I also added a little code at the end of the run to wait for 10 seconds to see if the memory use eventually goes down. It does not, and in fact there is an increase during the first second while I am calling CthYield while waiting (something to check as the cause of the leak). 

Some things that look suspect:
- _messagePool and _tokenPool (ckObjQ): code that seems to have not been touched for a long time, but with the potential for small allocations over time that can build up

- LB database - there is a significant allocation at the beginning 

- memory increase after yield

- CmiTmpAlloc - another piece of ancient code that may not even be used

Benchmark code and valgrind output for one of the PEs is attached.

Output for a local run, showing a leak of about .5 MB . For my BG/Q run on 64 nodes, memory use grows from ~45 MB to over 100 MB at the end.

Memory usage at the start: 1.575554 MB
Elapsed time for payload 32 with 1000 iterations: 0.007835 seconds
Memory usage: 1.711124 MB
Elapsed time for payload 64 with 1000 iterations: 0.006841 seconds
Memory usage: 1.756165 MB
Elapsed time for payload 128 with 1000 iterations: 0.006689 seconds
Memory usage: 1.766148 MB
Elapsed time for payload 256 with 1000 iterations: 0.006819 seconds
Memory usage: 1.736523 MB
Elapsed time for payload 512 with 1000 iterations: 0.006866 seconds
Memory usage: 1.732807 MB
Elapsed time for payload 1024 with 1000 iterations: 0.006953 seconds
Memory usage: 1.727753 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB
Waiting 1s
Memory usage: 1.969475 MB

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:24:48*

---
In recent experiments conducted by Lukasz and me, we found that the leak can be attributed to BGQ's internal malloc implementation. It does not return the memory back to the OS for small sized mallocs. While this behavior is not unusual for malloc implementation, BGQ's malloc is particular worrying since it may end up occupying large amount of memory unused, while malloc request for large sizes fail.

**Comment by lvkale** [comment]
*Original date: 2014-01-03 06:16:06*

---
So, what possible recourse do we have?

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 07:16:33*

---
BGQ team typically advises to do large allocs first followed by smaller one (pass the burden to application). Alternatively, we can think of intercepting the mallocs - more burden on the RTS - if done, we should do it generically for all machines.

**Comment by PhilMiller** [comment]
*Original date: 2014-12-22 20:55:20*

---
(retitle to make bug listings easier to read/understand)

**Comment by ericjbohm** [comment]
*Original date: 2015-10-26 17:58:33*

---
This not been documented as affecting any production application.  If it becomes necessary to address it in the future, the recommended solution of making a generic charm allocator/mempool that has a suitably large blocksize, should be pursued.  However, that is a significant piece of work which should be motivated by a compelling use case.
