### ISSUE TITLE
Investigate implementation of CCS on BG/Q

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#363]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/363*

---
The Mercury project (http://trac.mcs.anl.gov/projects/mercury) may provide a portable scheme for communication with running applications that we can leverage.  It provides a basic functionality for RPC that is very similar to CCS.  If we can build CCS on Mercury, then we can use CCS anywhere that Mercury works, which should be everywhere that we care about.  This would then allow CharmDebug to be more generally useful on varoius target architectures.

If Mercury can't be used to support CharmDebug, then we should examine the scheme being used by gdb on BG/Q and determine how difficult it would be to use as the substrate for CCS.

**Comment by stwhite91** [comment]
*Original date: 2017-08-01 18:11:05*

---
BG/Q is dying, so lowering priority and assigning away from Bilge.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-11 19:55:02*

---
This is probably just not going to happen, so closing it out.
