### ISSUE TITLE
[Bug] Inline entry methods don't like templates

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#3656]
Hi folks! We currently do the following patch:

```
-  _TRACE_CREATION_DETAILED(&env, CkIndex_AlgorithmArray <ParallelComponent, SpectreArrayIndex> ::template idx_invoke_iterable_action_void<ThisAction, PhaseIndex, DataBoxIndex>());
+  _TRACE_CREATION_DETAILED(&env, (CkIndex_AlgorithmArray <ParallelComponent, SpectreArrayIndex> ::template idx_invoke_iterable_action_void<ThisAction, PhaseIndex, DataBoxIndex>()));
```

This is just adding parents around the second macro argument of the `_TRACE_CREATION_DETAILED` macro. Should be an easy fix to get into 7.0.1!

**Comment by rbuch** [comment]
This should have been fixed in #3620, I think (triggered by your previous report of #3618). Can you confirm if that fix works for this issue?
