### ISSUE TITLE
[Bug] Cannot serialize unique_ptr with virtual inheritance of a PUP::able

### ISSUE THREAD

**Issue by nilsdeppe** [UIUC-PPL/charm#3657]
This is a regression from https://github.com/UIUC-PPL/charm/pull/3599 I don't understand why the code change there was made, but it caused a regression for us. We now cannot build if we have:

```
    PUP::able
  /   \
/       \
A      B
 \     /
  \   /
   C
````
we get the following error:
```
In file included from /home/nils/SpECTRE/spectre/tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Test_Binary.cpp:4:
In file included from /home/nils/SpECTRE/spectre/tests/Unit/Framework/TestingFramework.hpp:27:
In file included from /home/nils/SpECTRE/spectre/src/Utilities/System/Exit.hpp:6:
In file included from /home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/charm++.h:24:
In file included from /home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/cklists.h:6:
/home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/pup_stl.h:477:15: error: cannot cast 'PUP::able *' to 'elliptic::analytic_data::AnalyticSolution *' via virtual base 'PUP::able'
      t.reset((T*)t1);
              ^~~~~~
/home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/pup_stl.h:486:5: note: in instantiation of function template specialization 'PUP::pup<elliptic::analytic_data::AnalyticSolution, nullptr>' requested here
    pup(p, t);
    ^
/home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/pup_stl.h:415:54: note: in instantiation of function template specialization 'PUP::operator|<elliptic::analytic_data::AnalyticSolution>' requested here
    std::for_each(a.begin(), a.end(), [&p](T& t) { p | t; });
                                                     ^
/home/nils/SpECTRE/charm/multicore-linux-x86_64-gcc/include/pup_stl.h:426:5: note: in instantiation of function template specialization 'PUP::pup<std::unique_ptr<elliptic::analytic_data::AnalyticSolution>, 2UL, nullptr>' requested here
    pup(p, a);
    ^
/home/nils/SpECTRE/spectre/src/PointwiseFunctions/AnalyticData/Xcts/Binary.hpp:364:7: note: in instantiation of function template specialization 'PUP::operator|<std::unique_ptr<elliptic::analytic_data::AnalyticSolution>, 2UL>' requested here
    p | superposed_objects_;
      ^
/home/nils/SpECTRE/spectre/tests/Unit/PointwiseFunctions/AnalyticData/Xcts/Test_Binary.cpp:85:23: note: in instantiation of member function 'Xcts::AnalyticData::Binary<elliptic::analytic_data::AnalyticSolution, brigand::list<Xcts::Solutions::Schwarzschild>>::pup' requested here
  const auto binary = serialize_and_deserialize(derived);
                      ^
1 error generated.
```
I believe `pup` needs to be called "bottom up" for it to be safe (the opposite order of construction) which is also how I interpret the Charm++ manual https://charm.readthedocs.io/en/latest/charm%2B%2B/manual.html#subclass-allocation-via-pup-able with the example that every _derived_ class needs to first call its base class `pup` (construction order).

**Comment by rbuch** [comment]
Perhaps @jszaday would like chime in?

**Comment by jszaday** [comment]
I was encountering issues since `operator|` was undefined for my PUPable derived class. As PUP methods are virtual, the call ordering is not a concern (it will reach the PUP method of the derived class from the vtable).

Can you try changing the `t.reset((T*)t1);` to `t.reset(dynamic_cast<T*>(t1));` (per [this StackOverflow](https://stackoverflow.com/a/3749251))? If that fixes this issue, feel free to open a PR with that change. Otherwise, please revert my PR.

**Comment by nilsdeppe** [comment]
Sorry, isn't there a generic `operator|` that operates on any class that has a `pup(PUP::er& p)` member function? If the class doesn't have that defined, then the virtual function is not overridden and the derived classes `pup` function would not get called. What am I missing?

**Comment by jszaday** [comment]
In this case, it's because there's no generic `operator|` for pointers of PUPable derived classes. In the case of the error, there is no global `operator|(PUP::er& p, elliptic::analytic_data::AnalyticSolution *)`.

Part of the contract for PUPables is that you must override the virtual pup method, at least that's my understanding.

**Comment by nilsdeppe** [comment]
Oh, so in the original case where you ran into trouble you had a `std::unique_ptr<T*>` and that's why it failed to do `p | t`? I'm still trying to understand the failure case you ran into that made you make the change :) There's some context there that I'm missing, sorry!

Should we instead be dereferencing the pointer on lines 476 and 479? Thinking about this more, I think I generally like that better (assuming it works!) because then the issue of the "no `operator|` for pointer" is avoided. This then makes the only requirement of being able to serialize a `T` be that `p | object_of_T` is valid, which I think falls into "it better be otherwise this is spooky evil pointer things", no? The specific change I'm suggesting: Keep `t1` as `T`, then dereference it when it's used in `p | *t1;`.

**Comment by jszaday** [comment]
Something like that. Unfortunately, I did not preserve a representative snippet.

As for dereferencing, I'm sorry to say but one cannot dereference `nullptr`; note that `t1` is declared as `PUP::able* t1 = nullptr;`. Unfortunately, due to the design of PUPable de/serialization, their pup method allocates the object and sets the pointer.

**Comment by nilsdeppe** [comment]
Okay, no worries!

Derp, yea... Okay, the only option left that I see as easy and reasonable is to do `dynamic_cast` instead of C-style cast (which you shouldn't be using anyway! 😄 ). There's some overhead occurred for `dynamic_cast` over a `static_cast`, but given this is in serialization of a pointer it should be largely irrelevant compared to the memory allocation+serialization costs. Does the `dynamic_cast` solution (as in your previous comment) still sound okay?

I'd prefer to avoid limiting to classes marked as `final` since I worry that it'll just delay the issue for someone down the road (possibly me when SpECTRE builds another source file with such an inheritance pattern)...

**Comment by jszaday** [comment]
I concur, trying `dynamic_cast` seems reasonable (I leave that as an exercise to others).

Truthfully, I left it as a C-style cast assuming it would decay to `static_cast` whenever feasible, and `dynamic_cast` only when necessary; I see now the evils of my past ways. Later, I wrote a bit of code in Hypercomm to choose the best option called [`fast_cast`](https://github.com/jszaday/hypercomm/blob/8bf03d40f9b89dfd5fc9ca33a86158187c632da1/include/hypercomm/utilities.hpp#L82). If someone cares to, they can copy that here to try to avoid some penalties.

**Comment by nilsdeppe** [comment]
Oooh, `fast_cast` is fun :D I'm happy with either adding that or just doing a `dynamic_cast`. Like I said, the performance penalty of a `dynamic_cast` here is going to be irrelevant compared to all the serialization, sending over a network, and memory allocations. 

@rbuch if you're happy with a `dynamic_cast` I can submit a PR. I tested and this works with SpECTRE :)

**Comment by rbuch** [comment]
> Oooh, `fast_cast` is fun :D I'm happy with either adding that or just doing a `dynamic_cast`. Like I said, the performance penalty of a `dynamic_cast` here is going to be irrelevant compared to all the serialization, sending over a network, and memory allocations. 
> 
> @rbuch if you're happy with a `dynamic_cast` I can submit a PR. I tested and this works with SpECTRE :)

I think a `dynamic_cast` is fine here given the cost of the other operations being done, like you said. I'd be happy with that PR.
