### ISSUE TITLE
issues with dynamic insertion and deletion of array chare elements

### ISSUE THREAD

**Issue by kidder** [UIUC-PPL/charm#3660]
Hello,

I am developing adaptive mesh refinement for [spectre](https://github.com/sxs-collaboration/spectre) (which uses charm++) and have encountered several issues when inserting new elements and destroying old elements of an array chare.

The issues could be caused by my missing or not understanding the documentation regarding dynamic array insertion/deletion such as calls to `beginInserting` and `doneInserting`.

I have put together several charm++ only examples that illustrate two issues I have encountered, as well as a complete 1D example of the AMR algorithm that I am trying to implement.

The first issue is reproduced in `dynamic_array_expansion`.  The issue is that some newly created elements execute all entry methods called from the beginning of execution instead of those called after their creation.  This example fails on the `main` branch but not on `v7.0.0`.  git bisection points to commit 5e26e07023 (which I note is also blamed for #3643).

The second issue is reproduced in `dynamic_array_hang`.  The issue is that the code hangs in some instances when an element has been deleted at some point and then recreated later on a different PE.  This fails on v7.0.0, but the first issue prevents this example from being tested on the main branch.

Please let me know if there is any additional information you need.

**Comment by rbuch** [comment]
Thanks for your report! Where exactly can we get `dynamic_array_expansion` and `dynamic_array_hang` from?

**Comment by kidder** [comment]
Oops, sorry, meant to provide the link.  

https://github.com/kidder/charm_spectre_tests

**Comment by rbuch** [comment]
#3661 should fix at least the `dynamic_array_expansion` part of this. I can't get the `dynamic_array_hang` to reproduce with that change (without it, I get segfaults, not hangs). Can you test it out and see if it fixes it for you, too?

**Comment by kidder** [comment]
I confirm that this fixes the `dynamic_array_expansion` issue.
The `dynamic_array_hang` example only hangs on v7.0.0; it seems to succeed with this fix on main; my suspicion is that commit 5e26e07023 and this fix addresses that particular issue as well.

My `random_1d_amr_example` makes it much further now, and I'm getting an exception thrown in my code so I'll look at that more closely tomorrow to track down the cause.  

Thank you for the quick fix!

**Comment by rbuch** [comment]
Great, glad it does the trick! I'll leave this issue open pending your confirmation that both of your examples codes work with this change.

**Comment by nilsdeppe** [comment]
Question: would it be okay to add the examples into Charm++ as regression tests?

**Comment by rbuch** [comment]
> Question: would it be okay to add the examples into Charm++ as regression tests?

Yes, that's a good idea so long as you all are fine with contributing them. I'll create a new issue for that so this one stays focused on tracking the bug itself.

**Comment by kidder** [comment]
An update, the `dynamic_array_expansion` and `dynamic_array_hang` examples now appear to reliably work.

I've updated my `random_1d_amr_example` with parameters that now cause it to reproducibly fail (with an assertion about neighbors failing) on the second iteration, but only if run on 3 PEs.  It appears that an entry method called on a newly created element is not being executed despite two quiescence detections between the insert call to create the element and the call to `initialize_parent` (which initializes the ids of the neighbors)

This example is not as simple as the other two, so if you have any questions about it, please feel free to ping me on slack

**Comment by adityapb** [comment]
This issue is happening because the entry from the location manager isn't being cleared correctly when an element is destroyed. In this case, during the first iteration, element 1 is created on PE0. It is then deleted from PE0 and created on PE1, but the location manager on PE0 still thinks that it exists on PE0 since its entry wasn't cleared when it was deleted. So any message to this element from PE0 gets buffered on PE0 waiting for it to be created there and is never delivered. I am working on a PR to fix this issue
