### ISSUE TITLE
cray topology detection build time failure on perlmutter with confusing error message

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#3688]
./build charm++ ofi-crayshasta ...

will fail on perlmutter with the following error output:

charm/src/util/topomanager/CrayNid.c: In function 'getXTNodeID':
charm/src/util/topomanager/CrayNid.c:46:2: error: #error "Cannot get network topology information on a Cray build. Swap current module xt-mpt with xt-mpt/5.0.0 or higher and xt-asyncpe with xt-asyncpe/4.0 or higher and then rebuild"
   46 | #error "Cannot get network topology information on a Cray build. Swap current module xt-mpt with xt-mpt/5.0.0 or higher and xt-asyncpe with xt-asyncpe/4.0 or higher and then rebuild"
      |  ^~~~~

Which will be terribly confusing for a typical user as none of those modules exist in a slingshot environment.

This can be resolved via :
module load cray-pmi

Which is not in the default module stack on perlmutter.

The error output should be updated accordingly in slingshot environments.

**Comment by stwhite91** [comment]
It looks like this commit hasn't made it into a PR

**Comment by evan-charmworks** [comment]
@ericjbohm Could you make a PR for your branch `3688-cray-topology-detection-build-time-failure-on-perlmutter-with-confusing-error-message`?
