### ISSUE TITLE
charm++ multicore-windows build

### ISSUE THREAD

**Issue by soundarthiaga** [UIUC-PPL/charm#3698]
I'm trying to build the multicore charm++ binary in windows and facing some issues, is it possible to either share the charm++ binary or instructions to build multicore-windows version of charm++

**Comment by stwhite91** [comment]
`./build charm++ multicore-win-x86_64 --with-production` should work. Can you provide the full output of running that command?

**Comment by soundarthiaga** [comment]
Should I run it in cygwin or msys2
And which compiler should I use?

**Comment by evan-charmworks** [comment]
@soundarthiaga Please see https://github.com/UIUC-PPL/charm/wiki/Building-Charm-on-Windows which may help guide you through the process.
