### ISSUE TITLE
Metabalancer's use of immediate messages causes hangs with QD

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#37]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/37*

---
Replicate this bug with current charm, or show that its fixed and close.

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 18:55:50*

---
If this can't be replicated, close this issue.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:24:22*

---
As Eric said, if this issue is not reproducible, please close.

**Comment by harshithamenon** [comment]
*Original date: 2015-02-09 21:37:57*

---
Metabalancer has groups and not nodegroups. Therefore, changed the entry method attribute from immediate to expedited. http://charm.cs.uiuc.edu/gerrit/#/c/511/

But QD with immediate messages hangs. Created another issue (https://charm.cs.illinois.edu/redmine/issues/660)
