### ISSUE TITLE
Error in building charmm++ 7.0.0

### ISSUE THREAD

**Issue by yingioi0** [UIUC-PPL/charm#3739]
I have met a strange problem when building charmm++ 7.0.0:
[ 32%] Generating ../../include/CkFutures.decl.h, ../../include/CkFutures.def.h
/software/charm-v7.0.0/netlrts-linux-x86_64/bin/charmxi: symbol lookup error:/software/charm-v7.0.0/netlrts-linux-x86_64/bin/charmxi: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev
Fatal Error by charmc in directory/software/charm-v7.0.0/netlrts-linux-x86_64/include
   Command/software/charm-v7.0.0/netlrts-linux-x86_64/bin/charmxi -orig-file/software/charm-v7.0.0/tests/charm++/simplearrayhello/hello.ci returned error code 127
charmc exiting...

My envoriment shows below:
Charm++ 7.0.0 configuration: 
  OS version:      "CentOS Linux release 7.4.1708 (Core) " (Linux 3.10.0-693.el7.x86_64, x86_64)
  Charm++ version: v70000 
  Hostname:        inode99
  Machine layer:   netlrts-linux-x86_64
  Build target:    charm++
  Build type:      Debug
  C compiler:     /.local/bin/gcc [GNU 11.4.0]
  C++ compiler:   /.local/bin/c++ [GNU 11.4.0]
  F90 compiler:    /usr/bin/gfortran [GNU 4.8.5]
  CMake:           /usr/local/bin/cmake [3.8.2]
  Charmc flags:    -g
  Enabled options: TRACING ERROR_CHECKING ZLIB

The screen output is attached. Anyone who can help me? Thanks in advance.

[screenout.txt](https://github.com/UIUC-PPL/charm/files/11714373/screenout.txt)

**Comment by evan-charmworks** [comment]
I suspect this problem no longer exists with the latest code in our main branch. @yingioi0 Could you verify that on your machine?
