### ISSUE TITLE
Use new topology ordering function on BGQ

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#374]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/374*

---
Replace our short term solution to allow for correct topology information using an environment variable with the new function call that IBM provided on our request.

**Comment by nikhil-jain** [comment]
*Original date: 2013-12-06 20:23:35*

---
Resolved via http://charm.cs.uiuc.edu/gerrit/#/c/15/

**Comment by PhilMiller** [comment]
*Original date: 2013-12-08 06:43:15*

---
Builds seem to fail under GCC, due to a missing prototype:

```
BGQTorus.C: In constructor 'BGQTorusManager::BGQTorusManager()':
BGQTorus.C:57: error: 'Kernel_GetMapping' was not declared in this scope

```

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:06:46*

---
Not a GCC thing. Only some machines have an updated driver. This change has been temporarily rolled back, till all machine move to the next driver, V1R2M1.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-07 23:04:04*

---
It looks like the rollout of the V1R2M1 driver on Mira/Cetus is going to be held back, due to a just-uncovered bug in `MPI_Comm_create` and `MPI_Comm_split`. It would have happened this week or next, but that's been set aside.

**Comment by stwhite91** [comment]
*Original date: 2016-05-02 17:18:18*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/422/~~ https://github.com/UIUC-PPL/charm/commit/e223cf64a5f1c08b00e17d3b8dfd938062fbbbba
