### ISSUE TITLE
Is Data Layout configurable?

### ISSUE THREAD

**Issue by Anjiang-Wei** [UIUC-PPL/charm#3744]
I want to cite Charm++ in a paper and try to describe and understand Charm++'s features clearly. Could you please answer the following questions for me? I have read the documentation, but still could not find the answer.

1) Is data layout fixed for creating 2D array? Is it column-major or row-major? https://charm.readthedocs.io/en/latest/parfum/manual.html#data-layout

2) How can users handle memory collection? Should users use C++'s malloc and free?

**Comment by ericjbohm** [comment]
Charm++ does not prescribe data layout in memory. 

Charm++ arrays are designed to provide an abstraction for interactions between objects, generally for parallelization in a distributed memory context.    How memory is used within an object is entirely up to the user.   We recommend the new/delete operators as the preferred approach for memory management in C++ applications, but Charm++ can also be use in C or Fortran, where new/delete would not be appropriate.

The ParFUM framework you reference (now deprecated) was an abstraction layer above Charm++ designed to support unstructured mesh applications.  It also made no prescription regarding data layout.
