### ISSUE TITLE
Performance regression from SDAG overhaul

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#376]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/376*

---
The SDAG overhaul accounted for 13-14% of the overall 15% slowdown of AMR from 6.5 to 6.6-rc1. Part of this slowdown has already been addressed in commit:9bcafc5fd93840fc362e4dde2b34d53074a64ae7, but another 11-12% remains to be made up.

**Comment by lifflander** [comment]
*Original date: 2013-12-10 18:51:29*

---
I have identified that half the remaining SDAG overhead comes from "void" methods, which still use the generated closure.

**Comment by lifflander** [comment]
*Original date: 2013-12-12 06:08:34*

---
Fixed, needs a little more tested before it can be merged.

**Comment by PhilMiller** [comment]
*Original date: 2013-12-12 06:36:58*

---
AMR timings look much better now, though there might still be something lurking in SDAG. Running `./advection.sdag2 7 32 60` version 6.5 gives about 10.25s, while with the just-merged code I get 10.8s. So we're down to about a 5% difference. Eric's pending changes in #370 may cover that, but I'll hold off on closing this until we see that.

**Comment by lifflander** [comment]
*Original date: 2013-12-12 06:51:43*

---
Just a clarification: my timing are from linux (thrift). Phil's are from his mac. I am investigating perf on the mac now.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-03 05:18:16*

---
Jonathan - is this resolved?  If so, please close the issue.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-30 19:16:09*

---
As noted in #345, we're now at a 0.5% slowdown relative to 6.5.1. I think that's within the realm of acceptable, given the benefits gained. We can write some microbenchmarks to tune this further post-release.
