### ISSUE TITLE
Download AMPI benchmarks?

### ISSUE THREAD

**Issue by vsoch** [UIUC-PPL/charm#3761]
Hi! I'm trying to do the ssh clone at the top of the docs here:

https://charm.readthedocs.io/en/latest/ampi/05-examples.html

But it times out. Is this still the correct URL / port to download them, or is there somewhere else? Thank you!

**Comment by vsoch** [comment]
Are they packaged in the main tar.gz now? Note I see one AMPI directory here!

![image](https://github.com/UIUC-PPL/charm/assets/814322/258fbe47-800b-4fad-a61c-56693b6e3d01)

**Comment by ZwFink** [comment]
@stwhite91 Can you comment?

**Comment by stwhite91** [comment]
@matthiasdiener can you move the ampi-examples repo to the uiuc-ppl github, if you still have access to ampi-examples? I don't think I do

**Comment by matthiasdiener** [comment]
I was looking around on the `charm` machine, but could not find any of the gerrit repos. Maybe they were on a VM? @ebohm 


I vaguely remember that there may be some distribution restrictions on the code in that repo? Is there any specific benchmark you are interested in @vsoch ?

**Comment by vsoch** [comment]
I wanted to explore what was there - I can't say I knew in advance! I was going off of the clone here https://charm.readthedocs.io/en/latest/ampi/05-examples.html so I was generally interested in all the AMPI apps.
