### ISSUE TITLE
Installing and testing

### ISSUE THREAD

**Issue by BJWiley233** [UIUC-PPL/charm#3766]
Hi,  

From this website https://www.ks.uiuc.edu/Development/Download/download.cgi, it indicates to run:

```
cd multicore-linux-x86_64/tests/charm++/megatest
make pgm
```

Well there is no pgm.c file in the megatest folder and the Makefile does not indicate to make it so I get error:

```
make: *** No rule to make target 'pgm'.  Stop.
```

I downloaded NAMD_3.0b3_Source.tar.gz to compile because the multicore CUDA binary doesn't work with my version of CUDA 12.0.

**Comment by matthiasdiener** [comment]
It should probably be `make megatest`.

**Comment by matthiasdiener** [comment]
Closing this - please reopen if it is still an issue.
