### ISSUE TITLE
Segfault in SDAG anytime migration test on net icc, net -pedantic

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#378]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/378*

---
Coincident in time with the fixes for issue #370 and therefore probably caused by them.

See nightly build for details.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-07 22:53:06*

---
This appears to have been addressed with the revert and revision of the fix for #376 (commit:ff78 et seq). Close?
