### ISSUE TITLE
Performance degradation from alignment change

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#379]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/379*

---
Single core charm++ 1d Array pingpong is 10% worse.

netlrts-linux-x86_64 tests/charm++/pingpong for 10byte load for 1Darray (run on intellect) goes from ~0.50-us to ~0.57us across this change.
./pgm 10 100000 +pemap 7 +setcpuaffinity
Before:
Charm++: standalone mode (not using charmrun)
Charm++> Running in non-SMP mode: numPes 1
Converse/Charm++ Commit ID: v6.6.0-rc1-12-g9e4fe1f
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 7
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.490999 us
Roundtrip time for 1D threaded Arrays is 4.238181 us
Roundtrip time for 2D Arrays is 0.532241 us
Roundtrip time for 3D Arrays is 0.540168 us
Roundtrip time for Fancy Arrays is 0.545340 us
Roundtrip time for Chares (reuse msgs) is 0.200419 us
Roundtrip time for Chares (new/del msgs) is 0.360110 us
Roundtrip time for threaded Chares (reuse) is 3.546221 us
Roundtrip time for Groups is 0.199237 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.237141 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.439320 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.715337 us
Roundtrip time for NodeGroups is 0.218320 us
[Partition 0][Node 0] End of program

After:
Charm++: standalone mode (not using charmrun)
Charm++> Running in non-SMP mode: numPes 1
Converse/Charm++ Commit ID: v6.6.0-rc1-18-g575af7e
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 7
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.573909 us
Roundtrip time for 1D threaded Arrays is 4.364600 us
Roundtrip time for 2D Arrays is 0.538850 us
Roundtrip time for 3D Arrays is 0.608790 us
Roundtrip time for Fancy Arrays is 0.595131 us
Roundtrip time for Chares (reuse msgs) is 0.180972 us
Roundtrip time for Chares (new/del msgs) is 0.360940 us
Roundtrip time for threaded Chares (reuse) is 3.631361 us
Roundtrip time for Groups is 0.223718 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.266757 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.497260 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.748744 us
Roundtrip time for NodeGroups is 0.236740 us
[Partition 0][Node 0] End of program

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-12-19 00:30:00*

---
Unlike Eric, I am not seeing a consistent performance degradation when using the alignment changes on talent. Results are below. 

It seems Eric was not comparing with the commit immediately prior to this one. Eric, can you clarify which commit is v6.6.0-rc1-12-g9e4fe1f?


wesolwsk`talent:~/work/charm/tests/charm++/pingpong$ ./pgm-align 10 100000
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-18-g575af7e
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (4-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.470040 us
Roundtrip time for 1D threaded Arrays is 3.869350 us
Roundtrip time for 2D Arrays is 0.480330 us
Roundtrip time for 3D Arrays is 0.500450 us
Roundtrip time for Fancy Arrays is 0.517111 us
Roundtrip time for Chares (reuse msgs) is 0.162790 us
Roundtrip time for Chares (new/del msgs) is 0.287409 us
Roundtrip time for threaded Chares (reuse) is 3.141041 us
Roundtrip time for Groups is 0.173841 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.210319 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.388422 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.615840 us
Roundtrip time for NodeGroups is 0.202198 us
Program finished.
wesolwsk`talent:~/work/charm/tests/charm++/pingpong$ ./pgm-noalign 10 100000
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-17-gd831644
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (4-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.491240 us
Roundtrip time for 1D threaded Arrays is 3.974211 us
Roundtrip time for 2D Arrays is 0.464580 us
Roundtrip time for 3D Arrays is 0.502920 us
Roundtrip time for Fancy Arrays is 0.523140 us
Roundtrip time for Chares (reuse msgs) is 0.161021 us
Roundtrip time for Chares (new/del msgs) is 0.355291 us
Roundtrip time for threaded Chares (reuse) is 3.079610 us
Roundtrip time for Groups is 0.173278 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.205359 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.422044 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.635920 us
Roundtrip time for NodeGroups is 0.202460 us
Program finished.

**Comment by ericjbohm** [comment]
*Original date: 2013-12-19 17:35:23*

---
Lukasz Wesolowski wrote:
> Unlike Eric, I am not seeing a consistent performance degradation when using the alignment changes on talent. Results are below. 
> 
> It seems Eric was not comparing with the commit immediately prior to this one. Eric, can you clarify which commit is v6.6.0-rc1-12-g9e4fe1f?
> 

It was post 6.6, but before this commit.  Regardless, the same thing can be found by taking the new head and reverting the alignment commit.

However, you need make pingpong with  OPTS="-optimize -production" to wash out the asserts and other overheads that swamp fine grained studies with pingpong.

When running pingpong on talent, I see  0.433831 before vs 0.465651 after the alignment commit.

**Comment by mprobson** [comment]
*Original date: 2013-12-19 19:48:32*

---
This was because the change in xi-symbol.C to make sure a varsize field (i.e. x in PingMsg) is properly aligned. That causes the var size message to be 8 byte bigger than the old version, which explains everything.

Gengbin

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2013-12-19 20:05:55*

---
I am still unconvinced about the extent of the difference. There is a lot of variability across runs. Even when doing 100000 iterations, the average time for 1D Array pingpong with the latest changes on talent varies from .44 us to .49 us depending on the run. This is when compiling with "-optimize -production" and using +pemap 3.

Eric, are you accounting for the noise (or have you found a way to produce consistent results)?

Below are the results for three consecutive runs, showing some of the variation.

wesolwsk`talent:~/work/charm/net-linux-x86_64-after-align/tests/charm++/pingpong$ ./pgm 10 100000 +pemap 3 +setcpuaffinity
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-18-g575af7e
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 3
Charm++> Running on 1 unique compute nodes (4-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.470698 us
Roundtrip time for 1D threaded Arrays is 3.881028 us
Roundtrip time for 2D Arrays is 0.490959 us
Roundtrip time for 3D Arrays is 0.503819 us
Roundtrip time for Chares (reuse msgs) is 0.165119 us
Roundtrip time for Chares (new/del msgs) is 0.290101 us
Roundtrip time for threaded Chares (reuse) is 3.143792 us
Roundtrip time for Groups is 0.180297 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.207558 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.386658 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.607543 us
Roundtrip time for NodeGroups is 0.193720 us
Program finished.
wesolwsk`talent:~/work/charm/net-linux-x86_64-after-align/tests/charm++/pingpong$ ./pgm 10 100000 +pemap 3 +setcpuaffinity
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-18-g575af7e
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 3
Charm++> Running on 1 unique compute nodes (4-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.460730 us
Roundtrip time for 1D threaded Arrays is 3.910720 us
Roundtrip time for 2D Arrays is 0.560880 us
Roundtrip time for 3D Arrays is 0.521309 us
Roundtrip time for Fancy Arrays is 0.521009 us
Roundtrip time for Chares (reuse msgs) is 0.170720 us
Roundtrip time for Chares (new/del msgs) is 0.293810 us
Roundtrip time for threaded Chares (reuse) is 3.167570 us
Roundtrip time for Groups is 0.173664 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.211163 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.384278 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.631022 us
Roundtrip time for NodeGroups is 0.198684 us
Program finished.
wesolwsk`talent:~/work/charm/net-linux-x86_64-after-align/tests/charm++/pingpong$ ./pgm 10 100000 +pemap 3 +setcpuaffinity
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-18-g575af7e
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 3
Charm++> Running on 1 unique compute nodes (4-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
Pingpong with payload: 10 iterations: 100000
Roundtrip time for 1D Arrays is 0.440769 us
Roundtrip time for 1D threaded Arrays is 3.805139 us
Roundtrip time for 2D Arrays is 0.485699 us
Roundtrip time for 3D Arrays is 0.500448 us
Roundtrip time for Fancy Arrays is 0.552111 us
Roundtrip time for Chares (reuse msgs) is 0.173461 us
Roundtrip time for Chares (new/del msgs) is 0.288460 us
Roundtrip time for threaded Chares (reuse) is 3.116841 us
Roundtrip time for Groups is 0.170598 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 0.207620 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 0.394597 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 0.680876 us
Roundtrip time for NodeGroups is 0.202117 us
Program finished.

**Comment by ericjbohm** [comment]
*Original date: 2013-12-19 20:18:27*

---
Lukasz Wesolowski wrote:
> I am still unconvinced about the extent of the difference. There is a lot of variability across runs. Even when doing 100000 iterations, the average time for 1D Array pingpong with the latest changes on talent varies from .44 us to .49 us depending on the run. This is when compiling with "-optimize -production" and using +pemap 3.
> 
> Eric, are you accounting for the noise (or have you found a way to produce consistent results)?
> 

There is variability, but if you do a series of runs of each, the median is always worse for after the alignment change.  The results for OpenAtom are much more consistent (consistently worse) than for pingpong, but they entirely agree on a performance degradation.  NAMD (being group based) experiences negligible change in performance from this change, much like the envelope reduction change.  I'm curious as to whether a difference appears in ChaNGa also.

Making array performance worse is not a direction in which I wish to go. As it raises questions like "Should we convert openatom from arrays to groups with application management of further decomposition?", which is a giant leap backwards in productivity.

**Comment by ericjbohm** [comment]
*Original date: 2014-01-23 22:41:02*

---
After the reversion to the single contiguous envelope scheme there is no longer a measurable performance degradation from the alignment padding revision.
