### ISSUE TITLE
Verify that compress works with envelope reduction branch 

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#38]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/38*

---
Consult Lukasz regarding envelope reduction branch.

test merge with compression
g/envelope-reduction

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-02-08 22:13:27*

---
I tested persistent pingpong with message reduction and compression. It works fine

**Comment by PhilMiller** [comment]
*Original date: 2013-02-08 22:31:00*

---
Could we get a test against (your suitably modified version of) NAMD, too, since that actually intends to use this?
