### ISSUE TITLE
PAMI FIFO Size bug for large messages

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#39]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/39*

---
Connected to rendezvous issues, but can occur independently.

Workaround is to increase environment variable, 

for many small msgs:
for large msgs: 

Add text to our error output describing env variables.

Add ENV to release notes.

**Comment by PhilMiller** [comment]
*Original date: 2013-02-13 17:29:54*

---
Descheduling from 6.5 release because the pamilrts build seems to be sufficiently stable

**Comment by nikhil-jain** [comment]
*Original date: 2013-02-25 21:51:56*

---
Added the warning to src code. Added the note in release notes.
