### ISSUE TITLE
Message logging does not work with flag --with-production

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#395]
*Original author: Esteban Meneses*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/395*

---
A memory violation error appears during checkpoint with message logging (causalft) if the flag --with-production is used to build charm:

*** glibc detected *** /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d: munmap_chunk(): invalid pointer: 0x0000000000890570 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7ffff7282b96]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z26garbageCollectMlogForCharePvP13ChareMlogData+0x7c)[0x502d4c]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z14forAllCharesDoPFvPvP13ChareMlogDataES_+0x1e8)[0x507de8]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_ZN9CentralLB13ProcessAtSyncEv+0x32)[0x519182]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d[0x4855cd]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z15_processHandlerPvP11CkCoreState+0xa72)[0x4880e2]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(CsdScheduleForever+0x68)[0x538888]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(CsdScheduler+0x2d)[0x538b6d]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(ConverseInit+0xb56)[0x537066]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(main+0x27)[0x46ec27]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7ffff722576d]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d[0x46f341]
======= Memory map: ========
00400000-005ac000 r-xp 00000000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007ab000-007ac000 r--p 001ab000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007ac000-007bd000 rw-p 001ac000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007bd000-01069000 rw-p 00000000 00:00 0                                  [heap]
7ffff507c000-7ffff7204000 rw-p 00000000 00:00 0 
7ffff7204000-7ffff73b9000 r-xp 00000000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff73b9000-7ffff75b9000 ---p 001b5000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75b9000-7ffff75bd000 r--p 001b5000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75bd000-7ffff75bf000 rw-p 001b9000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75bf000-7ffff75c4000 rw-p 00000000 00:00 0 
7ffff75c4000-7ffff75d9000 r-xp 00000000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff75d9000-7ffff77d8000 ---p 00015000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77d8000-7ffff77d9000 r--p 00014000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77d9000-7ffff77da000 rw-p 00015000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77da000-7ffff78d5000 r-xp 00000000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff78d5000-7ffff7ad4000 ---p 000fb000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad4000-7ffff7ad5000 r--p 000fa000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad5000-7ffff7ad6000 rw-p 000fb000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad6000-7ffff7bbc000 r-xp 00000000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7bbc000-7ffff7dbb000 ---p 000e6000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dbb000-7ffff7dc3000 r--p 000e5000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dc3000-7ffff7dc5000 rw-p 000ed000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dc5000-7ffff7dda000 rw-p 00000000 00:00 0 
7ffff7dda000-7ffff7dfc000 r-xp 00000000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7fab000-7ffff7fd1000 rw-p 00000000 00:00 0 
7ffff7fd7000-7ffff7ffb000 rw-p 00000000 00:00 0 
7ffff7ffb000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00022000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7ffd000-7ffff7fff000 rw-p 00023000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
------------- Processor 4 Exiting: Caught Signal ------------
Signal: unknown signal
------------- Processor 3 Exiting: Caught Signal ------------
Signal: segmentation violation
Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
------------- Processor 0 Exiting: Caught Signal ------------
Signal: segmentation violation
Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
*** glibc detected *** /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d: munmap_chunk(): invalid pointer: 0x00000000010a4aa0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7ffff7282b96]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z26garbageCollectMlogForCharePvP13ChareMlogData+0x7c)[0x502d4c]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z14forAllCharesDoPFvPvP13ChareMlogDataES_+0x1e8)[0x507de8]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_ZN9CentralLB13ProcessAtSyncEv+0x32)[0x519182]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d[0x4855cd]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(_Z15_processHandlerPvP11CkCoreState+0xa72)[0x4880e2]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(CsdScheduleForever+0x68)[0x538888]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(CsdScheduler+0x2d)[0x538b6d]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(ConverseInit+0xb56)[0x537066]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d(main+0x27)[0x46ec27]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7ffff722576d]
/scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/./jacobi3d[0x46f341]
======= Memory map: ========
00400000-005ac000 r-xp 00000000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007ab000-007ac000 r--p 001ab000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007ac000-007bd000 rw-p 001ac000 08:06 8263749                            /scratch/autobuild/net-linux-x86_64-causalft/charm/net-linux-x86_64-causalft/tests/charm++/jacobi3d/jacobi3d
007bd000-01379000 rw-p 00000000 00:00 0                                  [heap]
7ffff507c000-7ffff7204000 rw-p 00000000 00:00 0 
7ffff7204000-7ffff73b9000 r-xp 00000000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff73b9000-7ffff75b9000 ---p 001b5000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75b9000-7ffff75bd000 r--p 001b5000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75bd000-7ffff75bf000 rw-p 001b9000 08:01 1181202                    /lib/x86_64-linux-gnu/libc-2.15.so
7ffff75bf000-7ffff75c4000 rw-p 00000000 00:00 0 
7ffff75c4000-7ffff75d9000 r-xp 00000000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff75d9000-7ffff77d8000 ---p 00015000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77d8000-7ffff77d9000 r--p 00014000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77d9000-7ffff77da000 rw-p 00015000 08:01 1186099                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ffff77da000-7ffff78d5000 r-xp 00000000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff78d5000-7ffff7ad4000 ---p 000fb000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad4000-7ffff7ad5000 r--p 000fa000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad5000-7ffff7ad6000 rw-p 000fb000 08:01 1181213                    /lib/x86_64-linux-gnu/libm-2.15.so
7ffff7ad6000-7ffff7bbc000 r-xp 00000000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7bbc000-7ffff7dbb000 ---p 000e6000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dbb000-7ffff7dc3000 r--p 000e5000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dc3000-7ffff7dc5000 rw-p 000ed000 08:01 860107                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
7ffff7dc5000-7ffff7dda000 rw-p 00000000 00:00 0 
7ffff7dda000-7ffff7dfc000 r-xp 00000000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7fab000-7ffff7fd1000 rw-p 00000000 00:00 0 
7ffff7fd7000-7ffff7ffb000 rw-p 00000000 00:00 0 
7ffff7ffb000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00022000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffff7ffd000-7ffff7fff000 rw-p 00023000 08:01 1181215                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
------------- Processor 2 Exiting: Caught Signal ------------
Signal: unknown signal
[3] Stack Traceback:
  [3:0] +0x364a0  [0x7ffff723a4a0]
  [3:1] CmiFree+0xd  [0x53966d]
  [3:2] _Z26garbageCollectMlogForCharePvP13ChareMlogData+0x7c  [0x502d4c]
  [3:3] _ZN13ElementCaller11addLocationER10CkLocation+0x61  [0x50fa91]
  [3:4] _ZN8CkLocMgr7iterateER13CkLocIterator+0x67  [0x49a077]
  [3:5] _Z14forAllCharesDoPFvPvP13ChareMlogDataES_+0x789  [0x508389]
  [3:6] _ZN9CentralLB13ProcessAtSyncEv+0x32  [0x519182]
  [3:7]   [0x4855cd]
  [3:8] _Z15_processHandlerPvP11CkCoreState+0xa72  [0x4880e2]
  [3:9] CsdScheduleForever+0x68  [0x538888]
  [3:10] CsdScheduler+0x2d  [0x538b6d]
  [3:11] ConverseInit+0xb56  [0x537066]
  [3:12] main+0x27  [0x46ec27]
  [3:13] __libc_start_main+0xed  [0x7ffff722576d]
  [3:14]   [0x46f341]
Fatal error on PE 3> segmentation violation
Command exited with non-zero status 1
0.06user 0.10system 0:11.95elapsed 1%CPU (0avgtext+0avgdata 20112maxresident)k

**Comment by xiangni** [comment]
*Original date: 2015-02-09 20:41:46*

---
Locate the crash happened when trying to delete envelops, still looking at how that happens.

**Comment by xiangni** [comment]
*Original date: 2015-02-10 06:18:22*

---
The crash is due to one flag in the envelop is not initialized correctly. Message logging use a field "flags" to identify whether to free the message being sent or not, since that field is not being initialized, sometimes the sending messages are freed silently. Will push the fix soon.

**Comment by xiangni** [comment]
*Original date: 2015-02-10 20:03:33*

---
http://charm.cs.uiuc.edu/gerrit/#/c/516/
