### ISSUE TITLE
CmiOneSided on Cray GNI (Gemini, Aries/Cascade)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#4]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/4*

---
Make CmiDirect work on Gemini/uGNI.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-22 01:22:12*

---
Eric: With less than a month to go before SC and your focus on MIC, I suspect this isn't going to happen for this release. Would you like to push it back? Alternately, if MIC support won't be production-grade by the release, perhaps a quick effort on this would be more immediately beneficial?

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 16:32:31*

---
The CmiDirect API should be discontinued. It has several issues which make it difficult to use, or even potentially invalid.  The use of the last byte to detect message completion of a put is only correct if ordering is enforced by the protocol below.  That is not semantically guaranteed in VERBS, though it does work in some implementations.  CmiDirect has no provisions at all for object migration, or fault handling.  No generic (no RMDA) implementation exists, therefore applications which use CmiDirect must have an alternate Charm message implementation #ifdefd in to handle the common case.  CmiDirect was an experimental prototype to study application level use of RDMA in Charm++, it succeeded insofar as it indicated that RDMA at the application level is worth pursuing.  However, it is not appropriate as an ongoing part of the Charm++ API.

Therefore, I am renaming this issue.  What we should be doing is getting the newer API,  CmiOneSided, into production capability.  Pritish and I designed it to address those concerns and to match the LRTS RDMA.  Unlike CmiOnesided, it has a generic implementation which can work on any message layer without RDMA support.  That implementation is on the remotes/origin/jetley/cmionesided branch.  I will extend it to use RDMA on the Cray as a demonstration to satisfy this bug.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 23:24:07*

---
With the new zero-copy support going in, it would seem that this is now moot. Reject, along with #652?
