### ISSUE TITLE
Report PAMI large/many msgs  issue to IBM

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#40]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/40*

---

Investigate possibility of a check with appropriate error condition to be emitted from SPI or PAMI.
Submit small example code to get this put into the IBM bug system.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-03 03:22:25*

---
Has this actually been passed along to IBM? If so, is there any update from them on when/how it will be addressed?

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-09 15:53:19*

---
Informal response was to handle it via the RTS and environment. Added those to the crash code.
