### ISSUE TITLE
megatest crashes on CrayXC30 

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#401]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/401*

---
multisectiontest crashed on crayxc30 using 144 cores.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-26 04:45:36*

---
Cray XE and XC is using exactly same machine code and configurations. 

Megatest on CrayXE works fine. 

Megatest on XC smp works fine. However, it does not work with non smp using more than 96 cores.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-28 19:58:57*

---
This may be purely a result of stuff exhibited in #259. We should investigate and see if that's the case before releasing. If we're just dealing with that, then I'd say defer.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-29 05:11:48*

---
I tracked the problem to be 'CmiOutofMemory' because one CmiAlloc tries to ask for negative bytes 

However, I do not know why this happens yet

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-29 05:24:03*

---
Sender size sets msg size to a correct number. However, on receiving side, this message size is a negative number.  It seems during message transferring, data is corrupted.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-30 20:46:10*

---
On Edison, megatest fails because of multi multisection, it fails at assertion iterations number. 
Otherwise, megaton, namd runs fine on Edison 

On Cray internal machine (swan), megacon fails due to received small message is corrupted. NAMD totally crashed. 

I compared the modules, uGNI, udreg, PMI, cray machine has newer version than Edison.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-30 20:49:55*

---
With just those three modules being newer on Swan, it should be straightforward to see which update leads to the misbehavior (assuming the Edison versions are available and mutually compatible), and give Cray the narrowed diagnosis before they ship that code to customer sites.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-30 20:51:52*

---
Reply to Phil : I can not find the older version on Swan same with that on Edison

**Comment by PhilMiller** [comment]
*Original date: 2014-01-30 20:52:50*

---
Does Edison maybe have the newer versions installed but non-default?

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-01-30 20:56:52*

---
I am wrong. It is actually opposite. Edision has newer version than Swan
The one on Swan is something like 7836. The one on Edison is 8253 (by default)

**Comment by PhilMiller** [comment]
*Original date: 2014-02-09 22:16:52*

---
Have we concluded that this is a system configuration / version problem, rather than one in our code? Is this causing practical impediments to users that we are in a position to fix?
