### ISSUE TITLE
charmrun_abort should print partition ID in partitioned runs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#405]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/405*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 22:56:21*

---
As part of your new charmrun maintainership.

**Comment by pplimport** [comment]
*Original author: Vipul Harsh*
*Original date: 2016-02-15 17:34:53*

---
Already been merged earlier : ~~https://charm.cs.illinois.edu/gerrit/#/c/113/~~ https://github.com/UIUC-PPL/charm/commit/2c0538b4a3c4190d117782234092b7b3d33ac577

**Comment by PhilMiller** [comment]
*Original date: 2016-02-15 17:36:26*

---
Assign back to Yanhua for attribution sake

**Comment by PhilMiller** [comment]
*Original date: 2016-02-18 04:33:11*

---
Fix was actually merged before 6.7.0.
