### ISSUE TITLE
Limit output during Charm build (i.e. 'quiet' build)

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#408]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/408*

---
Currently, during building Charm, almost everything is dumped onto stdout, which may not be necessary. Instead, we can limit what is directed to stdout and print useful info that may help user; rest can go to a log file.

**Comment by ericjbohm** [comment]
*Original date: 2017-10-25 18:31:04*

---
already implemented as --quiet.  Unclear that this should be made a default.
