### ISSUE TITLE
ChaNGa error: Cannot insert array element twice

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#410]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/410*

---
Tom was occasionally getting the following error on restarts on BlueWaters:

Charm++> Running in SMP mode: numNodes 2048,  31 worker threads per
process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.6.0-rc1-15-gf226754
CharmLB> Load balancer assumes all CPUs are same.
CharmLB> Load balancing instrumentation for communication is off.
Charm++> Running on 2048 unique compute nodes (32-way SMP).
Main(CkMigrateMessage) called
[0]CkRestartMain done. sending out callback.
[0] CmiAbort: Cannot insert array element twice!
ChaNGa version 2.0, commit 6ee40d5
Restarting at 1459
aborting job:
Cannot insert array element twice!

This is a job he has been restarting for about 100 times now (its been
running over the past month) this error just started happening recentl.

**Comment by harshithamenon** [comment]
*Original date: 2014-02-04 04:05:34*

---
Tom mentioned that this is hard to reproduce.

**Comment by harshithamenon** [comment]
*Original date: 2014-02-04 22:27:42*

---
This happens during checkpoint restart from the checkpoint log.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-12 21:04:17*

---
Fix merged. Test and close? Retargeted to 6.6.0 since we have a fix. Brought #437 to attention.

**Comment by harshithamenon** [comment]
*Original date: 2014-03-12 21:08:58*

---
Since I was not able to reproduce the problem on Tom's runs (since the checkpoint changed), I created the scenario where this would happen and tested the fix against that.
