### ISSUE TITLE
multicore-linux-arm7 port

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#411]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/411*

---
There is a net-linux-arm7-smp port already, so multicore-linux-arm7 should be a simple extension.
This would be useful for some ARM/CUDA performance and power testing we're doing this week.
Can test on cupertino.ks.uiuc.edu.

[multicore-arm7.patch](https://github.com/UIUC-PPL/charm/files/3536430/multicore-arm7.patch.txt)

**Comment by jcphill** [comment]
*Original date: 2014-02-05 17:15:57*

---
It looks like net-linux-arm7-smp does not launch a comm thread when in standalone mode.  Is this true?  If so priority can be reduced.

**Comment by ericjbohm** [comment]
*Original date: 2014-02-11 20:19:25*

---
Committed as http://charm.cs.illinois.edu/gerrit/70

**Comment by PhilMiller** [comment]
*Original date: 2014-02-11 20:33:25*

---
Jim, please confirm that this works and close the issue.

**Comment by jcphill** [comment]
*Original date: 2014-02-13 04:50:19*

---
Fails in megatest 10.  (net-linux-arm7-smp passes.)

```
tegra-ubuntu:~/feb2014/charm/multicore-arm7/tests/charm++/megatest> ./pgm +p4
Charm++: standalone mode (not using charmrun)
Converse/Charm++ Commit ID: v6.6.0-rc1-65-g32f1f5e
Warning> Randomization of stack pointer is turned on in kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try run with '+isomalloc_sync'.  
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes.
Charm++> cpu topology info is gathered in 0.060 seconds.
Megatest is running on 1 nodes 4 processors. 
test 0: initiated [groupring (milind)]
test 0: completed (0.10 sec)
test 1: initiated [nodering (milind)]
test 1: completed (0.00 sec)
test 2: initiated [varsizetest (mjlang)]
test 2: completed (0.00 sec)
test 3: initiated [varsizetest2 (phil)]
test 3: completed (0.00 sec)
test 4: initiated [varraystest (milind)]
test 4: completed (0.00 sec)
test 5: initiated [groupcast (mjlang)]
test 5: completed (0.01 sec)
test 6: initiated [groupmulti (gengbin)]
test 6: completed (0.00 sec)
test 7: initiated [groupsectiontest (ebohm)]
test 7: completed (0.00 sec)
test 8: initiated [multisectiontest (ebohm)]
test 8: completed (0.03 sec)
test 9: initiated [nodecast (milind)]
test 9: completed (0.00 sec)
test 10: initiated [synctest (mjlang)]
*** longjmp causes uninitialized stack frame ***: ./pgm terminated
Abort
```

**Comment by PhilMiller** [comment]
*Original date: 2014-02-13 04:53:59*

---
Eric, Jim, please both post the `build` commands used leading up to your respective `make test` results. This is a pretty stark discrepancy.

**Comment by jcphill** [comment]
*Original date: 2014-02-13 04:55:51*

---
    11  20:50   ./build charm++ multicore-arm7 --no-build-shared --with-production
    21  22:18   ./build charm++ net-linux-arm7-smp --no-build-shared --with-production

**Comment by PhilMiller** [comment]
*Original date: 2014-02-17 05:36:11*

---
I'm inclined to say that this shouldn't block the 6.6.0 release. It's new, non-critical functionality appearing late in the cycle. If we get it stabilized before 6.6.0 is finalized, great. If not, it can go in 6.6.1.

**Comment by jcphill** [comment]
*Original date: 2014-02-17 16:51:28*

---
Changing CMK_THREADS_USE_JCONTEXT to 0 fixes this.

**Comment by jcphill** [comment]
*Original date: 2014-02-18 19:20:02*

---
Bump. Can someone please integrate this?

**Comment by ericjbohm** [comment]
*Original date: 2014-02-18 19:43:20*

---
That patch solves the problem in megatest, but still crashes in megampi.  Wierdly, this problem doesn't arise in net-linux-arm7-smp.  That means that thread migration isn't working correctly in multicore-arm7.  Given that NAMD doesn't need thread migration, we can probably go ahead with this.

**Comment by jcphill** [comment]
*Original date: 2014-02-18 20:04:54*

---
How do you migrate threads in multicore when there's only one memory space?

**Comment by jcphill** [comment]
*Original date: 2014-02-18 20:06:05*

---
Nevermind. I guess you migrate between stacks on different pthreads.

**Comment by nikhil-jain** [comment]
*Original date: 2014-02-19 21:48:20*

---
I recommend testing threading using OS's "context".

**Comment by PhilMiller** [comment]
*Original date: 2014-06-23 19:31:18*

---
Accidentally mass-closed. There are known stability issues on all the ARM ports, so this shouldn't be closed.
