### ISSUE TITLE
Remove unused delta log scheme from trace-projections

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#417]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/417*

---
Generally signaled by "if (deltaLog) {"  this is a totally unused feature which probably never worked correctly.

Remove it.

**Comment by rbuch** [comment]
*Original date: 2014-02-15 00:23:38*

---
Implemented and pushed.  Awaiting code review.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 04:52:02*

---
~~https://charm.cs.illinois.edu/gerrit/84~~ https://github.com/UIUC-PPL/charm/commit/03fe04f41cdddada645ec21d1fb72abeb1a0e892
