### ISSUE TITLE
There are too many never used components in the default build

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#419]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/419*

---
This is a problem you really notice if you build on arm7, but it is generally poor practice to keep so much cruft in the default setup.

A example would be the 15 Grid*LB files, but I'm quite certain that a lot of other dead code lurks in the load balancers and elsewhere.  We should get rid of this stuff for 6.7.0

**Comment by harshithamenon** [comment]
*Original date: 2014-02-17 21:09:50*

---
The LBs that are most likely to be used and covering centralized, distributed and hierarchical schemes.

RotateLB (for debugging)
GreedyLB, RefineLB (balance computation load)
ScotchLB, MetisLB (communication aware)

HybridLB (hierarchical)

DistributedLB (distributed)

**Comment by ericjbohm** [comment]
*Original date: 2014-04-03 23:22:56*

---
Just addressing the too many load balancers problem turned out to be more involved than I expected it to be.  

Sifting through the morass of accumulated load balancers for the few that are used regularly was only the beginning.  

An intermediate version of building only a few balancers, now CommonLB, made it more awkward to build the more obscure LBs. That led to a clear desire for having a way to cleanly build only MetisLB, or ScotchLB (or xxxxLB).  Implementing that revealed a 3 year old hack.  That hack created empty scotch and metis headers for the sake of fooling make dependency checking when scotch and/or metis weren't available.  That turned out to be necessary only because our source files are using #include "metis.h" when they should be using #include <metis.h> to rely on searching include paths for headers falling outside our immediate source tree.  Using angle brackets there allows gcc -MM to do the right thing for such cases.
