### ISSUE TITLE
Large TLS segments cause crashes on Cray XE (exposed by AMPI using TLS for privatization)

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#42]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/42*

---
Memory incompatibility with large TLS > 64k. 

Bug reported to Cray and being worked on by them.

From email:
"Updated    2/6/2013 3:46:40 PM
Comment    After a little more digging, I discovered this doesn't have anything to do with MPI at all. The following code fails on compute nodes, but not service nodes:

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <pthread.h>

#define SIZE 800000
#define PATH_MAX 65536

__thread int globalbuf[SIZE] = {1} ;

void *work(void *thread_id)
{
char buf[PATH_MAX];

snprintf(buf, PATH_MAX, "hello, world!");

printf("%s\n", buf);

pthread_exit(NULL);
}

int main(void)
{
pthread_t thread;
long t = 0;

pthread_create(&thread, NULL, work, (void*)t);

sleep(2);

printf("exiting main\n");

pthread_exit(NULL);
}

mork tests/793540> cc -o test test.c
mork tests/793540> aprun -n 1 ./test
Application 10215948 exit signals: Segmentation fault
Application 10215948 resources: utime ~0s, stime ~0s
mork tests/793540> ./test
hello, world!
exiting main
mork tests/793540>

Reducing the value of SIZE allows it to execute successfully on compute nodes.

I used snprintf and a 64K buffer here because that's what was eventually getting tripped up in MPI. "

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 19:57:20*

---
Clarify subject

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 19:57:58*

---
As Celso reported, Cray has a workaround, setting _stack size_ (not memory usage) ulimit to some large but finite value, and is working on a proper solution.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-17 21:52:54*

---
Celso is tracking this with Cray, so assign it to him.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 22:26:58*

---
Set as Upstream so it's clear that this isn't a problem to be fixed in our code.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-03 03:30:09*

---
Has Cray reported any progress on a fix for this issue?

**Comment by pplimport** [comment]
*Original author: Celso Mendes*
*Original date: 2013-05-03 04:30:07*

---
Cray had responded that they are providing a new option (new env.var) to handle this, in a new CLE. So, they are keeping the bug as "Resolved" but still Open, such that it will be closed only after the new CLE is shipped. I suspect this will happen sometime in the Summer.

**Comment by rbuch** [comment]
*Original date: 2016-03-08 20:25:58*

---
Does this issue still exist?

**Comment by stwhite91** [comment]
*Original date: 2016-09-29 03:38:34*

---
This seems to have been taken care of by Cray sometime in the past 3 years. It's not an issue on Edison or Blue Waters now.
