### ISSUE TITLE
PXSHM: use external information instead of +nodesize runtime argument

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#420]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/420*

---
No body.

**Comment by ericjbohm** [comment]
*Original date: 2014-03-03 17:26:18*

---
pxshm needs to be debugged before we can make it a default, or integrate it with smp.  My explorations have revealed the following issues:

1. net-linux-x86_64-pxshm builds (--with-production) hang in megatest when run with +nodesize 4, on newer platforms (like prudence and my charmworks laptop).  Runs fine on older machines like intellect.
1. netlrts never absorbed pxshm properly.  Currently netlrts-pxshm fails to compile.
1. The definitions for the fence operations are weird (looks like cross pollination poisoning from xpmem implementation) in that they aren't consistent with the definitions in machine-smp.c by taking two parameters that are always set to 0.  
## in a pxshm-smp build you can just nuke the definitions in machine-pxshm.c to rely on smp, but megatest will hang even if nodesize is unset, so more work remains to achieve compatibility.
1. If you enable PXSHM_LOCK and add -lpthread to replace those highly suspect fence operations the bug goes away.  Locking seems to perform about as well as the fence scehem for pingpong on newer platforms, not sure about older platforms.  Haven't studied other benchmarks.

Need to unweird the pxshm fence implementation and analyze it for its correctness failing.

I'm inclined to switch to locking to future proof the implementation against the idiosyncracies of architecture specific fence semantics, but the situation requires more study.

**Comment by PhilMiller** [comment]
*Original date: 2015-04-14 20:59:40*

---
A few notes since the last updates:
1. As discussed in a core meeting recently, the fix for this should be much easier to add in charmrun or other machine-layer startup code that knows and uses the rank-node mapping than later on. I've CC'ed Ralf because he's been working on charmrun a fair bit lately, and adding a "ranks on this host" count should be pretty easy.
2. netlrts-darwin-x86_64-pxshm seems to compile and run just fine, with small changes to remove 'inline' declarations on some functions that might be clang quirks.

**Comment by PhilMiller** [comment]
*Original date: 2015-04-30 18:25:35*

---
Ralf has this working for net & netlrts via charmrun, and so verbs will be straightforward as well.

GNI needs an implementation, which should be a matter of munging the right data from PMI.

MPI is probably irrelevant, since when we're running on MPI, it should take care of communicating efficiently between processes, by whatever mechanism. The only instance of mpi-*/conv-mach-pxshm I see is on mpi-darwin-x86_64 that was copied from net-darwin-x86_64. I'll delete that.

**Comment by PhilMiller** [comment]
*Original date: 2015-05-13 18:23:41*

---
All but the GNI implementation have been tested and merged.
