### ISSUE TITLE
Update Metis calls to 5.x in load balancers

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#423]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/423*

---
Metis's stable version is 5.x, while our load balancers use 4.x. Also, if possible, remove extern based use of Metis functions in some LBs. Extern prevents compiler checking, and hence an API mismatch is not detected.

**Comment by nikhil-jain** [comment]
*Original date: 2014-02-22 17:44:48*

---
Marking it 6.6 but not sure.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-10 22:45:58*

---
My understanding of this issue's present status is that a few LB strategies have been updated to the METIS 5.x API, but several others have not. Is that correct?

**Comment by harshithamenon** [comment]
*Original date: 2014-04-10 22:48:31*

---
Thats right. Key ones which are used have been converted to Metis 5.x whereas others will work with older version on Metis.
