### ISSUE TITLE
_sendStats() during CkExit() sends per-pe messages to pe 0

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#425]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/425*

---
Calling CkExit() on, e.g., 240,000 cores of Blue Waters, yields the following error:

WallClock: 251.544098  CPUTime: 251.544098  Memory: 7621.382812 MB
------------- Processor 240000 Exiting: Called CmiAbort ------------
Reason: GNI_RC_CHECK
charm> Please use +useRecvQueue 327680 in your command line, if the error comes again, increase this number
[240000] Smsg_rx_cq full; err=GNI_RC_ERROR_RESOURCE
aborting job:
GNI_RC_CHECK

This is almost certainly due to _sendStats(), which bombards pe 0 with one message per pe rather than using a reduction tree, all to pass it to _printStats(), which is a no-op unless CMK_WITH_STATS && ( _printSS || _printCS ).

static inline void _sendStats(void)
{
  DEBUGF(("[%d] _sendStats\n", CkMyPe()));
#if CMK_WITH_STATS
  envelope *env = UsrToEnv(CkpvAccess(_myStats));
#else
  envelope *env = _allocEnv(StatMsg);
#endif
  env->setSrcPe(CkMyPe());
  CmiSetHandler(env, _exitHandlerIdx);
  CmiSyncSendAndFree(0, env->getTotalsize(), (char *)env);
}

The expedient fix is to not send these messages at all unless they will actually be printed.

**Comment by jcphill** [comment]
*Original date: 2014-03-04 20:27:54*

---
Anyone planning to fix this?

**Comment by nikhil-jain** [comment]
*Original date: 2014-03-04 20:34:41*

---
Assigned to Yanhua based on NAMD meeting minutes.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-19 23:03:26*

---
Have we concluded that the implemented fix is sufficient? If so, let's close this.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-24 19:44:53*

---
Will duplicate to change the stats-enabled case to use a reduction.
