### ISSUE TITLE
message copy performance on BGQ

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#426]
*Original author: Ehsan Totoni*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/426*

---
AMPI intra-node message passing is very slow on BGQ because there are memory copies involved. Charm++ can also be slow because of copies. Memory alignment could be the cause but various tests failed.

**Comment by nikhil-jain** [comment]
*Original date: 2014-03-05 16:31:40*

---
More info at https://charm.cs.illinois.edu/private/tms/listlog.php?param=296

**Comment by PhilMiller** [comment]
*Original date: 2014-03-26 19:57:20*

---
IBM documents their vector intrinsic routines here: http://pic.dhe.ibm.com/infocenter/compbg/v121v141/index.jsp?topic=%2Fcom.ibm.xlf141.bg.doc%2Flanguage_ref%2Fvmxintrinsics.html
The ones most specifically useful for implementing an unaligned memcpy are probably among sldw, perm, gpci, insert, lvsr, lvsl, and of course ld and st.

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-26 05:22:21*

---
Assigning it to Ehsan since he has a patch checked in for this.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2015-01-26 19:46:29*

---
ALIGN_BYTES is 8 or 16 bytes by default now.
