### ISSUE TITLE
Charmrun socket errors could be made more meaningful

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#427]
*Original author: Abhishek Gupta*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/427*

---

Some Charmrun errors such as 

```
Charmrun: error on request socket-- Socket closed before recv.
```

could be made more meaningful. Many times, it means that a node died, but is it possible to report which node died, ideally with a hostname?  This would be useful in tracking down repeatable errors due to faulty hardware.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 22:19:43*

---
~~https://charm.cs.illinois.edu/gerrit/670~~ https://github.com/UIUC-PPL/charm/commit/8ec1f214fad8678d821fc2314c103b5183db4ddf was merged.
