### ISSUE TITLE
bgtest targets should fail when run on non-bigsim builds

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#429]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/429*

---
Many pieces of code run by `make bgtest` will work incorrectly in inscrutable ways if run on a build of the runtime without emulation support enabled. They should fail noisily in that case, not behave erratically.

**Comment by ericjbohm** [comment]
*Original date: 2015-01-27 21:11:38*

---
I've looked at a few different ways to determine if we're in a BigSim build, or not.  Various library symbol tests are possible, but the cross platform portability of tools like nm is somewhat questionable. 

One approach would be to add CmiArg processing to abort when BigSim arguments are passed to a non-BigSim build.  

Downside: this is an ugly solution in that it is definitely weird to add arguments which result in an abort whenever they are present.  It also prevents us from using those arguments for some non-BigSim purpose, or being compatible with something else in the toolchain which would desire to do so.  It has the advantage of being relatively simple to implement.

An alternate avenue is a Make based test of execution testing for the _BG> BigSim emulator shutdown gracefully!_ message that the simulator throws on stderr.  As shown below.  This approach has pretty light platform requirements (shell support, pipe composition, stream redirection and grep) that I believe are already in the requirements necessary to build charm.  It correctly fails in a non-bigsim build. It will also fail if bigsim would fail to get far enough to output its termination line, which is correct.

Downsides: One annoying downside of this approach is that it adds the execution time of however long the test would take without arguments.  This is quite variable, as some tests will abort without arguments, while others will soldier on with minimally functional defaults.  It also requires a change to all of the individual test makefiles, though the _nm_ solution would have the same issue.

```

isBigSimTest: 
	if ! ./charmrun ./pgm 2>&1 | grep '^BG> BigSim' 2>&1 > /dev/null; then  echo "bgtest invalid, not a BigSim build"; exit 2; fi
BG> BigSim emulator shutdown gracefully!

bgtest: isBigSimTest all

```

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 19:56:21*

---
This is one example for the class of bugs in 654

**Comment by epmikida** [comment]
*Original date: 2015-02-10 17:38:53*

---
This bug was resolved by the fix for bug 654. Now there will be warnings printed out when attempting to use big sim params in a non-bigsim build.
