### ISSUE TITLE
Upgrade to ptmalloc version 3

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#430]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/430*

---
Needed for correct license.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-17 23:15:09*

---
Michael was tasked to test the specialized modes, and said it would be done in the next couple days.

**Comment by mprobson** [comment]
*Original date: 2014-03-20 17:56:54*

---
(for posterity)
Tested to ensure new malloc implementation did not break old memory modules:
Tested
-paranoid (good)
-leak (good - needs manual writeup)
-verbose (busted, but not by this)
-charmdebug (busted, but not by this)
Nikhil Tested
-isomalloc
-gnu
Untested (unchanged)
-default/os
