### ISSUE TITLE
Cray XC30 report BI error

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#432]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/432*

---
Sarah Anderson from Cray reported that on Cray XC30 there is no bandwidth injection control, Charm++ throws error pint message. 
Error, unable to retrieve BI config, rc=2
Error, unable to set BI config, rc=2

**Comment by PhilMiller** [comment]
*Original date: 2014-03-17 18:57:18*

---
-Does this actually prevent execution, or is it just an ugly error message that shouldn't be coming out?-

Edit: I can't even find references in the code base to the code in `src/util/ckBIconfig.h` that emits this. It does answer my question, though, which is that the error should be harmless.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-03-17 19:00:00*

---
It is just a error print. It looks ugly.

**Comment by ericjbohm** [comment]
*Original date: 2014-03-17 19:04:07*

---
I don't have access to an XC30 to reproduce this bug, but there is a charm configure time test for BI which could be modified to fail on XC30.  Then this should no longer be an issue.  Not sure why Cray is providing enough API for the test to pass when it isn't supported, but I suppose they have their reasons.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-10 23:09:46*

---
This now at least only prints from PE 0, per http://charm.cs.uiuc.edu/gerrit/#/c/162

**Comment by PhilMiller** [comment]
*Original date: 2014-04-11 05:43:36*

---
Shouldn't we not be printing this error at all on XC30, since BI doesn't exist there? I wouldn't call the mitigation an implemented fix.

**Comment by ericjbohm** [comment]
*Original date: 2014-04-11 13:03:16*

---
We don't have a status for "workaround". As I lack access to an XC30, I can't take this much farther.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-11 15:30:38*

---
Would it make sense to just add a flag in our conv-mach.h CMK_CRAY_USE_BALANCED_INJECTION that's 1 on the crayxe builds and 0 on the crayxc builds? If so, I can do that and test it easily enough.

**Comment by ericjbohm** [comment]
*Original date: 2014-04-11 15:34:00*

---
I think that would be sufficient.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-11 16:35:45*

---
http://charm.cs.uiuc.edu/gerrit/#/c/180/
