### ISSUE TITLE
build -debug on Stampede fails with "cannot find -lmodulecharmdebug_python"

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#433]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/433*

---

```

./build charm++ net-linux-x86_64 ibverbs smp iccstatic --no-build-shared --enable-error-checking  --with-prio-type=int -debug

gmake[1]: Entering directory `/home1/00288/tg455591/mar10/charm-6.6.0-rc3/net-linux-x86_64-ibverbs-smp-iccstatic/tmp/charmrun-src'
../../bin/charmc -debug  -Wno-error -lm -I.. -c -seq -DCMK_NOT_USE_CONVERSE=1 -DNOTIFY charmrun.C
../../bin/charmc -debug  -Wno-error -lm -I.. -cp ../../bin -seq -language c++ -o charmrun-notify charmrun.o
icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
ld: cannot find -lmodulecharmdebug_python
Fatal Error by charmc in directory /home1/00288/tg455591/mar10/charm-6.6.0-rc3/net-linux-x86_64-ibverbs-smp-iccstatic/tmp/charmrun-src
   Command icpc -static-intel -o charmrun-notify charmrun.o -L../../bin/../lib -lmodulecharmdebug_python -lmodulePythonCCS -lm -lpython2.6 -lmodulePythonCCS -lmodulecharmdebug_python returned error code 1
charmc exiting...

```

**Comment by jcphill** [comment]
*Original date: 2014-07-06 16:18:53*

---
I'm running into this issue again while trying to debug a segfault. Any ideas?

**Comment by PhilMiller** [comment]
*Original date: 2014-08-03 06:18:51*

---
Ping. Progress on this? Everything else to be fixed for 6.6 has been merged.

**Comment by ericjbohm** [comment]
*Original date: 2014-08-03 12:55:24*

---
Can't get much done over hotel wireless from Puerto Rico.

**Comment by PhilMiller** [comment]
*Original date: 2014-08-04 15:16:03*

---
I just tried to reproduce this, and the exact build command shown runs to completion on Stampede. I also tried adding `module load python` and reran the build, to see if there was a version skew error (2.6 vs 2.7). That build also ran successfully.

Jim: Does this still occur for you?

**Comment by jcphill** [comment]
*Original date: 2014-08-04 22:34:21*

---
I just tested and I still get the error, both with and without the fftw module loaded:

Currently Loaded Modules:
  1) TACC-paths   3) cluster-paths      5) mvapich2/1.9a2   7) TACC
  2) Linux        4) intel/13.0.2.146   6) cluster          8) fftw3/3.3.2

Currently Loaded Modules:
  1) TACC-paths   3) cluster-paths      5) mvapich2/1.9a2   7) TACC
  2) Linux        4) intel/13.0.2.146   6) cluster

login2$ git status
1. On branch charm
nothing to commit (working directory clean)
login2$ git show
commit 7ef40e7d4eca868513ea7d7fb65a5fcfc0d8b625
Author: Ronak Buch <rabuch2`illinois.edu>
Date:   Mon Aug 4 12:02:00 2014 -0500

    Improve grammar in comments

    Change-Id: I1c3e01e366253fc7647b542a2bd302870476ce3d

...

**Comment by PhilMiller** [comment]
*Original date: 2014-08-04 22:47:54*

---
OK, I've reproduced it now, and I think I have a handle on its cause. I'll try to have a patch posted this evening.

**Comment by PhilMiller** [comment]
*Original date: 2014-08-04 23:08:52*

---
Change 342 posted in Gerrit.

The reason I couldn't reproduce this earlier is that parallel compilation, which I assumed was inconsequential, was actually masking the problem. It generally meant that the module in question was built before the linker went looking for it. Really, that module shouldn't be linked into binaries meant to run on the build or run host at all.
