### ISSUE TITLE
Performance regressions in Episimdemics from 6.5-6.6

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#442]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/442*

---
(Separated for work-flow records purposes. EpiSimdemics has been tested to work properly against what we will release as 6.6.0, though possibly with a few percent room for performance improvement.)

From https://charm.cs.illinois.edu/redmine/issues/355#note-9
> 10/8 (0c386c6): 9.67s
> 11/5 (0f6dd83): 9.29s
> 11/8 (9fe3d55): 9.31s
> 11/8 (d06f4e): 9.31s
> 11/9 (4a59427): 9.44s    <---------------- REGRESSION 1.4% [regression may be in ancestor from 8/12 or before that]       *PHIL*
> 11/12 (7ebe67b): 9.25s  [4a59427 is not an ancestor]
> 11/12 (e73dccc): 9.43s   [not a regression - affected by 4a59427]
> 11/13 (797d916): 9.64s  <---------------- REGRESSION 2.2%  [regression goes away when using the flag `-fno-asynchronous-unwind-tables`] *NIKHIL*
> 11/14 (7a3ee37): 9.58s
> 11/14 (b283a8): 9.52s
> 12/6 (211f290): 9.66s
> 12/6 (9bcafc5): 9.87s      <---------------- REGRESSION 2.2%    *JONATHAN*
> 12/10 (d83164): 9.63s    <++++++++++ IMPROVEMENT 2.5% [addresses regression from 12/6?]   *JONATHAN*
> 12/3 (575af7): 9.41s     <++++++++++ IMPROVEMENT 2.3% [causes intermittent hangs!] *GENGBIN*
> 12/31 (72a354): 9.42s
> 12/31 (39db95): 9.60s    <----------- REGRESSION 1.9% *PHIL*
> 12/31 (6b2f7a8): 9.63s    
> 12/20 (3291c16): 9.60s   
> 1/14 (d8c3adf): 9.68s
> 1/16 (967eccd): 9.37s     <++++++++++ IMPROVEMENT 3.2% [reversal of envelope reduction changes]   *ERIC*
> 1/23 (62941b): 9.33s
> 1/23 (afe5e74): 9.35s
> 1/24 (3d170bd): 9.37s
> 1/24 (ddd5cce): 9.63s     <--------------- REGRESSION 2.8% [regression goes away when LB userdata is disabled; 
>                                                             I think it should be disabled by default] *HARSHITHA*
> 1/21 (9e7d57e): 9.61s
> 1/21 (c7b4189): 9.66s
> 1/21 (1af2a73):  9.62s
> 1/28 (cb2ee50): 9.74s     <--------------- REGRESSION 1.2% *PHIL*
> 2/3  (964cbcd): 9.76s
> 2/5  (375b185): 9.95s      <--------------- REGRESSION 1.9% *PHIL*
> 2/11 (b159235): 9.96s
> 2/11 (340161b5): 10.38s  <---------------- REGRESSION 4.2% [TRAM routing refactoring] *LUKASZ*
> 2/12 (c2b6ebfb): 10.37s
> 1/16 (28998a1): 10.27s   <+++++++++++ IMPROVEMENT 1.0%   *PHIL*
> 2/11 (32f1f5): 9.85s         <+++++++++++ IMPROVEMENT 4.1%   *PHIL*
> 2/15 (f8f673): 9.87s
> 2/19 (b670687): 9.85s
> 8/27 (c5c151e): 10.22s    <---------------- REGRESSION 3.8% *PHIL*
> 2/23 (3760b51): 10.22s
> 2/24 (9d06a86): 10.21s   [supposed to turn off LB userdata but performance is not improved]
> 2/24 (8074b89): 9.99s    <++++++++++++ IMPROVEMENT 2.2% *PHIL*
> 3/5  (6c0aea): 10.05s

Several of these have been addressed since that message - see subsequent notes to make updates.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-06-06 04:06:03*

---
There is still about a 10% difference in performance. Latest results from Jae-Seung: 

For CA data
64  {4 4 4 4 3}   596.725 sec
128 {4 4 8 4 3}   305.02 sec
256 {2 4 4 8 4 3} 161.731 sec
512 {4 4 4 8 4 3} 85.6405 sec

which used to be
64  542.067 sec
128 282.912 sec
256 147.323 sec
512 77.7464 sec
for {A, B, C, DE, 4, T/4}

AR
64  {2 4 8 4 3}   51.9871 sec
128 {2 4 4 4 4 3} 28.6399 sec
256 {2 4 4 8 4 3} 15.9834 sec

which used to be
64  47.0806 sec
128 26.0709 sec
256 14.5134 sec
for {A, B, C, DE, 4, T/4}

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2014-11-11 21:57:57*

---
I wrote scripts to automate the tests of commits.

Commit 0c386c6 of charm does not compile.

The actual version of Episimdemics is not compatible with old versions of Charm because of the changes in TRAM. The compilation is okay with some modifications but the execution is wrong. Need to find out what are the needed modifications.

Preliminary results do not show the same results as the previous tests, need to be confirmed.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-01-22 18:50:41*

---
I tested again the commits as done in https://charm.cs.illinois.edu/redmine/issues/355#note-9 and I got these different results:
```
340161b5:  9.816868
c2b6ebfb:  9.82957  (0.13%)
28998a1 :  9.839406 (0.10%)
32f1f5  :  9.753328 (-0.87%)
f8f673  :  9.757676 (0.04%)
b670687 :  9.753116 (-0.05%)
c5c151e : 10.07574  (3.31%) (guilty)
3760b51 : 10.06664  (-0.09%)
9d06a86 : 10.11038  (0.43%)
8074b89 : 10.14918  (0.38%)
6c0aea  :  9.909858 (-2.36%)
1e4d924 :  9.869604 (-0.41%)
cf4f851 : 10.03458  (1.67%) (guilty)
e46f420 : 10.03298  (-0.02%)
792e1a4 : 10.024129 (-0.09%)
5cf5514 : 10.18164  (1.57%) (guilty)
19f3555 : 10.18672  (0.05%)
bf2c9ec : 10.17509  (-0.11%)
80ffb2  : 10.17386  (-0.01%)
ea1ff8  : 10.17716  (0.03%)
726aa86 : 10.07918  (-0.96%)
cefd85b : 10.08894  (0.10%)
8941072 : 10.1116   (0.22%)
55b3f65 : 10.1202   (0.09%)
aa1f1af : 10.11366  (-0.06%)
72f946  : 10.31182  (1.96%) (guilty)
9fa0582 : 10.1635   (-1.44%)
248ac47 :  9.986356 (-1.74%)
6914450 :  9.865496 (-1.21%)
2347d5e :  9.877862 (0.13%)
aefd5c1 :  9.883292 (0.05%)
8742234 : 10.15496  (2.75%) (guilty)
f30ef02 : 10.12824  (-0.26%)
4552527 : 10.13804  (0.10%)
eeb0d58 : 10.02996  (-1.07%)
```


I used "git bisect" to find the guilty commits. I did not try to find (yet) if the performance decrease was justified.

I still have problems with older version, since the TRAM API has changed and I have this error "CqsEnqueueGeneral: invalid queueing strategy".

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-09 19:18:38*

---
c5c151e : 10.07574  (3.31%)
-> CkArrayOptions: missing pup of new 'array bounds' field
Okay.

cf4f851 : 10.03458  (1.67%)
-> Issue: #410. Set the array ifNotThere field in envelop when callback message for an array element is created
Okay.

5cf5514 : 10.18164  (1.57%)
-> Issue #355: Fix a race condition in TRAM initialization
Okay, only during initlialization.

72f946  : 10.31182  (1.96%)
-> extend +pemap notation to interleave hyperthreads, explaination in manual
Okay, only during initlialization.

8742234 : 10.15496  (2.75%)
Bug #445 Remove edges from commData when either the sender or the receiver is not present/deleted
Okay.

So, the performance changes from my comment 5 are justified.

For versions before 340161b5, Episimdemics has to be changed back. After removing SimpleMeshRouter, the compilation is fine.
But when I run it, I have the following error:
"Reason: CqsEnqueueGeneral: invalid queueing strategy.".

**Comment by PhilMiller** [comment]
*Original date: 2016-11-08 21:33:23*

---
There's now a much more intensive effort within the development team to optimize fine-grain application performance. Those efforts are tracked elsewhere, so closing this.
