### ISSUE TITLE
Audit licensing of contributed code

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#444]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/444*

---
Scan your core modules for any third party code and examine the relevant licensing.  Report on what code you find and how its license impacts our Charm++ distribution practices.

Directories listed starting from `src` (everything above/aside is ours).

Fully Checked:
* arch
* QuickThreads
* scripts
* util (except for crc32)
* xlat-i
* xlatcpm
* conv-core
* conv-ccs
* conv-ldb
* conv-perf
* ck-core
* ck-ldb
* ck-cp
* ck-perf
* ck-tune
* langs
* libs

Dirty
* util/crc32
* libs/ck-libs/datatransfer - Poorly written license that doesn't grant what it meant to from defunct Magic Software Company
* `ck-ldb/{tm_*,TreeMatchLB.*}` - questionable, since Jeannot was not working for UIUC. Would need assignment paperwork.
* conv-core/random.c - written by NCSA, so license from University may be fine.

Not fully checked:
* conv-com
* ck-com

**Comment by ericjbohm** [comment]
*Original date: 2014-03-18 22:26:49*

---
No licensing issues found in Rth, Verbs, One-sided, bigsim, bignetsim.

Pami code has contributions from a third party (IBM), but they are not claimed under a licensing agreement distinct from the general one for Charm.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-19 19:59:27*

---
No issues in charmxi, charmc, QD, MSA, build, or tcharm. Added column on module ownership page to record this more succintly: https://wiki.engr.illinois.edu/display/ppl/Software+Module+Ownership

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-03-21 01:20:06*

---

No issues in net, charmrun, and ccs.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2014-03-23 16:13:57*

---
No third party code in futures and BigSim.

A minor potential issue: BigSim uses the obsolete name "BlueGene" for some files and routines.

I assume the default parameters do not violate IBM's NDAs since they had been in the public repository for a long time.

**Comment by bilgeacun** [comment]
*Original date: 2014-03-23 21:25:47*

---
*CharmDebug:* Gdb can be attached to PE's in CharmDebug. Gbd is under GPL licensing, I'm not quite sure about the impact of this.  
*Charj:* (Charj is still distributed in the release.) It uses ANTLR framework for parser generator which has BSD license.

**Comment by harshithamenon** [comment]
*Original date: 2014-03-24 03:46:20*

---
No issues in ldb, seed ldb, reductions, csd or location mgr.

**Comment by nikhil-jain** [comment]
*Original date: 2014-03-24 16:31:20*

---
Updated for pami, mpi, cth, topo, partitions, data transfer,  startup, interop.

**Comment by xiangni** [comment]
*Original date: 2014-03-24 17:46:02*

---
No issues in FT framework.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-03-24 21:18:31*

---
Checked for  gni, lrts, smp, tracing 

lz4 compression algorithm:  BSD 2-Clause License

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2014-03-24 21:27:12*

---
liveViz 
- uses Intel SSE library for SIMD (xmmintrin.h), which is part of GCC, GPL.
- uses osl.h header, of whose origin I could not find. There is only one usage of it, to get the time.
- uses jpeglib, which is available under GPL license
- Open GL, seems to be free from license requirements http://www.opengl.org/about/#11

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-26 04:06:20*

---
I think a significant amount of code in the charm repository is not assigned as a module to anyone. This includes conv-com, ck-com, large chunks of src/util and libs, and various files in all the other directories. In addition, there are the examples, tests, and docs directories.

By the way, ckhashtable.C has the following comment:

This is a simple Hashtable implementation, with the interface shamelessly stolen from java.util.Hashtable.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-26 21:04:01*

---
Akhil Langer wrote:
> liveViz 
> - uses Intel SSE library for SIMD (xmmintrin.h), which is part of GCC, GPL.

xmmintrin.h from GCC explicitly includes a 'GCC Runtime Library Exception' that covers our usage. Other compiler vendors provide their own version of this header, all similarly unrestrictive.

> - uses osl.h header, of whose origin I could not find. There is only one usage of it, to get the time.

I can't find this header. Note that it's only referenced under an #ifdef commented as "serial version". I'll assume "OSL" refers to Orion Sky Lawlor, who authored LiveViz. He authored the including code in 2004, apparently while still at UIUC (commit msg references ongoing thesis work), so we should own it anyway.

> - uses jpeglib, which is available under GPL license

There are two version of libjpeg. The version packaged as `libjpeg8` on Ubuntu 12.04 is available under the *Lesser/Library* GPL, whose licensing terms are not contagious to programs linking against it. The version packaged as `libjpeg62` on Ubuntu 12.04 has more BSD-like terms, with a notice provision saying 

> If only executable code is distributed, then the accompanying documentation must state that "this software is based in part on the work of the Independent JPEG Group"

So, at worst we need to include the notice text when shipping linked binaries.

> - Open GL, seems to be free from license requirements http://www.opengl.org/about/#11

This looks fine.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-02 20:43:05*

---
Checked `src/arch` in full, and all looks reasonably good.

Checked `src/util` in full. Our CRC32 implementation is copied verbatim from a source that does not provide an explicit license we can use. We would need to reimplement afresh, or get an appropriately free implementation of some other checksum algorithm, or simply remove the associated functionality.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 18:45:38*

---
Please review for code that looks like it might night have been written outside of PPL, and Google for original sources. Please also review git logs to look for references to import or copy from elsewhere. Variable and function names typically make good search terms.

Individual assignments from  src/conv-core:


Xiang *done*
cmibacktrace.c
debug-conv.c
debug-conv++.C
debug-conv.h
debug-conv++.h
msgq.h

-Yanhua- Eric Bohm *done*
cmidirect.h
cmidirectmanytomany.h
conv-onesided.c
conv-onesided.h
persistent.h

Eric Mikida *done*
conv-conds.c
convcore.c
cpthreads.c
cpthreads.h
msgcallbacks.c
msgmgr.c

Ronak *done*
conv-config.h
conv-counter.c
conv-cpath.h
cpath.c
cpuaffinity.c
fmain.f90

Nikhil *done*
conv-interoperate.c
conv-ooc.h
conv-qd.h
conv-trace.h
conv-cpm.h
cpm.c

Michael *done*
global-elfcopy.C (no issue)
global-elfgot.C  (no issue)
global-macho.C   (no issue)
global-nop.c     (no issue)
loadsym.c        GNU Lesser GPL v2.1 or later; (C)2001 Victor Zandy <zandy`cs.wisc.edu>

Ehsan *done*
quiescence.c
quiescence.h
random.c
conv-random.h
futures.c

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 18:55:32*

---
Yanhua has been asked to review ck-perf.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 19:12:04*

---
Assignments from src/ck-core:

Akhil *done*
ckobjid.C
ckobjid.h
cksection.h
ckstream.h
cktiming.C
cktiming.h
objid.h

Abhishek *done*
debug-charm.C
debug-charm.h
debug-message.C
readonly.h
register.C
register.h
stats.h
tempo.C
tempo.ci
tempo.h

Bilge *done*
ckarray.C
ckarray.ci
ckarray.h
ckarrayindex.h
ckobjQ.C
ckobjQ.h
modifyScheduler.C
msgalloc.C
ckmarshall.ci
ckmessage.h

Lukasz *done*
charm-api.h
charmf.C
charmf.h
charm.h
charm++.h
ck.C
ck.h
middle-blue.h
middle-conv.h
middle.h
charmmod.f90

Harshitha *done*
ckcallback.C
ckcallback-ccs.h
ckcallback.ci
ckcallback.h
ckdirect.h
ckIgetControl.C
ckIgetControl.h


With this set of assignments, everyone's gotten something from the core to review. I'll start recycling names for libraries and other files.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-04-03 19:32:27*

---
in ck-perf, when we output compressed logs, we need zlib library, which is GPU compatible

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 19:36:53*

---
Assignments from ck-libs

Abhishek *done*
liveViz
liveViz3d
pythonCCS

Akhil *done*
barrier
sparseContiguousReducer
sparseReducer
multicast

Bilge *done*
amr
mblock
pmaf

Ehsan *done*
tmr
TMRC2D
taskGraph

Eric Bohm *done*
pencilfft
fftlib
pose

Harshitha *done*
ckloop
idxl

Michael *done*
fem
-partition.C makes use of metis which is Licensed under the Apache License, Version 2.0 (C) 1995-2013, Regents of the University of Minnesota
ifem   (no issues)
netfem (no issues)
ParFUM 
-parallel_part.c uses ParMetis which has it's own license (C) Regents of the University of Minnesota
-ParFUM_internals includes mpi.h
ParFUM-Iterators
-ParFUM_Iterators.cc includes cuda.h and cuda_runtime.h (unsure of licensing issues)
ParFUM-Tops
-ParFUM_TOPS.cc includes cuda.h and cuda_runtime.h (unsure of licensing issues)
ParFUM-Tops-Dev
-ParFUM_TOPS.cc includes cuda.h and cuda_runtime.h (unsure of licensing issues)

Phil *done*
completion
irecv
armci
boomarray

Xiang *done*
collide

Yanhua
search
state_space_searchengine

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-04-03 19:46:36*

---
state space search engine inside  src/ has no issues.  Example of UTS is using code from other people, copy right by the authors

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 19:53:36*

---
Nikhil: *done*
langs/bluegene

Bilge: *done*
langs/charj

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 19:55:31*

---
Per Yanhua in #444-25, `examples/charm++/state_space_searchengine/UnbalancedTreeSearch_SE/` needs to recover the AUTHORS and LICENSE file from the upstream UTS benchmark reference code. This is the only change necessary to comply with the stated terms of the MIT license.

Yanhua, could you please grab the original benchmark tarball and copy in the license information?

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 20:00:27*

---
Ronak *done*
ck-cp

Eric Mikida
langs/f90charm
langs/jade
langs/pvmc
langs/sdag
langs/simplemsg
langs/streams

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2014-04-03 20:17:52*

---
conv-core/random.c: the whole code is from NCSA.
No other issues in my assignments.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 20:28:15*

---
`libs/{completion,irecv,armci,boomarray}` are all fine once change 159 (BSD-ish license text for ARMCI) gets merge.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 20:39:18*

---
`conv-core/{random.c,conv-random.h}` have no apparent license beyond what the University/NCSA grant us. If the University fully represents NCSA's interest in that code, then we're fine, since they won't sue themself or its own licensees. The clarity of an explicit license would be ideal.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 20:47:54*

---
THe zlib license is wholly unrestrictive, and non-copyleft. GPL-compatible could be a problem for us (since GPL itself would be a problem), but that's not in play here.

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-04-03 20:54:42*

---

LiveViz is already checked by Akhil.
pyhtonCCS looks fine except: In PythonCCS.h

// README: in order for this library to work, there should be a link
// from /usr/include/python to the current python include version

#include "./pythonIncludes.h"

which is a pyhton include file. I suppose there are no problems with Python include file since Python releases are open source and GPL-compatible.

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2014-04-03 20:58:14*

---
Akhil
ckobjid.C - ok
ckobjid.h - ok
cksection.h - ok
ckstream.h - ok
cktiming.C - includes mambo.h which I could not figure out what it is. Also uses papi.h
cktiming.h - ok
objid.h - ok

**Comment by ericjbohm** [comment]
*Original date: 2014-04-03 21:01:34*

---
pencilfft: ok
 (contributed directly by Sameer Kumar, implicitly covered by the general Charm license like the pami machine source)
fftlib: ok
pose: ok

**Comment by ericjbohm** [comment]
*Original date: 2014-04-03 21:03:32*

---
cmidirect.h: ok
cmidirectmanytomany.h: ok
(contributed by Sameer, IBM is fine with this sort of thing)
conv-onesided.c: ok
conv-onesided.h: ok
persistent.h: ok

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2014-04-03 21:13:33*

---
Akhil
barrier: ok
sparseContiguousReducer: ok
sparseReducer - no included files, but some macro defs that need to be checked if they are written by us
multicast:ok

**Comment by PhilMiller** [comment]
*Original date: 2014-04-03 21:16:37*

---
Just a note to everyone: GPL compatibility is neither necessary nor sufficient condition for our needs. You should be noting the exact license involved. You don't need to understand it in detail (I can follow up on them), but I need links or unambiguous names/references.

**Comment by rbuch** [comment]
*Original date: 2014-04-04 19:05:43*

---
My assignments in conv-core and ck-cp all look fine, except for conv-counter.c's inclusion of papi.h.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-04 19:20:47*

---
PAPI is under a 3-clause BSD license, so it's fine.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-04-06 21:57:01*

---
Done with checking these files. The only issue I found is the inclusion of crc32.h in ck.C.

charm-api.h
charmf.C
charmf.h
charm.h
charm++.h
ck.C
ck.h
middle-blue.h
middle-conv.h
middle.h
charmmod.f90

**Comment by harshithamenon** [comment]
*Original date: 2014-04-07 14:50:33*

---
Done checking and no issues found.

ckcallback.C
ckcallback-ccs.h
ckcallback.ci
ckcallback.h
ckdirect.h
ckIgetControl.C
ckIgetControl.h

ckloop
idxl

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-07 15:50:12*

---
langs/bluegene - Clean
Charj - it describes a LICENSE of its own and is based on external BSD entities:

Portions of the Charj grammar are based on a Java 1.5 recognizer by Habelitz Software Developments. This recognizer is available at http://antlr.org/grammar/1207932239307/Java1_5Grammars and is governed by the following license... (BSD license type statement follows)

Portions of the Charj language are based on the Mantra language by Terence Parr. This software is available at http://www.linguamantra.org/ and is governed by the following license... (BSD license type statement follows)

The lib folder contains external jars - JSAP-2.1.jar	ant-antlr3.jar	antlr-3.2.jar

**Comment by PhilMiller** [comment]
*Original date: 2014-04-07 16:25:32*

---
The Java Simple Argument Parser (JSAP) library that CharJ uses is under the LGPL. So, we need to keep a source archive of it available to offer in correspondence to the binary, but we're otherwise fine.

**Comment by xiangni** [comment]
*Original date: 2014-04-07 19:11:05*

---
Done checking and no issues found in

cmibacktrace.c
debug-conv.c
debug-conv++.C
debug-conv.h
debug-conv++.h
msgq.h

collide

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-04-08 01:58:44*

---
From ck-core, no issues in following files:

debug-charm.C ok
debug-charm.h ok
debug-message.C
readonly.h ok
register.C ok
register.h ok
stats.h  ok
tempo.C ok
tempo.ci ok
tempo.h ok

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-08 02:08:41*

---
No issues in :

conv-interoperate.c
conv-ooc.h
conv-qd.h
conv-trace.h
conv-cpm.h
cpm.c

**Comment by bilgeacun** [comment]
*Original date: 2014-04-08 02:16:56*

---
No issues found in ck-core:
ckarray.C
ckarray.ci
ckarray.h
ckarrayindex.h
ckobjQ.C
ckobjQ.h
modifyScheduler.C
msgalloc.C
ckmarshall.ci
ckmessage.h

No issues found in libs/ck-libs:
amr
mblock
pmaf

**Comment by pplimport** [comment]
*Original author: Abhishek Gupta*
*Original date: 2014-04-08 02:36:10*

---
I rechecked CCS since I thought my earlier pass was very quick and may not have been thorough.

In ccs-auth.c, 
SHA-1 message hash code is copied from somewhere. The comments say:

Implemented and placed in the public domain by Steve Reid
Collected by Wei Dai (http://www.eskimo.com/~weidai/cryptlib.html)
Adapted for Charm++ by Orion Sky Lawlor, olawlor`acm.org, 7/20/2001

I tried following the link and finding the original source but was not able to find it. In fact, somebody else copied the same code with the same comment (even mentioning Orion Sky Lawlor and Charm++)

**Comment by PhilMiller** [comment]
*Original date: 2014-04-08 02:44:47*

---
http://sourceforge.net/p/cryptopp/code/HEAD/tree/trunk/c5/sha.cpp
That SHA1 code is indeed in the public domain, and thus free from copyright concerns.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-04-08 16:15:14*

---
Yanhua Sun wrote:
> state space search engine inside  src/ has no issues.  Example of UTS is using code from other people, copy right by the authors

Here is the license for UTS
Copyright (c) 2009 See AUTHORS file for copyright holders

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

**Comment by epmikida** [comment]
*Original date: 2014-04-09 01:05:05*

---
No issues found in conv-core:
conv-conds.c
convcore.c
cpthreads.c
cpthreads.h
msgcallbacks.c
msgmgr.c

No issues found in: langs/sdag, langs/simplemsg, langs/fortran90charm

Still looking into: langs/streams, langs/pvmc, langs/jade

**Comment by epmikida** [comment]
*Original date: 2014-04-09 19:19:20*

---
Finished reading code in lang.

lang/streams: used by NAMD. Don't know if code was written by NAMD and used by Charm++ or vice versa.
Here's the code in NAMD: http://www.ks.uiuc.edu/Research/namd/doxygen/MStream_8h-source.html
Here's NAMD's license info: http://www.ks.uiuc.edu/Research/namd/2.9/ug/node1.html

lang/pvmc: Uses PVM (Parallel Virtual Machine) code. Couldn't find licensing info on their homepage, but according to Wikipedia "PVM is free software, released under both the BSD License and the GNU General Public License."

lang/jade: Jade uses the GNU Lesser General Public License. I think this code may also use either ANTLR or Groovy code. ANTLR is the BSD license. Groovy is the Apache 2.0 license.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-09 19:41:40*

---
Submitted a patch to ditch the lang/streams code, since it has been defunct since it was committed.

Submitted a patch to add appropriate license/attribution text for UTS example.

Double-checked PVM and Jade. PVM is under a generic permissive license, and also defunct. Jade is derived from a Java grammar that's in the public domain, and uses ANTLR to generate its compiler, which is also under a permissive license.

Everything that's not deprecated is thus checked as clean, modulo the listed problem cases.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-11 20:53:27*

---
The bits of math library code from Magic Software that were imported into the data transfer library seem to have been inherited and revised by a company now known as "Geometric Tools":http://www.geometrictools.com/ContactInformation/ContactInformation.html who release the current version of that code (heavily modified, only a bare resemblance is recognizable) under the very permissive Boost Software License. So, we could either rewrite to use that newer version, or ask them for permission to continue using the older version under the present Boost license, or leave it be on the assumption that if the new code is distributed under BSL, then they're not going to pursue questionably licensed users of the old code.

**Comment by PhilMiller** [comment]
*Original date: 2014-05-05 19:13:39*

---
Existing issues are considered acceptable for release, and will be resolved subsequently.
