### ISSUE TITLE
communication aware load balancers fail on chare arrays that are not full

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#445]
*Original author: Nicolas Bock (@nicolasbock)*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/445*

---
Shameless pasting from an email conversation with Jonathan <jliffl2`illinois.edu>:

On your other email chain, you have discovered a bug in the communication-aware load balancing code, where the graph assumes that every edge will always have both nodes. This is obviously not true in the case of deletions and insertions (or even just periodic load balancing when the state may not be clearly defined)

**Comment by PhilMiller** [comment]
*Original date: 2014-05-17 00:43:53*

---
Could we get the full context of that conversation, to allow others in the group to track this down? Or, if there's a test case that exercises it, we can work through it that way.

**Comment by PhilMiller** [comment]
*Original date: 2014-08-12 00:38:53*

---
I'll try to see that this gets looked into shortly.

**Comment by PhilMiller** [comment]
*Original date: 2014-10-07 20:51:05*

---
Nicholas, would you mind giving the updated version of Charm++ a try with one of the affected LB strategies?
