### ISSUE TITLE
Does not connect to Ccs on first run

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#448]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/448*

---
When running Charmdebug for the first time for a simple hello application it prints the following error:
$ bin/charmdebug 
Loading preference file /dcsdata/home/mprobson/.cpdrc
start class // These start and ends are repeated
end class
start int
start array
end array
end int
DISPLAY variable = 128.174.236.49:0.0
ParDebug> /dcsdata/home/mprobson/charm/my/hello-mem-test/charmrun +p1 /dcsdata/home/mprobson/charm/my/hello-mem-test/hello   +cpd +DebugDisplay 128.174.236.49:0.0 ++server +DebugSuspend
ServThread started
ParDebug> Charmrun started (CCS IP 128.174.236.49, port 59514)
Parallel program printed: ccs: 2
ccs: Server IP = 128.174.236.49, Server port = 59514 $

Connecting to: 128.174.236.49:59514
Parallel program printed: Converse -memory mode: charmdebug
Charmrun> started all node programs in 1.318 seconds.

Parallel program printed: slot size 56
Converse/Charm++ Commit ID: v6.6.0-rc2-28-ga31a88d

Parallel program printed: Charm++> scheduler running in netpoll mode.

Parallel program printed: CharmLB> Load balancer assumes all CPUs are same.

Parallel program printed: Charm++> Running on 1 unique compute nodes (8-way SMP).

Parallel program printed: Charm++> cpu topology info is gathered in 0.004 seconds.

Parallel program printed: Hello World 
0
ServThread terminated
Finished running parallel program
java.net.SocketException: Connection reset by peer
  // then a really long exception trace
Network error connecting to PE 0 to perform debug/converse/arch
Error while starting the application (error: java.lang.NullPointerException. Aborting...
java.lang.NullPointerException
 // another really long exception trace
Starting generation new list 1395273981115
Ended generation new list 1395273981116

**Comment by PhilMiller** [comment]
*Original date: 2014-04-11 20:57:44*

---
Please triage and/or reassign appropriately

**Comment by xiangni** [comment]
*Original date: 2015-02-19 19:44:59*

---
In the earlier commit 117cc7fd26d7defa01b41492bfd4e7ec0b172518 to make liveViz working with failure, I set a SocketTimeoutException. However, the connection to charmdebug could be longer than that, thus causing the connection issue. I think we should revert that commit, the FT related changes could go to a separate branch? It can be tricky to find an ideal timeout value that satisfy both purposes.

**Comment by xiangni** [comment]
*Original date: 2015-02-19 21:28:43*

---
Reverted the faulty commit and verified that the connection error no longer shows up.
