### ISSUE TITLE
Prints out a warning mismatch

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#449]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/449*

---
Note: Related to #448 due to when connection happens (takes two tries), otherwise independent

**Comment by ericjbohm** [comment]
*Original date: 2015-10-06 20:38:57*

---
Write a real description for this so the bug is comprehensible.

**Comment by mprobson** [comment]
*Original date: 2015-10-26 18:31:05*

---
Could not reproduce using (presumably) the same program (as mentioned in #448).
