### ISSUE TITLE
ckcallback.h Error: The function "bzero" must have a prototype.

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#450]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/450*

---
Building --no-build-shared --enable-tracing --enable-tracing-commthread -optimize on net-sol-x86_64-smp (which is good at catching odd errors):
../bin/charmc  -optimize  -c -I. init.C
"./ckcallback.h", line 119: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 126: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 135: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 144: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 153: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 165: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 177: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 189: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 198: Error: The function "bzero" must have a prototype.
"./ckcallback.h", line 225: Error: The function "bzero" must have a prototype.

It also appears that CMK_REPLAYSYSTEM is true for some reason.

**Comment by jcphill** [comment]
*Original date: 2014-03-20 16:33:41*

---
Also, memset is generally preferred to bzero.

**Comment by nikhil-jain** [comment]
*Original date: 2014-03-20 17:58:08*

---
Historical artifact. Replaced with memset.

http://charm.cs.uiuc.edu/gerrit/144

**Comment by nikhil-jain** [comment]
*Original date: 2014-03-20 18:09:03*

---
As for CMK_REPLAYSYSTEM, I think its set by default; though it should be harmless unless some command line argument is passed. I will check on that.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-10 22:53:02*

---
This is all well, now.
