### ISSUE TITLE
segfault in LDObjData::~LDObjData()

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#451]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/451*

---
From a March 11 build:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 182895731264 (LWP 26405)]
0x000000389c669535 in free () from /lib64/tls/libc.so.6
(gdb) where
#0  0x000000389c669535 in free () from /lib64/tls/libc.so.6
#1  0x000000389f5ae29e in operator delete () from /usr/lib64/libstdc++.so.6
#2  0x0000000000aac545 in LDObjData::~LDObjData ()
#3  0x000000389f5b0a8b in __cxa_vec_dtor () from /usr/lib64/libstdc++.so.6
#4  0x000000389f5b0f3f in __cxa_vec_delete2 () from /usr/lib64/libstdc++.so.6
#5  0x0000000000aae2e1 in NamdCentLB::buildData ()
#6  0x0000000000aad23a in NamdCentLB::Strategy ()
#7  0x0000000000d13f33 in CentralLB::LoadBalance ()
#8  0x0000000000d13bda in CkIndex_CentralLB::_call_LoadBalance_void ()
#9  0x0000000000c63139 in CkDeliverMessageFree ()
#10 0x0000000000c61fe0 in _processHandler ()
#11 0x0000000000d66616 in CsdScheduleForever ()
#12 0x0000000000d66194 in CsdScheduler ()
#13 0x00000000006620fb in BackEnd::suspend ()
#14 0x0000000000b499c5 in ScriptTcl::run ()
#15 0x000000000065da5a in after_backend_init ()
#16 0x000000000065d58a in main ()

**Comment by jcphill** [comment]
*Original date: 2014-03-20 18:01:12*

---
Nevermind. Some .o files were from a build with an earlier version of charm.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-20 18:02:00*

---
Change status to reflect properly in statistics
