### ISSUE TITLE
_sendStats() during CkExit() sends per-pe messages to pe 0

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#452]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/452*

---
Calling CkExit() on, e.g., 240,000 cores of Blue Waters, yields the following error:

```
WallClock: 251.544098  CPUTime: 251.544098  Memory: 7621.382812 MB
------------- Processor 240000 Exiting: Called CmiAbort ------------
Reason: GNI_RC_CHECK
charm> Please use +useRecvQueue 327680 in your command line, if the error comes again, increase this number
[240000] Smsg_rx_cq full; err=GNI_RC_ERROR_RESOURCE
aborting job:
GNI_RC_CHECK
```

This is almost certainly due to _sendStats(), which bombards pe 0 with one message per pe rather than using a reduction tree, all to pass it to _printStats(), which is a no-op unless CMK_WITH_STATS && ( _printSS || _printCS ).

```
static inline void _sendStats(void)
{
  DEBUGF(("[%d] _sendStats\n", CkMyPe()));
#if CMK_WITH_STATS
  envelope *env = UsrToEnv(CkpvAccess(_myStats));
#else
  envelope *env = _allocEnv(StatMsg);
#endif
  env->setSrcPe(CkMyPe());
  CmiSetHandler(env, _exitHandlerIdx);
  CmiSyncSendAndFree(0 /* destPE */, env->getTotalsize(), (char *)env);
}
```

The all-to-zero point-to-point sends should be transformed to a reduction operation

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-26 05:19:55*

---
This appears to be duplicate. Rejecting.

**Comment by PhilMiller** [comment]
*Original date: 2014-05-26 14:33:24*

---
This was intentionally duplicated, to reflect different aims. See #425-6: #425 resolved the immediate hardship, and this is about making the stats-collection usable at scale.
