### ISSUE TITLE
zero-length arrays

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#458]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/458*

---
This only shows up on Solaris x86_64, and -features=zla does fix it, but aren't zero-length arrays still technically illegal?

../bin/charmc  -optimize -production   -c -I. BlockLB.C
"envelope.h", line 261: Error: An array cannot have zero size unless you use the
 option -features=zla.
"envelope.h", line 410: Warning: pe hides envelope::pe.
"sdag.h", line 78: Warning: msg hides SDAG::MsgClosure::msg.
"sdag.h", line 191: Warning: cl hides SDAG::Buffer::cl.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-02 16:41:35*

---
gcc/g++ 4.4 targeting C++98 agrees:

```
../../bin/../include/envelope.h: At global scope:
../../bin/../include/envelope.h:261:61: warning: ISO C++ forbids zero-size array â€˜alignâ€™ [-pedantic]
```

Practically speaking, I don't think this matters, since nothing takes that element's address, and all of our compilers will accept it anyway.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-10 23:06:31*

---
Jim, could you send me the output of `mpiCC -show` on that system, so I can add the features flag accordingly?

**Comment by jcphill** [comment]
*Original date: 2014-04-11 14:26:23*

---
It's just an old, single server - no mpiCC command.

jim`cardiff>CC -V
CC: Sun C++ 5.9 SunOS_i386 2007/05/03
