### ISSUE TITLE
Reduction for stats collection

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#460]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/460*

---
Have a reduction in Charm which takes in values and gives the min, max, avg etc.

**Comment by stwhite91** [comment]
*Original date: 2017-01-17 03:19:20*

---
Stats reductions were added a while ago here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1116/~~ https://github.com/UIUC-PPL/charm/commit/b43c918a03e4808109805a18688f9e48754a1850
