### ISSUE TITLE
ibverbs layer does not provide 16 byte alignment

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#461]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/461*

---
If using ibverbs, chunkheader and other headers following it are not 16 bytes aligned.

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-10 22:48:07*

---
Lukasz has put in a fix in gerrit for it http://charm.cs.uiuc.edu/gerrit/#/c/167/
This fixes the issues for all but one case - when the requested allocation is < 120 bytes. Internal ibverbs pools starts at 120 bytes resulting in 8 byte alignment only.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-15 23:36:15*

---
Fixed up the small message case and the case of standalone runs (that don't use the pool, because they don't need registered memory).

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-04-27 22:49:22*

---
As reported by Phil, alignment test is now passing in ibverbs for both large and small messages. Closing the issue.
