### ISSUE TITLE
Partition stdout redirection message should always comes from partition 0

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#462]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/462*

---
Charm++> Running in SMP mode: numNodes 1024,  14 worker threads per
process
Charm++> The comm. thread both sends and receives messages
Charm++> Using rank ordered division (scheme 0) for topology aware
partitions
Redirecting stdout to files
/lustre/atlas1/bio024/scratch/jimp/output/0/apr10_stmv2fs_128rep_1024_nop_0.log
through 127

Note that it's printing the partition 0 case, vs with topology it's 116:

Charm++> Using recursive bisection (scheme 3) for topology aware
partitions
Charm++> TORUS A SIZE 25 USING 9 10 11 12
Charm++> TORUS B SIZE 16 USING 2 3 4 5 6 7 8 9
Charm++> TORUS C SIZE 24 USING 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
18 19 20 21 22 23
Charm++> TORUS MINIMAL MESH SIZE IS 4 BY 8 BY 24
Redirecting stdout to files
/lustre/atlas1/bio024/scratch/jimp/output/116/apr10_stmv2fs_128rep_1024_def_116.log
through 127
_pmiu_daemon(SIGCHLD): [NID 10498] [c23-4c2s1n2] [Fri Apr 11 11:41:37
2014] PE RANK 289 exit signal Segmentation fault
[NID 10498] 2014-04-11 11:41:37 Apid 4847657: initiated application
termination

Also, the topology version crashes at the first replicaBarrier.

**Comment by jcphill** [comment]
*Original date: 2014-04-11 16:13:22*

---
OK, so the +stdout filename strangeness is just due to this:

      if ( CmiMyNodeGlobal() == 0 ) {
        printf("Redirecting stdout to files %s through %d\n",stdoutpath,CmiNumPartitions()-1);
      }

Global node 0 isn't always on partition 0.  This is annoying but not fatal.

The crash looks like a crash on one of the nodes.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-14 18:17:40*

---
Nikhil, could you triage this?

**Comment by nikhil-jain** [comment]
*Original date: 2014-04-14 18:40:16*

---
Jim further reported that it works for apoA1, but not for stmv. So we are not sure of which part is broken. I plan to look at it post SC deadline.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-24 22:07:08*

---
Now that we're post-SC, could you re-examine this?

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-05 18:52:53*

---
I am not able to reproduce this issue: just ran 100M stmv on BW with 4 partitions and topology scheme 3 on 16 nodes with and without SMP. Should I try some other configuration?

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-26 05:17:43*

---
I am inclined to mark this as resolved (rejected?). Jim, please confirm.

**Comment by PhilMiller** [comment]
*Original date: 2014-11-04 21:07:20*

---
Jim, Nikhil, is this still an issue?

**Comment by jcphill** [comment]
*Original date: 2014-11-05 20:55:09*

---
I think the issue that global node 0 isn't always on partition 0 is still there, but it only affects this one message.

**Comment by PhilMiller** [comment]
*Original date: 2014-11-11 19:20:28*

---
Retitled; I assume the crash in question was long ago resolved as independent of this?
