### ISSUE TITLE
Accurate file/line numbers in emitted SDAG atomic blocks

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#47]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/47*

---
We should emit #line directives with our generated SDAG code when it contains bits written by application developers, so that errors point them back to the original location in their code, not the generated def.h file.

Setting this is relatively easy. Resetting it so that later code in .def.h isn't mis-located is a bit more tricky. Here's the best solution I've gotten: http://stackoverflow.com/a/14824475/90002

**Comment by PhilMiller** [comment]
*Original date: 2013-02-18 19:13:00*

---
This will probably be a bit easier once at least the 'atomic' portion of #48 is done.

**Comment by ericjbohm** [comment]
*Original date: 2013-05-03 19:32:34*

---
Is this something you can complete before you leave for the summer?

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:14:13*

---
Ping - inactive for 3 months. The task is relatively small, please complete asap.

**Comment by PhilMiller** [comment]
*Original date: 2015-05-01 19:26:04*

---
With the improved position tracking in the refactored charmxi code, this should be somewhat more straightforward. Is there anything fundamentally obstructing this?

For the part about resetting the `#line` directives at the end of each block in the output, we can insert a marker of some sort as suggested in that StackOverflow post, and then replace them in the assembled string before/as it's output to the generated file.
