### ISSUE TITLE
Removal of METIS breaks linking for EveryLB

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#479]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/479*

---
A surprisingly large number of LB strategies rely on METIS.  Removing METIS from the distribution (http://charm.cs.uiuc.edu/gerrit/#/c/100/) created an EveryLB which will fail during link time without METIS.

Bug went undetected because there is no automated test of EveryLB

A fix for this is implemented in http://charm.cs.uiuc.edu/gerrit/#/c/89/
That patch set was originally triggered by https://charm.cs.illinois.edu/redmine/issues/419 
This bug could be fixed without that patch set, but then we'd have to do the same thing twice, in two different ways, for no apparent benefit.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-27 23:47:57*

---
Manually tested and confirmed fixed. Can also explicitly build MetisLB and link/run against that.
