### ISSUE TITLE
auto sleepOnIdle warning not printed due to race condition

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#485]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/485*

---
There is a race condition that typically prevents the printing that sleepOnIdle is being automatically enabled.  If pe 0 does not check _Cmi_sleepOnIdle before another thread modifies it then the warning is never printed.

A fix would be to wrap the entire block below inside "if (CkMyRank() == 0) {...} CmiNodeAllBarrier();"

Also, note that multicore can have a comm thread if +commthread is used at runtime, so for CMK_MULTICORE you need to check Cmi_commthread.

In src/ck-core/init.C:
```
#if CMK_SHARED_VARS_POSIX_THREADS_SMP
        if (CmiCpuTopologyEnabled()) {
            int *pelist;
            int num;
            CmiGetPesOnPhysicalNode(0, &pelist, &num);
#if !CMK_MULTICORE && !CMK_SMP_NO_COMMTHD
            // Count communication threads, if present
            // XXX: Assuming uniformity of node size here
            num += num/CmiMyNodeSize();
#endif
            if (!_Cmi_sleepOnIdle && !_Cmi_forceSpinOnIdle && num > CmiNumCores())
            {
              if (CmiMyPe() == 0)
                CmiPrintf("\nCharm++> Warning: the number of SMP threads (%d) is greater than the number of physical cores (%d), so threads will sleep while idling. Use +CmiSpinOnIdle or +CmiSleepOnIdle to control this directly.\n\n", num, CmiNumCores());
              _Cmi_sleepOnIdle = 1;
            }
        }
#endif

```

**Comment by jcphill** [comment]
*Original date: 2014-06-03 20:26:18*

---
I just re-sent a patch for this to core-ppl mailing list.

**Comment by nikhil-jain** [comment]
*Original date: 2014-06-03 21:16:59*

---
Minor patch. Assigning to Eric. 

Please look at core-mail to get the patch.

**Comment by jcphill** [comment]
*Original date: 2014-06-09 22:53:43*

---
ping

**Comment by PhilMiller** [comment]
*Original date: 2014-06-12 21:30:32*

---
Eric is now on vacation, so I'll handle this.

**Comment by PhilMiller** [comment]
*Original date: 2014-06-12 21:43:01*

---
Change 278 in gerrit.
