### ISSUE TITLE
strsignal fails to link on mpi-win64

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#488]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/488*

---

libconv-cplus-y.a(machine.o) : error LNK2019: unresolved external symbol strsignal referenced in function KillOnAllSigs
hello.exe : fatal error LNK1120: 1 unresolved externals
unix2nt_cc Fatal Error in directory /home/jim/charm/mpi-win64/tests/charm++/simplearrayhello
   Error executing C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\/BIN/amd64/LINK.EXE /nologo /subsystem:console /LIBPATH:C:\PROGRA~2\MICROS~1.0\VC\Lib\amd64 /LIBPATH:C:\PROGRA~1\MI564C~1\Lib\amd64 C:\PROGRA~1\MI564C~1\Lib\amd64\msmpi.lib /out:hello.exe /LIBPATH:C:\cygwin64\home\jim\charm\mpi-win64\lib C:\cygwin64\home\jim\charm\mpi-win64\lib\libldb-rand.o hello.o moduleinit1324.o C:\cygwin64\home\jim\charm\mpi-win64\lib\libmemory-default.o C:\cygwin64\home\jim\charm\mpi-win64\lib\libthreads-default.o C:\cygwin64\home\jim\charm\mpi-win64\lib\libckmain.a C:\cygwin64\home\jim\charm\mpi-win64\lib\libck.a C:\cygwin64\home\jim\charm\mpi-win64\lib\libconv-cplus-y.a C:\cygwin64\home\jim\charm\mpi-win64\lib\libconv-core.a C:\cygwin64\home\jim\charm\mpi-win64\lib\libconv-util.a C:\cygwin64\home\jim\charm\mpi-win64\lib\libconv-partition.a ws2_32.lib kernel32.lib user32.lib psapi.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib /MACHINE:X64 /ERRORREPORT:PROMPT
unix2nt_cc exiting...
Fatal Error by charmc in directory /home/jim/charm/mpi-win64/tests/charm++/simplearrayhello
   Command unix2nt_cc -D_CRT_SECURE_NO_DEPRECATE -I /cygdrive/c/PROGRA~1/MI564C~1/Inc -L /cygdrive/c/PROGRA~1/MI564C~1/Lib/amd64 -lmsmpi -o hello -L../../../bin/../lib -I../../../bin/../include ../../../bin/../lib/libldb-rand.o hello.o moduleinit1324.o ../../../bin/../lib/libmemory-default.o ../../../bin/../lib/libthreads-default.o -lckmain -lck -lconv-cplus-y -lconv-core -lconv-util -lconv-partition -lm returned error code 1

In src/arch/mpi/machine.c

static void KillOnAllSigs(int sigNo) {
    static int already_in_signal_handler = 0;
    char *m;
    if (already_in_signal_handler) return;   /* MPI_Abort(charmComm,1); */
    already_in_signal_handler = 1;

    CmiAbortHelper("Caught Signal", strsignal(sigNo), NULL, 1, 1);
}
/* ######End of functions related with exiting programs###### */

**Comment by jcphill** [comment]
*Original date: 2014-05-08 17:55:24*

---

```
diff --git a/src/arch/mpi/machine.c b/src/arch/mpi/machine.c
index f9fd138..58f040f 100644
--- a/src/arch/mpi/machine.c
+++ b/src/arch/mpi/machine.c
`` -29,6 +29,10 ``
 static void sleep(int secs) {
     Sleep(1000*secs);
 }
+static char* strsignal(int sig) {
+  static char outbuf[32];
+  sprintf(outbuf, "%d", sig);
+}
 #else
 #include <unistd.h> /*For getpid()*/
 #endif

```

**Comment by jcphill** [comment]
*Original date: 2014-05-16 14:53:23*

---
Anybody looking at this?  It's an easy fix.

**Comment by PhilMiller** [comment]
*Original date: 2014-05-16 14:58:07*

---
Core meeting last week said this was supposed to get pushed by one of the NAMD subgroup.
