### ISSUE TITLE
mpi-win64-smp various issues

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#489]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/489*

---
After copying the conv-mach-smp.* files from net-win64 I get the following errors:

```
../bin/charmc   -o machine.o  -DFOR_CPLUS=1 machine.c
machine.c
machine.c(347) : warning C4047: 'initializing' : 'CmiNodeLock' differs in levels of indirection from 'void *'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(357) : error C2223: left of '->recv' must point to struct/union
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(357) : warning C4033: 'CmiMyRecvQueue' must return a value
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(365) : error C2054: expected '(' to follow '_Cmi_mype'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(372) : error C2223: left of '->pe' must point to struct/union
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(372) : error C2198: 'pe_lToGTranslate' : too few arguments for call
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(374) : error C2059: syntax error : 'constant'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(377) : error C2059: syntax error : 'type'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(380) : error C2059: syntax error : 'constant'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(383) : error C2059: syntax error : 'type'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(386) : error C2059: syntax error : 'constant'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(405) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(445) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(1177) : warning C4047: '=' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(1386) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(1422) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(1442) : warning C4047: '=' : 'CmiState' differs in levels of indirection from 'int'
c:\cygwin64\home\jim\charm\mpi-win64-smp\tmp\machine-common-core.c(1463) : error C2065: '_Cmi_sleepOnIdle' : undeclared identifier
machine.c(497) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
machine.c(892) : error C2223: left of '->recv' must point to struct/union
machine.c(892) : error C2198: 'PCQueueEmpty' : too few arguments for call
machine.c(1000) : warning C4047: 'initializing' : 'CmiState' differs in levels of indirection from 'int'
unix2nt_cc Fatal Error in directory /home/jim/charm/mpi-win64-smp/tmp
   Error executing CL.EXE /nologo /W1 /EHsc /D_WINDOWS /DNOMINMAX /IC:\PROGRA~2\WI3CF2~1\8.0\Include /IC:\PROGRA~2\MICROS~1.0\VC\Include /MT /Fomachine.o /D_CRT_SECURE_NO_DEPRECATE /IC:\PROGRA~1\MI564C~1\Inc /IC:\cygwin64\home\jim\charm\mpi-win64-smp\include /D__CHARMC__=1 /DFOR_CPLUS=1 /c /Tcmachine.c
unix2nt_cc exiting...
Fatal Error by charmc in directory /home/jim/charm/mpi-win64-smp/tmp
   Command unix2nt_cc -D_CRT_SECURE_NO_DEPRECATE -I /cygdrive/c/PROGRA~1/MI564C~1/Inc -I../bin/../include -D__CHARMC__=1 -DFOR_CPLUS=1 -c machine.c -o machine.o returned error code 1
charmc exiting...
Makefile:471: recipe for target `../lib/libconv-cplus-n.a' failed
```

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-26 05:26:04*

---
One of the NAMD people - please take a first look. Upping priority.

**Comment by PhilMiller** [comment]
*Original date: 2014-11-09 16:39:35*

---
Ping. It would be *very* helpful if the necessary fixes got fully implemented before the core meeting this week. It should hopefully all be fairly simple changes. If you need help, ask.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-17 20:19:45*

---
Ping. Was this merged?

**Comment by rbuch** [comment]
*Original date: 2015-10-13 20:02:33*

---
There are some changes on ronak/mpi-win64-smp-fix, but it doesn't fully fix the problem.  It builds fine, but then there is a runtime failure, which I'm still trying to diagnose and fix.

**Comment by rbuch** [comment]
*Original date: 2015-10-26 22:21:39*

---
Gerrit Link: ~~https://charm.cs.illinois.edu/gerrit/#/c/885/~~ https://github.com/UIUC-PPL/charm/commit/8c55a0801d056610d7d59b6dc1b668ef8e0df05c

**Comment by jcphill** [comment]
*Original date: 2015-10-28 03:26:10*

---
On testing with --no-build-shared --enable-tracing --enable-tracing-commthread -optimize I get the following warning on every file:

c:\cygwin64\usr\tmp\charm-6.7.0-proj-build-2015-oct-27-179786-mpi-win64-smp\charm-6.7.0-pre\mpi-win64-smp\tmp\conv-config.h(137) : warning C4005: 'CMK_NODE_QUEUE_AVAILABLE' : macro redefinition^M
        c:\cygwin64\usr\tmp\charm-6.7.0-proj-build-2015-oct-27-179786-mpi-win64-smp\charm-6.7.0-pre\mpi-win64-smp\tmp\conv-mach-smp.h(4) : see previous definition of 'CMK_NODE_QUEUE_AVAILABLE'^M
../bin/charmc  -optimize  -I.   -c -o Refiner.o Refiner.C

and two unresolved symbols:

libconv-cplus-y.a(machine.o) : error LNK2019: unresolved external symbol TraceTimerCommon referenced in function handleOneRecvedMsg^M
libconv-cplus-y.a(machine.o) : error LNK2019: unresolved external symbol START_TRACE_RECVCOMM referenced in function PumpMsgs^M

Building --no-build-shared --with-production the warnings are still there but tests link and run successfully.

**Comment by rbuch** [comment]
*Original date: 2015-10-28 21:04:34*

---
We're aware of the warning on every file.

Do you mean that you're getting errors when building charm or when building an application?  I'm able to build with ./build charm++ mpi-win64 smp --no-build-shared --enable-tracing --enable-tracing-commthread -optimize with no errors.  However, I am getting errors building when actually building applications (unresolved START_TRACE_RECVCOMM).  We'll take a look.

**Comment by rbuch** [comment]
*Original date: 2015-10-28 22:10:19*

---
Turns out this is broken across all MPI builds, as that symbol is only defined when comm thread tracing is turned off.  Commit 8bbf1f4855f1e87b51fae1704f4a1b4ab8b081b9 took out the definition of START_TRACE_CREATION, as it should now be traced in machine-common-core.  I'll talk to Bilge to see what the recommended way to trace the comm thread is with the current machine layer code stack.

**Comment by jcphill** [comment]
*Original date: 2015-10-29 01:20:06*

---
Thanks. I only care about mpi-smp on Windows and never actually do any tracing so this isn't an issue. I only noticed because I've added compiling megatest to my builds.
