### ISSUE TITLE
FuncCkLoop needs a migration constructor and PUP'er routine for restart.

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#490]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/490*

---
Trying to use CkLoop in ChaNGa, I get the following at checkpoint time:

------------- Processor 186 Exiting: Called CmiAbort ------------
Reason: (Node)Group FuncCkLoop needs a migration constructor and PUP'er routine for restart.

**Comment by PhilMiller** [comment]
*Original date: 2014-11-11 19:17:45*

---
This was done a while ago, and should have been closed then.
