### ISSUE TITLE
extend +pemap notation to interleave hyperthreads

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#498]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/498*

---
Intel processors number the "cpus" for the two hyperthreads on each core as i and i+n for a machine with n cores.  This means that setting cpu affinity with a simple "+pemap 0-47" on a 24-core machine results in threads 0 and 24 sharing the same core, when one would logically expect threads 0 and 1 to share a core (which is how things are on AMD).  To work around this now we have to specify things like this:

+ppn 10 +pemap 0,24,1,25,2,26,3,27,4,28,6,30,7,31,8,32,9,33,10,34,12,36,13,37,14,38,15,39,16,40,18,42,19,43,20,44,21,45,22,46 +commap 5,11,17,23

I would suggest extending the +pemap syntax from Lower-Upper:Stride.Run to L-U+Offset:S.R, allowing for example, +pemap 0,24,1,25,.. to be expressed as +pemap 0-23+24 or, for some future chip, +pemap 0,24,48,72,1,25,49,73,... as +pemap 0-23+24+48+72

If this syntax looks good I can try to modify the pemap code.

Another syntax option would be to put the offsets before the stride as in +pemap 0+24+48+72-23, but I think that's more confusing.

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-22 21:53:47*

---
Jim, does an alternative already exist since you closed the issue?

**Comment by PhilMiller** [comment]
*Original date: 2014-05-22 21:56:12*

---
It got submitted in duplicate
