### ISSUE TITLE
extend +pemap notation to interleave hyperthreads

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#499]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/499*

---
Intel processors number the "cpus" for the two hyperthreads on each core as i and i+n for a machine with n cores. This means that setting cpu affinity with a simple "+pemap 0-47" on a 24-core machine results in threads 0 and 24 sharing the same core, when one would logically expect threads 0 and 1 to share a core (which is how things are on AMD). To work around this now we have to specify things like this:

+ppn 10 +pemap 0,24,1,25,2,26,3,27,4,28,6,30,7,31,8,32,9,33,10,34,12,36,13,37,14,38,15,39,16,40,18,42,19,43,20,44,21,45,22,46 +commap 5,11,17,23

I would suggest extending the +pemap syntax from Lower-Upper:Stride.Run to L-U+Offset:S.R, allowing for example, +pemap 0,24,1,25,.. to be expressed as +pemap 0-23+24 or, for some future chip, +pemap 0,24,48,72,1,25,49,73,... as +pemap 0-23+24+48+72

If this syntax looks good I can try to modify the pemap code.

Another syntax option would be to put the offsets before the stride as in +pemap 0+24+48+72-23, but I think that's more confusing.

[pemapplus.patch](https://github.com/UIUC-PPL/charm/files/3536435/pemapplus.patch.txt)

**Comment by jcphill** [comment]
*Original date: 2014-05-22 22:07:41*

---
For the example from above:

+ppn 10 +pemap 0,24,1,25,2,26,3,27,4,28,6,30,7,31,8,32,9,33,10,34,12,36,13,37,14,38,15,39,16,40,18,42,19,43,20,44,21,45,22,46 +commap 5,11,17,23

the equivalent showing complete new syntax:

+ppn 10 +pemap 0-23:6.5+24 +commap 5-23:6

**Comment by jcphill** [comment]
*Original date: 2014-05-22 22:58:46*

---
This was simple enough that I did it myself.  Patch attached.  Please submit and review.

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-26 05:15:18*

---
In interest of spreading small core tasks, I am assigning this to Akhil. Please reassign if needed.

**Comment by nikhil-jain** [comment]
*Original date: 2014-05-30 03:23:17*

---
Attaching the patch Jim had sent.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-06-02 21:57:00*

---
I went through the implementation and tested. It works good. 
Commit is submitted for review

**Comment by PhilMiller** [comment]
*Original date: 2014-06-19 21:24:31*

---
Thank you, Yanhua, for following this through.

This will be closed if no one find further issues with its operation.
