### ISSUE TITLE
Many-to-many primitive broken on DCMF

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#5]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/5*

---
The DCMF and PAMI machine layers offer an optimized many-to-many primitive that has been useful in NAMD, but it's currently reported to be broken.

**Comment by ericjbohm** [comment]
*Original date: 2013-03-08 23:03:46*

---
this was fixed by Nikhil's change to the argument order.  Confirmed by independent build and test of penciltest

**Comment by PhilMiller** [comment]
*Original date: 2013-03-30 15:26:46*

---
Noting that this was actually fixed before 6.5
