### ISSUE TITLE
CmiNumCores() does not reflect powered-off cores

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#501]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/501*

---
On our new Jetson TK1 development kit the Linux scheduler likes to turn off cores when they are idle, which means those cores do not show up in
sysconf(_SC_NPROCESSORS_ONLN) but only sysconf(_SC_NPROCESSORS_CONF), and also you can't set affinity to only those cores.  Apparently the OS will also modify your affinity mask if it later disables your core.

We could change CmiNumCores() in src/conv-core/cputopology.C to use the maximum of sysconf(_SC_NPROCESSORS_ONLN and sysconf(_SC_NPROCESSORS_CONF), which will all most runs to work as expected, as long as they don't set cpu affinity to a core that happens to be off, but we can at least test for that and report a reasonable error message, or try to wait until the OS enables the desired core.

**Comment by jcphill** [comment]
*Original date: 2014-06-03 20:26:23*

---
I just re-sent a patch for this to core-ppl mailing list.

**Comment by nikhil-jain** [comment]
*Original date: 2014-06-03 21:17:42*

---
Minor patch. Assigning to Ehsan in the interest of dividing core type of work.

Please look at core-mail to get the patch.

**Comment by PhilMiller** [comment]
*Original date: 2014-06-09 19:09:38*

---
As a general policy agreed in the core group, development hardware won't hold the release. If we can get the patch landed, great. If not, it will wait.

In the meantime, who in PPL has access to this hardware?

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2014-06-09 19:11:54*

---
How can I get access to the hardware?

**Comment by jcphill** [comment]
*Original date: 2014-06-09 22:50:28*

---
You would need a TCBG dongle, which really isn't worth it for a one-off fix, then John Stone could make you an account.
The patch I sent works.  The important thing is to be sure it doesn't break any other platform.
