### ISSUE TITLE
Check for errors in values returned by library calls

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#504]
*Original author: Lukasz Wesolowski*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/504*

---
The work required to methodically do this throughout the runtime system code base will likely pay for itself in reduced debugging time in the future.

Using CkAssert/CmiAssert may be preferable in frequently accessed and performance sensitive code.

Probably best to split this between 5 - 10 people to minimize the individual work required.

**Comment by stwhite91** [comment]
*Original date: 2018-04-29 22:58:43*

---
With the C++ attribute to warn when a function's return value is unused, we've fixed a lot of standard library calls to check for errors. Marking closed for now
