### ISSUE TITLE
Make Jenkins Instance Public

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#509]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/509*

---
We would like to open up our Jenkins build site to the public, much like the current site at http://charm.cs.illinois.edu/autobuild/cur/.

Currently the security is configured to allow logged in users to do anything. This is fine for lab mates and collaborators but we may need to switch to a role based system in order to ensure anonymous/non-logged in users can only view whether builds have passed etc. More evaluation is needed here to see if our build workspaces expose any sensitive information.

Another part of this task is ensuring that the nightly build suite actually runs and completes for most of the tests. This may be a separate issue entirely.

Finally, we need to make sure everyone is signed up and publish this at an externally accessible web address.

**Comment by rbuch** [comment]
Closing, no longer relevant since we no longer use Jenkins for testing.
