### ISSUE TITLE
Regular performance benchmarks for AMPI

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#51]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/51*

---
No body.

[all.pdf](https://github.com/UIUC-PPL/charm/files/3536160/all.pdf)
[HPCCG.pdf](https://github.com/UIUC-PPL/charm/files/3536164/HPCCG.pdf)
[miniMD.pdf](https://github.com/UIUC-PPL/charm/files/3536165/miniMD.pdf)
[all_res.cpp](https://github.com/UIUC-PPL/charm/files/3536355/all_res.cpp.txt)
[get_plots.sh](https://github.com/UIUC-PPL/charm/files/3536356/get_plots.sh.txt)

**Comment by ericjbohm** [comment]
*Original date: 2013-03-01 22:25:28*

---
IMB
Mantevo
NAS

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2013-12-31 22:37:23*

---
IMB performance comparison of MPI and AMPI on 2K cores of BlueGene/Q (Vesta) as of Nov. 14, 2013.
Two Mantevo mini-apps strong scaling comparison for MPI and AMPI.
Scripts to get plots from IMB results easily

**Comment by stwhite91** [comment]
*Original date: 2016-04-23 17:09:14*

---
AMPI benchmarks and codes can be found here: https://wiki.cites.illinois.edu/wiki/pages/viewpage.action?pageId=451248565
