### ISSUE TITLE
net-linux-arm7 unstable on Jetson TK1

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#510]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/510*

---
net-linux-arm7 is unstable when running NAMD ++local +p4 on Jetson TK1, with and without -O3.
net-linux-arm7-smp seems to be OK.  Runs fine on older CARMA board.

charm++/megatest fails +p4 for net-linux-arm7 -O3 but not for --with-production or an unoptimized build:
test 10: initiated [synctest (mjlang)]
***  ***: ./pgm terminated
------------- Processor 2 Exiting: Caught Signal ------------
Signal: unknown signal
Fatal error on PE 2> unknown signal

**Comment by ericjbohm** [comment]
*Original date: 2015-02-09 22:09:08*

---
will get new RSA token tomorrow so I can reproduce ARM bugs.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-16 18:28:02*

---
I need access to a Jetson TK1 to reproduce this.  Cupertino is the older model CARMA.  The computational resources web pages for TCBG do not list a machine with a Jetson TK1.  As the pages appear to be generally out of date, that isn't entirely surprising.

**Comment by jcphill** [comment]
*Original date: 2015-02-16 18:54:16*

---
Our Jetson TK1 is dead.  We're working on getting a new one.

**Comment by jcphill** [comment]
*Original date: 2015-02-18 16:22:02*

---
It looks like our Jetson is actually alive and well and living as cairo.ks.uiuc.edu.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-18 20:13:51*

---
I don't seem to have an account on Cairo.  Or if I do, the password is not known to me.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-19 19:21:14*

---
Bug is trivially reproducible in net and netlrts.

Does not occur using --with-production, or -O0 -g.  So far just -O3.  Going to require a lot more digging.

**Comment by ericjbohm** [comment]
*Original date: 2015-02-19 19:36:54*

---
Reproducible on single core with -O3 -g.

```
test 10: initiated [synctest (mjlang)]
***  ***: /home/bohm/charm/netlrts-linux-arm7-dbgO3/tests/charm++/megatest/pgm terminated

Program received signal SIGABRT, Aborted.
__libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44	../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xb65cbf0e in __GI_raise (sig=sig`entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb65ce766 in __GI_abort () at abort.c:89
#3  0xb65f2bf0 in __libc_message (do_abort=do_abort`entry=2, fmt=0xb6678028 "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:175
#4  0xb6644522 in __GI___fortify_fail (msg=0xb6679d68 <h_nerr> "\005") at fortify_fail.c:37
#5  0xb66443ae in __longjmp_chk (env=0x2, env`entry=0x315918, val=-1234730968) at ../setjmp/longjmp.c:38
#6  0x00215822 in qt_block (hfn=<optimized out>, old=<optimized out>, new=<optimized out>, sp=0x315918)
    at md/setjmp64_.c:99
#7  0x00116b64 in CkIndex_synctest_main::_call_doTest_void(void*, void*) ()
#8  0x0016cd12 in CkDeliverMessageFree (epIdx=216, msg=0xb6674078, obj=<optimized out>) at ck.C:593
#9  0x0016cf58 in _invokeEntryNoTrace (obj=0xb6688ffc, env=0x2e8c38, epIdx=216) at ck.C:637
#10 _invokeEntry (epIdx=216, env=0x2e8c38, obj=0xb6688ffc) at ck.C:648
#11 0x0017117e in _processForPlainChareMsg (ck=<optimized out>, env=0x2e8c38) at ck.C:1002
#12 _processHandler (converseMsg=<optimized out>, ck=<optimized out>) at ck.C:1285
#13 0x001f5086 in CmiHandleMessage (msg=<optimized out>) at convcore.c:1626
#14 CsdScheduleForever () at convcore.c:1854
#15 0x001f5448 in CsdScheduler (maxmsgs=maxmsgs`entry=-1) at convcore.c:1790
#16 0x001f38d6 in ConverseRunPE (everReturn=0) at machine.c:2692
#17 ConverseInit (argc=<optimized out>, argv=0xbe7ffba4, fn=<optimized out>, usc=<optimized out>, everReturn=0)
    at machine.c:2910
#18 0x000fedb2 in main (argc=<optimized out>, argv=<optimized out>) at main.C:18

```

Only tickled by synctest, tempotest, callback, and queens.  Not coincidentally, the only codes in the test or examples tree that use [threaded] entry methods.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-19 20:59:51*

---
(u)jcontext threads work fine, because I've forced Fortify support off on those library builds. I'm working on disabling it for QT in #502 as well. You only see crashes with optimization, because the checks are only enabled when the compiler is doing enough analysis to insert them.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-21 00:53:43*

---
http://charm.cs.uiuc.edu/gerrit/551
