### ISSUE TITLE
Allow arbitrary ordering of options when building charm

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#513]
*Original author: Lukasz Wesolowski*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/513*

---
Build options are not parsed correctly under some orderings of the options. This should be fixed so that any ordering will work.

**Comment by jcphill** [comment]
*Original date: 2014-06-05 12:29:56*

---
Examples?

**Comment by stwhite91** [comment]
*Original date: 2018-04-29 23:00:10*

---
A fix for at least part of the issue is here: ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3997/~~ https://github.com/UIUC-PPL/charm/commit/3d83d86e6090af25151e3a3a72dcf2bcfeb5eb97
