### ISSUE TITLE
fix pthread_setaffinity_np error handling

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#519]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/519*

---
Since bug 501 is delayed to 6.0.1 I've broken out this fix to pthread_setaffinity_np() error handling.

The old code assumed that pthread_setaffinity_np() set errno and returned 0 or -1 like setaffinity, but it actually returns the full error code.  This patch (emailed to core) sets errno to the return value of pthread_setaffinity_np() so that perror() works.

[thread_affinity_errno.patch](https://github.com/UIUC-PPL/charm/files/3536442/thread_affinity_errno.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2014-06-17 17:34:44*

---
Patch looks good, applying. Thanks

**Comment by PhilMiller** [comment]
*Original date: 2014-06-18 12:45:38*

---
Jim: for future issues for which you have a patch prepared, feel free to submit them directly to Gerrit. We're not going to be strict about an open issue for every change to the codebase.
