### ISSUE TITLE
Build and test Charm++ applications as part of regular testing

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#52]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/52*

---
No body.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-12 17:18:38*

---
I believe Jenkins integration does this for new commits.

**Comment by mprobson** [comment]
*Original date: 2015-02-12 17:21:07*

---
Nikhil is correct, we currently test NAMD, OpenAtom, and ChaNGa as part of our Charm verification suite for new commits. Is there something beyond this that needs to be integrated or should we close this issue? The only thing I can think of is maybe integrating Episimdemics or Ross tests.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-12 17:26:35*

---
Agreed, this can be closed out.
