### ISSUE TITLE
Ignored Unrecognized argument -U_FORTIFY_SOURCE on Windows

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#520]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/520*

---
Many messages of this type on Windows builds:

../bin/charmc  -optimize -production   -I.   -c -o convcomlibstrategy.o convcomlibstrategy.C
Ignored Unrecognized argument -U_FORTIFY_SOURCE

It appears that unix2nt_cc does not handle -U arguments.  This doesn't appear to have any functional impact.

The option comes from conv-mach-opt.sh when building --with-production:

$ cat /usr/tmp/charm-6.6-build-2014-Jun-13-28073-multicore-win64/charm-6.6.0-rc3/multicore-win64/include/conv-mach-opt.sh
1. Built-time options header, automatically generated by charm/build
[ -z "$CHARMINC" ] && CHARMINC="."
CMK_NO_BUILD_SHARED=true
BUILDOPTS="-optimize -production "

OPTS_CC="$OPTS_CC -U_FORTIFY_SOURCE"   # Option added by configure script's error checking section

OPTS_CXX="$OPTS_CXX -U_FORTIFY_SOURCE"   # Option added by configure script's error checking section

CMK_TRACE_ENABLED=0   # Option added by configure script's  section

CMK_CHARMDEBUG=0   # Option added by configure script's  section

CP="cp -p"   # Option added by configure script's cp command section

**Comment by PhilMiller** [comment]
*Original date: 2014-10-21 19:11:51*

---
http://charm.cs.uiuc.edu/gerrit/#/c/410/
