### ISSUE TITLE
SDAG case constructs and Bigsim traces

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#53]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/53*

---
Inspired by some other discussion, I went to look at the implementation of SDAG case clauses to see how they'd interact with Bigsim emulator trace recording. It looks like the natural result they'll produce is a dependence of the when that gets satisfied on the incoming messages that satisfied it and the preceding event, as it should be. This is perfect in the purely non-speculative case, where no messages that might match other whens in the case ever appear.

In the speculative case, I'm concerned that some messages might be improperly associated to multi-entry whens that never end up getting satisfied. I could picture this producing misleading traces or broken traces, or even crashing the runtime, though I'm uncertain which without further examination. We should try this and make sure that we haven't broken the bit of Bigsim that depends on SDAG.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-07 19:06:39*

---
Bilge and I were working on BigSim recently and found that sdag + bigsim emulation does not work for simple cases too. At the least, I wish to find the reason. Jonathan may already know?

**Comment by PhilMiller** [comment]
*Original date: 2015-09-22 20:11:47*

---
Nikhil notes that we're not generally using Charm code to generate these traces, and there are other issues if we want to do that. Not important for production, only for research. Thus, postpone.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 18:45:36*

---
Its been a year since the last update.  If this is important someone should start work.  If it isn't, the priority should be changed to low.

**Comment by matthiasdiener** [comment]
Bigsim has been removed in #2703.
