### ISSUE TITLE
ckcheckpoint Segfaults when CkIO is used

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#530]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/530*

---
To reproduce on a workstation:

1) checkout the trq/ckio branch of changa (this is the branch that uses the
ckio library)
2) build changa
3) go into the teststep directory and run "make testrestart"

The first checkpoint after an output (using CkIO) gets a SEGV at:
#0  CkPupArrayElementsData (p=..., notifyListeners=1) at ckcheckpoint.C:448
448               CKLOCMGR_LOOP(mgr->iterate(counter););

I suspect this has to do with checkpointing deleted arrays.  Compare the fix that was made in commit 5d25973051ce6f8c82ffed41342b317b3527a3ad

**Comment by PhilMiller** [comment]
*Original date: 2014-07-31 21:43:46*

---
As noted in Gerrit, the changes leading up to 335 pass at least my local testing, including restart on different PE counts from the checkpoint.
