### ISSUE TITLE
CkIO miscalculates number of stripes for large files.

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#531]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/531*

---
In Director::prepareWriteSession(), an int is used for the calculation of number of stripes.  This overflows for file sizes bigger than 2^31, and gets the wrong number of stripes.  Here is a proposed patch:

--- a/src/libs/ck-libs/io/ckio.C
+++ b/src/libs/ck-libs/io/ckio.C
`` -111,7 +111,8 `` namespace Ck { namespace IO {
           Options &opts = files[file].opts;
 
           // XXX: Replace with a direct calculation
-          int numStripes = 0, o = offset;
+          int numStripes = 0;
+          size_t o = offset;
           while (o < offset + bytes) {
             numStripes++;
             o += opts.peStripe - o % opts.peStripe;

**Comment by rbuch** [comment]
*Original date: 2014-07-24 22:33:08*

---
http://charm.cs.uiuc.edu/gerrit/#/c/320/
