### ISSUE TITLE
CthSuspend should detect corruption before firing other assertions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#532]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/532*

---
If a user code allocates too much data on a Cth thread stack, it can end up running way off the end of the normally limited-size stack that we allocate by default (a few kilobytes). This means that it will overwrite the thread control structure that describes the identity and state of each user-level thread we're running. This fault exhibits as the assertion failure "Reason: Fatal Error> trying to suspend a non-suspendable thread!", because the bit saying whether the thread is suspendable or not gets overwritten with zero.

To spare users such an inscrutable error, the Cth API routines (when error checking is enabled) should all check that the magic number in the thread struct is still right, and fail with an error suggesting the following if it's changed
* Run with a large value of `+stacksize` and see if the error goes away
* Move large data allocations from the stack to the heap
* Check for and correct buffer overruns of stack-allocated objects

This came up in helping prepare a Charm++ parallelization of CoHMM at LANL during my visit there. If not for old email discussion on core-ppl that I had archived, I would not have been able to figure this out all, rather than the hour or two that it took to resolve.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2014-10-14 18:30:06*

---
I implemented a simple sanity check of magic number and stack length in CthSuspend. It is checked in for review.
