### ISSUE TITLE
NAMD hangs on Edison XC30

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#533]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/533*

---
v6.6.0-rc3-87-g8f0a0cd gni-crayxc-smp built July 6 hangs during runs, occasionally also crashes but ATP doesn't appear to work and I haven't seen any stack traces, just errors like this:

------------- Processor 179078 Exiting: Called CmiAbort ------------
Reason: Converse zero handler executed-- was a message corrupted?
aborting job:
Converse zero handler executed-- was a message corrupted?

or sometimes:

_pmiu_daemon(SIGCHLD): [NID 02639] [c5-1c2s3n3] [Thu Jul 17 20:54:55 2014] PE RANK 46 exit signal Segmentation fault

**Comment by rbuch** [comment]
*Original date: 2014-07-24 20:51:58*

---
I haven't been able to reproduce this yet.  On what scale (number of processors or total run time) did you experience these failures?

On an unrelated note, I'm getting failures trying to run apoa1.  I am getting "FATAL ERROR: Error opening XSC output file ~/data/apoa/apoa1-out.xsc: No such file or directory" even though the file exists and has suitable permissions.

**Comment by jcphill** [comment]
*Original date: 2014-07-25 14:35:13*

---
This is user-reported. I haven't been able to reproduce it myself.
I assume your output error is that the directory ~/data/apoa doesn't exist.

**Comment by rbuch** [comment]
*Original date: 2014-07-25 17:51:06*

---
Okay, I'll keep trying, then.

It seems my issue was that I used ~ in my pathname.  Changing it to use the full absolute path worked.

**Comment by jcphill** [comment]
*Original date: 2014-07-28 15:56:30*

---
Gengbin sent me a patch on Friday and I built new binaries.  The user reports he hasn't seen any crashes since then.  We'll give it a few more days to be sure but I would suggest getting Gengbin's changes checked in ASAP.
