### ISSUE TITLE
Charm++ canot compile on JYC with new PE

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#534]
*Original author: Gengbin Zheng*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/534*

---

With the new programming environment on JYC, building Charm++ fails at link time with error of not linking libhugetlbfs library.
This seems to be Cray bug with the compiler wrapper.

Just documenting the issue here, no action item is needed.

**Comment by nikhil-jain** [comment]
*Original date: 2014-07-28 16:20:27*

---
How about we add library paths and libraries to our compilation scripts such as gni, hugepages etc? This will end our reliance on wrappers to provide libraries we need. (Currently we do such additions if building shared libraries/binaries).

**Comment by pplimport** [comment]
*Original author: Gengbin Zheng*
*Original date: 2014-08-05 16:35:47*

---
Cray has fixed it on JYC.
Seems to be some installation problem.

**Comment by jcphill** [comment]
*Original date: 2014-08-05 23:56:37*

---
New link failure building NAMD with CUDA on JYC but not without CUDA or on Blue Waters:

/u/sciteam/jphillip/charm-6.6/gemini_gni-crayxe-persistent-smp/bin/../lib/libcon
v-util.a(CrayNid.o): In function `getMeshCoord':
CrayNid.c:(.text+0x6d): undefined reference to `rca_get_meshcoord'
/u/sciteam/jphillip/charm-6.6/gemini_gni-crayxe-persistent-smp/bin/../lib/libcon
v-util.a(CrayNid.o): In function `getDimension':
CrayNid.c:(.text+0x10e): undefined reference to `rca_get_max_dimension'
/u/sciteam/jphillip/charm-6.6/gemini_gni-crayxe-persistent-smp/bin/../lib/libcon
v-util.a(CrayNid.o): In function `pidtonid':
CrayNid.c:(.text+0x2d0): undefined reference to `rca_get_meshcoord'
/usr/bin/ld: link errors found, deleting executable `namd2'

On further investigation, having module cudatoolkit loaded causes the link error.  I tested with both cudatoolkit/5.5.22-1.0502.7944.3.1 and
cudatoolkit/5.5.20-1.0402.7700.8.1 and both produce the same error, but cudatoolkit/5.0.35 appears to work.  Note that Blue Waters with
cudatoolkit/5.5.20-1.0402.7700.8.1 works fine.

Currently Loaded Modulefiles:
  1) modules/3.2.6.7
  2) nodestat/2.2-1.0502.49618.2.32.gem
  3) sdb/1.0-1.0502.50558.6.21.gem
  4) alps/5.2.0-2.0502.8594.12.4.gem
  5) lustre-cray_gem_s/2.5_3.0.82_0.7.9_1.0502.7780.16.1-1.0502.16013.10.3
  6) udreg/2.3.2-1.0502.8413.2.10.gem
  7) ugni/5.0-1.0502.8670.4.22.gem
  8) gni-headers/3.0-1.0502.8554.7.6.gem
  9) dmapp/7.0.1-1.0502.8638.10.85.gem
 10) xpmem/0.1-2.0502.50559.4.2.gem
 11) hss-llm/7.1.0
 12) Base-opts/1.0.2-1.0502.50561.3.1.gem
 13) craype-network-gemini
 14) cray-mpich/7.0.1
 15) atp/1.7.4
 16) pmi/5.0.4-1.0000.10161.132.18.gem
 17) cray-libsci/13.0.0
 18) gcc/4.8.1
 19) craype/2.1.3
 20) moab/8.0
 21) torque/4.2.8
 22) craype-interlagos
 23) java/jdk1.7.0_45
 24) globus/5.2.4
 25) gsissh/6.2p2
 26) altd/altd
 27) darshan/2.2.8
 28) scripts
 29) user-paths
 30) PrgEnv-gnu/5.2.14
 31) rca/1.0.0-2.0502.53282.8.1.gem
 32) craype-hugepages8M
 33) cudatoolkit/5.5.22-1.0502.7944.3.1
 34) fftw/3.3.4.0

Celso is trying to reproduce with a simpler example that uses rca.

**Comment by rbuch** [comment]
*Original date: 2015-01-22 20:48:27*

---
I assume this isn't a valid bug anymore due to the flux of JYC, but Robert Brunner is going to attempt building NAMD with CUDA on JYC and will report on its status (as I don't have access to JYC).

**Comment by jcphill** [comment]
*Original date: 2015-02-09 19:08:15*

---
I think the is addressed by the following workaround:
export PE_PKGCONFIG_LIBS=cray-rca:$PE_PKGCONFIG_LIBS

**Comment by rbuch** [comment]
*Original date: 2015-02-09 22:36:55*

---
Robert corroborated Jim's fix.  He said the following:

"1. copy rca module file to your home:

   cp /opt/cray/gem/modulefiles/rca/1.0.0-2.0502.53711.3.125.gem ~

2. edit module file, adding the following line:

   prepend-path PE_PKGCONFIG_LIBS cray-rca

3. module unload rca

4. module load ./1.0.0-2.0502.53711.3.125.gem

We have gcc 4.9.0 installed on jyc, but Cray reports that 4.9.0 is incompatible with CUDA, so 4.8.2 is still the default."
