### ISSUE TITLE
Data races in handler registration and assignment to global index variables

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#537]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/537*

---

```
// Converse handler registration writing handler indices to a global variable - that write should be made to happen just once
SUMMARY: ThreadSanitizer: data race isomalloc.c:2299 init_comm
SUMMARY: ThreadSanitizer: data race isomalloc.c:2301 init_comm
SUMMARY: ThreadSanitizer: data race isomalloc.c:2302 init_comm
SUMMARY: ThreadSanitizer: data race isomalloc.c:2304 init_comm
SUMMARY: ThreadSanitizer: data race init.C:941 initQd
SUMMARY: ThreadSanitizer: data race init.C:942 initQd
SUMMARY: ThreadSanitizer: data race ccs-builtins.C:643 CWebInit()
SUMMARY: ThreadSanitizer: data race conv-ccs.c:532 CcsInit
SUMMARY: ThreadSanitizer: data race cpuaffinity.c:602 CmiInitCPUAffinity
SUMMARY: ThreadSanitizer: data race cpuaffinity.c:604 CmiInitCPUAffinity
SUMMARY: ThreadSanitizer: data race cputopology.C:412 LrtsInitCpuTopo

// Charm handler registration, as above
SUMMARY: ThreadSanitizer: data race init.C:1241 _initCharm(int, char**)
SUMMARY: ThreadSanitizer: data race init.C:1245 _initCharm(int, char**)
SUMMARY: ThreadSanitizer: data race init.C:1248 _initCharm(int, char**)
SUMMARY: ThreadSanitizer: data race init.C:510 _exitHandler(envelope*)
SUMMARY: ThreadSanitizer: data race ckarray.C:753 _ckArrayInit()
SUMMARY: ThreadSanitizer: data race NullLB.C:47 lbprocinit()
```

The registration code needs to be modified to uniformly use functions that get the global initialization right internally

**Comment by PhilMiller** [comment]
*Original date: 2014-11-09 16:56:44*

---
Ping. We'd like to have a fix for this merged before the core meeting. This should be fairly simple, and would make a substantial difference for people who want to use ThreadSanitizer.

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-02 00:03:22*

---
Ping! Please tend to this.

**Comment by rbuch** [comment]
*Original date: 2014-12-02 00:09:24*

---
There's a commit waiting for review at http://charm.cs.illinois.edu/gerrit/#/c/381/.

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-02 00:12:05*

---
Ah nice..thanks for updating.

**Comment by PhilMiller** [comment]
*Original date: 2015-08-17 16:14:33*

---
Review had easy to address comments 7 months ago

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 23:20:50*

---
This has sat around for *2 years*. Please just finish the patch already.

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:36:16*

---
Still hanging in gerrit, waiting on cleanup...

**Comment by PhilMiller** [comment]
*Original date: 2017-10-11 19:37:47*

---
Ronak noted that the fix ran into trouble in rebasing and cleaning up. He'll add details here and/or on Gerrit

**Comment by rbuch** [comment]
*Original date: 2017-10-11 19:41:20*

---
Some fixes that I've been trying to do for this (editing calls to happen only once and inserting barriers to prevent other threads from getting too far) have been causing segfaults in my testing, and I've been unable to debug them (trying to attach a debugger causes hangs). I'll add manual debugging prints or something along those lines to get more insight.

**Comment by rbuch** [comment]
*Original date: 2017-10-19 22:22:00*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/381/~~ https://github.com/UIUC-PPL/charm/commit/be7ee10917004cb13a8fd0c27fd0f026bf774c43
