### ISSUE TITLE
test/converse/machinetest fails in net smp 

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#54]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/54*

---
tests/converse/machinetest example gives segmentation violation for smp version in net build. In non smp build, it is working fine. 
This is the case for both original and lrts ported net layer.

**Comment by ericjbohm** [comment]
*Original date: 2013-03-01 21:26:55*

---
Ask senior person for help as needed.  It is possible that the test itself is obsolete.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-19 20:04:37*

---
http://charm.cs.uiuc.edu/gerrit/#/c/545/

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-27 21:45:50*

---
More issues have shown up. The exit is not clean. Looking at it.
