### ISSUE TITLE
SMP mesage passing must enforce memory ordering consistency

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#541]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/541*

---
When one PE passes a message to another PE within the same process, memory consistency should require that subsequent code executed as a result of that message read the right data.

I believe the right semantics for this are as follows:
1. Placing a message in a queue should be under `memory_order_release`
1. Receivers like the comm thread that will only read from shared data derived from the message need to pick up the message with `memory_order_consume`
1. Receivers of a message that may infer broader synchronization from the message's delivery (i.e. some shared state outside the mesage having been updated) need to pick up the message with `memory_order_acquire`

The distinction between the latter two cases matters on machines that implement consistency of 'dependent loads' - if all loads to shared data is through the message itself, then they are guaranteed to be consistent with what was written before the message's deposit. On machines like POWER and ARM, this can provide a "performance advantage":http://preshing.com/20140709/the-purpose-of-memory_order_consume-in-cpp11/. However, it's not clear whether receivers will necessarily be able to make that distinction without introducing some additional overheard (like a separate queue to/from the comm thread). If they can't, then we'll just have to use `memory_order_acquire` uniformly.

**Comment by ericjbohm** [comment]
*Original date: 2017-10-25 18:26:29*

---
This appears to require an audit of memory consistency usage throughout machine-smp.

**Comment by PhilMiller** [comment]
*Original date: 2017-11-29 21:07:23*

---
Per the C++ standards committee, `memory_order_consume` has been temporarily deprecated while its broken definition gets fixed. Just use `memory_order_acquire` in its place until then.

**Comment by nitbhat** [comment]
*Original date: 2018-03-19 15:38:21*

---
Gerrit: ~~https://charm.cs.illinois.edu/gerrit/#/c/3877/~~ https://github.com/UIUC-PPL/charm/commit/dda4185ac4010c0a716ea88e5f0779af1899886c
