### ISSUE TITLE
NAMD with persistent messages crashes right after startup on Edison XC30

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#542]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/542*

---
Testing gni-crayxc-persistent-smp --with-production on Edison, before Gengbin's fix (and also on Rhea back in January), NAMD STMV on 30 or 32 nodes, finishes startup and then:

 Info: Finished startup at 17.1791 s, 3559.63 MB of memory in use
 
 ------------- Processor 598 Exiting: Called CmiAbort ------------
 Reason: Converse zero handler executed-- was a message corrupted?
 
 aborting job:
 Converse zero handler executed-- was a message corrupted?

or sometimes just a segmentation fault.  The smaller apoa1 runs fine.

With Gengbin's fix:

 Info: Finished startup at 15.0664 s, 3559.76 MB of memory in use
 
 ------------- Processor 751 Exiting: Called CmiAbort ------------
 Reason: Could not malloc()--are we out of memory? (used: 14.841MB)
 aborting job:
 Could not malloc()--are we out of memory? (used: 14.841MB)

gni-crayxc-smp runs fine.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-11-04 20:44:08*

---
I am able to reproduce this on Edison with 32 nodes.  After doing debugging, I turned off REMOTE_EVENT, the program runs correctly.  This is the related problem with ChaNGA crashing on XC30, not really a persistent problem. 

It seems that remote event notification on XC30 with dragonfly network  does not work as well as XE6 with Gemini
