### ISSUE TITLE
charmrun under causalft should respect ++local

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#543]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/543*

---
When running a message logging (and possibly just online checkpoint/restart) FT net build of Charm++, `charmrun` will try to launch replacement processes to take the place of failures. In testing environments, it's convenient to run with `++local` so that there's no need to SSH to remote nodes. When running the `causalfttest` targets, I found that charmrun tries to use ssh to launch the replacement, in spite of ++local.

Obviously, fixing this is not really helpful to production-like uses of the online FT builds, since losing a single process on a node is not really the kind of failure we expect. The testing use case is valuable, though.

**Comment by epmikida** [comment]
*Original date: 2015-10-26 21:24:01*

---
Might involve some refactoring of charmrun. At the point where we restart a node, a lot of the stuff used in local startup has already been lost. Charmrun could probably use a bit of refactoring as it is anyways.

**Comment by stwhite91** [comment]
*Original date: 2018-04-29 23:02:02*

---
causalft and mlogft are not production features and have been broken since at least 64-bit IDs were merged for 6.8.0
