### ISSUE TITLE
Port Qlogic-specific initialization parameters from net-ibverbs to lrts-verbs

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#545]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/545*

---
Tracking bug for change 318 in Gerrit, so that there's a visible record of why the release isn't tagged.

**Comment by ericjbohm** [comment]
*Original date: 2014-08-12 22:43:45*

---
On further study, the recovery code from net-ibverbs does not work on Omega.  Therefore adding it to verbs (lrts) for the 6.6 release is not critical.  It may be possible to automatically handle qlogic variations, but that will require significantly more study.  Phil and I do not think it is worth holding 6.6 for that.  Probably not worth PPL time given the fact that a function build is already achievable with the addition of the -DQLOGIC flag.  Will note platform specific tinkering as a todo, probably more appropriate for Charmworks.
