### ISSUE TITLE
CkIO is not SMP safe

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#550]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/550*

---
The Manager constructor in ckio.C sets the global variable "manager" to the "this" pointer.  All accesses
through "manager" on the node will refer to the same Manager object: the last one to call the constructor.

In particular the call to mananger->get(file_) at the top of the WriteSesson constructor can be executed by many PEs at once leading to a race condition on "files[token].fd" and the CmiOpen()s.  The result is that a file can be opened many times on the same node.  The Manager::doClose() method is executed in serial, so the file only gets closed once.  The end result is that a program using CkIO (e.g. ChaNGa) running on an SMP machine runs out of file descriptors and crashes.

I've got a kludgy fix: putting a CmiLock() around the if() block at line 192 in ckio.C.  This let's ChaNGa run without crashing; however, I think there is a deeper design problem here that needs to be addressed.

I need this working for my big runs on Blue Waters, so let me know if you want to see my fix on gerrit.

**Comment by PhilMiller** [comment]
*Original date: 2014-09-04 05:25:50*

---
The right fix would be for `Manager *manager` to be Ckpv instead of a simple global, so that each PE points at its own instance of the group. If you're comfortable implementing that, please assign this to yourself and go ahead. Otherwise, please assign it to Ronak.

**Comment by trquinn** [comment]
*Original date: 2014-09-04 17:42:45*

---
Proposed patch is at http://charm.cs.uiuc.edu/gerrit/364

**Comment by trquinn** [comment]
*Original date: 2014-09-17 22:05:52*

---
The patch has been merged.
