### ISSUE TITLE
lbuserdata generates segfaults

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#552]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/552*

---
Repeat by:
build ChaNGa net-linux-x86_64 smp --enable-lbuserdata -g -O2
"make" ChaNGa

In changa/teststep, run

../ChaNGa ++ppn 4 +balancer OrbLB test_pg.param

Segfault happens at "Step: 1.0"

The traceback is:
#0  0x00000030766896d0 in memcpy () from /lib64/libc.so.6
#1  0x000000000075b709 in operator= (this=0x7fffe808e470, dp=0x7fffe835cd80)
    at ../bin/../include/lbdb.h:157
#2  operator= (this=0x7fffe808e470, dp=0x7fffe835cd80)
    at ../bin/../include/lbdb.h:190
#3  LBDB::GetObjData (this=0x7fffe808e470, dp=0x7fffe835cd80)
    at LBDBManager.C:305
#4  0x0000000000763342 in GetObjData (this=0x7fffe816efa0)
    at ../bin/../include/LBDatabase.h:318
#5  CentralLB::BuildStatsMsg (this=0x7fffe816efa0) at CentralLB.C:373
#6  0x0000000000766d46 in CentralLB::ProcessAtSync (this=0x7fffe816efa0)
    at CentralLB.C:221
#7  0x00000000006e5c14 in CkDeliverMessageFree (epIdx=376, msg=0x7fffe808df70, 
    obj=0x7fffe816efa0) at ck.C:593
#8  0x00000000006e5e96 in _invokeEntryNoTrace (epIdx=376, env=0x7fffe808df20, 
    obj=0x7fffe816efa0) at ck.C:637
#9  _invokeEntry (epIdx=376, env=0x7fffe808df20, obj=0x7fffe816efa0)
    at ck.C:648
#10 0x00000000006e6115 in _deliverForBocMsg (ck=<value optimized out>, 
    epIdx=376, env=0x7fffe808df20, obj=0x7fffe816efa0) at ck.C:1091
#11 0x00000000006e7d89 in _processForBocMsg (
    converseMsg=<value optimized out>, ck=0x7fffe807c8d0) at ck.C:1103
#12 _processHandler (converseMsg=<value optimized out>, ck=0x7fffe807c8d0)
    at ck.C:1245
#13 0x00000000007a8048 in CsdScheduleForever () at convcore.c:1850
#14 0x00000000007a814d in CsdScheduler (maxmsgs=<value optimized out>)
    at convcore.c:1786
#15 0x00000000007a26f7 in ConverseRunPE (everReturn=0) at machine.c:2693
#16 0x00000000007a2773 in call_startfn (vindex=0x2) at machine-smp.c:413
#17 0x0000003076e079d1 in start_thread () from /lib64/libpthread.so.0
#18 0x00000030766e886d in clone () from /lib64/libc.so.6

In LBUserData::operator=() we have:
(gdb) p data
$1 = 0x7fffe8371db0 "\210"
(gdb) p d
$2 = (const LBObjUserData &) `0x7fffe8171ef0: {data = 0x0}

The memcpy is segfaulting because NULL data in the argument to operator=() is not being checked.

**Comment by trquinn** [comment]
*Original date: 2014-10-21 18:17:20*

---
This has been fixed in gerrit change IDs I3b9828ca58eb3579f3030e7eb21d16b24715748c
and I3d100e876f3e16ab814252058f0cab1628e0ef8c

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 19:38:51*

---
Merged changes to fix this:
http://charm.cs.uiuc.edu/gerrit/#/c/371/
http://charm.cs.uiuc.edu/gerrit/#/c/372/

**Comment by pplimport** [comment]
*Original author: Anonymous*
*Original date: 2015-04-06 09:38:56*

---
(Edited to delete spam - Phil)
