### ISSUE TITLE
Bulk construction for regular sparse arrays

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#554]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/554*

---
Bulk construction is not available for sparse arrays.  This typically results in a big loop of element insertions in main::main (as in OpenAtom PairCalculator construction).  That results in a one to many pattern of constructor messages.  We know that pattern performs badly, and can even break some machine layers (i.e., PAMI)

Regular sparse arrays could be bulk constructed if each dimension is specified by : start, end, stride

Irregular sparse arrays could pass an arrays of indices for construction.  

In either case, the resulting set of indices can be partitioned and constructor messages generated in a distributed manner.

**Comment by PhilMiller** [comment]
*Original date: 2014-09-23 22:13:01*

---
Suggested interface: replace the 'size' fields in `CkArrayOpts` with a `{lower, upper, stride}` struct. For values passed as a single int (i.e. a size `s` in the given dimension), the resulting struct is `{0, s, 1}`. Note that this matches the 0-indexed half-open interval [0, s) style that we have now.

Then `CkArrayMap::populateInitial` can be adjusted to look at those strided structs.

**Comment by PhilMiller** [comment]
*Original date: 2014-10-28 21:14:51*

---
Any chance of getting this built this week, since there's an OpenAtom push going on?

**Comment by epmikida** [comment]
*Original date: 2014-10-28 21:22:56*

---
Yes. My current tasks for this week will probably permit me enough time to work on this as well, and my whole week is dedicated to OpenAtom.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 15:35:05*

---
This got implemented, right? Where's the fix?

**Comment by epmikida** [comment]
*Original date: 2015-08-05 23:30:45*

---
Merged in ~~https://charm.cs.illinois.edu/gerrit/753~~ https://github.com/UIUC-PPL/charm/commit/12051c5a3d9e889c8a0222949e641854ef576745
