### ISSUE TITLE
Charm++ reduction examples

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#561]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/561*

---
AllReduce and RedExample are exactly the same, except some minor changes - can also be combined with typed_reduction
These should all be combined to illustrate all reduce, multi dimension section reductions and typed reduction.

**Comment by bilgeacun** [comment]
*Original date: 2014-11-11 22:10:32*

---
Cleaned-up and combined all reduction examples in one reductions folder.

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-12 17:26:00*

---
Since Bilge has already done this.

**Comment by bilgeacun** [comment]
*Original date: 2015-10-27 21:08:56*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/421/~~ https://github.com/UIUC-PPL/charm/commit/bf934ba08c8564146cfac79f9e78b7209df271a9
