### ISSUE TITLE
Charm++ Molecular and Molecular2D examples

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#563]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/563*

---
Molecular and Molecular2D examples are both 2D, there are naming differences, not sure if they are significantly different

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-26 17:44:47*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/878/~~ https://github.com/UIUC-PPL/charm/commit/59cd1de40ebbf9d92346374f901cbf8f8c09e3ec
