### ISSUE TITLE
Charm++ cell example cleanup

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#566]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/566*

---
cell contains accelerator examples: name of the example can be more meaningful.
Accelerator subgroup to resolve issues, probably delete it and eventually resurrect accelerated entry methods.

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 20:46:48*

---
Wasn't the decision on this to just delete the code in question, since there are up-to-date replacements in the upcoming GPU/accel patch? If so, could you please just do that, and not leave this to linger?

**Comment by PhilMiller** [comment]
*Original date: 2017-10-02 20:48:21*

---
Or better, just review this if indeed that's the direction to go:
~~https://charm.cs.illinois.edu/gerrit/3092~~ https://github.com/UIUC-PPL/charm/commit/2b7c3c6a8effdb6455d1cd68ab91190814276857
