### ISSUE TITLE
Charm++ barnes-charm example cleanup

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#567]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/567*

---
barnes-charm example contains src and barnes folders inside, which are exactly the same.
Make sure it works

**Comment by harshithamenon** [comment]
*Original date: 2014-10-15 10:30:38*

---
When I did make test, it ran to completion without any errors. Whereas when Bilge ran it, it crashed with some input not found error. Bilge is aware of this and we will try to see what is the difference between the two runs.

**Comment by rbuch** [comment]
*Original date: 2016-03-08 20:28:26*

---
Any updates on this?

**Comment by stwhite91** [comment]
*Original date: 2016-03-29 21:19:54*

---
The duplicated src/ and barnes/ directories are weird, and when I try to run it I get an input error...

**Comment by ericjbohm** [comment]
*Original date: 2017-09-06 19:47:00*

---
Rationalize this with the one in its own repository.  Either there should only be one, or there should be a clear well understood reason for each with cross referencing.

**Comment by minitu** [comment]
*Original date: 2017-09-07 19:56:39*

---
The two folders `src` and `barnes` are exactly the same.
From looking at the git logs, Pretish tried to rename `barnes` to `src`, but left `barnes` in the process.
The `src` folder contains code from Stanford that I believe was used as reference to create the Charm++ version, so renaming it to `ref_src` instead.
Compilation initially failed for me because of `isnan` used in `Main.cpp`, so added tge following at line 4: `using std::isnan`.

**Comment by minitu** [comment]
*Original date: 2017-09-07 20:01:56*

---
Patch: ~~https://charm.cs.illinois.edu/gerrit/#/c/2995/~~ https://github.com/UIUC-PPL/charm/commit/d62df12c887c262a59687e30b4e80011a5c2e815
Wondering if we should get rid of this example altogether and just use the barnes benchmark that we have.

**Comment by minitu** [comment]
*Original date: 2017-09-18 22:06:30*

---
Removing `ref_src` folder entirely.

**Comment by minitu** [comment]
*Original date: 2017-09-19 18:53:12*

---
Using `std::isnan` failed on titan, so replaced all `isnan` occurences with `std::isnan`. The input file specified in `make test` is invalid which makes it crash; thus reinstated input file checking code in `code_io.C`. Problem is there doesn't seem to be an input file that conforms to the format used in `code_io.C`. I feel we should just get rid of this example and point people to the Barnes-Hut mini-app instead.

**Comment by minitu** [comment]
*Original date: 2017-09-20 20:44:47*

---
Removing the entire folder; Barnes-Hut mini-app should be the one used as it is well documented and works fine.
