### ISSUE TITLE
Charm++ jacobi examples 

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#569]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/569*

---
Cleanup all jacobi examples.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-10-14 20:50:47*

---
Fixed boundary condition bug, sending/receiving bug.  Cleaned up with better formatting.  Only kept Jacobi2d with 1d decomposition, Jacobi2d with 2d decomposition and Jacobi3d with 2 decomposition three examples.
