### ISSUE TITLE
problem with mempool for AMPI programs

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#57]
*Original author: Celso Mendes*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/57*

---
I believe that there is a problem with mempool in Charm++ and it's affecting AMPI programs in some cases.

For current tests on Cray systems, using the Cray compiler (cce), we are having to build the codes with a line like

ampicc -o prog prog.c -dynamic -thread context -swapglobals -memory os-isomalloc ...

The reasons for having to use those options are:

* -dynamic: we plan to invoke code that uses GPUs, and that requires dynamic linking
* -thread context: as suggested by Nikhil, this fixes some problems that had been observed in the past
* -swapglobals: this is the only feasible mechanism to handle globals with AMPI, as TLS would require static linking
* -memory os-isomalloc: suggested by Gengbin; needed for migration without having to pack/unpack data

So, using those options, the example code from the Charm++ distribution (tests/ampi/migration/) breaks on a Cray system if it is compiled with an AMPI built with the Charm++ version from the GIT repository on Fe.23/2013. This error has been observed on JYC for both the mpi-crayxe and gemini_gni-crayxe layers of Charm.

However, that works fine if the AMPI used is built from the contents of the Charm GIT repository that existed on Feb.8/2013, prior to various modifications implemented on the mempool functionality. To obtain that older version, these commands were used:

* git clone git://charm.cs.uiuc.edu/charm.git
* git reset --hard 92515ffdd2b84839c8daa787706f606e1ab7227e                (this is a commit prior to the mempool changes) 
* edit file src/arch/mpi-crayxe/conv-mach.h to #define CMK_AMD64 1         (recent change from Phil; needed so that swapglobals will work)
* edit file src/arch/gemini_gni-crayxe/conv-mach.h to #define CMK_AMD64 1  (similar to above)
* build AMPI:  ./build AMPI mpi-crayxe --disable-charmdebug                (having PrgEnv-cray set, to use the Cray compiler)

On JYC, I left a snapshot of the error above, under directory ~cmendes/BUG-AMPI/ where there is a Makefile that builds the successful version of the program (built with the older Charm version, named 'charm-PHIL') and the buggy version (built with 'charm-git'). There is a copy of the outputs from execution on two JYC nodes. The error message (which can be seen on file run.git_out) is like

Stack walkback for Rank 1 starting:
  [empty]`0x5555b7ffffff
  mempool_destroy`XTTorus.h:204
Stack walkback for Rank 1 done
Process died with signal 11: 'Segmentation fault'

The results from successful executions of the same program are under file run.PHIL_out.

Hence, I strongly suspect that the error is being caused by those changes to mempool on Feb.8/2013.

-Celso

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-06 18:38:24*

---
mempool shouldn't be freed till the very end - however freeing mempool can get very tricky, and that is what consumed time :)

**Comment by PhilMiller** [comment]
*Original date: 2013-03-07 00:51:02*

---
Celso says
> I just tested on JYC, with the reported example and a few others,
> and the new AMPI from today's repository after your fix works fine!
