### ISSUE TITLE
NAMD crashes if L2Atomics are enabled with PAMI LRTS

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#58]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/58*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 21:57:07*

---
Move already short description to title, so it doesn't look like a general dysfunction.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-06 22:15:37*

---
This issue was resolved by updating the manner in which LrtsQueue are created. There was a race condition during Queue creation hat has been resolved.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 23:25:07*

---
May as well mark it for the release :-)
