### ISSUE TITLE
Support out-of-tree builds

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#59]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/59*

---
--destination is buggy. --prefix should be supported.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-03 20:19:36*

---
Need to go looking for relative path references that go outside of the linked build tree.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-02 20:11:53*

---
This isn't going to happen in the very near term that we want to do the release on, so pushing it back.

Just a quick note, also, that charmxi is now built in a way that will allow for out-of-tree compilation.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:29:20*

---
Important from software maintenance. Updating to remind myself.

**Comment by PhilMiller** [comment]
*Original date: 2014-07-02 23:19:24*

---
Change 304 almost fully implements this. On systems that provide `realpath`, the `build` script can be run from anywhere to create the build tree and compile Charm++. Within that generated tree, makefiles and such all appear to work as intended.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-30 22:48:52*

---
Dusted off http://charm.cs.uiuc.edu/gerrit/#/c/304/ and found that it is closer to ready than previously thought.
