### ISSUE TITLE
[immediate] entry methods on multicore-* builds

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#596]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/596*

---
Per Eric Mikida
> I created a simple test program to check this. It creates a main chare, which creates a group. The group constructor broadcasts a message to the group. The broadcasted message contributes to a reduction that calls exit.
> 
> The program works as expected with normal messaging, but I went back to the MetaBalancer.ci file and noticed the entry methods were marked as immediate. If I mark the entry method as immediate in the test program, it never receives the broadcast messages and hangs forever.
> 
> When I built charm in net-linux the program ran as expected.
> 
> I can look into single stepping it with GDB to see if I can find out exactly where it hangs. Should this be something I work on for charm works or should I focus on more high-priority tasks?

Please add any other details necessary to clarify this and then we'll reassign it.

[group_bug.zip](https://github.com/UIUC-PPL/charm/files/3536513/group_bug.zip)

**Comment by PhilMiller** [comment]
*Original date: 2014-11-11 19:27:58*

---
As a short-term work-around, could you make a quick change that treats [immediate] as [expedited] on multicore builds where they'll otherwise just never get executed?

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-02 00:01:11*

---
Ping...we want release out of way.

**Comment by PhilMiller** [comment]
*Original date: 2014-12-02 18:41:57*

---
Please post the test case you developed, so that we can hand this off to someone else.

**Comment by epmikida** [comment]
*Original date: 2014-12-02 19:18:04*

---
Phil Miller wrote:
> Please post the test case you developed, so that we can hand this off to someone else.

How/where should I post it? Right now it's just on my laptop.

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-02 19:21:40*

---
You can post the file/tar here.

**Comment by epmikida** [comment]
*Original date: 2014-12-02 19:44:01*

---
Nikhil Jain wrote:
> You can post the file/tar here.

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-05 21:23:51*

---
I am fixing it for now by disabling IMMEDIATE messages for multicore. Review at: http://charm.cs.uiuc.edu/gerrit/#/c/442/

Quick review appreciated.
