### ISSUE TITLE
Unused tests in test/charm++

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#598]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/598*

---
If the test works, include them in the Makefile or fix them/remove them. Look at the subtasks.

**Comment by nikhil-jain** [comment]
*Original date: 2014-11-04 22:26:52*

---
Look at https://charm.cs.illinois.edu/redmine/issues/595 to get the current status of the subtask test.

**Comment by PhilMiller** [comment]
*Original date: 2016-10-13 21:23:24*

---
I think we can close this? All of the subtasks are now closed.
