### ISSUE TITLE
python

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#603]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/603*

---
No body.

**Comment by lifflander** [comment]
*Original date: 2015-02-09 19:44:50*

---
This test exercises the python interface for CCS. It is dependent on including headers and linking with a certain version of Python, module charmdebug_python, module PythonCCS. Hence, it should not be run as a test by default. However, it is useful as a test case for this particular functionality so it should remain in the codebase.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-10 02:56:03*

---
Sounds reasonable to me. Closed.
