### ISSUE TITLE
topology

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#604]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/604*

---
No body.

**Comment by mprobson** [comment]
*Original date: 2015-02-12 20:58:14*

---
Test runs fine and tests distinct functionality (topo manager). I've added it to the Makefile so that it's now part of our test suite.

[[http://charm.cs.illinois.edu/gerrit/#/c/520/]]
