### ISSUE TITLE
broadcast

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#605]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/605*

---
No body.

**Comment by harshithamenon** [comment]
*Original date: 2015-02-09 22:11:53*

---
This test basically does a point to point broadcast and measures the time taken for it. 
Array element 0 sends point to point messages to other array elements, waits to receive a ack and then measures the time for point to point broadcast.

**Comment by harshithamenon** [comment]
*Original date: 2015-02-09 22:26:25*

---
I don't think this test needs to be in the autobuild.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-10 15:14:14*

---
If it's not a useful test, then please delete it.
