### ISSUE TITLE
io

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#606]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/606*

---
No body.

**Comment by ericjbohm** [comment]
*Original date: 2015-03-19 20:48:17*

---
Any progress on this?

**Comment by ericjbohm** [comment]
*Original date: 2015-03-26 20:27:43*

---
no sign of progress. Please report on this.

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2015-03-26 20:31:21*

---
Sorry, forgot to reply to this earlier. I am looking into this now.

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2015-03-26 20:51:17*

---
Test runs successfully on loyalty

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2015-03-26 21:20:16*

---
Submitted to gerrit for review.
Change-Id: I8ce2e21dbd317e5cd388cc4bbae07525c50c49b2

**Comment by PhilMiller** [comment]
*Original date: 2015-03-27 17:19:44*

---
Change merged. Thanks.
