### ISSUE TITLE
reductiontesting

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#607]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/607*

---
No body.

**Comment by bilgeacun** [comment]
*Original date: 2015-01-20 20:35:37*

---
This test has no test target. 

It tests section reductions in 1D - 2D - 3D arrays. Section reductions and reductions are already tested  in *xcastredn* and *delegation/multicast*. However these are only with 1D arrays. 

If testing this in 2D-3D arrays is necessary, we can either add a test target for *reductiontesting* or add 2D-3D test cases for *xcastredn* and *delegation/multicast*

**Comment by bilgeacun** [comment]
*Original date: 2015-10-27 21:06:46*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/501/~~ https://github.com/UIUC-PPL/charm/commit/0d15063fcd326f52f4e0680a0e09ab24ee846de4
