### ISSUE TITLE
PAMI NAMD Exit issue

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#61]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/61*

---
Test that PAMI NAMD exits cleanly on PAMI.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-03 06:41:05*

---
Seems to be working fine with latest charm.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-04 01:00:26*

---
Yanhua had reported that NAMD exits with a seg fault. Nikhil believed it was fixed with Sameer's last commit, hence it was retested to make sure there was no over sight.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-05 22:55:06*

---
Joseph Baker confirmed that dependent jobs are running correctly now.
