### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#614]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/614*

---
No body.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-01-22 18:30:04*

---
Code needs parameters, but none in make test. Code did not check that.
It works with many processors, but not with only one. I need to dig more.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-19 18:51:53*

---
This test does not have any added value compared to pingpong. So, I have deleted it.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-08 19:24:09*

---
I see no change for this either in the git logs or awaiting review on gerrit. Please post it.

**Comment by ericjbohm** [comment]
*Original date: 2015-03-26 20:28:25*

---
no sign of progress, please report on this.
