### ISSUE TITLE
startuptest

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#615]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/615*

---
No body.

**Comment by ericjbohm** [comment]
*Original date: 2015-01-21 01:00:25*

---
Updated to current CkArrayIndex API.  Fixed bug in Makefile.


As far as I can tell, this functionality is not being tested elsewhere.  So, I added it to the top level test Makefile.
