### ISSUE TITLE
hello-crosscorruption

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#616]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/616*

---
No body.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-01-22 19:40:03*

---
CkExit was commented, that explained the hang. I need to dig more to see the purpose of the test and to check the result.

**Comment by ericjbohm** [comment]
*Original date: 2015-03-26 20:28:42*

---
no sign of progress, please report on this.
