### ISSUE TITLE
Rename windows commands to not reference Windows NT

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#617]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/617*

---
This is related to Feature #574. The commands unix2nt_* should be renamed to something else. My current suggestion is unix2ms_*

**Comment by PhilMiller** [comment]
*Original date: 2014-11-09 16:44:45*

---
This doesn't really fit in with the goal of a pure bug-fix release.  Deferred.

**Comment by stwhite91** [comment]
*Original date: 2018-04-29 23:04:49*

---
Is this still an issue? If not, close it.

**Comment by evan-charmworks** [comment]
*Original date: 2018-12-19 19:41:47*

---
While the operating system as a whole no longer contains NT in its name, I believe the kernel is still called the "NT kernel", so keeping NT in the name is as valid as calling macOS "Darwin" or GNU/Linux "Linux".

**Comment by mprobson** [comment]
*Original date: 2019-02-20 21:43:11*

---
Seems like an unnecessary change, rejected (but feel free to over-ride if you have strong opinions on this...)
