### ISSUE TITLE
liveViz does not work with 1 pe

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#619]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/619*

---
If the program is running with +p1, the livdliv will not connect on client side. Is this a known problem?

**Comment by PhilMiller** [comment]
*Original date: 2015-04-30 18:05:03*

---
LiveViz should work on any number of PEs, even in a stand-alone run. If it doesn't this needs to be fixed. CCS in general is a key feature of Charm++

**Comment by xiangni** [comment]
*Original date: 2015-08-17 17:50:34*

---
Verified that liveViz fails to work with +p1.
