### ISSUE TITLE
missing args to main

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#62]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/62*

---
Add argument message to main in test and examples

**Comment by PhilMiller** [comment]
*Original date: 2013-03-03 08:10:03*

---
All fixed - there were only 8 of them, but the scripting approach was more fun. They were conveniently regular - every single one was written precisely "entry main();", so the final sed once I found them was really easy. The finding them distinctly was a bit trickier.

Eric- please build for yourself to confirm, then close.

**Comment by ericjbohm** [comment]
*Original date: 2013-03-04 19:06:49*

---
I think you missed a few.  These don't show up in a make test, but are part of the examples distribution.

grep -ri 'main(\s*)' examples
./charm++/hello/hello.ci:    entry main();
./charm++/barnes-charm/barnes.ci:    entry Main();
./charm++/state_space_searchengine/3SAT/soln-checker.py:def main():
./charm++/state_space_searchengine/3SAT/soln-checker.py:    main()
./charm++/cell/md/main.h:    ~Main();
./charm++/cell/md/main.C:Main::~Main() {
./charm++/f90charm/hello2D/hellof.f90:      SUBROUTINE f90charmmain()
./charm++/f90charm/hello/hellof.f90:      SUBROUTINE f90charmmain()
./charm++/f90charm/ldbDemo/ldbDemof.f90:      SUBROUTINE f90charmmain()
./multiphaseSharedArrays/simpleTestVarsize/testV.C:main()
./multiphaseSharedArrays/matmul/mm_sequential.C:int main()
./multiphaseSharedArrays/matmul/mm_sequential.C:main()
./multiphaseSharedArrays/matmul/sequential/mm2mkn.C:main()
./multiphaseSharedArrays/matmul/sequential/maxflops.c:main()
./multiphaseSharedArrays/matmul/sequential/mm2.C:main()
./multiphaseSharedArrays/matmul/sequential/mm1mkn.C:main()
./multiphaseSharedArrays/matmul/sequential/mm1.C:main()
./amr/cfd/cfdAMR.ci:   entry main();
./amr/jacobi2D/jacobi2DAMR.ci:   entry main();
./amr/jacobi2Dthesis/jacobi2DAMR.ci:   entry main();
./bigsim/tools/model_based_rewrite/interpolatelog.C:int main()
./bigsim/tools/rewritelog/interpolatelog.C:int main()
./bigsim/tools/changelog/changelog.C:int main()
./bigsim/tools/loadlog/loadlog.C:int main()
./bigsim/tools/buildlog/buildlog.C:int main() {
./bigsim/tools/rewritelog-old-format/interpolatelog.C:int main()
./pose/HiSim/Main/pgm.ci:    entry main();
./pose/SimBenchmark/pgm.ci:    entry main();
./pose/PHOLD/phold.ci:    entry main();
./pose/MiniNet/mininet.ci:    entry main();
./pose/LBSim/sched.ci:    entry main();
./pose/ASIM/pgm.ci:    entry main();
./pose/Ring/pgm.ci:    entry main();
./pose/PatternGen/pgm.ci:    entry main();
./pose/ChunkSim/pgm.ci:    entry main();
./converse/pingpong/pingpong.C:CmiStartFn mymain()
./converse/pingpong/pingpong_multipairs.C:CmiStartFn mymain()
./converse/pingpong_multi/pingpong.C:CmiStartFn mymain()
./collide/collidethread/hello.ci:    entry main();
./collide/collidecharm/hello.ci:    entry main();

**Comment by PhilMiller** [comment]
*Original date: 2013-03-04 23:26:27*

---
You were a bit generous, since only the .ci files are relevant, but there are many good catches. Here's my result set:
```
$ grep -P -r -nH --include '*.ci' -i 'entry.*main\(\s*\);' examples/ tests/ | column -s : -t
examples/charm++/barnes-charm/barnes.ci                        28      entry Main();
examples/charm++/hello/hello.ci                                20      entry main();
examples/amr/jacobi2Dthesis/jacobi2DAMR.ci                     7      entry main();
examples/amr/cfd/cfdAMR.ci                                     9      entry main();
examples/amr/jacobi2D/jacobi2DAMR.ci                           5      entry main();
examples/pose/Ring/pgm.ci                                      6       entry main();
examples/pose/LBSim/sched.ci                                   5       entry main();
examples/pose/ASIM/pgm.ci                                      6       entry main();
examples/pose/SimBenchmark/pgm.ci                              6       entry main();
examples/pose/HiSim/Main/pgm.ci                                11      entry main();
examples/pose/MiniNet/mininet.ci                               6       entry main();
examples/pose/PHOLD/phold.ci                                   6       entry main();
examples/pose/PatternGen/pgm.ci                                6       entry main();
examples/pose/ChunkSim/pgm.ci                                  6       entry main();
examples/collide/collidethread/hello.ci                        6       entry main();
examples/collide/collidecharm/hello.ci                         6       entry main();
tests/charm++/delegation/pipelined-section-reduction/hello.ci  18      entry main();
tests/charm++/commSpeed/pgm.ci                                 6       entry main();
tests/charm++/load_balancing/lb_test/sim/sim.ci                19      entry main();
tests/charm++/broadcast/broadcast.ci                           6       entry main();

```

**Comment by PhilMiller** [comment]
*Original date: 2013-03-04 23:58:26*

---
Everything turned up is fixed now.

**Comment by ericjbohm** [comment]
*Original date: 2013-03-05 00:12:01*

---
A few more stragglers.

bohm`intellect:~/work/git/charm/net-linux-x86_64-prod$ grep -ri 'main\s*(\s*)' --include *.ci *
tests/charm++/penciltest/testpencil.ci:	entry main ();
tests/charm++/pmetest/testpme.ci:	entry main ();
tmp/libs/ck-libs/pmaf/pgm.ci:    entry main();
tmp/libs/ck-libs/TMRC2D/old_pgm.ci:    entry main();

**Comment by PhilMiller** [comment]
*Original date: 2013-03-05 23:12:08*

---
The results of `net-linux-x86_64 (charm *$)$ find . -name '*.ci' | while read i; do echo $i; bin/charmc $i; done` now show nothing in this vein. In addition to the four you cite, I also covered `examples/multiphaseSharedArrays/matmul/test.ci`, which had an attribute that threw us both off:
```
     mainchare Test
     {
-        entry [threaded] Test();
+        entry [threaded] Test(CkArgMsg *);
         entry void done();
         entry void doneg();
     }

```
