### ISSUE TITLE
pe threads sleep on condition variables

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#620]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/620*

---
Currently when a PE is idle in smp or multicore builds it will poll either continuously or with fixed-length sleeps in sleep-on-idle mode.  For power-sensitive platforms such as tablets and laptops or for hyperthreads sharing the same hardware it would be potentially more efficient and faster to have PE threads sleep on a condition variable, letting the thread sleep until a message was actually posted.  I am not sure how to combine condition variables with periodic calls.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-23 20:34:04*

---
For whoever comes along to implement this, the system call you're looking for is probably `pthread_cond_timedwait`.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-18 15:26:53*

---
bil

**Comment by bilgeacun** [comment]
*Original date: 2016-02-15 20:31:57*

---
Gerrit patch: https://charm.cs.illinois.edu/gerrit/#/c/1058/

**Comment by bilgeacun** [comment]
*Original date: 2016-03-03 21:09:45*

---
pthread_cond_timedwait is already implemented. The comm thread sleeps on a 10ms timer or untill a message arrives.
We concluded that there is no need to implement another version where a comm thread sleeps only until a message arrives.
I have abandoned the gerrit commit.
