### ISSUE TITLE
CkIO: fdatasync() can be interupted

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#628]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/628*

---
Using the CkIO library, I am getting:
------------- Processor 126 Exiting: Called CmiAbort ------------
Reason: FATAL ERROR on PE 126 working on file 'cosmo25p.768sg1bwK1C52e2.000777/g
as/pos': fdatasync failed; system reported Interrupted system call

on Bluewaters.  It looks like Lustre will interrupt the fdatasync() system call, as it does write() and close().  A check for EINTR after a fdatasync() error is needed as in CmiFwrite() and friends.

<Insert Lustre rant here.>

**Comment by PhilMiller** [comment]
*Original date: 2014-11-30 04:14:37*

---
What an abysmal FS indeed.

**Comment by nikhil-jain** [comment]
*Original date: 2014-12-05 17:34:12*

---
Updates here Ronak?

**Comment by rbuch** [comment]
*Original date: 2014-12-05 21:00:53*

---
According to The Open Group, fdatasync() doesn't error with EINTR (http://pubs.opengroup.org/onlinepubs/7908799/xsh/fdatasync.html), but fsync() does (http://pubs.opengroup.org/onlinepubs/7908799/xsh/fsync.html).  Some think that this is an oversight (http://lwn.net/Articles/365403/).

Regardless, I'll implement a fix, but it seems it's possible that it may not work if the documentation is correct.
