### ISSUE TITLE
overall execution time printed at shutdown is wrong (large negative value)

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#629]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/629*

---
This commit:  "net & multicore: Print overall execution time at shutdown" is broken.

From multicore-linux64-iccstatic:

Program finished after -1415828393.721876 seconds.

**Comment by jcphill** [comment]
*Original date: 2014-11-13 16:40:50*

---
Changing from CmiWallTimer() to CmiClock doesn't work either, at least for NAMD, the primary reason being that Cmi_clock is initialized in ConverseRunPE(), which is actually called multiple times by the NAMD scripting system, so it always reports 0.04... seconds.  Simply using CmiWallTimer() without subtracting off Cmi_clock works fine:

-  printf("Program finished after %f seconds.\n", CmiWallTimer() - Cmi_clock);
+  printf("Program finished after %f seconds.\n", CmiWallTimer());

**Comment by jcphill** [comment]
*Original date: 2014-11-28 02:29:58*

---
Ping.

**Comment by nikhil-jain** [comment]
*Original date: 2014-11-28 05:06:16*

---
Assigning to Phil since it was his commit, reassign if I am misinformed.
