### ISSUE TITLE
megacon is leaking message memory

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#63]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/63*

---
Clean up and correct megacon's handling of memory.  where is the bug?

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 19:01:48*

---
Try valgrind on megacon and try to determine what exactly is going on here.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:30:40*

---
Inactive for 4 months; should be a small task; upping the priority.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-09 23:19:14*

---
- With valgrind without charmrun (net)
  - segfault with the test blkinhand
     ==31798== Use of uninitialised value of size 8
     ==31798==    at 0x423B35: swapJcontext (uJcontext.c:181)
     ==31798==    by 0x4236FE: CthSuspend (threads.c:780)
     ==31798==    by 0x41CB7F: blk_fibthr (blkinhand.c:47)
     ==31798==    by 0x41C881: CpmRecv_blk_fibthr (blkinhand.cpm.h:68)
     ==31798==    by 0x42CC39: CmiHandleMessage (convcore.c:1622)
     ==31798==    by 0x42D0D1: CsdSchedulePoll (convcore.c:1915)
     ==31798==    by 0x42CDFD: CsdScheduler (convcore.c:1788)
     ==31798==    by 0x42D237: CthStandinCode (convcore.c:1994)
     ==31798==    by 0x423DA3: CthStartThread (threads.c:1694)
     ==31798==    by 0x423ACA: setJcontext (uJcontext.c:136)
    -> From Eric B. it can be from the envelop, need to compare the error between net and netlrts

- With valgrind and with charmrun +p1
  - blkinhand: crash on multi
  - posixth: crash on all-at-once
  - future: crash on multi

- With +p2
  ==27891== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
  -> false positive
  -> need to create a suppression file for valgrind for this kind of error.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-19 21:09:08*

---
Comparison of the log file from valgrind between net and netlrts: same warnings. So, it is not from the envelop.

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-19 22:50:32*

---
Nothing got with address-sanitizer, but with report was wrong on a short example for uninitialized and leaks (clang version 3.5.1 and 3.3.5).

Need to help valgrind with the stacks: http://valgrind.org/docs/manual/manual-core-adv.html
The problem is this is tagged in the valgrind documentation as "Warning: Unfortunately, this client request is unreliable and best avoided.".

**Comment by pplimport** [comment]
*Original author: Cyril Bordage*
*Original date: 2015-02-20 03:39:42*

---
"--with-valgrind" added to build, to enable stack help for valgrind. Need to document it.
With that, megacon can run with valgrind without crashing.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-17 15:56:33*

---
fix implemented in: ~~https://charm.cs.illinois.edu/gerrit/#/c/787/~~ https://github.com/UIUC-PPL/charm/commit/93a5f5fe131b5b40581b883ef9a883a793fe05fb
