### ISSUE TITLE
Compilation on BW fails with cray compiler

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#633]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/633*

---
Compilation of any Charm++ code fails on BW if using Cray compiler.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-15 19:20:37*

---
Tested on JYC. Error is reproducible.  Cray compilers compiles on Titan.  Sent an email to BW help for -lrca linking problem

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2015-01-15 21:31:55*

---
This has something to do with cudatoolkit. When it is loaded, -lrca has problem with cray compiler. Otherwise, it is fine

**Comment by PhilMiller** [comment]
*Original date: 2015-01-25 21:41:44*

---
If I'm reading correctly, http://charm.cs.uiuc.edu/gerrit/458 is the resolution for this.
