### ISSUE TITLE
all trees should be pe/node/physnode/network topology aware

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#635]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/635*

---
There are various places in Charm++ where broadcast and reduction trees are implemented as PE n to PEs 2*n+1 and 2*n+2 (or the obvious k-way extension).  These should in all instances be replaced with a standard tree that aggregates communication hierarchically within a PE, node, physical node, and finally whatever network topology can be detected.  It doesn't need to be perfect at first, but we do need a single tree-generating utility that can be called everywhere that this kind of tree is needed.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 16:53:18*

---
Reductions are now at least SMP aware due to the fix for #1278. We still form a topology-oblivious tree over the nodes, though.

**Comment by PhilMiller** [comment]
*Original date: 2017-05-16 16:56:15*

---
This is a potentially serious performance defect, not just something to tidy up.

**Comment by juanjgalvez** [comment]
*Original date: 2017-06-05 20:12:47*

---
Patches:

~~https://charm.cs.illinois.edu/gerrit/#/c/2578/~~ https://github.com/UIUC-PPL/charm/commit/014e434ecacbf064a8e3debff97e121a4cb81edc
~~https://charm.cs.illinois.edu/gerrit/#/c/2585/~~ https://github.com/UIUC-PPL/charm/commit/6292e029729f452d48a7252c07e7a1a0664f4299
~~https://charm.cs.illinois.edu/gerrit/#/c/2586/~~ https://github.com/UIUC-PPL/charm/commit/3bece409d7ffcee547dc428ed99c63ca7733fefb
~~https://charm.cs.illinois.edu/gerrit/#/c/2587/~~ https://github.com/UIUC-PPL/charm/commit/985bcfa12e905d5c09baf115d56cf32a57684744
~~https://charm.cs.illinois.edu/gerrit/#/c/2588/~~ https://github.com/UIUC-PPL/charm/commit/55ba98208c71e67f9f520f6153332a44b5f7eb23
