### ISSUE TITLE
add CkLoop to standard build

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#636]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/636*

---
Trying some CkLoop code I find that it is not part of the standard Charm++ build, despite consisting of basically a single source file, and the proceedure for building it in the docs it to cd to a subdirectory and type make, which is not something I would like to ask NAMD users to do.

Annoyance #2:  no way to build CkLoop -debug without editing Makefile

Annoyance #3:  the CkLoop_Init numThreads argument for non-smp builds should really be an environment variable or a command-line parameter, since it depends on the execution environment, not the program.

Annoyance #4:  In the age of C++, why [first,last] rather than [begin,end)?

**Comment by jcphill** [comment]
*Original date: 2014-12-22 22:40:51*

---
Also, please do not subject the user to this message:

"CkLoopLib is used in SMP with a simple dynamic scheduling (converse-level notification) but not using node-level queue"

**Comment by PhilMiller** [comment]
*Original date: 2015-03-27 23:31:19*

---
One of the things holding back building CkLoop by default is the lack of Windows support in non-SMP/non-multicore builds. 

For Windows non-SMP/non-multicore builds, a real CkLoop implementation would be substantial effort for what seems like negligible gain - when performance matters, user should get/use a shared memory build anyway. Thus, I think it would be better to implement a simple dummy version of CkLoop that keeps the work within the PE that single-threaded Windows builds can use.

**Comment by harshithamenon** [comment]
*Original date: 2015-08-17 19:56:14*

---
Now that ckloop builds on windows (https://charm.cs.illinois.edu/redmine/issues/701), shall we build ckloop by default? The gerrit change ~~https://charm.cs.illinois.edu/gerrit/#/c/669/~~ https://github.com/UIUC-PPL/charm/commit/95e91c699d5a8aba6a6157936b4a4692eae97974 has been merged.

For ChaNGa, we build ckloop when the build target ChaNGa is specified to avoid making users go and build ckloop specifically.

**Comment by rbuch** [comment]
*Original date: 2015-08-17 21:09:46*

---
I think we should build it by default.  It blocks enough applications that it's an annoyance, and I don't see any reasons why we shouldn't build by default.

**Comment by jcphill** [comment]
*Original date: 2015-09-25 21:21:16*

---
This looks like it hasn't been merged...

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:08:15*

---
~~https://charm.cs.illinois.edu/gerrit/808~~ https://github.com/UIUC-PPL/charm/commit/e09e533ac041b4db4dfc7bcc740dc734d07e6344
