### ISSUE TITLE
update projections

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#637]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/637*

---
The last version of projections available for download is 6.5.1 from July 2013.  While it works fine, there are some issues I would hope are resolved by now that a new release would take care of.

Specifically, when tracing messages back through a CkLoop or periodic callback function (which show up as untraced background in projections), causality is assigned to the most recent entry point on the pe rather than, e.g., the origin of the CkLoop call or the entry point that scheduled the periodical callback.

**Comment by jcphill** [comment]
*Original date: 2015-03-12 20:17:55*

---
Note that charmplusplus.org currently links to projections 6.2.1.

**Comment by rbuch** [comment]
*Original date: 2016-02-15 21:29:05*

---
CkLoop issues fixed in ~~https://charm.cs.illinois.edu/gerrit/#/c/512/~~ https://github.com/UIUC-PPL/charm/commit/2e2760a1a525cb666131f6c5f8214e0b4b136b30.
