### ISSUE TITLE
killing ++local runs of smp builds dumps memory map and backtrace for all processes

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#640]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/640*

---
Running, e.g., netlrts-linux-x86_64-smp-tcp via ./charmrun ++local +p16 interactively and killing it with control-C dumps large amounts of debug data to the screen, and also tends to leave orphan processes.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-09 18:10:49*

---
Note that there's also a potential issue of orphan processes left behind that should get killed in this circumstance. Possibly re-direct this issue for that particular problem with SIGINT under SMP ++local.
