### ISSUE TITLE
expedited nodegroup messages all run on pe 0 on multicore builds

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#644]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/644*

---
expedited nodegroup messages under smp builds run on any available pe but on multicore builds they appear to all run on pe 0.  I understand this is done with immediate messages because there is no comm thread, but it doesn't make any sense for expedited.

**Comment by jcphill** [comment]
*Original date: 2015-01-14 17:58:48*

---
It also appears that non-expedited nodegroup messages all run on the same pe they are sent from for multicore builds.

**Comment by PhilMiller** [comment]
*Original date: 2015-01-22 21:19:20*

---
Nikhil says that we just need to set the NODEQUEUE flag to 1 on the multicore builds.
