### ISSUE TITLE
CmiDeliverSpecificMsg() should sleep on idle if CmiDeliverMsgs(1) would

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#645]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/645*

---
NAMD startup phase 1 using CmiDeliverMsgs(0) doesn't allow the thread to sleep when oversubscribed.  This seems correct.  CmiDeliverMsgs(1) does allow the thread do sleep, so it seems CmiDeliverSpecificMsg() should as well.

**Comment by bilgeacun** [comment]
*Original date: 2015-01-21 14:35:17*

---
What was the initial reason behind changing from CmiDeliverMsgs(0) to CmiDeliverMsgs(1) ? CmiDeliverSpecificMsg(..) looks like a blocking call unlike CmiDeliverMsgs(1), I'm not sure if it make much sense to allow the thread to go to sleep for that function.

**Comment by jcphill** [comment]
*Original date: 2015-01-22 01:18:18*

---
The use case is busy-waiting:  "while ( ! <specific message processed> ) { CmiDeliverMsgs(0); }".  If you do this with oversubscribed cores progress degrades severely because none of the threads ever sleep.  It's not an important use case but the fix seemed easy.

**Comment by bilgeacun** [comment]
*Original date: 2015-01-22 21:19:56*

---
According to Jim, performance degrade happens in the startup in smp mode when each worker thread in the node assigned a comm thread. As Namd should not run this way, we have decided, this change is not worthwhile to implement. Instead Charm++ smp mode could provide a more strict default case for ppn.
