### ISSUE TITLE
Missing $(TESTOPTS) in lots of test invocations

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#646]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/646*

---

```
$ git grep charmrun tests/ examples/  | grep Makefile: | grep -v TESTOPTS | egrep -v 'rm -r?f' | wc -l 
154
```

This is an approximation of the number of charmrun invocations in tests and examples that don't include `$(TESTOPTS)` like they're supposed to.

The right answer to this is not adding them everywhere, but rather systematically replacing charmrun invocations with a standard 'run' function sourced from an included makefile snippet, so that this error can never be repeated again.

**Comment by pplimport** [comment]
*Original author: Ehsan Totoni*
*Original date: 2015-02-09 20:12:27*

---
fix submitted for review:

http://charm.cs.uiuc.edu/gerrit/509

scripts used:
```
#!/bin/bash 
FILES=`git grep charmrun tests/ examples/ | grep Makefile: | egrep -v 'rm -r?f' | cut -d : -f 1 | uniq`

for MFILE in $FILES; do
  echo $MFILE
  SLASHES=`echo $MFILE | grep -o "/" | tr "\n" "\0"`
#remove one slash
  SLASHES=${SLASHES:1}
  PRE=`echo $SLASHES | sed 's/\//\.\.\//g'`
  echo $PRE
  sed -i '1i-include '${PRE}'common.mk' $MFILE
done


#!/bin/bash 
FILES=`git grep charmrun tests/ examples/ | grep Makefile: | egrep -v 'rm -r?f' | cut -d : -f 1 | uniq`

for MFILE in $FILES; do
  echo $MFILE
#sed -i -e 's/\btime\b//g' -e '/charmrun/ // s/$/\)/'   's/\.' $MFILE
  sed -i 's/\btime\b//g' $MFILE
  sed -i '/^[ \t]*-*\.\/charmrun/ s/\$(TESTOPTS)//g' $MFILE
  sed -i '/^[ \t]*-*\.\/charmrun/ s/$/)/' $MFILE
  sed -i 's/^[ \t]*\.\/charmrun/\t\$(call run,/' $MFILE
  sed -i 's/^[ \t]*-\.\/charmrun/\t-\$(call run,/' $MFILE
done

```

**Comment by PhilMiller** [comment]
*Original date: 2015-02-13 23:04:36*

---
There may be some holdovers left behind, but the bulk work is done. Thanks!
