### ISSUE TITLE
Mac OS X / Darwin builds should default to compiling with clang, not g++

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#651]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/651*

---
Apple has ceased to keep GCC up to date on Mac OS and replaced it fully with Clang/LLVM. The version of GCC they ship is far enough behind that the configure test introduced under #356 fails, while Clang would have passed for the last several years. Unless we want to require users to install a newer version of GCC via MacPorts/HomeBrew/Fink/etc., we should default to compiling with clang on Mac OS builds.

The necessary change should be replacing `g++` and `gcc` with `clang` in `src/arch/*darwin*/conv-mach.sh` and adapting the compiler flags defined there accordingly.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-07 17:34:47*

---
The impact of this can be seen "in autobuild":http://charm.cs.illinois.edu/autobuild/old.2015_02_07__03_41/net-darwin-x86_64-smp.txt

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-07 17:47:04*

---
Reassigning to Sam for load balancing.

**Comment by stwhite91** [comment]
*Original date: 2015-02-09 18:55:44*

---
Changed the default compiler to clang for the 6 darwin builds in src/arch.
They all compile with clang on my Mac now.

**Comment by stwhite91** [comment]
*Original date: 2015-02-09 21:08:17*

---
Change was approved and merged on Gerrit.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-10 17:24:02*

---
http://charm.cs.uiuc.edu/autobuild/cur/net-darwin-x86.txt

```
../../bin/charmc -optimize -production   -Wno-error -lm -I.. -cp ../../bin -seq daemon.o ../sockRoutines-seq.o -o charmd
ld: warning: ignoring file daemon.o, file was built for i386 which is not the architecture being linked (x86_64): daemon.o
ld: warning: ignoring file ../sockRoutines-seq.o, file was built for i386 which is not the architecture being linked (x86_64): ../sockRoutines-seq.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Fatal Error by charmc in directory /scratch/autobuild/darwin32/charm/net-darwin-x86/tmp/charmrun-src
   Command clang -mmacosx-version-min=10.6 -O2 -o charmd daemon.o ../sockRoutines-seq.o -L../../bin/../lib -lm returned error code 1
charmc exiting...
```

It looks like the 32-bit targets are slightly broken, because linking of code with `-seq` is complaining about trying to link a 64-bit binary. Note that the linker command line doesn't have the `-m32` argument being passed to it.

We may hack this by simply dropping support for 32-bit Mac OS X. The constraint on that is whether the iOS NAMD users build on that or something more esoteric.

**Comment by stwhite91** [comment]
*Original date: 2015-02-11 02:06:17*

---
Passing the -m32 argument to the linker fixes the build issue.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-12 17:52:11*

---
http://charm.cs.uiuc.edu/autobuild/cur/netlrts-darwin-x86_64-smp.txt
Could you see if this failure is a consequence of switching from gcc to clang, or what's going on there? If it's ancillary, please open a new issue.

**Comment by stwhite91** [comment]
*Original date: 2015-02-12 21:54:14*

---
I can't reproduce the error in tests/charm++/alignment/alignmentCheck for a netlrts-darwin-x86_64-smp build, so I will make a separate issue for this.
