### ISSUE TITLE
Command line parsing of RTS defined flags is off for certain flags in certain builds

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#654]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/654*

---
As an example, in the jacobi3d-sdag test one of the commands passes +killfile as an argument. If charm is not built with syncft then this argument doesn't get parsed out by the RTS and slips through to the user. This caused a crash in the jacobi3d-sdag tests because the user was using argument count to decide which params to set, but the argument count differened based on which charm build used.

The proposed solution is to make sure that system flags such as +killfile are parsed out regardless of the build, and have warnings thrown for unsupported flags.

[cmd_line.f90](https://github.com/UIUC-PPL/charm/files/3536523/cmd_line.f90.txt)

**Comment by epmikida** [comment]
*Original date: 2015-02-09 21:55:26*

---
Having all flags parsed out during initialization turned out to be infeasible due to the sheer number of arguments, and the number of different places/builds where they might exist. Phil suggested at least warning users of arguments that start with a '+'. This way it doesn't preclude applications from using '+' for their own arguments, but in the case of failures they will at least see that there is a warning about the potential misuse of Charm++ flags.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-10 19:50:58*

---
http://charm.cs.illinois.edu/autobuild/old.2015_02_10__03_31/net-darwin-x86_64-smp.txt
We're getting noise from +vp on AMPI and tcharm programs, in which the RTS doesn't consume `+vp N` before handing off the arguments.

**Comment by stwhite91** [comment]
*Original date: 2015-02-11 21:09:10*

---
Yes, charmrun does not consume the +vpN option. I was about to make a new issue about that until I saw this one. XPACC has started adding command line arguments to their code and AMPI breaks that.

**Comment by stwhite91** [comment]
*Original date: 2015-02-12 17:37:43*

---

```

The XPACC code is in Fortran, also. Attached is a small sample (A)MPI Fortran program to reproduce the problem.
The program prints out the number of command line arguments and the arguments themselves.

Build: ~/charm/bin/ampif90 cmd_line.f90 -o cmd_line
Run: ./charmrun +p1 ./cmd_line +vp1 x y z

Instead of seeing the 3 arguments x, y, and z printed, I just get the warning:

WARNING: +vp1 is a command line argument beginning with a '+' but was not parsed by the RTS.

```

**Comment by epmikida** [comment]
*Original date: 2015-02-12 20:34:12*

---
So it appears that the issue described above is a whole different issue. The example program doesn't receive any command line arguments whatsoever, regardless of what command line arguments are used. When compiled as an MPI program instead, it works as expected. The c/c++ ampi test programs correctly parse and receive commandline args, so the issue appears to specifically be for fortran ampi. I will open a separate issue for this, and fix the current issue by making sure that the warning isn't printed out until after AMPI has had the chance to parse out the +vpN.

**Comment by epmikida** [comment]
*Original date: 2015-02-12 23:25:30*

---
I don't think that the solution of just checking for AMPI, then moving where the check for extra arguments will work. After further digging, it looks like a lot of various mainchares use CmiGetArg calls to consume more '+' arguments, so somehow we'd have to be able to figure out which of the mainchares were actually written by users, make sure to construct them last, and right before constructing them check to make sure we've parsed out all of the '+' CLAs.

The only other option I could think of would be to move the warning after all mainchare constructors have been called, but then we may miss errors in cases where users main chares change values in argv, or crash in the constructor due to bad arguments before we even get the chance to warn them.

**Comment by stwhite91** [comment]
*Original date: 2015-03-05 21:20:04*

---
Can we roll this change back until a better solution is found? Running an AMPI program now always results in getting a warning that the +vp option was not parsed by the RTS. This would be confusing for any new user of AMPI.

**Comment by epmikida** [comment]
*Original date: 2015-08-17 18:44:21*

---
In core it was decided that the best solution would be to maintain a table of options that other modules will parse. These modules will add opts to this table when they register with charm.

**Comment by epmikida** [comment]
*Original date: 2015-08-17 19:46:57*

---
Under review: ~~https://charm.cs.illinois.edu/gerrit/#/c/789/~~ https://github.com/UIUC-PPL/charm/commit/7d66202179f2ffde00394f8d51ece12d22f90eb22
