### ISSUE TITLE
Make -E option default to enable macros in .ci files 

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#656]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/656*

---
#if's in .ci files should be parsed without passing -E argument. This would make new users life easier.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 20:36:18*

---
~~https://charm.cs.illinois.edu/gerrit/769~~ https://github.com/UIUC-PPL/charm/commit/4e31d37adc6720b4d71178586c2a3b284ebe8ccc
