### ISSUE TITLE
update charmc --help output

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#657]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/657*

---
  jim`sunnyvale$./charmc --help

  Charm++ Version 60601

  Usage: charmc [ flags ] <files>

  flags:
        -o <target> -g -O
        -D<define> -I<include path> -L<lib path> -l<library> -s
        -machine <mach> -seq -host -language <lang> 
        -balance <mode> -tracemode <mode> -memory <mode>
        -modules <comma-separated list of C++ modules>
        -verbose -save -purify -cp <dest> -gen-cpm <package>
        -use-reliable-cc -use-fastest-cc
        -cc <new cc> -c++ <new CC>  -ld <new ld> -ld++ <new LD>
        -cpp-option <opt> -ldro-option <opt> -cc-option <opt>
        -c++-option <opt> -ld-option <opt> -ld++-option <opt>
        -fmoddir <f90mod path>
        -pg <opt> -build-shared -charm-shared -no-trace-mpi
        -mpi -nomain-module -nomain -custom-part
 
  Cell specific flags:
        -spu-cpp -spu-lib <libname>
 
  Charmc compiles C, C++, f77, f90, Converse, Converse++, Charm, 
 and Charm++ programs.  The flags generally match those of cc or f77.
 Version 5.0, Parallel Programming Lab, UIUC, 1999

**Comment by stwhite91** [comment]
*Original date: 2015-03-10 20:57:39*

---
Here's what I think it should be, but I have a question at the end:

```
$./charmc --help

Charm++ Version 60601

Usage: charmc [ flags ] <files>

flags:
-o <target> -g -O
-D <define> -I <include path> -L <lib path> -l <library> -s
-machine <mach> -seq -host -language <lang> 
-balance <mode> -tracemode <mode> -memory <mode>
-module <comma-separated list of C++ modules>
-verbose -save -purify -cp <dest> -gen-cpm <package>
-use-reliable-cc -use-fastest-cc -use-new-std
-cc <new cc> -c++ <new CC> -ld <new ld> -ld++ <new LD>
-cpp-option <opt> -ldro-option <opt> -cc-option <opt>
-c++-option <opt> -ld-option <opt> -ld++-option <opt>
-f90 <new f90> -f90-option <opt> -fmoddir <f90mod path>
-pg <opt> -build-shared -charm-shared -no-trace-mpi
-mpi -openmp -nomain-module -nomain -custom-part

Charmc compiles C, C++, f77, f90, AMPI, Converse, Converse++, Charm, 
and Charm++ programs. The flags generally match those of cc or f90.
Version 5.0, Parallel Programming Lab, UIUC, 1999
```


Should that last line be left as is, removed, or have the updated charm++ version number and year (and remove version number from first line)?

**Comment by nikhil-jain** [comment]
*Original date: 2015-03-16 17:13:46*

---
We should drop the version since it already given earlier. Rest should be updated. Parallel Programming Lab, UIUC, 2015.

**Comment by stwhite91** [comment]
*Original date: 2015-03-17 16:43:21*

---
Change is in gerrit at: http://charm.cs.uiuc.edu/gerrit/#/c/637/
