### ISSUE TITLE
QD with immediate msgs hangs

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#660]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/660*

---
I have created a small test case extending Eric Mikida's testcase (https://charm.cs.illinois.edu/redmine/issues/596) to reproduce the hang.

[qd_immediatemsg_bug.tgz](https://github.com/UIUC-PPL/charm/files/3536527/qd_immediatemsg_bug.tar.gz)

**Comment by ericjbohm** [comment]
*Original date: 2015-08-27 21:06:30*

---
Immediate message should be placed in nodequeue in multicore context, then executed normally.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-03 05:45:59*

---
I am not able to reproduce this hang on Mac OSX Yosemite. Tried with and without production. Any particular flag/condition needed to reproduce?

**Comment by harshithamenon** [comment]
*Original date: 2015-09-03 13:51:17*

---
I believe that I had tried it with net-linux build without any special flags. I am unable to find the directory I worked on so can't be sure.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-03 14:25:14*

---
Ah, my bad. I should see both expedited and immediate msgs. I think I have reproduced the bug now. Thanks!

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-03 15:39:41*

---
This commit most likely fixed this issue too: ~~https://charm.cs.illinois.edu/gerrit/#/c/442/~~ https://github.com/UIUC-PPL/charm/commit/2d0a5a05d5494a76bf38a7b1f8dad7630d914b6a
