### ISSUE TITLE
charm++/alignment test fails with randomized queues

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#663]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/663*

---
See parent task for full details.

**Comment by pplimport** [comment]
*Original author: Akhil Langer*
*Original date: 2015-02-19 22:43:15*

---
Fixed. There was a bug in the alignment test. Number of priority bits were specified incorrectly.

**Comment by PhilMiller** [comment]
*Original date: 2015-02-19 22:45:55*

---
http://charm.cs.uiuc.edu/gerrit/#/c/554/

**Comment by PhilMiller** [comment]
*Original date: 2015-02-20 07:23:53*

---
Credit and close.
