### ISSUE TITLE
Reduce the impact of large messages sent to unlocated or migrated chare array elements

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#67]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/67*

---
Currently, any message sent to a chare array element (the *target*) whose location is uncached or has migrated is reflected off the object's home PE. For large messages (size threshold unspecified), this is both wasteful of network bandwidth and potentially slower than just sending a few small messages around to determine the recipient PE where the target lives and then sending the large message there directly.

The direct solution to this performance issue is to transfer large messages directly from the sender to their ultimate destination. The portable implementation of that would be to buffer large messages in the location/array manager on the sending PE  until a message indicating the current location is received. Less portable solutions will be presented in another issue.

In the migration case (as opposed to uncached lookup), how does the sending PE know that the target object has moved before sending? There's probably a big gap here for all sorts of location management improvements.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-02 00:23:50*

---
On systems that transmit even large messages directly, e.g. net-*, the explicit latency is only improved by buffering when the transmission time of the message payload is greater than the cost of an additional HR: 2a + 2nb when reflecting off the home PE vs 3a + nb when buffering at the sender. The reduction in network utilization may justify always buffering all but the smallest messages, though.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-06 13:40:42*

---
As I work on this, I realize there's a potential problem with always buffering messages when one doesn't definiteively know where the recipient resides. In the case where the recipient is actually on the home PE, this strategy would add the latency of a full round-trip plus however long messages take to get through the queues (requesting current location from home PE, and waiting for the reply), and various additional processing.

Depending on the application, that could be the very common case, or the really rare case. In the mostly-on-home-PEs case, this problem would only occur early in execution, and fade away after locations are cached, but that makes this a real tradeoff and not an unequivocal win.

**Comment by heyram** [comment]
*Original date: 2013-05-06 16:26:30*

---
Watch out for the massive upheaval of cklocation code that is happening on branch ramv/locmgr-cleanup. Any changes that involve locmgr or the msg delivery paths in arrmgr / locmgr are likely to have significant conflicts. One fix would be to merge early and often from the cleanup branch into master.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-06 16:29:02*

---
I'm not making this change yet due to the uncertainty in the tradeoff between optimizing for objects on their home PEs and objects residing elsewhere.

Regardless, though, the implementation would have a very narrow scope, limited entirely to `CkLocMgr::deliverUnknown()` I think.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 02:03:49*

---
Discussion in the core group suggested making this a runtime flag, so that impact can be easily tested and application developers and users can choose either way. It may as well take the payload size to use as a cutoff as an argument. The appropriate comparison is to the size of the message to request the recipient's location - messages within some delta of that should be sent directly.

**Comment by PhilMiller** [comment]
*Original date: 2013-07-01 23:50:15*

---
Implemented on branch `ramv/locmgr-cleanup`. Adds a new runtime flag `+messageBufferingThreshold` that controls how large messages must be before they are buffered. Passes `make test` in `tests/charm++` (after fixing an issue on that branch). Needs application correctness and performance testing.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 19:26:38*

---
Could grab the same implementation technique to mainline, since the location manager cleanup is somewhat stalled. However, it's not clear that there's an application use case for this that isn't better addressed by other mechanisms. Basically, we need a realistic benchmark that will actually show a benefit.

**Comment by PhilMiller** [comment]
*Original date: 2013-10-07 19:09:28*

---
Someone else can identify a relevant usecase and port the code to mainline if it matters. Either way, I'm not going to the effort to port non-useful code over just for the release.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-06 20:48:35*

---
As noted, it has been implemented on Ram's location manager cleanup branch, on which the 64-bit ID work is built. Still not clear whether it's worthwhile/useful to anything real.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-23 16:02:56*

---
This was merged with the 64-bit ID work.
