### ISSUE TITLE
Remove commlib

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#674]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/674*

---
Not used in production.  Should be removed.  Note, some extra application level work may be required to ensure that OpenAtom and NAMD still compile correctly without it, so changes to those source trees should go production before changes to charm to excise commlib.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-07 05:31:21*

---
I got an urge to delete some code, so I did.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-07 06:22:02*

---
Initial steps in http://charm.cs.uiuc.edu/gerrit/581 and http://charm.cs.uiuc.edu/gerrit/582

Still bits in fftlib and pose that include and reference comlib. The references in both are all ifdefed, so those should be easy.

**Comment by PhilMiller** [comment]
*Original date: 2015-06-08 19:27:40*

---
Change to remove comlib entirely: http://charm.cs.uiuc.edu/gerrit/744
Waiting on updates in OpenAtom to actually be mergeable.
