### ISSUE TITLE
Compiling ci files that use "typename T" in argument list fails

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#676]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/676*

---
Quoting Lawrence Kidder <kidder`astro.cornell.edu> (reproduced by Nikhil)

I have Typename.C containing:

```
#include "Typename.decl.h"

template <typename T>
class A : public CBase_A {
public:
  A() {}
  void help(const typename T::X& arg) {}
};

class B {};

class C { typedef B X; };

class Main : public CBase_Main {
public:
  Main(CkArgMsg* m) {}
};

#include "Typename.def.h"


and Typename.ci containing:

mainmodule Typename {
  template <typename T>
  array [1D] A {
    entry A();
    entry void help(const typename T::X&);
  };

  array [1D] A<T>;

  mainchare Main {
    entry Main(CkArgMsg* m);
  };
};
```

The syntax error is caused by the keyword typename in the entry method A<T>::help

If I remove the keyword template, the interface file will compile, but of course Typename.C no longer compiles because the generated Charm++ methods fail with error: missing 'typename' prior to dependent type name 'T::X'

**Comment by nikhil-jain** [comment]
*Original date: 2015-02-25 06:22:42*

---
My initial observation noted in a mail sent locally:

This may be a bug in the way we parse ci file. charmc seems to be throwing error when it sees two-word types of an entry method argument. Example "typename T". 

I applied the usual macro trick to replace the two words by one, and with few other tweaks in Larry's code, I could get his code to compile. Will work with someone more knowledgeable on these things.

**Comment by PhilMiller** [comment]
*Original date: 2015-05-29 22:29:07*

---
Ralf, is fixing this as easy as changing the parser's definition of QualNamedType?

**Comment by PhilMiller** [comment]
*Original date: 2015-10-26 14:56:11*

---
I think we can actually fix this the other direction - remove the need to ever say `typename` in the .ci file, and automatically insert it as needed in the generated output. I'll grab someone to work with me on this today.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-28 18:48:42*

---
Was this resolved?

**Comment by PhilMiller** [comment]
*Original date: 2016-09-28 18:50:17*

---
No, it was not. Just worked around.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:48:00*

---
Reassign to Evan based on discussion with Eric B.  Confer on how important this work is to schedule in the near future.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-17 20:41:21*

---
~~https://charm.cs.illinois.edu/gerrit/3523~~ https://github.com/UIUC-PPL/charm/commit/022aa17111e4f87cce5155c16436ff05593f9f65

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-17 23:16:55*

---
My WIP patch breaks the use of typename as a template parameter. Solving this is proving more difficult than expected.
