### ISSUE TITLE
LRTS support for setting up a message to send and transmitting a GET handle

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#68]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/68*

---
On platforms that use GET-based RDMA for large messages, there are various circumstances where it is useful to be able to set up a message for transmission, and get a handle that an eventual recipient can be told to retrieve. Use cases generally involved large messages. Interacting use cases include constrained receiver-side memory, and message delivery to migrated objects.

**Comment by PhilMiller** [comment]
*Original date: 2013-09-17 20:34:25*

---
Not on the release radar, and no implementation on the horizon within the time remaining.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 23:27:22*

---
Looks like the code for #1234 essentially addresses this desire. Try it out in CharmLU, perhaps.

**Comment by ericjbohm** [comment]
*Original date: 2017-01-26 18:33:07*

---
Is this solved by #1234?

**Comment by stwhite91** [comment]
*Original date: 2017-04-22 15:27:24*

---
I think this issue is covered by the combination of the separate sender-side and receiver-side issues.
