### ISSUE TITLE
reliable inter-partition barrier

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#680]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/680*

---
I'm trying to ensure that NAMD has reached certain phases of startup before allowing certain inter-partition one-sided operations.
However, if I call the NAMD DataExchanger replica_barrier() function too early the entry points don't exist on every partition so I get
a seg fault.  This seems like a chicken-vs-egg problem that needs to be addressed via an entry point set up during Converse
startup.  I only need the barrier for pe 0 of each partition.

[replica_barrier.diff](https://github.com/UIUC-PPL/charm/files/3536531/replica_barrier.diff.txt)

**Comment by jcphill** [comment]
*Original date: 2015-08-13 20:20:11*

---
Ping.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-17 19:14:14*

---
Will the attached patch to NAMD solve the problem?

**Comment by jcphill** [comment]
*Original date: 2015-08-18 22:11:30*

---
It's not that the entry points don't exist on every thread on the node, but that they don't exist on pe 0 of every partition, unless I've somehow misdiagnosed the issue.

**Comment by jcphill** [comment]
*Original date: 2015-08-28 16:38:45*

---

Using a slightly modified version of Nikhil's patch that guarantees that 
CkpvAccess(BOCclass_group).dataExchanger is initialized on pe 0 before any message processing can call this function:

#define CPROXY_DE(x) ((CProxy_DataExchanger)(x))

  void recvEvalCommand(DataMessage *dmsg) {
    Pointer msg(dmsg);
    CPROXY_DE(CkpvAccess(BOCclass_group).dataExchanger)[CkMyPe()].recv_eval_command(msg);
  }

I now get this error (after a few tries):

------- Partition 0 Processor 0 Exiting: Called CmiAbort ------
Reason: Error! This group proxy has not been initialized!
Fatal error on Partition 0 PE 0> Error! This group proxy has not been initialized!

After adding some debugging, it looks like it is being called from inside the LrtsInitCpuTopo function, which calls a scheduler to process its own messages:

FATAL ERROR: BOCgroup::dataExchanger is zero in recvRed!
FATAL ERROR: See http://www.ks.uiuc.edu/Research/namd/bugreport.html
[0] Stack Traceback:
  [0:0] CmiAbortHelper+0x73  [0xcd6ba3]
  [0:1] _Z8NAMD_bugPKc+0x76  [0x6175f6]
  [0:2] recvRed+0xda  [0xb87b6a]
  [0:3] CsdSchedulePoll+0x95  [0xcdf035]
  [0:4] LrtsInitCpuTopo+0x280  [0xd0d810]
  [0:5] _Z10_initCharmiPPc+0x10fd  [0xbd756d]
  [0:6] _Z11master_initiPPc+0x78  [0x61e698]
  [0:7] main+0x18  [0x61a798]
  [0:8] __libc_start_main+0xfd  [0x301e01ed1d]
  [0:9]   [0x5ab8f9]

This means that messages from other partitions may arrive during the call to initCharm.

Is there a way to re-enqueue a message for delivery later?  When I try just re-sending it seems to loop forever on that one message.

For the record, my test case is:
./charmrun ./namd2 ++local +p16 ++ppn 2 +replicas 4 +stdout out.%d alanin -- replicaBarrier

with apoa1 running +p16 on the same 16-core/32-thread machine.

**Comment by jcphill** [comment]
*Original date: 2015-08-28 19:26:09*

---
OK, I think I know how to fix this to implement a reliable cross-partition startup barrier.

**Comment by jcphill** [comment]
*Original date: 2015-08-28 20:01:45*

---
Yes, I think I've achieved a workaround in NAMD.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-28 20:05:20*

---
Can I view it? Trying to understand the missing piece.

**Comment by jcphill** [comment]
*Original date: 2015-08-28 22:21:06*

---
 
 ...
 + static int recvRedCalledEarly;
 + 

 ...
    void recvRed(DataMessage *dmsg) {
 +     if ( CkpvAccess(BOCclass_group).dataExchanger.isZero() ) {
 +       ++recvRedCalledEarly;
 +       CmiFree(dmsg);
 +       return;
 +     }
      CPROXY_DE(CkpvAccess(BOCclass_group).dataExchanger)[CkMyPe()].recv_red();
      CmiFree(dmsg);
    }

 ...
    void replica_barrier() {
 +     for ( ; recvRedCalledEarly > 0; --recvRedCalledEarly ) CPROXY_DE(CkpvAccess(BOCclass_group).dataExchanger)[CkMyPe()].recv_red();
      CPROXY_DE(CkpvAccess(BOCclass_group).dataExchanger)[CkMyPe()].barrier();
      CpvAccess(breakScheduler) = 0;
      while(!CpvAccess(breakScheduler)) CsdSchedulePoll();

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-17 19:50:52*

---
Jim did custom implementation for NAMD.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-03 23:20:15*

---
Dropping target version, to avoid confusing people into thinking the Charm code has such a thing recently implemented.
