### ISSUE TITLE
error in completion detection manual

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#691]
*Original author: Ehsan Totoni*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/691*

---
In the manual, the example for completion detection does not have "CkCallback allProduced" in start_detection() call, so it results in a compile error.

**Comment by epmikida** [comment]
*Original date: 2015-09-24 20:05:26*

---
Fixed multiple correctness and formatting issues in change 841. ~~https://charm.cs.illinois.edu/gerrit/#/c/841/~~ https://github.com/UIUC-PPL/charm/commit/2e68334f30761d5ee9b8c705a85263796c98cce83
