### ISSUE TITLE
PUP generated for [local] entry method

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#692]
*Original author: Ehsan Totoni*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/692*

---
For HPCCG mini-app, pup functions are generated for a local entry method's arguments. This results in a compiler error since the arguments are pointers.

**Comment by epmikida** [comment]
*Original date: 2015-08-17 21:24:04*

---
This issue is specifically for SDAG local entry methods only.

**Comment by epmikida** [comment]
*Original date: 2015-08-17 21:48:22*

---
After discussion with Phil, it seems that as soon as we enter a closure that is local, we should not be allowed to migrate. So as long as a local closure is active, if the chare tries to migrate we need to throw an error. Then we can cast pointers in the pup to intptr_t in the generated pups for the parameters that need it.

**Comment by epmikida** [comment]
*Original date: 2015-09-24 20:54:26*

---
After more discussion with Jonathan, we realized that a local sdag closure should never be migrated. The closure is created on the send side, then deleted on the receive side when it the method completes. During the closures lifetime, it may contain pointers to local data, and therefore shuold not be migrated. For methods marked as local, if we try to pup it's closure, we will just throw and error. It is the users responsibility to synchronize their migrations correctly when using local methods.

**Comment by epmikida** [comment]
*Original date: 2015-09-24 22:26:21*

---
Implemented in change 842. ~~https://charm.cs.illinois.edu/gerrit/#/c/842/~~ https://github.com/UIUC-PPL/charm/commit/cf8c8c82aa0e61b1ef2f9dcba8901e7c2a097b97
