### ISSUE TITLE
Stampede icc Shared Libraries Not Found

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#696]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/696*

---
When running any Charm program on Stampede and compiling with icc, using ./charmrun without ++local results in "error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory," even though the correct path is included in $LD_LIBRARY_PATH.  Programs work correctly when run without ./charmrun or when using ++local.

Using Charm commit 8e743b853772032c0483920106c44e0137962fad and a net-linux-x86_64-ibverbs-smp-icc build with the intel/13.0.2.146 module loaded.

**Comment by jcphill** [comment]
*Original date: 2015-03-11 03:46:25*

---
That's what ++runscript is for.

**Comment by rbuch** [comment]
*Original date: 2015-03-11 03:53:37*

---
Ah, I see.  We had solved it by using "-Wl, -rpath", but weren't sure if it was a known issue or not.
