### ISSUE TITLE
Physical node detection broken on PAMI-LRTS with partitions

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#70]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/70*

---
Per Jim:

> I'm seeing some physical node detection isues on BG/Q.
> 
> pami seems to set physical nodes == nodes:
> 
> Info: Running on 384 processors, 32 nodes, 32 physical nodes.
> 
> pamilrts seems to set physical nodes == processors:
> 
> Info: Running on 384 processors, 32 nodes, 384 physical nodes.
> 
> Both of these were running -n 8 c4 +ppn 12.

And again:

> It looks like for current git Charm++ the issue is confined to replicas. Both pami and pamilrts report correct physical node counts for non-replica runs, but with replicas pamilrts seems to set physical nodes = num pes in each replica:
> 
> Running on 384 processors, 32 nodes, 384 physical nodes.
> 
> I'd settle for physical nodes = nodes since that doesn't violate any assumptions that code using this information might have made.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 23:21:45*

---
The bit of NAMD code printing this is
```
src/main.C
188:    iout << iINFO << "Running on " << CkNumPes() << " processors, "
189-         << CmiNumNodes() << " nodes, "
190-         << CmiNumPhysicalNodes() << " physical nodes.\n" << endi;

```

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-07 00:03:58*

---
This was because CmiNumNodes gets its value from Converse which is aware of SMP threads, whereas CmiNumPhysicalNodes gets its value from TopoManager which case of partitioning resorts to a linear chain as topology. Fixed this by making TopoManager aware of node structure even when partitioning is being done.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-07 00:51:54*

---
Is this all working on Cray and clusters too?

**Comment by PhilMiller** [comment]
*Original date: 2013-03-08 00:34:13*

---
Yes, this is a non-issue on Cray and cluster platforms.
