### ISSUE TITLE
Calls to CkExit must be unique

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#700]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/700*

---
You can't call it multiple times. The clearest bug is when projections is enabled, the traces may be truncated if there are multiple calls.

Libraries register functions and re-call CkExit to continue the exit sequence. I propose we change that to an explicit API call something like, ContinueExitSequence().

We can then allow CkExit to be re-entrant by setting a flag when the exitHandler is called.

As a secondary concern, we need to see how this affects end-of-run analysis.

**Comment by PhilMiller** [comment]
*Original date: 2015-06-20 21:00:54*

---
Specifically, applications doing something like a state-space search must currently centralize to a single call to `CkExit`, rather than letting any chare that finds a desired solution call `CkExit()`.

Modified to distinguish from the just-opened #761.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-20 20:00:24*

---
I'm going to recommend that we document this limitation for now, and fix it shortly after the release.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-26 17:38:18*

---
Places in the codebase that would need to change to a new internal API:

* src/ck-cp/controlPoints.C
* src/ck-perf/trace-Tau.C
* src/ck-perf/trace-controlPoints.C
* src/ck-perf/trace-projections.C
* src/ck-perf/trace-simple.C
* src/ck-perf/trace-summary.C

Places that potentially make multiple calls:

* src/libs/ck-libs/
** amr/amr.C shutdown
** ParFUM/mesh_adjacency.C error handling
** fem/fem_mesh_adjacency.C error handling
** mblock/patch.C error handling
* src/ck-ldb/LBDatabase.C in simulation mode when bad command-line arguments are passed.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-06 20:40:37*

---
Limitation documented in ~~https://charm.cs.illinois.edu/gerrit/899~~ https://github.com/UIUC-PPL/charm/commit/b9cebe5eb8581e648f70271452f42c49f2254ec0

**Comment by PhilMiller** [comment]
*Original date: 2017-04-10 22:29:25*

---
~~https://charm.cs.illinois.edu/gerrit/2377~~ https://github.com/UIUC-PPL/charm/commit/67aa76d3b7e425b58954c334b320cf90e763411b
That took long enough...
