### ISSUE TITLE
charmrun startup handles failed connection attempts very poorly

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#704]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/704*

---
There are various reasons that charmrun may transiently fail to establish its initial ssh connections to compute nodes at startup. The most common of these is that the OpenSSH server defaults to a limit of 10 pending connections, and rejects any subsequent attempts until it is below the limit. Because charmrun won't retry connections, bumping up against this limit guarantees failure. Other reasons might be things like overloaded authentication mechanisms, DOS prevention mechanisms at other levels, and others. These transient failures are very off-putting to new users, and also cause frequent spurious test failures (most often in kNeighbor, because it launches up to 7 PEs instead of the usual maximum of 4). Subtasks will describe potential fixes - one or more of them may be enough, allowing us to reject the rest.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-19 20:07:53*

---
Other potential improvements that I think are less likely to be worthwhile, given #705, #706, and potentially #707 are
* There should be a default value for `++batch` below the default sshd connection limits
* Charmrun should limit the number of simultaneous connections it will open to any one compute node below the default sshd connection limits

**Comment by PhilMiller** [comment]
*Original date: 2015-12-04 20:05:41*

---
The potential issue I see remaining in this area is high connection rates back to charmrun after processes are launched - i.e. they come in faster than charmrun can handle, and so the kernel starts rejecting some. We should test if that can actually occur in practice, and if so implement default `++batch` or other internal rate limiting to mitigate it.

**Comment by stwhite91** [comment]
*Original date: 2016-12-21 19:33:48*

---
We avoided the issues with default sshd connection limits on darwin autobuilds by just lowering the max +p argument in our tests to like 6. Not sure if that issue is a problem anywhere else.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-23 16:55:32*

---
Ah, I just checked, and it is still an issue on Mac OS with default settings when increasing # of PEs. It seems not to be an SSH connection or session limit, since we're now only opening a single SSH connection to localhost. This'll take more investigation.

I suspect the remaining issue may be on the runtime side, in getting a failed attempt at connecting back to charmrun, and then not retrying at all. It may also be that charmrun is running into some limit on fast it can accept the connections.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-23 16:58:28*

---
Annoyingly, I can't seem to get it to reproduce anywhere near as reliably with dtruss watching the charmrun process. Lots of successful runs with it attached, first run without it fails.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-05 14:57:24*

---
This seems to no longer be a noticeable problem, so closing. Mac OS users can typically just use `++local`, and things all seem to be working well elsewhere.
