### ISSUE TITLE
Net charmrun should default to ++scalable-start

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#705]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/705*

---
Make sure there's no reason not to run by default with ++scalable-start (only one ssh connection to each host), and then enable it.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-24 20:06:42*

---
In the last core meeting, there was suspicion that `++scalable-start` is incompatible with some other feature. Please start by figuring out what, if anything, that is.

**Comment by juanjgalvez** [comment]
*Original date: 2015-10-26 19:18:47*

---
syncfttest running in net-linux-x86_64 with TESTOPTS=++scalable-start over three nodes works

scalable-start option conflicts with ++debug in charmrun.c, so to default to scalable-start we need to disable arg_scalable_start if someones uses ++debug(-no-pause)

**Comment by juanjgalvez** [comment]
*Original date: 2015-10-26 21:07:09*

---
The following liveViz test with ++scalable-start works without errors:

./charmrun ./wave2d +p7 ++server ++server-port 7654 ++scalable-start ++nodegroup galvez-test ++nodelist ~/nodelist.txt

Program runs across three nodes, visualizing the output remotely with liveViz in my laptop. No errors.

**Comment by juanjgalvez** [comment]
*Original date: 2015-10-27 15:42:03*

---
3-partition run of jacobi3d with ++scalable-start and across three nodes also works without any errors (using netlrts-linux-x86_64).

**Comment by juanjgalvez** [comment]
*Original date: 2015-12-02 22:12:09*

---
Fix here ~~https://charm.cs.illinois.edu/gerrit/#/c/924/~~ https://github.com/UIUC-PPL/charm/commit/65b75d134bdf2f5b24603ac0861345d884bd0ee5
