### ISSUE TITLE
Net charmrun should round-robin simultaneous connections

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#707]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/707*

---
To avoid connection limits to any one compute node, charmrun should order its connection attempts to spread them across multiple nodes rather than making all connections to a specific destination at once.

**Comment by PhilMiller** [comment]
*Original date: 2015-03-19 20:02:10*

---
With universal `++scalable-start`, there's no need for this.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 18:33:42*

---
scalable start is the default now
