### ISSUE TITLE
pthread_create error not properly checked

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#711]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/711*

---
Trying to run an verbs-x86_64 smp build on a node with lots of cores can result in a hang at startup.  The problem appears to be at machine-smp.c:507:
```
503       for (i=start; i<=end; i++) {        
504         pthread_attr_init(&attr);
505         pthread_attr_setscope(&attr, PTHREAD_SCOPE_SYSTEM);
506         ok = pthread_create(&pid, &attr, call_startfn, (void *)i);
507         if (ok<0) PerrorExit("pthread_create"); 
508         pthread_attr_destroy(&attr);
509       }
```

pthread_create returns non-zero (errno, apparently) if it fails (I get EAGAIN if I ask for too many threads.)  Line 507 doesn't properly catch that failure, so the next CmiNodeBarrier() hangs because it is waiting for threads that never get created.  There for the check should be:
if (ok!=0) PerrorExit()

It would be even better if it gave some hints about how to fix the problem: in my case, the number of threads I requested was greater than (total virtual memory)/(stack size).  Lowering the stack size got me going.

**Comment by bilgeacun** [comment]
*Original date: 2015-04-03 17:25:26*

---
http://charm.cs.uiuc.edu/gerrit/#/c/663/
