### ISSUE TITLE
Crash with net/machine-ibverbs on QLOGIC

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#732]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/732*

---
Reported by Andrew Pontzen <a.pontzen`ucl.ac.uk>.  It looks like this fix is in the new verbs port.
Andrew says:

Hi Tom,

I don’t really know who to report this to (changa_uw bug list doesn’t seem
appropriate) but I have had problems launching changa, this time on UCL’s
own cluster which has qlogic infiniband. It was crashing at startup with a
segmentation fault. After some digging I narrowed it down to a failure in
machine-ibverbs.c, and then hacked together a patch by following the advice
here:

http://www.orangefs.org/trac/orangefs/attachment/ticket/43/qlogic_ib.patch

from which I made up the following patch for charm

diff --git a/src/arch/net/machine-ibverbs.c b/src/arch/net/machine-ibverbs.c
index 50956a4..38a76aa 100644
--- a/src/arch/net/machine-ibverbs.c
+++ b/src/arch/net/machine-ibverbs.c
`` -897,8 +897,8 `` struct infiOtherNodeData *initInfiOtherNodeData(int
node,int addr[3]){
        // Error code 22 means that there was an invalid parameter when
calling to this verbs, try with qlogic-specific parameters 
        if (err==22)
        {
-       attr.timeout        = 26;
-       attr.retry_cnt      = 20;
+       attr.timeout        = 14;
+       attr.retry_cnt      = 7;

After making these changes changa appears to be running fine. But as I say I
don’t really know what I’ve changed here so just thought I’d let you know in
case it’s helpful to someone else - or in case this might make something
blow up that I should know about...

Cheers, Andrew

**Comment by nikhil-jain** [comment]
*Original date: 2015-04-30 15:49:07*

---
I think the code for handling QLOGIC correctly is already in there. Charm build need to be told though that this is QLOGIC we are building for:

./build charm++ verbs-linux-x86_64 --with-production -DQLOGIC 

Aside, net-* builds have been deprecated, so it would be good if Changa users use netlrts-* and verb-* builds.

**Comment by nikhil-jain** [comment]
*Original date: 2015-04-30 15:53:45*

---
On second thoughts, the current handling of the failure if the user did not specify -DQLOGIC can be improved. I will check in a patch soon.

**Comment by nikhil-jain** [comment]
*Original date: 2015-04-30 18:47:27*

---
The patch was merged.  Hopefully, now on user won't trip on the Qlogic specification.

http://charm.cs.uiuc.edu/gerrit/gitweb?p=charm.git;a=commit;h=ce5d773919690e622da14b1cc89f4410be834530
