### ISSUE TITLE
charmxi: #endif terminates any enclosing comment

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#736]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/736*

---
Charmxi treats any '`#endif`' as marking the end of a comment (!?), causing an "invalid construct" syntax error to be reported on the following innocuous code:

```
mainmodule m {
  mainchare A {
    entry A(CkArgMsg*);
    /*
    #endif
    banzai!
    */
    }
  }
}

```

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:48:01*

---
Reassign to Evan based on discussion with Eric B.  Confer on how important this work is to schedule in the near future.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-03 21:23:52*

---
I cannot replicate this problem. Note that the provided test case has a mismatched number of braces. When that is fixed, charmc gives me no error.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-16 23:07:46*

---
Closing this until/unless I hear otherwise.
