### ISSUE TITLE
charmxi: Serial block comments started by '//' aren't copied to the def headers.

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#737]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/737*

---
Oddly enough, C-style comments (`/* */`) stay untouched:

```
mainmodule m {
  mainchare A {
    entry A(CkArgMsg*);
    entry void fun() {
      serial {
        // now you see me
        /* now you don't */
        CkPrintf("this line will always show"); // this bit
      }
    }
  }
}
```

This generates the following code on `m.def.h`:

```
{ // begin serial block

                       
      /* now you don't */
      CkPrintf("this line will always show");            
    
} // end serial block
```

This can be a bit jarring when highlighting syntax errors on the generated code, e.g. if gcc shows a line printed differently from what the user sees. (Also notice how the spacing is preserved, i.e. there's white space after the CkPrintf.)

There is also a matter of correctness, such as in this case:

```
mainmodule m {
  mainchare A {
    entry A(CkArgMsg*);
    entry void fun() {
      serial {
        CkPrintf("hope you like your compiler"); /* // */ CkPrintf("warnings");
      }
    }
  }
}

```

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:18*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
