### ISSUE TITLE
verbs-smp 10% slower than net-ibverbs-smp on Stampede

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#745]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/745*

---
Comparing NAMD running STMV on 128 nodes of Stampede (++ppn 15 +commap 0 +pemap 1-15) for verbs (vsmp...) or net-ibverbs (smp...) for both 6.6.1 (...old) and current head (...new) I get a performance difference of over 10% between verbs and net-ibverbs:
```
may2015_stmv_128.log.smpnew:Info:  Initial time: 1920 CPUs 0.00854789 s/step 0.0989339 days/ns 1944.25 MB memory
may2015_stmv_128.log.smpnew:Info:  Initial time: 1920 CPUs 0.00972939 s/step 0.112609 days/ns 1944.25 MB memory
may2015_stmv_128.log.smpnew:Info:  Initial time: 1920 CPUs 0.00793615 s/step 0.0918536 days/ns 1943.75 MB memory
may2015_stmv_128.log.smpnew:Info:  Benchmark time: 1920 CPUs 0.00791043 s/step 0.0915559 days/ns 1943.25 MB memory
may2015_stmv_128.log.smpnew:Info:  Benchmark time: 1920 CPUs 0.00786715 s/step 0.091055 days/ns 1943.25 MB memory
may2015_stmv_128.log.smpold:Info:  Initial time: 1920 CPUs 0.00853866 s/step 0.0988271 days/ns 1940.93 MB memory
may2015_stmv_128.log.smpold:Info:  Initial time: 1920 CPUs 0.00845077 s/step 0.0978099 days/ns 1940.93 MB memory
may2015_stmv_128.log.smpold:Info:  Initial time: 1920 CPUs 0.00763273 s/step 0.0883418 days/ns 1940.43 MB memory
may2015_stmv_128.log.smpold:Info:  Benchmark time: 1920 CPUs 0.00758638 s/step 0.0878053 days/ns 1939.93 MB memory
may2015_stmv_128.log.smpold:Info:  Benchmark time: 1920 CPUs 0.00805121 s/step 0.0931853 days/ns 1939.93 MB memory
may2015_stmv_128.log.vsmpnew:Info: Initial time: 1920 CPUs 0.0113378 s/step 0.131225 days/ns 1948.55 MB memory
may2015_stmv_128.log.vsmpnew:Info: Initial time: 1920 CPUs 0.00987099 s/step 0.114248 days/ns 1938.48 MB memory
may2015_stmv_128.log.vsmpnew:Info: Initial time: 1920 CPUs 0.00926541 s/step 0.107239 days/ns 1948.55 MB memory
may2015_stmv_128.log.vsmpnew:Info: Benchmark time: 1920 CPUs 0.00925729 s/step 0.107145 days/ns 1947.54 MB memory
may2015_stmv_128.log.vsmpnew:Info: Benchmark time: 1920 CPUs 0.00903439 s/step 0.104565 days/ns 1947.54 MB memory
may2015_stmv_128.log.vsmpold:Info: Initial time: 1920 CPUs 0.00978132 s/step 0.11321 days/ns 1947.54 MB memory
may2015_stmv_128.log.vsmpold:Info: Initial time: 1920 CPUs 0.00983178 s/step 0.113794 days/ns 1937.48 MB memory
may2015_stmv_128.log.vsmpold:Info: Initial time: 1920 CPUs 0.00916775 s/step 0.106108 days/ns 1947.54 MB memory
may2015_stmv_128.log.vsmpold:Info: Benchmark time: 1920 CPUs 0.0091498 s/step 0.1059 days/ns 1946.54 MB memory
may2015_stmv_128.log.vsmpold:Info: Benchmark time: 1920 CPUs 0.00910915 s/step 0.10543 days/ns 1946.54 MB memory
```
The full build is net-linux-x86_64-ibverbs-smp-iccstatic and verbs-linux-x86_64-smp-iccstatic.

**Comment by bilgeacun** [comment]
*Original date: 2015-07-06 15:40:14*

---
I have reproduced the problem with 128 nodes on Stampede. For 64 nodes and lower, there is no performance difference between net-ibverbs-smp and verbs-smp.

I'm attaching two projections images. In both images, the top part is from net-ibverbs, the bottom part is verbs. In net-ibverbs iterations have a rectangle shape whereas in verbs they more look like triangles. 
Then, I wrote a simple broadcast benchmark and compared the performance on this simpler case. Verbs-smp is much faster then net-ibverbs on the broadcast benchmark.
Performance on 128 nodes: 
verbs-smp: 53 sec - net-ibverbs-smp: 83 sec.

Any ideas where else I could look to figure out the problem? 

!https://charm.cs.illinois.edu/redmine/attachments/download/99/namd_128_nodes_net&verbs-iteration.png!
!https://charm.cs.illinois.edu/redmine/attachments/download/100/namd_128_nodes-net&verbs.png!

**Comment by jcphill** [comment]
*Original date: 2015-07-22 17:02:45*

---
You need to look at timelines to see what is causing the delays.  It looks like broadcasts are being delayed by other messages in verbs while they propagate much faster in net-ibverbs.

**Comment by bilgeacun** [comment]
*Original date: 2015-07-23 15:15:26*

---
Attaching a snapshot from the timeline. Although the comm thread(N61) receives the broadcast message, it takes 10 ms for PE920 to start processing it. There is a long idle period where PE seems to be doing nothing. There are more cases like this in the timeline which is quite strange.

**Comment by PhilMiller** [comment]
*Original date: 2015-07-23 15:37:42*

---
An observation from the time profiles: on `verbs-`, it looks like the issue is occurring on every alternate step - one step begins sharply, the next ramps slowly, and repeats. Maybe that, or an examination of whether the symptoms are different between the two cases, can provide us some clue.

**Comment by jcphill** [comment]
*Original date: 2015-07-23 19:40:59*

---
I assume that those are sets of four timesteps - the ramp up is the end of PME and the sharp jump is the pressure broadcast.

A 10ms lag is really bad.  What happens if you use ++ppn 14 to leave a core free for the OS?  I assume you're using +commap and +pemap.

**Comment by bilgeacun** [comment]
*Original date: 2015-07-31 17:33:53*

---
Leaving one core for the OS does not solve the problem.

**Comment by jcphill** [comment]
*Original date: 2015-07-31 20:21:46*

---
Does not solve the performance difference or the 10ms lags?  Do you set the lags in net-ibverbs as well or only verbs?

**Comment by bilgeacun** [comment]
*Original date: 2015-08-05 16:35:02*

---
Leaving one core out does seems to resolve the lag but not the performance difference between verbs, net-ibverbs.

I have done more extensive broadcast benchmark test with different msg size and realized that verbs bcast performance is actually worse than net-ibverbs with bigger msg sizes like 2MB and more. Analyzing the projections logs of the bcast benchmark I have seen the behavior in the attached picture. This lead me to think the broadcast is happening point to point. And that was true. Both CMK_BROADCAST_SPANNING_TREE and CMK_BROADCAST_HYPERCUBE was disabled for verbs. netlrts do use spanning tree broadcast. The problem is only for verbs.

The fix is implemented here:  [[~~https://charm.cs.illinois.edu/gerrit/#/c/766/~~ https://github.com/UIUC-PPL/charm/commit/b1db2f25a931534c555aadd14740f8f6831bf9ae]]

Step time of NAMD with the fix on 128 nodes, performance is equivalent:
```
verbs-smp: Info: Benchmark time: 1792 CPUs 0.0075624 s/step 0.0875278 days/ns 1880.32 MB memory
net-ibverbs-smp: Info: Benchmark time: 1792 CPUs 0.00768936 s/step 0.0889972 days/ns 1880.06 MB memory
```

**Comment by PhilMiller** [comment]
*Original date: 2015-08-05 17:09:20*

---
Could we systematically check for the same issue on other LRTS layers?

**Comment by bilgeacun** [comment]
*Original date: 2015-08-06 01:15:10*

---
If neither HYPERCUBE or SPANNING_TREE is defined, LRTS sets the broadcast to be  SPANNING_TREE by default. (These are marked as *default* below)

gni-pxshm and gni-xpmem - defines HYPERCUBE
other gni layers - default
pamilrts - default
netlrts - defines HYPERCUBE
verbs - default (with the latest commit)
mpi-darwin - defines HYPERCUBE
other mpi builds - default

**Comment by jcphill** [comment]
*Original date: 2015-08-06 17:52:41*

---
128 nodes looks good, but there is still a performance difference at 256 nodes:

 aug2015_stmv_256.log.smpnew:Info: Initial time: 3840 CPUs 0.00758821 s/step 0.0878265 days/ns 1980.68 MB memory
 aug2015_stmv_256.log.smpnew:Info: Initial time: 3840 CPUs 0.00691429 s/step 0.0800265 days/ns 1980.68 MB memory
 aug2015_stmv_256.log.smpnew:Info: Initial time: 3840 CPUs 0.00509702 s/step 0.0589933 days/ns 1980.17 MB memory
 aug2015_stmv_256.log.smpnew:Info: Benchmark time: 3840 CPUs 0.00458197 s/step 0.0530321 days/ns 1979.92 MB memory
 aug2015_stmv_256.log.smpnew:Info: Benchmark time: 3840 CPUs 0.00486118 s/step 0.0562637 days/ns 1979.92 MB memory
 
 aug2015_stmv_256.log.smpold:Info: Initial time: 3840 CPUs 0.00751507 s/step 0.08698 days/ns 1981.91 MB memory
 aug2015_stmv_256.log.smpold:Info: Initial time: 3840 CPUs 0.00677677 s/step 0.0784349 days/ns 1981.91 MB memory
 aug2015_stmv_256.log.smpold:Info: Initial time: 3840 CPUs 0.00523586 s/step 0.0606003 days/ns 1981.15 MB memory
 aug2015_stmv_256.log.smpold:Info: Benchmark time: 3840 CPUs 0.00473469 s/step 0.0547997 days/ns 1981.15 MB memory
 aug2015_stmv_256.log.smpold:Info: Benchmark time: 3840 CPUs 0.00495834 s/step 0.0573882 days/ns 1981.15 MB memory
 
 aug2015_stmv_256.log.vsmpnew:Info: Initial time: 3840 CPUs 0.0100037 s/step 0.115784 days/ns 1983.09 MB memory
 aug2015_stmv_256.log.vsmpnew:Info: Initial time: 3840 CPUs 0.00844873 s/step 0.0977862 days/ns 1983.09 MB memory
 aug2015_stmv_256.log.vsmpnew:Info: Initial time: 3840 CPUs 0.00726676 s/step 0.084106 days/ns 1982.59 MB memory
 aug2015_stmv_256.log.vsmpnew:Info: Benchmark time: 3840 CPUs 0.0065947 s/step 0.0763276 days/ns 1982.59 MB memory
 aug2015_stmv_256.log.vsmpnew:Info: Benchmark time: 3840 CPUs 0.00704554 s/step 0.0815456 days/ns 1982.59 MB memory
 
 aug2015_stmv_256.log.vsmpold:Info: Initial time: 3840 CPUs 0.00981046 s/step 0.113547 days/ns 1989.24 MB memory
 aug2015_stmv_256.log.vsmpold:Info: Initial time: 3840 CPUs 0.00933472 s/step 0.108041 days/ns 1986.69 MB memory
 aug2015_stmv_256.log.vsmpold:Info: Initial time: 3840 CPUs 0.00756891 s/step 0.0876031 days/ns 1986.18 MB memory
 aug2015_stmv_256.log.vsmpold:Info: Benchmark time: 3840 CPUs 0.0077241 s/step 0.0893993 days/ns 1986.18 MB memory
 aug2015_stmv_256.log.vsmpold:Info: Benchmark time: 3840 CPUs 0.007278 s/step 0.0842361 days/ns 1986.18 MB memory

**Comment by jcphill** [comment]
*Original date: 2015-08-06 18:29:15*

---
On the other hand, when I leave one core free the verbs layer screams.  Is there something about the verbs layer that is more sensitive to interference?

 aug2015_stmv_256.log3.smpnew:Info: Initial time: 3584 CPUs 0.0073737 s/step 0.0853438 days/ns 1909.81 MB memory
 aug2015_stmv_256.log3.smpnew:Info: Initial time: 3584 CPUs 0.00711763 s/step 0.08238 days/ns 1909.81 MB memory
 aug2015_stmv_256.log3.smpnew:Info: Initial time: 3584 CPUs 0.0056485 s/step 0.0653761 days/ns 1909.56 MB memory
 aug2015_stmv_256.log3.smpnew:Info: Benchmark time: 3584 CPUs 0.00498003 s/step 0.0576392 days/ns 1909.56 MB memory
 aug2015_stmv_256.log3.smpnew:Info: Benchmark time: 3584 CPUs 0.00498166 s/step 0.0576581 days/ns 1909.56 MB memory

 aug2015_stmv_256.log3.smpold:Info: Initial time: 3584 CPUs 0.00773356 s/step 0.0895088 days/ns 1908.58 MB memory
 aug2015_stmv_256.log3.smpold:Info: Initial time: 3584 CPUs 0.00711045 s/step 0.0822969 days/ns 1908.58 MB memory
 aug2015_stmv_256.log3.smpold:Info: Initial time: 3584 CPUs 0.00530507 s/step 0.0614013 days/ns 1907.82 MB memory
 aug2015_stmv_256.log3.smpold:Info: Benchmark time: 3584 CPUs 0.00538055 s/step 0.0622749 days/ns 1907.82 MB memory
 aug2015_stmv_256.log3.smpold:Info: Benchmark time: 3584 CPUs 0.00513796 s/step 0.0594671 days/ns 1907.82 MB memory

 aug2015_stmv_256.log3.vsmpnew:Info: Initial time: 3584 CPUs 0.00710366 s/step 0.0822183 days/ns 1913.52 MB memory
 aug2015_stmv_256.log3.vsmpnew:Info: Initial time: 3584 CPUs 0.0066739 s/step 0.0772443 days/ns 1913.27 MB memory
 aug2015_stmv_256.log3.vsmpnew:Info: Initial time: 3584 CPUs 0.0052785 s/step 0.0610937 days/ns 1913.27 MB memory
 aug2015_stmv_256.log3.vsmpnew:Info: Benchmark time: 3584 CPUs 0.00452979 s/step 0.0524281 days/ns 1913.27 MB memory
 aug2015_stmv_256.log3.vsmpnew:Info: Benchmark time: 3584 CPUs 0.00422217 s/step 0.0488677 days/ns 1913.27 MB memory

 aug2015_stmv_256.log3.vsmpold:Info: Initial time: 3584 CPUs 0.0118218 s/step 0.136827 days/ns 1928.98 MB memory
 aug2015_stmv_256.log3.vsmpold:Info: Initial time: 3584 CPUs 0.0114227 s/step 0.132207 days/ns 1900.95 MB memory
 aug2015_stmv_256.log3.vsmpold:Info: Initial time: 3584 CPUs 0.00989773 s/step 0.114557 days/ns 1921.03 MB memory
 aug2015_stmv_256.log3.vsmpold:Info: Benchmark time: 3584 CPUs 0.00984771 s/step 0.113978 days/ns 1921.03 MB memory
 aug2015_stmv_256.log3.vsmpold:Info: Benchmark time: 3584 CPUs 0.0097272 s/step 0.112583 days/ns 1921.03 MB memory

**Comment by jcphill** [comment]
*Original date: 2015-08-07 03:35:40*

---
Bilge Acun wrote:
> If neither HYPERCUBE or SPANNING_TREE is defined, LRTS sets the broadcast to be  SPANNING_TREE by default. (These are marked as *default* below)
> 
> gni-pxshm and gni-xpmem - defines HYPERCUBE
> other gni layers - default
> pamilrts - default
> netlrts - defines HYPERCUBE
> verbs - default (with the latest commit)
> mpi-darwin - defines HYPERCUBE
> other mpi builds - default

It looks like hypercube was just removed for gni-crayxe and gnu-crayxc. Was this benchmarked? I'm not sure how hypercube was implemented, but if it sent the longest distance first it would be more efficient on a torus network than a n->2n+1,2n+2 tree.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-07 03:55:32*

---
HYPERCUBE was set as default on GNI only for non-SMP mode, and in an indirect manner via inclusion of conv-mach-pxshm by default for GNI. So, it wont affect the SMP build, but Jim has a valid point about benchmarking. I did not benchmark the effect for non-SMP version. 

Jim, what benchmark would be a reasonable one and how may nodes/cores?

**Comment by jcphill** [comment]
*Original date: 2015-08-07 19:05:24*

---
Non-smp is only for smaller systems, so STMV on 128 nodes would be a good test.

Since we're looking at broadcasts it would be great if someone went a little deeper into topology, physical node, and node adaptation.

**Comment by PhilMiller** [comment]
*Original date: 2015-08-17 14:56:48*

---
Closed by linked patch being merged? Maybe open another bug for whatever other issue might be observed as in comments 13 & 14 from Jim?

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:19*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
