### ISSUE TITLE
charmxi: Report errors and warnings in a standard format including file name and line number

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#75]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/75*

---
charmxi prints various error and warning messages when it finds problems with its input, but they are highly variable. At the very least, they should all report the file and line on which an issue arises, in a consistent format. Even better, the messages should follow some consistent grammar, too. If we want to be really fancy, printing the affected line with indicative markup like clang does would be awesome.

**Comment by nikhil-jain** [comment]
*Original date: 2014-01-06 04:36:45*

---
Inactive for 3 months; should be a small task; increasing the priority.
