### ISSUE TITLE
charmrun: ++debug fails when the executable filepath has spaces in it

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#755]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/755*

---
The full filepath passed to the debugger is not quoted/properly escaped, leading to a confusing "file cannot be found" error on e.g. `gdb`.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:20*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
