### ISSUE TITLE
Multicore build polls non-existent network

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#757]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/757*

---
When I profile a benchmark run on a multicore-linux64, I see substantial time being spent in `CommunicationServerNet()`, called from `CmiGetNonLocal()` and `CmiNotifyStillIdle()`, both in machine-common-core.c. This is completely wasted time, since there is no network to be polled.

Fixing this ought to be as simple as extending the `#ifdef` in `CmiGetNonLocal` for an early return on multicore builds.

**Comment by jcphill** [comment]
*Original date: 2015-05-29 22:21:32*

---
Not sure how the code works exactly, but there may be a GPU to be polled, so don't accidentally eliminate the periodic calls.

**Comment by PhilMiller** [comment]
*Original date: 2015-05-29 22:23:34*

---
No worries - that code is nowhere near this.

**Comment by bilgeacun** [comment]
*Original date: 2015-06-26 19:43:44*

---
Implemented: http://charm.cs.uiuc.edu/gerrit/#/c/752

I tested tests/charm++/pingpong benchmark and observed significant reduction in execution time.

Old version:
```
Roundtrip time for 1D Arrays is 7.463217 us
Roundtrip time for 1D threaded Arrays is 11.463165 us
Roundtrip time for 1D Arrays Marshalled is 7.839918 us
Roundtrip time for 2D Arrays is 8.259058 us
Roundtrip time for 3D Arrays is 7.024050 us
Roundtrip time for Fancy Arrays is 6.875038 us
Roundtrip time for Chares (reuse msgs) is 4.098892 us
Roundtrip time for Chares (new/del msgs) is 5.639076 us
Roundtrip time for threaded Chares (reuse) is 7.488012 us
Roundtrip time for Groups is 4.554987 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 4.767895 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 6.839991 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 7.976055 us
Roundtrip time for NodeGroups is 4.397869 us
```

Fixed version:
```
Roundtrip time for 1D Arrays is 4.464149 us
Roundtrip time for 1D threaded Arrays is 10.300875 us
Roundtrip time for 1D Arrays Marshalled is 7.171154 us
Roundtrip time for 2D Arrays is 4.462957 us
Roundtrip time for 3D Arrays is 4.529953 us
Roundtrip time for Fancy Arrays is 5.262136 us
Roundtrip time for Chares (reuse msgs) is 2.921104 us
Roundtrip time for Chares (new/del msgs) is 4.500866 us
Roundtrip time for threaded Chares (reuse) is 6.536961 us
Roundtrip time for Groups is 2.863884 us
Roundtrip time for Groups (1 KB pipe, no memcpy, no allocs) is 2.902985 us
Roundtrip time for Groups (1 KB pipe, no memcpy, w/ allocs) is 4.495144 us
Roundtrip time for Groups (1 KB pipe, w/ memcpy, w/ allocs) is 5.390882 us
Roundtrip time for NodeGroups is 2.719879 us

```

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:20*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
