### ISSUE TITLE
any time migration for reduction 

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#76]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/76*

---
I am implementing intra-node load balancing. The idea is before an entry method is executed checked whether there is idle PEs.
If there is idle, and this PE has more work, push this Msg to the idle PE and also migrate the object. 

A lot of benchmark hangs. After some time, I located the bug related to reduction. whenever there is reduction in code,
it hangs. 

I have a small benchmark to test this charmgit:benchmarks/intra-node-balance/testreduction 
The charm is on branch  intra-node-balancing

After some debugging, I found the problem might be like this. 
A object is migrated to one PE in previous step. In next step, the contribution message is still regarded as migration message, which directly contribute to parent
Meanwhile its group is waiting for it.

I am doubting the problem is about the setting of redNo

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-03-06 20:30:37*

---
When Base::pup is added to pup, any time migration works with reduction

**Comment by PhilMiller** [comment]
*Original date: 2013-03-06 22:02:51*

---
We can use the 'Rejected' to distinguish issues that were in the runtime from issues in client code.
