### ISSUE TITLE
Typo in void CtgInit(void) in both global-elfcopy.C and global-elfgot.C

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#767]
*Original author: Tom Coles*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/767*

---
When compiling Charm++, I noticed errors coming from the files global-elfcopy.C and global-elfgot.C in the conv-core directory. These errors are because of what I think is a typo in the void CtgInit(void) function, which is present in both of these files. 
The following line appears on the third line of this function in both files:  CpvInitialize(CtgGlobal,_curCtg); However, the CtgGlobal here should (I think) be CtgGlobals. 
I expect that this might be unimportant because of the preprocessor errors in these files "Global-elfcopy won't work properly under smp version: -copyglobals disabled", but it nevertheless showed up as extra errors when compiling and made me think that something wasn't working properly.

**Comment by ericjbohm** [comment]
*Original date: 2015-08-17 18:51:54*

---
The typo does not currently matter because CpvInitialize does nothing in non-SMP mode, and we do not support swapglobals in SMP mode.  Regardless, I have fixed the typo and pushed the change in for review.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:21*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
