### ISSUE TITLE
checkpoint writes should be checked for errors

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#768]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/768*

---
In  CkCheckpointMgr::Checkpoint(), the writes and closes don't get checked for errors.  I propose that at least the closes should be.  The opens are checked in openCheckpointFile().  Checking writes would mean changing the PUP::toDisk::bytes() method.

**Comment by PhilMiller** [comment]
*Original date: 2015-07-16 18:50:42*

---
This may need some discussion, since we need to decide what it should do in response to various errors. We don't want to create a situation where a transient FS error kills a job that would otherwise have continued to run successfully.

**Comment by xiangni** [comment]
*Original date: 2015-07-22 03:33:20*

---
If errors happen during write and file close, should we just ignore the current checkpoint and let application back to execution? We will wait for the next checkpoint to try again.

**Comment by trquinn** [comment]
*Original date: 2015-07-22 05:35:21*

---
Allowing the application to continue on makes sense.  However, the application should be able to know that something has gone wrong, and that the recent checkpoint is garbage.  Perhaps the callback should have an argument that can indicate success/failure?

**Comment by jcphill** [comment]
*Original date: 2015-07-22 16:59:10*

---
It depends what the error is.  Most transient errors can be retried for some number of times.  Errors like a full filesystem should probably kill the program.

**Comment by trquinn** [comment]
*Original date: 2015-07-22 17:33:18*

---
The CmiFwrite() and CmiFclose() already catch "EINTR" and retry, which is what Lustre throws when it wants you to try again.  The ones that are left are "EAGAIN" and "EPIPE" (not relevant, I think) "EBADF", "EFAULT", "EFBIG", EINVAL, (all programming errors), "EIO" ("Disk On Fire" error; I think it would be a really good idea to kill the program on this one), and "ENOSPC" (Probably kill the program on this one?).

**Comment by jcphill** [comment]
*Original date: 2015-07-23 01:52:38*

---
There is also the standard short write (fewer bytes written than requested) that can also be retried.

**Comment by jcphill** [comment]
*Original date: 2015-07-23 01:55:44*

---
Also, it looks like NAMD has come across ENOMEM at some point, judging from Output.C:


```
00083 void NAMD_write(int fd, const char *buf, size_t count, const char *errmsg="NAMD_write64") {
00084   double firsttime = 0.;
00085   while ( count ) {
00086 #if defined(WIN32) && !defined(__CYGWIN__)
00087     long retval = _write(fd,buf,count);
00088 #else
00089     ssize_t retval = write(fd,buf,count);
00090 #endif
00091     if ( retval < 0 && errno == EINTR ) retval = 0;
00092     if ( retval < 0 && errno == ENOMEM ) {
00093       if ( firsttime == 0. ) firsttime = CmiWallTimer();
00094       if ( (CmiWallTimer() - firsttime) < 300. ) retval = 0;
00095     }
00096     if ( retval < 0 ) NAMD_err(errmsg);
00097     if ( retval > count ) NAMD_bug("extra bytes written in NAMD_write64()");
00098     buf += retval;
00099     count -= retval;
00100   }
00101   if ( firsttime != 0. ) {
00102     iout << iWARN << errmsg << ": NAMD_write64() retried for " << (CmiWallTimer() - firsttime) << " seconds.\n" << endi;
00103   }
00104 }
00105 
```

**Comment by xiangni** [comment]
*Original date: 2015-07-27 16:20:16*

---
I pushed a change to gerrit. Now we provide an extra interface if users want to know if checkpoint is complete or not. I'm still debating whether to kill the job in the runtime system or not. Or maybe we should also tell the users what kind of errors have happened?

Tom, I can't add you as a reviewer in gerrit, it says "Tom Quinn <trq`astro.washington.edu> does not identify a registered user or group". Do you have another account?

**Comment by xiangni** [comment]
*Original date: 2015-09-22 20:47:50*

---
Based on the discussion during core meeting:
1. Allow user to choose the tolerance of failures during checkpointing: "can fail", "must succeed".
2. If "can fail", RTS just returns "1" or "0" informing user if checkpoint is successful or not.
3. If "must succeed", RTS prints all the error messages during checkpoint writing in addition to returning the flag (indicating checkpoint fails or not) and user decide whether to abort the program or not.

**Comment by jcphill** [comment]
*Original date: 2015-09-23 12:54:39*

---
I think Xiang's note is a mix of the initial and final proposals.  Since the caller is required to provide a callback there is no reason that the checkpoint library needs to abort internally.  The simplest options is for the caller to provide a "verbose errors" flag to cause (a histogram of?) fatal errors to be printed on stderr for the user to diagnose.  Non-fatal errors (e.g., interrupted system call) should of course be re-tried internally to the output routines on each processor.  The callback will indicate if the checkpoint succeeded or not, and the caller can decide to abort, retry immediately, or retry later in the run.  A typical use case might be that after two failed checkpoints in a row the caller enables verbose errors for the next checkpoint and exits if it also fails, but this does not need to be enforced.
Perhaps three modes would simplify the typical use case:
 "hide errors" - just returns success or failure
 "print errors" - print errors to stderr and return success or failure
 "die on error" (default) - print errors to stderr and exit on failure

**Comment by PhilMiller** [comment]
*Original date: 2015-10-20 20:08:54*

---
~~https://charm.cs.illinois.edu/gerrit/758~~ https://github.com/UIUC-PPL/charm/commit/b3aaca24ca99f4a87f98db156502a3fdfb5518fd

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:22*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
