### ISSUE TITLE
Variable-size ckcallbacks

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#79]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/79*

---
Instead of byte-pupable ckcallbacks, change them to be variable-size.

Outstanding work:
- Fix use in CkReductionMsg
- Implement semi-analogous structure for callbacks in messages
- Test more complex cases using Thread callbacks with ChaNGa
- Merge into mainline

**Comment by lifflander** [comment]
*Original date: 2013-05-24 00:31:38*

---
This will be obviated by the objid in ckcallbacks. Hence, a non-issue

**Comment by PhilMiller** [comment]
*Original date: 2013-09-17 20:19:32*

---
De-target since it was rejected.
