### ISSUE TITLE
Enable cuda builds of charm to run non-cuda programs

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#792]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/792*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:33:40*

---
This seems like a significant bug to me if I understand it correctly and if it is still pertinent: you can't build Charm with CUDA support and run a simple Charm program that doesn't use CUDA?

**Comment by mprobson** [comment]
*Original date: 2017-02-01 20:18:24*

---
This bug is fixed/obviated by patch ~~https://charm.cs.illinois.edu/gerrit/#/c/2063/~~ https://github.com/UIUC-PPL/charm/commit/a873294f7fc69b0ea9404863fd94dcd1991bf32d
