### ISSUE TITLE
Write default cuda kernelSelect so cuda build works out of the box

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#793]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/793*

---
No body.

**Comment by mprobson** [comment]
*Original date: 2017-02-01 20:19:52*

---
This bug is fixed/obviated by patch ~~https://charm.cs.illinois.edu/gerrit/#/c/2063/~~ https://github.com/UIUC-PPL/charm/commit/a873294f7fc69b0ea9404863fd94dcd1991bf32d

**Comment by PhilMiller** [comment]
*Original date: 2017-02-12 02:12:42*

---
Already done, so mark as part of the current pending release, not its successor
