### ISSUE TITLE
build process modifies charmc resulting in "Text file busy" errors

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#797]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/797*

---
When I try to do simultaneous builds, the ones started earlier die with "Text file busy" errors on the charmc script:
```
jim`sunnyvale$grep "Text file busy" *
Linux-x86_64-ibverbs.log:/bin/sh: ../bin/charmc: /bin/sh: bad interpreter: Text file busy
Linux-x86_64.log:/bin/sh: ../bin/charmc: Text file busy
Linux-x86_64-multicore.log:gmake[1]: execvp: ../bin/charmc: Text file busy
Linux-x86_64-TCP.log:gmake[1]: execvp: ../bin/charmc: Text file busy
```
I then see that the build process is in fact doing something to modify the charmc script and its Makefile:
```
 jim`sunnyvale$ls -l src/scripts/
 total 720
 -rwxr-xr-x 1 jim namd  48708 Aug  4 16:17 charmc*
 -rw-r--r-- 1 jim namd    692 May 19 15:46 charm.mk
 -rwxr-xr-x 1 jim namd    588 May 19 15:47 commitid.sh*
 -rwxr-xr-x 1 jim namd    551 May 19 15:46 commitid.sh.orig*
 -rwxr-xr-x 1 jim namd 151822 May 19 15:47 configure*
 -rw-r--r-- 1 jim namd  60113 May 19 15:46 configure.in
 -rw-r--r-- 1 jim namd   7801 May 19 15:46 conv-autoconfig.h.in
 -rw-r--r-- 1 jim namd   3801 May 19 15:46 conv-config.sh
 -rwxr-xr-x 1 jim namd    826 May 19 15:46 dep.pl*
 -rwxr-xr-x 1 jim namd    338 May 19 15:46 gatherflat*
 -rwxr-xr-x 1 jim namd   1401 May 19 15:46 gathertree*
 -rw-r--r-- 1 jim namd   4666 May 19 15:46 Make.cidepends
 -rw-r--r-- 1 jim namd 223183 May 19 15:46 Make.depends
 -rw-r--r-- 1 jim namd  40332 Aug  4 16:17 Makefile
 -rw-r--r-- 1 jim namd  20879 May 19 15:46 Makefile.win32
 -rw-r--r-- 1 jim namd     11 May 19 15:46 Make.tau
```
This appears to be due to the following lines in the build script:
```
 sed -e $SED_CHARMC $srcbase/scripts/Makefile > .Makefile.$$ && cp .Makefile.$$ $srcbase/scripts/Makefile && rm -f  .Makefile.$$
 sed -e $SED_CHARMC $srcbase/scripts/charmc > .charmc.$$ && cp .charmc.$$ $srcbase/scripts/charmc && rm -f .charmc.$$
```
This should not be done to charmc and Makefile in place (make a copy!) or at the very least only do it in the very rare circumstance that Tau is being used.

**Comment by jcphill** [comment]
*Original date: 2015-08-04 22:12:54*

---
I think replacing the cp followed by rm -f with mv -f would fix this, as mv is atomic.

**Comment by jcphill** [comment]
*Original date: 2015-08-05 18:17:47*

---
On second thought, cp is likely used to preserve the permissions of the original file, so mv is not a substitute.

**Comment by ericjbohm** [comment]
*Original date: 2015-10-26 17:18:07*

---
Moved the TAU file hackery down into the TAU conditional block.  Collision still theoretically possible, but only if someone is doing both simultaneous builds and TAU.  If that ever comes up we can worry about it then.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:22*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
