### ISSUE TITLE
Add tests and documentation for sparse-array bulk construction

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#798]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/798*

---
Feature #554 added bulk construction for spare arrays in Charm++. Need to ensure that documentation and tests are up to date.

**Comment by epmikida** [comment]
*Original date: 2015-10-27 02:33:53*

---
Implemented in changes 879 and 873, just waiting for a merge.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:17*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.

**Comment by PhilMiller** [comment]
*Original date: 2016-08-04 02:36:54*

---
For ease of cross-reference: ~~https://charm.cs.illinois.edu/gerrit/879~~ https://github.com/UIUC-PPL/charm/commit/1d3dc7558ce2c080373f7da7d565cc9a6423e09f
