### ISSUE TITLE
Create separate builds for accel and gpu manager

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#801]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/801*

---
Building accel (once merged) might break gpu manager so we want separate macros (CMK_CUDA_ACCEL AND CMK_CUDA_GPU) because they both currently share CMK_CUDA. This will need more testing once merged.

Accel depends on GPU manager so we want the CMK_GPU stuff turned on as well whereas gpu manager does not want anything inside CMK_CUDA_ACCEL

**Comment by minitu** [comment]
Currently there are no plans on integrating accel into Charm++ mainline, closing this issue for now.
