### ISSUE TITLE
CUDA examples broken on Blue Waters

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#802]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/802*

---
From Eric Bohm:
```
Fatal CUDA Error at cuda-hybrid-api.cu:450.
Return value 46 from 'cudaStreamCreate(&kernel_stream)'.  Exiting.
```
This on bluewaters in non smp mode. Looks like it happens when there is more than 1 PE per node, which is kind of the expected case in non-smp.

NOTE: I think the node level manager we're working on will fix this but I wanted to go ahead and document it outside of Changa.

**Comment by jcphill** [comment]
*Original date: 2015-08-11 19:47:02*

---
I'm guessing that the GPU is in process-exclusive mode.
The real bug is that the raw error code is printed rather than the equivalent error string, as well as the node and device number.

**Comment by jcphill** [comment]
*Original date: 2015-08-12 15:33:44*

---
As a follow-up, you never want multiple processes using the same GPU unless you are using the CUDA Multi Process Service (MPS), which aggregates the API calls to allow kernels from different processes to overlap.

**Comment by mprobson** [comment]
*Original date: 2016-02-15 20:50:21*

---
When running the same hello program on blue waters using the nodeGPU patch we also get an error, albeit a different one:
```
mprobson`nid25349:~/charm/gni-crayxe-cuda-nodeGPU-g/examples/charm++/cuda/hello> make test
./charmrun  ./hello +p4 10 

Running on 4 processors:  ./hello 10
aprun -n 4 -d 2 ./hello 10
Init HYBRID API [0]
Init HYBRID API [0]
Fatal CUDA Error all CUDA-capable devices are busy or unavailable at cuda-hybrid-api.cu:913.
 Return value 46.Exiting on cudaMallocHost((void **)&hd, (sizeof(Header)+bufSize)) .
_pmiu_daemon(SIGCHLD): [NID 25200] [c5-2c0s7n0] [Mon Feb 15 14:13:29 2016] PE RANK 2 exit signal Aborted
[NID 25200] 2016-02-15 14:13:29 Apid 33630471: initiated application termination
Application 33630471 exit codes: 134
Application 33630471 resources: utime ~0s, stime ~1s, Rss ~6240, inblocks ~8653, outblocks ~19125
make: *** [test] Error 134
```
I'm currently working on improving error reporting to debug.

**Comment by mprobson** [comment]
*Original date: 2016-02-16 18:52:37*

---
As a result of Debug Day:
1. I have an improved error checking patch that I'm going to clean up and submit, I'll post the link here when I do
1. Due to this patch I was able to determine that nodeGPU has the same error
1. Which means that Jim was (probably) right about the machine being in process exclusive mode by default

> * I check and BW uses default so multiple processes should be able to access the device
> * However that doesn't actually seem to be the case
> * Fortunately,  you can fix this with `export CRAY_CUDA_MPS=1`
> * Check this link: https://bluewaters.ncsa.illinois.edu/accelerator-jobs-on-xk-nodes
> * Enabling CRAY_CUDA_MPS fixes the crash in both builds

1. My plan is to add this to the manual
1. I also plan to try this on Titan and see if there is a similar configuration issue

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:03:16*

---
Is this issue up to date or did things get merged for it?

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 14:32:44*

---
Bump, what is the status of this issue?

**Comment by stwhite91** [comment]
*Original date: 2018-03-15 20:31:49*

---
Not a release blocker

**Comment by ericjbohm** [comment]
Should this be closed?
