### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#804]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/804*

---
Contributors and current developers list at the end is about 5 years out of date.  Shift current up into former, add PPLers from the missing years, and put the current core team in as developers.

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-26 17:26:23*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/871/~~ https://github.com/UIUC-PPL/charm/commit/f5468a2e4d66116bb9c25412264992cd1423dd6e

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:23*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
