### ISSUE TITLE
SDAG tracing counts time waiting for a when to be satisfied as overhead

### ISSUE THREAD

**Issue by epmikida** [UIUC-PPL/charm#805]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/805*

---
When a when block is unsatisfied, SDAG still traces it as SDAG overhead, even though at this point the runtime is free to do other things. Tracing of SDAG overhead should stop when a when goes unsatisfied.

**Comment by lifflander** [comment]
*Original date: 2015-08-20 20:11:51*

---
Fix has been implemented. Needs to undergo testing.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-03 19:43:02*

---
I don't see the patch posted on Gerrit. Could you push it and post a link?

**Comment by PhilMiller** [comment]
*Original date: 2015-09-22 21:22:21*

---
Could we get that patch posted for review & integration? It'd be nice to have it integrated before 6.7, if it's already done.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-09 03:52:04*

---
Ping - please post the patch.

**Comment by lifflander** [comment]
*Original date: 2015-11-10 00:07:34*

---
Working on putting together the patch.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-04 20:10:48*

---
Ping. Is there a fix for this? Even if it's only partial, we can hand that off to someone else to finish up.

**Comment by PhilMiller** [comment]
*Original date: 2016-02-11 17:46:11*

---
Ping, again. Is there actually fixed code for this sitting in a repository somewhere, or is that still a work in progress?

**Comment by stwhite91** [comment]
*Original date: 2016-03-08 20:10:37*

---
What's the status of this?

**Comment by stwhite91** [comment]
*Original date: 2016-03-17 14:02:19*

---
Jonathan said he has a partial fix but that it wasn't entirely correct, so he'll look at it again.

**Comment by epmikida** [comment]
*Original date: 2017-04-12 02:53:44*

---
I can't seem to reproduce this bug, and the code looks pretty sound from what I can tell. The only way TRACE_EXECUTE_BEGIN is called with SDAG_RTS as the entry point will always be from within an invokeEntry call. These calls end with the corresponding TRACE_EXECUTE_END() from either ck.C:651 or cklocation.C:1981.
