### ISSUE TITLE
CkReduction::set breaks CkMulticast section reductions

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#806]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/806*

---
Any section reduction where the size of the output CkReductionMsg changes with each contribution fails.
This means that CkReduction::set, CkReduction::concat, and any custom reductions that gather contributions together in any fashion will fail.

When aborting CkMulticast outputs "Reason: Reduction data are not of same length!"

[McastSetRedn.tar](https://github.com/UIUC-PPL/charm/files/3536545/McastSetRedn.tar.gz)

**Comment by stwhite91** [comment]
*Original date: 2015-08-17 14:47:34*

---
To reproduce, change the reduction type in examples/charm++/hello/xarraySection/hello.C

**Comment by lvkale** [comment]
*Original date: 2015-08-17 19:28:44*

---
The only information available at the place where the check is made (near line 1328 in ckmulticast.c) is a a pointer to the reducer function. So, this check should not happen at that place. Suggested action (a) remove the check (b) see if it can be added inside individual reduction functions that are predefined (such as max/min/sum, I assume) where it makes sense. I think it makes sense to do (a) with high priority and do (b) later with somewhat lower priority, unless its obvious what to do.

**Comment by lvkale** [comment]
*Original date: 2015-08-17 19:36:40*

---
Sam: I listed (a) as a quickfix. You should do it so your app can continue. If it seems easy enough to do (b) (add the test in individual functions) then go ahead, otherwise postpone this.

**Comment by stwhite91** [comment]
*Original date: 2015-08-17 23:09:05*

---
Removing the check does not fix the issue. It seems like there is a deeper assumption somewhere in ckmulticast's implementation of reductions.

When the abort is removed, the resulting CkReductionMsg is corrupted. If using CkReduction::set, traversing the CkReduction::setElement linked list results in a segfault. And if using a custom reduction, the return values are corrupt. I'll continue debugging it.

**Comment by stwhite91** [comment]
*Original date: 2015-09-25 17:01:55*

---
Removing the check does not fix the issue. It seems like there is a deeper assumption somewhere in ckmulticast's implementation of reductions.
When the abort is removed, the resulting CkReductionMsg is corrupted. If using CkReduction::set, traversing the CkReduction::setElement linked list results in a segfault.
Attached is an example program that does a CkReduction::set operation across an x-array section.

**Comment by stwhite91** [comment]
*Original date: 2015-10-19 02:48:00*

---
A workaround for implementing a Section AllGather in Charm++ is to have all chares contribute a buffer (with size equal to the resulting buffer size) that has all of the non-local elements zeroed out to a CkReduction::sum_{type} reduction.

**Comment by epmikida** [comment]
*Original date: 2015-11-11 00:53:18*

---
This is actually a bug with all reductions that grow in size (ie: concat and set). I've started looking at section reductions, and Ronak and I are refactoring reductions to behave more consistently among reduction managers, so this falls under that purview, so I've tentatively reassigned it to me.

**Comment by epmikida** [comment]
*Original date: 2016-02-15 18:03:47*

---
Removing the size check above is all that is needed to fix the issues with concatenation. The size was already correctly maintained throughout the reduction. Set still has weird memory corruption that I need to track down. It's possibly because the actual size of a set message needs to include extra bits for the delimiters that are not taken into account in the multicast reductions.

**Comment by epmikida** [comment]
*Original date: 2016-02-15 18:35:13*

---
Found the source of the error. It appears messages are not being correctly marked as leaves vs interior messages which changes how the set reducer function works.

**Comment by epmikida** [comment]
*Original date: 2016-02-15 19:38:53*

---
Fixed in ~~https://charm.cs.illinois.edu/gerrit/#/c/1055/~~ https://github.com/UIUC-PPL/charm/commit/cd10f91ed7f5734af2412e309f17a9236b07cc021
