### ISSUE TITLE
redo performance comparison

### ISSUE THREAD

**Issue by lvkale** [UIUC-PPL/charm#807]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/807*

---
SInce its an old bug, its worthwhile re-doing a perfoemance comparison.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 18:35:55*

---
not worth pursuing extensive analysis on this platform as pami efforts are now oriented to the newer versions of pami on new platforms.
