### ISSUE TITLE
Implement a communication aware load balancer

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#808]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/808*

---
Implement a comm aware load balancer based on KL or FM algorithm.

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:31:52*

---
This issue description is pretty vague to me, so closing for now. It can be reopened under a more descriptive listing if it is still desired.
