### ISSUE TITLE
Manytomany on PAMI SMP hangs without Async

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#81]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/81*

---
charm++/penciltest and NAMD with optPME/manytomany set to 1 hangs  for SMP (without async).   ASYNC works

**Comment by PhilMiller** [comment]
*Original date: 2013-03-25 15:22:20*

---
Sameer confirmed the issue and said he will fix it:
> I looked at the manytomany implementation and its broken for SMP w/o ASYNC.  I will fix this asap.  Please use manytomany with ASYNC enable till I can fix that.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 22:25:00*

---
Sameer's not registered here, so we can't just assign it to him. He is upstream for this in a sense, though, so set that to indicate that it's not on our plate.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-14 01:15:06*

---
Any word from Sameer about progress on this?

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-14 19:58:25*

---
I have not heard anything back from Sameer

**Comment by PhilMiller** [comment]
*Original date: 2013-10-09 20:53:40*

---
Short-term change noted in #302. Keeping this open and future-targeted for long-term fix.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-10-11 03:44:55*

---
Temporary solution is to force user compile charm with async if they use many to many. Other abort. 

For all many-to-many interface, I added the following 

#if CMK_SMP && !CMK_ENABLE_ASYNC_PROGRESS
    CmiAbort("!!!!!!!!!Please build Charm++ with async in order to use many-to-many interface\n");
#else

  do work

#endif

**Comment by PhilMiller** [comment]
*Original date: 2013-10-11 03:49:06*

---
I split the checking off to #302 so that we can clearly track our interactions with IBM over this issue here.

**Comment by ericjbohm** [comment]
*Original date: 2018-12-06 21:11:10*

---
Old CkDirect based version slated for removal.  PAMI support for this appears to be dead.  Basic idea needs reconstruction in context of zerocopy.
