### ISSUE TITLE
Update Ch. 4 of the manual on chare array reductions

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#810]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/810*

---
Section 4 of the manual does not list the pre-defined typed reduction functions for type 'long' though they exist.
There are also other typos.

**Comment by stwhite91** [comment]
*Original date: 2015-09-03 17:05:02*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/796/~~ https://github.com/UIUC-PPL/charm/commit/031733cd578e06f2a95b8da30c9fb1abb9d3b764

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:24*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
