### ISSUE TITLE
Publish GPU manager documentation

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#813]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/813*

---
mprobson/gpu-manager-doc-cleanup

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:06:52*

---
~~https://charm.cs.illinois.edu/gerrit/806~~ https://github.com/UIUC-PPL/charm/commit/5ad8c5d52cab740f3330c115e195f40a84561d24
