### ISSUE TITLE
tcharm/ampi '+vp<N>' option provokes a false warning

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#814]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/814*

---
The recent commit here (~~https://charm.cs.illinois.edu/gerrit/#/c/789/~~ https://github.com/UIUC-PPL/charm/commit/7d66202179f2ffde00394f8d51ece12d22f90eb2) doesn't account for the common usage of AMPI/tcharm's '+vp' option, so it issues false warnings about the runtime not consuming that flag.
In our example programs and documentation this option is usually given as '+vpN' instead of 'vp N', as in './charmrun +pN ./pgm +vpN'.
The false warning might be unsettling to new users of AMPI.

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-18 16:00:16*

---
Most likely this commit should fix this issue: https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commit;h=7d66202179f2ffde00394f8d51ece12d22f90eb2

(note that this commit was merged last night).

**Comment by stwhite91** [comment]
*Original date: 2015-08-18 18:00:00*

---
I reviewed that commit, and it ignores the spacing issue: it handles '+vp N' correctly but issues false warnings for '+vpN'.
The most common usage of AMPI's '+vp' option is to have no space between the flag and its argument.

**Comment by epmikida** [comment]
*Original date: 2015-09-01 21:12:00*

---
Addressed fully by fixes to bug 654.
