### ISSUE TITLE
AMPI's Fortran 'apup' interface breaks without complete Fortran2003 support

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#823]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/823*

---
The Fortran "apup" interface makes use of Fortran2003's type polymorphic "interface" feature to provide a single PUP function for pointers and allocatables of all basic types (logicals, chars, ints, reals, complexes) and sizes/shapes.
Unfortunately, this features breaks for GCC pre-4.9.0, ICC pre-15.0, and XLC pre-and-including-14.0.

Since compiler versions that provide this support are not common, make the apup interface use a separate API for allocatables by default.

**Comment by stwhite91** [comment]
*Original date: 2015-09-03 17:07:48*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/822/~~ https://github.com/UIUC-PPL/charm/commit/b22635314fb3ee2cd74b1f5edb9ec677fe515b4f

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:24*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
