### ISSUE TITLE
Link time error for Neighbor LB

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#825]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/825*

---
This merged change breaks linking when Neighbor LB is used. Linking order of cldb-*.a is incorrect.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-17 20:14:24*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/826/~~ https://github.com/UIUC-PPL/charm/commit/5c8ce0e179b74040006a64a00b9c535cbb88b106
