### ISSUE TITLE
Chare array construction semantics differ wrt readonly array proxy on PE 0

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#828]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/828*

---
When creating a chare array from a mainchare's main routine, on PE 0 chare array elements are created inline at the ckNew call, but for remote chare creation a message is sent after the inline calls complete. If the constructor for chare elements in this chare array makes use of a global variable for the proxy to its array (i.e. it sets the return value of ckNew as a global 'arrayProxy'), then this global value will be valid on all PEs except PE 0.

This arose in an application that used a global variable instead of 'thisProxy' in a chare array constructor to create a CkCallback for a later reduction. Since this global was undefined on PE 0, the reduction would fail with the message "Error! This group proxy has not been initialized!"

[simple_reduction.tar](https://github.com/UIUC-PPL/charm/files/3536555/simple_reduction.tar.gz)

**Comment by stwhite91** [comment]
*Original date: 2015-09-05 03:09:51*

---
Assigning to Nikhil based on module ownership...

**Comment by stwhite91** [comment]
*Original date: 2015-09-07 15:59:51*

---
This program reproduces the error. Since the behavior is non-deterministic, you will probably have to run it several times to reproduce it.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-08 05:41:51*

---
https://charm.cs.illinois.edu/gerrit/#/c/823/

Use of array listeners makes dropping inline-element creation slightly difficult. The above listed change showcases the round about way of doing the same.

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 18:40:15*

---
Is it worth taking another look at this after the recent infrastructure changes?

**Comment by epmikida** [comment]
*Original date: 2019-04-02 18:46:28*

---
Is this required for something important? As Nikhil mentioned above, I think inline array creation is fairly ingrained in the RTS to the point where certain applications depend on it (although they probably shouldn't). I know when the topic has come up before, there's been resistance in removing the inline creation. I also can't really think of any cases where you wouldn't just use 'thisProxy', or  pass in the value of a different proxy. I can take a look into inline creation again and see if any changes over the past years have made it any less difficult to remove.

**Comment by stwhite91** [comment]
*Original date: 2019-04-02 19:27:22*

---
No, it can be closed
