### ISSUE TITLE
CkLoop projections tracing doesn't reflect the origin/traceback of work

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#829]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/829*

---
~~https://charm.cs.illinois.edu/gerrit/512~~ https://github.com/UIUC-PPL/charm/commit/2e2760a1a525cb666131f6c5f8214e0b4b136b30

**Comment by ericjbohm** [comment]
*Original date: 2016-09-21 18:42:07*

---
Has a consistent approach been implemented regarding projections tracing of our node level parallel schemes?

**Comment by PhilMiller** [comment]
*Original date: 2017-09-29 15:12:04*

---
Is this a direct duplicate of #1437? Or is there something more subtle here still to be addressed beyond that?

**Comment by rbuch** [comment]
*Original date: 2017-10-04 18:25:42*

---
As far as I know, this is a duplicate of #1437, and it's been fixed in ~~https://charm.cs.illinois.edu/gerrit/#/c/3084/~~ https://github.com/UIUC-PPL/charm/commit/1620b19d543848e3ee1e8ad4ff32c440491698de.  I'll close it.
