### ISSUE TITLE
SDAG case crashes if a message arrives before the associated CSpeculation structure is allocated

### ISSUE THREAD

**Issue by lifflander** [UIUC-PPL/charm#83]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/83*

---
If a message arrives for a `case` first and the `CSpeculation` structure is not allocated yet, there will be a invalid memory access (logically)

**Comment by PhilMiller** [comment]
*Original date: 2013-05-01 19:06:15*

---
Retitle to be more specific

**Comment by lifflander** [comment]
*Original date: 2013-05-24 00:25:39*

---
I have verified in the generated code that this case will not arise.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-07 21:11:38*

---
Removing release version, since it's not a relevant change for the release.
