### ISSUE TITLE
Reject duplicate command line arguments that don't make sense to repeat

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#831]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/831*

---
Many command line arguments only make sense to process once - e.g. `+ppn`. The runtime should check for and error on attempts to pass such an argument multiple times.

**Comment by sbak5** [comment]
*Original date: 2016-02-15 22:10:15*

---
When a user inserts duplicate arguments for the same option, charm RTS abrots the app and print the message saying that user inserted duplicate parameters. 

This is the link to gerrit. ~~https://charm.cs.illinois.edu/gerrit/#/c/1062/~~ https://github.com/UIUC-PPL/charm/commit/f10c746576f3608207c4b621d7bdcb5c1c5756ec
