### ISSUE TITLE
+traceprocessors  causes crash.

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#834]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/834*

---
No body.

[out](https://github.com/UIUC-PPL/charm/files/3536562/out.txt)

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-18 13:17:11*

---
Offloading Ronak.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-18 13:18:27*

---
In order to get it running, I had done the following change:


```
diff --git a/src/ck-perf/trace-projections.C b/src/ck-perf/trace-projections.C
index 41c225e..5876e14 100644
--- a/src/ck-perf/trace-projections.C
+++ b/src/ck-perf/trace-projections.C
`` -1045,7 +1045,7 `` TraceProjections::TraceProjections(char **argv):
        currentPhaseID(0), lastPhaseEvent(NULL)
 {
   //  CkPrintf("Trace projections dummy constructor called on %d\n",CkMyPe());
-
+  _logPool = NULL;
   if (CkpvAccess(traceOnPe) == 0) return;
 
   CtvInitialize(int,curThreadEvent);
```

**Comment by pplimport** [comment]
*Original author: Probir Roy*
*Original date: 2015-09-24 21:46:41*

---
I could not regenerate the bug. I ran "./charmrun ++local ./jacobi3d.prj 64 64 +p32 +traceprocessors 3 ++verbose". I am using netlrts build.

I have attached the output as reference.

**Comment by pplimport** [comment]
*Original author: Probir Roy*
*Original date: 2015-10-06 18:31:45*

---
Nikhil to add the fix he has, the bug is not reproducible with simple cases

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-13 19:23:50*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/856/~~ https://github.com/UIUC-PPL/charm/commit/0e62935a5d15a0c86e9d7b4114c3a8ca38f33b2e

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:25*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
