### ISSUE TITLE
net-linux-smp crash in autobuild

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#835]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/835*

---
Investigate the cause for the crash. Attempt a run with +isomalloc_sync as a possible solution.

**Comment by bilgeacun** [comment]
*Original date: 2015-09-18 19:03:30*

---
+isomalloc_sync does not solve the problem.. The crash happens once in a while and the same problem exists in netlrts as well.
I'm investigating it more..

**Comment by bilgeacun** [comment]
*Original date: 2015-09-18 19:17:30*

---
The fix is implemented here: ~~https://charm.cs.illinois.edu/gerrit/#/c/832/~~ https://github.com/UIUC-PPL/charm/commit/7ecb906c111ebd6968f142cbf6ddfdb5f89d0849

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:25*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
