### ISSUE TITLE
net-cygwin fails to compile xi-scan.C

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#836]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/836*

---
Investigate the compilation failure of xi-scan.C

**Comment by PhilMiller** [comment]
*Original date: 2015-09-21 18:31:40*

---
As seen here: http://charm.cs.uiuc.edu/autobuild/old.2015_09_21__01_04/net-cygwin.txt

```
../bin/charmc -host  -I/home/nikhil/autobuild/cygwin/charm/src/xlat-i/ -I/home/nikhil/autobuild/cygwin/charm/src/xlat-i/sdag/ -I. -DYY_NEVER_INTERACTIVE   -c -o xi-scan.o /home/nikhil/autobuild/cygwin/charm/src/xlat-i/xi-scan.C
xi-scan.C: In function 'void yy_init_buffer(YY_BUFFER_STATE, FILE*)':
xi-scan.C:1752:59: error: 'fileno' was not declared in this scope
Fatal Error by charmc in directory /home/nikhil/autobuild/cygwin/charm/net-cygwin/tmp
   Command g++ -I../bin/../include -D__CHARMC__=1 -I/home/nikhil/autobuild/cygwin/charm/src/xlat-i/ -I/home/nikhil/autobuild/cygwin/charm/src/xlat-i/sdag/ -I. -DYY_NEVER_INTERACTIVE -fno-stack-protector -std=c++0x -c /home/nikhil/autobuild/cygwin/charm/src/xlat-i/xi-scan.C -o xi-scan.o returned error code 1
charmc exiting...
make[1]: *** [xi-scan.o] Error 1
make: *** [headers] Error 2
<builtin>: recipe for target 'xi-scan.o' failed
```

**Comment by PhilMiller** [comment]
*Original date: 2015-09-21 19:42:23*

---
Attempted fix in ~~https://charm.cs.illinois.edu/gerrit/836~~ https://github.com/UIUC-PPL/charm/commit/e3492dc8741cb45d1713ddae56685fae7bfc8041 but I can't test due to ssh login issues.

Also, great numerical coincidence!

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:26*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
