### ISSUE TITLE
pami build crash in autobuild

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#839]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/839*

---
No body.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-18 13:16:09*

---
All crashes are in io test. Reassigning to Ronak, who should reassign if necessary.

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-21 17:58:06*

---
More info on the crash:

{snd:0,rcv:0} Reason: FATAL ERROR on PE 0 working on file 'test0': fdatasync failed; system reported Function not implemented

**Comment by nikhil-jain** [comment]
*Original date: 2015-09-22 20:48:54*

---
conv-mach should have a flag that tell Charm that fdatasync should not be used; instead use fsync.

**Comment by rbuch** [comment]
*Original date: 2015-09-24 22:21:44*

---
I've added hardcoded fdatasync as not being available on PAMI builds in ronak/839-pami-io-crash.  I currently don't have an ALCF token (it's being shipped), so I can't test it right now.  I'm waiting on others to report back to see if it has succeeded.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-29 19:09:55*

---
~~https://charm.cs.illinois.edu/gerrit/843~~ https://github.com/UIUC-PPL/charm/commit/84638402ce98128856990d16af52a224ebdec9a9
Tested and merged by Nikhil

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:27*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
