### ISSUE TITLE
cray: Symbol name conflict on gethugepagesize()

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#841]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/841*

---
Per Jim:
> Hi,
> 
> It looks like the new libhugetlbfs.a on JYC has a function name gethugepagesize that conflicts with cray_tlbhack.c.
> 
> Jim
> 
> 
> /usr/lib/../lib64/libhugetlbfs.a(hugeutils.o): In function `gethugepagesize':
> /usr/src/packages/BUILD/cray-libhugetlbfs-2.16/hugeutils.c:871: multiple definition of `gethugepagesize'
> /u/sciteam/jphillip/charm-6.7.0/gemini_gni-crayxe-persistent/bin/../lib/cray_tlbhack.o:cray_tlbhack.c:(.text+0x0): first defined here

We should rename this function to avoid the conflict, which will probably become more prevalent in the near future.

[fix_gethugepagesize.patch](https://github.com/UIUC-PPL/charm/files/3536571/fix_gethugepagesize.patch.txt)
[fix_gethugepagesize.patch.1](https://github.com/UIUC-PPL/charm/files/3536573/fix_gethugepagesize.patch.1.txt)

**Comment by ericjbohm** [comment]
*Original date: 2015-09-29 17:03:42*

---
BlueWaters RSA Token expired.  Working on getting it replaced.

**Comment by PhilMiller** [comment]
*Original date: 2015-09-29 20:10:16*

---
Jim to try making the declaration `static` and submit a patch

**Comment by jcphill** [comment]
*Original date: 2015-09-29 20:28:54*

---
This file is linked only for the gni layer and appears to exist to substitute getpagesize() for gethugepagesize():

jim`sunnyvale$cat gni/Makefile.machine
BUILD_GPU_MANAGER=$(shell CHARMINC=.; if test -f ./conv-config.sh; then . ./conv-config.sh; echo $$BUILD_CUDA; fi )

ifeq "$(BUILD_GPU_MANAGER)" "1"
hybridAPI: 
           cd hybridAPI && make install

charm++: hybridAPI

.PHONY: hybridAPI
endif

$(L)/libconv-cplus-n.a: machine.h machine.c machine-common-core.c machine-broadcast.c machine-lrts.h machine-pxshm.c machine-xpmem.c machine-persistent.c machine-commthd-util.c machine-smp.c pcqueue.h  $(L)/cray_tlbhack.o

$(L)/cray_tlbhack.o: cray_tlbhack.c
        $(CHARMC) -o $` cray_tlbhack.c

jim`sunnyvale$cat gni/cray_tlbhack.c 
#include <unistd.h>

int gethugepagesize()
{
    return getpagesize();
}

From gni/machine.c:

    /*
    env = getenv("HUGETLB_DEFAULT_PAGE_SIZE");
    if (env)
        _tlbpagesize = CmiReadSize(env);
    */
    /* real gethugepagesize() is only available when hugetlb module linked */
    _tlbpagesize = gethugepagesize();
    if (myrank == 0) {
        printf("Charm++> Cray TLB page size: %1.fK\n", _tlbpagesize/1024.0);
    }

**Comment by jcphill** [comment]
*Original date: 2015-09-29 20:52:31*

---
The craype-hugepages8M module doesn't load correctly on JYC, so that may be causing this issue.

jphillip`jyc1:~> module load craype-hugepages8M
craype-hugepages8M(26):ERROR:102: Tcl command execution failed:   if {[is-loaded $mod]} {
    puts stderr "\nError:"
    puts stderr "$name is not supported for use with $mod.\n"
    exit 1
  }

**Comment by jcphill** [comment]
*Original date: 2015-09-30 21:59:22*

---
Timothy Bouvet of NCSA fixed the module script and reported the bug to the vendor, but the error persists, even for megatest:

 ../../../bin/charmc  -o pgm blkinhand.o megacon.o ringsimple.o ring.o fibobj.o fibthr.o broadc.o priotest.o deadlock.o vars.o nodenum.o specmsg.o bigmsg.o vecsend.o posixth.o future.o multicast.o multisend.o handler.o reduction.o -language converse++
 /usr/lib/../lib64/libhugetlbfs.a(hugeutils.o): In function `gethugepagesize':
 /usr/src/packages/BUILD/cray-libhugetlbfs-2.16/hugeutils.c:871: multiple definition of `gethugepagesize'
 ../../../bin/../lib/cray_tlbhack.o:cray_tlbhack.c:(.text+0x0): first defined here

**Comment by jcphill** [comment]
*Original date: 2015-09-30 22:13:23*

---

The fix is to add back the environment variable that was removed:

 export HUGETLB8M_POST_LINK_OPTS='-Wl,--whole-archive,-lhugetlbfs,--no-whole-archive -Wl,-Ttext-segment=0x20000000,-zmax-page-size=0x20000000'

**Comment by jcphill** [comment]
*Original date: 2015-10-01 13:54:20*

---
The real problem is the following lines in src/scripts/charmc:

 if [ -z "$NATIVE" -a -n "$UGNI_CFLAGS" ]
 then
     linkopt=`env | grep  "HUGETLB[0-9]*[MKG]_POST_LINK_OPTS" 2> /dev/null`
     test -z "$linkopt" && POST_LIBRARIES=`AddList $POST_LIBRARIES $CHARMLIB/cray_tlbhack.o`
 fi

This is using the environment variable as a proxy for having the hugepage module loaded.

**Comment by jcphill** [comment]
*Original date: 2015-10-01 14:29:07*

---
The attached patch fixes this by checking the LOADEDMODULES variable, which should be stable over time.

**Comment by jcphill** [comment]
*Original date: 2015-10-01 14:53:12*

---
It also looks like same mechanism is used to detect the Cray rca library:

 grep -r POST_LINK_OPT src/
 src/scripts/configure.in:test_linkc "whether Cray rca library is available" "yes" "no" "$CRAY_RCA_POST_LINK_OPTS -lrca"
 src/scripts/configure.in:test_linkc "whether Cray rca_has get_max_dimension" "yes" "no" "$CRAY_RCA_POST_LINK_OPTS -lrca"
 src/scripts/configure:test_linkc "whether Cray rca library is available" "yes" "no" "$CRAY_RCA_POST_LINK_OPTS -lrca"
 src/scripts/configure:test_linkc "whether Cray rca_has get_max_dimension" "yes" "no" "$CRAY_RCA_POST_LINK_OPTS -lrca"

If POST_LINK_OPTS are on the way out this may fail, although I suspect the $CRAY_RCA_POST_LINK_OPTS isn't doing anything.

**Comment by jcphill** [comment]
*Original date: 2015-10-01 15:03:38*

---
The rca tests will work even with $CRAY_RCA_POST_LINK_OPTS removed.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-06 17:08:25*

---
Please link to the change when moving to status 'implemented'

**Comment by jcphill** [comment]
*Original date: 2015-10-07 21:17:31*

---
Please assign this to someone else.

**Comment by jcphill** [comment]
*Original date: 2015-10-07 21:19:42*

---
Also, discussion from the meeting was that cray_tlbhack can be completely expunged.

**Comment by jcphill** [comment]
*Original date: 2015-10-13 18:01:18*

---
Attached patch removes all references to cray_tlbhack.[co].
Please also remove src/arch/gni/cray_tlbhack.c

**Comment by ericjbohm** [comment]
*Original date: 2015-10-13 19:29:06*

---
Removing tlbhack entirely seems to work just fine.  Change pushed to review.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:27*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
