### ISSUE TITLE
RRMap broken for >1D chare arrays

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#854]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/854*

---
The built-in RRMap CkArrayMap only does a true round-robin mapping for 1D arrays. For >1D arrays it hashes the indices of each element modulo a big prime number and the number of PEs. This leads to unbalanced mappings of chares to PEs (some PEs might not get any chares in some cases or some PEs will have more than others), and the behavior is not true to the API.
This is seemingly because the map interface does not know the extent of the array dimensions, only the indices of each chare array element.

**Comment by stwhite91** [comment]
*Original date: 2016-11-02 15:30:11*

---
Abandoned patch for this: https://charm.cs.illinois.edu/gerrit/#/c/1053/

BlockLB similarly does not take into account the dimensionality of a chare array.

CkArrayOptions already provides an interface (opts.setBounds()) to let users gives us the number of chares per dimension of their array, but this information is not passed through the location manager to the ArrayMap and LB objects.

A further cleanup for this issue is that section 13.2.1 of the manual should be rewritten to encourage users to use setBounds and the other things that CkArrayOptions exposes.

**Comment by stwhite91** [comment]
*Original date: 2017-02-07 03:16:45*

---
The real work here is in passing the bounds from CkArrayOptions through to CkArrayMap, so that RRMap can linearize the index space of multidimensional arrays for a true round-robin mapping.

The case of BlockLB is basically the same, BlockLB needs to know the bounds but currently doesn't.

**Comment by pplimport** [comment]
*Original author: Dong Hun Lee*
*Original date: 2017-04-19 15:11:23*

---
RRMap using Nikhil's previous code.
~~https://charm.cs.illinois.edu/gerrit/#/c/2421/~~ https://github.com/UIUC-PPL/charm/commit/04a4c404d2aff8d4f324828c13ba49433fda0a15

**Comment by stwhite91** [comment]
*Original date: 2017-05-02 16:14:52*

---
Note that the patch implements this for RRMap, and adds the mechanism to do it in BlockLB, but I think BlockLB will need to explicitly be fixed too.
