### ISSUE TITLE
mpi-win64 ckloop build fails

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#855]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/855*

---
Attached patch fixes ckloop build on mpi-win64.

[win64_ckloop.patch](https://github.com/UIUC-PPL/charm/files/3536574/win64_ckloop.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:16:37*

---
~~https://charm.cs.illinois.edu/gerrit/850~~ https://github.com/UIUC-PPL/charm/commit/d464551bd241a5becd658a94f4ffcb2b106ec265
