### ISSUE TITLE
darwin: missing CmiSetCPUAffinity fallback needed by CkLoop

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#856]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/856*

---
On netlrts-darwin-x86_64 linking with -module CkLoop fails missing CmiSetCPUAffinity.  This attached patch provides a fallback implementation, and also extends the warnings that affinity is not available from only +setcpuaffinity to include +pemap etc.

[cpuaffinity_fallback.patch](https://github.com/UIUC-PPL/charm/files/3536575/cpuaffinity_fallback.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2015-10-04 23:39:10*

---
It looks like we could actually implement CPU affinity on OS X:
https://developer.apple.com/library/mac/releasenotes/Performance/RN-AffinityAPI/#//apple_ref/doc/uid/TP40006635-CH1-DontLinkElementID_2

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:15:33*

---
~~https://charm.cs.illinois.edu/gerrit/851~~ https://github.com/UIUC-PPL/charm/commit/2f60690d86fed2b50c4f7fd608590b0fd306252d
