### ISSUE TITLE
races in nodegroup SDAG methods

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#859]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/859*

---
Inspecting the generated code there seems to be nothing to prevent SDAG control structures from being modified simultaneously by multiple pes on the same node. The only way to prevent this is to mark all SDAG-related entries exclusive, which then also serializes the code in serial blocks.
The expedient fixes would be to disable SDAG for node groups, or to make node group SDAG entries exclusive.
Going forward it seems that for and while in SDAG should serialize, while a new control structure may be needed to allow concurrent execution.

**Comment by jcphill** [comment]
*Original date: 2015-10-14 20:18:59*

---
Also wondering if the following is safe:

 entry [exclusive] recvData();
 entry processData(int i);
 entry [exclusive] workDone();

 entry [exclusive] doWork {   
  for (i=0;i < n;i++) {
    when recvData() serial {
      thisProxy[CkMyNode)].processData(i)
    }
  }
  for (i=0;i < n;i++) {
    when workDone();
  }
 }  
 
 void mynodegroup::processData(int i) {
  ...process data...
  thisProxy[CkMyNode()].workDone();
 }

**Comment by PhilMiller** [comment]
*Original date: 2015-10-21 18:06:15*

---
~~https://charm.cs.illinois.edu/gerrit/866~~ https://github.com/UIUC-PPL/charm/commit/5466f4c2422b5e7d4eb10a36c4228f66b8623ed1

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:28*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
