### ISSUE TITLE
Building Charm++ fails w/o TLS support in CkLoop

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#862]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/862*

---
The following command "./build charm++ mpi-darwin-x86_64 --with-production --enable-tracing -j8" gives the following error  
"CkLoop.C:18:8: error: thread-local storage is not supported for the current target"
       ^

**Comment by stwhite91** [comment]
*Original date: 2015-10-22 19:55:23*

---
Same for net-darwin-x86 build:

https://charm.cs.illinois.edu/autobuild/cur/net-darwin-x86.txt

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 02:00:01*

---
~~https://charm.cs.illinois.edu/gerrit/876~~ https://github.com/UIUC-PPL/charm/commit/e04d7268ed2e39e719d75d0312b5eda29f4aa6ec

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:28*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
