### ISSUE TITLE
netlrts-smp hangs or rounds up pes on startup if ppn does not divide pes

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#863]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/863*

---
Hangs: ./charmrun ++local +p13 ./namd2 ++ppn 2
Hangs: ./charmrun ++local +p13 ./namd2 ++ppn 3
Rounds up to 16: ./charmrun ++local +p13 ./namd2 ++ppn 4
Hangs: ./charmrun ++local +p13 ./namd2 ++ppn 5
Rounds up to 18: ./charmrun ++local +p13 ./namd2 ++ppn 6
Rounds up to 14: ./charmrun ++local +p13 ./namd2 ++ppn 7
etc.

jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 2 | grep SMP
Charmrun> started all node programs in 0.022 seconds.
Charm++> Running in SMP mode: numNodes 7,  2 worker threads per process
^C
jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 3 | grep SMP
Charmrun> started all node programs in 0.020 seconds.
Charm++> Running in SMP mode: numNodes 5,  3 worker threads per process
^C
jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 4 | grep SMP
Charmrun> started all node programs in 0.016 seconds.
Charm++> Running in SMP mode: numNodes 4,  4 worker threads per process
Charm++> Running on 1 unique compute nodes (32-way SMP).
CkLoopLib is used in SMP with a simple dynamic scheduling (converse-level notification) but not using node-level queue
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: FATAL ERROR: No simulation config file specified on command line.

Fatal error on PE 0> FATAL ERROR: No simulation config file specified on command line.

jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 5 | grep SMP
Charmrun> started all node programs in 0.015 seconds.
Charm++> Running in SMP mode: numNodes 3,  5 worker threads per process
^C
jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 6 | grep SMP
Charmrun> started all node programs in 0.013 seconds.
Charm++> Running in SMP mode: numNodes 3,  6 worker threads per process
Charm++> Running on 1 unique compute nodes (32-way SMP).
CkLoopLib is used in SMP with a simple dynamic scheduling (converse-level notification) but not using node-level queue
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: FATAL ERROR: No simulation config file specified on command line.

Fatal error on PE 0> FATAL ERROR: No simulation config file specified on command line.

jim`sunnyvale$./charmrun ++local +p13 ./namd2 ++ppn 7 | grep SMP
Charmrun> started all node programs in 0.012 seconds.
Charm++> Running in SMP mode: numNodes 2,  7 worker threads per process
Charm++> Running on 1 unique compute nodes (32-way SMP).
CkLoopLib is used in SMP with a simple dynamic scheduling (converse-level notification) but not using node-level queue
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: FATAL ERROR: No simulation config file specified on command line.

Fatal error on PE 0> FATAL ERROR: No simulation config file specified on command line.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 02:08:45*

---
This gets my vote for being release-critical-ish.

**Comment by stwhite91** [comment]
*Original date: 2015-10-27 22:32:41*

---
If this is going to be pushed into the 6.7 release, load balance this away from me. With the XPACC review and issue 838 I'm almost certainly  not going to touch this this week.

**Comment by stwhite91** [comment]
*Original date: 2015-12-04 02:15:26*

---
I'm re-assigning this for load balancing reasons, to Bilge because it's LRTS related.

**Comment by jcphill** [comment]
*Original date: 2016-02-04 20:50:03*

---
Ping.

**Comment by bilgeacun** [comment]
*Original date: 2016-02-15 20:48:14*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1052/~~ https://github.com/UIUC-PPL/charm/commit/059fb430eb342ada726d595057f368abab0ecf861

**Comment by nitbhat** [comment]
*Original date: 2016-02-15 22:49:32*

---
Error message is thrown and charm exits when the number of PEs per node cannot divide the number of PEs.

**Comment by nitbhat** [comment]
*Original date: 2016-02-15 22:50:01*

---
Error message is thrown and charm exits when the number of PEs per node cannot divide the number of PEs.

**Comment by PhilMiller** [comment]
*Original date: 2016-03-11 22:11:56*

---
Autobuild for `net-linux(-x86_64)-smp` is failing now, because passing `+p1 +ppn2` isn't valid. Maybe we need an additional heuristic of clamping PPN to P if the latter is lower?

**Comment by stwhite91** [comment]
*Original date: 2016-04-01 02:17:39*

---
What was decided on this?

**Comment by stwhite91** [comment]
*Original date: 2016-04-08 13:06:33*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1133/~~ https://github.com/UIUC-PPL/charm/commit/c39aa897363f8c5d1791de036eb0466a7ebec156
