### ISSUE TITLE
multicore has misleading startup message about communication thread

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#864]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/864*

---
multicore-linux64 prints on startup:
Charm++> The comm. thread both sends and receives messages

There is no communication thread (thankfully), but this is confusing.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 21:35:07*

---
~~https://charm.cs.illinois.edu/gerrit/882~~ https://github.com/UIUC-PPL/charm/commit/83090dc35b6df30f4006fdaebfb4b964d57c1bb2

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:29*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
