### ISSUE TITLE
Update section 7.3 of Manual on Load Balancing Chare arrays

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#865]
*Original author: Vipul Harsh*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/865*

---
http://charm.cs.illinois.edu/manuals/pdf/charm++.pdf  
Section 7.3 - Load Balancing Chare Arrays is not properly written. Some of the things are partially incorrect.

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:28:40*

---
It would be good if you can do a quick read over and correction of this documentation since no else in the lab has your level of knowledge in this area
