### ISSUE TITLE
Reductions should not allow mis-matched client callbacks

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#867]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/867*

---
Currently, we do not compare the callbacks, and hence let a race condition occur when callbacks don't match.

**Comment by PhilMiller** [comment]
*Original date: 2015-10-27 02:06:37*

---
~~https://charm.cs.illinois.edu/gerrit/880~~ https://github.com/UIUC-PPL/charm/commit/4ce0ac8b8ae9ad7827a6a05d9ce00d0986e1bf45

**Comment by PhilMiller** [comment]
*Original date: 2016-01-18 00:06:40*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/890/~~ https://github.com/UIUC-PPL/charm/commit/f5875dc7c7d9c9dd39817a64e89b5830c71e5b53
