### ISSUE TITLE
Test for error condition in BigSim log writing

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#868]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/868*

---
BigSim should test if ftell returns reasonable value when writing.

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-26 16:59:10*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/863/~~ https://github.com/UIUC-PPL/charm/commit/0fff51563be1a2b42135e60ba8b20c0c6e8ab886

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:29*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
