### ISSUE TITLE
Merge PICS framework to Charm

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#869]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/869*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2016-10-14 19:40:26*

---
These 3 changes have been merged:

1. Critical path header changes: ~~https://charm.cs.illinois.edu/gerrit/#/c/893/~~ https://github.com/UIUC-PPL/charm/commit/b240e238385ba2d0aa08748880b3b34ce59d03a2

2. Trace module API changes: ~~https://charm.cs.illinois.edu/gerrit/#/c/894/~~ https://github.com/UIUC-PPL/charm/commit/904294e5c4000ad2d91daba3c92c90173318f431

3. Perf report: ~~https://charm.cs.illinois.edu/gerrit/#/c/895/~~ https://github.com/UIUC-PPL/charm/commit/af83b9900c136e843ff715a65afd656c74d4ba66

I'm not sure what is left to do on this. IIRC Core decided to only merge these parts of PICS at this time, if that is correct then we can close this issue?

**Comment by stwhite91** [comment]
*Original date: 2017-02-01 18:29:27*

---
Marking this merged since there is nothing left from PICS that we decided we wanted to merge
