### ISSUE TITLE
smp standalone inconsistency

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#872]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/872*

---
If you run netlrts-smp standalone (without charmrun) +p determines the number of worker threads and +ppn is silently ignored.
For mpi-smp standalone (without mpiexec) +ppn determines the number of worker threads and +p is silently ignored.
For net-ibverbs-smp standalone either +p or +ppn are accepted, with +ppn taking precedence if both are present.

**Comment by nikhil-jain** [comment]
*Original date: 2015-10-28 03:41:32*

---
Assigning to Eric since he is currently tasked to resolve all such inconsistencies.

**Comment by jcphill** [comment]
*Original date: 2016-09-14 15:54:14*

---
Ping.

**Comment by juanjgalvez** [comment]
*Original date: 2016-09-14 16:37:05*

---
The hwloc changes being worked on at Charmworks will presumably address these and other issues (if I'm not mistaken).

**Comment by evan-charmworks** [comment]
*Original date: 2017-11-06 18:00:43*

---
What is the desired behavior?

**Comment by jcphill** [comment]
*Original date: 2017-11-06 18:17:24*

---
+ppn N, no +p -> N worker threads
+p N, no +ppn -> N worker threads
+ppn N +p N -> N worker threads
+ppn N +p M, M != N -> error
no +p or +ppn -> 1 worker thread

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-19 19:14:27*

---
~~https://charm.cs.illinois.edu/gerrit/3452~~ https://github.com/UIUC-PPL/charm/commit/6ec0f6de23ef5cf040221a8511ee90173cf634f9
