### ISSUE TITLE
send messages from non-PE threads

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#873]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/873*

---
CUDA has the ability to call back to the CPU when a kernel finishes, but the callback executes in a thread that is launched by the CUDA runtime so messages sends fail. If messages could be sent from this thread then it would not be necessary to poll the GPU for kernel completion.  This would only need to be supported in smp/multicore versions.  This could also be used for dedicated I/O threads.

**Comment by jcphill** [comment]
*Original date: 2017-02-18 20:08:55*

---
I observe that #1393 seems to have solved this issue for GPUManager.

**Comment by mprobson** [comment]
*Original date: 2017-11-29 20:54:09*

---
See above comments about 1393 solving this issue

**Comment by mprobson** [comment]
*Original date: 2018-09-27 17:22:21*

---
#1393 Merged
