### ISSUE TITLE
build interactive config should use netlrts or verbs instead of net and net-ibverbs

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#874]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/874*

---
I'm assuming you want to steer people to the lrts layers.  You could also ask if they want support for partitions/replicas.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-18 22:59:16*

---
~~https://charm.cs.illinois.edu/gerrit/917~~ https://github.com/UIUC-PPL/charm/commit/cd8350baeb1722999de0d2ff539c0e228e31fc61
