### ISSUE TITLE
Make checkpoint test create all sorts of entities and assert that their values are as expected

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#88]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/88*

---
Right now, `tests/charm++/chkpt` only even tries to save and restore a mainchare, an array, and some singleton chares. It should also cover readonly variables, groups, and nodegroups, and should have some values stored and recovered that can be checked analytically in each .

**Comment by ericjbohm** [comment]
*Original date: 2013-08-28 18:56:49*

---
Any progress on this?

**Comment by xiangni** [comment]
*Original date: 2013-08-28 19:06:25*

---
No, I will start looking at it.

**Comment by xiangni** [comment]
*Original date: 2013-08-28 20:29:51*

---
Added the checkpoint test in tests/charm++/chkpt for group, nodegroup and readonly variables. Data after restart is also verifies. Waiting for the nightly build to test it.
