### ISSUE TITLE
++scalable-start broken for verbs-smp

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#880]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/880*

---
jim`ariel$./charmrun ++verbose +p16 ++ppn 2 ++nodegroup emadib4 ++scalable-start ./namd2
Charmrun> scalable start enabled. 
Charmrun> charmrun started...
Charmrun> using /home/jim/.nodelist as nodesfile
Charmrun> adding client 0: "ariel", IP:130.126.120.127
Charmrun> adding client 1: "ariel", IP:130.126.120.127
Charmrun> adding client 2: "ariel", IP:130.126.120.127
Charmrun> adding client 3: "ariel", IP:130.126.120.127
Charmrun> adding client 4: "ariel", IP:130.126.120.127
Charmrun> adding client 5: "ariel", IP:130.126.120.127
Charmrun> adding client 6: "ariel", IP:130.126.120.127
Charmrun> adding client 7: "ariel", IP:130.126.120.127
Charmrun> adding client 8: "bastogne", IP:130.126.120.120
Charmrun> adding client 9: "bastogne", IP:130.126.120.120
Charmrun> adding client 10: "bastogne", IP:130.126.120.120
Charmrun> adding client 11: "bastogne", IP:130.126.120.120
Charmrun> adding client 12: "bastogne", IP:130.126.120.120
Charmrun> adding client 13: "bastogne", IP:130.126.120.120
Charmrun> adding client 14: "bastogne", IP:130.126.120.120
Charmrun> adding client 15: "bastogne", IP:130.126.120.120
Charmrun> Charmrun = 130.126.120.127, port = 57386
Charmrun> IBVERBS version of charmrun
start_nodes_rsh
Charmrun> Sending "0 130.126.120.127 57386 26309 0" to client 0.
Charmrun> find the node program "/Scr/jim/NAMD_binaries/NAMD-build-2015-Nov-07-10879/NAMD_2.11b1_Linux-x86_64-verbs-smp/./namd2" at "/Scr/jim/NAMD_binaries/NAMD-build-2015-Nov-07-10879/NAMD_2.11b1_Linux-x86_64-verbs-smp" for 0.
Charmrun> Starting ssh ariel -l jim -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o NoHostAuthenticationForLocalhost=yes /bin/bash -f
Charmrun> remote shell (ariel:0) started
Charmrun> Sending "4 130.126.120.127 57386 26309 0" to client 4.
Charmrun> find the node program "/Scr/jim/NAMD_binaries/NAMD-build-2015-Nov-07-10879/NAMD_2.11b1_Linux-x86_64-verbs-smp/./namd2" at "/Scr/jim/NAMD_binaries/NAMD-build-2015-Nov-07-10879/NAMD_2.11b1_Linux-x86_64-verbs-smp" for 8.
Charmrun> Starting ssh bastogne -l jim -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o NoHostAuthenticationForLocalhost=yes /bin/bash -f
Charmrun> remote shell (bastogne:8) started
Charmrun> node programs all started
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: No xauth data; using fake authentication data for X11 forwarding.
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: No xauth data; using fake authentication data for X11 forwarding.
Charmrun remote shell(ariel.0)> remote responding...
Charmrun remote shell(ariel.0)> starting node-program...
Charmrun remote shell(ariel.0)> remote shell phase successful.
Charmrun remote shell(bastogne.8)> remote responding...
Charmrun remote shell(bastogne.8)> starting node-program...
Charmrun remote shell(bastogne.8)> remote shell phase successful.
Charmrun> Waiting for 0-th client to connect.
Charmrun> Waiting for 1-th client to connect.
Charmrun> Waiting for 2-th client to connect.
...hangs...

verbs works fine, ibverbs-smp, netlrts-smp works fine, verbs-smp fails even without ++ppn

**Comment by jcphill** [comment]
*Original date: 2015-11-07 22:43:22*

---
In arch/verbs/machine.c:

#if ! CMK_SMP && ! defined(_WIN32)
/* parse forks only used in non-smp mode */
static void parse_forks(void) {
  char *forkstr;
  int nread;
  int forks;
  int i,pid;
  forkstr=getenv("CmiMyForks");
  if(forkstr!=0) { /* charmrun */
        nread = sscanf(forkstr,"%d",&forks);
        for(i=1;i<=forks;i++) { /* by default forks = 0 */
                pid=fork();
                if(pid<0) CmiAbort("Fork returned an error");
                if(pid==0) { /* forked process */
                        /* reset mynode,pe & exit loop */
                        Lrts_myNode+=i;
                        _Cmi_mype+=i;
                        break;
                }
        }
  }
}
#endif

**Comment by jcphill** [comment]
*Original date: 2015-11-07 22:45:53*

---
Fixed in arch/netlrts/machine.c

#if ! defined(_WIN32)
/* parse forks only used in non-smp mode */
static void parse_forks(void) {
  char *forkstr;
  int nread;
  int forks;
  int i,pid;
  forkstr=getenv("CmiMyForks");
  if(forkstr!=0) { /* charmrun */
        nread = sscanf(forkstr,"%d",&forks);
        for(i=1;i<=forks;i++) { /* by default forks = 0 */
                pid=fork();
                if(pid<0) CmiAbort("Fork returned an error");
                if(pid==0) { /* forked process */
                        /* reset mynode,pe & exit loop */
                        Lrts_myNode+=i;
#if ! CMK_SMP
                        _Cmi_mype+=i;
#endif
                        break;
                }
        }
  }
}
#endif

**Comment by jcphill** [comment]
*Original date: 2015-11-08 02:43:07*

---
Fix checked in.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-08 17:35:01*

---
Fix was here: ~~https://charm.cs.illinois.edu/gerrit/901~~ https://github.com/UIUC-PPL/charm/commit/63ec01b2d48db9811779d2438ef2627e9bea58d5

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 03:05:30*

---
Set status back to Merged so that we can distinguish whether the code was changed in some way, or the fix was elsewhere. Both are non-open states from Redmine's perspective.
