### ISSUE TITLE
Change type to indicate non-participation in reductions

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#882]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/882*

---
Currently, Charm++ allows some members of a reduction to pass in CkReduction::random to ignore their contributions.  However, CkReduction::random is a valid type for reductions.  Create a new type explicitly for this purpose (something like CkReduction::ignore) and clean up the code that currently special cases CkReduction::random.

**Comment by juanjgalvez** [comment]
*Original date: 2016-03-02 21:13:43*

---
In the runtime, the only places where a contribution with CkReduction::random is used is in ckarray.C and ckreduction.h. As far as I can tell, the use in these places is the intended use of random.

**Comment by juanjgalvez** [comment]
*Original date: 2016-08-16 15:55:51*

---
Patch here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1800/~~ https://github.com/UIUC-PPL/charm/commit/3cb576a426f96dff91d221f7ed8b6d2ce57a8e5b
