### ISSUE TITLE
symbolic links in build tmp directories use absolute pathnames

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#888]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/888*

---
jim`lisboa>ls -l /Projects/namd2/charm-6.6.1/multicore-linux64-iccstatic/tmp/charmc
lrwxrwxrwx  1 jim tbres 24 Mar 15  2015 /Projects/namd2/charm-6.6.1/multicore-linux64-iccstatic/tmp/charmc -> ../../src/scripts/charmc*
jim`lisboa>ls -l /Projects/namd2/charm-6.7.0/multicore-linux64-iccstatic/tmp/charmc
lrwxrwxrwx  1 jim tbres 102 Nov  8 11:31 /Projects/namd2/charm-6.7.0/multicore-linux64-iccstatic/tmp/charmc -> /Projects/namd2/Programmers/jim/charm-6.7.0-build-2015-Nov-08-17541/charm-6.7.0-pre/src/scripts/charmc*

This is a regression of the following:

commit 8e507808a3e124f08b560122327fb70931fce35a
Author: Orion Lawlor <olawlor`acm.org>
Date:   Fri Sep 8 22:03:36 2000 +0000

    Made soft links use relative pathnames instead of absolute.
    This lets you move a charm++ installation without having
    to recompile anything.
    
    It also stops the confusing oddness that happens when you
    move, e.g., charm to old_charm, and install a new charm.
    Then the old_charm (absolute) soft links point into the
    new charm directory!

**Comment by nikhil-jain** [comment]
*Original date: 2015-11-11 16:21:08*

---
This change was most likely a side effect of enabling out of tree build, hence assigning to Phil.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-23 19:22:02*

---
The change that caused this breakage was to allow out-of-tree builds, such as having the source tree on a shared FS and the build on a faster FS.

Unless this poses critical problems with practical deployment, we're not going to take the deeper changes necessary to maintain out-of-tree builds and also un-break this (copying all headers into `include/` and scripts into `bin/` instead of symlinking them through `tmp/`), because of the expectation that larger things will break when we do that.

**Comment by jcphill** [comment]
*Original date: 2015-11-24 03:23:39*

---
The symlinks utility provides a way to turn absolute links into symbolic links, so this is fixable after the build.
We absolutely don't want to copy headers and scripts.  In-tree builds don't need to be able to move out of the tree.  The only change is to use relative links in tmp for in-tree builds, which should be possible.

**Comment by jcphill** [comment]
*Original date: 2015-11-30 21:59:27*

---
Commits 921/922 fix this.

**Comment by jcphill** [comment]
*Original date: 2015-12-03 17:51:58*

---
Can someone take a look at the unified fix in ~~https://charm.cs.illinois.edu/gerrit/#/c/921/~~ https://github.com/UIUC-PPL/charm/commit/6f8f9d422dff83a4e71639be4c982037877b6741 please?
