### ISSUE TITLE
simd.h include of altivec.h defines vector and bool

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#889]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/889*

---
This generates all kinds of interesting errors on Power.
Getting ready to submit a patch.

**Comment by PhilMiller** [comment]
*Original date: 2015-11-11 16:42:41*

---
~~https://charm.cs.illinois.edu/gerrit/908~~ https://github.com/UIUC-PPL/charm/commit/c660ce3e8337549b7ce83d2f747e3476763a9225
Jim's patch
