### ISSUE TITLE
BigSim loadlog test assumes that compute-node binaries can run on the host

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#89]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/89*

---
The program `examples/bigsim/tools/loadlog` is compiled with `charmc -seq`, which targets sequential code for the machine architecture that the parallel runtime targets. The test in the Makefile, however, tries to run the resulting binary on whatever host or head node the scripts are running on, rather than on a compute node. On machines where the head nodes can't run the compute node's binaries, this will fail.

Nikhil and I tried switching the compilation to the native compiler with `charmc -host`, but this fails because the binary still tries to link against runtime libraries compiled for the target system. Making the loadlog tool actually run on the host would require compiling host versions of all of its dependencies.

The alternative seems to be to run loadlog on a compute node, like the rest of the tests, with `./charmrun ./loadlog`. Unfortunately, it's sequential rather than a Charm++ or Converse binary, so it won't connect back to charmrun on net builds like it's expected to, and so will fail there.

As a short-term expedient, we could disable this test for autobuild so that we can at least be sure that everything else is passing.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-12 18:35:52*

---
Disabled the `examples/bigsim/tools` tests just on the stable branch so that we can recheck that everything else passes and tag the release.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-14 22:47:56*

---
Disabled on mainline, too, so that other tests can run in autobuild.

**Comment by PhilMiller** [comment]
*Original date: 2013-08-28 18:44:59*

---
Reassignment pending availability of corresponding funding.

**Comment by matthiasdiener** [comment]
Bigsim has been removed in #2703.
