### ISSUE TITLE
charmrun: Host name returned by skt_to_name may not coincide with the actual host of the PE using that socket

### ISSUE THREAD

**Issue by juanjgalvez** [UIUC-PPL/charm#890]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/890*

---
In some cases the host name returned by skt_to_name is not the real host name of the process using that socket.
This can be reproduced adding this piece of code in charmrun.C (main) right after "Charmrun> started all node programs in %.3f seconds"

```
#ifndef HSTART
  for (int i = 0; i < req_nClients; i++) {
    SOCKET fd = req_clients[i];

    const char *name = skt_to_name(fd);
    fprintf(stdout, "Socket %d: hostname associated with this socket (according to skt_to_name) is %s\n", fd, name);

    for (int j = 0; j < nodetab_max; j++) {
      if (nodetab_ctrlfd(j) == fd) {
        if (strcmp(nodetab_name(j), name) != 0) {
          fprintf(stderr, "ERROR: skt_client_table and nodetable socket mismatch!\n");
          fprintf(stderr, "(PE %d in %s) uses socket %d\n", j, nodetab_name(j), fd);
          exit(1);
        }
        break;
      }
    }
  }
#endif
```

Sample output when running (on three hosts):
./charmrun ./jacobi3d 256 128 +p9 ++verbose

Charmrun> started all node programs in 1.885 seconds.
Socket 4: hostname associated with this socket (according to skt_to_name) is humility.cs.illinois.edu
Socket 5: hostname associated with this socket (according to skt_to_name) is humility.cs.illinois.edu
Socket 6: hostname associated with this socket (according to skt_to_name) is humility.cs.illinois.edu
Socket 7: hostname associated with this socket (according to skt_to_name) is charity.cs.illinois.edu
ERROR: skt_client_table and nodetable socket mismatch!
(PE 6 in courtesy.cs.illinois.edu) uses socket 7

**Comment by jcphill** [comment]
*Original date: 2015-11-12 14:22:38*

---
Under what circumstances does this actually cause a launch failure?

**Comment by juanjgalvez** [comment]
*Original date: 2015-11-12 14:27:47*

---
This doesn't cause a failure. As far as I know it can only cause wrong output so, for example, if some host is failing for whatever reason, the user might see a different host printed than the one that's actually failing.

**Comment by juanjgalvez** [comment]
*Original date: 2015-12-02 22:13:46*

---
Fix here ~~https://charm.cs.illinois.edu/gerrit/#/c/926/~~ https://github.com/UIUC-PPL/charm/commit/bd7f60db095990a364e8165c751240a29f559ab4
