### ISSUE TITLE
ChaNGa out of tree build broken

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#892]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/892*

---
Simon tried to build using the following command on Blue Waters on the nodeGPU branch of charm and kept getting an error:

```
./build ChaNGa gemini_gni-crayxe hugepages smp cuda –with-production –enable-tracing –j8
```

I suspect that the problem is related to the build target (ChaNGa) and not the branch (nodeGPU) but I haven't confirmed it yet. I'll post the error here when Simon emails it to me.

**Comment by mprobson** [comment]
*Original date: 2015-11-12 22:19:07*

---
I should note that if you get a <code>hybridAPI.h missing</code> error, just re-run the command. This is a known bug (see #788) that I'm working on fixing in other layers.

**Comment by nikhil-jain** [comment]
*Original date: 2015-11-12 22:33:37*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/912/~~ https://github.com/UIUC-PPL/charm/commit/802b882aa3d14748aaaa32866a09b8927b7e8b88
