### ISSUE TITLE
MPI_Comm_create hangs for disjoint groups

### ISSUE THREAD

**Issue by xiangni** [UIUC-PPL/charm#894]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/894*

---
When different groups are passed by different subsets of processors, the call hangs. Example code can be found in MPI1/DGEMM from https://github.com/ParRes/Kernels.

**Comment by stwhite91** [comment]
*Original date: 2015-11-21 20:47:20*

---
In MPI-1.1, it was an error for users to call MPI_Comm_create with multiple groups. In MPI-2.2, MPI_Comm_create was changed to allow users to pass multiple disjoint groups with an intra-communicator, to simplify user code. AMPI currently hangs for the case with multiple disjoint groups.

**Comment by stwhite91** [comment]
*Original date: 2015-11-25 19:06:35*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/919/~~ https://github.com/UIUC-PPL/charm/commit/6afa9951a48ec6e4cc9527f05f1fe4556c043a7f
