### ISSUE TITLE
multicore eats and ignores +ppn/++ppn

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#900]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/900*

---
In 6.6.1 and earlier Charm++ the multicore version would treat "+ppn" and "++ppn" the same as "+p" (set the number of worker threads to use).  The current 6.7.0-rc1 version eats "+ppn" or "++ppn" and the following argument but does not set the number of worker threads.

**Comment by ericjbohm** [comment]
*Original date: 2015-12-08 19:15:24*

---
Implemented in ~~https://charm.cs.illinois.edu/gerrit/948~~ https://github.com/UIUC-PPL/charm/commit/b092d698fb342315e266eca19572dfaed694f8e9

netlrts parses +ppn in machine-common-init, so the parsing logic for netlrts/machine.c had no ++ppn to consume, and therefore did nothing.

Replaced pointless arg parse code with error checking to test that +p and ++ppn are consistent, then use that value (or the value of whichever one is set) for npes to trigger the launching logic.
