### ISSUE TITLE
Threads awoken by CthAwaken don't let Projections trace back to the event that woke them

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#901]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/901*

---
When working with code using threads (threaded entry methods, probably AMPI as well), Projections traces are somewhat annoying to work with in the timeline, because clicking on the bar representing the thread's execution produces the warning that "Message was sent from outside the current time range" which is very misleading. `CthAwaken()` should record the event that led to that thread being placed in the queue as runnable, so that awakenings can be traced back.

On close examination, there is a trace from the message event to the `dummy_thread_chare::dummy_thread_ep` event, but then none from that to the actual work that runs in the thread which gets recorded as a separate event.

This of course breaks critical path following as well.

[0001-Bug-901-Added-tracing-for-thread-context-switch-even.patch](https://github.com/UIUC-PPL/charm/files/3536577/0001-Bug-901-Added-tracing-for-thread-context-switch-even.patch)
[Makefile](https://github.com/UIUC-PPL/charm/files/3536578/Makefile.txt)
[threadTest.C](https://github.com/UIUC-PPL/charm/files/3536579/threadTest.C.txt)
[threadTest.ci](https://github.com/UIUC-PPL/charm/files/3536580/threadTest.ci.txt)

**Comment by PhilMiller** [comment]
*Original date: 2016-01-08 20:13:32*

---
Patch implemented in collaboration with Charmworks prospective hire Steve Hoelle. Attached, will post to Gerrit shortly.

Cleans up tracing around thread creation/switching events substantially, gets me the tracing I need.

**Comment by PhilMiller** [comment]
*Original date: 2016-01-08 21:05:43*

---
Test case that we wrote and used to debug these various changes. To be meaningful to integrate in the automatic test suite, would need to add some introspection into what the traces are recording (i.e. whether each resumed thread depends on the event that awoke it).

**Comment by PhilMiller** [comment]
*Original date: 2016-01-08 21:36:02*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/989/~~ https://github.com/UIUC-PPL/charm/commit/3fc7d6680f775af70558a08185fd1fd6a1e34337

**Comment by stwhite91** [comment]
*Original date: 2016-04-01 18:55:05*

---
The patch needs manual verification for BigSim

**Comment by jcphill** [comment]
*Original date: 2017-02-17 05:59:31*

---
This does not appear to work for threads as used in NAMD where threads are awoken from regular entries rather than other threads.

**Comment by jcphill** [comment]
*Original date: 2017-02-17 06:21:51*

---
Also, threads are created by CthCreate(), not as [threaded] entries.

**Comment by PhilMiller** [comment]
*Original date: 2017-02-17 18:35:09*

---
Jim: Could you try things out with the above change reverted? Looking at the code again, I realize I may have actually broken the cases you mention while fixing the case I was concerned with.

**Comment by jcphill** [comment]
*Original date: 2017-02-17 21:05:54*

---
With change 989 reverted I now see correct tracing for Cthreads.

**Comment by PhilMiller** [comment]
*Original date: 2017-04-20 15:28:02*

---
This isn't a regression relative to 6.7, and I'm not immediately able to get back to this. Deferring for now.

**Comment by stwhite91** [comment]
*Original date: 2017-04-25 03:57:00*

---
With issue #901 resolved now, this issue has become a more visible sore of AMPI Projections usage. Note that AMPI threads are created by TCharm with a call to CthCreate(). AMPI does have a few [threaded] entry methods too, but those only used for split-phase communicator creation.

**Comment by sbak5** [comment]
*Original date: 2017-10-25 04:25:26*

---
This issue is similar to the following CkLoop tracing issue and I fixed in my local branch for ULT OpenMP to be shown on Projections correctly. 
https://charm.cs.illinois.edu/redmine/issues/1437

I'll push this patch when available.

**Comment by stwhite91** [comment]
*Original date: 2017-10-30 16:54:42*

---
https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=15f34d71f4c7704dde34db3efec1c9689604e4cb

**Comment by stwhite91** [comment]
*Original date: 2017-11-29 18:28:49*

---
Seonmyeong, can you push this patch to gerrit?

**Comment by PhilMiller** [comment]
*Original date: 2017-12-06 17:30:20*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3359/~~ https://github.com/UIUC-PPL/charm/commit/5c4f5d6b29737c850da00d16707e426ff43fe9d3
