### ISSUE TITLE
Add Support for Execution on a Specific PE to CkLoop

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#904]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/904*

---
The colvars library (https://github.com/colvars/colvars/), used in NAMD, has a computational bottleneck we are planning on addressing with CkLoop.  However, some of the work needs to be executed on the calling PE (to take advantage of shared state and to allow the Tcl interpreter's stack checker to work correctly).

There are many ways to do this, but the best design we've come up with so far is adding a second function argument to CkLoop which is executed on the calling PE and can run in parallel with the other work in CkLoop.

**Comment by harshithamenon** [comment]
*Original date: 2015-12-08 21:15:53*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/947/~~ https://github.com/UIUC-PPL/charm/commit/294d0d8de422077099e72153d28856d944403f39
