### ISSUE TITLE
  MANY "Warning: IndexPool_getslot 0x407c3f00 overflow when expanding to: 524288"

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#909]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/909*

---
I get 10s of Gigabytes of the above message when running on BlueWaters with 8k nodes for a few hours.  This is a) not informative to the user, b) a LOT of extra data in my diagnostic files.  Version information:

Charm++> Running on Gemini (GNI) with 8192 processes
Charm++> static SMSG
Charm++> SMSG memory: 24064.0KB
Charm++> memory pool init block size: 8MB, total memory pool limit 0MB (0 means no limit)
Charm++> memory pool registered memory limit: 200000MB, send limit: 100000MB
Charm++> only comm thread send/recv messages
Charm++> Cray TLB page size: 2048K
Charm++> Running in SMP mode: numNodes 8192,  31 worker threads per process
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.6.0-340-g6532307
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map : 1-31
Charm++> set comm 0 on node 0 to core #0
Charm++> Running on 8192 unique compute nodes (32-way SMP).

**Comment by PhilMiller** [comment]
*Original date: 2015-12-04 19:59:32*

---
Something that's dumping 10s of GB of output on users should get fixed with some haste.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-15 19:32:01*

---
Original fix attempt: ~~https://charm.cs.illinois.edu/gerrit/941~~ https://github.com/UIUC-PPL/charm/commit/64bdb62b581a6e127234289005ee89dda0d74f1d
Reversion: ~~https://charm.cs.illinois.edu/gerrit/949~~ https://github.com/UIUC-PPL/charm/commit/7dda481a0c14a5dddebd5a2afba7d181d4e8ad92
Later fix: ~~https://charm.cs.illinois.edu/gerrit/951~~ https://github.com/UIUC-PPL/charm/commit/31590360f0889aee32f62aa46615b278c82bb7f4
