### ISSUE TITLE
Architecture target for Cray XC

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#91]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/91*

---
Merge the architecture files for Cray XC based on Cray XE support.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-14 06:16:17*

---
Merged the cray-xc branch to master. symlinking needs to be done to avoid carrying a copy of machine files for gemini_gni-crayxe and gni-crayxc.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-14 06:19:02*

---
As discussed, we'll move `gemini_gni-crayxe` to the new saner name `gni-crayxe`, and put in a `gemini_gni-crayxe/vdir_link` pointing to `gni-crayxe`

**Comment by PhilMiller** [comment]
*Original date: 2013-03-30 16:58:01*

---
Support on the stable branch is tracked in #140 now.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-30 21:08:39*

---
gemini_gni simlinked to gni-crayxe.
