### ISSUE TITLE
AMPI_Testall does not set flag to true if request count is 0

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#910]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/910*

---
The MPI standard specifies that MPI_Testall(count, array_of_requests, flag, array_of_statuses) should set 'flag' to true, update the 'array_of_statuses', and return MPI_SUCCESS if all 'count' requests in 'array_of_requests' have completed. Currently, AMPI returns MPI_SUCCESS without setting 'flag' to true in the case that count is 0.

This bug breaks all of the examples in Hypre. With it fixed, Hypre builds and its example programs that are thread-safe run to completion on AMPI with virtualization, migration, etc!

**Comment by stwhite91** [comment]
*Original date: 2015-12-03 20:06:43*

---
We should also consider adding Hypre-2.10.1 to AMPI's distribution, like ROMIO (though more thorough testing would be needed). No changes to Hypre's source or build system were required to get it working. Also, we would want to make all of the example Hypre programs thread safe if we include them so that they can all be run with virtualization.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-03 21:11:52*

---
Will retarget to 6.7.0 if the patch gets cleaned up and merged before other stuff is resolved.

**Comment by stwhite91** [comment]
*Original date: 2015-12-03 21:33:48*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/931/~~ https://github.com/UIUC-PPL/charm/commit/d959b5a9d4f351f01e3faccc16ebb3f5a0b4a000
