### ISSUE TITLE
trivial build portability

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#916]
*Original author: Patrick Welche*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/916*

---
test(1) uses '=' not '==' for string comparison. '==' is a bash extension.

[0001-test-1-uses-for-string-comparison.patch](https://github.com/UIUC-PPL/charm/files/3536581/0001-test-1-uses-for-string-comparison.patch.txt)

**Comment by PhilMiller** [comment]
*Original date: 2015-12-08 20:17:41*

---
Thank you for the patch. We'll get that merged shortly.

**Comment by PhilMiller** [comment]
*Original date: 2015-12-08 21:45:05*

---
~~https://charm.cs.illinois.edu/gerrit/950~~ https://github.com/UIUC-PPL/charm/commit/74ba8d1ae5d4c9eed2e1f9507aa0bad52b4209a1
