### ISSUE TITLE
auto-test should handle multiple ppn

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#917]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/917*

---
Currently, if ppn > 1 is given as TESTOPTS, auto-test will fail since +p<> may not divide them. Should be handle more graciously.

**Comment by bilgeacun** [comment]
*Original date: 2016-03-13 15:47:38*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1111~~ https://github.com/UIUC-PPL/charm/commit/93c9f262faabdcc737ca342bfed7151fca884ee0

**Comment by PhilMiller** [comment]
*Original date: 2016-04-11 19:36:07*

---
Windows builds are still failing autobuild due to an inability to find the testrun script where they expect it.

**Comment by PhilMiller** [comment]
*Original date: 2016-04-11 19:36:52*

---
Sorry, I see that was opened as #1028
