### ISSUE TITLE
Compilation failing in net-cygwin

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#923]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/923*

---
Look at the error here: http://charm.cs.illinois.edu/autobuild/cur/net-cygwin.txt

**Comment by stwhite91** [comment]
*Original date: 2016-04-13 22:33:29*

---
This error was present in the 6.7.0 release and we're not sure how to fix it.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 19:12:52*

---
This was the _ftime/ftime issue. Fixed with a patch contributed by Ed Karrells, from Sanjay's CS598 course.
