### ISSUE TITLE
ibverbs broken by undef QLOGIC

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#927]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/927*

---
This is the only possibly relevant change that I can see:

diff -r charm-6.7.0-build-2015-Dec-11-194922/charm-6.7.0-rc2/src/scripts/conv-autoconfig.h.in charm-6.7.0-build-2015-Dec-16-167340/charm-6.7.0/src/scripts/conv-autoconfig.h.in
376a377,379
> 
> /* enable qlogic */
> #undef QLOGIC

https://charm.cs.illinois.edu/gerrit/gitweb?p=charm.git;a=commitdiff;h=23309543f865ac16970ff07db03676ecdf79eafc

**Comment by jcphill** [comment]
*Original date: 2015-12-17 16:05:49*

---
OK, here is the effect of the change.

Dec 11 (works):
jim`sunnyvale$grep -r QLOGIC net-linux-x86_64-ibverbs-iccstatic/
net-linux-x86_64-ibverbs-iccstatic/tmp/configure:#define QLOGIC 0
net-linux-x86_64-ibverbs-iccstatic/tmp/configure:#define QLOGIC 1
net-linux-x86_64-ibverbs-iccstatic/tmp/configure.in:  AC_DEFINE_UNQUOTED(QLOGIC, 0, [disable qlogic])
net-linux-x86_64-ibverbs-iccstatic/tmp/configure.in:  AC_DEFINE_UNQUOTED(QLOGIC, 1, [enable qlogic])
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c://#define QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifndef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:// Here NON_SRQ is for QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifndef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifdef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/config.log:#define QLOGIC 0
net-linux-x86_64-ibverbs-iccstatic/tmp/config.status:D["QLOGIC"]=" 0"

Dec 16 (fails):
jim`sunnyvale$grep -r QLOGIC net-linux-x86_64-ibverbs-iccstatic/
net-linux-x86_64-ibverbs-iccstatic/tmp/config.log:#define QLOGIC 0
net-linux-x86_64-ibverbs-iccstatic/tmp/conv-autoconfig.h:#define QLOGIC 0
net-linux-x86_64-ibverbs-iccstatic/tmp/configure.in:  AC_DEFINE_UNQUOTED(QLOGIC, 0, [disable qlogic])
net-linux-x86_64-ibverbs-iccstatic/tmp/configure.in:  AC_DEFINE_UNQUOTED(QLOGIC, 1, [enable qlogic])
net-linux-x86_64-ibverbs-iccstatic/tmp/configure:#define QLOGIC 0
net-linux-x86_64-ibverbs-iccstatic/tmp/configure:#define QLOGIC 1
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c://#define QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifndef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:// Here NON_SRQ is for QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifndef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/machine-ibverbs.c:#ifdef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/tmp/config.status:D["QLOGIC"]=" 0"
net-linux-x86_64-ibverbs-iccstatic/tmp/conv-autoconfig.h.in:#undef QLOGIC
net-linux-x86_64-ibverbs-iccstatic/include/conv-autoconfig.h:#define QLOGIC 0

Note that the macro usage is all ifdef/ifndef rather than if, defining QLOGIC 0 enables it.

**Comment by jcphill** [comment]
*Original date: 2015-12-17 16:32:51*

---
Building a fix now...

**Comment by jcphill** [comment]
*Original date: 2015-12-17 16:57:26*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/958/~~ https://github.com/UIUC-PPL/charm/commit/cecee1bf0fa290f706c5df508a9ff3a31efa7f87

**Comment by jcphill** [comment]
*Original date: 2015-12-17 17:43:40*

---
For resulting errors see Bug #926 "hangs on verbs error", but in short:

Info: Startup phase 0 took 0.00197887 s, 237.66 MB of memory in use
[0] wc[0] status 12 wc[i].opcode 0
[14] wc[0] status 12 wc[i].opcode 0
[1] wc[0] status 12 wc[i].opcode 0

**Comment by nikhil-jain** [comment]
*Original date: 2015-12-18 20:06:36*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/958/~~ https://github.com/UIUC-PPL/charm/commit/cecee1bf0fa290f706c5df508a9ff3a31efa7f87
