### ISSUE TITLE
ibverbs immediatering test much slower than verbs

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#928]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/928*

---
net-linux-x86_64-ibverbs-iccstaticon 64 cores of Stampede:
test 3: initiated [immediatering (gengbin)]
test 3: completed (33.43 sec)
test 31: initiated [multi immediatering (gengbin)]
test 31: completed (32.37 sec)

verbs-linux-x86_64-iccstatic on 64 cores of Stampede:
test 3: initiated [immediatering (gengbin)]
test 3: completed (0.16 sec)
test 31: initiated [multi immediatering (gengbin)]
test 31: completed (0.18 sec)

At least verbs is OK, but clearly some kind of resource contention blocking progress on ibverbs.

**Comment by PhilMiller** [comment]
*Original date: 2016-01-01 17:15:25*

---
Is this necessarily something we should plan to fix? Is there currently a good reason to run with net-ibverbs instead of verbs? We are trying to deprecate the non-LRTS implementations, but haven't set a firm target for when.

**Comment by ericjbohm** [comment]
*Original date: 2016-01-12 17:26:29*

---
With verbs already highlighted as the go to target, effort spent optimizing net..ibverbs would need a real use case justification.

**Comment by rbuch** [comment]
*Original date: 2016-03-08 20:20:36*

---
I'm closing this since net-ibverbs is essentially deprecated.
