### ISSUE TITLE
[local] entry methods don't set tracing event dependencies

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#937]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/937*

---
When calling a `[local]` method of a group or array element, we get a distinct trace event for the time spent in the called object. However, that event's dependency field is left unset, meaning that traceback will lose its trail at these events.

At present, look in `src/xlat-i/xi-Entry.C` methods `genGroupDefs` and `genArrayDefs`. Per #921, I may be moving this code into virtual methods on `ArrayElement` and `Group.

**Comment by PhilMiller** [comment]
*Original date: 2016-05-19 19:37:05*

---
Necessary change is in xi-Entry.C in Entry::genArrayDefs and analogs for chare/group/nodegroup entry methods. 

At least in the array case, one fix will address both `[inline`] and `[local]` methods, because the code is factored out to be common (from my changes for #921). All I don't know in terms of how to fix this is the right way to get the right event ID to pass in.

**Comment by PhilMiller** [comment]
*Original date: 2017-12-04 22:26:54*

---
Seonmyeong, you may be in a good position to address this quickly. If so, please re-assign it to yourself.

**Comment by sbak5** [comment]
*Original date: 2018-02-13 23:00:31*

---
Similar to the CthThread and CkLoop tracing issue. (eventID is set 0 )

For local methods (or inline), we may set a Cpv vaariable for these local invocation. The variable contain PE local event ID which can be used by local method invocations.

**Comment by sbak5** [comment]
*Original date: 2018-02-14 23:23:17*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/3723/~~ https://github.com/UIUC-PPL/charm/commit/8a7c99369b1f37dccd9dbd2328370db5d4ae24e0

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 06:00:45*

---
Does this also fix bug #459?

**Comment by stwhite91** [comment]
*Original date: 2018-04-06 00:16:02*

---
Bump

**Comment by stwhite91** [comment]
*Original date: 2018-05-01 21:45:50*

---
This is one of two remaining bugs targeted at v6.9.0

**Comment by rbuch** [comment]
*Original date: 2018-07-11 00:35:56*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3723/~~ https://github.com/UIUC-PPL/charm/commit/8a7c99369b1f37dccd9dbd2328370db5d4ae24e0 (same link as before, it has just been updated to work for recursive calls and to make the sender accurate).

**Comment by stwhite91** [comment]
*Original date: 2018-07-27 01:56:36*

---
Note that the '+tracenested' runtime option is needed to generate correct traces.
