### ISSUE TITLE
6.5.0 on ANL BGQ systems (Vesta, Cetus/Mira)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#94]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/94*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:21*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-02 22:02:14*

---
Builds to be found in `~phil/charm-6.5`

**Comment by PhilMiller** [comment]
*Original date: 2013-04-03 19:27:14*

---
#104 prevents us building the 5 `xlc * (smp, async-smp) * debug` targets, but the the remaining 43/48 targets are built. I've confirmed that each of them can successfully link a complete binary, viz. megatest.

For reference, the set of builds occupies 6.6G in my home directory. The megatest binaries added another 1.6G while I had them sitting there.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-04 14:52:43*

---
Test update

**Comment by PhilMiller** [comment]
*Original date: 2013-04-04 14:53:17*

---
Test update again

**Comment by PhilMiller** [comment]
*Original date: 2013-04-04 15:07:10*

---
test update 3

**Comment by nikhil-jain** [comment]
*Original date: 2013-04-10 18:46:16*

---
Confirmed access to these locations.
