### ISSUE TITLE
Metabalancer initialization is not thread safe

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#941]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/941*

---
Metabalancer.C:_metabalancerInit() calls __registerCommandLineOpt() which modifies a global object "_optSet".  Since this is called by all PEs on a node, this has a huge potential for race problems.

I'm marking this as "Urgent" because it is a nasty, hard to track down bug that has crept in since the previous release, and probably should be fixed in the current (6.7.0) release.

Following the general load balancer initialization, I propose the following change:

```
<code>
diff --git a/src/ck-ldb/MetaBalancer.C b/src/ck-ldb/MetaBalancer.C
index 3afbccb..f47ae46 100644
--- a/src/ck-ldb/MetaBalancer.C
+++ b/src/ck-ldb/MetaBalancer.C
`` -93,7 +93,6 `` MetaLBInit::MetaLBInit(CkArgMsg *m) {
 
 // called from init.C
 void _metabalancerInit() {
-  _registerCommandLineOpt("+MetaLBNoObjTimer");
   CkpvInitialize(int, metalbInited);
   CkpvAccess(metalbInited) = 0;
   char **argv = CkGetArgv();
`` -102,6 +101,7 `` void _metabalancerInit() {
 }
 
 void MetaBalancer::initnodeFn() {
+  _registerCommandLineOpt("+MetaLBNoObjTimer");
 }
 
 // called by my constructor
</code>

```

**Comment by nikhil-jain** [comment]
*Original date: 2016-01-11 22:32:32*

---
I think this issue was resolved by this commit: 96889b970256f21f727ee2fb91a7a805197bca44

__registerCommandLineOpt only adds to optSet on PE 0.

**Comment by trquinn** [comment]
*Original date: 2016-01-11 23:48:47*

---
This commit didn't make it into the "Single instance of GPU Manager" changeset, which is why it bit me.  I guess this can be closed.

**Comment by harshithamenon** [comment]
*Original date: 2016-01-12 17:30:28*

---
As Nikhil mentioned, the commit 96889b970256f21f727ee2fb91a7a805197bca44 should have fixed it. The smp aware GPU manager patch did not have this fix.
