### ISSUE TITLE
Rename AMPI extensions to keep MPI namespace sanctity

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#943]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/943*

---

```

http://charm.cs.illinois.edu/manuals/html/ampi/manual.html lists a number of extensions to MPI that are implemented in AMPI.

MPI_Migrate        MPI_Checkpoint     MPI_MemCheckpoint  MPI_Register
MPI_MigrateTo      MPI_Register_main  MPI_Setmigratable  MPI_Get_userdata
MPI_Start_measure  MPI_Stop_measure   MPI_Just_migrated  MPI_About_to_migrate
MPI_My_pe          MPI_My_node        MPI_Num_pes        MPI_Num_nodes
MPI_Set_load       MPI_Command_argument_count            MPI_Get_command_argument

From MPI 3.1 2.6.3:

"All MPI names have an MPI_ prefix, defined constants are in all capital letters, and defined types and functions have one capital letter after the prefix. Programs must not declare names (identifiers), e.g., for variables, functions, constants, types, or macros, beginning with any prefix of the form MPI_, where any of the letters are either upper or lower case. To support the profiling interface, programs must not declare functions with names beginning with any prefix of the form PMPI_, where any of the letters are either upper or lower case."

This text is slightly stronger in MPI-3 than in older versions, but the intent has always been the same.

Normally, this point is academic.  However, the MPI Forum has debated adding two functions with the same names as AMPI extensions (https://github.com/jeffhammond/miscellaneous-mpi-issues/issues/2 - note that this location is temporary and may falsely suggest it is a pet project of mine; migrating from Trac - e.g. https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/351 - has been a lot of work for some of us).  While the syntax and semantics may end up being the same, since they should match Fortran 2008, if they are not, it's going to be a major headache for users.  While this ticket may not ever pass, it demonstrates the real possibility of problems caused by using the MPI_ namespace.

Currently, MPICH uses MPIX_ for extensions, while Open-MPI uses OMPI_.  I would encourage the AMPI_ namespace to avoid conflicts with those, although the MPI standard is silent on this topic.

This is low priority and I'll submit a patch at some point if it is below the ZBB line for you all, assuming you are amenable to making the change.

```

**Comment by stwhite91** [comment]
*Original date: 2016-01-14 17:17:14*

---
MPI-2.2 formalized MPI naming conventions, which we should generally try to follow:
http://www.mpi-forum.org/docs/mpi-2.0/mpi-20-html/node6.htm

Proposed name changes for AMPI extensions (current on left, proposed on right):
```
MPI_Migrate                   AMPI_Migrate  (info key: "ampi_load_balance", values: "false", "sync", "async")
MPI_Checkpoint                AMPI_Migrate  (info key: "ampi_checkpoint", values: "false", "to_file=dir_name")
MPI_MemCheckpoint             AMPI_Migrate  (info key: "ampi_checkpoint", value: "in_memory")
MPI_Start_measure             AMPI_Load_start_measure
MPI_Stop_measure              AMPI_Load_stop_measure
MPI_Set_load                  AMPI_Load_set_value
MPI_MigrateTo                 AMPI_Migrate_to_pe
MPI_SetMigratable             AMPI_Comm_set_migratable
MPI_Get_userdata              AMPI_Get_pup_data
MPI_Datatype_iscontig         AMPI_Type_is_contiguous
MPI_Register                  AMPI_Register_pup
MPI_Register_main             AMPI_Register_main
MPI_Just_migrated             AMPI_Register_just_migrated
MPI_About_to_migrate          AMPI_Register_about_to_migrate
MPI_My_pe                     (attr key: AMPI_MY_PE)
MPI_My_node                   (attr key: AMPI_MY_NODE)
MPI_Num_pes                   (attr key: AMPI_NUM_PES)
MPI_Num_nodes                 (attr key: AMPI_NUM_NODES)
MPI_Print                     AMPI_Print
MPI_Yield                     AMPI_Yield
MPI_Suspend                   AMPI_Suspend
MPI_Resume                    AMPI_Resume
MPI_IGet                      AMPI_Iget
MPI_IGet_Wait                 AMPI_Iget_wait
MPI_IGet_free                 AMPI_Iget_free
MPI_IGet_data                 AMPI_Iget_data
MPI_Alltoall2                 AMPI_Alltoall_iget
MPI_Alltoall_medium           AMPI_Alltoll_medium
MPI_Alltoall_long             AMPI_Alltoall_long
MPI_Set_startevent            AMPI_Set_start_event
MPI_Set_endevent              AMPI_Set_end_event
N/A                           AMPI_Trace_begin
N/A                           AMPI_Trace_end
_TRACE_REGISTER_FUNCTION_NAME AMPI_Trace_register_function_name
_TRACE_REGISTER_FUNCTION_ID   AMPI_Trace_register_function_id
_TRACE_START_FUNCTION_NAME    AMPI_Trace_begin_function_name
_TRACE_START_FUNCTION_ID      AMPI_Trace_begin_function_id
_TRACE_END_FUNCTION_NAME      AMPI_Trace_end_function_name
_TRACE_END_FUNCTION_ID        AMPI_Trace_end_function_id
MPI_GPU_Invoke                AMPI_GPU_Invoke
MPI_GPU_Iinvoke               AMPI_GPU_Iinvoke
MPI_Command_argument_count    AMPI_Command_argument_count  (Fortran only)
MPI_Get_command_argument      AMPI_Get_command_argument    (Fortran only)
```

To get the PE number of an AMPI rank do:
```
MPI_Comm_get_attr(MPI_COMM_WORLD, AMPI_MY_PE, &my_pe, &flag);
```

To use AMPI_Migrate() in an AMPI application do:
```
MPI_Info hints;
MPI_Info_create(&hints);
MPI_Info_set(hints, "ampi_checkpoint", "in_memory");
...
AMPI_Migrate(hints);

```

**Comment by PhilMiller** [comment]
*Original date: 2016-01-21 19:22:11*

---
Your `AMPI_Register_Just_migrated` has a case inconsistency. 'J' should be lower case.

I think there are standard MPI interfaces for accessing the kind of information provided by `AMPI_{my,num}_{pe,node}`. Could we implement those interfaces accordingly?

I agree that the checkpoint routines, if they're to persist, should both state their mechanism. However, I think that in the spirit of an adaptive RTS, we should not have the application logic saying when and how to load balance or checkpoint. I think a single routine `AMPI_Migrate(void)` should actually cover load balancing, checkpointing, and migrate-to. Any controls on its operation should come from RTS launch parameters or some attributes settings controlled far away from the point where the code says "now is a good time to migrate".

**Comment by stwhite91** [comment]
*Original date: 2016-01-21 20:00:06*

---
Thanks, I fixed the case inconsistency.

I don't think there is any standard MPI interface for getting an MPI rank's current PE # or Node #.  We already have built-in keyval attributes on all AMPI communicators (accessed by AMPI_Comm_get_attr), but I'm afraid those attributes are never properly set!  I will check MPICH and OpenMPI, but I think at least OpenMPI's answer is to use hwloc...

I agree on your overall point concerning MPI_Migrate, but we should give users ways to tune the load balancing frequency and checkpoint frequency separately at runtime then.  Also, currently, MPI_Checkpoint() takes a directory path to store the checkpoints in.  That should be made into a runtime option such as:  +checkpoint 'dirname',  to match the existing +restart 'dirname' option or else those two should be combined into one option.

**Comment by PhilMiller** [comment]
*Original date: 2016-01-21 20:07:44*

---
I was thinking of those attributes, yeah. We should make sure they're set as appropriate, rather than adding extra routines.

**Comment by stwhite91** [comment]
*Original date: 2016-01-21 20:42:34*

---
Consensus is that AMPI should have one extension routine for load balancing and all checkpointing schemes, with the user passing in an MPI_Info object to provide 'hints' (like in MPI-IO routines) to the runtime for what it wants: load balance, may checkpoint, must checkpoint, checkpoint to disk, checkpoint in memory, etc. The routine should named something like AMPI_Migrate ...

In general, using MPI attributes and MPI_Info hints are two good strategies for implementing AMPI extensions to MPI. We need to fix the attributes for MyPe, NumPes, etc. and then we can replace MPI_My_pe() with the builtin attribute AMPI_MY_PE on all comms and windows, accessed with: MPI_Comm_get_attr(comm, AMPI_MY_PE, &my_pe, flag). This has been fixed and merged here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1018/~~ https://github.com/UIUC-PPL/charm/commit/e7eabb9eb1b8bbe772a1c1368c6a08e330476478

**Comment by stwhite91** [comment]
*Original date: 2016-02-25 20:15:13*

---
Renaming of all extensions according to the table in my first comment on this issue, changing AMPI_Migrate, updating examples/tests/documentation:
~~https://charm.cs.illinois.edu/gerrit/#/c/1093/~~ https://github.com/UIUC-PPL/charm/commit/d329d24b98f9b0627dc80cd68de18656a27880e4
