### ISSUE TITLE
6.5.0 on ANL BGP systems (Surveyor, Challenger/Intrepid)

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#95]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/95*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:21*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by nikhil-jain** [comment]
*Original date: 2013-03-29 20:37:21*

---
On Challenger/Intrepid - /home/njain/charm-6.5
On Surveyor - /home/njain/charm-6.5 (only xlc versions)

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 20:40:05*

---
I've confirmed that the builds are there and that the permissions are set to allow access. Thanks!
