### ISSUE TITLE
6.5.0 on Titan

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#96]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/96*

---
No body.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 02:10:10*

---
The node-numbering fix for bug #119 has been cherry-picked to the charm-6.5 branch. Please do the builds against that branch.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:22*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-03-29 15:29:37*

---
Two days ago, I build in directory /tmp/charm but today i could not find it. (maybe it is tmp, it is removed). 
Today, i built another in directory /tmp/scratch/charm. We will see whether it will be kept there for a while.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-08 17:00:15*

---
Yanhua: Any progress on identifying a stable location on Titan at which builds of Charm++ can be offered to users? Have you asked the support staff for help if home and project directories are not suitable?

**Comment by mprobson** [comment]
*Original date: 2013-04-08 19:24:36*

---
From Yanhua:

I sent an email to ask. It seems no current directory satisfies our purpose, it is either erased or only to some groups. 

I am still waiting for more reply.

Yanhua

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2013-04-12 15:21:06*

---
After a lot of email to help desk, they confirmed that on Titan they do not reset home directory as before (on Jaguar). 
NOw charm++ is install  ~suny/Charm6.5/charm
