### ISSUE TITLE
Replace CmiEnforce(0) calls in verbs and net layer

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#960]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/960*

---
See [[~~https://charm.cs.illinois.edu/gerrit/#/c/966/~~ https://github.com/UIUC-PPL/charm/commit/2b1bf178d3f5aa58aee732af61a73e7be56e9d22]] for discussion. Copying some relevant bits here.

Phil: All of the 'CmiEnforce(0);' calls should be CmiAbort calls with an associated failure description. It never, ever makes sense to assert or enforce logical false. 

Jim: Yes, they should be, but my goal was to improve the code via low-risk mechanical substitution that would not require testing.  I'm more concerned with CmiAssert being a no-op than a poor error message.

**Comment by minitu** [comment]
*Original date: 2017-02-06 18:00:32*

---
There were CmiEnforce(0) calls in the net layer, so also replaced those.
