### ISSUE TITLE
AMPI support for cancelling recv requests/statuses

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#961]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/961*

---
3 semi-related issues:
1) MPI_Test_cancelled is a no-op
2) MPI_Cancel incorrectly frees requests instead of marking them cancelled
3) MPI_Status_set_cancelled is unimplemented

**Comment by stwhite91** [comment]
*Original date: 2016-03-06 16:44:01*

---
MPI_Status_set_cancelled no-op implementation: ~~https://charm.cs.illinois.edu/gerrit/#/c/1083/~~ https://github.com/UIUC-PPL/charm/commit/3a63347142c478cafdb6374225539f8484f421de

**Comment by stwhite91** [comment]
*Original date: 2016-06-06 03:00:56*

---
No real use case or pressing need for this yet...

To implement, I think we'd need to add a field to MPI_Request (isCancelled?), and set that field if MPI_Cancel is called on a receive op that hasn't completed already, rather than freeing the request as we do now. Then in MPI_{Wait,Test}{any,some,all} we'd need to check for cancelled and do the right thing.

**Comment by stwhite91** [comment]
*Original date: 2016-06-09 20:04:23*

---
Reopen if/when there is a use case.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-11 01:53:42*

---
Fine to mark it low priority, and not planed for an upcoming release. Re-opening, because the issue still exists, and is a real point of non-conformance.

**Comment by PhilMiller** [comment]
*Original date: 2016-09-11 01:54:11*

---
Deassign and mark Unscheduled.

**Comment by PhilMiller** [comment]
*Original date: 2016-11-04 20:29:44*

---
Note that recent moves in the MPI forum suggest deprecating the ability to cancel send requests, since the semantics were ill-defined, and it was essentially never used in applications. So this will only need to apply to receive requests.
