### ISSUE TITLE
multicore segfaults with +p129 due to fixed-size array

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#962]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/962*

---
In src/arch/netlrts/machine.c and src/arch/net/machine.c the inProgress array size is fixed at 128.
This size should be expanded to accomodate machines with high numbers of hardware threads, and ideally allocated (or at least tested) at runtime.

**Comment by jcphill** [comment]
*Original date: 2016-01-22 22:49:41*

---
Same issue in src/arch/verbs/machine.c

**Comment by bilgeacun** [comment]
*Original date: 2016-02-02 17:04:34*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1033/~~ https://github.com/UIUC-PPL/charm/commit/bed4af1a6423921ed52bb06cac281788f97f2523
