### ISSUE TITLE
Runtime flag to silence runtime output

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#963]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/963*

---
We should have a flag (++silent, ++silence, ++quiet, whatever) that suppresses runtime output such as all preamble info and the post-run statement.
Here's a netlrts-linux run without any application print statements. We might not want to advertise this (so we can get it in bug reports) but some users (Intel PRK people for example) might want it.

```
./charmrun  ./hello +p4 10  
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 1.217 seconds.
Charm++> Running in non-SMP mode: numPes 4
Converse/Charm++ Commit ID: v6.7.0-30-g80080fa
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.001 seconds.
[Partition 0][Node 0] End of program

```

**Comment by stwhite91** [comment]
*Original date: 2016-01-23 16:51:46*

---
A practical use case for this flag: HDF5's build system compiles and runs a simple program and then parses the output of that run. Our runtime output breaks their parsing. Obviously we can fix their test, but this feature should exist anyway.

**Comment by juanjgalvez** [comment]
*Original date: 2016-03-02 18:47:41*

---
Fix here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1097/~~ https://github.com/UIUC-PPL/charm/commit/99ffe0aab4e90190b0cdd35c9cccec6710fa5813

Tested on net-linux-[smp], netlrts-linux-[smp][syncft], multicore-linux, mpi-linux-[smp], pamilrts-bluegeneq-xlc

**Comment by juanjgalvez** [comment]
*Original date: 2016-03-04 20:47:42*

---
The solution I have implemented for the runtime is to disable CmiPrintfs during initialization and postrun when ++quiet is passed. NOTE that they are still enabled in the middle of the program execution.

There are many printfs throughout the codebase but it looks to me that most are commented out, printed when something terrible happens and the program is going to abort, printed when in some debug mode, or printed in some rare condition which I don't know if it's ever reached. So I think there's no point going over all of them and converting to CmiPrintf. Instead I have converted the ones which I have seen printed in normal runs on various arch layers.

I see two options:
1) Assuming my commit is correct and once it's been tested thoroughly, go ahead with it and correct any prints which I could have missed in the future as they are discovered.
2) Make an autotest for this, e.g. an empty charm++ program and the test would run it with ++quiet and detect if there is output. But this probably won't detect all possible cases (some output may only be printed when charm is launched with certain options), so not sure it's worth it.

**Comment by stwhite91** [comment]
*Original date: 2016-04-02 13:43:29*

---
Initial commit reverted because it broke netlrts-smp when running without the ++quiet flag. Other lrts-smp layers may also be broken.

~~https://charm.cs.illinois.edu/gerrit/#/c/1126/~~ https://github.com/UIUC-PPL/charm/commit/f642465439e7fa0011244b1b0c7dee5bd0de2ff9
