### ISSUE TITLE
cuda build fails unituitvely on blue waters when cudatoolkit isn't loaded

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#966]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/966*

---

```
./build charm++ gni-crayxe smp cuda
```
 
<code>module load cudatoolkit</code> fixes this but we should bail out very early if we can't find nvcc
This is a longstanding problem in gpuManager
Probably related to some other fixes/bugs

**Comment by minitu** [comment]
*Original date: 2017-01-23 18:06:08*

---
Same thing happens on NCSA nano cluster when no CUDA toolkit directory exists.
Modified build script to bail out as soon as no CUDA toolkit is found.
[[~~https://charm.cs.illinois.edu/gerrit/#/c/2150/~~ https://github.com/UIUC-PPL/charm/commit/632d3a98d54da02a4a64975cda662339df2d1b6f]]
