### ISSUE TITLE
Investigate nightly autobuild failures

### ISSUE THREAD

**Issue by mprobson** [UIUC-PPL/charm#972]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/972*

---
Nightly autobuild has been failing since February 5th, figure out what recently merged patch has caused this

**Comment by juanjgalvez** [comment]
*Original date: 2016-02-15 17:07:49*

---
Some autobuild tests return 'Test on remote host', for example on integrity with net-linux build.
I replicated the same commands as auto build manually on integrity and didn't see any errors or hangs (note that the autobuild script doesn't show any problems either).

So, doing this on integrity works correctly (tests include megatest):

./build LIBS net-linux -j8 --with-production --enable-error-checking 
make test TESTOPTS="++local"

**Comment by juanjgalvez** [comment]
*Original date: 2016-02-15 21:07:10*

---
The issue is that when autobuild runs charm++ tests, some tests processes finish but the process remains in memory.
So the remote ssh session which is running the tests never exits (because it's waiting for these processes to finish).

**Comment by juanjgalvez** [comment]
*Original date: 2016-02-15 21:31:40*

---
Error was caused by commit for bug 962. But we don't know the cause. Removing the free(inProgress) at the end of ConverseExit seems to correct the issue.
