### ISSUE TITLE
multicore: spawn a thread per core by default

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#973]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/973*

---
The multicore builds of Charm++ don't have any big tradeoff space between process and thread count, or diversity in node configuration, etc. When launched without any specification of how many threads to use, I think it should default to launching enough threads to fully subscribe the system, rather than just one.

I could see this maybe being switched on by building `--with-production`, since development work favors explicit control, while deployment favors convenient defaults that don't require knowledgeable user input.

**Comment by PhilMiller** [comment]
*Original date: 2016-02-15 01:30:45*

---
Assign to Eric B initially, since he's working on process launch configuration stuff intensively. If you agree that this is a good idea, implementing it on hwloc or whatever should be quite straightforward for whoever else it gets assigned to.

**Comment by jcphill** [comment]
*Original date: 2016-02-15 03:17:58*

---
Please do not change defaults (or anything else other than debugging assertions) based on the build flags (like --with-production) as this will only confuse people.  If you want control you can backwards-compatibly specify +p <threads>.
If you're going to default to all cpus you should I assume also default to +setcpuaffinity (unless the user specifies +p, in which case default to off as now.)

**Comment by ericjbohm** [comment]
*Original date: 2016-02-15 05:28:47*

---
I agree that this will be fairly easy to implement once hwloc is integrated.  However, changing a default behavior like this may be too surprising.

This would represent a major behavioral discontinuity from the non multicore version.  That one behaves as MPI does, single core by default.  

This change would bring the multicore build into line with the OpenMP approach, which defaults to thread per core. I'm not sure which approach is more likely to lead to more user confusion.

**Comment by evan-charmworks** [comment]
*Original date: 2017-12-19 19:42:24*

---
Yes, this would be trivial to implement with hwloc integrated. Has there been a consensus on whether or not multicore builds should have this change? It would make use a bit easier for users with that configuration, but it would also introduce an inconsistency with all other Charm++ build types.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-16 23:03:06*

---
Bump. Is this something we want to proceed with, and is it important for 6.9.0?

**Comment by stwhite91** [comment]
*Original date: 2018-01-16 23:19:29*

---
Bring it up at the next Core meeting, I don't think there's a consensus

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-19 21:05:28*

---
Consensus from the core meeting:
Leave sequential mode as the default at all times.
Add a parameter in the vein of "++auto-provision" that automatically determines values to fully subscribe provided resources.
When run without flags, print a message suggesting this flag (and potentially others), as well as "+p1" to silence it.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-23 21:43:50*

---
~~https://charm.cs.illinois.edu/gerrit/3565~~ https://github.com/UIUC-PPL/charm/commit/1832a536122ad77c20e51f7bec72fcef8e5297b9

**Comment by stwhite91** [comment]
*Original date: 2018-02-01 05:41:46*

---
++autoProvision provides this behavior, but we decided that the default of no +p option should remain +p1

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-01 17:18:11*

---
~~https://charm.cs.illinois.edu/gerrit/3565~~ https://github.com/UIUC-PPL/charm/commit/1832a536122ad77c20e51f7bec72fcef8e5297b9
