### ISSUE TITLE
Comm Thread Tracing Build Fails

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/charm#977]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/977*

---
As noted in ~~https://charm.cs.illinois.edu/gerrit/#/c/894/~~ https://github.com/UIUC-PPL/charm/commit/904294e5c4000ad2d91daba3c92c90173318f431, the change breaks the build when comm thread tracing is enabled.

**Comment by PhilMiller** [comment]
*Original date: 2016-02-17 18:53:42*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1050/~~ https://github.com/UIUC-PPL/charm/commit/a65b4f461b91a3d6075a5d9546d5c42c3f70df31
