### ISSUE TITLE
Compare the performance of Harshit's accel patch to GPU manager

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#978]
*Original author: Prateek Jindal*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/978*

---
Harshit has a patch for accel: https://charm.cs.illinois.edu/gerrit/#/c/824/3

This needs to be tested and compared with GPU manager.

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 06:00:14*

---
Is this still relevant? If not, close the issue.
