### ISSUE TITLE
charmxi: mismatched module braces leads to confusing error messages.

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/charm#979]
*Original author: Ralf Gunter Corrêa Carvalho*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/979*

---
The following code sample raises a very obscure error message:

`
mainmodule mod {
  mainchare mchare {
    entry mchare(CkArgMsg *m);
  }
`

`
~/p/p/c/t/c/c/tmp ❯❯❯ ~/programming/ppl/charm/bin/charmxi tmp.ci
tmp.ci:5:4-4: error: invalid construct
`

**Comment by PhilMiller** [comment]
*Original date: 2017-12-29 17:48:01*

---
Reassign to Evan based on discussion with Eric B.  Confer on how important this work is to schedule in the near future.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-03 22:38:04*

---
The output of charmxi with the given test case is currently:


```
[PARSE-ERROR] Unexpected/missing token at line 5. Current token being parsed: ''.
```


This is better than the "invalid construct" message in the original report. It's still not the clearest but seems sufficient to get the point across.

**Comment by evan-charmworks** [comment]
*Original date: 2018-01-16 23:09:08*

---
The above message seems a good enough solution to me. I'm closing this. Feel free to re-open if there is disagreement.
