### ISSUE TITLE
Application hangs when load balancer is called with dynamic deletion

### ISSUE THREAD

**Issue by harshithamenon** [UIUC-PPL/charm#981]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/981*

---
No body.

**Comment by harshithamenon** [comment]
*Original date: 2016-02-15 20:05:03*

---
When an object is deleted, the barrier condition may get satisfied. This is not checked currently.

**Comment by PhilMiller** [comment]
*Original date: 2016-02-17 18:55:52*

---
~~https://charm.cs.illinois.edu/gerrit/1056~~ https://github.com/UIUC-PPL/charm/commit/07e2a189b3b1560655bcfd689499f991b0122f7a
