### ISSUE TITLE
Gather reduction operation using Tuple/Set reducers

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#982]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/982*

---
This is CkReduction::set with source identifiers per contribution.

We could have 2 arrays with the same number of elements, one with source indices and one with delimited contributions.
Or we could have a source field in each contribution struct...

**Comment by ericjbohm** [comment]
*Original date: 2016-02-18 17:01:54*

---
this is not a bug, it is a new feature request.

**Comment by stwhite91** [comment]
*Original date: 2016-05-23 18:25:14*

---
This could be implemented using the new Tuple reducer type with two CkReduction::set reducers, one containing the array index of the contributor and the other containing the data contributed. However, this is much less elegant than having a native CkReduction::gather type with gatherElements forming a linked list where each element contains the array index of the contributor, the data size, and the actual data.

**Comment by stwhite91** [comment]
*Original date: 2016-05-27 03:07:00*

---
Steve Hoelle's fix for using set reductions inside tuple reductions: ~~https://charm.cs.illinois.edu/gerrit/#/c/1219/~~ https://github.com/UIUC-PPL/charm/commit/7799d940e6cbe8ee023ff9404be2a5569ebb176e

This enables straightforward implementation of unordered gather operations, which can be reordered as needed on the receiver's side. This is adequate for AMPI's use case, and I don't know of any other current use cases in our applications.

Edit: Eric B expressed interest in a gather operation for OpenAtom. See AMPI_Allgather for the contribution and gatherResult for the ordering of messages by contributor's rank: ~~https://charm.cs.illinois.edu/gerrit/#/c/1220/~~ https://github.com/UIUC-PPL/charm/commit/2154322c8adcfba0683b9cc1d81978f1591f6bdc

**Comment by PhilMiller** [comment]
*Original date: 2016-06-16 16:42:22*

---
We can close this as 'Merged' now, right?

**Comment by stwhite91** [comment]
*Original date: 2016-06-16 16:48:26*

---
I'm fine with closing it, though I think the documentation should be updated for Tuple/Stats reducers, and perhaps an example of a gather (tuple/set) would be useful as a replacement for the current example of set reducers here: http://charm.cs.illinois.edu/manuals/html/charm++/4.html#SECTION01361000000000000000

**Comment by stwhite91** [comment]
*Original date: 2016-08-05 14:31:29*

---
Closing this now since there is an open issue for the documentation, #1140.
