### ISSUE TITLE
Cray regularpages build is broken

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#986]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/986*

---
The regularpages build for Crays was broken by this commit:

~~https://charm.cs.illinois.edu/gerrit/#/c/852/~~ https://github.com/UIUC-PPL/charm/commit/ec5a49b6cba0fd95607cf22deb5a626d228b1fe4

The error happens when linking because gethugepagesize() is not defined anywhere for the regularpages build:
```
$ charmc -o hello hello.o
../../../../bin/../lib/libconv-cplus-y.a(machine.o): In function `LrtsInit':
/u/sciteam/swhite1/charm/gni-crayxe-regularpages/tmp/machine.c:4029: undefined reference to `gethugepagesize'
/usr/bin/ld: link errors found, deleting executable `hello'
collect2: error: ld returned 1 exit status

```

**Comment by bilgeacun** [comment]
*Original date: 2016-03-11 22:34:33*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/1110/~~ https://github.com/UIUC-PPL/charm/commit/e5aa8639ea411e0e9ac266f237fb070f2962b3ac
