### ISSUE TITLE
Entry methods with no parameters can't be called with CkEntryOptions, can't take group construction dependence.

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#987]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/987*

---
Most entry method declarations lead to generated methods on the corresponding CProxy object that include an optional `const CkEntryOptions *opts = NULL` as the last parameter. However, entry methods taking no arguments generate a proxy with a corresponding method that takes no arguments either.

It's clear why it's implemented this way - the code on both send and receive sides would have to be duplicated to choose between working with a zero-payload system message and a dynamically allocated message with room for a priority or whatever else the options might dictate. Nevertheless, it's a somewhat glaring and surprising inconsistency that some entry methods can be passed options, and others can't.

**Comment by nitbhat** [comment]
*Original date: 2016-10-14 02:52:43*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/1916/~~ https://github.com/UIUC-PPL/charm/commit/cdfed762c79ce2062f043c496b5da38821abe579

Earlier entry methods without params such as 

```
entry void foo(); 
```


were created as: 

```
 void foo(void); in decl.h
```
 and 
```
 void foo() {..} in def.h
```


After the fix, CkEntryOptions was added as an optional parameter. 
This creates

```
 void foo(CkEntryOptions *impl_e_opts=NULL) in decl.h 
```
  and 
```
 void foo(CkEntryOptions *impl_e_opts) {..} in def.h 
```

**Comment by stwhite91** [comment]
*Original date: 2016-12-07 20:45:04*

---
The above fix makes the syntax work, but doesn't actually pass CkEntryOptions through the runtime. In the case of priorities, which make no guarantees about scheduling order, this doesn't break any semantic guarantees to the user, but if the user is using CkEntryOptions to set a group dependence, this breaks that promise.

**Comment by nitbhat** [comment]
*Original date: 2017-04-13 18:58:53*

---
Fix: ~~https://charm.cs.illinois.edu/gerrit/#/c/2392/~~ https://github.com/UIUC-PPL/charm/commit/0e3489758fe910cc87b324e696c0ccf778babfe5

Charmxi now spits the code to set group dependency in the envelope for a group's constructor that takes no parameters.
