### ISSUE TITLE
Tutorial codes are not accessible

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#989]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/989*

---

Per https://lists.cs.illinois.edu/lists/arc/charm/2016-02/msg00013.html

The requested URL /tutorial/examples/ParallelPrefix.tar.gz was not found on this server.

The requested URL /tutorial/examples/ParallelPrefix_NoBarrier.tar.gz was not found on this server.

Please contact dongli`lasg.iap.ac.cn when this has been addressed.

**Comment by stwhite91** [comment]
*Original date: 2016-03-15 14:01:55*

---
The links on the charmplusplus tutorial page are correct here: http://charmplusplus.org/tutorial/ParallelPrefix.html

But the email is referencing the tutorial here, where they are broken: https://charm.cs.illinois.edu/tutorial/ParallelPrefix.htm

So you just need to update the links on the illinois page.

**Comment by stwhite91** [comment]
*Original date: 2016-05-02 19:25:53*

---
It looks like this has been fixed

**Comment by pplimport** [comment]
*Original author: Shanna DeSouza*
*Original date: 2016-06-14 16:46:39*

---
The charmplusplus.org version of the tutorial is now updated and the links to the example codes are no longer broken (the folder with examples is now in the repository). The link from charm.cs.illinois.edu/help now takes you to the charmplusplus.org version of the tutorial, which should be the only version online here in the near future.

**Comment by pplimport** [comment]
*Original author: Shanna DeSouza*
*Original date: 2016-06-14 16:50:26*

---
Also, Li Dong had been communicated with back in February and again today.

**Comment by PhilMiller** [comment]
*Original date: 2016-12-22 23:12:45*

---
Confirmed that download links now work.
