### ISSUE TITLE
6.5.0 on Kraken

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#99]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/99*

---
No body.

**Comment by pplimport** [comment]
*Original author: Esteban Meneses*
*Original date: 2013-03-24 21:38:11*

---
BUILDS

1) (OK) ./build AMPI mpi-crayxe -j8 -g

2) (ERROR) ./build AMPI mpi-crayxe -j8 --disable-error-checking -optimize
debug-charm.C: In function 'void CpdBeforeEp(int, void*, void*)':
debug-charm.C:66:57: error: expected primary-expression before ';' token
Fatal Error by charmc in directory /nics/d/home/emenese2/test/charm/mpi-crayxe/tmp
   Command CC -I../bin/../include -D__CHARMC__=1 -I. -O2 -c debug-charm.C -o debug-charm.o returned error code 1

**Comment by PhilMiller** [comment]
*Original date: 2013-03-24 21:43:58*

---
Please investigate what went wrong there, open a descriptive issue, and just fix it, if possible.

**Comment by pplimport** [comment]
*Original author: Esteban Meneses*
*Original date: 2013-03-24 22:16:19*

---
3) (OK) ./build AMPI mpi-crayxe -j8 --with-production

4) (OK) 3) (OK) ./build AMPI mpi-crayxe smp -j8 -g

5) (ERROR) ./build AMPI mpi-crayxe smp -j8 --disable-error-checking -optimize
debug-charm.C: In function 'void CpdBeforeEp(int, void*, void*)':
debug-charm.C:66:57: error: expected primary-expression before ';' token
Fatal Error by charmc in directory /nics/d/home/emenese2/test/charm/mpi-crayxe-smp/tmp
   Command CC -D_REENTRANT -D_REENTRANT -I../bin/../include -D__CHARMC__=1 -I. -O2 -c debug-charm.C -o debug-charm.o returned error code 1

6) (OK) ./build AMPI mpi-crayxe smp -j8 --with-production

**Comment by PhilMiller** [comment]
*Original date: 2013-03-28 03:24:23*

---
The known issues blocking some of these builds (#119, #131) have been dealt with. We want to get everything from the 6.5 release wrapped up so we can announce the installed paths for users. If I don't see an issue complete and a path recorded tomorrow, I'm going to start nagging.

**Comment by PhilMiller** [comment]
*Original date: 2013-04-01 17:08:56*

---
Ping: this was supposed to get done last week. Please complete the missing builds and post the path at which users can find them, so we can close this out.

**Comment by pplimport** [comment]
*Original author: Esteban Meneses*
*Original date: 2013-04-08 21:46:27*

---
  All builds are successful now.

2) (OK) ./build AMPI mpi-crayxe -j8 --disable-error-checking -optimize

5) (OK) ./build AMPI mpi-crayxe smp -j8 --disable-error-checking -optimize

**Comment by PhilMiller** [comment]
*Original date: 2013-04-08 21:52:32*

---
Please get someone else who has current access to Kraken to confirm that they can get to your builds and close this issue.
