### ISSUE TITLE
C++ comments in C code in headers

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/charm#990]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/990*

---
https://lists.cs.illinois.edu/lists/arc/charm/2016-02/msg00010.html

The // prefix comment is not recognized in C89 and should not be used in headers which are not explicitly C++.

Please address this specific case and grep around for other headers that may also have that issue.

**Comment by PhilMiller** [comment]
*Original date: 2016-03-10 20:26:19*

---
This should not take any substantial amount of time. Please clean this up and push a fix.
