### ISSUE TITLE
The Projections interface function 'traceUserSuppliedData()' is undocumented in the manual

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#994]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/994*

---
No body.

**Comment by stwhite91** [comment]
*Original date: 2016-05-27 02:57:33*

---
Assigning to Ronak to delegate...

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:02:11*

---
Setting priority higher because these are easy to fix things that act as paper-cuts to users

**Comment by rbuch** [comment]
*Original date: 2017-04-04 20:09:13*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2354/~~ https://github.com/UIUC-PPL/charm/commit/18e123acd89fc9c3ac60fc4090e3e8563cfdfc76

**Comment by PhilMiller** [comment]
*Original date: 2017-04-10 16:12:33*

---
Note that the commit message gets the bug number wrong. Too late now, though.
