### ISSUE TITLE
autobuild on thrift

### ISSUE THREAD

**Issue by nikhil-jain** [UIUC-PPL/charm#998]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/998*

---
Since thrift is down, autobuild test for clang are not functional. Either bring thrift up, or move the build away to an active system.

**Comment by stwhite91** [comment]
*Original date: 2016-03-10 21:31:20*

---
We want this fixed to test the 6.7.1 release.

**Comment by bilgeacun** [comment]
*Original date: 2016-03-10 21:46:09*

---
I just changed thrift to ambition. Hopefully it'll be fixed after tonight.

**Comment by bilgeacun** [comment]
*Original date: 2016-03-11 14:19:46*

---
Fixed.
