### ISSUE TITLE
netlrts writeableDgrams is never reset to 0

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#999]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/999*

---
In src/arch/netlrts/machine-eth.c CommunicationServerNet():

      if (writeableDgrams) {
        CmiUnlock(Cmi_comm_var_mutex);
        int temp;
        if (0!=(temp=TransmitDatagram())) {
          again=1;
          CmiLock(Cmi_comm_var_mutex);
          writeableDgrams = temp;
          CmiUnlock(Cmi_comm_var_mutex);
        }
      } else CmiUnlock(Cmi_comm_var_mutex);

Note that writeableDgrams = temp only happens if temp != 0.

I assume that this grew out of an attempt to reduce the time holding the lock.

In any case, this defeats my efforts to allow the communication thread to sleep, since CheckSocketsReady sees that writeableDgrams (and writeableAcks) are set and returns immediately reporting that dataskt is writeable.

Related, in standalone mode CheckSocketsReady(int withDelayMs) returns 0 immediately.  If withDelayMs is nonzero it should sleep for that long before returning.

**Comment by jcphill** [comment]
*Original date: 2016-03-02 00:02:08*

---
I think simply inserting an optimistic "writeableDgrams = 0" as below fixes the first issue:

      if (writeableDgrams) {
        writeableDgrams = 0;
        CmiUnlock(Cmi_comm_var_mutex);
        int temp;
        if (0!=(temp=TransmitDatagram())) {
          again=1;
          CmiLock(Cmi_comm_var_mutex);
          writeableDgrams = temp;
          CmiUnlock(Cmi_comm_var_mutex);
        }
      } else CmiUnlock(Cmi_comm_var_mutex);

**Comment by bilgeacun** [comment]
*Original date: 2017-02-06 18:21:05*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/2199~~ https://github.com/UIUC-PPL/charm/commit/f505e76bbf9f3bb3bf3fe621b0180688e5bc7ca8

**Comment by PhilMiller** [comment]
*Original date: 2017-04-04 20:43:04*

---
The part of the above change that wasn't directly addressing this bug got reverted, but the fix for this is solidly in place.
~~https://charm.cs.illinois.edu/gerrit/#/c/2332/~~ https://github.com/UIUC-PPL/charm/commit/8d7644fcf2bbb37dfd2de2ed8cfce2a7198ee89d1
